### PR TITLE
fix: fix clipped placeholder

### LINKED ISSUE #21583: [Bug]: Import token has clipped heading
**Describe the bug**

Clipping on the header for `Import Tokens` when switching to that page

**Expected behavior**

It shouldn't clip

**Screenshots/Recordings**

https://github.com/user-attachments/assets/8c31133f-d78b-4d6b-860f-8f8ccff1e700

**Steps to reproduce**

Going to `Import Tokens` shows clipped heading

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

7.58

**Build type**

None

**Device**

iPhone Max Pro 13

**Operating system**

iOS

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Fix Clipped header

## **Changelog**

CHANGELOG entry: Fixed clipped placeholder header

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/21583

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

https://github.com/user-attachments/assets/9a49df4e-9033-49df-b8e7-0231ee685696

### **After**

https://github.com/user-attachments/assets/ac58a2c4-35a8-436f-a7bd-2bf9e7748f1f

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Simplifies AssetSearch input styling by making TextInput flex and removing dynamic sizing, preventing placeholder clipping; updates related snapshots.
> 
> - **UI**
>   - **AssetSearch (`app/components/UI/AssetSearch/index.tsx`)**: Make `TextInput` use `flex: 1` and remove dynamic height/width state and effect; simplify style props.
> - **Tests**
>   - Update snapshots for `AssetSearch` and `SearchTokenAutocomplete` to reflect input style changes.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 116c29f34d1889a9c4eaea8e805933d6bc0dca41. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/AssetSearch/index.tsx [hunk 1]
```diff
@@ -175,10 +163,7 @@ const AssetSearch = ({ onSearch, onFocus, onBlur, selectedChainId }: Props) => {
 
       <View style={styles.input}>
         <TextInput
-          style={[
-            styles.textInput,
-            { height: inputDimensions, width: inputDimensions },
```
Comment (sahar-fehri) [inline app/components/UI/AssetSearch/index.tsx:180]: TextInput has an explicit width set to 86% (line 181) while its parent is 80% (line 68), causing the placeholder to clip
The TextInput is 86% wide inside a parent 80% container, causing overflow and placeholder clipping.
@salimtb  removing this styling, any idea why it was needed in the first place?

File: app/components/UI/AssetSearch/index.tsx [hunk 2]
```diff
@@ -54,6 +54,7 @@ const createStyles = (colors: any) =>
     textInput: {
       ...fontStyles.normal,
       color: colors.text.default,
+      flex: 1,
```
[the remark this answers is not in the document]
Comment (sahar-fehri) [reply app/components/UI/AssetSearch/index.tsx:51]: Fixed by removing inputDimensions

File: app/components/UI/AssetSearch/index.tsx (hunk 1 above)
Comment (salimtb) [reply app/components/UI/AssetSearch/index.tsx:180]: this is not needed any more , i'm fine to remove it

**Review by salimtb — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by bergarces — APPROVED** [review]
