### PR TITLE
fix: Max balance for dApp erc20 approval

### LINKED ISSUE #13122: [Bug]: Clicking on Max button in approval confirmation results in infinite dapp approval requests
### Describe the bug

When clicking the max button for ERC20 token approval confirmation component, decimals are truncated resulting in an insufficient approval for users that want to swap max

### Expected behavior

That when the user clicks that max button, the users full token amount is approved, not the users full token amount truncated to 4 decimal points 

### Screenshots/Recordings

https://photos.google.com/share/AF1QipPiuxuslgoyjGpquKAE2ErLhyqSZ5BwpmITqPLmNpICSaiJoFa2N4o7QFUUwbMG_Q/photo/AF1QipO5rXf5IqqE5blnsOoaGxbcgGjmFWBvT3eCWJg7?key=bUt5VzlVVl9IQXZCdzI2U0FnT3V0MndQX2JTWVhn

### Steps to reproduce

1. Go To Portfolio Swaps within Mobile app browser
2. Select unapproved ERC20 to swap with token balance that extends past 4 decimal places
3. Click Approve within Portfolio
4. Change approval amount in confirmations screen to max using the max button
5. Approve token
6. Observe that users full balance is not approved

See this address for example 0x4b784C5674f06F0C2060aE1176631c0CA488FDef

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.38.0

### Build type

None

### Device

Unknown

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

When the user clicks "Max" on ERC20 token approvals, the account token balance is set as the spending cap. However, this number is rounded to 5 decimals places, which sometimes results in a value smaller than the actual token balance.

This PR fixes this bug by setting the unrounded account token balance instead.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/13122

## **Manual testing steps**

1. Go to this page...
2.
3.

### **After**

Screenshot 2025-03-06 at 14 00 32

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/component-library/components-temp/CustomSpendCap/CustomSpendCap.tsx [hunk 1]
```diff
@@ -75,8 +76,8 @@ const CustomSpendCap = ({
   };
 
   useEffect(() => {
-    if (maxSelected) setValue(accountBalance);
-  }, [maxSelected, accountBalance]);
+    if (maxSelected) setValue(unroundedAccountBalance || accountBalance);
+  }, [maxSelected, accountBalance, unroundedAccountBalance]);
```
Comment (digiwand) [inline app/component-library/components-temp/CustomSpendCap/CustomSpendCap.tsx:80]:
```suggestion
    if (maxSelected) setValue(unroundedAccountBalance);
  }, [maxSelected, unroundedAccountBalance]);
```

I think we may no longer need accountBalance. Else I think since unroundedAccountBalance may be an empty string, || accountBalance may never be reached

**Review by digiwand — DISMISSED** [review]
added a suggestion to remove conditional

It could also be helpful to add tests to check the full balance is shown

**Review by brianacnguyen — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]
