### PR TITLE
fix: fix swaps button on asset overview page for multichain feature

### LINKED ISSUE #12546: Portfolio view: Swap button unavailable for non-native tokens in All networks view
### Describe the bug

While being on the _All networks_ view and clicking on a non-native token from a different network than the currently selected one,  the _Swap_ button is not available

### Expected behavior

See Swap button

### Screenshots/Recordings

https://github.com/user-attachments/assets/f13ee1d5-f385-47e4-bda8-0db11411869b

### Steps to reproduce

1. Have multiple tokens on multiple networks
2. Switch to _All Networks_ view
3. Click on a non-native token from a different network than the currently selected one
4. Notice _Swap_ button is missing

### Error messages or log output

_No response_

### Detection stage

In beta

### Version

v7.35.1. (1502)

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Pixel 6 Pro - Android 14

### Operating system

Android

### Additional context

QA build

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

When user has "all Networks" selected; and he is on a network that does not support swaps but clicks on a network on a chain that supports swaps. He should be able to see the swaps button

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12546#issuecomment-2536209631

## **Manual testing steps**

1. Click on "All Networks"
2. Switch to a network where swaps is not supported (you can add Scroll or blast from chainlist)
3. Click on a token from ethereum network
4. You should be able to see swaps button

### **After**

https://github.com/user-attachments/assets/af560641-c854-4288-b0cc-231ba450edd3

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Swaps/utils/index.js [hunk 1]
```diff
@@ -40,13 +41,16 @@ if (__DEV__) {
   allowedChainIds.push(...allowedTestnetChainIds);
 }
 
-export function isSwapsAllowed(chainId) {
+export function isSwapsAllowed(chainId, tokenChainId = undefined) {
```
Comment (sahar-fehri) [inline app/components/UI/Swaps/utils/index.js:44]: I saw that this fct is being used elsewhere, wanted to minimize the fix so i made the tokenChainId optional

Comment (bergeron) [reply app/components/UI/Swaps/utils/index.js:44]: Is there a reason it can't continue being a single `chainId` arg?

Comment (vinnyhoward) [reply app/components/UI/Swaps/utils/index.js:44]: I think its because `chainId` refers to the selected chain id. The `tokenChainId` refers to the assets token chain id. I would think the `chainId` would be removed when the feature flag is removed.

Comment (sahar-fehri) [reply app/components/UI/Swaps/utils/index.js]: No reason actually; pushed an update [90fe809](https://github.com/MetaMask/metamask-mobile/pull/12650/commits/90fe809642b8fb9f9e14436e7544229afc1f7d78)

Comment (sahar-fehri) [reply app/components/UI/Swaps/utils/index.js]: Just saw your comment @vinnyhoward ; i think we can make the asset detail page send the asset chainId instead of the chainId; no need to update the isSwapsAllowed function

File: app/components/Views/Asset/index.js [hunk 2]
```diff
@@ -480,7 +481,7 @@ class Asset extends PureComponent {
     const styles = createStyles(colors);
     const asset = navigation && params;
     const isSwapsFeatureLive = this.props.swapsIsLive;
-    const isNetworkAllowed = isSwapsAllowed(chainId);
+    const isNetworkAllowed = isSwapsAllowed(asset.chainId);
```
Comment (vinnyhoward) [inline app/components/Views/Asset/index.js:484]: Shouldn't we have a legacy version of this? And this change to be under feature flag?

Comment (sahar-fehri) [reply app/components/Views/Asset/index.js:484]: I did not think this should affect the old flow; i expect the asset to always have a chainId; and when the user is on the current network or the "old flow" the asset.chainId would equal the currentChainId; wdyt?

Comment (vinnyhoward) [reply app/components/Views/Asset/index.js:484]: `chainId` was introduced recently to support multi chain. You can see the type here
```
export interface TokenI {
  // previous types
  chainId?: string; // recently added for multi chain
  isNative?: boolean;
  ticker?: string;
}
```
The legacy assets won't have that and their `chainId` is derived from the selected chain id selector. So I think we'd need both still? One for regular flow and one feature flag? I could test it here too in a sec

Comment (sahar-fehri) [reply app/components/Views/Asset/index.js:484]: Good point; can update this with a feature flag in this case

Comment (sahar-fehri) [reply app/components/Views/Asset/index.js]: updated here [3233475](https://github.com/MetaMask/metamask-mobile/pull/12650/commits/3233475d99bd09849c6c7884d2f194f52af87cf1)

**Review by vinnyhoward — APPROVED** [review]
LGTM!

**Review by bergeron — APPROVED** [review]

**Review by gambinish — APPROVED** [review]

**Review by infiniteflower — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
LGTM
