### PR TITLE
fix: main balance formatting

### LINKED ISSUE #13638: [Bug]: Display second decimal on rounded total balances
### Describe the bug

If a user fiat total is $42.50", the total will display in the aggregated balance as "$42.5".  Fiat usually always displays at least two decimal places, so let's do that.

### Expected behavior

_No response_

### Screenshots/Recordings

Image

### Steps to reproduce

1.  By luck have an aggregated balance with a rounded decimal number.

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.40

### Build type

None

### Device

iPhone

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gambinish**
## **Description**

On mobile, we've had a bug where if the aggregated balance of someone's wallet was rounding to the tenths decimal place rather than the hundredths.

If the balance in `10.1` the aggregated fiat balance should read `$10.00 USD` rather than `$10.1`

We are leveraging the `formatWithThreshold` utility, which we've been using on extension for a while. I would like to begin integrating this throughout both codebases, and hope to outline this plan in an ADR shortly. It might be worth it to consolidate this function into core.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/13638

## **Manual testing steps**

1. Go to this page...
2.
3.

### **Before**

rounding-bug

### **After**

Screenshot 2025-03-04 at 10 39 38 AM

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx [hunk 1]
```diff
@@ -145,7 +147,8 @@ export const PortfolioBalance = React.memo(() => {
               testID={WalletViewSelectorsIDs.TOTAL_BALANCE_TEXT}
               variant={TextVariant.DisplayMD}
             >
-              {multichainBalances.displayBalance}
+              {multichainBalances.displayBalance}{' '}
+              {currentCurrency.toUpperCase()}
```
Comment (owencraston) [inline app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx:151]: IMO the `multichainBalances.displayBalance` should already have the current currency formatted along with the correct decimals.

Comment (gambinish) [reply app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx:151]: I thought about this also. The problem is that the `AccountNetworkInfo` component also uses this hook, but based on what I'm seeing, it doesn't show the currency symbol.

Should we change this behavior? Or should we update the hook to handle both cases? Having it added here felt like the simplest thing, but we can change it up if we want to.

Comment (owencraston) [reply app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx:151]: after speaking on slack we decided to return the currentCurrency from the hook. the result should look something like this...

```
`${multichainBalances.displayBalance} ${multichainBalances.displayCurrency}`
```

Comment (gambinish) [reply app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx]: Change we discussed about is here: https://github.com/MetaMask/metamask-mobile/pull/13818/commits/28cc8e9a679d0c57a5c52a703cc58ed99ef4e01d

File: app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx [hunk 2]
```diff
@@ -145,7 +145,8 @@ export const PortfolioBalance = React.memo(() => {
               testID={WalletViewSelectorsIDs.TOTAL_BALANCE_TEXT}
               variant={TextVariant.DisplayMD}
             >
-              {multichainBalances.displayBalance}
+              {multichainBalances.displayBalance}{' '}
```
Comment (owencraston) [inline app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx:148]: Nit: 

```
`${multichainBalances.displayBalance} ${multichainBalances.displayCurrency}`
```

**Review by owencraston — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by OGPoyraz — APPROVED** [review]
