### PR TITLE
fix: use correct order for BTC network and fees cp-7.59.0

### LINKED ISSUE #22314: [Bug]: Incorrect network ordering + fees
### Describe the bug

Currently, BTC network placement and fees are incorrect. After discussion with product, this has been considered a critical priority as it'll have the potential to risk revenue for the specific network.

### Expected behavior

BTC to be placed in correct order and fiat fees to be formatted correctly.

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Go to swaps
2. See BTC being placed last in the horizontal scroll
3. See fees showing as 0 due to the use of the crypto instead of the fiat value

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.59.0

### Build type

None

### Device

iPhone 13 Pro

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by SteP-n-s**
## **Description**

Fix issue with incorrect network order & fees

## **Changelog**

CHANGELOG entry: fix incorrect network order and fees

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/22314

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **After**

https://github.com/user-attachments/assets/907764f2-695e-4cda-bda8-eaee609fc562

simulator_screenshot_AC60FBFE-5FB0-488D-97F1-9D16106F285E

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Sorts destination networks by popularity with BTC included and standardizes network fee display to fiat, with updated tests and e2e adjustments.
> 
> - **Bridge UI**
>   - **Network ordering**: Export and use `ChainPopularity` to sort destination networks; add BTC (`BtcScope.Mainnet`) and adjust rankings; fallback to `Infinity` for unknown chains.
>   - **Dest selector**: Apply popularity sort in `BridgeDestNetworkSelector` (excludes current chain unless Unified mode).
>   - **Snapshots/Tests**: Update snapshots to reflect new order; add test for popularity fallback.
> - **Quote Data**
>   - **Fees**: Always format `networkFee` using fiat `valueInCurrency` (handles `<$0.01`, `$0`, and missing values as `-`); remove primary-currency/ticker-based formatting.
>   - **Unit Tests**: Update and expand tests to cover new fee formatting cases and edge conditions.
> - **E2E**
>   - Adjust `swipeNetwork` to target updated ordering.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit fc761a6adc85b09e363589937ff8548140c065fa. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/Bridge/hooks/useBridgeQuoteData/index.ts [hunk 1]
```diff
@@ -123,20 +119,12 @@ export const useBridgeQuoteData = ({
...
-      maximumFractionDigits: 6,
-    });
-    const formattedAmount = `${networkFeeFormatter.format(
-      Number(amount),
-    )} ${ticker}`;
     const formattedValueInCurrency = fiatFormatter(
       new BigNumber(valueInCurrency),
     );
 
-    return primaryCurrency === 'ETH'
```
Comment (bfullam) [inline app/components/UI/Bridge/hooks/useBridgeQuoteData/index.ts:136]: What's the intent here? Do we want to just always show network fees in fiat now and if so, why? Seems like we'd want to maintain the user preference from settings on whether to have the primary currency be fiat or some other denomination.

Comment (SteP-n-s) [reply app/components/UI/Bridge/hooks/useBridgeQuoteData/index.ts:136]: We’re removing the crypto representation of network fees based on [this](https://consensyssoftware.atlassian.net/browse/SWAPS-3380) product requirement.

**Review by micaelae — APPROVED** [review]
