### PR TITLE
make null conversionRate safe

### LINKED ISSUE #9492: Custom network incorrect account balance when symbol is left blank.
**Describe the bug**
When a custom network symbol that we optionally take is left blank we assume it is an ETH network. So then we apply the ETH conversion rate to getBalance. This is easily result in users thinking they have more funds they they actually do when viewing their balance. The max amount in the send field will show the correct amount. 

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Add the xDai network, steps are [xDai MetaMask setup](https://www.xdaichain.com/for-users/wallets/metamask/metamask-setup)
2. Omit the asset symbol which we say is optional
3. The current conversion rate of ETH should times the balance we get from the network and apply the ETH suffix to the value.

**Expected behavior**
Either require the network symbol field to prevent this behavior, or when on a network other than the defaults do not apply the conversionRate to it.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by adonesky1**
**Description**
The goal of this PR is to enable this [controller's repo PR](https://github.com/MetaMask/controllers/pull/465) to merge which will stop us from using stale conversionRates when a user input native currency is invalid for a custom network. 

I have a PR open in the extensions repo to handle the possible null conversionRate that the change in the controller's repo makes possible. Here I'm adding a temporary measure (that should be iterated on) to avoid issues that could arise from null conversionRates.

The only place I was able to find an issue from modifying CurrencyRateController state was in Number.js where we were dividing by the conversionRate which caused a result of infinity. I've added a patch for this. If someone knows of other potential issues that I've missed please let me know!

Partially Resolves [#9492](https://github.com/MetaMask/metamask-extension/issues/9492) & [#10785
](https://github.com/MetaMask/metamask-extension/issues/10785)

### CODE REVIEW

File: app/core/Engine.js [hunk 1]
```diff
@@ -308,7 +308,9 @@ class Engine {
 			TokenRatesController
 		} = this.context;
 		const { selectedAddress } = PreferencesController.state;
-		const { conversionRate, currentCurrency } = CurrencyRateController.state;
+		const { currentCurrency } = CurrencyRateController.state;
+		const conversionRate =
```
Comment (estebanmino) [inline app/core/Engine.js:312]: any reason to not getting `conversionRate` from the destructuring above? then 
```
const conversionRate = conversionRate === null ? 0 : conversionRate
```

Comment (adonesky1) [reply app/core/Engine.js:312]: I might be misunderstanding your comment but if I destructure conversionRate I can't declare it again. And I can't reassign it because it is readonly.

Comment (adonesky1) [reply app/core/Engine.js:312]: Could do:
`const { currentCurrency, conversionRate } = CurrencyRateController.state;
		const modifiedConversionRate = conversionRate === null ? 0 : conversionRate;`

Comment (adonesky1) [reply app/core/Engine.js:312]: @estebanmino ^

Comment (adonesky1) [reply app/core/Engine.js:312]: @estebanmino ^

Comment (estebanmino) [reply app/core/Engine.js:312]: oh yes, you're right!

**Review by estebanmino — APPROVED** [review]
👌

**Comment by adonesky1** [comment]
@estebanmino any idea why the CI process is stalling?

**Comment by adonesky1** [comment]
or @rickycodes^ ?
