### PR TITLE
fix: blockaid validations are not being flagged in re-designed signature request pages

### LINKED ISSUE #13068: [Bug]: Malicious permits are not flagged
### Describe the bug

Malicious permits and Sign permit are not flagged

### Expected behavior

Malicious permits are flagged by Blockaid

### Screenshots/Recordings

https://github.com/user-attachments/assets/61edc819-0493-4305-a40c-c0d95c9f6bf6

### Steps to reproduce

1. Connect to[ test dapp](https://metamask.github.io/test-dapp/)
2. Submit any Malicious permit or Sign permit

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

v7.39.0(1529)

### Build type

None

### Device

iPhone 15

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

fix for blockaid validations are not being flagged in re-designed signature request pages

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/13068

## **Manual testing steps**

1. To to test dapp
2. Submit malicious permit
3. Check blockaid banner on the page

## **Screenshots/Recordings**
Screenshot 2025-01-21 at 11 24 39 PM

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/confirmations/selectors/security-alerts.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import { SecurityAlertResponse } from '@metamask/transaction-controller';
+import { RootState } from '../../../../reducers';
+
+export const selectSignatureSecurityAlertResponse = (
+  rootState: RootState,
+): { securityAlertResponse: SecurityAlertResponse } =>
+  rootState.signatureRequest;
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/selectors/security-alerts.ts:7]: We can move this to the `SignatureController` in future via a `updateSecurityAlertResponse` method but a selector for this for now is great.

File: app/components/Views/confirmations/hooks/useSecurityAlertResponse.ts [hunk 2]
```diff
@@ -0,0 +1,12 @@
+import { useSelector } from 'react-redux';
+
+import { selectSignatureSecurityAlertResponse } from '../selectors/security-alerts';
+
+// todo: the hook to be extended to include transactions
+export function useSecurityAlertResponse() {
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/hooks/useSecurityAlertResponse.ts:6]: ❤️

**Review by matthewwalsh0 — APPROVED** [review]

File: app/components/Views/confirmations/selectors/security-alerts.ts (hunk 1 above)
Comment (jpuri) [reply app/components/Views/confirmations/selectors/security-alerts.ts:7]: Yep I will create a task for this. I was actually expecting that this is already done on mobile also and that caused this issue with re-designs.

Comment (OGPoyraz) [reply app/components/Views/confirmations/selectors/security-alerts.ts:7]: Just for the note, if you create ticket let's double it for extension as well
https://consensys.slack.com/archives/C070G0RCX0T/p1737015853322059

**Review by OGPoyraz — APPROVED** [review]
