### PR TITLE
fix: anonymous props that's not moved to sensitive props

### LINKED ISSUE #12728: [Bug]: getAnalyticsParams return anonymous props that's not moved to sensitive props
### Describe the bug

See https://github.com/MetaMask/metamask-mobile/blob/a59756873da17fc420f8f14d27c267224a2097ac/app/components/Views/confirmations/components/ApproveTransactionReview/index.js#L582-L586

### Expected behavior

- Have two events for `Approval Started`: anon and non-anon
- Do not have the `number_tokens_requested` prop in non-anon event props
- Have the `number_tokens_requested` prop in anon event sensitive props

### Screenshots/Recordings

_No response_

### Steps to reproduce

- View the tx approval screen
- check `Approval Started` event props
- no anonymous event, only one non anonymous one but it contains `number_tokens_requested`

### Error messages or log output

n/a

### Detection stage

On main branch

### Version

main

### Build type

None

### Device

any

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by NicolasMassart**
## **Description**

Add a legacy compatible process in the addProperties function to handle the object props that contains a `anonymous: true` and move them to sensitiveProperties instead.

It was planned that code would use addSensistive properties, but sometimes, we get some mixed props from places like a getAnalyticsParams function that returns a lot props and passes them along far before the event is built.
It would require a too big refactoring to split these props at the source.
I decided to add a new processing in the addProperties directly to filter anonymous props passed as normal props and redirect them.

Even if this new additional processing is executed for all the addProperties calls, it is not adding enough processing time to negatively impact performances.

## **Related issues**

Fixes https://github.com/MetaMask/metamask-mobile/issues/12728

>[!NOTE]
> This fixes props for when events are not properly polulated, but ideally they are, and some effort to fix how eventsa re populated have been made in #12532

## **Manual testing steps**

1. View the tx approval screen
2. check `Approval Started` event props
3. generates both a non-anonymous and an anonymous event.
4. Only anonymous event contains `number_tokens_requested`

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/Analytics/MetricsEventBuilder.ts [hunk 1]
```diff
@@ -77,15 +77,45 @@ class MetricsEventBuilder {
     return new MetricsEventBuilder(event);
   }
 
+  #getFilteredLegacyProperties = (properties: JsonMap) => {
+    const [filteredProps, anonymousProps] = Object.entries(properties).reduce(
```
Comment (Cal-L) [inline app/core/Analytics/MetricsEventBuilder.ts:81]:
```suggestion
    const filteredProps: JsonMap = {};
const anonymousProps: JsonMap = {};

for (const [key, value] of Object.entries(properties)) {
  if (
    value !== null && 
    typeof value === 'object' && 
    'anonymous' in value &&
    value.anonymous === true
  ) {
    anonymousProps[key] = value.value;
  } else {
    filteredProps[key] = value;
  }
}

return [filteredProps, anonymousProps];
```

Save on performance by removing reduce

**Review by Cal-L — COMMENTED** [review]
Left a comment

**Comment by Cal-L** [comment]
Are the E2E failures from this branch or main?

**Review by joaoloureirop — APPROVED** [review]
lgtm

**Comment by NicolasMassart** [comment]
PR reverted because of e2e tests failing because of it
