### PR TITLE
Clicking toAddress to add it to address book

### LINKED ISSUE #6008: [Bug] Recipient Address component not clickable nor able to be added to the Address Book
**Describe the bug**
The Recipient Address component is not clickable nor allows to be added to the Address Book. 
Screens affected are both with Sends/Transfers from inside MetaMask and external dapp transactions.

**Screenshots**

https://user-images.githubusercontent.com/54408225/226701059-deb430f2-5a4f-4857-9b7b-9c87bfebf9cf.mp4

**To Reproduce**
_Steps to reproduce the behavior_

**Case 1**: Regular Send/Transfer from inside MetaMask (this applies to all assets: ETH, ERC20, ERC721..)

1.Click Send from inside MetaMask
2. Add any recipient address and proceed
3. Add any amount and proceed
4. See how recipient address is not clickable nor able to be added to the address book

**Case 2**: Transaction coming from a dapp
1. Go to test dapp
2. Connect MM
3. Click Send EIP1159
4. See how recipient address is not clickable nor able to be added to the address book

**Expected behavior**
Recipient Address should be clickable and then added to the address book.
This is already done on [Verify Contract](https://github.com/MetaMask/MetaMask-planning/issues/179) details feature, so the implementation could be re-used.

**Note**: this issue can be fixed after [Address component refactor PR](https://github.com/MetaMask/metamask-mobile/pull/5900) is merged

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: v6.1.2

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by jpuri**
Fixes: #6008 

A reusable component is created to wrap child elements, the child elements when clicked will trigger add-to-address-book modal to open.

QA steps:
Add to address book works well at:
- send page where to address is selected
- confirm send page
- any DAPP transaction

### CODE REVIEW

File: app/components/UI/AddToAddressBookWrapper/AddToAddressBookWrapper.tsx [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+    AddressBookController.set(address, alias, network);
+    setAlias(undefined);
+  };
+
+  return (
+    <>
+      <TouchableOpacity
+        activeOpacity={0.5}
+        onPress={() => setShowAddToAddressBook(true)}
+        testID={'add-address-button'}
```
Comment (blackdevelopa) [inline app/components/UI/AddToAddressBookWrapper/AddToAddressBookWrapper.tsx:56]: nit: should we make this a constant? Will be nice.

File: app/components/UI/AddToAddressBookWrapper/AddToAddressBookWrapper.tsx [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+      >
+        {children}
+      </TouchableOpacity>
+      {showAddToAddressBook && (
```
Comment (blackdevelopa) [inline app/components/UI/AddToAddressBookWrapper/AddToAddressBookWrapper.tsx:60]: can we use `?` instead of `&&`. [See](https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx)

File: app/components/hooks/useExistingAddress.test.ts [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+describe('useExistingAddress', () => {
+  it('should return existing address from identities', async () => {
+    const { result } = renderHook(() => useExistingAddress('0x0'));
+    expect(result?.current?.name).toEqual('Account 1');
+  });
+  it('should return existing address from address book', async () => {
+    const { result } = renderHook(() => useExistingAddress('0x1'));
+    expect(result?.current?.name).toEqual('Account 2');
+  });
+  it('should return undefined for unknown address', async () => {
```
Comment (blackdevelopa) [inline app/components/hooks/useExistingAddress.test.ts:50]: nit: what's unknown address?

**Review by blackdevelopa — COMMENTED** [review]
LGTM. Just left small nit

File: app/components/UI/AddToAddressBookWrapper/AddToAddressBookWrapper.tsx (hunk 1 above)
Comment (jpuri) [reply app/components/UI/AddToAddressBookWrapper/AddToAddressBookWrapper.tsx:56]: done

**Review by blackdevelopa — DISMISSED** [review]

**Review by segun — DISMISSED** [review]

**Comment by seaona** [comment]
## Address saved not rendered on ERC20 Token Transfers
Whenever I am sending an ERC20 token, I can see how clicking toAddress allows me to save the address, but whenever I save it, the Account name is not displayed. It is still displayed the address.

**Repro**
1. Go to test dapp
2. Click Create Token for deploying an ERC20 Token
3. Add token to Wallet
4. Click Transfer 
5. Click `toAddress`
6. Save an account name
7. See how the address is still displayed

This also happens if I try to Send the token from inside MetaMask instead of the dapp.
If I check the address book, I can see how the address has been saved correctly.

https://user-images.githubusercontent.com/54408225/233589551-5c867b51-4930-427e-8e17-975933c5d13d.mp4

## Add to Address Book does not open with ERC721 Sends
Whenever we are trying to send an ERC721 token, when I am on the Confirmation screen, clicking the To Address does not open the Add to Address Book modal.

[erc721-address-not-open.webm](https://user-images.githubusercontent.com/54408225/233592454-4aae76ff-bb01-4669-b96b-2ece715cd0fc.webm)

Since there is [another issue related to SEnd erc721](https://github.com/MetaMask/mobile-planning/issues/911), it might have some effect on what I am seeing, so maybe after this issue is fixed, this one will be resolved 

**Repro**
1. Go to test dapp
2. Deploy Collectibles contract
3. Mint a token
4. Go to the Wallet
5. Click NFTs tab
6. Add the NFT you just minted
7. Click the NFT
8. Click Send
9. Add a recipient
10. Proceed
11. On the last confirmation screen, click To Address -- see nothing happens

## Add to Address Book with ERC1155 Sends
Pending to test, as need[ there is an issue](https://github.com/MetaMask/mobile-planning/issues/912) that should be resolved first, otherwise I cannot import any ERC1155 adn test it.

**Comment by jpuri** [comment]
@seaona : PR is updated with fix, can you plz re-test.

**Comment by seaona** [comment]
@jpuri I see the issues fixed! I've checked the ERC721 in Mainnet since I couldn't import tokens manually due to the previous known issue.
I could use the auto-detect NFTs for doing overcoming it.

**Review by segun — APPROVED** [review]
LGTM

**Review by blackdevelopa — APPROVED** [review]
