### PR TITLE
fix: sanitize seedless controller state  - cp-7.53.0

### LINKED ISSUE #18317: [Bug]: Sanatize SeedlessOnboardingController state for download log state
### Describe the bug

This issue is related to specific SeedlessOnboardingController state that should not be persisted for downloading of logs. 

### Expected behavior

Sensitive state should not be persisted. 

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Open RC app and login using social login.
2. Download state logs 
3. See persisted data

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.53.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

All

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

Not device specific

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ieow**
## **Description**
Sanatize SeedlessOnboardingController state for download log state

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes:
https://github.com/MetaMask/pm-security/issues/484
## **Manual testing steps**

```gherkin
Feature: Sanitize SeedlessControllerState

  Scenario: downloaded state logs should have sanitized seedlessOnboarding Controller state
    Given user created wallet with seedless wallet
    When user download state logs
    Then download logs should only have sanitized seedlessOnboarding Controller state
```

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/logs/index.ts [hunk 1]
```diff
@@ -13,6 +13,38 @@ import { RootState } from '../../reducers';
...
+    ),
+    encryptedKeyringEncryptionKey: Boolean(
+      SeedlessOnboardingController.state.encryptedKeyringEncryptionKey,
+    ),
+    metadataAccessToken: Boolean(
+      SeedlessOnboardingController.state.metadataAccessToken,
+    ),
+    accessToken: Boolean(SeedlessOnboardingController.state.accessToken),
+    refreshToken: Boolean(SeedlessOnboardingController.state.refreshToken),
+    revokeToken: Boolean(SeedlessOnboardingController.state.revokeToken),
```
Comment (matthiasgeihs) [inline app/util/logs/index.ts]: Hm, why do you include these variables as booleans?
Normally (see KeyringController), we would simply delete the sensitive items from the state.

I can also see that this might lead to confusion downstream, as the variables are there, but contain unexpected values.

File: app/util/logs/index.ts [hunk 2]
```diff
@@ -25,6 +57,7 @@ export const generateStateLogs = (state: any, loggedIn = true): string => {
   delete fullState.engine.backgroundState.PhishingController;
   delete fullState.engine.backgroundState.AssetsContractController;
   delete fullState.engine.backgroundState.DeFiPositionsController;
+  delete fullState.engine.backgroundState.SeedlessOnboardingController;
```
Comment (matthiasgeihs) [inline app/util/logs/index.ts:91]: Would be great if you could add a similar comment above this line as was done for the KeyringController.

File: app/util/logs/index.ts [hunk 3]
```diff
@@ -13,6 +13,38 @@ import { RootState } from '../../reducers';
...
+      SeedlessOnboardingController.state.encryptedKeyringEncryptionKey,
+    ),
+    metadataAccessToken: Boolean(
+      SeedlessOnboardingController.state.metadataAccessToken,
+    ),
+    accessToken: Boolean(SeedlessOnboardingController.state.accessToken),
+    refreshToken: Boolean(SeedlessOnboardingController.state.refreshToken),
+    revokeToken: Boolean(SeedlessOnboardingController.state.revokeToken),
+  };
+};
```
[the remark this answers is not in the document]
Comment (matthiasgeihs) [reply app/util/logs/index.ts:75]: @ieow please respond here. is this an actual issue?

File: app/util/logs/index.ts (hunk 1 above)
Comment (matthiasgeihs) [reply app/util/logs/index.ts]: `socialBackupsMetadata` is missing here. Is this intended? If so, why?

Comment (matthiasgeihs) [reply app/util/logs/index.ts]: `nodeAuthTokens` is missing here. Is this intended? If so, why?

File: app/util/logs/index.ts [hunk 4]
```diff
@@ -13,6 +13,38 @@ import { RootState } from '../../reducers';
...
 import { MetaMetrics } from '../../core/Analytics';
 
+const getSanitizedSeedlessOnboardingControllerState = () => {
+  const { SeedlessOnboardingController } = Engine.context;
+  return {
+    userId: SeedlessOnboardingController.state.userId,
+    isSeedlessOnboardingUserAuthenticated:
+      SeedlessOnboardingController.state.isSeedlessOnboardingUserAuthenticated,
+    passwordOutdatedCache:
+      SeedlessOnboardingController.state.passwordOutdatedCache,
```
Comment (matthiasgeihs) [inline app/util/logs/index.ts]: Several fields from `AuthenticatedUserDetails` are missing. (e.g., `authConnection`, `authConnectionId`, `socialLoginEmail`, ...)

Comment (matthiasgeihs) [reply app/util/logs/index.ts]: `authPubKey` from `SRPBackedUpUserDetails` is missing

File: app/util/logs/index.ts (hunk 1 above)
Comment (ieow) [reply app/util/logs/index.ts]: I think it is helpful in debugging when these parameters are indicated present or absent of the data.
These parameter could help to determine the state of the controller if there are errors happening
for example the refresh revoke token case.

The other parameters are missed out as I didn't notice the & typing.
will add those parameters as well

File: app/util/logs/index.ts (hunk 4 above)
Comment (ieow) [reply app/util/logs/index.ts]: added

File: app/util/logs/index.ts (hunk 2 above)
Comment (ieow) [reply app/util/logs/index.ts:91]: added

File: app/util/logs/index.ts [hunk 5]
```diff
@@ -13,6 +13,63 @@ import { RootState } from '../../reducers';
...
+        keyringId,
+        type,
+      };
+    }),
+
+    // return node index only
+    nodeAuthTokens: (nodeAuthTokens ?? []).map((item) => {
+      const { nodeIndex } = item ?? {};
+      return nodeIndex;
+    }),
```
Comment (matthiasgeihs) [inline app/util/logs/index.ts]: we should include the node pub key as well for debugging

File: app/util/logs/index.ts (hunk 1 above)
Comment (matthiasgeihs) [reply app/util/logs/index.ts]: ok

File: app/util/logs/index.ts (hunk 4 above)
Comment (matthiasgeihs) [reply app/util/logs/index.ts]: `authConnectionId` is still missing

File: app/util/logs/index.ts [hunk 6]
```diff
@@ -13,6 +13,63 @@ import { RootState } from '../../reducers';
...
+    vaultEncryptionKey,
+    vaultEncryptionSalt,
+    encryptedSeedlessEncryptionKey,
+    encryptedKeyringEncryptionKey,
+    metadataAccessToken,
+    accessToken,
+    refreshToken,
+    revokeToken,
+    authPubKey,
+  } = SeedlessOnboardingController.state ?? {};
```
Comment (matthiasgeihs) [inline app/util/logs/index.ts]: `authConnectionId` is missing

File: app/util/logs/index.ts [hunk 7]
```diff
@@ -13,6 +13,63 @@ import { RootState } from '../../reducers';
...
+    vault: Boolean(vault),
+    vaultEncryptionKey: Boolean(vaultEncryptionKey),
+    vaultEncryptionSalt: Boolean(vaultEncryptionSalt),
+    encryptedSeedlessEncryptionKey: Boolean(encryptedSeedlessEncryptionKey),
+    encryptedKeyringEncryptionKey: Boolean(encryptedKeyringEncryptionKey),
+    metadataAccessToken: Boolean(metadataAccessToken),
+    accessToken: Boolean(accessToken),
+    refreshToken: Boolean(refreshToken),
+    revokeToken: Boolean(revokeToken),
+    authPubKey: Boolean(authPubKey),
```
Comment (matthiasgeihs) [inline app/util/logs/index.ts]: Why do you sanitize the `authPubKey`?

**Review by matthiasgeihs — DISMISSED** [review]

File: app/util/logs/index.test.ts [hunk 8]
```diff
@@ -46,6 +46,21 @@ jest.mock('../../core/Engine', () => ({
...
+      state: {
+        userId: 'userId',
+        isSeedlessOnboardingUserAuthenticated: true,
+        socialBackupsMetadata: [
+          {
+            type: 'google',
+            keyringId: 'keyring1',
+            hash: 'should not be in logs',
+          },
+          null,
```
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts]: why add `null` here? this is not a valid value for this state item.

File: app/util/logs/index.test.ts [hunk 9]
```diff
@@ -46,6 +46,21 @@ jest.mock('../../core/Engine', () => ({
...
+        ],
+        nodeAuthTokens: [{ nodeIndex: 1 }, { nodeIndex: 2 }, null],
```
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts]: why add `null` here? this is not a valid value for this state item.

File: app/util/logs/index.ts (hunk 5 above)
Comment (ieow) [reply app/util/logs/index.ts]: added

File: app/util/logs/index.test.ts (hunk 8 above)
Comment (ieow) [reply app/util/logs/index.test.ts]: to hit the coverage which test the `??` condition 
that resolve comment from cursorbot
https://github.com/MetaMask/metamask-mobile/pull/18299/commits/589f84d84e7ce2559c1574a3269d6b9da5601f79

File: app/util/logs/index.test.ts (hunk 9 above)
Comment (ieow) [reply app/util/logs/index.test.ts]: to hit the coverage which test the ?? condition
that resolve comment from cursorbot
https://github.com/MetaMask/metamask-mobile/commit/589f84d84e7ce2559c1574a3269d6b9da5601f79

File: app/util/logs/index.ts (hunk 7 above)
Comment (ieow) [reply app/util/logs/index.ts]: un-sanitized

File: app/util/logs/index.ts (hunk 6 above)
Comment (ieow) [reply app/util/logs/index.ts]: added

File: app/util/logs/__snapshots__/index.test.ts.snap [hunk 10]
```diff
@@ -446,7 +446,33 @@ exports[`logs :: generateStateLogs generates a valid json export 1`] = `
...
+        "isSeedlessOnboardingUserAuthenticated": true,
+        "metadataAccessToken": false,
+        "nodeAuthTokens": [
+          {
+            "nodeIndex": 1,
+          },
+          {
+            "nodeIndex": 2,
+          },
+          {},
```
Comment (matthiasgeihs) [inline app/util/logs/__snapshots__/index.test.ts.snap:463]: For my understanding: This empty object is the result of applying state sanitization to `null`, correct?

File: app/util/logs/__snapshots__/index.test.ts.snap [hunk 11]
```diff
@@ -446,7 +446,33 @@ exports[`logs :: generateStateLogs generates a valid json export 1`] = `
...
+        ],
+        "refreshToken": false,
+        "revokeToken": false,
+        "socialBackupsMetadata": [
+          {
+            "keyringId": "keyring1",
+            "type": "google",
+          },
+          {},
```
Comment (matthiasgeihs) [inline app/util/logs/__snapshots__/index.test.ts.snap:472]: For my understanding: This empty object is the result of applying state sanitization to `null`, correct?

File: app/util/logs/index.test.ts
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts:1]: Where are we testing that the SeedlessOnboardingController state has been sanitized?

File: app/util/test/initial-background-state.json
Comment (matthiasgeihs) [inline app/util/test/initial-background-state.json:1]: Do we need to add the other state values here?

File: app/util/logs/index.ts [hunk 12]
```diff
@@ -13,6 +13,69 @@ import { RootState } from '../../reducers';
...
+    // Return Boolean for state availablity of sensitive data
+    vault: Boolean(vault),
+    vaultEncryptionKey: Boolean(vaultEncryptionKey),
+    vaultEncryptionSalt: Boolean(vaultEncryptionSalt),
+    encryptedSeedlessEncryptionKey: Boolean(encryptedSeedlessEncryptionKey),
+    encryptedKeyringEncryptionKey: Boolean(encryptedKeyringEncryptionKey),
+    metadataAccessToken: Boolean(metadataAccessToken),
+    accessToken: Boolean(accessToken),
+    refreshToken: Boolean(refreshToken),
+    revokeToken: Boolean(revokeToken),
```
Comment (NEllusion) [inline app/util/logs/index.ts:73]: Can we add a test that ensures these are always booleans and never any other value?

Comment (ieow) [reply app/util/logs/index.ts:73]: Added Testcases here
https://github.com/MetaMask/metamask-mobile/pull/18299/files#diff-211eb929237232cdcc4f6035d8ff35307a6337089abe12ace4890e591f900accR442

File: app/util/logs/__snapshots__/index.test.ts.snap (hunk 10 above)
Comment (ieow) [reply app/util/logs/__snapshots__/index.test.ts.snap:463]: Yes

File: app/util/logs/__snapshots__/index.test.ts.snap (hunk 11 above)
Comment (ieow) [reply app/util/logs/__snapshots__/index.test.ts.snap:472]: Yes

File: app/util/logs/index.test.ts
Comment (ieow) [reply app/util/logs/index.test.ts:1]: Added Testcases here
https://github.com/MetaMask/metamask-mobile/pull/18299/files#diff-211eb929237232cdcc4f6035d8ff35307a6337089abe12ace4890e591f900accR442

File: app/util/test/initial-background-state.json
Comment (ieow) [reply app/util/test/initial-background-state.json:1]: Added Testcases here
https://github.com/MetaMask/metamask-mobile/pull/18299/files#diff-211eb929237232cdcc4f6035d8ff35307a6337089abe12ace4890e591f900accR442

**Review by himanshuchawla009 — APPROVED** [review]
lgtm, social login email is still present in state logs, we should validate that if that's fine from user privacy perspective.

File: app/util/logs/index.ts (hunk 4 above)
Comment (matthiasgeihs) [reply app/util/logs/index.ts]: done

File: app/util/logs/index.test.ts [hunk 13]
```diff
@@ -346,4 +351,151 @@ describe('logs :: downloadStateLogs', () => {
...
+
+        vault: 'should be in boolean',
+        vaultEncryptionKey: 'should be in boolean',
+        vaultEncryptionSalt: 'should be in boolean',
+        encryptedSeedlessEncryptionKey: 'should be in boolean',
+        encryptedKeyringEncryptionKey: 'should be in boolean',
+        metadataAccessToken: 'should be in boolean',
+        accessToken: 'should be in boolean',
+        refreshToken: 'should be in boolean',
+        revokeToken: 'should be in boolean',
```
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts]: nit
```suggestion
        vault: 'should be a boolean',
        vaultEncryptionKey: 'should be a boolean',
        vaultEncryptionSalt: 'should be a boolean',
        encryptedSeedlessEncryptionKey: 'should be a boolean',
        encryptedKeyringEncryptionKey: 'should be a boolean',
        metadataAccessToken: 'should be a boolean',
        accessToken: 'should be a boolean',
        refreshToken: 'should be a boolean',
        revokeToken: 'should be a boolean',
```

File: app/util/logs/index.test.ts [hunk 14]
```diff
@@ -346,4 +351,151 @@ describe('logs :: downloadStateLogs', () => {
...
+        metadataAccessToken,
+        accessToken,
+        refreshToken,
+        revokeToken,
+        nodeAuthTokens,
+        socialBackupsMetadata,
+      } = logsObj.engine.backgroundState.SeedlessOnboardingController;
+
+      expect(nodeAuthTokens[0].nodeIndex).toBe(1);
+      expect(nodeAuthTokens[0].authToken).toBe(undefined);
```
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts]: Why is this converted to undefined, but others are converted to boolean?

File: app/util/logs/index.test.ts [hunk 15]
```diff
@@ -346,4 +351,151 @@ describe('logs :: downloadStateLogs', () => {
...
+
+      expect(socialBackupsMetadata[0].keyringId).toBe('keyring1');
+      expect(socialBackupsMetadata[0].hash).toBe(undefined);
```
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts]: Why is this converted to undefined, but others are converted to boolean?

File: app/util/logs/__snapshots__/index.test.ts.snap
Comment (matthiasgeihs) [inline app/util/logs/__snapshots__/index.test.ts.snap:1]: I see additional snap shots have been added here. Before there was only one (afaik).
Is it really necessary to add additional snapshots here?
I see this potentially becoming a burden to maintain, because when you change a small detail, you now have to update several snapshots instead of just one.

File: app/util/logs/index.test.ts [hunk 16]
```diff
@@ -46,6 +48,9 @@ jest.mock('../../core/Engine', () => ({
         isUnlocked: true,
       },
     },
+    SeedlessOnboardingController: {
+      state: {},
+    },
```
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts:53]: For the `KeyringController`, we add the sanitized state here.
However, for the `SeedlessOnboardingController` we add the empty state. Why?

File: app/util/logs/index.test.ts [hunk 17]
```diff
@@ -346,4 +351,151 @@ describe('logs :: downloadStateLogs', () => {
     const jsonData = JSON.parse(decodedData);
     expect(jsonData).not.toHaveProperty('metaMetricsId');
   });
+
+  it('able to download when SeedlessController state is undefined', async () => {
```
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts]: nit
```suggestion
  it('able to download when SeedlessOnboardingController state is undefined', async () => {
```

File: app/util/logs/index.test.ts [hunk 18]
```diff
@@ -346,4 +351,151 @@ describe('logs :: downloadStateLogs', () => {
...
+    await downloadStateLogs(mockStateInput, false);
+
+    expect(Share.open).toHaveBeenCalledWith({
+      subject: 'TestApp State logs -  v1.0.0 (100)',
+      title: 'TestApp State logs -  v1.0.0 (100)',
+      url: expect.stringContaining('data:text/plain;base64,'),
+    });
+  });
+
+  describe('Sanitized SeedlessController State', () => {
```
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts]: nit
```suggestion
  describe('Sanitized SeedlessOnboardingController State', () => {
```

Comment (matthiasgeihs) [inline app/util/logs/index.test.ts]: We are testing `generateStateLogs` here. Why are these tests not listed under `describe('logs :: generateStateLogs', ...)`?

**Review by himanshuchawla009 — CHANGES_REQUESTED** [review]
we should remove social login email from state logs.

File: app/util/logs/index.test.ts [hunk 19]
```diff
@@ -346,4 +351,151 @@ describe('logs :: downloadStateLogs', () => {
...
+    it('Able to download when SeedlessController state is empty', () => {
```
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts]: You are testing `generateStateLogs`, not `downloadStateLogs`.
```suggestion
    it('should generate state logs when SeedlessOnboardingController state is empty', () => {
```

File: app/util/logs/index.test.ts [hunk 20]
```diff
@@ -346,4 +351,151 @@ describe('logs :: downloadStateLogs', () => {
...
+      expect(encryptedKeyringEncryptionKey).toBe(false);
+      expect(metadataAccessToken).toBe(false);
+      expect(accessToken).toBe(false);
+      expect(refreshToken).toBe(false);
+      expect(revokeToken).toBe(false);
+
+      expect(JSON.parse(logs)).toMatchSnapshot();
+    });
+
+    it('Sanitized SeedlessController sensitive data', () => {
```
Comment (matthiasgeihs) [inline app/util/logs/index.test.ts]:
```suggestion
    it('should sanitize SeedlessOnboardingController sensitive data', () => {
```

**Comment by matthiasgeihs** [comment]
> we should remove social login email from state logs.

Why? This is for debugging purposes. This state log can contain all kinds of personal information. Please double check if removing email is really intended here. @himanshuchawla009

**Comment by himanshuchawla009** [comment]
> > we should remove social login email from state logs.
> 
> Why? This is for debugging purposes. This state log can contain all kinds of personal information. Please double check if removing email is really intended here. @himanshuchawla009

CS team already requested us to remove email from settings page so that its not visible in screenshots sent to CS team , i think the same reasoning is applicable here.

File: app/util/logs/index.test.ts (hunk 15 above)
Comment (ieow) [reply app/util/logs/index.test.ts]: this is part of an object, the token/hash in object presence indicated by other member field.
The other do not have such indication unless converted to boolean

File: app/util/logs/index.test.ts (hunk 20 above)
Comment (ieow) [reply app/util/logs/index.test.ts]: refer testing guideline
https://github.com/MetaMask/contributor-docs/blob/main/docs/testing/unit-testing.md#snapshots

File: app/util/logs/__snapshots__/index.test.ts.snap
Comment (ieow) [reply app/util/logs/__snapshots__/index.test.ts.snap:1]: snapshot is automatically generated upon cmd.
it can highlight outcome changes when you change the code

File: app/util/logs/index.test.ts (hunk 14 above)
Comment (ieow) [reply app/util/logs/index.test.ts]: this is part of an object, the token/hash in object presence indicated by other member field.
The other do not have such indication unless converted to boolean

File: app/util/logs/index.test.ts (hunk 16 above)
Comment (ieow) [reply app/util/logs/index.test.ts:53]: We mock it in the test instead of global mocking.
Also we start test with test case where seedlessOnboarding is not enabled ( hence empty state) and make sure it does not break existing flow

File: app/util/logs/index.test.ts (hunk 13 above)
Comment (ieow) [reply app/util/logs/index.test.ts]: updated

File: app/util/logs/index.test.ts (hunk 18 above)
Comment (ieow) [reply app/util/logs/index.test.ts]: moved under  `describe('logs :: generateStateLogs', ...)`

File: app/util/logs/index.test.ts (hunk 19 above)
Comment (ieow) [reply app/util/logs/index.test.ts]: updates with `Able generate logs when`

File: app/util/logs/index.test.ts (hunk 18 above)
Comment (ieow) [reply app/util/logs/index.test.ts]: updated

File: app/util/logs/index.test.ts (hunk 17 above)
Comment (ieow) [reply app/util/logs/index.test.ts]: updated

**Review by himanshuchawla009 — DISMISSED** [review]
lgtm

**Review by jvbriones — APPROVED** [review]

**Review by himanshuchawla009 — APPROVED** [review]
lgtm

**Comment by ieow** [comment]
Add no e2e needed as the e2e run only failing same workflow as the main e2e run.
The failure is also not related to this pr
