### PR TITLE
fix: cp-7.47.0 Fix QR wallet support in swaps flow

### LINKED ISSUE #16277: [Bug] QR signature not appearing to sign preventing swap flow
build: main

1. add hardware wallet
2. import qr account (keystone)
3. switch to polygon mainnet
4. initiate swap txn POL to USDC
5. confirm txn and wait for qr code to appear to sign

Expected: QR code to sign appears
Actual: QR code does not appear

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXhXQ2c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1729989fdb1e7e9a4eb4bc73a32bb7c81662a08d/ScreenRecording_06-10-2025%2011-43-05_1.MP4)

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to fix hidden QR modal on the transaction confirmation that doesn't require approval, specifically the described flow is swaps when using QR hardware wallet.

This PR will be CP into `7.47.0`, title will be changed after `QA passed`.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/16277

## **Manual testing steps**

See recordings

### **Before**

https://github.com/user-attachments/assets/715e3d49-a698-4071-b79a-bd0c3b039957

### **After**

https://github.com/user-attachments/assets/769aade6-9da6-4810-92cd-153ef66d12b2

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Swaps/QuotesView.js [hunk 1]
```diff
@@ -1061,6 +1064,8 @@ function SwapsQuotesView({
             deviceConfirmedOn: WalletDevice.MM_MOBILE,
             networkClientId,
             origin: process.env.MM_FOX_CODE,
```
Comment (OGPoyraz) [inline app/components/UI/Swaps/QuotesView.js:1066]: It might be historically settled but @MetaMask/swaps-engineers needs to address this later because it's very confusing that we set `origin` as `MM_FOX_CODE`. It should be either `metamask` (as it's more appropriate) `Metamask Mobile`, but needs to be very well tested as some swaps code is checking this.

**Review by bfullam — DISMISSED** [review]

File: app/components/Views/confirmations/legacy/SendFlow/Amount/index.js [hunk 2]
```diff
@@ -705,10 +706,13 @@ class Amount extends PureComponent {
         .build(),
     );
 
+    const shouldUseRedesignedTransferConfirmation = 
+      isRedesignedTransferConfirmationEnabledForTransfer && !isHardwareAccount(transaction.from);
```
Comment (OGPoyraz) [inline app/components/Views/confirmations/legacy/SendFlow/Amount/index.js:710]: Fixing send flow with QR wallet here - as we can't only rely on feature flag. Potentially we will CP this into `7.49.0` fyi @MetaMask/confirmations

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by bfullam — APPROVED** [review]

**Comment by vivek-consensys** [comment]
QR flows working as expected on both Android/iOS

**Review by pedronfigueiredo — APPROVED** [review]

**Comment by OGPoyraz** [comment]
`No E2E Smoke Needed` added because failures are not realted with this PR:
See more here: https://consensys.slack.com/archives/C08QGLH60N7/p1750243472998199
