### PR TITLE
fix: cp-7.41.0 Handle better errors by getting tags in pre-init

### LINKED ISSUE #12289: [Sentry] TypeError: undefined is not an object (evaluating 'n.flatMap')
Sentry Issue: [METAMASK-MOBILE-31ZW](https://metamask.sentry.io/issues/6044922213/?referrer=github_integration)

```
TypeError: undefined is not an object (evaluating 'n.flatMap')
  at None (app:///main.jsbundle:4661:386)
  at E (app:///main.jsbundle:2878:564)
  at None (app:///main.jsbundle:2877:1041)
  at E (app:///main.jsbundle:2878:564)
  at None (app:///main.jsbundle:2877:1007)
...
(16 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**

Handle errors in a more scalable way by adding a try catch to get tags function. Also added test coverage

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/sentry/tags/index.ts [hunk 1]
```diff
@@ -5,44 +5,50 @@ import { selectAllTokensFlat } from '../../../selectors/tokensController';
...
+      'wallet.nft_count': nftCount,
+      'wallet.notification_count': notificationCount,
+      'wallet.pending_approval': firstApprovalType,
+      'wallet.token_count': tokenCount,
+      'wallet.transaction_count': transactionCount,
+      'wallet.unlocked': unlocked,
+    };
+  } catch (error) {
+    captureException(`Error getting tags: ${error}`);
+    return null;
```
Comment (Gudahtt) [inline app/util/sentry/tags/index.ts:52]: It looks like this function returns tags if they're found, or `undefined` if they're not. Perhaps we can simplify this and not introduce a third return type? We should be able to use `undefined` here as well

File: app/util/sentry/tags/index.ts [hunk 2]
```diff
@@ -5,44 +5,50 @@ import { selectAllTokensFlat } from '../../../selectors/tokensController';
...
-  )
-    return;
-  if (!state?.engine?.backgroundState?.TokensController) return;
-  if (!state?.engine?.backgroundState?.TokensController?.allTokens) return;
-  if (!state?.engine?.backgroundState?.TransactionController) return;
-  if (!state?.engine?.backgroundState?.TransactionController?.transactions)
-    return;
-  if (!state?.engine?.backgroundState?.ApprovalController) return;
+  try {
+    if (!state?.engine?.backgroundState?.AccountsController) return;
```
Comment (Gudahtt) [inline app/util/sentry/tags/index.ts:12]: Nit: These early exits can be removed now as well, they were intended to guard against the same crashes we're now catching more broadly.

File: app/util/sentry/tags/index.ts [hunk 3]
```diff
@@ -5,44 +5,50 @@ import { selectAllTokensFlat } from '../../../selectors/tokensController';
...
+      'wallet.account_count': accountCount,
+      'wallet.nft_count': nftCount,
+      'wallet.notification_count': notificationCount,
+      'wallet.pending_approval': firstApprovalType,
+      'wallet.token_count': tokenCount,
+      'wallet.transaction_count': transactionCount,
+      'wallet.unlocked': unlocked,
+    };
+  } catch (error) {
+    captureException(`Error getting tags: ${error}`);
```
Comment (Gudahtt) [inline app/util/sentry/tags/index.ts:51]: Note that in this case the failure is expected and not indicative of any problem, so I'm not sure we need to log anything to Sentry or Segment or anywhere. It's normal for this to be called pre-initialization.

**Review by Gudahtt — COMMENTED** [review]
Left a few suggestions.

Also, this broader `try..catch` will definitely solve the problem, but we could also consider splitting it up by selector or chunks of related selector. e.g. if `unlocked` is retrieved in a separate `try..catch` block, we might be able to retrieve that even before Engine initialization.

File: app/util/sentry/tags/index.ts (hunk 3 above)
Comment (tommasini) [reply app/util/sentry/tags/index.ts:51]: It's true! Well noted. I assumed that it would be a problem, but it wouldn't because, at this point in time, the data couldn't just be retrieved yet

**Comment by tommasini** [comment]
@Gudahtt Kept the optional chaining, but based on your comment I think this is in a much better state! Let me know your thoughts!

File: app/util/sentry/tags/index.ts (hunk 1 above)
Comment (tommasini) [reply app/util/sentry/tags/index.ts]: Addressed this commit: https://github.com/MetaMask/metamask-mobile/pull/13598/commits/29a8a15c384bfe583066e0d03339c7fa02952440

**Review by MarioAslau — APPROVED** [review]
