### PR TITLE
fix: formatting remove territory for unified formatting

### LINKED ISSUE #26428: [Bug]: Total aggregated balance displays US$ instead of just $
### Describe the bug

The total aggregated balance is displayed as `US$xx.xx` instead of just `$xx.xx`

This issue has been previously resolved [last year](https://github.com/MetaMask/metamask-mobile/issues/17827), but it has re-appeared in 7.67.0

### Expected behavior

The total aggregated balance to be displayed as `$xx.xx`, without the `US`

### Screenshots/Recordings

Image

https://github.com/user-attachments/assets/6e9abcb4-3b36-4365-a5f0-f71216350345

### Steps to reproduce

1. Install v7.67.0
2. Notice total balance

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

7.67.0

### Build number

3764

### Build type

None

### Device

iPhone 15

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

We are removing the locale territory (e.g. 'en-US', 'en-GB') so we can have a unified currency experience.
Will need to sync with the ramps team who are using these shared utils.

I've also added a small test harness to prevent this regression in the future.

## **Changelog**

CHANGELOG entry: fix: formatting remove territory for unified formatting

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/26428 https://consensyssoftware.atlassian.net/browse/ASSETS-2767

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

Screenshot 2026-02-26 at 10 53 56

### **After**

Screenshot 2026-02-26 at 12 08 56

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Changes locale handling for all callers of `useFormatters`, which can affect currency/number formatting across the app; impact is broad but the logic change is small and covered by a new regression test.
> 
> **Overview**
> Forces `useFormatters` to *drop the locale territory* (e.g., `en-US` -> `en`) before creating formatters, to unify currency formatting output.
> 
> Adds a hook test that mocks `I18n.locale` across several English locales and asserts `formatCurrency` for USD uses the `$` prefix (and never `US$`).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 6e0cf303a8611a738fda26268abd2ef317a75e2e. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/hooks/useFormatters.ts [hunk 1]
```diff
@@ -2,7 +2,9 @@ import { useMemo } from 'react';
 import { createFormatters } from '@metamask/assets-controllers';
 import I18n from '../../../locales/i18n';
 
+export const getLocaleLanguageCode = () => I18n.locale.split('-')[0];
+
 export function useFormatters() {
-  const locale = I18n.locale;
+  const locale = getLocaleLanguageCode();
```
Comment (Prithpal-Sooriya) [inline app/components/hooks/useFormatters.ts:8]: @MetaMask/ramp @georgeweiler Does this impact your flows?

This was changed in your PR, but ended up impacting assets flows.
https://github.com/MetaMask/metamask-mobile/pull/26035/changes#diff-c583620b5c0776e28d00912a7d784c08e4a24b4d00e891a1bfc90c0d07965731

File: app/selectors/assets/assets-list.test.ts [hunk 2]
```diff
@@ -974,6 +985,46 @@ describe('selectAsset', () => {
...
+
+  describe('balanceFiat locale formatting', () => {
+    beforeEach(() => {
+      const actualNumberFormat = Intl.NumberFormat;
+      jest.spyOn(Intl, 'NumberFormat').mockImplementation((locale, options) => {
+        // Mobile (Android & IOS do not support currencyDisplay and are unable to use 'narrowSymbol')
+        // We can remove these mocks once this becomes supported.
+        delete options?.currencyDisplay;
+        return actualNumberFormat(locale, options);
+      });
```
Comment (Prithpal-Sooriya) [inline app/selectors/assets/assets-list.test.ts:997]: The underlying formatting uses `currencyDisplay: 'narrowSymbol'`, which I think is the correct approach.

However this is not supported on IOS/Android and you can see this since some balances still show `$US` prefix.

We now instead will format currency based on just the language code (skipping region) so we have unified currency format consistency.

**Review by bergarces — APPROVED** [review]
American experience for everyone!

This might have the unintended consequence of forcing language defaults based on a specific country. English is not the only example.

File: app/components/hooks/useFormatters.ts (hunk 1 above)
Comment (georgeweiler) [reply app/components/hooks/useFormatters.ts:8]: looking good, thanks!

Screenshot 2026-02-26 at 9 36 57 AM
Screenshot 2026-02-26 at 9 38 02 AM

**Review by georgeweiler — APPROVED** [review]
