### PR TITLE
fix: approval request with id x not found

### LINKED ISSUE #6774: [Bug] `MetaMask Tx Signature: Unknown problem` when Approve an ERC20/ERC721
**Describe the bug**
After deploying an ERC20/ERC721 token I've hit the Approve button and got into the following error: `MetaMask Tx Signature: Unknown problem`

**Screenshots**

image

**To Reproduce**
Further investigation is needed as the issue is hard to repro (I can only reproduce it the first time I hit Approve after a fresh build). Some hints:
- It was the first time I tried an Approve after building MM from scratch
- After closing the popup, everything worked normally again
- I could perform subsequent Approves without error

**Expected behavior**
No error should happen

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: current main (that would be 7.4.0, unsure if in other versions)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by vinistevam**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
To reproduce it, follow these steps: create a token, leave the modal open, and move the MMM app to the background. When you bring the MMM back to the foreground, you will encounter the error. 

- add checks if has an approval request before rejecting it.

Additional reports on sentry: https://metamask.sentry.io/issues/?project=2299799&query=is%3Aunresolved+Approval&referrer=issue-list&statsPeriod=30d&utc=true

**Screenshots/Recordings**

After fix:

[create-token-fixed.webm](https://github.com/MetaMask/metamask-mobile/assets/45455812/10f9aaf4-f937-441c-af20-9ef04b5f9a88)

Before fix:

[before-fix.webm](https://github.com/MetaMask/metamask-mobile/assets/45455812/eeb7e7a9-15e7-4323-ab7c-f140b052cc92)

**Issue**

resolves: https://github.com/MetaMask/metamask-mobile/issues/6774

**E2E Pipeline**
https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/6778146f-5e13-4f23-b31f-4665bfb01b85

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

File: app/components/Views/Approval/index.js [hunk 1]
```diff
@@ -137,13 +137,13 @@ class Approval extends PureComponent {
...
       const { transaction, selectedAddress } = this.props;
-      const { KeyringController } = Engine.context;
+      const { KeyringController, ApprovalController } = Engine.context;
       if (!transactionHandled) {
         if (isQRHardwareAccount(selectedAddress)) {
           KeyringController.cancelQRSignRequest();
-        } else {
-          Engine.context.ApprovalController.reject(
-            transaction.id,
+        } else if (ApprovalController.has({ id: transaction?.id })) {
```
Comment (matthewwalsh0) [inline app/components/Views/Approval/index.js:144]: While I think we could investigate the architecture at a higher level down the line to verify all the places we are trying to reject, given this is in production now, this is a nice and clean way to avoid the error.

If this pattern becomes a common one, we could even add an optional `ignoreMissing` flag to the `reject` method itself in future.

**Review by matthewwalsh0 — APPROVED** [review]
