### PR TITLE
fix: refactor recreatevault -> change password cp-7.53.0

### LINKED ISSUE #17618: [Bug]: Creating new Solana account when changing password, it will be disappeared when re-login
### Describe the bug

When user have 2 mobiles device, android and ios
on ios device, user see 3 account
on android device, user change the password
on ios device, lock the account, unlock, check and see 4 accounts
if reset the wallet on android and ios, the new solana wallet will be disappear

Note: if login same social account on extension, will not show any new solana account

### Expected behavior

Should not have this behavior

### Screenshots/Recordings

on ios device
Image

on extension

Image

### Steps to reproduce

1. When user have 2 mobiles device, android and ios
2. on ios device, user see 3 account
3. on android device, user change the password
4. on ios device, lock the account, unlock, check and see 4 accounts
5. reset the wallet on android and ios, the new solana wallet will be disappear

6. if login same social account on extension, will not show any new solana account

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

7.52.99

### Build type

Beta

### Device

Honor Play, iPhone14promax

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ieow**
## **Description**
Refactor recreateNewVault with changePassword
changePassword is recently added in KeyringController, refactoring mobile's recreateNewVault to reduce the complexity of change password in mobile

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes:
#17593
 #17618
## **Manual testing steps**

1. Login into Wallet
2. Go to Setting > Security Settings > Change Password
3. Submit old password 
4. Submit new password

### **After**

https://github.com/user-attachments/assets/724a7f84-f88c-4139-8d66-c43232ccfaff

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/Vault.js [hunk 1]
```diff
@@ -1,349 +1,96 @@
...
 
 import { selectSeedlessOnboardingLoginFlow } from '../selectors/seedlessOnboardingController';
 import { Authentication } from './Authentication/Authentication';
 import { endTrace, trace, TraceName, TraceOperation } from '../util/trace';
 
 /**
- * Restore the given serialized QR keyring.
- *
- * @param {unknown} serializedQrKeyring - A serialized QR keyring.
+ * Returns current vault seed phrase
```
Comment (himanshuchawla009) [inline app/core/Vault.js]:
```suggestion
 * Returns the seed phrase from vault for the provided `keyringId`.
```

File: app/core/Vault.js [hunk 2]
```diff
@@ -1,349 +1,96 @@
...
+ * It does it using an empty password or a password set by the user
```
Comment (himanshuchawla009) [inline app/core/Vault.js]:
```suggestion
 * If the wallet is unlocked, the password can be an empty string. Otherwise, a password is required to retrieve the seed phrase from the vault.
```

File: app/core/Vault.js [hunk 3]
```diff
@@ -1,349 +1,96 @@
...
-  } catch (e) {
     Logger.error(
-      e,
-      'error while trying to restore imported srp accounts on recreate vault',
+      error,
+      '[recreateVaultWithNewPassword] seedless onboarding pw change error',
     );
-  }
-};
+    // restore keyring with old password if seedless onboarding pw change fails
```
Comment (himanshuchawla009) [inline app/core/Vault.js]: this comment is not valid anymore.

File: app/core/Vault.js [hunk 4]
```diff
@@ -1,349 +1,96 @@
...
-      );
-    }
 
-    return keyringId;
-  } catch (e) {
     Logger.error(
-      e,
-      'error while trying to restore imported srp accounts on recreate vault',
+      error,
+      '[recreateVaultWithNewPassword] seedless onboarding pw change error',
```
Comment (himanshuchawla009) [inline app/core/Vault.js]:
```suggestion
      '[seedlessChangePassword] seedless onboarding pw change error',
```

File: app/core/Vault.js [hunk 5]
```diff
@@ -1,349 +1,96 @@
...
-  return await KeyringController.exportSeedPhrase(password, keyringId);
-};
-
 /**
  * Recreates a vault with the new password
  *
  * @param password - current password
  * @param newPassword - new password
- * @param selectedAddress
+ * @param selectedAddress - selected address
```
Comment (himanshuchawla009) [inline app/core/Vault.js]:
```suggestion
 * @param selectedAddress - current selected address in wallet.
```

File: app/core/Vault.js [hunk 6]
```diff
@@ -24,326 +23,90 @@ import { Authentication } from './Authentication/Authentication';
...
-  )
-    ? await getSerializedKeyring(KeyringTypes.ledger)
-    : undefined;
-  const serializedQrKeyring = hasKeyringType(
-    KeyringController.state,
-    KeyringTypes.qr,
-  )
-    ? await getSerializedKeyring(KeyringTypes.qr)
-    : undefined;
+  await KeyringController.changePassword(newPassword);
```
[the remark this answers is not in the document]
Comment (himanshuchawla009) [reply app/core/Vault.js]: is this new `changePassword` function backward compatible for existing mobile users? @mikesposito

File: app/core/Vault.js [hunk 7]
```diff
@@ -1,349 +1,96 @@
...
 /**
- * Restore the given serialized Ledger keyring.
+ * Changes the password of the seedless onboarding controller
  *
- * @param {unknown} serializedLedgerKeyring - A serialized Ledger keyring.
+ * @param {string} newPassword - new password
+ * @param {string} password - current password
  */
-export const restoreLedgerKeyring = async (serializedLedgerKeyring) => {
+export const seedlessChangePassword = async (newPassword, password) => {
```
Comment (himanshuchawla009) [inline app/core/Vault.js]:
```suggestion
export const recreateSeedlessVaultWithNewPassword = async (newPassword, password) => {
```

File: app/core/Vault.js [hunk 8]
```diff
@@ -1,349 +1,96 @@
...
-      await KeyringController.createNewVaultAndRestore(
-        password,
-        primaryKeyringSeedPhrase,
-      );
-      seedlessChangePasswordError = new SeedlessOnboardingControllerError(
-        SeedlessOnboardingControllerErrorType.ChangePasswordError,
-        error || 'Password change failed',
-      );
-      await Authentication.syncKeyringEncryptionKey();
+      await KeyringController.changePassword(password);
```
Comment (mikesposito) [inline app/core/Vault.js]: If this step fails for some reason we'll be in a tough spot, where the `seedlessChangePassword` failed while the first `KeyringController.changePassword` was successful - or in other words, KeyringController will use the new password while SeedlessOnboardingController will use the old password.

At the same time, I can't think of a reason the first call would succeedv while the second fails.

File: app/core/Vault.js [hunk 9]
```diff
@@ -1,349 +1,96 @@
...
+  if (isSeedlessFlow) {
     try {
-      trace({
-        name: TraceName.OnboardingResetPassword,
-        op: TraceOperation.OnboardingSecurityOp,
-      });
-      await SeedlessOnboardingController.changePassword(newPassword, password);
-      await Authentication.syncKeyringEncryptionKey();
-      specificTraceSucceeded = true;
+      await seedlessChangePassword(newPassword, password);
```
Comment (chaitanyapotti) [inline app/core/Vault.js]: we should keep the sentry traces still

File: app/core/Vault.js (hunk 3 above)
Comment (mikesposito) [inline app/core/Vault.js]: nit: is this comment still relevant?

**Review by mikesposito — COMMENTED** [review]
Thanks for taking on this work! Changes look overall good, though I left a comment regarding the only thing that concerns me with this refactor - even though, regardless, this new version seems infinitely safer than the original code we had.

File: app/core/Vault.js (hunk 8 above)
Comment (himanshuchawla009) [inline app/core/Vault.js]: we also need to revert seedless controller encryption key as well are doing in extension.

```
    const revertedKeyringEncryptionKey = await exportEncryptionKey();
     await storeKeyringEncryptionKey(revertedKeyringEncryptionKey);
 
 ```

**Review by himanshuchawla009 — CHANGES_REQUESTED** [review]

File: app/core/Vault.js (hunk 8 above)
Comment (himanshuchawla009) [reply app/core/Vault.js]: in case of error , its reverting keyring controller back to old pwd but nevertheless there can be rare cases like user closes the window when seedless controller call in progress.

Comment (himanshuchawla009) [reply app/core/Vault.js]: Also we are already handling the case when keyring state is latest but seedless controller local state is outdated, in the change pwd flow let say seedless backend calls succeeds but local state is still old because user closes the app, then  when user will open the app again they will see the popup "Your password has been changed" and once they enter the new pwd keyring state will sync with seedless.

Comment (mikesposito) [reply app/core/Vault.js]: > we are already handling the case when keyring state is latest but seedless controller local state is outdated 

That's good to know. Given that, would it make sense to just throw an error in case `seedlessChangePassword` fails, instead of trying to revert the KeyringController password? This way, we would rely on the existing flow

File: app/core/Vault.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (mikesposito) [reply app/core/Vault.js]: yes, the `changePassword` function works for both existing and new users.

**Comment by mikesposito** [comment]
> is this new changePassword function backward compatible for existing mobile users? @mikesposito

@himanshuchawla009 yes, the `changePassword` function works for both existing and new users

File: app/core/Vault.js (hunk 8 above)
Comment (ieow) [reply app/core/Vault.js]: [at the finally ](https://github.com/MetaMask/metamask-mobile/pull/17642/files#diff-9cf2bc6561abadc82def41b57791dc765fd05bf93563c4b198dd09d07f60ad1fR97)
we use the Authentication.syncKeyringEncryptionKey

File: app/core/Vault.ts [hunk 10]
```diff
@@ -0,0 +1,111 @@
...
+    // if it succed seedless change password but fail on the change password on local, we will prompt user password out of date
+    // and ask user to login with new password
+    if (isSeedlessFlow) {
+      await recreateSeedlessVaultWithNewPassword(newPassword, password);
+    }
+
+    await KeyringController.changePassword(newPassword);
+  } finally {
+    if (isSeedlessFlow) {
+      await Authentication.syncKeyringEncryptionKey();
```
Comment (himanshuchawla009) [inline app/core/Vault.ts]: we shouldn't do this in case of error right? Finally block will be executed in all cases.

File: app/core/Vault.ts [hunk 11]
```diff
@@ -0,0 +1,111 @@
...
+  }
+  Engine.setSelectedAddress(selectedAddress);
+};
+
+/**
+ * Recreates a vault with the same password for the purpose of using the newest encryption methods
+ *
+ * @param password - Password to recreate and set the vault with
+ */
+export const recreateVaultWithSamePassword = async (
```
Comment (himanshuchawla009) [inline app/core/Vault.ts]: why diff function is required, is it being used anywhere?

File: app/core/Vault.ts [hunk 12]
```diff
@@ -0,0 +1,111 @@
...
+ * @param {string} keyringId - Keyring ID to retrieve the seed phrase from the vault
+ * @returns {Promise<string>} - Seed phrase from the vault
+ */
+export const getSeedPhrase = async (password: string, keyringId: string) => {
+  const { KeyringController } = Engine.context;
+  return await KeyringController.exportSeedPhrase(password, keyringId);
+};
+
+/**
+ * Changes the password of the seedless onboarding controller
```
Comment (himanshuchawla009) [inline app/core/Vault.ts]:
```suggestion
 * Changes the password of the seedless onboarding controller and re-creates seedless vault using new password.
```

File: app/core/Vault.ts [hunk 13]
```diff
@@ -0,0 +1,111 @@
...
+  } finally {
+    endTrace({
+      name: TraceName.OnboardingResetPassword,
+      data: { success: specificTraceSucceeded },
+    });
+  }
+};
+
+/**
+ * Recreates a vault with the new password
```
Comment (himanshuchawla009) [inline app/core/Vault.ts]:
```suggestion
 * Recreates keyring and seedless storage vault with the new password.
```

File: app/core/Vault.ts [hunk 14]
```diff
@@ -0,0 +1,111 @@
...
+ *
+ * @param password - current password
+ * @param newPassword - new password
+ * @param selectedAddress - current selected address in wallet.
+ */
+export const recreateVaultWithNewPassword = async (
```
Comment (himanshuchawla009) [inline app/core/Vault.ts]:
```suggestion
export const recreateVaultsWithNewPassword = async (
```

**Review by himanshuchawla009 — CHANGES_REQUESTED** [review]

File: app/core/Vault.ts (hunk 11 above)
Comment (ieow) [reply app/core/Vault.ts]: removed

**Review by himanshuchawla009 — APPROVED** [review]
lgtm
