### PR TITLE
fix: cp-7.59.0 ensure that txs show on asset details page

### LINKED ISSUE #22251: [Bug]: Solana activity on token details page is not working
**Describe the bug**

Activity is not propagating on the `Token Details` page for Solana. When I kill the app and click Solana, no activity shows even though there should be. Once I click `Activity` and navigate back to `Token Details`, the activity propagates.

**Expected behavior**

The activity should propagate without me navigating to the `Activity` page first.

**Screenshots/Recordings**

https://github.com/user-attachments/assets/c9d0f22e-2859-44a5-9629-3306d4fa5e47

**Steps to reproduce**

1. Have a TX on a SOL token
2. Go to `Token Details`
3. Notice no activity
4. Navigate to `Activity`
5. Go to `Token Details`
6. Notice activity is propagating now

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

7.59

**Build type**

None

**Device**

iPhone Max Pro 13

**Operating system**

iOS

### PR DESCRIPTION
**Pull request by bergarces**
## **Description**

Fixes an issue in which txs sometimes do not show on the details page for non-evm assets.

## **Changelog**

CHANGELOG entry: Fixed an issue in which txs sometimes do not show on the details page for non-evm assets.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/22251

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

https://github.com/user-attachments/assets/d9a517d4-130b-42bc-9d5a-d216dff1d491

### **After**

https://github.com/user-attachments/assets/d726164c-f231-402f-af58-f7ad67e810f6

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Use a new selector to aggregate/filter non-EVM transactions by chain and asset so the Asset details page shows the correct txs.
> 
> - **Asset view (`app/components/Views/Asset/index.js`)**:
>   - Replace `selectNonEvmTransactions` with `selectNonEvmTransactionsForSelectedAccountGroup`.
>   - For non-EVM assets, filter txs by `chainId` and asset (native vs token via `address`/`symbol`), add lightweight caching, and sort by time.
> - **Selectors (`app/selectors/multichain/multichain.ts`)**:
>   - Mark `selectNonEvmTransactions` as deprecated.
>   - Add `selectNonEvmTransactionsForSelectedAccountGroup` to aggregate and flatten non-EVM txs across the selected account group, sorting by timestamp.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 037033ae8e7d883e58751fb5e37a750791ff3569. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/Asset/index.js [hunk 1]
```diff
@@ -668,8 +668,12 @@ const mapStateToProps = (state, { route }) => {
 
   ///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
   if (asset?.chainId && isNonEvmChainId(asset.chainId)) {
-    const nonEvmTransactions = selectNonEvmTransactions(state);
-    const txs = nonEvmTransactions?.transactions || [];
+    const nonEvmTransactions =
+      selectNonEvmTransactionsForSelectedAccountGroup(state);
```
Comment (bergarces) [inline app/components/Views/Asset/index.js:672]: Yes, this is a selector being called without a hook inside a mapping function of a javascript class component. You are not dreaming it.

**Review by sahar-fehri — APPROVED** [review]

File: app/components/Views/Asset/index.js (hunk 1 above)
Comment (Prithpal-Sooriya) [reply app/components/Views/Asset/index.js:672]: 🤣

Comment (Prithpal-Sooriya) [reply app/components/Views/Asset/index.js:672]: Wow... This is a connected class component (with mapStateToProps)... But this might be a much larger lift...

Comment (Prithpal-Sooriya) [reply app/components/Views/Asset/index.js:672]: I would love to add this to our backlog to cleanup.

File: app/selectors/multichain/multichain.ts [hunk 2]
```diff
@@ -467,6 +467,10 @@ interface NonEvmTransactionStateEntry {
   lastUpdated: number | undefined;
 }
 
+/**
+ * @deprecated
```
Comment (Prithpal-Sooriya) [inline app/selectors/multichain/multichain.ts:471]: TY

Comment (Prithpal-Sooriya) [reply app/selectors/multichain/multichain.ts:471]: I wonder if there are any recommendations we can inform teams that want to use this selector?
Meh, we can keep this as a github comment to stumble upon.

**Review by Prithpal-Sooriya — APPROVED** [review]
