### PR TITLE
fix: hide amount in simulations for testnets if its opt out

### LINKED ISSUE #9906: Hide amount in simulations for testnets if it's opted out by user
**Background**

The mobile displays simulation fiat values in testnets regardless of the user preference in advance settings. 

**Goal**

Currently it displays `NaN US$` and the goal is to remove fiat values completely if user opt out.

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to hide testnet fiat values if user opt out in the settings.

[Open in GitHub Codespaces](https://codespaces.new/MetaMask/metamask-extension/pull/25167?quickstart=1)

## **Related issues**

- Fixes: https://github.com/MetaMask/metamask-mobile/issues/9906

## **Manual testing steps**

1. Change current network to any testnet
2. Go to setting, turn on "Show conversion on test networks"
3. Try simple send - see fiat values displayed in simulations
4. Go to setting, turn off "Show conversion on test networks"
5. Try simple send - see no fiat values displayed in simulations
6. Change current network to mainnet or any other network which is not testnet
7. Try simple send - see fiat values displayed in simulations

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/hooks/useHideFiatForTestnet/index.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+import { TEST_NETWORK_IDS } from '../../../constants/network';
+
+/**
+ * Returns true if the fiat value should be hidden for testnet networks.
+ *
+ * @returns boolean
+ */
+export default function useHideFiatForTestnet(): boolean {
+  const showFiatInTestnets = useSelector(selectShowFiatInTestnets);
+  const chainId = useSelector(selectChainId);
```
Comment (matthewwalsh0) [inline app/components/hooks/useHideFiatForTestnet/index.ts:13]: As mentioned in the other PR, should we add an optional `chainId` property to avoid reliance on the global network?

File: app/reducers/settings/index.js [hunk 2]
```diff
@@ -62,3 +62,6 @@ const settingsReducer = (state = initialState, action) => {
   }
 };
 export default settingsReducer;
+
+export const selectShowFiatInTestnets = (state) =>
```
Comment (matthewwalsh0) [inline app/reducers/settings/index.js:66]: Would it be more standard to include the selectors in the reducer or in the `app/selectors` directory?

File: app/components/UI/SimulationDetails/FiatDisplay/FiatDisplay.test.tsx [hunk 3]
```diff
@@ -1,46 +1,75 @@
...
-      { state: mockInitialState },
-    );
-    expect(getByText(expected)).toBeDefined();
+describe('FiatDisplay', () => {
+  const mockUseHideFiatForTestnet = jest.mocked(useHideFiatForTestnet);
+  const mockUseFiatFormatter = jest.mocked(useFiatFormatter);
+
+  beforeEach(() => {
+    jest.resetAllMocks();
+    mockUseHideFiatForTestnet.mockReturnValue(false);
```
Comment (matthewwalsh0) [inline app/components/UI/SimulationDetails/FiatDisplay/FiatDisplay.test.tsx:25]: As mentioned in extension PR, should we instead set the settings state via `renderWithProvider` to avoid coupling to the selectors?

File: app/components/hooks/useHideFiatForTestnet/index.ts (hunk 1 above)
Comment (OGPoyraz) [reply app/components/hooks/useHideFiatForTestnet/index.ts]: Done

File: app/components/UI/SimulationDetails/FiatDisplay/FiatDisplay.test.tsx (hunk 3 above)
Comment (OGPoyraz) [reply app/components/UI/SimulationDetails/FiatDisplay/FiatDisplay.test.tsx]: Done

File: app/reducers/settings/index.js (hunk 2 above)
Comment (OGPoyraz) [reply app/reducers/settings/index.js]: Done, recently learned that this approach will be replaced by `app/core/redux/slices`

**Review by matthewwalsh0 — APPROVED** [review]
