### PR TITLE
fix: fix bug first NFT in collection gets always displayed

### LINKED ISSUE #7699: [Bug]: First NFT in collection gets displayed no matter which is tapped
### Describe the bug

In the NFTs list, when tapping an image - if it’s not the first in the list, it will display the information for the first in the list.

### Expected behavior

Display the one tapped

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/8558670/bd386680-dd17-4285-bb89-54f1cba86ff8

https://we.tl/t-UEH1Ons7BB

### Steps to reproduce

1. open MetaMask app
2. Choose an account with NFTs in it
3. Choose a collection of which more than one token is owned by the chosen account
4. Notice it showing you the wrong information

### Error messages or log output

_No response_

### Version

7.9.4

### Build type

None

### Device

Apple iPhone 13 Pro

### Operating system

iOS

### Additional context

Same was noticed on a friend’s device (that’s what brought it to my attention)

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

In the NFTs list, when tapping an image - if it’s not the first in the list, it will display the information for the first in the list.

## **Related issues**

Fixes: [#7699](https://github.com/MetaMask/metamask-mobile/issues/7699)

## **Manual testing steps**

1. Go to NFTs tab
2. Choose a collection who contains more than one NFT
3. Click on the second one , the informations of the first one will be displayed

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/26223211/593647d2-e96f-4ed5-a349-fcb3ae99a74b

### **After**

https://github.com/MetaMask/metamask-mobile/assets/26223211/121f53ae-117e-445e-9cd7-5543b25ae611

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by salimtb** [comment]
I have read the CLA Document and I hereby sign the CLA

File: app/components/UI/CollectibleModal/CollectibleModal.tsx [hunk 1]
```diff
@@ -45,7 +45,9 @@ const CollectibleModal = () => {
   const handleUpdateCollectible = useCallback(() => {
     if (isIpfsGatewatEnabled || displayNftMedia) {
       const newUpdatedCollectible = collectibles.find(
-        (nft: Collectible) => nft.address === collectible.address,
+        (nft: Collectible) =>
+          nft.address === collectible.address &&
+          nft.tokenId === collectible.tokenId,
```
Comment (salimtb) [inline app/components/UI/CollectibleModal/CollectibleModal.tsx:50]: the bug comes from the fact that we're using the find method to filter out the right token, but the condition we're using is wrong because we're only relying on the address which is common to all the other nft.
as a result, the find method returns the first item that matches this condition and stops iteration.

Comment (Cal-L) [reply app/components/UI/CollectibleModal/CollectibleModal.tsx:50]: Nice catch

**Review by Cal-L — APPROVED** [review]
LGTM

**Review by chrisleewilcox — APPROVED** [review]
LGTM
