### PR TITLE
fix: margin incrementally applied to icon when bottom sheet opened

### LINKED ISSUE #3210: Margin increases incrementally every time tooltip is opened by the user, Only affects Icons in the BottomSheet
When a user opens the tooltip component and an icon exists on the BottomSheet, the icons incrementally move to the right every time the tooltip is open, breaking the layout in the BottomSheet.

### PR DESCRIPTION
**Pull request by Daniel-Cross**
## **Description**

When the user opens the tooltip bottom sheet, `marginLeft` is applied incrementally to the icons on the previous bottom sheet, breaking the layout. 

## **Related issues**

Fixes: https://github.com/orgs/MetaMask/projects/149/views/1?pane=issue&itemId=101057723&issue=MetaMask%7Csnaps%7C3210

## **Manual testing steps**

1. Go to this page...
2.
3.

### **Before**

https://github.com/user-attachments/assets/e6c3df9a-b7be-47cf-a4fc-bbba57a6c352

### **After**

https://github.com/user-attachments/assets/ca9c723a-c22d-4d4c-9258-2c82b2282ab3

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Snaps/SnapUILink/SnapUILink.tsx [hunk 1]
```diff
@@ -29,21 +29,22 @@ const onPress = (href: string) => {
 // TODO: This component should show a modal for links when not using preinstalled Snaps
 export const SnapUILink: React.FC<SnapUILinkProps> = ({ href, children }) => {
   const label = (
-    <>
+    <View
+      style={{
+        flexDirection: 'row',
+        alignItems: 'center',
+        justifyContent: 'center',
+        gap: 2,
```
Comment (FrederikBolding) [inline app/components/Snaps/SnapUILink/SnapUILink.tsx:37]:
```suggestion
        gap: 4,
```
To match the extension design

File: app/components/Snaps/SnapUILink/SnapUILink.tsx [hunk 2]
```diff
@@ -31,13 +31,17 @@ export const SnapUILink: React.FC<SnapUILinkProps> = ({ href, children }) => {
   const label = (
     <>
       {children}
+      <View
+        style={{
```
Comment (FrederikBolding) [inline app/components/Snaps/SnapUILink/SnapUILink.tsx:35]: Lint is failing - also is this really the best way to do this? 😅

Comment (Daniel-Cross) [reply app/components/Snaps/SnapUILink/SnapUILink.tsx:35]: Unfortunately this might be the only way to do this and keep the styling. In the fix I did previously the colour of the text link wasn't inherited and the `View` moved everything slightly out of line.

image

With this 'spacer' it doesn't affect those things.

**Review by david0xd — APPROVED** [review]
