### PR TITLE
fix: closing of gas info tooltip

### LINKED ISSUE #10948: [Bug]: Close button on Tooltip modals in edit gas flow doesn't work
### Describe the bug

Close button on tooltip modals doesn't work and there is no way to get out of the flow other than restarting the app.

Steps to reproduce

1. Create a transaction
2. Click on edit gas
3. Click on Low or Aggressive gas options
4. Click on the tooltips next to the estimated time
5. Try to close the tooltip modal
IMG_3049
IMG_3048

### Expected behavior

Expected behavior - Modal should close when close button is clicked

### Screenshots/Recordings

_No response_

### Steps to reproduce

**Steps to reproduce**

1. Create a transaction
2. Click on edit gas
3. Click on Low or Aggressive gas options
4. Click on the tooltips next to the estimated time
5. Try to close the tooltip modal

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

7.30.0

### Build type

None

### Device

iphone 13 pro

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Fix closing gas info tooltip on send page.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/10948

## **Manual testing steps**

1. Create a transaction
2. Click on edit gas
3. Click on Low or Aggressive gas options
4. Click on the tooltips next to the estimated time
5. Try to close the tooltip modal

## **Screenshots/Recordings**

https://github.com/user-attachments/assets/e128ae95-f195-4162-8ced-31ef3b87db96

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by matthewwalsh0 — DISMISSED** [review]

File: app/components/Views/confirmations/components/TransactionReview/TransactionReviewEIP1559Update/index.tsx [hunk 1]
```diff
@@ -49,6 +49,7 @@ const TransactionReviewEIP1559Update = ({
   const [showLearnMoreModal, setShowLearnMoreModal] = useState(false);
   const [
     isVisibleTimeEstimateInfoModal,
+    ,
```
Comment (NicolasMassart) [inline app/components/Views/confirmations/components/TransactionReview/TransactionReviewEIP1559Update/index.tsx:52]: S: can you add a smll code comment in this to explain why we have this lonely coma? It's clear in this PR, but in the wild, no sure I would not try to fix it if I see it. The risk of regression on this is very high without any comment.

**Review by NicolasMassart — DISMISSED** [review]

**Review by OGPoyraz — DISMISSED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Comment by sleepytanya** [comment]
Bitrise builds: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/4fc7b3d9-069a-423f-a4f8-18b712465898?tab=artifacts


 Gas info modal can be closed as expected.

iOS:

https://github.com/user-attachments/assets/6badfb0e-d7e0-423a-b9ea-11c1577cd09b

Android:



https://github.com/user-attachments/assets/959ed3f2-b726-4b70-8b1f-dcb3240bb229
