### PR TITLE
fix: walletconnect issue 15240 chain mismatch #15539

### LINKED ISSUE #15240: [Bug]: WalletConnect chain mismatch on per-dapp-selected-network
### Describe the bug

This issue is related to the following PR: https://github.com/MetaMask/metamask-mobile/pull/14539

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/d02fcf6e-d20f-4439-a18e-7638637f54d7

### Steps to reproduce

- Go to https://appkit-lab.reown.com/library/wagmi/ on your desktop browser
- Connect via QR Code
- Sign -> it correctly prompts to sign on Mainnet
- Switch chain to OP (this should not change immediately)
- Sign -> See issue. It prompts the user to sign on mainnet but it should've made the prompt to sign on OP

### Error messages or log output

```shell

```

### Detection stage

On a feature branch

### Version

7.36.0

### Build type

None

### Device

iPhone 11

### Operating system

Android, iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by elribonazo**
## **Description**
This PR fixes 2 issues, network change event not reflecting and invalid network being shown on personal_sign, and handleSendTransaction.

Improved the code to better manage getting the current network with support for the latest Per-DApp Selected changes.
Additionally when personal_sign or other activity like handleSendTransaction where still using old globalNetworkSelector and for this case we added a check isPerDappSelectedNetworkEnabled and use other selectors when true and fallback to old global network selector if the flag is not yet activated.

Also brought some minimal improvements to the code for better readability, reduce code duplicity, etc.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15240

## **Manual testing steps**

Please follow the instructions in the related [github issue](https://github.com/MetaMask/metamask-mobile/issues/15240)

## **Screenshots/Recordings**

1st Issue, personal sign showing wrong network after changing the selected network from the Dapp.

| Before       | After  (with multichain flags)       |  
|--------------|--------------|
| <video src="https://github.com/user-attachments/assets/d02fcf6e-d20f-4439-a18e-7638637f54d7">  |<video alt="as"  src="https://github.com/user-attachments/assets/d6b45d57-5abf-4119-ab5a-bd2dc9e2bc5f"> | Currently failing, switches network but does not show personal_sign after |

2nd issue, transaction preview shows wrong network selected
| Before       | After  (with multichain flags)       |  
|--------------|--------------|
|  Not recorded | <video src="https://github.com/user-attachments/assets/8b3085d9-b171-4106-a1bd-ddc9d0cc4784"> | 

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Prithpal-Sooriya** [comment]
QA'ed this PR with both multichain flags enabled and disabled
https://www.loom.com/share/38b14d8afa1042439c8576d5d0559b16?sid=64567d11-bb2f-47f0-bc8d-f184045dda2d
https://www.loom.com/share/fe471b0155ea46c2b55598ce0d526499?sid=9ce3288e-e62f-4e7c-80e0-58a5597265dd

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 1]
```diff
@@ -140,23 +143,59 @@ class WalletConnect2Session {
...
+      return perOriginChainId;
+    }
+    return providerConfigChainId;
+  }
+
+  private networkChanged(caipChainId: `${string}:${string}`) {
+    const currentChainId = this.getCurrentChainId();
+    const [, currentChainIdDecimal] = currentChainId.split('x');
+    const [, caipChainIdDecimal] = caipChainId.split(':');
+    return currentChainIdDecimal !== caipChainIdDecimal
```
Comment (jiexi) [inline app/core/WalletConnect/WalletConnect2Session.ts]: the `parseCaipChainId` helper may be useful here.

`const [, currentChainIdDecimal] = currentChainId.split('x');` is incorrect as 0x10 !== decimal 10 but instead decimal 16

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 2]
```diff
@@ -140,23 +143,59 @@ class WalletConnect2Session {
...
+  }
+
+  private getNetworkClientIdForChainId(chainId: number) {
+    if (isPerDappSelectedNetworkEnabled()) {
+      const networkConfigurationsByChainId = selectEvmNetworkConfigurationsByChainId(store.getState());
+      const { rpcEndpoints: [{ networkClientId }] } = networkConfigurationsByChainId[`0x${chainId.toString(16)}`];
```
Comment (jiexi) [inline app/core/WalletConnect/WalletConnect2Session.ts]: thoughts on using the `toHex()` helper?

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 3]
```diff
@@ -508,6 +537,15 @@ class WalletConnect2Session {
       return;
     }
 
+    if (isPerDappSelectedNetworkEnabled() && this.networkChanged(caip2ChainId)) {
+      const chainId = parseInt(caip2ChainId.split(':')[1])
```
Comment (jiexi) [inline app/core/WalletConnect/WalletConnect2Session.ts]: same about `parseCaipChainId`

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 4]
```diff
@@ -140,23 +143,59 @@ class WalletConnect2Session {
...
+
+  private networkChanged(caipChainId: `${string}:${string}`) {
+    const currentChainId = this.getCurrentChainId();
+    const [, currentChainIdDecimal] = currentChainId.split('x');
+    const [, caipChainIdDecimal] = caipChainId.split(':');
+    return currentChainIdDecimal !== caipChainIdDecimal
+  }
+
+  private getNetworkClientIdForChainId(chainId: number) {
+    if (isPerDappSelectedNetworkEnabled()) {
```
Comment (jiexi) [inline app/core/WalletConnect/WalletConnect2Session.ts]: `getCurrentChainId` already has branching logic for getting the per dapp OR globally selected chain Id. Is it still necessary to guard it in `getNetworkClientIdForChainId` as well?

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 5]
```diff
@@ -561,8 +599,10 @@ class WalletConnect2Session {
     origin: string,
   ) {
     try {
-      const networkClientId = getGlobalNetworkClientId();
-
+      const currentChainId = this.getCurrentChainId();
+      const networkClientId = this.getNetworkClientIdForChainId(
+        parseInt(currentChainId.split('x')[1], 16)
```
Comment (jiexi) [inline app/core/WalletConnect/WalletConnect2Session.ts]: this is incorrect. e.g. 0x10 !== decimal 10 but instead decimal 16

**Comment by jiexi** [comment]
This PR makes me realize that we really should instead be tapping into the existing accounts changed and chain changed events being emitted by BackgroundBridge and then rerouting them to `web3Wallet.emitSessionEvent`. This makes it so we don't have to double up on this state change logic in both WalletConnect2Session and BackgroundBridge (which is used in WalletConnect2Session). I'm unsure of time constraints or other factors which would make this not a reasonable change to request this very moment. I'll leave this to your discretion. 

Thank you for making the changes in this PR!

File: app/core/WalletConnect/WalletConnect2Session.ts (hunk 2 above)
Comment (elribonazo) [reply app/core/WalletConnect/WalletConnect2Session.ts]: added

**Comment by elribonazo** [comment]
> This PR makes me realize that we really should instead be tapping into the existing accounts changed and chain changed events being emitted by BackgroundBridge and then rerouting them to `web3Wallet.emitSessionEvent`. This makes it so we don't have to double up on this state change logic in both WalletConnect2Session and BackgroundBridge (which is used in WalletConnect2Session). I'm unsure of time constraints or other factors which would make this not a reasonable change to request this very moment. I'll leave this to your discretion.
> 
> Thank you for making the changes in this PR!

Happy to talk with Adam and see if we can improve this, probably not now, but sooner rather than later for sure!

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 6]
```diff
@@ -140,23 +143,58 @@ class WalletConnect2Session {
...
+      const perOriginChainId = selectPerOriginChainId(
+        store.getState(),
+        this.hostname,
+      );
+      return perOriginChainId;
+    }
+    return providerConfigChainId;
+  }
+
+  private getChainIdForCaipChainId(caipChainId: `${string}:${string}`) {
```
Comment (jiexi) [inline app/core/WalletConnect/WalletConnect2Session.ts]:
```suggestion
  private getChainIdForCaipChainId(caipChainId: CaipChainId) {
```

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 7]
```diff
@@ -52,7 +55,7 @@ class WalletConnect2Session {
   private requestByRequestId: {
     [requestId: string]: WalletKitTypes.SessionRequest;
   } = {};
-  private lastChainId: string;
+  private lastChainId: `0x${string}`;
```
Comment (jiexi) [inline app/core/WalletConnect/WalletConnect2Session.ts]: `Hex`?

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 8]
```diff
@@ -140,23 +143,58 @@ class WalletConnect2Session {
...
+      return perOriginChainId;
+    }
+    return providerConfigChainId;
+  }
+
+  private getChainIdForCaipChainId(caipChainId: `${string}:${string}`) {
+    const caipNetworkConfiguration = selectNetworkConfigurationsByCaipChainId(store.getState());
+    const { chainId } = caipNetworkConfiguration[caipChainId];
+    //TODO: Remove this cast when caipNetworkConfiguration is fixed, duplicate types for chainId
+    return chainId as `0x${string}`;
```
Comment (jiexi) [inline app/core/WalletConnect/WalletConnect2Session.ts]:
```suggestion
    return chainId as Hex`;
```

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 9]
```diff
@@ -140,23 +143,58 @@ class WalletConnect2Session {
...
+  }
+
+  private getNetworkClientIdForCaipChainId(caipChainId: `${string}:${string}`) {
```
Comment (jiexi) [inline app/core/WalletConnect/WalletConnect2Session.ts]: same re: `CaipChainId`

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 10]
```diff
@@ -140,23 +143,58 @@ class WalletConnect2Session {
...
+    const networkConfigurationsByChainId = selectEvmNetworkConfigurationsByChainId(store.getState());
+    const chainId = this.getChainIdForCaipChainId(caipChainId);
+    //Casting is required, because caipnetwork config has duplicate types and we assume the correct one is 0xString
+    const { rpcEndpoints: [{ networkClientId }] } = networkConfigurationsByChainId[chainId as `0x${string}`];
```
Comment (jiexi) [inline app/core/WalletConnect/WalletConnect2Session.ts]: same re: `Hex`

File: app/core/WalletConnect/WalletConnect2Session.ts (hunk 6 above)
Comment (elribonazo) [reply app/core/WalletConnect/WalletConnect2Session.ts]: ok

File: app/core/WalletConnect/WalletConnect2Session.ts (hunk 7 above)
Comment (elribonazo) [reply app/core/WalletConnect/WalletConnect2Session.ts]: Yes

File: app/core/WalletConnect/WalletConnect2Session.ts (hunk 8 above)
Comment (elribonazo) [reply app/core/WalletConnect/WalletConnect2Session.ts]: Yes

File: app/core/WalletConnect/WalletConnect2Session.ts (hunk 10 above)
Comment (elribonazo) [reply app/core/WalletConnect/WalletConnect2Session.ts]: kk

File: app/core/WalletConnect/WalletConnect2Session.ts (hunk 6 above)
Comment (jiexi) [reply app/core/WalletConnect/WalletConnect2Session.ts]: if this method's only purpose is to convert a CaipChainId to Evm Hex ChainID, then I still strongly recommend just doing something like
```
const { reference } = parseCaipChainId(caipChainId)
return toHex(reference)
```

**Review by ecp4224 — DISMISSED** [review]

**Review by jiexi — DISMISSED** [review]
Signing off for the wallet API side of this and less for the WC integration

File: app/core/WalletConnect/WalletConnect2Session.ts [hunk 11]
```diff
@@ -140,23 +143,58 @@ class WalletConnect2Session {
...
+      const perOriginChainId = selectPerOriginChainId(
+        store.getState(),
+        this.hostname,
+      );
+      return perOriginChainId;
+    }
+    return providerConfigChainId;
+  }
+
+  private getChainIdForCaipChainId(caipChainId: CaipChainId) {
```
Comment (tommasini) [inline app/core/WalletConnect/WalletConnect2Session.ts:185]: I believe you don't need to create this util method we have it somewhere, let me see if I find it

Comment (tommasini) [reply app/core/WalletConnect/WalletConnect2Session.ts:185]: We can use this function
https://github.com/MetaMask/utils/blob/main/src/caip-types.ts#L258C17-L258C33
```
const evmCaipChainId: CaipChainId = "eip155:10";
const { reference } = parseCaipChainId(evmCaipChainId);
return toHex(reference) // 0xa
```

Comment (elribonazo) [reply app/core/WalletConnect/WalletConnect2Session.ts:185]: Yeah @jiexi also wrote me about this, talked also to @ecp4224 about it.

According to the specs reference can have non hex characters, assuming that WalletConnect will always be and use EVM only networks is something I'm not super in favor. 

That is the main reason why this code is there, I totally get your point though.

Screenshot 2025-06-05 at 22 17 17

**Review by tommasini — DISMISSED** [review]

**Comment by elribonazo** [comment]
I'm attaching the builds in the ticket
With isPerDapp flags in true: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/c55379b7-0e0f-4feb-acf5-83cb4179b428
with isPerDapp flags in false: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/51f8d30b-0d7c-43b9-ae38-3164a53fccba

This will help establish single source or truth, so we can record all the videos and move on!

**Review by tommasini — DISMISSED** [review]

**Review by EtherWizard33 — DISMISSED** [review]
LGTM I can approve to unblock it, but have limited context on this, or running these flows, its usualy SDK team
@elribonazo  knows and said he was suppose to run it with @adonesky1 
.
@adonesky1 has anything come out your meeting with Javi, the result was this PR or this was before?

**Comment by ALUMINIS650** [comment]
what caused the mismatch?

**Review by tommasini — DISMISSED** [review]

**Review by cmd-ob — APPROVED** [review]

**Review by EtherWizard33 — APPROVED** [review]
approving for wallet -ux for the settings unit-test change to mock values

**Comment by adonesky1** [comment]
Skipping bitrise because all tests are failing except these two:
Screenshot 2025-06-09 at 12 30 16 PM

Which we've established are failing on `main` already
