### PR TITLE
Bugfix: duplicated word in seedphrase

### LINKED ISSUE #1020: Can't confirm seed phrase when two words are identical
There is an issue when the generated seed phrase contains a repeated word.  You will not be able to progress past the "Confirm seed phrase" view when onboarding because it checks both words if you fill out one.

### LINKED ISSUE #1233: Cannot confirm seed phrase due to duplicate seed words
When going through the flow of backing up and confirming the wallet seed phrase,  it is not possible to complete the confirmation if there are two of the same seed word. (see screenshot).

Screenshot_2019-11-04-22-56-05-534_io metamask

It looks like when one of the duplicate seed words is selected, both of them are greyed out and cannot be used again. I haven't tried to reproduce this issue since it is contingent on that any newly created wallet has duplicate seed words.

support case for reference: 26406

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

Fix for issue with duplicated words on seedphrase

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Fixes #1233 
Fixes #1020

### CODE REVIEW

**Review by ibrahimtaveras00 — APPROVED** [review]
built release mode to both OS's, all looks good, QA Passed 👍

File: app/components/Views/AccountBackupStep5/index.js [hunk 1]
```diff
@@ -174,9 +174,60 @@ class AccountBackupStep5 extends PureComponent {
...
+		const dict = {};
+		this.words.forEach((word, i) => {
+			dict[[word, i]] = { currentPosition: undefined };
+		});
+		this.setState({ wordsDict: dict });
+	};
+
+	findNextAvailableIndex = () => {
+		const { confirmedWords } = this.state;
+		for (let i = 0; i < 12; i++) if (!confirmedWords[i].word) return i;
```
Comment (danjm) [inline app/components/Views/AccountBackupStep5/index.js]: Instead of
```
for (let i = 0; i < 12; i++) if (!confirmedWords[i].word) return i;
return 12;
```
could do
```
return confirmedWords.findIndex(obj => !word)
```

and then use `this.findNextAvailableIndex() === -1` on line 218

File: app/components/Views/AccountBackupStep5/index.js [hunk 2]
```diff
@@ -174,9 +174,60 @@ class AccountBackupStep5 extends PureComponent {
...
+	};
+
+	componentDidMount = () => {
+		this.createWordsDictionary();
+	};
+
+	createWordsDictionary = () => {
+		const dict = {};
+		this.words.forEach((word, i) => {
+			dict[[word, i]] = { currentPosition: undefined };
```
Comment (danjm) [inline app/components/Views/AccountBackupStep5/index.js]: Its not exactly clear to anyone ready the code that the keys of `dict` will be strings of the form `'word,i'`

The code could be a bit clearer if the keys were explicitly set with strings.

For example:
```
dict[`${word},${i}`] = { currentPosition: undefined };
```
It would then be clearer what is happening when the key is split on line 280

**Review by danjm — APPROVED** [review]
Reviewed code. It all looks good and that it works fine. Made a couple comments on code improvements that can be made, but they don't need to block merging.

File: app/components/Views/AccountBackupStep5/index.js (hunk 1 above)
Comment (estebanmino) [reply app/components/Views/AccountBackupStep5/index.js]: 👌

File: app/components/Views/AccountBackupStep5/index.js (hunk 2 above)
Comment (estebanmino) [reply app/components/Views/AccountBackupStep5/index.js]: I can change it if it's not clear

**Comment by estebanmino** [comment]
@ibrahimtaveras00 can you do other QA pass?  I've changed the code, just to be sure. I'm pushing the hardcoded seed phrase for you to test it.

**Review by ibrahimtaveras00 — APPROVED** [review]
latest updates look good, QA passed 👍
