### PR TITLE
fix: remove call to private/internal methods from the `@metamask/keyring-controller`

### LINKED ISSUE #8931: [Ledger] Investigate KeyringController methods used in Ledger mobile integration
Refer to slack thread https://consensys.slack.com/archives/C026NDN79JB/p1710333124579809.

We found a few cases in mobile where private/internal KeyringController methods were being called, seemingly for no reason. It looks like they were added as part of the Ledger integration, but it's unclear why from looking at the PR. Could someone here help investigate, and remove these method calls if they're not needed?

### PR DESCRIPTION
**Pull request by dawnseeker8**
## **Description**

Mark has reported that ledger has mis use keyringController method in this slack thread https://consensys.slack.com/archives/C026NDN79JB/p1710333124579809

This PR will investigate the any ledger existing code which misuse keyring controller methods and fix all areas contain the error.

## **Related issues**

Fixes: #8931 

## **Manual testing steps**

The menual tests should including `forget ledger devices`, `relauch app` and `change password` to see whether ledger account still there.

### **After**
https://github.com/MetaMask/metamask-mobile/assets/7315988/a5edeabc-e943-4509-996c-b460ccc751b4

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Review by gantunesr — DISMISSED** [review]

**Comment by vivek-consensys** [comment]
@dawnseeker8 I have found an issue on Samsung S21 using Android 13, when forgetting ledger device, the account is still displayed even though the account should be removed. Please see screen recording:- 


https://github.com/MetaMask/metamask-mobile/assets/106310394/13038395-d40f-4827-b281-ee0609cbddbd

**Comment by vivek-consensys** [comment]
I have also found an issue on Samsung S21 using Android 13, when changing the password after connecting the ledger device, the account is not displayed. Please see screen recording:-

https://github.com/MetaMask/metamask-mobile/assets/106310394/ca9c1e5f-18f2-4c56-afeb-43c52825fc2b

File: app/core/Vault.js [hunk 1]
```diff
@@ -36,7 +36,6 @@ export const restoreLedgerKeyring = async (keyring) => {
       (await getLedgerKeyring()).deserialize(serializedLedgerKeyring);
 
       await KeyringController.persistAllKeyrings();
-      KeyringController.updateIdentities(await KeyringController.getAccounts());
```
Comment (Gudahtt) [inline app/core/Vault.js:39]: It looks like we still need an explicit "Update identities" call in this circumstance. I thought this was unnecessary, but hadn't realized that the necessary change in the PreferencesController wasn't released until v7 and we're still on v4 here (see [this note](https://github.com/MetaMask/core/blob/main/packages/preferences-controller/CHANGELOG.md#700) about the state synchronization). Sorry for the confusion!

Instead I'd recommend something like this:

```
// TODO: Remove after updating `@metamask/preferences-controller` to v7
Engine.context.PreferencesController.updateIdentities(await KeyringController.getAccounts())
```

File: app/core/Ledger/Ledger.ts [hunk 2]
```diff
@@ -95,13 +95,10 @@ export const closeRunningAppOnLedger = async (): Promise<void> => {
  */
 export const forgetLedger = async (): Promise<void> => {
   const keyringController = Engine.context.KeyringController;
-  const preferencesController = Engine.context.PreferencesController;
+
   const keyring = await getLedgerKeyring();
   keyring.forgetDevice();
 
-  const accounts: string[] = await keyringController.getAccounts();
-  preferencesController.setSelectedAddress(accounts[0]);
```
Comment (Gudahtt) [inline app/core/Ledger/Ledger.ts:103]: The preferences state isn't getting updated properly here either, so I'd recommend the same thing as in the other file: 

```
// TODO: Remove after updating `@metamask/preferences-controller` to v7
Engine.context.PreferencesController.updateIdentities(await KeyringController.getAccounts())
```

The reason being that we need the PreferencesController to update the identity state, so the removed accounts are no longer present. Switching the selected account alone is not sufficient, because the removed account is still present in state and can be switched back to.

Updating identities will trigger a selected account update if necessary, so we don't need to make that switch here.

File: app/core/Vault.js (hunk 1 above)
Comment (dawnseeker8) [reply app/core/Vault.js:39]: i have done the code change base on your comments.

File: app/core/Ledger/Ledger.ts (hunk 2 above)
Comment (dawnseeker8) [reply app/core/Ledger/Ledger.ts:103]: I have done the code change base on your comment, thank you very much.

**Review by Gudahtt — APPROVED** [review]

**Comment by vivek-consensys** [comment]
Bitrise build: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/473efed9-4db1-4fde-b399-cb0cd4e385a5

**Comment by vivek-consensys** [comment]
Tested flows and working as expected on Samsung S21 using Android 13. 

Change password flow:-

https://github.com/MetaMask/metamask-mobile/assets/106310394/6f092776-b027-4c09-bc06-0a14a571fbb2

Forget Ledger device flow:- 

https://github.com/MetaMask/metamask-mobile/assets/106310394/7f442572-580d-4932-b99f-71425f65ed07
