### PR TITLE
fix: cp-7.55.0 use home page network filter for default swaps pair

### LINKED ISSUE #19130: [Bug]: Unified Swaps bugs
### Describe the bug

1. Network and tokens are preselected in Swap screen after network switch. 
User has to manually select token on another network, after that app is on the home screen again and user has to initiate Swap one more time.

2. Sometimes user is not redirected to home screen, and screen looks like Bridge tx while screens says it's Swap. Quotes are not fetched.

3. Selecting token on another network through networks picker results in Bridge tx.

### Expected behavior

1. Preselected values:

https://github.com/user-attachments/assets/5d4036c4-7655-4543-b1f6-758db1d8879b

2.  Weird Swap / Bridge screen

https://github.com/user-attachments/assets/d4c0ae2e-41fd-4de8-a14b-e997a0fd2a20

3.  Bridge when trying to do Swap:

https://github.com/user-attachments/assets/379f0060-faac-49b5-acd2-d2bb1f7c4518

### Screenshots/Recordings

1. Preselected values:

https://github.com/user-attachments/assets/317e22ef-948a-4048-b0d5-b317f21f39b9

2.  Weird Swap / Bridge screen:

https://github.com/user-attachments/assets/ce2f98ba-ddf2-4e60-9e53-e4d1a1106c05

3. Bridge when trying to do Swap:

https://github.com/user-attachments/assets/c541d4ea-6f4b-4f05-b6e5-a5e427c62665

### Steps to reproduce

1. Submit swap
2. Switch networks
3. Submit swap again

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.55.0. (2343)

### Build type

None

### Device

Samsung S24 +

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by bfullam**
## **Description**
This PR syncs the swaps UI with the network filter on the home page. If a user has a specific network selected in the filter, the swaps UI will populate with default tokens from that network. If the user has "popular networks" selected, we fallback to ETH <> USDC on Mainnet as the default pair.

## **Changelog**

CHANGELOG entry: Fixed a bug where the initial swap pairs were out of sync with the home page network filter

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/19130

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Bridge/hooks/useSwapBridgeNavigation/index.ts [hunk 1]
```diff
@@ -76,7 +102,9 @@ export const useSwapBridgeNavigation = ({
               symbol: bridgeSourceNativeAsset.symbol,
               image: bridgeSourceNativeAsset.iconUrl ?? '',
               decimals: bridgeSourceNativeAsset.decimals,
-              chainId: selectedChainId,
+              chainId: isSolanaChainId(effectiveChainId)
```
Comment (SteP-n-s) [inline app/components/UI/Bridge/hooks/useSwapBridgeNavigation/index.ts]: We probably need to add a @TODO here now that more non-EVM chains are going to be added (BTC, Tron).

**Review by SteP-n-s — DISMISSED** [review]

File: app/components/UI/Bridge/hooks/useSwapBridgeNavigation/index.ts (hunk 1 above)
Comment (bfullam) [reply app/components/UI/Bridge/hooks/useSwapBridgeNavigation/index.ts]: Agreed. Added

**Review by SteP-n-s — APPROVED** [review]

**Review by infiniteflower — APPROVED** [review]
