### PR TITLE
fix: check isNative to determine if a token is a gas token

### LINKED ISSUE #12855: [Bug]: Sending transaction from the token details page for POL, BNB, and AVAX, there appears to be an issue with balance detection, resulting in an 'insufficient funds' warning
### Describe the bug

When initiating a `Send `transaction from the token details page for POL, BNB, and AVAX (on native chains), there appears to be an issue with balance detection, resulting in an `Insufficient funds` warning. This occurs irrespective of whether the transaction is started from the `Current` or `All Networks` view. The balance for these tokens is accurately detected within both the `Send` and `Swap` flows

### Expected behavior

Balances are accurately detected for all tokens.

### Screenshots/Recordings

https://github.com/user-attachments/assets/9e5b18a8-134e-4adf-a678-405b7f3376fd

### Steps to reproduce

1. Go to the `Token details` page for POL, BNB or AVAX
2. Click `Send`
3. Observe that token balance is displayed as 0

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

v7.38.0(1523)

### Build type

None

### Device

Samsung S24+, iPhone 15

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by bfullam**
## **Description**

This PR fixes an issue with sending native gas tokens on chains where the gas token is not ETH.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12855

## **Manual testing steps**

1. Go to Avalanche
2. Make sure you have some balance of AVAX (the native gas token)
1. Go to Send
3. Make sure native gas token is selected
4. Try to send some AVAX < your total balance
5. You should not see any warnings about not having enough balance

Do the same thing but on Arbitrum (native gas token is ETH)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sleepytanya** [comment]
Bitrise build: https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/50335cabeb8af2bb

Correctly detected balance for AVAX, BNB and POL:


https://github.com/user-attachments/assets/ef8fc5b0-0c2d-456b-a3b8-466f9e3148d8

File: app/components/Views/confirmations/SendFlow/Confirm/index.js [hunk 1]
```diff
@@ -427,7 +428,7 @@ class Confirm extends PureComponent {
      * Ref.: https://github.com/MetaMask/metamask-mobile/pull/3989#issuecomment-1367558394
      */
     if (
-      selectedAsset.isETH ||
+      isNativeToken(selectedAsset.isETH, selectedAsset.isNative) ||
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/SendFlow/Confirm/index.js:431]: What's the conceptual difference between `isETH` and `isNative`?

It seems we're updating every usage of `isETH` in this file so I'm wondering if there's a conceptual overlap?

File: app/components/Views/confirmations/utils/generic.ts [hunk 2]
```diff
@@ -11,3 +11,5 @@ export const getHostFromUrl = (url: string) => {
   }
   return;
 };
+
+export const isNativeToken = (isETH: boolean, isNative: boolean) => isETH || isNative;
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/utils/generic.ts:15]: Does this util add any clarity, or is it making the logic more ambiguous since it's just encapsulating an `OR`?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: app/components/Views/confirmations/utils/generic.ts (hunk 2 above)
Comment (matthewwalsh0) [reply app/components/Views/confirmations/utils/generic.ts:15]: In that case, would it be more valuable to accept a `selectedAsset` object?

File: app/components/Views/confirmations/SendFlow/Confirm/index.js (hunk 1 above)
Comment (matthewwalsh0) [reply app/components/Views/confirmations/SendFlow/Confirm/index.js:431]: I'm not sure what value we get by checking if the native ticker is literally `ETH`.

I've always assumed `isETH` is `true` if it's the native balance, regardless of the ticker. So I wonder if that got lost somewhere along the way.

For now, could we exclusively use `isNative` for clarity? Should it not include all `isETH` cases also?

File: app/components/Views/confirmations/utils/generic.ts (hunk 2 above)
Comment (bfullam) [reply app/components/Views/confirmations/utils/generic.ts]: Agreed, that's definitely cleaner. Done 🤝

File: app/components/Views/confirmations/SendFlow/Confirm/index.js (hunk 1 above)
Comment (bfullam) [reply app/components/Views/confirmations/SendFlow/Confirm/index.js]: Agreed that `isETH` being based on the ticker is odd, not sure why/when that decision was made.

Addressed the necessity of checking isETH in your comment thread and applied the suggested changes 👌

File: app/components/Views/confirmations/utils/generic.ts [hunk 3]
```diff
@@ -11,3 +12,5 @@ export const getHostFromUrl = (url: string) => {
   }
   return;
 };
+
+export const isNativeToken = (selectedAsset: TokenI) => selectedAsset.isNative || selectedAsset.isETH;
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/utils/generic.ts:16]: Worth investigating in future if and why `isETH` is required.

**Review by matthewwalsh0 — APPROVED** [review]

File: app/components/Views/confirmations/utils/generic.ts (hunk 3 above)
Comment (bfullam) [reply app/components/Views/confirmations/utils/generic.ts:16]: Agreed!
