### PR TITLE
[FIX] Fixes touch area of a close button and aligned the button

### LINKED ISSUE #3557: Touch area of the close button is too small and button is not aligned
**Describe the bug**
When requesting payment with QR Code, the touch area of the close button is too small and not aligned.

**Screenshots**

Screen Shot 2022-01-10 at 23 07 41

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Receive and request payment
2. Select the asset to request and enter the amount
3. Click on QR Code
4. See the error

**Expected behavior**
The close button should be aligned with the text and increase its touch area

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by blackdevelopa**
**Description**

When requesting payment with QR Code, the touch area of the close button is too small and not aligned. This PR fixes both

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #3557

### CODE REVIEW

File: app/components/UI/PaymentRequestSuccess/index.js [hunk 1]
```diff
@@ -124,11 +123,14 @@ const styles = StyleSheet.create({
 	},
 	titleQr: {
 		flexDirection: 'row',
+		alignItems: 'center',
+		marginBottom: Device.isIos() ? 8 : 10,
```
Comment (andreahaku) [inline app/components/UI/PaymentRequestSuccess/index.js:127]: Maybe you can create a constant like:
`const isIos = Device.isIos();`
and use this here and below (line 131) so that this doesn't have to be called twice ;)

**Review by andreahaku — COMMENTED** [review]
I think there's no need to include `yarn.lock` and `Podfile.lock` in the PR. It'd be better to commit only files related to the task. They can be included if you update/add/remove a dependency.

File: app/components/UI/PaymentRequestSuccess/index.js (hunk 1 above)
Comment (blackdevelopa) [reply app/components/UI/PaymentRequestSuccess/index.js]: Thank you. Updated.

**Comment by blackdevelopa** [comment]
> I think there's no need to include `yarn.lock` and `Podfile.lock` in the PR. It'd be better to commit only files related to the task. They can be included if you update/add/remove a dependency.


Thank you. Updated.

**Review by andreahaku — APPROVED** [review]

**Review by cortisiko — APPROVED** [review]
🌮 🌮 🌮 🌮
