### PR TITLE
fix: cp-7.41.0 Prevent flickering on `RetryModal`

### LINKED ISSUE #13547: [Bug]: After an attempt to cancel a transaction, users are spammed with the "Failed Transaction Update" banner
### Describe the bug

Following an attempt to cancel a transaction, users experience repeated `Failed Transaction Update` message.
 Even after selecting the option to cancel, these notifications continue to appear for some time. 

### Expected behavior

The notification system stops displaying messages in a timely manner

### Screenshots/Recordings

https://github.com/user-attachments/assets/4428a947-485a-41b1-9e5d-c9359abb71bc

https://github.com/user-attachments/assets/669564dc-892c-4baf-b808-4f6a29c4d8ee

Image

### Steps to reproduce

1. Send a transaction with low gas
2. Cancel the tx

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.41.0 (1557)

### Build type

None

### Device

iPhone 15, Samsung S24 Ultra

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR relocates `RetryModal` to stop flickering in `TransactionsHistory` screen.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/13547

## **Manual testing steps**

See issue https://github.com/MetaMask/metamask-mobile/issues/13547

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Transactions/index.js [hunk 1]
```diff
@@ -885,6 +878,12 @@ class Transactions extends PureComponent {
           {(this.state.speedUp1559IsOpen || this.state.cancel1559IsOpen) &&
             this.renderUpdateTxEIP1559Gas(this.state.cancel1559IsOpen)}
         </View>
+        <RetryModal
```
Comment (OGPoyraz) [inline app/components/UI/Transactions/index.js:881]: Line 876 is having numerous re-renders. This PR is just preventing the `RetryModal` to not get those re-renders. So this is temporarily fixing the issue. I believe `app/components/UI/Transactions/index.js` needs a strong refactor.

**Comment by sleepytanya** [comment]
@OGPoyraz 

Fixed!

QA builds: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/0ff72647-0564-4000-b60d-0555ee0f3a23?tab=artifacts

Android:


https://github.com/user-attachments/assets/fadaea6f-842f-422c-927a-f25c390b7a27

iOS:


https://github.com/user-attachments/assets/8f3a11d1-4975-446c-b1de-5d8023504b98

File: app/components/Views/Asset/__snapshots__/index.test.js.snap [hunk 2]
```diff
@@ -36,6 +36,35 @@ exports[`Asset should not display swaps button if the asset is not allowed 1`] =
       />
     </View>
   </View>
+  <Modal
```
Comment (OGPoyraz) [inline app/components/Views/Asset/__snapshots__/index.test.js.snap:39]: This is an expected snapshot update since Modal is moved over to root of `Transactions`

**Review by matthewwalsh0 — APPROVED** [review]

**Review by salimtb — APPROVED** [review]
Assets changes LGTM
