### PR TITLE
fix(snaps): Refactor `SnapBridge` to use `SelectedNetworkController`

### LINKED ISSUE #22419: [Bug]: Couldn't resolve ENS when network manager selection is different than Ethereum Mainnet
**Describe the bug**

If the network manager selection is a single network and any other network than Ethereum Mainnet, then sending to an ENS address results in error `Couldn't resolve ENS name`

**Expected behavior**

No error

**Screenshots/Recordings**

https://github.com/user-attachments/assets/37d00bf6-349b-4c2c-8d55-5d7502201623

**Steps to reproduce**

1. Select Linea network or any other network except Ethereum Mainnet
2. Go to send flow
3. Click ETH token
4. Enter amount
5. Type ENS address
6. Notice error Couldn't resolve ENS name
7. Go back to home page
8. Select All popular networks or Ethereum Mainnet in the network manager
9. Repeat steps 2,3,4,5
10. Notice there is no error and send is possible to ENS address

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

7.59.0

**Build type**

None

**Device**

Pixel 6 Pro, iPhone 15

**Operating system**

iOS, Android

### PR DESCRIPTION
**Pull request by GuillaumeRx**
## **Description**

This PR refactors the `SnapBridge` to use `SelectedNetworkController` to create a provider proxy. It also removes a lot of unnecessary logic. This fixes an issue where the snap couldn't switch the network.

## **Changelog**

CHANGELOG entry: Fix snap `wallet_switchEthereumChain`

## **Related issues**

Fixes: #22419

## **Manual testing steps**

1. Set the selected network to any other network than ethereum mainnet (like polygon, base,...)
2. Go to the send flow
3. Expect a valid ENS name to be resolved when trying to send ETH on mainnet

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Refactors SnapBridge to source provider/block tracker from SelectedNetworkController, streamlines the JSON-RPC middleware stack and stream wiring, and types snapId as SnapId in init.
> 
> - **Snaps**:
>   - **`SnapBridge` refactor**:
>     - Use `SelectedNetworkController.getProviderAndBlockTracker(snapId)` and add `createSelectedNetworkMiddleware`.
>     - Rebuild JSON-RPC engine: origin middleware → selected network → filter/subscription polyfills → preinstalled snaps middleware (when applicable) → permission middleware → snaps method middleware → user RPC middleware (with `#getProviderState`) → forward via `providerAsMiddleware(proxy.provider)`.
>     - Replace custom multiplexing with `setupMultiplex` and `pump`; add concise logging; adopt strong typings (`SnapId`, `JsonRpcMiddleware`, `InternalAccount`); remove legacy proxy/network-version logic.
> - **Engine**:
>   - In `controllers/snaps/execution-service-init.ts`, pass `snapId` as `SnapId` when creating `SnapBridge`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 78ef6013069b118513c923caac7e02165ebeeaea. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/core/Snaps/SnapBridge.ts [hunk 1]
```diff
@@ -1,172 +1,180 @@
...
     snapId,
     connectionStream,
     getRPCMethodMiddleware,
-  }: ISnapBridgeProps) {
-    Logger.log(
-      '[SNAP BRIDGE LOG] Engine+setupSnapProvider: Setup bridge for Snap',
-      snapId,
-    );
+  }: {
+    snapId: string;
```
Comment (FrederikBolding) [inline app/core/Snaps/SnapBridge.ts]:
```suggestion
    snapId: SnapId;
```

Then we don't need to cast later

Comment (GuillaumeRx) [reply app/core/Snaps/SnapBridge.ts]: We'll then need to cast in `execution-service-init.ts` :sweat_smile:

File: app/core/Snaps/SnapBridge.ts [hunk 2]
```diff
@@ -1,172 +1,180 @@
...
-  connectionStream: Duplex;
-  // TODO: Replace "any" with type
-  // eslint-disable-next-line @typescript-eslint/no-explicit-any
-  getRPCMethodMiddleware: (args: any) => any;
-}
-
+/**
+ * Type definition for the GetRPCMethodMiddleware function.
+ */
+type GetRPCMethodMiddleware = ({
```
Comment (FrederikBolding) [inline app/core/Snaps/SnapBridge.ts:34]: Does a type not exist for this elsewhere?

File: app/core/Snaps/SnapBridge.ts (hunk 1 above)
Comment (FrederikBolding) [reply app/core/Snaps/SnapBridge.ts]: That sounds acceptable to me

File: app/core/Snaps/SnapBridge.ts [hunk 3]
```diff
@@ -1,172 +1,180 @@
...
 
-    // TODO: Replace "any" with type
-    // eslint-disable-next-line @typescript-eslint/no-explicit-any
-    const { NetworkController } = Engine.context as any;
+  /**
+   * Gets the network state for the provider based on the origin.
+   * @param origin - The origin of the request.
+   * @returns An object containing the chain ID and network version.
+   */
+  async #getProviderNetworkState(origin: string) {
```
Comment (FrederikBolding) [inline app/core/Snaps/SnapBridge.ts]: Snaps do not request the provider network state, so we can perhaps eliminate this entire thing too

File: app/core/Snaps/SnapBridge.ts (hunk 2 above)
Comment (GuillaumeRx) [reply app/core/Snaps/SnapBridge.ts:34]: Nope, our `getRPCMethodMiddleware` function only takes part of the params that the original `getRPCMiddleware` function takes: https://github.com/MetaMask/metamask-mobile/blob/13ce6904311b0cd0e0efe565b5b788874c4c6e96/app/core/Engine/controllers/snaps/execution-service-init.ts#L44

File: app/core/Snaps/SnapBridge.ts [hunk 4]
```diff
@@ -205,55 +213,35 @@ export default class SnapBridge {
...
+  setupProviderConnection() {
+    Logger.log('[SNAP BRIDGE] Setting up provider connection');
 
-  async getProviderNetworkState(origin: string) {
-    const networkClientId = Engine.controllerMessenger.call(
-      'SelectedNetworkController:getNetworkClientIdForDomain',
-      origin,
+    const stream = setupMultiplex(this.stream).createStream(
+      'metamask-provider',
     );
```
Comment (FrederikBolding) [inline app/core/Snaps/SnapBridge.ts]:
```suggestion
    const mux = setupMultiplex(this.stream);

    const stream = mux.createStream(
      'metamask-provider',
    );
```

Readability nit

File: app/core/Snaps/SnapBridge.ts [hunk 5]
```diff
@@ -1,171 +1,124 @@
...
-  async getProviderState() {
+  /**
+   * Gets the provider state including unlock status and network information.
+   * @returns An object containing the provider state.
+   */
+  async #getProviderState() {
     return {
-      isUnlocked: this.isUnlocked(),
-      ...(await this.getProviderNetworkState(this.snapId)),
+      isUnlocked: Engine.context.KeyringController.isUnlocked(),
```
[the remark this answers is not in the document]
Comment (GuillaumeRx) [reply app/core/Snaps/SnapBridge.ts:77]: Intended

File: app/core/Snaps/SnapBridge.ts [hunk 6]
```diff
@@ -1,171 +1,124 @@
...
-
-  #mux: typeof ObjectMultiplex;
-  // TODO: Replace "any" with type
-  // eslint-disable-next-line @typescript-eslint/no-explicit-any
-  #providerProxy: any;
-  // TODO: Replace "any" with type
-  // eslint-disable-next-line @typescript-eslint/no-explicit-any
-  #blockTrackerProxy: any;
+  getRPCMethodMiddleware: GetRPCMethodMiddleware;
+  deprecatedNetworkVersions: Record<string, string | null> = {};
```
Comment (FrederikBolding) [inline app/core/Snaps/SnapBridge.ts]:
```suggestion
```
Unused now

File: app/core/Snaps/SnapBridge.ts [hunk 7]
```diff
@@ -1,171 +1,123 @@
...
-    }
-    this.blockTracker = blockTracker;
-  };
-
-  async getProviderState() {
+  /**
+   * Gets the provider state.
+   * @returns An object containing the provider state.
+   */
+  async #getProviderState() {
```
Comment (FrederikBolding) [inline app/core/Snaps/SnapBridge.ts]: Does not need to be async anymore
```suggestion
  #getProviderState() {
```

File: app/core/Snaps/SnapBridge.ts [hunk 8]
```diff
@@ -1,171 +1,123 @@
...
+ *
+ * @param params - The parameters for the SnapBridge.
+ * @param params.snapId - The ID of the Snap.
+ * @param params.connectionStream - The stream to connect to the Snap.
+ * @param params.getRPCMethodMiddleware - A function to get the RPC method middleware.
+ */
 export default class SnapBridge {
-  snapId: string;
+  snapId: SnapId;
   stream: Duplex;
```
Comment (FrederikBolding) [inline app/core/Snaps/SnapBridge.ts]: Can we make these hash private?

File: app/core/Snaps/SnapBridge.ts [hunk 9]
```diff
@@ -1,259 +1,191 @@
...
 import { Duplex } from 'stream';
+// @ts-expect-error - No types declarations
+import pump from 'pump';
+
+import { JsonRpcEngine, JsonRpcMiddleware } from '@metamask/json-rpc-engine';
+// @ts-expect-error - No types declarations
+import createFilterMiddleware from '@metamask/eth-json-rpc-filters';
+// @ts-expect-error - No types declarations
+import createSubscriptionManager from '@metamask/eth-json-rpc-filters/subscriptionManager';
+import { JsonRpcParams } from '@metamask/eth-query';
```
Comment (FrederikBolding) [inline app/core/Snaps/SnapBridge.ts]:
```suggestion
import { JsonRpcParams } from '@metamask/utils';
```

**Review by FrederikBolding — DISMISSED** [review]

**Review by FrederikBolding — APPROVED** [review]
