### PR TITLE
fix: error validating wallet connect signature with security provider

### LINKED ISSUE #9778: [Bug]: ppom fails to validate signature requests coming from wallet connect
### Describe the bug

Blockaid's error message is being displayed for signature requests received via wallet connect.

Note: transactions request received via wallet connect seem to work correctly. 

Note: this is affecting [8% of signature requests](https://mixpanel.com/s/2xRaCs) and [causing 75% of the errors on mobile](https://mixpanel.com/s/4hJZ9J).

### Expected behavior

No error warning is displayed and security alerts work correctly. 

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Go to opensea.io on a mobile browser (not MM's)
2. Click on `login`
3. Select walletconnect
4. Select MetaMask
5. Approve the connection request
6. Navigate back to the browser and wait for opensea to trigger a signature request
7. Navigate back to MM to see the signature request
8. Notice the error warning displayed

This can also be reproduced with our test dapp.

### Error messages or log output

_No response_

### Version

7.22.0

### Build type

None

### Device

Iphone

### Operating system

iOS

### Additional context

I was checking [metrics for this](https://mixpanel.com/s/3IjeYe) now and it seems this issue started with mobile v7.21 release and got significantly worse on 7.22.

On what could have introduced it on [7.21](https://www.notion.so/metamask-consensys/7-21-0-af785cbfe2204a6d9d6991d9bf8c1548?pvs=4):

- updating ppom to v1.4.5 - this was the only change made by confirmations on that release

- changes made to wc integration:
- Wc fixes + ux improvements ([#9188](https://github.com/MetaMask/metamask-mobile/pull/9188))
- Wc connections and permissions system network improvement ([#9150](https://github.com/MetaMask/metamask-mobile/pull/9150))
- Sdk connection dependency upgrade ([#9045](https://github.com/MetaMask/metamask-mobile/pull/9045))

- Signature controller update to v6.0.0 ([#9166](https://github.com/MetaMask/metamask-mobile/pull/9166))

On what could have made it worse on [7.22](https://www.notion.so/metamask-consensys/7-22-0-94f1675c5e984d8eaaf1e23af297052e?pvs=4):

- [#9247](https://github.com/MetaMask/metamask-mobile/pull/9247): Updated siwe parse to v2.1.0.

- [#9283](https://github.com/MetaMask/metamask-mobile/pull/9283): Added missing walletConnect prop.

### Severity

_No response_

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## **Description**

When connected to a dApp via WalletConnect, security provider validation on signature requests was unable to complete and displaying a warning.

This appears to be due to a change in the `WalletConnectV2` request handler causing the JSON-RPC params to be converted to an object, as opposed to the original array. This is non-standard and therefore the PPOM was throwing with the following error:

`Error validating JSON RPC using PPOM: Error: invalid type: map, expected a sequence at line 1 column 882` 

## **Related issues**

Fixes: #9778 

## **Manual testing steps**

See issue.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/WalletConnect/WalletConnectV2.ts [hunk 1]
```diff
@@ -373,13 +373,7 @@ class WalletConnect2Session {
     let method = requestEvent.params.request.method;
     const chainId = parseInt(requestEvent.params.chainId);
 
-    const beforeMethodParams = requestEvent.params.request.params as any;
-    // Replace blockExplorerUrls with blockExplorerUrl
-    const methodParams = {
-      ...beforeMethodParams,
-      // blockExplorerUrl: beforeMethodParams.blockExplorerUrls,
```
Comment (matthewwalsh0) [inline app/core/WalletConnect/WalletConnectV2.ts:380]: I couldn't identify a need for this, and it appears the params that were being overridden have been commented out.

Though this is an array, so any properties would likely need to be set on the first param, depending on the method.

**Review by OGPoyraz — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Comment by sleepytanya** [comment]
[Bitrise build](https://app.bitrise.io/build/6b3fc70e-a6fb-4b4c-9312-2994ab46b9da?tab=artifacts), Samsung S24+ (physical device), Android 14.

When attempting to connect OpenSea.io with MetaMask via mobile browser (not MM's browser), users are currently being redirected to Google Play instead of establishing a direct connection:


https://github.com/MetaMask/metamask-mobile/assets/104780023/807e4391-7802-498a-9780-e0f005a7dcd6

**Comment by sleepytanya** [comment]
Hi @christopherferreira9 :hi_wave:!

Thank you for your response, I really appreciate the attention.

Here is production v7.23.0(1333) - user is redirected to the MM browser:



https://github.com/MetaMask/metamask-mobile/assets/104780023/d92fd013-806f-46bc-8f2d-5c15da711150

 But now I have another question - shouldn't we also see the MM 'connect account' opened instead of just opensea.io in the MM browser? Or I misremembering things.

@bschorchit

File: app/core/WalletConnect/WalletConnectV2.ts (hunk 1 above)
Comment (abretonc7s) [reply app/core/WalletConnect/WalletConnectV2.ts:380]: we can remove it, must have been left by mistake

**Review by abretonc7s — APPROVED** [review]

**Comment by sleepytanya** [comment]
Security provider validation on signature requests  works as anticipated, connection can be successfully made via `Wallet Connect` and `MetaMask`.


https://github.com/MetaMask/metamask-mobile/assets/104780023/9fa51879-1ac3-468f-bae9-5655bbb02dac
