### PR TITLE
fix: adjust the apiLogoUrl logic to handles cases when icon is an object with uri key

### LINKED ISSUE #7920: [Bug]: Crash when signing message
### Describe the bug

The application crashes when signing an `eth_signTypedData_v4` message on the main branch. Various Bitrise test runs hint that the same is true of other types of messages as well.

### Expected behavior

The application should not crash when signing a message

### Screenshots/Recordings

Screenshot 2023-11-23 at 10 11 02 AM

### Steps to reproduce

* Navigate to https://metamask.github.io/test-dapp using a build from `main` (tested with https://github.com/MetaMask/metamask-mobile/commit/69c79dfa4ae7ea495fc454669363ceaffefed494)
  * I have tested this with a development build, I am not sure if that matters for this reproduction though
* Connect an account to the dapp
* Trigger an `eth_signTypedData_v4` signature, and the application with crash

### Error messages or log output

Initially the error shown is `Attempting to define a property on object that is not extensible`. However this error is itself caused by the underlying error, and is related to `ses`.

I removed `ses` locally to find the underlying error here, which was `_imageSource$uri.endsWith is not a function`. It is from this line: https://github.com/MetaMask/metamask-mobile/blob/69c79dfa4ae7ea495fc454669363ceaffefed494/app/util/favicon/index.ts#L163

### Version

69c79dfa4ae7ea495fc454669363ceaffefed494

### Build type

None

### Device

iPhone 13 Pro simulator

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by omridan159**
## **Description**

Adjust the `apiLogoUrl` logic to handles cases when `icon` is an object with `uri` key

## **Related issues**

Fixes: #

## **Manual testing steps**

1. Tested using the https://metamask.github.io/test-dapp/ with connect and personal sign operation

### **After**

https://github.com/MetaMask/metamask-mobile/assets/61094771/c8ee8a80-e1f3-43c1-a509-943d7cedd159

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by abretonc7s — DISMISSED** [review]

**Review by abretonc7s — DISMISSED** [review]

**Comment by Gudahtt** [comment]
This seems to be related to #7920

Reminder to describe the _purpose_ of the change in the PR title/description, not just _what_ has changed. I didn't realize this was related to fixing a crash at first. See here for more about that: https://github.com/MetaMask/contributor-docs/blob/main/docs/pull-requests.md#use-the-description-to-explain-the-need-and-solution

**Review by abretonc7s — APPROVED** [review]

**Comment by christopherferreira9** [comment]
Fixed for both Android and iOS

File: app/components/UI/WebsiteIcon/index.js [hunk 1]
```diff
@@ -62,7 +62,7 @@ class WebsiteIcon extends PureComponent {
     /**
      * Icon image to use, this substitutes getting the icon from the url
      */
-    icon: PropTypes.string,
+    icon: PropTypes.oneOfType([PropTypes.string | PropTypes.object]),
```
Comment (wachunei) [inline app/components/UI/WebsiteIcon/index.js:65]: This is wrong, this is returning a number as a bitwise operation result.

Comment (wachunei) [reply app/components/UI/WebsiteIcon/index.js:65]: fixed in https://github.com/MetaMask/metamask-mobile/pull/7953
