### PR TITLE
Fix/respect custom spend limit on dapp approve modal

### LINKED ISSUE #2380: Custom spend limit not respected on dapp approve modal
**Describe the bug**

When you set a custom spend limit, it doesn't save

**Screenshots**

Screen Shot 2021-03-12 at 7 13 39 PM

Seen here = http://recordit.co/vKqFMtbfm4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to uniswap
2. Set up an ERC20 to x with a token you need to approve
3. On approve modal edit permission 
4. Change the custom spend limit and save

**Expected behavior**

Custom spend limit should be respected

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by rickycodes**
**Description**

This gets the custom spend limit working for dapp approve again:

https://user-images.githubusercontent.com/675259/115463410-c80a9f00-a1f9-11eb-9168-094bd049b810.mp4

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2380

### CODE REVIEW

File: app/components/UI/ApproveTransactionReview/index.js [hunk 1]
```diff
@@ -419,16 +418,22 @@ class ApproveTransactionReview extends PureComponent {
...
+			).toString(10);
+
+			const approvalData = generateApproveData({
+				spender: spenderAddress,
+				value: Number(uint).toString(16)
+			});
+			const newApprovalTransaction = { ...transaction, data: approvalData };
+			setTransactionObject(newApprovalTransaction);
+		} catch (e) {
+			//
```
Comment (sethkfman) [inline app/components/UI/ApproveTransactionReview/index.js:435]: Should we log something in Sentry?

Comment (wachunei) [reply app/components/UI/ApproveTransactionReview/index.js:435]: If I recall correctly this would catch issues with a specific case regarding the number being used to create the approval transaction. I'd say we should log something to keep track of the number of times it happens, thoughts @rickycodes ?

File: app/components/UI/ApproveTransactionReview/EditPermission/index.js [hunk 2]
```diff
@@ -106,33 +108,44 @@ function EditPermission({
 	onPressSpendLimitCustomSelected,
 	toggleEditPermission
 }) {
-	const [approvalSet, setApprovalSet] = useState(false);
+	const [initialState] = useState(() => ({
+		spendLimitUnlimitedSelected,
+		spendLimitCustomValue
+	}));
```
Comment (andrepimenta) [inline app/components/UI/ApproveTransactionReview/EditPermission/index.js:114]: I think here you can simplify?
`useState({spendLimitUnlimitedSelected, spendLimitCustomValue})`

File: app/components/UI/ApproveTransactionReview/EditPermission/index.js [hunk 3]
```diff
@@ -106,33 +108,44 @@ function EditPermission({
...
 
 	const displayErrorMessage = useMemo(
 		() => !spendLimitUnlimitedSelected && minimumSpendLimit > spendLimitCustomValue,
```
Comment (andrepimenta) [inline app/components/UI/ApproveTransactionReview/EditPermission/index.js:117]: `minimumSpendLimit` seems to be a string? Any problem doing this comparison?

File: app/components/UI/ApproveTransactionReview/index.js [hunk 4]
```diff
@@ -38,7 +38,7 @@ import { withNavigation } from 'react-navigation';
 import { getNetworkName, isMainNet } from '../../../util/networks';
 import scaling from '../../../util/scaling';
 import { capitalize } from '../../../util/general';
-import EditPermission from './EditPermission';
+import EditPermission, { MINIMUM_VALUE } from './EditPermission';
```
Comment (andrepimenta) [inline app/components/UI/ApproveTransactionReview/index.js:41]: Should MINIMUM_VALUE be on the constants util?

**Review by andrepimenta — CHANGES_REQUESTED** [review]

File: app/components/UI/ApproveTransactionReview/index.js (hunk 4 above)
Comment (rickycodes) [reply app/components/UI/ApproveTransactionReview/index.js:41]: It's only used for `EditPermission` so I think this is fine?

File: app/components/UI/ApproveTransactionReview/EditPermission/index.js (hunk 3 above)
Comment (rickycodes) [reply app/components/UI/ApproveTransactionReview/EditPermission/index.js:117]: should be fine:
```
> '2' > '1'
true
> '2' < '1'
false
```

**Comment by ibrahimtaveras00** [comment]
I tested Rinkeby uniswap.exchange and Ropsten https://ropsten.kyber.network and they both don't behave how our swaps behave, although I'm not sure if that's from the dapp side, and I can't confirm on prod as spend limit isn't respected.

Our swaps behavior: 
If you have 4 UNI and you approve 2, then swap 2, the next time you want to swap more UNI you will have to approve again

Dapps behavior:
just need to approve once, no matter what the custom spend limit is

**Review by ibrahimtaveras00 — APPROVED** [review]
👍🏽

**Review by andrepimenta — APPROVED** [review]
Only have one more thing: https://github.com/MetaMask/metamask-mobile/pull/2556/files#diff-07d844893596c7056d106bff7269585b347aaeea01f22e4ca5e3d57625974be3R111
Otherwise, looks good to me!
