### PR TITLE
fix: Fix/9662 account section disappears

### LINKED ISSUE #9662: [BUG] Account section disappears when app is idle with in-app browser web pages opened or closed
**Description:** 
The account selection drop-down disappears at the top of the Wallet screen while web pages are open and the user toggles between the in-app browser and the Wallet screen. The issue also occurs when the app is idle and reopened without any web pages open. 

The glitch eventually resolves on its own toggling between screens.

**Expected behavior:** 
The accounts drop-down is always displayed at the top of the Wallet home screen page, allowing the user to switch between accounts. 

**Recordings**: 

https://github.com/MetaMask/metamask-mobile/assets/22276767/b4bf811a-a24a-41ea-bcf6-01dc5d96ab7d

https://github.com/MetaMask/metamask-mobile/assets/22276767/763b314a-a2c7-427f-a165-b9d690356471

### PR DESCRIPTION
**Pull request by Cal-L**
## **Description**

This PR fixes the issue where the accounts section on the wallet screen disappears after re-authenticating post app auto lock. The main change happens in the `useAccounts` hook, where we are now grabbing the accounts from the `AccountsController` via Redux rather than from the `KeyringController` from the Engine context. We're also now fetching the selected account from the `AccountsController` as well. While the root issue isn't immediately clear, I suspect it has to do with the accounts temporarily disappearing from the KeyringController between lock/auth phases while the app is locked for an extended period of time. In any case, these changes mirror the changes that @owencraston is working on, which will eventually migrate most accounts data to be derived from the `AccountsController`. This fix can serve as a POC that the `AccountsController` is a reliable source of truth when referencing account information.

## **Related issues**

Fixes: #9662 #9279
## **Manual testing steps**

1. Import wallet via SRP
2. Check that phone is set to auto lock
3. Set MM app to immediate lock
4. Go to wallet screen
5. Wait for app to auto lock
6. Wait 5-10mins
7. Unlock phone and re-authenticate to MM
8. Notice account section is still intact on the wallet screen

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/10508597/27d7823b-1d1f-48a0-89ae-946cdcf6e853

### **After**

https://github.com/MetaMask/metamask-mobile/assets/10508597/e8ba2a56-ee2c-48bf-b602-46e62626f1f5

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [X] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [X] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/test/accountsControllerTestUtils.ts
Comment (Cal-L) [inline app/util/test/accountsControllerTestUtils.ts:1]: This file is carried over from @owencraston's refactor https://github.com/MetaMask/metamask-mobile/pull/9070

File: app/components/hooks/useAccounts/useAccounts.ts [hunk 1]
```diff
@@ -27,39 +26,43 @@ import {
...
     useState<EnsByAccountAddress>({});
-
-  const identities = useSelector(selectIdentities);
   const chainId = useSelector(selectChainId);
   const accountInfoByAddress = useSelector(selectAccounts, isEqual);
-  const selectedAddress = useSelector(selectSelectedAddress);
   const conversionRate = useSelector(selectConversionRate);
   const currentCurrency = useSelector(selectCurrentCurrency);
   const ticker = useSelector(selectTicker);
+  const internalAccounts = useSelector(selectInternalAccounts);
```
Comment (Cal-L) [inline app/components/hooks/useAccounts/useAccounts.ts:53]: Account controller selectors here replace fetching accounts from KeyringController and selected address from PreferencesController

File: app/components/UI/AccountSelectorList/AccountSelector.test.tsx
Comment (Cal-L) [inline app/components/UI/AccountSelectorList/AccountSelector.test.tsx:1]: Most of the files are just test file updates to be compatible with the accounts controller data

**Review by Cal-L — COMMENTED** [review]
Left comments for reference

File: app/util/test/accountsControllerTestUtils.ts
Comment (owencraston) [reply app/util/test/accountsControllerTestUtils.ts:1]: For context these functions are used in hundreds of files so we thought it was best to put them into a util.

File: app/selectors/accountsController/index.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
+import { AccountsControllerState } from '@metamask/accounts-controller';
+import { captureException } from '@sentry/react-native';
+import { createSelector } from 'reselect';
+import { RootState } from '../../reducers';
+
+const selectAccountsControllerState = (state: RootState) =>
+  state.engine.backgroundState.AccountsController;
+
+export const selectInternalAccounts = createSelector(
```
[the remark this answers is not in the document]
Comment (Cal-L) [reply app/selectors/accountsController/index.ts]: Updated!

File: app/selectors/accountsController.ts [hunk 3]
```diff
@@ -0,0 +1,30 @@
+import { AccountsControllerState } from '@metamask/accounts-controller';
+import { captureException } from '@sentry/react-native';
+import { createSelector } from 'reselect';
+import { RootState } from '../reducers';
+
+const selectAccountsControllerState = (state: RootState) =>
+  state.engine.backgroundState.AccountsController;
+
+export const selectInternalAccounts = createSelector(
```
Comment (owencraston) [inline app/selectors/accountsController.ts:9]: I realized that this is going to return a new object reference no matter what. This is not good for performance and usually these values are used at top levels of the app so it will have serious performance hits. Instead lets try something like this.

```ts
import { createDeepEqualSelector } from './util';

export const selectInternalAccounts = createDeepEqualSelector(
  (state) => state.accountsController.internalAccounts.accounts,
  (accounts) => Object.values(accounts),
);
```

Comment (Cal-L) [reply app/selectors/accountsController.ts]: Updated to use deep equal

**Comment by Cal-L** [comment]
Regression test run - https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/2cd1d690-7a48-4cea-9854-73c59ce6dc42

**Review by owencraston — APPROVED** [review]

File: app/components/hooks/useAccounts/useAccounts.ts [hunk 4]
```diff
@@ -27,39 +26,44 @@ import {
...
+  const selectedInternalAccount = useSelector(selectSelectedInternalAccount);
 
   const isMultiAccountBalancesEnabled = useSelector(
     selectIsMultiAccountBalancesEnabled,
   );
 
+  // Memoize checkBalanceErrorFn so it doesn't cause an infinite loop
+  const checkBalanceError = useCallback(
+    (balance: string) => checkBalanceErrorFn?.(balance),
```
Comment (tommasini) [inline app/components/hooks/useAccounts/useAccounts.ts:62]: I dont find this property being used anywhere where the useAccounts hook is used, I'm wondering if it's really needed

**Review by tommasini — APPROVED** [review]
LGTM! Just left a comment with a question

File: app/components/hooks/useAccounts/useAccounts.ts (hunk 4 above)
Comment (Cal-L) [reply app/components/hooks/useAccounts/useAccounts.ts:62]: It's used in the `AccountSelector` file

File: app/components/hooks/useAccounts/useAccounts.ts [hunk 5]
```diff
@@ -119,22 +123,20 @@ const useAccounts = ({
...
-    const keyrings: any[] = Engine.context.KeyringController.state.keyrings;
-    const flattenedAccounts: Account[] = keyrings.reduce((result, keyring) => {
-      const {
-        accounts: accountAddresses,
-        type,
-      }: { accounts: string[]; type: KeyringTypes } = keyring;
-      for (const index in accountAddresses) {
-        const checksummedAddress = toChecksumAddress(accountAddresses[index]);
-        const isSelected = selectedAddress === checksummedAddress;
+    const flattenedAccounts: Account[] = internalAccounts.map(
```
Comment (Gudahtt) [inline app/components/hooks/useAccounts/useAccounts.ts:126]: This change resulted in the account list being in a different order. The keyrings are ordered differently from the internal accounts. We've gone from "keyring order" to "internal account insertion order".

File: app/components/hooks/useAccounts/useAccounts.ts [hunk 6]
```diff
@@ -119,22 +123,20 @@ const useAccounts = ({
...
+        } = internalAccount;
+        const checksummedAddress = toChecksumAddress(address);
+        const isSelected = selectedInternalAccount.address === address;
         if (isSelected) {
-          selectedIndex = result.length;
+          selectedIndex = index;
         }
-        const identity = identities[checksummedAddress];
-        if (!identity) continue;
-        const { name } = identity;
```
Comment (Gudahtt) [inline app/components/hooks/useAccounts/useAccounts.ts:137]: We used to get the name from the `PreferencesController` state, on this line. Now we're getting it from the `AccountsController` state instead, on line 131 above.

Due to a separate bug, there are some users who have names set in the `PreferencesController` identities state, but not the `AccountsController` state. This change to `useAccounts` has resulted in these unsynced custom names no longer showing on the accounts list.
