### PR TITLE
fix: cp-7.53.0 select non-evm transactions irrespective of account

### LINKED ISSUE #18053: [Bug]: App crashes when user clicks on the info CTA of a Solana asset on the swap asset picker
### Describe the bug

When trying to access details of Solana tokens via the destination asset picker, the app crashes.

Issue is caused by the changes that took place on the `MultichainTransactionListItem` component through the introduction of `useMultichainTransactionDisplay`. PR can be found [here](https://github.com/MetaMask/metamask-mobile/pull/17446).

### Expected behavior

The asset details screen should open up without an issue.

### Screenshots/Recordings

https://github.com/user-attachments/assets/b992ccc9-2a56-4c49-8a01-bb91ae88c9ca

### Steps to reproduce

1. Select any evm network on the network selector
2. Go to swaps screen
3. Select the destination picker
4. Filter by Solana network
5. Click on any info icon

### Error messages or log output

```shell
TypeError: Cannot read property 'length' of undefined
```

### Detection stage

During release testing

### Version

7.53

### Build type

None

### Device

iPhone Pro 13

### Operating system

iOS

### Additional context

Transaction considers `to` and `from` properties to always be present on the top level of the object but there are transactions items that include these inside a `txParams` property. Example can be seen below:

```
{"blockNumber": "138451695", "chainId": "0xa", "hash": "0xf563e87a0fa699afb0a1afa8350901dc220e491051037de0fd1af89c5d181a62", "id": "26d38580-60bc-11f0-905a-d3e8c1406151", "isTransfer": true, "networkClientId": "afb6235a-765e-41a6-8308-7c86bd892172", "status": "confirmed", "time": 1752502167000, "toSmartContract": false, "transferInformation": {"amount": 1, "contractAddress": "0x4551cb34da2767626c7ce46a7a85b7628985086d"}, "txParams": {"chainId": "0xa", "data": "0x729ad39e", "from": "0x4a048bd0a8c8ab21b512bd1c9bc660ed5f5e6dbc", "gas": "0xaa2676", "gasPrice": "0x482e", "gasUsed": "0x8ca861", "nonce": "0x5ad0", "to": "0x2455a84cdc13ea853fab15498b4ca90c7e5c0c28", "value": "0x1"}, "type": "incoming", "verifiedOnBlockchain": false}
```

### Severity

_No response_

### PR DESCRIPTION
**Pull request by darioAnongba**
## **Description**

We currently alway fetch EVM transactions to only discard them if the account is a non EVM one and the asset is also a non EVM asset. Yet, when coming from the swaps view, the selected account can be an EVM account and the asset a non-EVM one, so we currently crash because we pass the EVM transactions to the non-EVM transaction list. To temporarily fix this, we should fetch non-EVM transactions depending on the asset, irrespective of the account being EVM or not.

This is only a temporary fix because the list of transactions will always be empty in this scenario since the account is not aligned with the asset. Only switching accounts will correctly display the transactions. 

## **Changelog**

CHANGELOG entry: fixes App crashes when user clicks on the info CTA of a non-EVM asset on the swap asset picker

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/18053

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by zone-live — APPROVED** [review]

**Review by aganglada — APPROVED** [review]

File: app/components/Views/Asset/index.js [hunk 1]
```diff
@@ -682,15 +682,12 @@ let cacheKey = null;
...
   let allTransactions = evmTransactions;
+
   ///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
-  if (
-    selectedInternalAccount &&
-    !isEvmAccountType(selectedInternalAccount.type) &&
-    route.params?.chainId &&
-    isNonEvmChainId(route.params.chainId)
-  ) {
+  if (asset?.chainId && isNonEvmChainId(asset.chainId)) {
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Asset/index.js:690]: Okay, so now we are not tracking the selectedInternalAccount?
I think this should be fine as a hotfix.

**Review by Prithpal-Sooriya — APPROVED** [review]

File: app/components/Views/Asset/index.js (hunk 1 above)
Comment (darioAnongba) [reply app/components/Views/Asset/index.js:690]: yes, we don't need to track because an account cannot have assets outside of its scopes.
