### PR TITLE
fix: fix sort feature

### LINKED ISSUE #13260: [Bug]:  [Bug]: Sort tokens by declining balance appears to be malfunctioning across both the "Popular Networks" and "Current Network" views.
### Describe the bug

The functionality to sort tokens by declining balance appears to be malfunctioning across both the "Popular Networks" and "Current Network" views. Tokens currently seem to be sorted in an order that may appear random to users.
(the issue is not present in 7.38.0)

### Expected behavior

When sort by declining balance is selected, tokens should be accurately sorted according to their balance in descending order 

### Screenshots/Recordings

https://github.com/user-attachments/assets/72cd76aa-6c9d-4cbc-8a28-af029bb62bc4

### Steps to reproduce

1. Sort tokens by declining balance

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.39.0(1539)

### Build type

None

### Device

iPhone 15, Samsung S24 Ultra

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**
Fix a regression on sort token feature

## **Related issues**

Fixes: #13260 

## **Manual testing steps**

1. Go to this page...
2.
3.

### **After**

https://github.com/user-attachments/assets/b9ccdfd4-6a9f-47b9-93f6-ec2687487158

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Tokens/index.tsx [hunk 1]
```diff
@@ -286,7 +264,13 @@ const Tokens: React.FC<TokensI> = memo(({ tokens }) => {
...
       const assets = categorizeTokens(filteredTokens);
 
-      const tokensWithBalances = calculateTokenFiatBalances(assets);
+      // Calculate fiat balances for tokens
+      const tokenFiatBalances = calculateFiatBalances(assets);
+
+      const tokensWithBalances = assets.map((token, i) => ({
+        ...token,
+        tokenFiatAmount: tokenFiatBalances[i],
+      }));
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Tokens/index.tsx:273]: Nice function!

Nit (not blocking) - if this function is not reused, could we reduce this to a single `.map` call?
```ts
const calculateFiatBalance = (asset) => // logic for a single asset

const tokensWithBalances = assets.map((token) => ({
  ...token,
  tokenFiatAmount: calculateFiatBalance(token)
})

```

Comment (Prithpal-Sooriya) [reply app/components/UI/Tokens/index.tsx:273]: TBH this i huge nit, so lets ignore.

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by sethkfman — APPROVED** [review]
LGTM
