### PR TITLE
fix: 24546 ledger unknown error eth not open

### LINKED ISSUE #24546: [Bug]: [Mobile] Unknown error is shown if the ETH app isn't running and the user tries to select Ledger accounts
**Describe the bug**

Unknown error is shown if the ETH app isn't running and the user tries to select Ledger accounts

**Expected result:**

In MM, the UI error should be informative: the ETH app isn't running.

**Actual result:**

Ledger unknown error is shown.

**Environment - iOS:**

Device: iPhone 12 ; iOS 26.1
MM iOS version: 7.61.0

**Environment - Android:**

Device: Samsung Galaxy S22 ; Android 16
MM PROD version: 7.60.4

**Environment - Ledger Nano X:**

ETH app version 1.20.0
Ledger OS:

- secure element 2.6.0
- microcontroller 2.39.0
- bootloader 1.25.0

Hardware version: ledger NanoX v2.0

**Screenshots/Recordings**

Image

**Steps to reproduce**

**Steps to reproduce:**

- Add hardware wallet
- Connect Ledger Nano X wallet
- In Ledger, quit the ETH app
- In MM, select the accounts and click Unlock
- View the unknown error

**Error messages or log output**

```shell

```

**Where was this bug found?**

Live version (from official store)

**Version**

7.60.4

**Build number**

7.60.4

**Build type**

None

**Device**

Ledger

**Operating system**

iOS, Android

**Severity**

sev3

### PR DESCRIPTION
**Pull request by dawnseeker8**
## **Description**
This PR will fix #24546 regarding unknown error display in ledger selection screen.
The root cause of this issue is due to mis match of error code returned from ledger sdk.  i have setup a constant array to cover all code regarding `Eth not open` and also mapping the error code with localisation string.

## **Changelog**

CHANGELOG entry: Fix #24546 with human readable message

## **Related issues**

Fixes: #24546 

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Touches hardware-wallet error classification and account unlock/pagination paths, so misclassification could change user flows or hide actionable errors; token-list CTA logic also changes gating behavior for Earn CTAs.
> 
> **Overview**
> Fixes Ledger UX by introducing a dedicated `EthAppNotOpen` error classification (status-code and message based) and mapping it to new localized strings, so users see a clear “open the Ethereum app” prompt instead of generic/unknown errors.
> 
> Plumbs this error through Ledger flows: `useLedgerBluetooth`, `Ledger` core (`getLedgerAccountsByOperation`, `unlockLedgerWalletAccount`), `LedgerConnect`, and the confirmation modal now render the new error state and tests cover the new mappings and helpers.
> 
> Cleans up token list rendering by removing the `shouldShowTokenListItemCta` prop from `TokenList`/`TokenListItem`/`TokenListItemV2` and having items call `useMusdCtaVisibility` internally; also loosens stablecoin lending CTA gating to rely on the returned `earnToken` rather than an extra BigNumber threshold check (and updates tests accordingly).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 372625a468d6e39362f6bea81d7a7ad0476312da. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by Akaryatrh — DISMISSED** [review]

File: app/components/UI/Tokens/TokenList/TokenListItem/TokenListItem.tsx [hunk 1]
```diff
@@ -59,8 +59,7 @@ import useEarnTokens from '../../../Earn/hooks/useEarnTokens';
 import { EARN_EXPERIENCES } from '../../../Earn/constants/experiences';
 import { EVENT_LOCATIONS as EARN_EVENT_LOCATIONS } from '../../../Earn/constants/events/earnEvents';
 import { useStablecoinLendingRedirect } from '../../../Earn/hooks/useStablecoinLendingRedirect';
-import BigNumber from 'bignumber.js';
-import { MINIMUM_BALANCE_FOR_EARN_CTA } from '../../../Earn/constants/token';
+import { useMusdCtaVisibility } from '../../../Earn/hooks/useMusdCtaVisibility';
```
Comment (dawnseeker8) [inline app/components/UI/Tokens/TokenList/TokenListItem/TokenListItem.tsx:66]: This file changed is not relative to this PR, however, it break the `yarn lint:tsc` pipeline pass for sometimes now, and prevent my PR getting green. so i need to fix it by myself.

**Review by mathieuartu — COMMENTED** [review]
Looks good on the accounts side, with a side note: we'll probably delete all this with the introduction of the hardware wallet overhaul (currently WIP here: https://github.com/MetaMask/metamask-mobile/pull/25519) as we are centralizing all HW related error management, and we handle the Eth app not being opened already.

**Review by mathieuartu — DISMISSED** [review]
LGTM as a temp solution until we deliver the unified HW provider in the coming weeks

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: app/components/UI/Tokens/TokenList/TokenListItem/TokenListItem.tsx [hunk 2]
```diff
@@ -63,8 +63,7 @@ import useEarnTokens from '../../../Earn/hooks/useEarnTokens';
 import { EARN_EXPERIENCES } from '../../../Earn/constants/experiences';
```
Comment (juanmigdr) [inline app/components/UI/Tokens/TokenList/TokenListItem/TokenListItem.tsx:63]: Now there is a TokenDetailsV1 and V2 (for AB testing, hopefully V1 will be removed soon). The same changes here should be applied to app/components/UI/Tokens/TokenList/TokenListItemV2/TokenListItemV2.tsx

**Review by juanmigdr — COMMENTED** [review]
V2 was merged in today, sorry for the late review

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by Akaryatrh — APPROVED** [review]
