### PR TITLE
fix: Fix/re order internal accounts

### LINKED ISSUE #9990: [Bug]: Accounts list sorting has unexpectedly changed, not consistent with previous releases
### Describe the bug

After upgrading to 7.24.1 account list sorting on the main wallet view is broken compared to previous releases.

### Expected behavior

Account names list sorting should persist after upgrade.
Based on previous releases, sorting should follow pattern from top-down wallet accounts, hw accounts, imported accounts.

### Screenshots/Recordings
7.21.0
image
7.24.1
image

Not able to reproduce when upgrading with only one type of HW account.
https://github.com/MetaMask/metamask-mobile/assets/6626407/ee50f075-83f5-46cd-a798-8f4f8ecf1081
### Steps to reproduce

GIVEN I am on v7.21.0 of mobile app
WHEN I upgrade mobile app
THEN account list sorting on main wallet view is the same as previous releases

### Error messages or log output

_No response_

### Version

7.24.1

### Build type

None

### Device

Any

### Operating system

iOS, Android

### Additional context

Discussion [here](https://consensys.slack.com/archives/C029JG63136/p1718305653605689?thread_ts=1718038234.258619&cid=C029JG63136).

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Cal-L**
## **Description**

This PR updates the `selectInternalAccounts` selector to return accounts sorted by the order of the accounts in the KeyringController. This update preserves the sorting behavior of accounts and matches behavior of versions prior to 7.24.0.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/9990

## **Manual testing steps**

To reproduce the issue

- Install 7.23.0
- Import accounts via SRP
- Create an account from the wallet
- Import an account via private key
- Create another account from the wallet
- Notice that the section of accounts on the account selector list is ordered by 1. SRP, 2.. Wallet, 3. Private key

- Download 7.24.0
- Open the account selector list and notice that accounts are now sorted by the order in which the accounts were created. Reference the steps above for the order.

To see the fix
- Install this branch
- Open the account selector list and notice that the accounts are ordered the same as it was on 7.23.0 - 1. SRP, 2.. Wallet, 3. Private key.

### **Before**

Creating accounts on 7.21.0, then upgrading to 7.24.0. The account name change is unrelated to this fix and will be addressed in a separate hotfox for 7.24.1.
https://github.com/MetaMask/metamask-mobile/assets/10508597/3c1a5587-1172-4db1-8bea-6d64239f7baf

### **After**

Continuing from the state above, upgrading to this branch fixes the ordering
https://github.com/MetaMask/metamask-mobile/assets/10508597/15277032-2adf-4370-bd3c-c92b3037c526

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/selectors/keyringController/index.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+const selectKeyringControllerState = (state: RootState) =>
+  state.engine.backgroundState.KeyringController;
+
+export const selectKeyrings = createDeepEqualSelector(
+  selectKeyringControllerState,
+  (keyringControllerState) => keyringControllerState.keyrings,
+);
+
+export const selectOrderedKeyringAccounts = createDeepEqualSelector(
```
Comment (Gudahtt) [inline app/selectors/keyringController/index.ts:12]: Nit: TSDoc comments here would be helpful

File: app/selectors/keyringController/utils.ts
Comment (Gudahtt) [inline app/selectors/keyringController/utils.ts:1]: It's a bit confusing to have test-only fixtures in a module called "utils", alongside our real code. Is there some way we can make it more obvious that this is meant for tests? Or we could move it directly into the test module.

File: app/selectors/accountsController.test.ts [hunk 2]
```diff
@@ -84,47 +91,58 @@ describe('Accounts Controller Selectors', () => {
...
-            'eth_signTypedData_v3',
-            'eth_signTypedData_v4',
-          ],
-          type: 'eip155:eoa',
+    it(`returns internal accounts of the accounts controller sorted by the keyring controller's accounts`, () => {
+      // Generate accounts for AccountsController in reverse order
+      const reversedKeyringAccounts = [...MOCK_KEYRINGS]
+        .reverse()
+        .flatMap((keyring) => [...keyring.accounts].reverse());
+      const accountsForInternalAccounts = reversedKeyringAccounts.reduce(
```
Comment (Gudahtt) [inline app/selectors/accountsController.test.ts:99]: Nit: It looks like much of this code is meant to create mock data for the test. Could we move this into a separate function, so that it's easier to tell what the test is doing?

File: app/selectors/keyringController/index.ts (hunk 1 above)
Comment (Cal-L) [reply app/selectors/keyringController/index.ts]: Added

File: app/selectors/keyringController/utils.ts
Comment (Cal-L) [reply app/selectors/keyringController/utils.ts:1]: I'm a bit weary of moving the code into the test itself since it's used in other selector tests as well. Didn't want to introduce potential circular dependencies in the future, so I kept it as a separate module. Just renamed the file to `testUtils` for now

File: app/selectors/accountsController.test.ts (hunk 2 above)
Comment (Cal-L) [reply app/selectors/accountsController.test.ts]: Abstracted into function and added JS docs

File: app/selectors/keyringController/index.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+  (keyringControllerState) => keyringControllerState.keyrings,
+);
+
+/**
+ * A memoized selector that returns the list of accounts from all keyrings in the form of a flattened array of strings.
+ */
+export const selectFlattenedKeyringAccounts = createDeepEqualSelector(
+  selectKeyrings,
+  (keyrings) => {
+    const flattenedKeyringAccounts = keyrings.flatMap(
```
[the remark this answers is not in the document]
Comment (Gudahtt) [reply app/selectors/keyringController/index.ts:26]: Perhaps we can use lodash here instead: https://lodash.com/docs/#flatMap

[the remark this answers is not in the document]
Comment (owencraston) [reply app/selectors/keyringController/index.ts:26]: full browser support was achieved in 2018 on iOS and android. It feels safe to use but since we already have lodash installed there is little drawback to using it.

Screenshot 2024-06-14 at 10 13 21 AM
Screenshot 2024-06-14 at 10 13 26 AM

[the remark this answers is not in the document]
Comment (Cal-L) [reply app/selectors/keyringController/index.ts:26]: flatMap is supported on iOS 12+, which is our min deployment version - https://retyui.github.io/react-native-compat-table/#:~:text=Array.prototype.flat,es2019

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by owencraston — APPROVED** [review]

**Comment by Cal-L** [comment]
Test passed on last functional change. Latest test failures most likely related to flakeyness
