### PR TITLE
fix: cp-7.55.0 sending ERC721 in new send implementation

### LINKED ISSUE #19479: [Bug]: App crashes with 'View: Root TypeError: undefined is not a function' when sending ERC 721
### Describe the bug

App crashes with `View: Root TypeError: undefined is not a function `when sending ERC 721.

### Expected behavior

ERC 721 can be successfully sent.

### Screenshots/Recordings

https://github.com/user-attachments/assets/9218ff07-eac6-421d-bb5e-743b7d280849

### Steps to reproduce

1. Send ERC 721

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.55.0 (2372)

### Build type

None

### Device

iPhone 15, Samsung S24 +

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

sending ERC721 in new send implementation

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/19479

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Screenshots/Recordings**
TODO

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/confirmations/hooks/send/useRouteParams.ts [hunk 1]
```diff
@@ -17,16 +19,21 @@ export const useRouteParams = () => {
 
   useEffect(() => {
     if (paramsAsset) {
+      const paramChainId =
+        isNonEvmAddress(paramsAsset.address) && paramsAsset?.chainId
+          ? toHex(paramsAsset?.chainId)
+          : paramsAsset?.chainId?.toString().toLowerCase();
```
Comment (jpuri) [inline app/components/Views/confirmations/hooks/send/useRouteParams.ts:25]: For NFT chainid was numeric which broke `paramsAsset.chainId?.toLowerCase()`

**Review by OGPoyraz — DISMISSED** [review]

**Review by cryptotavares — DISMISSED** [review]

**Review by OGPoyraz — APPROVED** [review]
