### PR TITLE
fix(12945): privacy mode and account selection bottom sheet

### LINKED ISSUE #12945: [Bug]: Account bottom sheet shows account balance even though balance was hidden
### Describe the bug

The title is pretty self-explanatory. If i were to hide my token balances on the wallet view then the balances should also be hidden on the account bottom sheet. 

### Expected behavior

Hiding wallet balances should hide account balances in all places and not limited to only the main wallet view.  

### Screenshots/Recordings

Image

### Steps to reproduce

Import a wallet with token balances
While on the wallet view, hide token balances
Notice your balance is hidden
Open the account bottom sheet, and notice the cumulative token balances appear

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.38.0 (1523)

### Build type

None

### Device

iPhone 16 Pro

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by vinnyhoward**
## **Description**

Issue: Privacy mode was not hiding account balances within the account selector bottom sheet at all

Solution: Have the account selector bottom sheet component subscribe to the `privacyMode` prop which hides the balance of all accounts, introduce the `disablePrivacyMode` route params so that the account selector bottom sheet can opt out of privacy mode completely for certain flows. Cases where this is needed is in the send flow and swap flow. We do not hide the balance when a user needs to switch between accounts when sending/swapping

## **Related issues**

Fixes: [#12945](https://github.com/MetaMask/metamask-mobile/issues/12945)

## **Manual testing steps**

1. Turn on privacy mode by clicking the eye icon within the portfolio balance at the top
2. Click on the account selector in the top to confirm balances for other accounts are hidden
3. Goto send and swap flow to confirm balances are NOT hidden even when privacy mode is ON

### Send Flow
| Before | After |
|:---:|:---:|
|before_swap_flow|after_swap_flow|

### Swap Flow
| Before | After |
|:---:|:---:|
|before_send_flow|after_send_flow|

### **Before**

NA

### **After**

NA

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/WalletAccount/WalletAccount.tsx [hunk 1]
```diff
@@ -88,11 +86,7 @@ const WalletAccount = ({ style }: WalletAccountProps, ref: React.Ref<any>) => {
             tags: getTraceTags(store.getState()),
             op: TraceOperation.AccountList,
           });
-          navigate(
```
Comment (vinnyhoward) [inline app/components/UI/WalletAccount/WalletAccount.tsx:91]: This component is no longer in use due to the header redesign, however I did have to make changes to this component in order for the linters to pass

File: app/components/UI/WalletAccount/WalletAccount.test.tsx [hunk 2]
```diff
@@ -9,7 +9,6 @@ import renderWithProvider, {
   DeepPartial,
 } from '../../../util/test/renderWithProvider';
 import ClipboardManager from '../../../core/ClipboardManager';
-import { createAccountSelectorNavDetails } from '../../../components/Views/AccountSelector';
```
Comment (vinnyhoward) [inline app/components/UI/WalletAccount/WalletAccount.test.tsx:12]: This test file/component  is no longer in use due to the header redesign, however I did have to make changes to this component in order for the linters and tests to pass

File: app/components/UI/WalletAccount/WalletAccount.test.tsx [hunk 3]
```diff
@@ -134,19 +133,6 @@ describe('WalletAccount', () => {
     fireEvent.press(getByTestId(WalletViewSelectorsIDs.ACCOUNT_COPY_BUTTON));
     expect(ClipboardManager.setString).toHaveBeenCalledTimes(1);
   });
-
-  it('should navigate to the account selector screen on account press', () => {
```
Comment (vinnyhoward) [inline app/components/UI/WalletAccount/WalletAccount.test.tsx:138]: This test file/component is no longer in use due to the header redesign, however I did have to make changes to this component in order for the linters and tests to pass

**Review by wachunei — APPROVED** [review]
Ramp changes LGTM

**Review by darkwing — APPROVED** [review]

File: app/components/Views/confirmations/SendFlow/AddressFrom/AddressFrom.tsx [hunk 4]
```diff
@@ -131,6 +131,7 @@ const SendFlowAddressFrom = ({
       params: {
         isSelectOnly: true,
         onSelectAccount,
+        disablePrivacyMode: true,
```
Comment (OGPoyraz) [inline app/components/Views/confirmations/SendFlow/AddressFrom/AddressFrom.tsx:134]: Not sure missing the obvious but if `disablePrivacyMode` set to `true` then it won't respect the `privacyMode` user selected is that right? Shouldn't this set to be `false` so that user preference will reflect in the `AccountSelector`?

Comment (vinnyhoward) [reply app/components/Views/confirmations/SendFlow/AddressFrom/AddressFrom.tsx:134]: The `AddressFrom` component is used during the send flow and we want to opt out of `privacyMode` in that flow. We should always show the balance regardless if you've toggled it on or not

Comment (OGPoyraz) [reply app/components/Views/confirmations/SendFlow/AddressFrom/AddressFrom.tsx:134]: I thought that we should respect the user preference after reading the PR description.

If that's the goal then it's all looking good, thanks for the explanation.

**Review by OGPoyraz — APPROVED** [review]
Confirmation changes LGTM

File: app/components/Views/confirmations/SendFlow/AddressFrom/AddressFrom.tsx (hunk 4 above)
Comment (vinnyhoward) [reply app/components/Views/confirmations/SendFlow/AddressFrom/AddressFrom.tsx:134]: Its a good question, product decided its best to show a balance during the swap/send flows so that they know which ones have a balance so they can switch

**Review by Cal-L — APPROVED** [review]
LGTM
