### PR TITLE
fix: Multichain balances

### LINKED ISSUE #3111: Add CronjobController on mobile
The CronjobController is not currently set up on mobile. It should be instantiated alongside the SnapController.

### PR DESCRIPTION
**Pull request by owencraston**
## **Description**

This PR fixes the broken balances for Solana on mobile. There were a series of updates that broke the balances. This PR addresses this issue with the following..

- updating the Solana snap to the latest.
- updating the assets controller (which contains all of the multichain controllers) to the latest which has no breaking changes but some bug fixes
- integrating the CronJobController which the snaps rely on to update the balances
- Integrating the MultichainAssetRatesController which the MultichainBalancesController/MultichainAssetsController now relies on

This PR also migrates all of the Multichain controllers to use the latest "init" pattern. These changes were modelled off of the accounts controller.

**NOTE**: Bitcoin Balances are still broken and likely requires a the snap to be updated. BTC is not a priority for now.

## **Related issues**

Fixes: https://github.com/MetaMask/accounts-planning/issues/859

Closes https://github.com/MetaMask/snaps/issues/3111

## **Manual testing steps**

1. Import a wallet that has funds with Solana (there are SRPs in 1Password that contain SOL)
2. click on the account list at the top of the wallet
3. click on add new account
4. click on Add Solana account
5. your account should be created and after a few seconds your wallet should be rendered in fiat.

### **Before**

https://github.com/user-attachments/assets/619c51b3-b416-4611-a586-96a1f457d322

### **After**

https://github.com/user-attachments/assets/6ef99752-7380-407d-9a66-b8047195cfb1

Confirmed that the currency rate conversion is still working as expected for both EVM and non EVM accounts.

https://github.com/user-attachments/assets/a7a3c4f3-7166-4f7a-a849-256959fa677e

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/Engine/Engine.ts [hunk 1]
```diff
@@ -454,6 +461,27 @@ export class Engine {
       multichainRatesControllerMessenger,
       multichainRatesController,
     );
+
+    const cronjobControllerMessenger = this.controllerMessenger.getRestricted({
```
Comment (tommasini) [inline app/core/Engine/Engine.ts:465]: Now we have a folders to have the messengers on, we can start to move this there, this is a new pattern introduced by this [PR](https://github.com/MetaMask/metamask-mobile/pull/13065)

File: app/selectors/multichain/multichain.ts [hunk 2]
```diff
@@ -20,24 +20,32 @@ import {
...
+  SOLANA_TESTNET = 'solana:4uhcVJyU9pJkvQyS88uRDiswHXSCkY3z',
+}
+
 export enum MultichainNativeAssets {
   Bitcoin = `${BtcScope.Mainnet}/slip44:0`,
   BitcoinTestnet = `${BtcScope.Testnet}/slip44:0`,
-  Solana = `${SolScope.Mainnet}/token:EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v`,
-  SolanaDevnet = `${SolScope.Devnet}/token:EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v`,
-  SolanaTestnet = `${SolScope.Testnet}/token:EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v`,
+  Solana = `${SolScope.Mainnet}/slip44:501`,
```
Comment (tommasini) [inline app/selectors/multichain/multichain.ts:35]: Nice catch!

**Comment by tommasini** [comment]
Where is this event "ExecutionService:unhandledError" coming from? Weird error!

File: app/core/Engine/Engine.ts (hunk 1 above)
Comment (owencraston) [reply app/core/Engine/Engine.ts]: done. I did this with a few of the other multichain controllers.

File: app/core/Engine/utils/test-utils.ts [hunk 3]
```diff
@@ -25,15 +22,25 @@ export function buildControllerInitRequestMock(
...
-> = (request) => {
-  const { getController } = request;
+/**
+ * Create a generic mock controller init function
+ *
+ * @template T - The controller type
+ * @template M - The messenger type
+ * @returns A mock controller init function
+ */
+export function createMockControllerInitFunction<
```
Comment (owencraston) [inline app/core/Engine/utils/test-utils.ts:32]: @Cal-L I made this more generic.

File: app/selectors/multichain/multichain.ts [hunk 4]
```diff
@@ -20,24 +20,32 @@ import {
   selectSelectedNonEvmNetworkSymbol,
 } from '../multichainNetworkController';
 
-/**
- * @deprecated TEMPORARY SOURCE OF TRUTH TBD
```
Comment (FrederikBolding) [inline app/selectors/multichain/multichain.ts:24]: Is this still not temporary?

File: app/core/Snaps/SnapsMethodMiddleware.ts [hunk 5]
```diff
@@ -129,6 +130,7 @@ const snapMethodMiddlewareBuilder = (
       engineContext.ApprovalController.addAndShowApprovalRequest.bind(
         engineContext.ApprovalController,
       ),
+    getIsLocked: () => AppState.currentState !== 'active',
```
Comment (FrederikBolding) [inline app/core/Snaps/SnapsMethodMiddleware.ts:133]: This should return whether the keyring controller is locked.

File: app/core/Engine/Engine.ts [hunk 6]
```diff
@@ -797,6 +740,7 @@ export class Engine {
           target,
         ),
       getClientCryptography: () => ({ pbkdf2Sha512: pbkdf2 }),
+      getIsLocked: () => AppState.currentState !== 'active',
```
Comment (FrederikBolding) [inline app/core/Engine/Engine.ts:743]: This should return whether the keyring controller is locked

File: app/core/Engine/Engine.ts [hunk 7]
```diff
@@ -355,21 +351,6 @@ export class Engine {
 
     networkController.initializeProvider();
 
-    const multichainNetworkControllerMessenger =
```
Comment (FrederikBolding) [inline app/core/Engine/Engine.ts:358]: In the future, I would recommend not combining large refactors like moving the messengers and instantiation around with also introducing new features like the cronjob controller. It makes reviewing the changes and reasoning about them harder than it needs to be

File: app/core/Engine/controllers/CronJobController/index.ts [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+ * @param request - The request object.
+ * @returns The CronjobController.
+ */
+export const cronjobControllerInit: ControllerInitFunction<
+  CronjobController,
+  CronjobControllerMessenger
+> = (request) => {
+  const { controllerMessenger, persistedState } = request;
+
+  const cronjobControllerState = (persistedState.CronjobController ??
```
Comment (FrederikBolding) [inline app/core/Engine/controllers/CronJobController/index.ts:23]: Wouldn't `persistedState.CronjobController` already be undefined if it hasn't been persisted before? Why do we need the `?? undefined` clause?

File: app/core/Engine/controllers/CronJobController/index.ts
Comment (FrederikBolding) [inline app/core/Engine/controllers/CronJobController/index.ts:1]: Not necessarily a question for this PR, but naming every controller init file `index` makes it a lot harder to find. Are we sure about the naming?

File: app/core/Engine/controllers/MultichainAssetsController/index.ts [hunk 9]
```diff
@@ -1,41 +1,34 @@
...
-  }
+export const multichainAssetsControllerInit: ControllerInitFunction<
+  MultichainAssetsController,
+  MultichainAssetsControllerMessenger
+> = (request) => {
+  const { controllerMessenger, persistedState } = request;
+
+  const multichainAssetsControllerState =
+    (persistedState.MultichainAssetsController ??
+      defaultMultichainAssetsControllerState) as MultichainAssetsControllerState;
```
Comment (FrederikBolding) [inline app/core/Engine/controllers/MultichainAssetsController/index.ts:26]: Shouldn't the controller already be managing its own default state?

File: app/core/Engine/types.ts [hunk 10]
```diff
@@ -246,13 +256,15 @@ type SnapsGlobalActions =
   | SnapsRegistryActions
   | SubjectMetadataControllerActions
   | PhishingControllerActions
-  | SnapsAllowedActions;
+  | SnapsAllowedActions
+  | ExecutionServiceActions;
 type SnapsGlobalEvents =
```
Comment (FrederikBolding) [inline app/core/Engine/types.ts:261]: I have never seen these types before, why aren't these part of `GlobalActions`?

File: app/core/Engine/messengers/cron-job-controller-messenger/index.ts [hunk 11]
```diff
@@ -0,0 +1,40 @@
...
+// Export the types
+export * from './types';
+
+/**
+ * Get the CronjobControllerMessenger for the CronjobController.
+ *
+ * @param baseControllerMessenger - The base controller messenger.
+ * @returns The CronjobControllerMessenger.
+ */
+export function getCronJobControllerMessenger(
```
Comment (FrederikBolding) [inline app/core/Engine/messengers/cron-job-controller-messenger/index.ts:22]:
```suggestion
export function getCronjobControllerMessenger(
```

File: app/core/Engine/controllers/CronJobController/index.ts
Comment (FrederikBolding) [inline app/core/Engine/controllers/CronJobController/index.ts:1]: Please rename the path to `../CronjobController/..`

File: app/core/Engine/Engine.ts (hunk 6 above)
Comment (FrederikBolding) [inline app/core/Engine/Engine.ts:743]: I don't think we need this here, we just need it defined for the Snaps method middleware
```suggestion
```

File: app/selectors/multichain/multichain.ts (hunk 4 above)
Comment (owencraston) [reply app/selectors/multichain/multichain.ts:24]: yes it is.

File: app/core/Snaps/SnapsMethodMiddleware.ts (hunk 5 above)
Comment (owencraston) [reply app/core/Snaps/SnapsMethodMiddleware.ts:133]: ah

File: app/core/Engine/controllers/CronJobController/index.ts
Comment (owencraston) [reply app/core/Engine/controllers/CronJobController/index.ts:1]: You raise a good point. This is definitely the pattern that was set out in the accounts-controller but I agree, we should probably name it something more verbose. 
Screenshot 2025-03-04 at 9 36 04 AM

File: app/core/Engine/controllers/CronJobController/index.ts (hunk 8 above)
Comment (owencraston) [reply app/core/Engine/controllers/CronJobController/index.ts:23]: good catch, I'll pass a more strongly typed default state.

File: app/core/Engine/controllers/MultichainAssetsController/index.ts (hunk 9 above)
Comment (owencraston) [reply app/core/Engine/controllers/MultichainAssetsController/index.ts:26]: what are you referring to? If you are referring to the default state pattern, I was following the pattern that @Cal-L set out. I am not certain its needed but there is something nice about having the default state be strongly typed.

File: app/core/Engine/types.ts (hunk 10 above)
Comment (owencraston) [reply app/core/Engine/types.ts:261]: Good point, I added them when I was trying to solve a bug related to the Execution service events but they ended up not being needed. I will remove them.

File: app/core/Engine/controllers/MultichainAssetsController/index.ts (hunk 9 above)
Comment (FrederikBolding) [reply app/core/Engine/controllers/MultichainAssetsController/index.ts:26]: IMO it's nicer for the default state to be defined at the controller level, which we are already doing. If we are introducing another level of default state we'll have to maintain and update both?

**Comment by owencraston** [comment]
CI is broken but all of the unit tests pass. Same with the lint and lint:tsc.

Screenshot 2025-03-04 at 10 53 50 AM

Screenshot 2025-03-04 at 10 55 44 AM

File: app/core/Engine/messengers/index.ts [hunk 12]
```diff
@@ -1,5 +1,15 @@
 import { getAccountsControllerMessenger } from './accounts-controller-messenger';
 import type { ControllerMessengerByControllerName } from '../types';
+import { getMultichainNetworkControllerMessenger } from './multichain-network-controller-messenger/multichain-network-controller-messenger';
+import { getCurrencyRateControllerMessenger } from './currency-rate-controller-messenger/currency-rate-controller-messenger';
+///: BEGIN:ONLY_INCLUDE_IF(preinstalled-snaps,external-snaps)
+import { getCronjobControllerMessenger } from './cronjob-controller-messenger/cronjob-controller-messenger';
```
Comment (tommasini) [inline app/core/Engine/messengers/index.ts:6]: cron job controller messenger will not be needed in the keyring-snaps code fence?

Comment (owencraston) [reply app/core/Engine/messengers/index.ts:6]: Since its more foundational to snaps, I figured I would include it in the preinstalled-snaps/external-snaps code fence instead.

**Review by tommasini — DISMISSED** [review]
LGTM! But let's recover the CI to get the unit test results!

**Review by gambinish — DISMISSED** [review]

File: app/core/Engine/controllers/CronJobController/index.ts
Comment (owencraston) [reply app/core/Engine/controllers/CronJobController/index.ts:1]: I ended up changing all the names to be more verbose because I agree, the index files are a pain in the ass.

File: app/core/Engine/controllers/MultichainAssetsController/index.ts (hunk 9 above)
Comment (owencraston) [reply app/core/Engine/controllers/MultichainAssetsController/index.ts]: fair point, I will keep it as is for now and we can change it later.

File: app/core/Engine/Engine.ts (hunk 7 above)
Comment (owencraston) [reply app/core/Engine/Engine.ts:358]: agreed. Sorry about that.

File: app/core/Engine/controllers/MultichainAssetsController/index.ts (hunk 9 above)
Comment (owencraston) [reply app/core/Engine/controllers/MultichainAssetsController/index.ts]: On second thought, I like your suggestion better. I will make these changes in the controllers that I added.

**Review by FrederikBolding — APPROVED** [review]
Snaps changes LGTM

**Review by gambinish — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
