### PR TITLE
Blockaid experimental settings should be visible on all networks

### LINKED ISSUE #8411: [Bug]: PPOM - Experimenal Settings for Blockaid disappear when a non-supported network is selected
### Describe the bug

**Problem:** whenever I select a network not supported by Blockaid, I see that the Blockaid section disappears from Experimental Settings

### Expected behavior

Even though Blockaid does not support all the networks, we should always see the option in the Settings

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/11f5cb33-f94a-405f-9e71-c7b294e98be0

### Steps to reproduce

1. Select a network not supported by Blockaid (i.e. Sepolia)
2. Go to Experimental Settings
3. See Blockaid section is not there

### Error messages or log output

_No response_

### Version

main (7.16 - not happening in 7.15)

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Blockaid experimental settings should be visible on all networks

## **Related issues**

Fixes: #8411

## **Manual testing steps**

1. Switch to Goreli network
2. Go to experimental settings
3. Option to enable blockaid should be visible

## **Screenshots/Recordings**

NA

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've clearly explained what problem this PR is solving and how it is solved.
- [X] I've linked related issues
- [X] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [X] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by blackdevelopa — APPROVED** [review]

File: app/core/RPCMethods/RPCMethodMiddleware.ts [hunk 1]
```diff
@@ -550,9 +549,7 @@ export const getRpcMethodMiddleware = ({
             address: req.params[0].from,
             checkSelectedAddress: isMMSDK || isWalletConnect,
           });
-          if (isBlockaidFeatureEnabled()) {
-            PPOMUtil.validateRequest(req);
-          }
+          PPOMUtil.validateRequest(req);
```
Comment (segun) [inline app/core/RPCMethods/RPCMethodMiddleware.ts:552]: Does this mean we want to call validate for all requests?

Comment (jpuri) [reply app/core/RPCMethods/RPCMethodMiddleware.ts:552]: Validate method works only if blockaid is enabled

Comment (blackdevelopa) [reply app/core/RPCMethods/RPCMethodMiddleware.ts:552]: I think that's the intention, yeah? @jpuri

**Review by segun — APPROVED** [review]
