### PR TITLE
fix: HWB197 (24544) fix ledger transaction speedup and cancel

### LINKED ISSUE #24544: [Bug]: [Mobile] Ledger - The user can't speed up or cancel a transaction
**Describe the bug**

**Expected result:**

The user should be able to cancel/speed up the transaction.

**Actual result:**

When the user tries to cancel/speed up the transaction, “transaction update failed” errors are presented.

**Environment - iOS:**

Device: iPhone 12 ; iOS 26.1
MM PROD version: 7.61.5

**Environment - Android:**

Device: Samsung Galaxy S22 ; Android 16
MM PROD version: 7.61.5

**Environment - Ledger Nano X:**

ETH app version 1.20.0
Ledger OS:

- secure element 2.6.0
- microcontroller 2.39.0
- bootloader 1.25.0

Hardware version: ledger NanoX v2.0

**Screenshots/Recordings**

Image

https://github.com/user-attachments/assets/0a15e072-342a-4b75-8cc3-b3f2a3d16676

https://github.com/user-attachments/assets/f82499ee-2b7f-4643-a608-bed7da45d078

**Steps to reproduce**

**Steps to reproduce:**

- Add hardware wallet
- Connect Ledger Nano X wallet
- Send sepoliaETH and set low network fee
- In Ledger, sign the transaction
- Try to speed up the transaction OR try to cancel the transaction

**Error messages or log output**

```shell

```

**Where was this bug found?**

Live version (from official store)

**Version**

7.61.5

**Build number**

3412

**Build type**

None

**Device**

Ledger

**Operating system**

iOS, Android

**Severity**

sev1

### PR DESCRIPTION
**Pull request by dawnseeker8**
## **Description**
This PR fix the ledger transaction speedup and cancel not able to run issue.
The root clause of this issue was caused by when we introduce the new unified transaction view and we forgot to check account is ledger devices or not, and didn't handle ledger differently because ledger require BLE approve to trigger the speed up and cancl transaction.

If you look at legacy behavior defined in `Transaction/index.js` file which has this code to handle ledger device check and then do speedup and cancel

```
const isLedgerAccount = isHardwareAccount(this.props.selectedAddress, [...]);
...
if (isLedgerAccount) {
  await this.signLedgerTransaction({...replacementParams...});
} else {
  await speedUpTransaction(...);
}
```

## **Changelog**

CHANGELOG entry: Modify `useUnifiedTxActions.ts` to specially handle ledger transaction speed up and cancel transaction.

## **Related issues**

Fixes: #24544 

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Changes transaction replacement execution paths and fee parameter wiring for Ledger accounts, which can affect speed up/cancel behavior; coverage is improved with new unit tests but the flow is user-funds-adjacent.
> 
> **Overview**
> Fixes unified transaction *speed up* and *cancel* for Ledger accounts by detecting Ledger keyring addresses and routing replacement transactions through `LedgerTransactionModal` (BLE confirmation) instead of calling `speedUpTransaction`/`TransactionController.stopTransaction` directly.
> 
> Extends Ledger replacement parameters to support *legacy* `gasPrice` as `legacyGasFee` (in addition to EIP-1559 fees), passes the appropriate fee shape through the modal, and ensures modal state is cleaned up even when the user rejects on the Ledger confirmation screen. Adds comprehensive unit tests covering Ledger vs non-Ledger paths and legacy vs EIP-1559 fee handling.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit fe1368224191761e72801cb33e86dff330e17187. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts [hunk 1]
```diff
@@ -265,6 +292,26 @@ export function useUnifiedTxActions() {
       if (!speedUpTxId) {
         throw new Error('Missing transaction id for speed up');
       }
+
+      const isLedgerAccount = isHardwareAccount(selectedAddress ?? '', [
```
Comment (Akaryatrh) [inline app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts]: Can be moved under line 70 (removing the need to duplicate it inside `cancelTransaction`)

**Review by Akaryatrh — DISMISSED** [review]

**Review by Akaryatrh — DISMISSED** [review]

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts (hunk 1 above)
Comment (dawnseeker8) [reply app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts]: done.

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts [hunk 2]
```diff
@@ -265,6 +292,26 @@ export function useUnifiedTxActions() {
...
+          replacementParams: {
+            type: LedgerReplacementTxTypes.SPEED_UP,
+            eip1559GasFee: {
+              maxFeePerGas: `0x${transactionObject?.suggestedMaxFeePerGasHex ?? ''}`,
+              maxPriorityFeePerGas: `0x${transactionObject?.suggestedMaxPriorityFeePerGasHex ?? ''}`,
+            },
+          },
+        });
+        return;
+      }
```
[the remark this answers is not in the document]
Comment (dawnseeker8) [reply app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts:322]: Fixed by cursor.

**Review by Akaryatrh — DISMISSED** [review]

File: app/components/UI/LedgerModals/LedgerTransactionModal.tsx [hunk 3]
```diff
@@ -28,6 +28,9 @@ export interface ReplacementTxParams {
     maxFeePerGas?: string;
     maxPriorityFeePerGas?: string;
   };
+  legacyGasFee?: {
+    gasPrice?: string;
```
Comment (dawnseeker8) [inline app/components/UI/LedgerModals/LedgerTransactionModal.tsx:32]: This part is to support the legacy gas transaction., which is commented by cursor recommandation.

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts [hunk 4]
```diff
@@ -239,22 +289,6 @@ export function useUnifiedTxActions() {
     }
   };
 
-  const onSpeedUpCompleted = () => {
-    setSpeedUp1559IsOpen(false);
```
Comment (dawnseeker8) [inline app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts:244]: Has been moved up due to lint complain this two method need to be difined before use it.

File: app/components/UI/LedgerModals/LedgerTransactionModal.tsx [hunk 5]
```diff
@@ -52,13 +55,14 @@ const LedgerTransactionModal = () => {
 
   const executeOnLedger = useCallback(async () => {
     if (replacementParams?.type === LedgerReplacementTxTypes.SPEED_UP) {
+      const gasFeeParams =
+        replacementParams.legacyGasFee ?? replacementParams.eip1559GasFee;
```
Comment (gantunesr) [inline app/components/UI/LedgerModals/LedgerTransactionModal.tsx]: I'm assuming that the logic here is that if `legacyGasFee` is defined then it should take priority over `eip1559GasFee` regardless of the value. It'd be good to have another way to identify legacy vs EIP1559 txs for the replacement params but this seems reasonable for the moment

File: app/components/UI/LedgerModals/LedgerTransactionModal.tsx [hunk 6]
```diff
@@ -52,13 +55,14 @@ const LedgerTransactionModal = () => {
...
       //@ts-expect-error Will defer this typescript issue to the hardware wallet team, confirmations or transactions team
-      await speedUpTransaction(transactionId, replacementParams.eip1559GasFee);
+      await speedUpTransaction(transactionId, gasFeeParams);
     } else if (replacementParams?.type === LedgerReplacementTxTypes.CANCEL) {
-      await TransactionController.stopTransaction(
-        transactionId,
-        replacementParams.eip1559GasFee,
-      );
+      const gasFeeParams =
+        replacementParams.legacyGasFee ?? replacementParams.eip1559GasFee;
```
Comment (gantunesr) [inline app/components/UI/LedgerModals/LedgerTransactionModal.tsx]: Do we need this to be duplicated?

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.test.ts [hunk 7]
```diff
@@ -522,5 +528,370 @@ describe('useUnifiedTxActions', () => {
...
+            await result.current.speedUpTransaction({});
+          });
+
+          expect(createLedgerTransactionModalNavDetails).toHaveBeenCalledWith({
+            transactionId: 'ledger-speedup-legacy',
+            deviceId: 'device-id',
+            onConfirmationComplete: expect.any(Function),
+            replacementParams: {
+              type: LedgerReplacementTxTypes.SPEED_UP,
+              legacyGasFee: undefined,
```
Comment (gantunesr) [inline app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.test.ts:637]: should this be defined for this test case?

File: app/components/UI/LedgerModals/LedgerTransactionModal.tsx (hunk 6 above)
Comment (dawnseeker8) [reply app/components/UI/LedgerModals/LedgerTransactionModal.tsx]: Extracted the duplicated gasFeeParams calculation out of both the SPEED_UP and CANCEL branches, computing it once before the if/else block

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.test.ts (hunk 7 above)
Comment (dawnseeker8) [reply app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.test.ts:637]: legacyGasFee is undefined because getCancelOrSpeedupValues returns undefined when existing gasPrice is non-zero

File: app/components/UI/LedgerModals/LedgerTransactionModal.tsx (hunk 5 above)
Comment (dawnseeker8) [reply app/components/UI/LedgerModals/LedgerTransactionModal.tsx]: yea, you are correct, currently this way is the simplest, however we can think about a robust way in the future which will may require changing more files.

**Review by Akaryatrh — DISMISSED** [review]

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts [hunk 8]
```diff
@@ -78,11 +85,54 @@ export function useUnifiedTxActions() {
...
+  const isLedgerAccount = isHardwareAccount(selectedAddress ?? '', [
+    ExtendedKeyringTypes.ledger,
+  ]);
+
   const toggleRetry = (msg?: string) => {
     setRetryIsOpen((prev) => !prev);
     setRetryErrorMsg(msg);
   };
 
+  const onSpeedUpCompleted = () => {
```
Comment (PatrykLucka) [inline app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts]: I think it's worth to wrap it with `useCallback` with empty deps

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts [hunk 9]
```diff
@@ -78,11 +85,54 @@ export function useUnifiedTxActions() {
...
+    setSpeedUp1559IsOpen(false);
+    setSpeedUpIsOpen(false);
+    setExistingGas(null);
+    setSpeedUpTxId(null);
+    setExistingTx(null);
+  };
+
+  const onCancelCompleted = () => {
```
Comment (PatrykLucka) [inline app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts]: same as above - it's worth to wrap it with `useCallback` with empty deps

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts [hunk 10]
```diff
@@ -78,11 +85,54 @@ export function useUnifiedTxActions() {
...
+    setCancel1559IsOpen(false);
+    setCancelIsOpen(false);
+    setExistingGas(null);
+    setCancelTxId(null);
+    setExistingTx(null);
+  };
+
+  const signLedgerTransaction = async (transaction: LedgerSignRequest) => {
```
Comment (PatrykLucka) [inline app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts]: With above changes, we could also wrap this function with `useCallback`. Having above functions as dependencies, this function will effectively change only when navigation changes

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts (hunk 8 above)
Comment (dawnseeker8) [reply app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts]: have warp with useCallback.

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts (hunk 10 above)
Comment (dawnseeker8) [reply app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts]: have warp with useCallback.

File: app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts (hunk 9 above)
Comment (dawnseeker8) [reply app/components/Views/UnifiedTransactionsView/useUnifiedTxActions.ts]: have warp with useCallback.

**Review by Akaryatrh — APPROVED** [review]

**Review by MarioAslau — APPROVED** [review]
LGTM

**Review by PatrykLucka — APPROVED** [review]
