### PR TITLE
fix: fix scroll custom import tokens

### LINKED ISSUE #15267: [Bug]: Inconsistent language across EVM to SOL
### Describe the bug

On ETH a brand new wallet with no transactions it says "Please Switch networks to see activity"

The copy should be consistent with Solana: “You have no transactions!”

### Expected behavior

_No response_

### Screenshots/Recordings

**EVM Scree**
Image

**SOL Screen**
Image

### Steps to reproduce

1. Create an account or use an account with no tx history
2. View the EVM screen and the SOL screens

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Device

iOS

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Related issues**

Fixes: #15267 

## **Manual testing steps**

1. Go to import token page
2. go to custom import
3. click on select network then try to scroll

### **After**

https://github.com/user-attachments/assets/441e7fd0-05eb-4f27-a3c3-6f7163f4cbd7

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/AddAsset/components/NetworkListBottomSheet.tsx [hunk 1]
```diff
@@ -42,14 +43,17 @@ export default function NetworkListBottomSheet({
     <BottomSheet
       shouldNavigateBack={false}
       ref={sheetRef}
+      isInteractable={false}
       onClose={() => setOpenNetworkSelector(false)}
-      isInteractable
```
Comment (salimtb) [inline app/components/Views/AddAsset/components/NetworkListBottomSheet.tsx:46]: The issue is with the BottomSheet component when it contains a scrollable element (like a ScrollView or FlatList). In this case, user interactions (such as scrolling) don't work properly inside the BottomSheet.

There are two possible solutions:
- Use the ReusableModal component instead – This doesn't have the same interactivity issues.
- Disable interactivity within the BottomSheet and add a close button – This lets users dismiss the modal manually.

In this PR, the second approach has been implemented as a temporary workaround while we wait for the Design System (DS) team to fix the issue.

**Review by Prithpal-Sooriya — APPROVED** [review]
