### PR TITLE
fix: (cp-7.47.0) allow formatting tokens to be done on either EVM or SOL chain

### LINKED ISSUE #15625: [Bug]: All other balances show $0 in acoount list when on Solana Network
### Describe the bug

If the Solana Network is selected, all the balances other than Solana show $0.00 balance

Image

### Expected behavior

All fiat balances should be displayed correctly

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Switch to Solana Network
2. Open Account List

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.47.0

### Build type

None

### Device

iPhone 14 , Pixel 8

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

iOS 18.1 
Android 15

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

Ensures we correctly get token formats for both evm and non-evm chains.

<details><summary>DevLog</summary>

https://www.loom.com/share/21c3e6a65b364b72b2dc641d47ec89a8?sid=c2049471-9315-4a01-814f-cba8cbb1edb4
</details> 

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15625 https://github.com/MetaMask/metamask-mobile/issues/15651

## **Manual testing steps**

See repro steps in issue

1. Select solana
2. check if EVM accounts still have fiat balances.

### **After**

https://www.loom.com/share/20d566382ce54c1b94c4d79f49dc6bbf?sid=6ba7838b-cc99-43bb-ab47-db3e103023eb

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/hooks/useGetFormattedTokensPerChain.tsx [hunk 1]
```diff
@@ -89,9 +90,9 @@ export const useGetFormattedTokensPerChain = (
 } => {
   const stableAccounts = useStableReference(accounts);
   const stableAllChainIDs = useStableReference(allChainIDs);
+  const currentEvmChainID = useSelector(selectEvmChainId);
+  const currentSolChainID = useSelector(selectSelectedNonEvmNetworkChainId);
 
-  // TODO: [SOLANA] Revisit this before shipping, `selectAllTokenBalances` selector needs to most likely be replaced by a non evm supported version
-  const currentChainId = useSelector(selectChainId);
```
Comment (Prithpal-Sooriya) [inline app/components/hooks/useGetFormattedTokensPerChain.tsx:94]: This was a lie LOL.
This selector gives you the currentChainId from either solana or EVM.

File: app/components/hooks/useGetFormattedTokensPerChain.tsx [hunk 2]
```diff
@@ -89,9 +90,9 @@ export const useGetFormattedTokensPerChain = (
 } => {
   const stableAccounts = useStableReference(accounts);
   const stableAllChainIDs = useStableReference(allChainIDs);
+  const currentEvmChainID = useSelector(selectEvmChainId);
+  const currentSolChainID = useSelector(selectSelectedNonEvmNetworkChainId);
```
Comment (Prithpal-Sooriya) [inline app/components/hooks/useGetFormattedTokensPerChain.tsx:94]: New logic:
Instead of trying to give you the token formatting for only 1 chain (e.g non-EVM if selected), we will try to give you the token formatting for 1 EVM chain, and 1 Non-EVM chain.

This way when you have solana selected, it will still try to use the selectedEVM chain to get balance for EVM accounts.

**Review by gambinish — APPROVED** [review]
