### PR TITLE
fix: animation added for loading state on SnapUILink button

### LINKED ISSUE #3179: Add animation for SnapUIButton on mobile

### PR DESCRIPTION
**Pull request by Daniel-Cross**
## **Description**

Added Lottie animation for `SnapUILink` button loading state as it's currently unhandled.

## **Related issues**

Fixes: https://github.com/MetaMask/snaps/issues/3179

Screenshot 2025-03-12 at 15 01 22

## **Manual testing steps**

1. Go to this page...
2.
3.

### **After**

https://github.com/user-attachments/assets/7270746f-cad3-444b-8377-3000c131d6fc

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Approvals/InstallSnapApproval/.InstallSnapApproval.tsx.swp
Comment (FrederikBolding) [inline app/components/Approvals/InstallSnapApproval/.InstallSnapApproval.tsx.swp:1]: This seems unintentional

File: app/components/Snaps/SnapUIButton/loading.json [hunk 1]
```diff
@@ -0,0 +1 @@
...":{"a":0,"k":100,"ix":11}},"ef":[],"shapes":[{"ty":"gr","bm":0,"hd":false,"mn":"ADBE Vector Group","nm":"Ellipse 1","ix":1,"cix":2,"np":3,"it":[{"ty":"el","bm":0,"hd":false,"mn":"ADBE Vector Shape - Ellipse","nm":"Ellipse Path 1","d":1,"p":{"a":0,"k":[0,0],"ix":3},"s":{"a":0,"k":[45.356,45.356],"ix":2}},{"ty":"st","bm":0,"hd":false,"mn":"ADBE Vector Graphic - Stroke","nm":"Stroke 1","lc":2,"lj":2,"ml":1,"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":7,"ix":5},"c":{"a":0,"k":[0.0118,0.4627,0.7882],"ix":3}},{"ty":"tr","a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"sk":{"a":0,"k":0,"ix":4},"p":{"a":0,"k":[3.178,3.178],"ix":2},"r":{"a":0,"k":0,"ix":6},"sa":{"a":0,"k":0,"ix":5},"o":{"a":0,"k":100,"ix":7}}]},{"ty":"tm","bm":0,"hd":false,"mn":"ADBE Vector Filter - Trim","nm":"Trim Paths 1","ix":2,"e":{"a":1,"k":[{"o":{"x":0.362,"y":0.158},"i":{"x":0.17,"y":1},"s":[0.1],"t":0},{"s":[100],"t":40}],"ix":2},"o":{"a":1,"k":[{"o":{"x":0.75,"y":0.35},"i":{"x":0.166,"y":0.61},"s":[0],"t":0},{"s":[360],"t":50}],"ix":3},"s":{"a":1,"k":[{"o":{"x":0.333,"y":0},"i":{"x":0.335,"y":1},"s":[0],"t":15},{"s":[100],"t":50}],"ix":1},"m":1}],"ind":1}],"v":"5.7.5","fr":30,"op":50,"ip":0,"assets":[]}
```
Comment (FrederikBolding) [inline app/components/Snaps/SnapUIButton/loading.json:1]: Curious, where do these assets come from?

File: app/components/Approvals/InstallSnapApproval/.InstallSnapApproval.tsx.swp
Comment (Daniel-Cross) [reply app/components/Approvals/InstallSnapApproval/.InstallSnapApproval.tsx.swp:1]: Certainly is! Don't know what happened here but I'll revert the name.

File: app/components/Snaps/SnapUIButton/loading.json (hunk 1 above)
Comment (Daniel-Cross) [reply app/components/Snaps/SnapUIButton/loading.json:1]: Comes from here: https://lottiefiles.com/free-animation/loading-spinner-zdAFWDw9ax

Comment (FrederikBolding) [reply app/components/Snaps/SnapUIButton/loading.json:1]: Do we not have a spinner like this used elsewhere in mobile?

Comment (FrederikBolding) [reply app/components/Snaps/SnapUIButton/loading.json:1]: Or a shared place for files used with Lottie?

Comment (Daniel-Cross) [reply app/components/Snaps/SnapUIButton/loading.json:1]: The current implementation on buttons on mobile is the `ActivitySpinner`

```
  const renderLoading = () => (
      <ActivityIndicator size="small" color={DEFAULT_BUTTONPRIMARY_LABEL_COLOR} />
    );
```
And the only other animations I could find for loading purposes looked similar to the `ActivityIndicator`, which is this: 
image

I would prefer to save the `loading.json` file in some asset folder instead of with the component. Do you have a suggestion for Snap assets like this? Should it be moved to a new asset folder?

Comment (Daniel-Cross) [reply app/components/Snaps/SnapUIButton/loading.json:1]: There is also no current loading implementation on `ButtonVariant.Link`, which is where this loader is being added.

Comment (Daniel-Cross) [reply app/components/Snaps/SnapUIButton/loading.json:1]: I can't seem to find any other Lottie files in the build when I search for `.json` files but they could have exported them as something else? Perhaps a Snaps assets file could be enough?

File: app/components/Snaps/SnapUIButton/SnapUIButton.tsx [hunk 2]
```diff
@@ -68,9 +66,15 @@ export const SnapUIButton: FunctionComponent<
       disabled={disabled}
       label={
         loading ? (
-          <Icon
-            // TODO: Animate this icon.
-            name={IconName.Loading}
+          <AnimatedLottieView
+            source={{ uri: './loading.json' }}
```
Comment (FrederikBolding) [inline app/components/Snaps/SnapUIButton/SnapUIButton.tsx:70]: The other instances of using Lottie seem to use `require` instead. I wonder if the URI only works in dev mode

Comment (Daniel-Cross) [reply app/components/Snaps/SnapUIButton/SnapUIButton.tsx:70]: I did that at first but the TypeScript linter hated `require` being used when not a top level import. From experience, `uri` usually works fine, but I can always add a TypeScript ignore line in and use `require` instead if we prefer that?

**Review by FrederikBolding — APPROVED** [review]
