### PR TITLE
fix: update treatment sticky buy/sell cp-7.69.0

### LINKED ISSUE #27326: [Bug]: Update sticky buy/sell labels
### Describe the bug

We ran an A/B test with the sticky Buy/Sell buttons on the token details page. The data showed total conversions weren't where we expected, so we've updated the sticky button labels to Swap/Buy instead. It's behind a feature flag -- we'll roll it out gradually and monitor the numbers.

Here's how the logic works (PR):
**Swap button:** Shown whenever the user has any token with a positive balance (across all chains). Per Andrew's guidance, even if the current token's chain isn't natively supported by Swaps, we still route the user into the Swap flow — it defaults to Ethereum pre-fills. So the Swap button is no longer gated on chain support.

**Buy button (on-ramp):** When the Swap button is present, we only show Buy if the token is actually supported by a third-party ramp provider. If no Swap button is shown (e.g. fresh wallet with no assets), we always fall back to showing Buy regardless — the ramp screen handles notifying the user if the token isn't supported.
This ensures there's always at least one CTA in the sticky footer

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

Prod now does not have the sticky buttons, but we will enable the FF in prod for 10% of users
after that users should see new swap/buy buttons

### Error messages or log output

```shell

```

### Where was this bug found?

Live version (from official store)

### Version

7.69.0

### Build number

N/A

### Build type

None

### Device

Iphone

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Replaces the sticky "Buy/Sell" footer buttons in the token details treatment variant with "Swap/Buy":
* **Swap** uses the existing swap navigation (goToSwaps() with no overrides — source = current token, dest = swap UI default)
* **Buy** redirects to on-ramp (fiat purchase), matching the existing Cash Buy behavior

Button visibility is conditional on two signals:
* **Swap** shown when user has eligible tokens to swap from (hasEligibleSwapTokens). Per Swaps lead guidance, the Swap button is no longer gated on chain support — even if the current token's chain isn't natively supported by Swaps, the user is routed into the Swap flow which defaults to Ethereum pre-fills.
* **Buy** shown when ramp supports the token (isBuyable), or as a fallback when user has no swap-eligible tokens — ensuring there is always at least one CTA in the sticky footer.
 
No changes to the control variant (legacy inline action buttons).

## **Changelog**

CHANGELOG entry: Updated token details sticky footer from Buy/Sell to Swap/Buy buttons

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/27326

## **Manual testing steps**

```gherkin
Feature: Token details sticky Swap/Buy footer

  Scenario: user sees both Swap and Buy
    Given user has ETH and USDC in wallet
    When user opens a ramp-supported token (e.g. LINK)
    Then sticky footer shows "Swap" and "Buy"
    And tapping Swap opens bridge UI with source = LINK
    And tapping Buy opens the on-ramp flow

  Scenario: user sees Swap only when ramp unsupported
    Given user has ETH and USDC in wallet
    When user opens a token not supported by ramp providers
    Then sticky footer shows only "Swap"

  Scenario: user sees Swap on unsupported chain
    Given user has ETH on Ethereum mainnet
    When user opens a native token on Fantom (unsupported by Swaps)
    Then sticky footer still shows "Swap"
    And tapping Swap routes to Swap flow with Ethereum pre-fills

  Scenario: user sees Buy only when no swap-eligible tokens
    Given user has an empty wallet or only holds the viewed token
    When user opens a ramp-supported token
    Then sticky footer shows only "Buy"

  Scenario: user sees Buy as fallback
    Given user has an empty wallet
    When user opens a token not supported by ramp providers
    Then sticky footer shows only "Buy"
    And the ramp screen handles notifying the user it is unsupported

  Scenario: trending token swap direction
    Given user has ETH and taps a token from trending feed
    When user taps Swap in the sticky footer
    Then bridge UI opens with source = ETH, dest = trending token
```

### **After**

Screenshot 2026-03-11 at 09 24 41

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I've included tests if applicable
- [ ] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Updates token details treatment CTA logic and navigation, which can affect conversion flows (swaps/on-ramp) and button visibility across tokens/chains. Risk is moderate due to UX/flow changes but limited to the A/B treatment and covered by updated unit tests.
> 
> **Overview**
> Updates the Token Details *treatment* sticky footer to show **`Swap`/`Buy`** CTAs instead of `Buy`/`Sell`. `Swap` now routes via `goToSwaps()` and is shown when `useTokenActions` reports `hasEligibleSwapTokens`; `Buy` routes to on-ramp via `onBuy` and is shown when the token is ramp-buyable (`useTokenBuyability`) or as a fallback when no swap-eligible tokens exist.
> 
> Extends `useTokenActions` to expose `hasEligibleSwapTokens` and updates `TokenDetails.test.tsx` to reflect the new button set and visibility matrix. Also adjusts the provider selection empty-state copy to use `fiat_on_ramp_aggregator.no_providers_available` when quotes are not shown.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 652129d2d9828b02630c3541fe4174ce25782eea. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/TokenDetails/Views/TokenDetails.tsx [hunk 1]
```diff
@@ -277,31 +275,29 @@ const TokenDetails: React.FC<{
...
+                      onPress: () => goToSwaps(),
                     },
                   ]
                 : []),
+              {
+                variant: ButtonVariants.Primary,
+                label: strings('asset_overview.buy_button'),
+                size: ButtonSize.Lg,
+                onPress: onBuy,
+              },
```
[the remark this answers is not in the document]
Comment (sahar-fehri) [reply app/components/UI/TokenDetails/Views/TokenDetails.tsx]: This is intentional to avoid having zero sticky buttons to render

File: app/components/UI/TokenDetails/Views/TokenDetails.tsx [hunk 2]
```diff
@@ -178,6 +180,9 @@ const TokenDetails: React.FC<{
   });
   const displaySwapsButton = isSwapsAssetAllowed && AppConstants.SWAPS.ACTIVE;
 
+  const showSwapButton = hasEligibleSwapTokens;
```
[the remark this answers is not in the document]
Comment (sahar-fehri) [reply app/components/UI/TokenDetails/Views/TokenDetails.tsx:183]: Updated description and it is intentional. If user enters the asset details page for a token on a network not supported by Swaps, we still want to route them into the Swap flow, and default to Ethereum when doing so.

File: app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx [hunk 3]
```diff
@@ -59,7 +60,7 @@ const ButtonBase = ({
         <Icon
           color={labelColor.toString()}
           name={startIconName}
-          size={DEFAULT_BUTTONBASE_ICON_SIZE}
+          size={startIconSize ?? DEFAULT_BUTTONBASE_ICON_SIZE}
```
Comment (sahar-fehri) [inline app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx]: The design system's `BottomSheetFooter` (@metamask/design-system-react-native) enforces variant per slot: primaryButtonProps always renders as Primary, secondaryButtonProps always renders as Secondary. It doesn't support two Primary buttons or an array-based API. We're keeping the deprecated component-library BottomSheetFooter here because its buttonPropsArray lets us set explicit variants per button, allowing both Swap and Buy to render as Primary.

Comment (georgewrmarshall) [reply app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx]: Hey @sahar-fehri, looks like this is missing it's prop object. Can you instead add a `startIconProps` that is typed Partial IconProps and spread here?

**Review by brianacnguyen — CHANGES_REQUESTED** [review]
Please remove icon size override. the icon size change should be done systematically

File: app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx (hunk 3 above)
Comment (sahar-fehri) [reply app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx]: we decided to revert eventually https://consensys.slack.com/archives/C0354T27M5M/p1773188661121699?thread_ts=1773184280.339299&cid=C0354T27M5M

**Review by brianacnguyen — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by amitabh94 — DISMISSED** [review]

File: android/app/build.gradle [hunk 4]
```diff
@@ -188,7 +188,7 @@ android {
         minSdkVersion rootProject.ext.minSdkVersion
         targetSdkVersion rootProject.ext.targetSdkVersion
         versionName "7.70.0"
-        versionCode 3607
```
Comment (tommasini) [inline android/app/build.gradle:191]: Can we revert the changes related to the build number?

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by amitabh94 — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
