### PR TITLE
fix: ledger ETH app errors

### LINKED ISSUE #24547: [Bug]: [Mobile] Ledger - The transaction isn't displayed on Ledger after getting the "please open the ETH app" notification from MM and opening the ETH app on Ledger
**Describe the bug**

The transaction isn't displayed on Ledger after getting the "please open the ETH app" notification from MM and opening the ETH app on Ledger

**Expected result:**

After opening the ETH app on Ledger, the transaction should be displayed for review.

**Actual result:**

On ledger the transaction isn't displayed for review.

**Environment - iOS:**

Device: iPhone 14 Pro Max ; iOS 18.6.2
MM version: 7.61.0 build 3264

**Environment - Android:**

Device: Samsung Galaxy A21s ; Android 12
MM PROD version: 7.60.4

**Environment - Ledger Nano X:**

ETH app version 1.20.0
Ledger OS:

- secure element 2.6.0
- microcontroller 2.39.0
- bootloader 1.25.0

Hardware version: ledger NanoX v2.0

**Screenshots/Recordings**

https://github.com/user-attachments/assets/c86dc368-9b02-4358-8045-a613040eda2c

https://github.com/user-attachments/assets/c7794d6a-91d1-4e3a-af9d-c6938f908376

**Steps to reproduce**

- Open MM mobile
- Add hardware wallet
- Connect Ledger Nano X wallet
- On Ledger, have the ETH app installed, but don't open it
- On MM, initiate Send/Swap transaction
- On MM, confirm the transaction
- On MM, view the "please open the ETH app" notification
- On Ledger, open the ETH app
- On MM, notice that the "confirm transaction on your ledger" info
- On ledger, nothing happens. The transaction isn't displayed for review

**Error messages or log output**

```shell

```

**Where was this bug found?**

Live version (from official store)

**Version**

7.61.0

**Build number**

3264

**Build type**

None

**Device**

Ledger

**Operating system**

Android, iOS

**Severity**

sev3

### LINKED ISSUE #25631: [Bug]: [Ledger] Select an account - Uninformative error is shown after trying to connect few ledger accounts or use pagination even though the ETH app is open
**Describe the bug**

**issue1**:  Error "disconnected device" message is shown after trying to connect few ledger accounts even though the ETH app is open

**issue2:**  "Unspecified error" message is shown after trying to use the pagination in the Select an Account screen even though the ETH app is open

**Expected result:**

In MM, the UI error should be informative OR the user should be able to proceed with connecting MM to Ledger since the ledger ETH app is open.

**Actual result:**

Uninformative error is shown and the user can't proceed with connecting MM with Ledger.

**Environment - iOS:**

Device: iPhone 12 ; iOS 26.1
MM iOS version: 7.65.0
branch: fix/24546-ledger-unknown-error-eth-not-open

**Environment - Android:**

Device: Samsung Galaxy S22 ; Android 16
MM iOS version: 7.65.0
branch: fix/24546-ledger-unknown-error-eth-not-open

**Environment - Ledger Nano X:**

ETH app version 1.20.0
**Ledger OS:**
secure element 2.6.0
microcontroller 2.39.0
bootloader 1.25.0
Hardware version: ledger NanoX v2.0

**Screenshots/Recordings**

https://github.com/user-attachments/assets/50cb5f50-5178-4bc6-98b4-7c919910aab2
https://github.com/user-attachments/assets/d0ed53e1-68ea-4e3f-b1ed-4caddc62a715

**Steps to reproduce**

**issue1:**  Error "disconnected device" message is shown after trying to connect few ledger accounts even though the ETH app is open

**Steps to reproduce:**

- on Ledger, open the ETH app
- start with connecting MM to Ledger and get to the Select an Account screen
- on Ledger, quit the ETH app
- in MM, select an account and click “Unlock”
- Notice the error message: Please open the ETH app on your Ledger device - the fix works as expected
- in Ledger, open the ETH app
- in MM, select few more Ledger accounts tap Unlock
- Notice the error message: Disconnected device

**issue2:**  "Unspecified error" message is shown after trying to use the pagination in the Select an Account screen even though the ETH app is open

- on Ledger, open the ETH app
- start with connecting MM to Ledger and get to the Select an Account screen
- on Ledger, quit the ETH app
- in MM, select an account and click “Next” in the pagination
- Notice the error message: Please open the ETH app on your Ledger device - the fix works as expected
- in Ledger, open the ETH app
- in MM, tap “Next” in the pagination
- Notice the error message: Unspecified error when connect Ledger Hardware

**Error messages or log output**

```shell

```

**Where was this bug found?**

Internal release testing

**Version**

7.65.0

**Build number**

3418 branch: fix/24546-ledger-unknown-error-eth-not-open

**Build type**

None

**Device**

Ledger

**Operating system**

Android, iOS

**Severity**

sev3

### LINKED ISSUE #25947: [Bug]: Infinite loader is presented on Connect Ledger screen even though the Ledger ETH app is open - edge case
### Describe the bug

**Expected result:**

After opening the ledger ETH app, in MM the user should be taken to the next screen - Select an account.

**Actual result:**

After opening the ledger ETH app, in MM there is infinite loader on the Connect Ledger screen.

**Environment - iOS:**

Device: iPhone 12 ; iOS 26.2.1
MM iOS version: 7.63.1 build 3625

**Environment - Android:**

Device: Samsung Galaxy S22 ; Android 16
MM iOS version: 7.63.1 build 3625

**Environment - Ledger Nano X:**

ETH app version 1.20.0
Ledger OS:
secure element 2.6.0
microcontroller 2.39.0
bootloader 1.25.0
Hardware version: ledger NanoX v2.0

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/c1de25d6-e585-43ea-acbf-4f45e202730d

### Steps to reproduce

- on Ledger, open the BTC app
- start with connecting MM to Ledger and get to the Connect Ledger screen
- tap Continue and notice the loader
- on the Ledger device, notice that the BTC app is closed automatically
- on Ledger, open the ETH app
- in MM, notice that the user is stuck in the Connect Ledger screen with infinite loader

### Error messages or log output

```shell

```

### Where was this bug found?

Live version (from official store)

### Version

7.63.1

### Build number

3625

### Build type

None

### Device

Ledger

### Operating system

Android, iOS

### Additional context

_No response_

### Severity

sev3

### PR DESCRIPTION
**Pull request by dawnseeker8**
## **Description**

This PR solve multiple issues related to the ledger ETH app. These are issue #24547, #25631, and #25947 

## **Changelog**

CHANGELOG entry: fix Ledger transaction not displayed after opening ETH app.
CHANGELOG entry: fix pagination and unlock accounts uninformative error after opening ETH app

## **Related issues**

Fixes: #24547
Fixes: #25631 
Fixes: #25947

## **Manual testing steps**

Steps to reproduce

#24547
Open MM mobile
1. Add hardware wallet
2. Connect Ledger Nano X wallet
3. On Ledger, have the ETH app installed, but don't open it
4. On MM, initiate Send/Swap transaction
5. On MM, confirm the transaction
6. On MM, view the "please open the ETH app" notification
7. On Ledger, open the ETH app
8. On MM, notice that the "confirm transaction on your ledger" info
9. On ledger,  The transaction is displayed for review

#25631 
- on Ledger, open the ETH app
- start with connecting MM to Ledger and get to the Select an Account screen
- on Ledger, quit the ETH app
- in MM, select an account and click “Unlock”
- Notice the error message: Please open the ETH app on your Ledger device - the fix works as expected
- in Ledger, open the ETH app
- in MM, select few more Ledger accounts tap Unlock
- Flow should continue, and everything should work without errors.

#25947
- on Ledger, open the BTC app
- start with connecting MM to Ledger and get to the Connect Ledger screen
- tap Continue and notice the loader
- on the Ledger device, notice that the BTC app is closed automatically
- on Ledger, open the ETH app
- Ledger should open ETH app and continue.

### **Before**

Check issues: #24547 #25631 #25947

### **After**

TBC...

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Refactors Ledger BLE workflow/retry and disconnect handling, which can affect hardware-wallet connection stability and signing flows. Risk is mitigated by substantial new unit coverage across app-switch, error-classification, and retry scenarios.
> 
> **Overview**
> Fixes Ledger ETH-app recovery issues by routing account pagination/unlock flows through `useLedgerBluetooth.ledgerLogicToRun`, ensuring operations resume cleanly after prompting users to open/close the Ethereum app and avoiding stuck loading or misleading disconnect errors.
> 
> Refactors `useLedgerBluetooth` to use a mockable `loadBleTransport` wrapper (instead of native dynamic import), adds explicit disconnect classification via new `ledgerErrors` helpers (`DISCONNECT_ERROR_NAMES`, `isDisconnectError`), and hardens reconnect/disconnect state handling (including app-switch recursion + restart limits). Tests are significantly expanded for the hook and updated for `LedgerBluetoothAdapter` transient BLE retry behavior.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit f4f232f743de0e1a76736dfc4054395ac7164bb0. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/LedgerSelectAccount/index.tsx
Comment (NicolasMassart) [inline app/components/Views/LedgerSelectAccount/index.tsx]: Question: is this `style-` a typo?

**Review by NicolasMassart — COMMENTED** [review]
Complete “Manual testing steps” and “After” screenshots (replace “TBC…”).

After the possible typo fix and addressing the Cursor bot items (and template), this will look good to me.

File: app/components/Views/LedgerSelectAccount/index.tsx
Comment (dawnseeker8) [reply app/components/Views/LedgerSelectAccount/index.tsx]: I didn't implement this, i discover that this `style-` also appear in `main` branch.

Comment (dawnseeker8) [reply app/components/Views/LedgerSelectAccount/index.tsx]: anyway, i have removed `-` in ths style to make the syntax correct.

Comment (NicolasMassart) [reply app/components/Views/LedgerSelectAccount/index.tsx]: I know, it's not you, but as I found it, I wanted to ask. Thanks for the fix.

File: app/components/hooks/Ledger/loadBleTransport.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+/**
+ * Wrapper around the dynamic BLE transport import.
+ *
+ * Extracted to a static-import module so tests can mock it with jest.mock(),
+ * which does not intercept native dynamic import() in the Node 22 test env.
+ */
+const loadBleTransport = async (deviceId: string) => {
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  const BluetoothTransport: any = await import(
```
Comment (NicolasMassart) [inline app/components/hooks/Ledger/loadBleTransport.ts]: Suggestion: get rid of the `any` type (and eslint disable) as [the package is providing type](https://github.com/LedgerHQ/ledger-live/blob/4aa070481061e05272cb588d726cc7f363ff25c3/libs/ledgerjs/packages/react-native-hw-transport-ble/package.json#L25C3-L25C36) for [the BleTransport class](https://github.com/LedgerHQ/ledger-live/blob/4aa070481061e05272cb588d726cc7f363ff25c3/libs/ledgerjs/packages/react-native-hw-transport-ble/src/BleTransport.ts#L434C22-L434C34)

Comment (dawnseeker8) [reply app/components/hooks/Ledger/loadBleTransport.ts]: After few attends of getting rid of the `any` without succeed, and also use the help with AI with opus 4.6 model, and still Cursor AI will use any here due to Ai also unable to detect the type from BleTransport class.

File: app/components/Views/LedgerSelectAccount/index.test.tsx [hunk 2]
```diff
@@ -213,14 +216,13 @@ describe('LedgerSelectAccount', () => {
     mockUnlockLedgerWalletAccount.mockResolvedValue(undefined);
     mockForgetLedger.mockResolvedValue(undefined);
 
-    (
-      useLedgerBluetooth as unknown as jest.MockedFunction<
-        typeof useLedgerBluetooth
-      >
-    ).mockImplementation(() => ({
+    (useLedgerBluetooth as jest.Mock).mockImplementation(() => ({
```
Comment (NicolasMassart) [inline app/components/Views/LedgerSelectAccount/index.test.tsx]: suggestion (non-blocking): Prefer jest.mocked() over as jest.Mock for hook mock

```ts
    jest.mocked(useLedgerBluetooth).mockImplementation(() => ({
      isSendingLedgerCommands: false,
      isAppLaunchConfirmationNeeded: false,
      ledgerLogicToRun: jest.fn(
        async (fn: (transport: unknown) => Promise<void>) =>
          fn(undefined as unknown),
      ),
      error: undefined,
      cleanupBluetoothConnection: jest.fn(),
    }));
```

File: app/components/hooks/Ledger/loadBleTransport.ts [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+
+const loadBleTransport = async (
+  deviceId: string,
+): Promise<BluetoothInterface> => {
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  const BluetoothTransport: any = await import(
+    '@ledgerhq/react-native-hw-transport-ble'
+  );
+  return BluetoothTransport.default.open(deviceId);
+};
```
Comment (NicolasMassart) [inline app/components/hooks/Ledger/loadBleTransport.ts:19]: suggestion (non-blocking): Add your own type to avoid any and eslint-disable


```suggestion
type BleTransportModule = {
  default: { open: (deviceId: string) => Promise<BluetoothInterface> };
};
const loadBleTransport = async (
  deviceId: string,
): Promise<BluetoothInterface> => {
  const BluetoothTransport = (await import(
    '@ledgerhq/react-native-hw-transport-ble'
  )) as BleTransportModule;
  return BluetoothTransport.default.open(deviceId);
};
```

File: app/components/hooks/Ledger/useLedgerBluetooth.ts [hunk 4]
```diff
@@ -32,8 +34,63 @@ interface UseLedgerBluetoothHook {
...
+    return e.code;
+  }
+  if (e.name === 'TransportStatusError') {
+    return classifyTransportStatusError(e.statusCode);
+  }
+  if (e.name === 'TransportRaceCondition') {
+    return LedgerCommunicationErrors.LedgerHasPendingConfirmation;
+  }
+  return classifyErrorByMessage(e.message);
+}
```
Comment (NicolasMassart) [inline app/components/hooks/Ledger/useLedgerBluetooth.ts]: suggestion (non-blocking): Replace any with unknown

```suggestion
function classifyLedgerError(e: unknown): LedgerCommunicationErrors {
  if (e instanceof LedgerError) {
    return e.code;
  }
  const err = e as { name?: string; statusCode?: number; message?: string };
  if (err?.name === 'TransportStatusError' && typeof err.statusCode === 'number') {
    return classifyTransportStatusError(err.statusCode);
  }
  if (err?.name === 'TransportRaceCondition') {
    return LedgerCommunicationErrors.LedgerHasPendingConfirmation;
  }
  return classifyErrorByMessage(typeof err?.message === 'string' ? err.message : '');
}
```

Apply the same idea to handleOpenEthAppError(e: unknown) and the catch (e: unknown) in processLedgerWorkflow, and remove the corresponding eslint-disable comments once types are correct.

File: app/core/HardwareWallet/adapters/LedgerBluetoothAdapter.test.ts
Comment (NicolasMassart) [inline app/core/HardwareWallet/adapters/LedgerBluetoothAdapter.test.ts:1]: suggestion (non-blocking): Use jest.mocked(connectLedgerHardware)

For consistency with the project Jest mocking guideline, use jest.mocked(connectLedgerHardware) instead of (connectLedgerHardware as jest.Mock) when configuring the mock.

**Review by NicolasMassart — COMMENTED** [review]
BLE and app-switch changes look good.

Before merge: finish “Manual testing steps” and “After” screenshots (replace “TBC…” by real content or just mark N/A if it's not manually testable) and address any open Cursor bot comments. 
Ideally if you could also make suggested changes, that would be cleaner (we really want to avoid eslint exclusions)

File: app/components/Views/LedgerSelectAccount/index.test.tsx (hunk 2 above)
Comment (dawnseeker8) [reply app/components/Views/LedgerSelectAccount/index.test.tsx]: fixed with refinement to fix the lint issue.

File: app/core/HardwareWallet/adapters/LedgerBluetoothAdapter.test.ts
Comment (dawnseeker8) [reply app/core/HardwareWallet/adapters/LedgerBluetoothAdapter.test.ts:1]: fixed .

**Comment by dawnseeker8** [comment]
@metamaskbot update-mobile-fixture

File: app/components/hooks/Ledger/useLedgerBluetooth.test.ts [hunk 5]
```diff
@@ -63,14 +72,45 @@ jest.mock('../../../../locales/i18n', () => ({
...
 }));
 
-// Import hook after all mocks
-import useLedgerBluetooth from './useLedgerBluetooth';
+// Import hook and helpers after all mocks
+import useLedgerBluetooth, { isDisconnectError } from './useLedgerBluetooth';
+
+// ---------------------------------------------------------------------------
+// Helpers
+// ---------------------------------------------------------------------------
```
Comment (NicolasMassart) [inline app/components/hooks/Ledger/useLedgerBluetooth.test.ts:80]: Suggestion (non-blocking): do not use excessive comment formatting, it must look good on small screens

**Review by NicolasMassart — DISMISSED** [review]
despite my multiple requests, I eventually filled the PR Manual testing steps myself, so we can have future easy understanding of the fixed issues and testing without having to dig in the related issue.
Sometimes there's discrepency between issue and PR for many reasons, so PR should be the final source of truth and include all the required data to approve.
Note that when this will land in a release, it will be required to test again and you will have long forgotten the context. Having clear tests steps for you to follow will be crucial.
Thank you for taking this into account for next time.

**Review by NicolasMassart — APPROVED** [review]
