### PR TITLE
fix: fix swap flow

### LINKED ISSUE #12757: [Bug]:  Swap button hidden for non current network
### Describe the bug

The "Swap" button does not appear for tokens that are not on the currently selected network, even when swaps are supported for that token on the network it belongs to. This creates confusion for users expecting the swap functionality to be available for any supported token.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/822407e7-191d-47e0-b5f1-f96c31a84c74

### Steps to reproduce

1. do a fresh install app
2. select popular network
3. go to any token and try to swap from token detail page

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.38.0

### Build type

None

### Device

Pixel 7, iphone 14

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Related issues**

Fixes: #12757 

## **Manual testing steps**

1. Go to this page...
2.
3.

### **After**

https://github.com/user-attachments/assets/480510e9-b2fe-4e92-9bd0-3a30d0d2ae07

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/Asset/index.js [hunk 1]
```diff
@@ -240,8 +247,27 @@ class Asset extends PureComponent {
...
+      Logger.error(error, 'Swaps: error while fetching swaps liveness');
+      this.props.setLiveness(chainId, null);
+    }
+  };
+
   componentDidMount() {
     this.updateNavBar();
+
+    const tokenChainId = this.props.route?.params?.chainId;
+    if (tokenChainId) {
```
Comment (sahar-fehri) [inline app/components/Views/Asset/index.js:267]: Good to make this conditional because tokenChainId would be undefined if we are not in portfolioView feature

**Review by sahar-fehri — DISMISSED** [review]

**Review by sahar-fehri — APPROVED** [review]
