### PR TITLE
fix: align connection logic with extension cp-7.57.0

### LINKED ISSUE #20808: [Bug]: Revert Account Cell styles for DaPP Connection flows and Account List on bot clients
### Describe the bug

We need to revert to the old cell styles on DaPP connection and the Account List. Relevant [Slack thread](https://consensys.slack.com/archives/C06FXU326RL/p1758305842324109). The Figma link is located [HERE](https://www.figma.com/design/tIC9CbWA9QS7tju1VjIkov/BIP-44-Mobile?node-id=3977-62017&t=myJVQqnxuzcQiQeF-4)

### Expected behavior

- We have updated DaPP connection/edit/permission flows for the new cell styling
- We have updated the Account List with the new styling 
- We have implemented these changes across both clients

### Screenshots/Recordings

None

### Steps to reproduce

None

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.57.0

### Build type

None

### Device

iPhone

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This PR aligns the connection logic with the extension client. 

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: [20808](https://github.com/MetaMask/metamask-mobile/issues/20808)

## **Manual testing steps**

```gherkin
Feature: Dapp connection

  Scenario: user connects to matcha.xyz
    Given already connected with an evm account

    When user connects a nonevm account
    Then the connection is successful

  Scenario: user connects to matcha.xyz
    Given already connected with an nonevm account

    When user connects an evm account
    Then the connection is successful
```

### **After**

https://github.com/user-attachments/assets/630ddf34-20b7-4022-a298-f9c741ba02e5

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Aligns multichain connection logic with the extension by refining default network/account selection (EIP-1193, namespaces, testnets), updating selectors/utils, and adjusting tests.
> 
> - **Connection & Network Selection**:
>   - Compute default selected `CaipChainId`s using requested/connected chains, requested namespaces (excluding `wallet`), current selected network, and testnet awareness; special handling for EIP-1193 requests.
>   - Split network configurations into non-test and test via `TESTNET_CAIP_IDS`; add `getSelectedMultichainNetwork` selector.
> - **Account Groups & Permissions**:
>   - Refactor `useAccountGroupsForPermissions` to filter/prioritize groups (connected, supports chain/namespace, fulfills requested accounts), include connected-or-requested groups, and apply fallback only when no priority groups exist.
>   - Rename/replace util to `getCaip25AccountIdsFromAccountGroupAndScope`; return field renamed to `caipAccountIdsOfConnectedAndRequestedAccountGroups`.
> - **Components & Tests**:
>   - Update `MultichainAccountConnect` and `MultichainAccountPermissions` to use new selection logic, selector, and util; initialize state with refined defaults.
>   - Adjust tests to new API/behavior and remove an obsolete network selection assertion.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit e879522f7ccb2ba15df8383eb1a8b789aabf42dd. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by owencraston — DISMISSED** [review]
tested and the functionality seems to match what I see on extension. DId not look too much at the code since I have very little context.

File: app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx [hunk 1]
```diff
@@ -156,17 +167,53 @@ const MultichainAccountConnect = (props: AccountConnectProps) => {
...
+    () =>
+      Object.entries(networkConfigurations).reduce(
+        ([nonTestNetworksList, testNetworksList], [chainId, network]) => {
+          const caipChainId = chainId as CaipChainId;
+          const testnetCaipIds = TEST_NETWORK_IDS.map((id) =>
+            toCaipChainId(
+              KnownCaipNamespace.Eip155,
+              parseInt(id, 16).toString(),
+            ),
+          );
```
Comment (jiexi) [inline app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx]: might be good to calculate this once outside of the loop. Thoughts on if it should live in this component or in the same file as the TEST_NETWORK_IDS constant?

File: app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx [hunk 2]
```diff
@@ -156,17 +167,53 @@ const MultichainAccountConnect = (props: AccountConnectProps) => {
...
+        },
+        [
+          [] as EvmAndMultichainNetworkConfigurationsWithCaipChainId[],
+          [] as EvmAndMultichainNetworkConfigurationsWithCaipChainId[],
+        ],
+      ),
     [networkConfigurations],
   );
 
+  const alreadyConnectedCaipChainIds = useMemo(
```
Comment (jiexi) [inline app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx:209]: i feel like the `already` part is implied, or I guess i don't see much more clarity with it added

File: app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx [hunk 3]
```diff
@@ -179,26 +226,100 @@ const MultichainAccountConnect = (props: AccountConnectProps) => {
...
+    const allNetworksList = [
+      ...nonTestNetworkConfigurations,
+      ...testNetworkConfigurations,
+    ].map(({ caipChainId }) => caipChainId);
+
+    const walletRequest =
+      requestedCaipChainIds.filter(
+        (caipChainId) =>
+          parseCaipChainId(caipChainId).namespace === KnownCaipNamespace.Wallet,
+      ).length > 0;
```
Comment (jiexi) [inline app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx]: Are you seeing a case where `isEip1193Request` is true but there is no `wallet:eip155` scope included in the request? I think we should rely only on `isEip1193Request` here

File: app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx [hunk 4]
```diff
@@ -179,26 +226,100 @@ const MultichainAccountConnect = (props: AccountConnectProps) => {
...
+    const selectedNetworkIsTestNetwork = testNetworkConfigurations.find(
+      (network: { caipChainId: CaipChainId }) =>
+        network.caipChainId === currentlySelectedNetworkChainId,
+    );
+
+    const defaultSelectedNetworkList = selectedNetworkIsTestNetwork
+      ? [...nonTestNetworkConfigurations, selectedNetworkIsTestNetwork].map(
+          ({ caipChainId }) => caipChainId,
+        )
+      : nonTestNetworkConfigurations.map(({ caipChainId }) => caipChainId);
```
Comment (jiexi) [inline app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx]: worth adding an extra variable to avoid having to repeat the caipChainId map logic?

File: app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx (hunk 2 above)
Comment (montelaidev) [reply app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx:209]: Its the same name on extension. I would prefer to keep the difference between the clients to a minimum.

File: app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx (hunk 3 above)
Comment (montelaidev) [reply app/components/Views/MultichainAccounts/MultichainAccountConnect/MultichainAccountConnect.tsx]: Youre right, we can just use `isEip1193Request` here

**Review by jiexi — APPROVED** [review]
