### PR TITLE
fix: add tokenList iconUrl to `IdentIcon` component

### LINKED ISSUE #10216: [Bug]: Identicons displayed instead of token icons
### Describe the bug

Within simulations UI, we're displaying identicons for known tokens instead of their icons. We should display tokens icons for consistency and so it's easier for users to recognize their tokens and understand the outcome of the proposed transaction.

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

Go to a dapp and do a swap
Notice how tokens will be displayed in simulations with identicons

### Error messages or log output

_No response_

### Version

7.26

### Build type

None

### Device

iphone 11

### Operating system

iOS

### Additional context

image

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to add support for `IdentIcon` component to use iconUrl for token entity from `tokenList` 

## **Related issues**

Fixes:

### **Before**

Screenshot 2024-06-28 at 11 56 58

### **After**

Screenshot 2024-06-28 at 11 41 13

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by vinistevam — DISMISSED** [review]

File: app/components/UI/Identicon/index.tsx [hunk 1]
```diff
@@ -43,23 +44,33 @@ const Identicon: React.FC<IdenticonProps> = ({
...
+  const tokenListIconUrl = tokenList[address.toLowerCase()]?.iconUrl;
+
+  const styleForBlockieAndTokenIcon = [
+    {
+      height: diameter,
+      width: diameter,
+      borderRadius: diameter / 2,
+    },
+    customStyle,
+  ];
```
Comment (jpuri) [inline app/components/UI/Identicon/index.tsx:61]: Using `useMemo` here may be useful to avoid re-rendering each time object is created.

**Review by jpuri — DISMISSED** [review]

File: app/components/UI/Identicon/index.tsx (hunk 1 above)
Comment (OGPoyraz) [reply app/components/UI/Identicon/index.tsx:61]: By memoising `styleForBlockieAndTokenIcon` with `useMemo` will not be enough to prevent rerender for `Image` component here.

Together use of `useMemo` and `React.memo` below `Image` component will be sufficient to prevent re render but not `Identicon` only `Image`. So let's assume that we do it in this case. 
``` 
// outside of the component
const MemoizedImage = React.memo(({ src, style }) => {
  return <Image source={{ uri: src }} style={style} />;
});



//in component
const styleForBlockieAndTokenIcon = useMemo(() => ([
  {
    height: diameter,
    width: diameter,
    borderRadius: diameter / 2,
  },
  customStyle,
]), [diameter, customStyle]);

if (tokenListIconUrl) {
    return (
      <MemoizedImage
        src={uri}
        style={styleForBlockieAndTokenIcon}
      />
    );
  }

```

Since we've memoized `styleForBlockieAndTokenIcon` using `useMemo`, its reference will remain stable across renders as long as `diameter` and `customStyle` don't change. This stability in reference is crucial for `React.memo` to be effective because `React.memo` does a shallow comparison of props to determine if re-rendering is necessary.

However problem here is that most `customStyle` is passed like this
```
<IdentIcon
//...
 customStyle={{margin:5}}
 //...
/>
```

Passed styles like `{margin:5}` will lead shallow comparison to be fail so it will not work as we want. If we really sure that `Image` optimisation is important than we need a deeper refactor to remove these styling references first. And then use `React.memo` in the very atomic component.

**Comment by sleepytanya** [comment]
Bitrise builds: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/dc732094-b76d-4ac8-b836-4e905ccdba53?tab=artifacts
 iPhone 15, iOS 17.5.1
Samsung S24+, Android 14

The app slows down significantly with simulations enabled.

iPhone:


https://github.com/MetaMask/metamask-mobile/assets/104780023/c80c1a02-072d-4acf-85f7-eadfbd984962

 Samsung:


https://github.com/MetaMask/metamask-mobile/assets/104780023/d35de537-8839-49a7-ac8b-6b1f39d48b06

File: app/components/hooks/DisplayName/useTokenList.ts [hunk 2]
```diff
@@ -1,38 +1,25 @@
...
-  return Object.keys(tokenMap).reduce((acc, address) => {
-    const tokenMetadata = tokenMap[address];
-    return {
-      ...acc,
-      [address.toLowerCase()]: {
-        ...tokenMetadata,
-      },
-    };
-  }, {});
-}
```
Comment (OGPoyraz) [inline app/components/hooks/DisplayName/useTokenList.ts:21]: I decided to remove this normalizer function because iterating over 1.5MB object is not performant and never achieved to memoize the result of it even using `createDeepSelector` on the `TokenListToken`.

File: app/selectors/tokenListController.ts [hunk 3]
```diff
@@ -20,7 +21,7 @@ export const selectTokenList = createSelector(
  * Return token list array from TokenListController.
  * Can pass directly into useSelector.
  */
-export const selectTokenListArray = createSelector(
+export const selectTokenListArray = createDeepEqualSelector(
```
Comment (matthewwalsh0) [inline app/selectors/tokenListController.ts:24]: ❤️

File: app/components/UI/Identicon/index.tsx [hunk 4]
```diff
@@ -43,23 +45,36 @@ const Identicon: React.FC<IdenticonProps> = ({
   useBlockieIcon = true,
 }) => {
   const { colors } = useTheme();
+  const tokenListArray: TokenListToken[] = useTokenList();
+  const normalizedAddress = address?.toLowerCase();
+  const tokenListIcon = tokenListArray.find(
```
Comment (matthewwalsh0) [inline app/components/UI/Identicon/index.tsx:50]: Could we instead use `useTokenListEntries` to avoid duplicating this `find`?

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by vinistevam — DISMISSED** [review]

File: app/components/UI/Identicon/index.tsx (hunk 4 above)
Comment (OGPoyraz) [reply app/components/UI/Identicon/index.tsx]: Good suggestion, added this

**Review by matthewwalsh0 — APPROVED** [review]

**Comment by sleepytanya** [comment]
Bitrise QA builds: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/613024ad-473f-4ac9-bc82-112fa1f68a89?tab=artifacts

iPhone15, Samsung S24+
Token icons displayed correctly, no performance issues.

Android:


https://github.com/MetaMask/metamask-mobile/assets/104780023/e309432b-d974-472b-bac5-a52945f90bc7


iOS:


https://github.com/MetaMask/metamask-mobile/assets/104780023/da3bf6d3-b19f-4f6e-8456-220d50582337
