### PR TITLE
fix: incorrect network when adding token

### LINKED ISSUE #20927: [Bug] When importing token, it does not default to the current network active
View issue in GitHub: https://github.com/MetaMask/metamask-mobile/issues/20927

Build: 7.57 (2680)

1. Add custom network (HEMI)
2. Click the + button to import token
3. Import token screen should be displayed

Expected: Verify the current network is defaulted on Import Token screen
Actual: Polygon is selected on Import Token screen

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFtQ3c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0c6173fbb0ae28324ce08368839c0002e23aa42/ImportToken-NotCurrentNetwork.MP4)

### PR DESCRIPTION
**Pull request by juanmigdr**
## **Description**
Switching networks does not affect the selected network on the "Import Tokens" screen, the selected network should be the chosen network by default.

After investigation I found out that if prior to opening the "Import tokens" screen, we opened the "Swap" screen, the issue was fixed. After further digging it turns out we are not updating the network on the MultichainNetworkController when switching networks and Swaps had a fallback for this.

**Furthermore, the looks of this screen should be improved in a separate PR to improve user experience on adding tokens**

## **Changelog**

CHANGELOG entry: when adding a token the network selected is wrong

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/20927 & https://consensyssoftware.atlassian.net/browse/ASSETS-1390

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

https://github.com/user-attachments/assets/aec5cef7-d5e1-4d6b-860d-042733c2cc8a

### **After**

https://github.com/user-attachments/assets/14152b4e-bf09-470d-8e2d-353eaca0cb26

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Ensure MultichainNetworkController switches to the correct active network when enabling/selecting networks, defaulting to Ethereum after enabling all popular networks, with tests updated accordingly.
> 
> - **Hooks (`useNetworkSelection`)**:
>   - Add `selectNetworkConfigurationsByCaipChainId` selector to access full network configs.
>   - Implement `switchActiveNetwork(caipChainId)` to set `MultichainNetworkController` active network via `networkClientId` from config `rpcEndpoints`.
>   - Invoke `switchActiveNetwork` after `enableNetwork` in `selectCustomNetwork` and `selectPopularNetwork`.
>   - After `enableAllPopularNetworks`, switch active network to `eip155:1` (Ethereum Mainnet).
> - **Tests**:
>   - Mock `selectNetworkConfigurationsByCaipChainId` and provide configs with `networkClientId`s.
>   - Assert `MultichainNetworkController.setActiveNetwork` is called (e.g., with `mainnet-client-id`) after selection and after enabling all popular networks.
>   - Minor test adjustments, including error-path coverage for `setActiveNetwork`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 636ad9572653c38faed50f179a0f8cdec300cb1d. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/hooks/useNetworkSelection/useNetworkSelection.ts [hunk 1]
```diff
@@ -105,6 +113,37 @@ export const useNetworkSelection = ({
...
+      const networkConfig = networkConfigurations[caipChainId];
+      if (!networkConfig || !('rpcEndpoints' in networkConfig)) {
+        // Configuration is missing or lacks RPC endpoints
+        return;
+      }
+
+      const { rpcEndpoints, defaultRpcEndpointIndex } = networkConfig;
+      const { networkClientId } = rpcEndpoints[defaultRpcEndpointIndex];
+
+      await MultichainNetworkController.setActiveNetwork(networkClientId);
```
Comment (bergarces) [inline app/components/hooks/useNetworkSelection/useNetworkSelection.ts:142]: Not 100% sure, but shouldn't this be called in `NetworkController`?

Comment (bergarces) [reply app/components/hooks/useNetworkSelection/useNetworkSelection.ts:142]: Nevermind, I've just seen the function description and it allows evm ids.

**Review by salimtb — APPROVED** [review]

**Review by bergarces — APPROVED** [review]
