### PR TITLE
fix: cp-7.47.0 reset bridge state after swap

### LINKED ISSUE #16196: [Bug]: Solana - Swap - Previous Swap amount and destination token values are cached when starting a fresh new Swap
### Describe the bug

Previous Swap amount and destination token values are cached when starting a fresh new Swap.
Instead of seeing empty values, I see the Swap form already pre-filled with my previous Swap values

### Expected behavior

The Swap values should be clear whenever we start a new fresh Swap.

### Screenshots/Recordings

https://github.com/user-attachments/assets/d21244b2-77c2-40f5-a817-5c25e6849b97

### Steps to reproduce

1. Select Solana
2. Perform a Swap SOL - DAI (example) with any amount
3. Confirm tx
4. Start a new Swap
5. See the amount and destination token is already pre-filled with the values from step 2

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

@seaona Description seaona opened on Jun 9, 2025 Describe the bug  Cannot perform Send flows when Basic functionality is off Expected behavior  Same as in EVM networks? We should be able to perform Send flows, when Basic functionality is off Screenshots/Recordings send-solana-basic-func-mobile.mp4 Steps to reproduce      Select Solana     Go to privacy settings     Disable Basic functionality     Click Send     See you remain at the Home page  Error messages or log output  Detection stage  During release testing Version  7.47 (1953)

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by bfullam**
## **Description**
Currently the bridge state is not reset after a swap because an old check on the isSubmitting status is preventing it. This PR removes that deprecated check to allow for proper state reset after a swap is completed.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/16196

## **Manual testing steps**

1. Select Solana
2. Perform a Swap SOL - DAI (example) with any amount
3. Confirm tx
4. Start a new Swap
5. See the amount and destination token is already pre-filled with the values from step 2

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Bridge/Views/BridgeView/index.tsx [hunk 1]
```diff
@@ -211,13 +211,10 @@ const BridgeView = () => {
...
   useEffect(
     () => () => {
-      // Only reset state if we're not in the middle of a transaction
-      if (!isSubmittingTxRef.current) {
-        dispatch(resetBridgeState());
-        // Clear bridge controller state if available
-        if (Engine.context.BridgeController?.resetState) {
-          Engine.context.BridgeController.resetState();
-        }
+      dispatch(resetBridgeState());
```
Comment (SteP-n-s) [inline app/components/UI/Bridge/Views/BridgeView/index.tsx:205]: hm, does this mean that now we can reset the state if you're in the middle of a transaction?

Comment (bfullam) [reply app/components/UI/Bridge/Views/BridgeView/index.tsx:205]: No, this check was only built in to prevent a race condition that happened when we were trying to navigate to the transaction history page **after** the snap confirmation. Since we navigate there before now, that race condition doesn't happen and instead this check prevents the state from being reset at all.

**Review by SteP-n-s — APPROVED** [review]
