### PR TITLE
fix: breaking change from `@metamask/transaction-controller` regarding Ledger transactions

### LINKED ISSUE #8917: [BUG] Unable to send transaction using Ledger device
Describe the bug
User is unable to send a transaction using Ledger device to another account within the account list. Unexpected Error is displayed

Expected behaviour
User is able to send a transaction using Ledger device to another account

Screenshots/Recordings

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy9ZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--919d54520223f7e97f9d3239e9ea2d08b6455064/Screen_Recording_20240313_113554_MetaMask.mp4)

Steps to reproduce
1. Connect Ledger device
2. Switch network to Linea Testnet
3. Send transaction from Ledger account to Account 2 (normal account)
4. Confirm transaction on Ledger device
5. Error displayed

Error messages or log output
`WARN  Non-serializable values were found in the navigation state. Check:LedgerTransactionModal > params.onConfirmationComplete (Function)This can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/troubleshooting#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state for more details.LOG  [MetaMask DEBUG]: Analytics 'trackEventWithParameters' - {"category":"Ledger hardware wallet error"} {"device_type": "Ledger", "error": "UnknownError"} undefined undefined WARN  Possible Unhandled Promise Rejection (id: 5):Error: transaction underpricedError: transaction underpriced
    at construct (native)
    at Wrapper (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:27345:64)
    at construct (native)
    at _createSuperInternal (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:343931:406)
    at call (native)
    at EthereumRpcError (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:343949:26)
    at getEthJsonRpcError (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:344441:78)
    at internal (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:344375:34)
    at ?anon_0_ (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:678531:93)
    at next (native)
    at fulfilled (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:677869:30)
    at tryCallOne (/Users/viveksrilal/Documents/Projects/MMLedger/GitHub/metamask-mobile-ledger/metamask-mobile/node_modules/react-native/ReactAndroid/hermes-engine/.cxx/Release/3us355wb/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/viveksrilal/Documents/Projects/MMLedger/GitHub/metamask-mobile-ledger/metamask-mobile/node_modules/react-native/ReactAndroid/hermes-engine/.cxx/Release/3us355wb/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:33913:26)
    at _callTimer (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:33832:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:33862:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:34025:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:2493:46)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:2305:45)
    at __guard (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:2477:15)
    at flushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:2304:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:2298:33)`

Version
7.17.1
https://app.bitrise.io/app/be69d4368ee7e86d/build/ba8b574b-942c-4b72-a5fa-f8074a1222fc/artifact/5c757ba4c8fcbfb4/p/012b3b638d115dc53e2c1c9d52e05c72

Build type
None

Device
Samsung S21

Operating system
Android 13

Severity
Sev-1-high

### PR DESCRIPTION
**Pull request by dawnseeker8**
## **Description**

After the TransactionController upgrade to 8.0.1, it use `@ethereumjs/tx: 4.2.0 version, this library have break change on tx.common class which drop function chainIdBN(), and the old version @ethereumjs/tx: 3.5.0 used in @consensys/ledgerhq-metamask-kering still use the old version of tx.common and deprecated chainIdBN() function in BaseTransaction.ts.

So to fix the issue in main branch, we need to upgrade @consensys/ledgerhq-metamask-kering to use @ethereumjs/tx: 4.2.0. and then upgrade `main` branch to use latest `@consensys/ledgerhq-metamask-kering`.

## **Related issues**

Fixes: #8917 

### send funds screen ( please make sure PR #8930 merged to `main` branch first)
1. Connect Ledger device
2. Switch network to Linea Testnet
3. Send transaction from Ledger account to Account 2 (normal account)
4. Confirm transaction on Ledger device
5. Transaction should successfully submitted.

### test-dapp send coin transacation
1. Connect Ledger device
2. Switch network to Linea Testnet
3. open `test-dapp`  https://metamask.github.io/test-dapp 
4. connect the dapp with your ledger wallet.
5. click `Send EIP 1559 Transaction`.
6. Confirm in `ledger`
7. your transaction should be submitted successfully and complete successfully.

### **Before**
https://github.com/MetaMask/metamask-mobile/assets/106310394/0ae2fddb-40d1-4b13-af8c-0143525bf28f

### **After**

https://github.com/MetaMask/metamask-mobile/assets/7315988/326b34a7-904e-4f01-9d18-52c47cd072bc

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by dawnseeker8** [comment]
Smoke E2E tests passd in this link https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/ae55294b-24d2-4b99-abd0-8a92bfe0bcce

File: app/components/Views/confirmations/SendFlow/Confirm/index.js [hunk 1]
```diff
@@ -831,6 +831,8 @@ class Confirm extends PureComponent {
 
       const { result, transactionMeta } = this.state;
 
+      await this.persistTransactionParameters(transaction);
+
```
Comment (dawnseeker8) [inline app/components/Views/confirmations/SendFlow/Confirm/index.js:835]: Above change is to fix the issue during send funds in ledger cause the `gas underprice`.  the cause is `await this persistTransactionParameters()` have been put below ledger code, which cause ledger transaction have not gas information submitted. the fix is move that function from line 865 above the ledger code so that TranscactionController can store the transaction detail before ledger submit the transaction.

**Review by gantunesr — APPROVED** [review]

**Comment by gantunesr** [comment]
Lets have this QAed before merging @dawnseeker8 and @vivek-consensys

**Comment by angelcheung22** [comment]
@vivek-consensys  please help to QA this one.

**Comment by vivek-consensys** [comment]
Tested on iPhone 13 on iOS 17.3.1 using Bitrise build:- https://app.bitrise.io/build/6a2bd46b-4134-45be-a1af-5eca5f5fc796?tab=artifacts


[Swap Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODd2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c337dffd8d81bd37a6704cff7fdcb077e213e868/RPReplay_Final1710843240.MP4)


[Send Txn Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUR2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a74a182a2baefac3cf43d80e96b07a6353ded50/RPReplay_Final1710843065.MP4)
