### PR TITLE
fix: cp-7.50.2 retrieving configured chains from NetworkController 

### LINKED ISSUE #17167: TypeError: undefined is not an object (evaluating 't.multichainNetworkConfigurationsByChainId')
Sentry Issue: [METAMASK-MOBILE-3XFW](https://metamask.sentry.io/issues/6740821095/?referrer=github_integration)

```
TypeError: undefined is not an object (evaluating 't.multichainNetworkConfigurationsByChainId')
  at e.selectNonEvmNetworkConfigurationsByChainId (app/selectors/multichainNetworkController/index.ts:60:7)
  at getConfiguredCaipChainIds (app/util/metrics/MultichainAPI/networkMetricUtils.ts:39:20)
  at e.default (app/util/metrics/UserSettingsAnalyticsMetaData/generateUserProfileAnalyticsMetaData.ts:24:20)
  at this.configure (app/core/Analytics/MetaMetrics.ts:573:12)
...
(17 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by wenfix**
## **Description**

[This issue](https://github.com/MetaMask/metamask-mobile/issues/17167) shows the app crashing due to trying to access state for identity analytics that's not immediately available. This PR adds a safer way to access this state, returning gracefully in case it doesn't exist or we hit a race condition.

## **Changelog**
CHANGELOG entry: Fixes a bug that causes thee app to crash when accessing `NetworkController` and `MultichainNetworkController` state that is undefined.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/17167

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/metrics/MultichainAPI/networkMetricUtils.ts [hunk 1]
```diff
@@ -36,9 +36,31 @@ function caipifyChainId(chainId: CaipChainId | string): CaipChainId {
...
+      ...nonEvmNetworkConfigurations,
+    };
+
+    const chainIds = Object.values(allNetworkConfigurations)
+      .filter((network) => network && network?.chainId)
+      .map((network) => caipifyChainId(network.chainId));
+
+    return chainIds;
+  } catch (error) {
+    return [];
```
Comment (wenfix) [inline app/util/metrics/MultichainAPI/networkMetricUtils.ts]: Returning gracefully here to prevent a potential crash. Should we log this condition should we get here? @adonesky1

Comment (adonesky1) [reply app/util/metrics/MultichainAPI/networkMetricUtils.ts]: I don't think we should try/catch here since we're using the optional chaining we shouldn't have any state access issues

Comment (wenfix) [reply app/util/metrics/MultichainAPI/networkMetricUtils.ts]: ty, removed the try-catch!

Comment (tommasini) [reply app/util/metrics/MultichainAPI/networkMetricUtils.ts]: Since we lost te memoization effect from the selector usage, I'm wondering if it makes sense to try to memoize this function (Since it's an util function I'm not sure we can do it, just an idea that came out )

Comment (wenfix) [reply app/util/metrics/MultichainAPI/networkMetricUtils.ts]: I don't think we can do it via React's `useMemo` given that it's not called inside a React hook. Using lodash seems overkill. Any suggestions?

File: app/util/metrics/MultichainAPI/networkMetricUtils.ts [hunk 2]
```diff
@@ -35,10 +35,31 @@ function caipifyChainId(chainId: CaipChainId | string): CaipChainId {
  * @returns An array of CAIP chain IDs for all configured networks.
  */
 export function getConfiguredCaipChainIds(): CaipChainId[] {
+  // We're accessing state directly and safely here because there's a potential race condition
+  // that causes the state to be undefined where we access it.
+  // Issue described here: https://github.com/MetaMask/metamask-mobile/issues/17167
```
Comment (adonesky1) [inline app/util/metrics/MultichainAPI/networkMetricUtils.ts]:
```suggestion
  // We're accessing state with optional chaining here because there's a race condition
  // that causes redux state to be undefined when we access it.
  // Issue here: https://github.com/MetaMask/metamask-mobile/issues/17167
```

**Review by adonesky1 — APPROVED** [review]
LGTM

File: app/util/metrics/MultichainAPI/networkMetricUtils.ts [hunk 3]
```diff
@@ -35,10 +35,31 @@ function caipifyChainId(chainId: CaipChainId | string): CaipChainId {
...
-  const networks = selectNetworkConfigurations(state);
+  const evmNetworkConfigurations =
+    state?.engine?.backgroundState?.NetworkController
+      ?.networkConfigurationsByChainId || {};
+
+  const multichainNetworkController =
+    state?.engine?.backgroundState?.MultichainNetworkController;
+
+  const nonEvmNetworkConfigurations =
+    multichainNetworkController?.multichainNetworkConfigurationsByChainId || {};
```
Comment (tommasini) [inline app/util/metrics/MultichainAPI/networkMetricUtils.ts:51]:
```suggestion
  const nonEvmNetworkConfigurations = state?.engine?.backgroundState?.MultichainNetworkController?.multichainNetworkConfigurationsByChainId || {};
```

**Review by tommasini — APPROVED** [review]
