### PR TITLE
fix: order size and margin displayed on trade screen differ from execution for small amounts

### LINKED ISSUE #19832: [Bug]: Incorrect margin calculation / display on the create position screen
## Describe the bug

Start with available margin: $5.56
First trade:
It says it requires $3.67 of margin to buy 0.0025 ETH
But instead it uses $3.98 to buy 0.0025 ETH

Second trade:
It says it requires $3.67 of margin to buy 0.0025 ETH
But instead it uses ($5.39-3.97=) $1.42 of margin to buy (0.0036 - 0.0025=) 0.0011 ETH
There wasn't enough balance available but the trade went through

Third trade:
The trading screen doesn’t notice you have only $0.14 left in your perp account, and allows you to go ahead and the order fails to be created

## Expected behavior

The margins must be calculated correctly and refreshed on the UI

## Screenshots/Recordings

https://github.com/user-attachments/assets/5ef13783-34d7-4f1a-8d13-c4316231b333

## Steps to reproduce

1. Go to Perps and start with a relatively low balance on your account
2. Start a trade that will reduce the balance to a lower value
3. Repeat the trade ( this should ideally not go ahead as you don't have enough balance to complete it)

## Error messages or log output

```shell

```

## Detection stage

During release testing

## Version

7.56.0

## Build type

None

## Device

iPhone 15

## Operating system

iOS

### PR DESCRIPTION
**Pull request by nickewansmith**
## **Description**

1. What is the reason for the change?

Order size and margin displayed on trade screen differed from execution for small amounts due to position size rounding behavior.

2. What is the improvement/solution?

Optimization: Automatically finds the highest USD amount that results in the same position size
Accuracy: Uses mark price for calculations, ensuring consistency with execution
User Experience: Maximizes value while maintaining intended position size

📊 Technical Details
Position Size Calculation Enhancement
Uses Math.ceil() for rounding (choosing higher end of range)

Comment clarification: "HL chooses the order size closest to the usd value on the low end. We instead choose the order size closest to the usd value on the high end"

Form interactions: All amount-setting actions trigger optimization
Market data: Optimization only runs when valid market data is available
Balance limits: Respects available balance constraints

Breaking Changes
usePerpsOrderForm no longer returns calculations object
Components must calculate margin locally using available market data

Backward Compatibility
All existing functionality preserved
Optimization is additive - doesn't change core order placement logic

## **Changelog**

CHANGELOG entry: Changed perps order form to snap to the highest dollar amount for the related position size.

## **Related issues**

Fixes: https://consensyssoftware.atlassian.net/browse/TAT-1695
Fixes: https://github.com/MetaMask/metamask-mobile/issues/19832

## **Manual testing steps**

```gherkin
Feature: fix margin used and order value correctness

  Scenario: user order flow
    Given a user is on the order view
    When user places an order
    Then the margin used should be very near to equal to what shows up in HL ui give or take req time and possibly price 
    When user places an order
    Then the position dollar value spent in HL ui should be at or below the highest dollar amount before the next position size

  Scenario: user order flow
    Given a user is on the market detail page and is ready to place an order
    When user initially loads the order view 
    Then the initial order amount should be set to the highest dollar amount they will spend to order that position size
    When user initially loads the order view and they don't have enough to make an order
    Then the amount the they can spend will be set and the slider will be disabled

  Scenario: user order flow
    Given a user is on the market detail page and is ready to place an order
    When user selects percentage buttons or manually edits the amount
    Then the final amount will update to the highest dollar amount that could be spent for the position size


```

### **After**
https://github.com/user-attachments/assets/dc7bc2b7-0833-4f21-8f68-80c713333a4e

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Optimizes order sizing to the highest USD for the same position size, computes margin locally using mark price, updates hooks/context API and UI, and adds comprehensive tests.
> 
> - **Perps Order View (UI/logic)**
>   - Compute `marginRequired` locally using `markPrice` via `calculateMarginRequired` and pass to validation.
>   - Integrate new context fields: `optimizeOrderAmount` and `maxPossibleAmount`; remove reliance on `calculations` from context.
>   - Clamp inputs and slider to `maxPossibleAmount`; trigger optimization on percentage/slider changes; show "Insufficient funds" when below minimum.
>   - Use `positionSize` from `calculatePositionSize`; refine tooltip handling and header interactions.
> - **Hooks/Context**
>   - `usePerpsOrderForm`: remove `calculations` return; add debounced `optimizeOrderAmount` and `maxPossibleAmount` (derived from live price/market data); initialize amount with `findOptimalAmount`.
>   - Consume live prices and market data to derive limits and optimal amounts.
> - **Utils**
>   - Update `calculatePositionSize` rounding (conservative rounding); add `findOptimalAmount`, `findHighestAmountForPositionSize`, and `getMaxAllowedAmount`.
> - **Tests**
>   - Update/expand tests for order view interactions (tooltips, insufficient funds, header), new hook behavior, and new utils; adjust tooltip tests to use stream provider.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 36c9d2d038f3478ae1b59c2536bde8e7f4660f44. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by nickewansmith** [comment]
Testing this again I found an issue with ASTER coin order form that I am currently looking into.

File: app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx [hunk 1]
```diff
@@ -642,13 +664,40 @@ const PerpsOrderViewContentBase: React.FC = () => {
       if (currentAmount > maxAllowed) {
         setAmount(String(maxAllowed));
       }
+
+      // Optimize the amount after keypad input is complete
+      // Use a timeout to ensure the amount has been set first
+      setTimeout(() => {
+        optimizeOrderAmount(assetData.price, marketData?.szDecimals);
+      }, 0);
```
Comment (gambinish) [inline app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx]: Is there a way to do this without a setTimeout? Maybe `requestAnimationFrame` or something along those lines?

I'm actually not sure if that would be any better, but just a thought

Comment (gambinish) [reply app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx]: If we stick with setTimeout approach, we may want to clear timeout to cleanup the effect: https://codesandbox.io/p/sandbox/react-settimeout-with-useeffect-hook-69oed?file=%2Fsrc%2FApp.js

File: app/components/UI/Perps/hooks/usePerpsOrderForm.ts [hunk 2]
```diff
@@ -52,6 +54,16 @@ export function usePerpsOrderForm(
...
   const { account } = usePerpsLiveAccount();
+  const prices = usePerpsLivePrices({
+    symbols: [initialAsset],
+    throttleMs: 1000,
+  });
+  const currentPrice = prices[initialAsset];
+  const {
+    marketData,
+    // isLoading: isLoadingMarketData,
+    // error: marketDataError,
```
Comment (gambinish) [inline app/components/UI/Perps/hooks/usePerpsOrderForm.ts]: Is this commented code intentional?

File: app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx [hunk 3]
```diff
@@ -275,6 +285,19 @@ const PerpsOrderViewContentBase: React.FC = () => {
...
+    () => () => {
+      if (optimizeTimeoutRef.current) {
+        clearTimeout(optimizeTimeoutRef.current);
+      }
+      if (keypadOptimizeTimeoutRef.current) {
+        clearTimeout(keypadOptimizeTimeoutRef.current);
+      }
+    },
+    [],
+  );
```
[the remark this answers is not in the document]
Comment (gambinish) [reply app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx]: Hmm, I think this bugbot comment might actually be legit. I can help take a look at this

File: app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx (hunk 1 above)
Comment (nickewansmith) [reply app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx]: Removed all setTimeouts, while and for loops

File: app/components/UI/Perps/utils/orderCalculations.ts [hunk 4]
```diff
@@ -51,3 +61,193 @@ export function calculateMarginRequired(params: MarginRequiredParams): string {
...
+  }
+
+  if (highestAmount > maxAllowedAmount) {
+    const decrementedPositionSize =
+      (Math.ceil(positionSizeNum * multiplier) - 1) / multiplier;
+
+    // If the decremented position size would be 0 or negative, return original amount
+    if (decrementedPositionSize <= 0) {
+      return '0';
+    }
```
[the remark this answers is not in the document]
Comment (nickewansmith) [reply app/components/UI/Perps/utils/orderCalculations.ts:156]: This might have been updated by mistake as it was in sync with the comment above.

File: app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx [hunk 5]
```diff
@@ -368,6 +393,21 @@ const PerpsOrderViewContentBase: React.FC = () => {
...
+      });
+    }
+  }, [
+    orderForm.amount,
+    assetData.markPrice,
+    orderForm.leverage,
+    isLoadingMarketData,
+    positionSize,
+  ]);
+
```
[the remark this answers is not in the document]
Comment (nickewansmith) [reply app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx:378]: We must use the mark price to get accurate margin

**Review by gambinish — APPROVED** [review]
