### PR TITLE
fix: add autoscroll in RPC URL form when virtual keyboard blocks content

### LINKED ISSUE #12154: [Bug]: In the "Add RPC URL" modal, the "RPC Name" field becomes obscured by the keyboard on mobile devices
### Describe the bug

In the `Add RPC URL` modal, the `RPC Name` field becomes obscured by the keyboard on mobile devices—completely on Android and partially on iOS.

### Expected behavior

-

### Screenshots/Recordings

Android:

https://github.com/user-attachments/assets/6e9eff24-0a50-4611-97ac-e8c32586f629

iOS:

https://github.com/user-attachments/assets/28540a19-2e08-44c4-ae1c-70d2f5d4c233

### Steps to reproduce

1. Add new RPC URL

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

7.34.0 (1473)

### Build type

None

### Device

iPhone 15, Samsung S24+

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12154

## **Manual testing steps**

1. Visit the RPC form in video
2. Click into the fields to edit/add
3. EXPECTED - you should see the device scroll to make sure the input is visible

### **After**

https://www.loom.com/share/4750e5fe528445d893f9e80f9abd9f00?sid=8a2d12ef-46b0-4bf2-aa4b-555166499ffd

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 1]
```diff
@@ -175,11 +176,6 @@ const createStyles = (colors) =>
       backgroundColor: colors.background.default,
       borderTopLeftRadius: 10,
       borderTopRightRadius: 10,
-      height: Device.getDeviceHeight() * 0.7,
-    },
-    sheetContent: {
-      flex: 1,
-      flexShrink: 1,
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:182]: This container styles is not needed.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 2]
```diff
@@ -175,11 +176,6 @@ const createStyles = (colors) =>
       backgroundColor: colors.background.default,
       borderTopLeftRadius: 10,
       borderTopRightRadius: 10,
-      height: Device.getDeviceHeight() * 0.7,
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:178]: Dropping the height field here, and allowing the `KeyboardAwareScrollView` to control the height allows us to inherit the "auto-scroll to input" behaviour

**Review by vinnyhoward — APPROVED** [review]
