### PR TITLE
fix: Add `networkClientId` to `estimateGas` function

### LINKED ISSUE #12612: [Bug]: Intrinsic gas too low / Internal JSON-RPC / Intrinsic gas exceeds gas limit for Linea  error when sending non-native tokens on all Popular networks
### Describe the bug

Error message when sending non-native tokens on Ethereum Mainnet:

`Intrinsic gas too low: gas 21000, minimum needed 21620`

### Expected behavior

No error message

### Screenshots/Recordings

https://github.com/user-attachments/assets/56eefc38-7370-4e8f-a31e-b791afa65c77

### Steps to reproduce

1. Switch to Ethereum Mainnet
2. send any token except ETH native token
3. notice gas limit error

### Error messages or log output

```shell

```

### Detection stage

In beta

### Version

7.36.0 (1505)

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

Latest 2 QA builds

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to add `networkClientId` argument to `estimateGas` function.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12612

## **Manual testing steps**

1. Try sending non-native asset initiated from app
2. See no "Instricted gas too low" error 
3. Expect transaction to be passed

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/confirmations/SendFlow/Amount/index.js [hunk 1]
```diff
@@ -1570,6 +1580,7 @@ const mapStateToProps = (state, ownProps) => ({
   ),
   swapsIsLive: swapsLivenessSelector(state),
   chainId: selectChainId(state),
+  networkClientId: selectNetworkClientId(state),
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/SendFlow/Amount/index.js:1583]: I've a separate PR removing all usages of the global network selectors in confirmations, but I appreciate this is a quick fix to resolve the regression.

**Review by matthewwalsh0 — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Comment by Unik0rnMaggie** [comment]
Fix works for both sending non-native tokens and ERC721 tokens:


https://github.com/user-attachments/assets/f8e86e4d-0447-404a-81ed-048d50471501


https://github.com/user-attachments/assets/9b7d3def-0c41-4e1f-8dca-22964dea8a3f

Small issue noted: after sending the NFT, the MM app closes

**Comment by sleepytanya** [comment]
@Unik0rnMaggie  Can't reproduce issue with ERC 721 as 'Next' is disabled for me

**Comment by Unik0rnMaggie** [comment]
Thank you very much @sleepytanya ! It seems you are experiencing [this](https://github.com/MetaMask/metamask-mobile/issues/12317) bug 

I'm also not sure why using the build from this fix it works to send NFTs, and using the latest RC build i'm still experiencing [the errors](https://github.com/MetaMask/metamask-mobile/issues/12317#issuecomment-2592174904)
