### PR TITLE
fix: blockaid banner fix for signature requests - warning should not disappear after checking message details

### LINKED ISSUE #7804: [Bug]: PPOM - Warning disappears for Signatures after checking Signature Details
### Describe the bug

**Problem:** whenever we are triggering a Signature, the ppom warning disappears after checking the signature details and going back to the Confirm screen.

### Expected behavior

- The warning should still be present when you go back to the Confirmation screen
- Should the warning be also present in the Signature details view? cc @bschorchit 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/e32892a9-2b87-445a-9a47-b3b4858ae797

### Steps to reproduce

1. Enable Blockaid
2. Trigger a Signature
3. See warning
4. Check signature details - now warning there
5. Go back to the Confirmation screen
6. See there's no warning anymore

### Error messages or log output

_No response_

### Version

develop (with blockaid feature flag on)

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**
Blockaid banner fix for signature requests - warning should not disappear after checking message details.

## **Related issues**

Fixes: #7804

## **Manual testing steps**

1. Go to test dapp
2. Submit a malicious signature request
3. Warning from blockaid appears
4. Go to message details and navigate back
5. Warning should not disappear

## **Screenshots/Recordings**
https://github.com/MetaMask/metamask-mobile/assets/2182307/b5965706-1a2a-47f2-ad4b-d4d241d08aab

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've clearly explained what problem this PR is solving and how it is solved.
- [X] I've linked related issues
- [X] I've included manual testing steps
- [X] I've included screenshots/recordings if applicable
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [X] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by jpuri** [comment]
Bitrise: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/04b46fe0-9d1f-411b-b801-4b85ab9441eb

**Review by blackdevelopa — APPROVED** [review]

File: app/components/UI/SignatureRequest/Root/Root.tsx [hunk 1]
```diff
@@ -42,6 +42,9 @@ const Root = ({
 
   useEffect(() => {
     store.dispatch(setSignatureRequestSecurityAlertResponse());
+    return () => {
+      store.dispatch(setSignatureRequestSecurityAlertResponse());
+    };
```
Comment (segun) [inline app/components/UI/SignatureRequest/Root/Root.tsx:47]: This will call it twice?

**Review by cryptotavares — APPROVED** [review]

File: app/components/UI/SignatureRequest/Root/Root.tsx (hunk 1 above)
Comment (jpuri) [reply app/components/UI/SignatureRequest/Root/Root.tsx:47]: Yep the second one will work on unmount.
