### PR TITLE
fix: WalletConnect requests should show loading banner for blockaid.

### LINKED ISSUE #7768: QR Code scanning is broken
[This commit](https://github.com/MetaMask/metamask-mobile/commit/6697afbe7d671ef0f43fb115c5b25387fe57989d) seems to have broken QR Code Scanning, every QR Code request now shows the attached error.

Commenting out line 128 from [this file](https://github.com/MetaMask/metamask-mobile/blob/6697afbe7d671ef0f43fb115c5b25387fe57989d/app/components/Views/QRScanner/index.tsx) seems to fix the issue for Deeplink and WalletConnect

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEhJQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7432313f5851ad685eeb4ced81581811280fd2e6/image.png)

### PR DESCRIPTION
**Pull request by segun**
## **Description**

Make PPOM validations for deeplink and walletconnect async to leverage recent blockaid performance improvements

The changes to app/components/Views/QRScanner/index.tsx are necessary as it's a bug introduced by a recent commit. Details of the bug and the fix [here](https://github.com/MetaMask/metamask-mobile/issues/7768)

## **Related issues**

Fixes: [#1655](https://github.com/MetaMask/MetaMask-planning/issues/1655)

1. Checkout branch and run on real device
2. Comment out the line described [here](https://github.com/MetaMask/metamask-mobile/issues/7768)
3. Go to [testdapp for wallet connect](https://seaona.github.io/test-dapp/)
4. Connect wallet using wallet connect 
5. Perform a PPOM Transaction
6. You should see a loading banner and after a few moments see the blockaid banner (as shown in image below)

### **Before**
IMG_1573

### **After**

IMG_1572

Then

IMG_1573

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/QRScanner/index.tsx [hunk 1]
```diff
@@ -124,8 +124,8 @@ const QRScanner = () => {
 
       if (
         origin === Routes.SEND_FLOW.SEND_TO ||
-        origin === Routes.SETTINGS.CONTACT_FORM ||
-        origin === Routes.WALLET_VIEW
+        origin === Routes.SETTINGS.CONTACT_FORM
+        // origin === Routes.WALLET_VIEW
```
Comment (jpuri) [inline app/components/Views/QRScanner/index.tsx:128]: Hey @segun is above intended change ?

Comment (segun) [reply app/components/Views/QRScanner/index.tsx:128]: I made this change so I could work with QR Code, otherwise I get error every single time I try to scan a QR Code. I made a comment about it in the PR Description.

There's already an issue logged to fix this (against the core team I guess cc @seaona). So once that issue is fixed, I can rebase and remove this change.

**Review by jpuri — APPROVED** [review]

**Comment by jpuri** [comment]
Changes look good, will be great if some unit test coverage can also be added to it.

**Review by blackdevelopa — APPROVED** [review]

**Comment by blackdevelopa** [comment]
@segun, it seems [bitrise](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/f9f4651b-929a-4291-8abe-19c663019bc9) is failing. Can you update branch and retry?

**Comment by segun** [comment]
Bitrise https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/009996a4-a89d-4719-aec8-bf60dca596f2
