### PR TITLE
Use Linking to support URLs using default browser

### LINKED ISSUE #1295: Unable to click submit on bug report or support ticket page on android devices
User reported being unable to submit a ticket directly within the app.  One of our CS agents was able to reproduce this on his Android device: https://imgur.com/B5NgwOS

Re: support case: 29719

### PR DESCRIPTION
**Pull request by rickycodes**
re: #1295 

context: when the user goes to "Send Feedback" and they're presented with "GENERAL" and "BUG REPORT" the user will be prompted to open the link in their default browser. this is because the zendesk form does not submit in metamask mobile. this should _only_ affect functionality in android.

<strike>Alternatively we could check what platform is being used and only adjust this functionality on Android?</strike>

this PR does this now

resolves: #1295

### CODE REVIEW

**Review by estebanmino — CHANGES_REQUESTED** [review]
i'd like to fix the issue inside the app rather than sending the user to other app and fix it later. WDYT?

**Comment by rickycodes** [comment]
I added the platform check so the two support links only promp user for default browser on Android.

File: app/components/UI/DrawerView/index.js [hunk 1]
```diff
@@ -285,6 +286,8 @@ const drawerBg = require('../../../images/drawer-bg.png'); // eslint-disable-lin
 const instapay_logo_selected = require('../../../images/mm-instapay-selected.png'); // eslint-disable-line
 const instapay_logo = require('../../../images/mm-instapay.png'); // eslint-disable-line
 
+const USE_EXTERNAL_LINKS = (Platform.OS === 'android') | false;
```
Comment (rickycodes) [inline app/components/UI/DrawerView/index.js]: I need to change this to `||`

**Review by brunobar79 — APPROVED** [review]
LGTM

**Review by estebanmino — APPROVED** [review]

**Review by ibrahimtaveras00 — APPROVED** [review]
Looks good, QA Passed 👍
