### PR TITLE
fix: Unnecessary truncation for MainActionButton and BottomNav cp-7.55.0

### LINKED ISSUE #18478: [Bug]: Homepage buttons display text improperly abbreviated on iPhone Pro
### Describe the bug

See screnshot below. Most buttons are abbreviated to the point that it's hard for the user to understand the meaning. Happens only on iPhone 12 Pro. Not on Max or Android

### Expected behavior

_No response_

### Screenshots/Recordings

Image

### Steps to reproduce

1. Install 7.54 on iPhone Pro
2. Notice the buttons have abbreviated text

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.54.0

### Build type

None

### Device

iPhone 12 Pro

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by brianacnguyen**
## **Description**
This PR added a flex shrink 0 to the `MainActionButton` text to prevent unnecessary truncations

## **Changelog**

CHANGELOG entry: Fixed unnecessary truncation for the main action buttons on the homepage

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/18478

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **After**
Simulator Screenshot - iPhone 12 Pro - 2025-09-03 at 09 37 51

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/component-library/components-temp/MainActionButton/MainActionButton.tsx [hunk 1]
```diff
@@ -73,14 +78,26 @@ const MainActionButton = ({
...
-          </Text>
+          {!shouldUseProtectedText ? (
+            // Phase 1: Visible text with flexShrink: 0 (no truncation protection)
+            <Text
+              variant={TextVariant.BodySMMedium}
+              color={TextColor.Default}
+              style={[styles.label, { flexShrink: 0 }]}
+            >
+              {label}
+            </Text>
```
Comment (georgewrmarshall) [inline app/component-library/components-temp/MainActionButton/MainActionButton.tsx]: What if we were to just add `{ flexShrink: 0 }` to the text with `numberOfLines` will it still truncate? This might prevent the flex layout from shrinking before render? Just spitballing.

Comment (brianacnguyen) [reply app/component-library/components-temp/MainActionButton/MainActionButton.tsx]: then numberOfLines=1 would not truncate properly in cases where it does need to truncate

Comment (brianacnguyen) [reply app/component-library/components-temp/MainActionButton/MainActionButton.tsx]: Going to try out this approach and see....

**Review by davibroc — DISMISSED** [review]
I have tested and seems the problem is resolved

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]
LGTM
