### PR TITLE
fix(snaps): Add fix for missing Snap permission labels

### LINKED ISSUE #3158: [Mobile] Fix missing permission metadata
Go through all the Snap permissions on mobile and fix the one with missing metadata.

Image

### PR DESCRIPTION
**Pull request by david0xd**
## **Description**
Add missing Snaps permission labels.

## **Related issues**
Fixes: https://github.com/MetaMask/snaps/issues/3158

## **Manual testing steps**
1. Create a Snap with all permissions specified in the manifest (example provided in this PR).
2. Verify that permission labels are displayed correctly and none is missing.

### **Before**
Screenshot 2025-05-15 at 12 03 51

### **After**
Screenshot 2025-05-09 at 16 14 51
Screenshot 2025-05-16 at 14 54 01
Screenshot 2025-05-16 at 14 52 46

### ***Snap Manifest used for testing***
```json
{
  "version": "0.1.0",
  "description": "An example Snap written in TypeScript.",
  "proposedName": "TypeScript Example Snap",
  "repository": {
    "type": "git",
    "url": "https://github.com/MetaMask/template-snap-monorepo.git"
  },
  "source": {
    "shasum": "uRfWyB6iNNrQvb/LrR6YtjlMauey+/eWjoAfbEqVqeA=",
    "location": {
      "npm": {
        "filePath": "dist/bundle.js",
        "packageName": "snap",
        "registry": "https://registry.npmjs.org/"
      }
    }
  },
  "initialPermissions": {
    "endowment:page-home": {},
    "snap_dialog": {},
    "endowment:rpc": {
      "dapps": true,
      "snaps": false
    },
    "snap_getBip32Entropy": [
      {
        "path": ["m", "44'", "0'"],
        "curve": "secp256k1"
      },
      {
        "path": ["m", "44'", "0'"],
        "curve": "ed25519"
      },
      {
        "path": ["m", "44'", "0'"],
        "curve": "ed25519Bip32"
      }
    ],
    "snap_getBip32PublicKey": [
      {
        "path": ["m", "44'", "0'"],
        "curve": "secp256k1"
      }
    ],
    "snap_getBip44Entropy": [
      {
        "coinType": 1
      },
      {
        "coinType": 3
      }
    ],
    "endowment:network-access": {},
    "snap_manageState": {},
    "endowment:name-lookup": {
      "chains": ["eip155:1"]
    },
    "snap_notify": {},
    "endowment:cronjob": {
      "jobs": [
        {
          "expression": "5 4 30 12 *",
          "request": {
            "method": "execute"
          }
        }
      ]
    },
    "endowment:ethereum-provider": {},
    "snap_getEntropy": {},
    "endowment:transaction-insight": {},
    "wallet_snap": {
      "npm:@metamask/bip32-example-snap": {
        "version": "0.34.1-flask.1"
      },
      "npm:@metamask/bip44-example-snap": {
        "version": "0.34.1-flask.1"
      }
    },
    "endowment:lifecycle-hooks": {},
    "snap_getPreferences": {},
    "endowment:protocol": {
      "scopes": {
        "solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1": {
          "methods": ["getBlockHeight", "getGenesisHash"]
        }
      }
    },
    "endowment:signature-insight": {},
    "endowment:webassembly": {}
  },
  "platformVersion": "6.22.0",
  "manifestVersion": "0.1"
}
```

## **Pre-merge author checklist**
- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**
- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/Snaps/components/SnapPermissions/SnapPermissions.tsx [hunk 1]
```diff
@@ -189,6 +191,33 @@ const SnapPermissions = ({
...
+      const title = strings(
+        `app_settings.snaps.snap_permissions.human_readable_permission_titles.${key}`,
+        { otherSnapName: snapNames },
+      );
+      walletSnapPermissionData.push({ label: title, date });
+
+      return walletSnapPermissionData;
+    },
+    [],
+  );
```
Comment (GuillaumeRx) [inline app/components/Views/Snaps/components/SnapPermissions/SnapPermissions.tsx:219]: Can we handle this as we do in extension: https://github.com/MetaMask/metamask-extension/blob/dc8cef386abb158499761bce02ced6ec3a0341b5/ui/helpers/utils/permission.js#L284-L317

**Review by GuillaumeRx — CHANGES_REQUESTED** [review]

**Review by GuillaumeRx — CHANGES_REQUESTED** [review]

**Review by GuillaumeRx — APPROVED** [review]
LGTM
