### PR TITLE
fix: prevent network selector modal from going behind IOS keyboard

### LINKED ISSUE #13781: [Bug]: [iOS specific] Network select bottom disappears while searching for a network
### Describe the bug

The network select bottom sheet disappears while I search for a network name. This is terrible UX, as it seems like our UI is buggy. 

### Expected behavior

Network search should not result in the bottom sheet disappearing

### Screenshots/Recordings

https://github.com/user-attachments/assets/daebeca0-8c7c-4cd6-9d8a-d18d4ddaf501

### Steps to reproduce

When I am on the wallet view
And I tap on the network picker
And I search for a network name
Then the network select bottom sheet disappears. 

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.41.0 (1586)

### Build type

None

### Device

iOS and Android

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

This is an IOS specific issue where the content goes behind the virtual keyboard and is hidden if it is too small.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/13781

## **Manual testing steps**

1. Go to network selector modal
2. Filter the list to 1 item (e.g. Ethereum)
3. EXPECTED - ensure that the content is still visible on an IOS device with the keyboard open.

### **After**

https://www.loom.com/share/7013a5cd960849ffaa4d3cbaf2456a17?sid=58523d20-2bfb-474d-ac45-284f572df4f1

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/NetworkSelector/NetworkSelector.tsx [hunk 1]
```diff
@@ -1020,6 +1021,14 @@ const NetworkSelector = () => {
         <KeyboardAvoidingView
           behavior={Device.isIos() ? undefined : 'height'}
           keyboardVerticalOffset={KEYBOARD_OFFSET}
+          style={{
+            borderWidth: 3,
+            borderColor: 'green',
+            // flex: 1,
```
Comment (Prithpal-Sooriya) [inline app/components/Views/NetworkSelector/NetworkSelector.tsx:1027]: Whoops, I'll get rid of this testing styles

File: app/components/Views/NetworkSelector/NetworkSelector.tsx [hunk 2]
```diff
@@ -1,4 +1,5 @@
 // Third party dependencies.
+/* eslint-disable */
```
Comment (Prithpal-Sooriya) [inline app/components/Views/NetworkSelector/NetworkSelector.tsx:2]: Get rid of this eslint disable.

File: app/components/Views/NetworkSelector/NetworkSelector.tsx [hunk 3]
```diff
@@ -188,7 +189,7 @@ const NetworkSelector = () => {
     networkName: selectedNetworkName,
   } = useNetworkInfo(origin);
 
-  const KEYBOARD_OFFSET = 120;
+  const KEYBOARD_OFFSET = 50;
```
Comment (Prithpal-Sooriya) [inline app/components/Views/NetworkSelector/NetworkSelector.tsx:192]: Double-check if this keyboard offset needed to change (this change might've snuck in while debugging)

File: app/components/Views/NetworkSelector/NetworkSelector.styles.ts [hunk 4]
```diff
@@ -159,6 +159,9 @@ const createStyles = (colors: Colors) =>
       marginTop: 4,
     },
     screen: { justifyContent: 'flex-end' },
+    keyboardView: {
+      minHeight: Device.getDeviceHeight() * 0.5,
```
Comment (Prithpal-Sooriya) [inline app/components/Views/NetworkSelector/NetworkSelector.styles.ts:163]: This feels a little magic number-y.
But enforces that the view once the keyboard is open takes up at least 50% of the screen. Thus allowing the search header to be visible.

Comment (Prithpal-Sooriya) [reply app/components/Views/NetworkSelector/NetworkSelector.styles.ts:163]: The `<KeyboardAvoidingView>` also takes other behaviours, like "padding" which pushes the view up when the keyboard is opened.

However this would require a larger refactor.

**Review by vinnyhoward — APPROVED** [review]
Love the loom videos, LGTM!
