### PR TITLE
Replace Fabric Crashlytics with Sentry

### LINKED ISSUE #1321: Migrate away from Fabric Crashlytics
The Fabric Crashlytics platform is shutting down on March 31st, as it has been replaced by/migrated to Firebase Crashlytics. We need to migrate to some other service for crash reporting (e.g. Firebase Crashlytics, Sentry, etc.)

### PR DESCRIPTION
**Pull request by Gudahtt**
* Remove Fabric and Crashlytics
* Add Sentry reporting
  Errors are reported using `captureException`, and non-errors are added as breadcrumbs. This means the non-error events won't be directly sent to Sentry, but they will be included as context for any errors that do occur.

  The sentry configuration is mainly in the `sentry.debug.properties` file. The only config outside of that file is the DSN used for reporting errors, which is hard-coded in the `setupSentry.js` module.

  There are three separate sets of config: default, debug, and release. The default config is missing the auth token, so it can't be used to publish source maps. However, builds that use the default config will still correctly report errors to the `test-metamask-mobile` Sentry project.

  The debug config is identical to the default config except that it includes the auth token. The debug config is for publishing any non-production builds (e.g. testing, pre-releases).

  The release configuration is to be used for production builds only. This is the only config that sends errors to the `metemask-mobile` Sentry project.

  The debug and release config files have not been added to the repo. They are automatically instantiated from the example files if the `MM_SENTRY_AUTH_TOKEN` environment variable is set. Setting this environment variable in CI should allow publishing from CI.

Closes #1321

### CODE REVIEW

File: android/sentry.properties [hunk 1]
```diff
@@ -0,0 +1,5 @@
+defaults.url=https://sentry.io/
+defaults.org=metamask
+defaults.project=metamask-mobile
+auth.token=f3a55b2e27454dd4aa1628a7ee7e71ae7e70ca0089e24ffeab8c5d6ae6f47369
```
Comment (Gudahtt) [inline android/sentry.properties]: This should be replaced with a new key that is added via environment file or variable.

Ideally we can leave a public key for a "test" account maybe, as we do for the extension? :man_shrugging:

File: app/util/setupSentry.js [hunk 2]
```diff
@@ -0,0 +1,20 @@
+import { init } from '@sentry/react-native';
+import { Dedupe, ExtraErrorData } from '@sentry/integrations';
+
+const METAMASK_ENVIRONMENT = process.env['METAMASK_ENVIRONMENT']; // eslint-disable-line dot-notation
+// const SENTRY_DSN = 'https://ae39e4b08d464bba9fbf121c85ccfca0@sentry.io/2299799'
+const TEST_SENTRY_DSN = 'https://1cb0be9b81554de381b65ffa80874924@sentry.io/2453959';
```
Comment (Gudahtt) [inline app/util/setupSentry.js]: Whoops, this was from my own testing with a throwaway account - I'll remove this.

File: app/util/setupSentry.js [hunk 3]
```diff
@@ -0,0 +1,20 @@
+import { init } from '@sentry/react-native';
+import { Dedupe, ExtraErrorData } from '@sentry/integrations';
+
+const METAMASK_ENVIRONMENT = process.env['METAMASK_ENVIRONMENT']; // eslint-disable-line dot-notation
```
Comment (Gudahtt) [inline app/util/setupSentry.js]: This environment isn't set anywhere yet

File: android/app/src/main/java/io/metamask/MainApplication.java [hunk 4]
```diff
@@ -50,10 +50,10 @@ public boolean getUseDeveloperSupport() {
 		protected List<ReactPackage> getPackages() {
 		return Arrays.<ReactPackage>asList(
 				new MainReactPackage(),
+            new RNSentryPackage(),
```
Comment (rickycodes) [inline android/app/src/main/java/io/metamask/MainApplication.java]: nit: seems tabbing is off here?

Comment (Gudahtt) [reply android/app/src/main/java/io/metamask/MainApplication.java]: Thanks for the reminder - I had been meaning to fix this. Some combination of the automatic linker and my brand-new environment has left a lot of the formatting in a bad state.

File: app/util/Logger.js [hunk 5]
```diff
@@ -18,14 +17,15 @@ export default class Logger {
...
-		// TODO use crashlytics opt-in
 		// Check if user passed accepted opt-in to metrics
 		const metricsOptIn = await AsyncStorage.getItem('@MetaMask:metricsOptIn');
 		if (__DEV__) {
 			args.unshift('[MetaMask DEBUG]:');
 			console.log.apply(null, args); // eslint-disable-line no-console
 		} else if (metricsOptIn === 'agreed') {
-			Fabric.Crashlytics.log(JSON.stringify(args));
+			addBreadcrumb({
+				message: JSON.stringify(args)
```
Comment (Gudahtt) [inline app/util/Logger.js]: There is a lot more useful info we could add here to the breadcrumb, but this is a good start at least. I might improve this later by changing the arguments to allow logging structured data, rather than an arbitrary array

**Comment by Gudahtt** [comment]
To test this locally, I added the line `throw new Error('TEST')` to the constructor of `app/components/Views/Root/index.js`. It should then blow up immediately when the app opens.

You can test the breadcrumbs by adding a `Logger.log` call as well, right above the error.

File: sentry.properties [hunk 6]
```diff
@@ -0,0 +1,5 @@
+defaults.url=https://sentry.io/
+defaults.org=metamask
+defaults.project=test-metamask-mobile
+auth.token=
```
Comment (danjm) [inline sentry.properties]: How does the auth token work? When is it needed?

Comment (Gudahtt) [reply sentry.properties]: It is used to publish sourcemaps, which happens as part of the release build

File: app/util/Logger.js [hunk 7]
```diff
@@ -18,14 +17,15 @@ export default class Logger {
 	 * @returns - void
 	 */
 	static async log(...args) {
-		// TODO use crashlytics opt-in
 		// Check if user passed accepted opt-in to metrics
 		const metricsOptIn = await AsyncStorage.getItem('@MetaMask:metricsOptIn');
 		if (__DEV__) {
 			args.unshift('[MetaMask DEBUG]:');
 			console.log.apply(null, args); // eslint-disable-line no-console
 		} else if (metricsOptIn === 'agreed') {
```
Comment (danjm) [inline app/util/Logger.js]: Does mobile metrics opt-in include a note about error reporting?

File: sentry.properties (hunk 6 above)
Comment (Gudahtt) [reply sentry.properties]: A similar command is in place for the extension (`sentry:publish`) which also needs a token; any submission of release artifacts requires this token.

Unfortunately with React Native, this command is integrated with the normal build process; I'm not sure how to pull it into a separate step. The modifications to the build process were done automatically when linking `@sentry/react-native`, and I wasn't eager to customize them. At least it's automatically skipped in dev mode though, so it shouldn't affect dev environments

File: app/util/Logger.js (hunk 7 above)
Comment (Gudahtt) [reply app/util/Logger.js]: Not sure. I was curious about this as well; on the extension we don't ask for permission to collect error information at all.

**Comment by danjm** [comment]
I've completed code review.

- sentry api usage seems correct, and replacement of fabric calls seem correct
- javascript code looks sound
- code related to fabric and crashlytics has been deleted
- build.sh looks fine to my not so bash trained eyes

**Review by estebanmino — APPROVED** [review]
working on IOS! 🥇
