### PR TITLE
fix: #3931 Stop loading when enabling biometrics from settings

### LINKED ISSUE #3931: iPhone: Settings > Security & Privacy > Unlock device: Forever spinning/loading screen when backing out of providing password
**Describe the bug**
Forever spinning/loading screen is displayed when backing out of providing password.

**Screenshots**
https://recordit.co/rywn6GwmMl

**To Reproduce**

- Settings > Security & Privacy
- Tap Unlock with Touch ID? or Tap Unlock with device passcode?
- On the Enter your password screen
- Tap back "<"
- Forever spinning/loading image
- Tap back again to get to Settings

**Expected behavior**
Settings & Privacy screen if user tap back "<" on Enter your password screen.

**Smartphone (please complete the following information):**
 - Device: [iPhone]
 - App Version: 4.2.2 (834)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by Cal-L**
## **Description**

The original issue is that the settings screen contains an infinite loader when navigating back after enabling biometrics. The fix is a one liner to resolve the loading state after navigating forward so that navigating backwards doesn't result in the infinite loader

## **Related issues**

Fixes: #3931 

## **Manual testing steps**

1. Go to settings tab
2. Tap on `Security & privacy`
3. With biometrics off, tap on the biometrics toggle
4. You will be navigated forward to a screen requesting your password
5. Navigate backwards
6. Without the fix, you will be on an infinite loader screen. With the fix, the infinite loader should've resolved and you should see the settings screen

### **Before**

https://github.com/user-attachments/assets/111d2ea3-390c-4775-8a2a-e44b0bb2edfe

### **After**

https://github.com/user-attachments/assets/5a382786-3b47-45d7-9607-3f47b546fc20

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx [hunk 1]
```diff
@@ -332,6 +332,7 @@ const Settings: React.FC = () => {
     if (credentials && credentials.password !== '') {
       storeCredentials(credentials.password, enabled, passwordType);
     } else {
+      setLoading(false);
```
Comment (Cal-L) [inline app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx:335]: Resolves loading on the screen before navigating

**Review by vinnyhoward — APPROVED** [review]
