### PR TITLE
fix(predict): cp-7.63.0 add transaction validation and improve error handling

### LINKED ISSUE #24804: [Bug]: Predict deposit transactions failing with 'not enough input to decode' error
## Describe the bug

Predict deposit transactions (`transaction_type == predict_deposit`) are failing with the error:

```
Invalid parameters: transaction could not be decoded: not enough input to decode
```

This error is appearing in Mixpanel for the `Transaction Finalized` event when users attempt to deposit funds into their Predict (Polymarket) wallet.

### Mixpanel Data
https://mixpanel.com/s/PApe9
- `Invalid parameters: transaction could not be decoded: not enough input to decode` error
- `failed to decode param in array[0] invalid JSON input` error
- Both errors suggest ABI encoding/decoding issues in the transaction data

### Root Cause Analysis

The error originates from the **Smart Transactions API** when it attempts to decode transaction data. The "not enough input to decode" error is thrown by ABI decoders when transaction data doesn't have enough bytes to decode expected parameters.

**Affected code path:**
- `PolymarketProvider.prepareDeposit()` in `app/components/UI/Predict/providers/polymarket/PolymarketProvider.ts`
- The deposit batch can contain up to 3 transactions:
  1. Deploy proxy wallet (`getDeployProxyWalletTransaction()`)
  2. Set allowances (`getProxyWalletAllowancesTransaction()`)
  3. Transfer/deposit (ERC20 `transfer()` via `generateTransferData()`)

**Potential issues identified:**

1. **Silent failure in sub-transaction generators**: Both `getDeployProxyWalletTransaction` and `getProxyWalletAllowancesTransaction` return `undefined` on error instead of throwing:

```typescript
// In safe/utils.ts line 362-412
export const getDeployProxyWalletTransaction = async ({ signer }) => {
  try {
    // ... transaction generation
  } catch (error) {
    // Error is logged but function returns undefined silently
    Logger.error(error as Error, errorContext);
    // No return/throw - function returns undefined
  }
};
```

2. **Validation already exists but may not cover all cases**: The code checks for undefined transactions but the batch might still be submitted with malformed data if encoding fails partially.

3. **Race condition with account state**: `getAccountState()` could return stale data affecting which transactions are included in the batch.

## Expected behavior

Predict deposit transactions should either:
1. Complete successfully with valid transaction data
2. Fail gracefully with a user-friendly error message before submission to the Smart Transactions API

## Steps to reproduce

1. Open MetaMask Mobile
2. Navigate to Predict (Polymarket integration)
3. Attempt to deposit funds to Predict wallet
4. Under certain conditions (new wallet, missing allowances, network issues), the transaction fails with the decoding error

Note: This is an intermittent issue - most deposits succeed (~5,785 confirmed vs ~1,064 failed in the same period).

## Error messages or log output

```
Invalid parameters: transaction could not be decoded: not enough input to decode
```

Related error:
```
failed to decode param in array[0] invalid JSON input
```

## Where was this bug found?

Live version (from official store)

## Proposed Fix

1. **Add explicit validation before batch submission** in `PredictController.depositWithConfirmation()`:

```typescript
// Validate all transactions have proper data before submission
const invalidTx = transactions.find(tx => !tx.params?.data || tx.params.data.length < 10);
if (invalidTx) {
  throw new Error('Invalid transaction data: one or more transactions have malformed or empty data');
}
```

2. **Make sub-transaction generators throw instead of returning undefined**:

```typescript
// In getDeployProxyWalletTransaction
} catch (error) {
  Logger.error(error as Error, errorContext);
  throw new Error(`Failed to generate deploy transaction: ${error instanceof Error ? error.message : 'Unknown error'}`);
}
```

3. **Add transaction data length logging** for debugging:

```typescript
Logger.log('Predict deposit transactions:', transactions.map(tx => ({
  type: tx.type,
  to: tx.params?.to,
  dataLength: tx.params?.data?.length ?? 0,
})));
```

### Files involved:
- `app/components/UI/Predict/providers/polymarket/PolymarketProvider.ts` (lines 1384-1479)
- `app/components/UI/Predict/providers/polymarket/safe/utils.ts` (lines 362-412, 567-586)
- `app/components/UI/Predict/controllers/PredictController.ts` (lines 1797-1911)
- `app/util/transactions/index.js` (`generateTransferData` function)

### Related Mixpanel errors for predict_deposit:
- `Relay request failed with status: fallback` (149 occurrences)
- `Transaction incomplete at startup` (31 occurrences)
- Various `insufficient funds` errors (expected user errors)

## Severity

- **Impact**: Medium - affects ~15% of predict_deposit transaction attempts
- **User visibility**: Yes - users see transaction failure
- **Scope**: Limited to Predict feature users on Polygon network

### PR DESCRIPTION
**Pull request by caieu**
## **Description**

Adds comprehensive validation for deposit transactions to prevent
silent failures causing 'not enough input to decode' errors.

Changes:
- Add transaction validation in depositWithConfirmation:
  - Verify transaction and params objects exist
  - Validate 'to' address format (0x prefix, 42 chars)
  - Validate data field exists and has valid hex format
  - Enforce minimum data length (10 chars)
- Improve error handling in polymarket safe utils:
  - Re-throw errors in getDeployProxyWalletTransaction instead of
    returning undefined
  - Add try-catch with proper error propagation in
    getProxyWalletAllowancesTransaction
  - Add call data length validation
- Update tests with valid mock addresses/data
- Add test coverage for all new validation error scenarios

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: #24804

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Strengthens transaction reliability and diagnostics around Predict deposits and Polymarket Safe flows.
> 
> - Add `validateDepositTransactions` and invoke in `depositWithConfirmation`; logs transaction summary before submission
> - Enforce checks: presence of `params`, valid `to` (0x, 42 chars), `data` existence/hex format, and minimum data length
> - Improve Safe utils: re-throw signing failures in `getDeployProxyWalletTransaction`; wrap `getProxyWalletAllowancesTransaction` in try/catch and validate call data length
> - Update tests to use valid addresses/data and add coverage for all new validation/error scenarios
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 4a9afd5be4b33a3a4a26e2bcc2456cbf237c61d7. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/Predict/controllers/PredictController.ts [hunk 1]
```diff
@@ -1873,6 +1873,141 @@ export class PredictController extends BaseController<
...
+        })),
+      });
+
+      const MIN_VALID_DATA_LENGTH = 10;
+      const VALID_ADDRESS_LENGTH = 42;
+      for (let i = 0; i < transactions.length; i++) {
+        const tx = transactions[i];
+
+        if (!tx) {
+          Logger.error(
```
Comment (matallui) [inline app/components/UI/Predict/controllers/PredictController.ts]: Should we put all this logic below in a utility function, e.g., `validateDepositTransaction`?

**Review by matallui — APPROVED** [review]
