### PR TITLE
fix: Prompt for biometric access on iOS during wallet creation - cp-7.65.0

### LINKED ISSUE #25998: [UX Regression] Biometric permission prompt no longer shown during wallet creation onboarding
## Severity

**Sev1 — High**

## Description

The MetaMask mobile app previously prompted the user to enable biometric authentication (Face ID / Touch ID / fingerprint) immediately after creating their wallet password during onboarding. In the latest build, this biometric opt-in prompt **no longer appears**.

This is a critical regression because:
- Users are not given the opportunity to enable biometrics during the most natural point in the flow (account creation).

## Steps to Reproduce

1. Install the latest MetaMask mobile app build.
2. Open the app and begin the **Create a new wallet** flow.
3. Set a wallet password and confirm it.
4. Proceed through the Secret Recovery Phrase backup steps.
5. Complete onboarding.

## Expected Behavior

After the user creates and confirms their password, the app should display a prompt asking whether they want to enable biometric authentication (e.g., "Enable Face ID?" / "Enable biometric login?"). This prompt was consistently present in prior releases.

## Actual Behavior

The biometric authentication prompt is **not shown** at any point during or after password creation. The user completes onboarding without ever being asked to enable biometrics.

## Environment

- **App:** MetaMask Mobile (latest build)
- **OS:** iOS and Android (both affected)

## Impact

- **All new users** who go through the wallet creation flow are affected.
- Users are left without biometric unlock unless they manually navigate to **Settings > Security & Privacy** and enable it themselves.
- Reduces security posture and convenience for the majority of mobile users.

## Probable Root Cause

This regression was likely introduced in PR [#24496](https://github.com/MetaMask/metamask-mobile/pull/24496) (commit [18232e8](https://github.com/MetaMask/metamask-mobile/commit/18232e88265da433cdeb02b034f7b73274a06a9d)), which refactored the Login screen to replace `userEntryAuth` and `appTriggeredAuth` with the consolidated `unlockWallet` method.

While the PR was scoped to the **Login screen**, it also made changes to shared core modules that affect the onboarding flow:

- **`SecureKeychain.ts`** (-64 lines): Removed "iOS immediate prompt logic" and "storage side-effects." Since `SecureKeychain` is shared infrastructure used by both Login and onboarding, removing the immediate biometric prompt logic likely broke the onboarding flow's ability to trigger the biometric opt-in.
- **`SecureKeychain.test.ts`** (-90 lines): Removed test coverage for the biometric prompt behavior, eliminating the safety net that would have caught this regression.
- The PR description explicitly states: *"we removed a redundant biometrics prompt when FIRST enabling biometrics toggle upon logging in"* — this was intentional for Login, but the side effect on onboarding appears **unintentional**.
- The manual testing steps in the PR only validated the Login flow; the onboarding/password-creation flow was never tested for biometric prompt behavior.

## Additional Context

- The biometric prompt during onboarding was consistently present in releases prior to this change.
- No user-facing changelog entry mentions the removal of this prompt, further suggesting it was unintentional.
- The PR's empty `CHANGELOG entry:` field indicates no user-facing behavioral changes were planned.

### PR DESCRIPTION
**Pull request by Cal-L**
## **Description**

This PR addresses a regression on 7.65.0 where biometrics access is no longer prompted on wallet creation for iOS. The change here adds that back, which should result in a more intuitive user experience + makes it consistent with Android. This is an improvement relative to the code that was removed in https://github.com/MetaMask/metamask-mobile/pull/24496 since we're now detecting the auth type prior to the password being stored rather than triggering two storage actions. 

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/25998

## **Manual testing steps**

Allowing biometrics
- Will be prompted ask for biometric access on wallet creation
- If allowed, unlock access control will be stored using biometrics
- Future unlock triggers biometrics

Rejecting biometrics
- Will be prompted ask for biometric access on wallet creation
- If rejected, unlock access control will not be stored, forcing user to use password
- Future unlock falls back to password entry

### **After**

Allowing biometrics
https://github.com/user-attachments/assets/9a05e870-b1fe-465e-ba8c-6b565198ed9e

Rejecting biometrics
https://github.com/user-attachments/assets/9ce0be47-2aaf-4ce3-bf6e-c0386559546c

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Touches authentication method selection and keychain password storage/fallback paths used during onboarding/import/reset, so mistakes could impact how users are prompted and how unlock methods are persisted; changes are well-covered by updated tests but span multiple critical flows.
> 
> **Overview**
> Restores an explicit iOS biometric prompt during wallet creation/import by introducing `Authentication.requestBiometricsAccessControlForIOS` and invoking it from `ChoosePassword` and `ImportFromSecretRecoveryPhrase`, falling back to `PASSWORD` when the user declines/cancels.
> 
> Refactors password persistence by removing `updateAuthTypeStorageFlags` and `storePasswordWithFallback`, making `Authentication.storePassword` public and adding an optional fallback-to-password retry used by `newWalletAndKeychain`/`newWalletAndRestore`/Reset Password. Updates OAuth rehydration and reset-password flows/tests accordingly, and adds/adjusts unit tests to cover iOS decline/success and fallback behavior.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 5639099ab62bb495743b8a6d205c29651affa361. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/ChoosePassword/index.tsx [hunk 1]
```diff
@@ -283,6 +283,17 @@ const ChoosePassword = () => {
   const handleWalletCreation = useCallback(
     async (authType: AuthData, previous_screen: string | undefined) => {
       if (previous_screen?.toLowerCase() === ONBOARDING.toLowerCase()) {
+
+        try {
+          // Prompt user for biometrics access control
+          Platform.OS === 'ios' && await Authentication.getPassword();
```
Comment (ieow) [inline app/components/Views/ChoosePassword/index.tsx]: I think we need to setPassword() first before calling getPassword() to get it prompted

**Review by joaoloureirop — DISMISSED** [review]

File: app/components/Views/ChoosePassword/index.tsx (hunk 1 above)
Comment (Cal-L) [reply app/components/Views/ChoosePassword/index.tsx]: Update code to use LocalAuthentication package from expo. This is better since it doesn't require us to store password prior to checking for biometric access.

File: app/core/Authentication/Authentication.ts [hunk 2]
```diff
@@ -443,31 +444,6 @@ class AuthenticationService {
     }
   };
 
-  /**
```
[the remark this answers is not in the document]
Comment (Cal-L) [reply app/core/Authentication/Authentication.ts:446]: Resolved

File: app/core/Authentication/Authentication.ts
Comment (ieow) [inline app/core/Authentication/Authentication.ts:356]: we could have a `getGenericPassword` here for Ios only and throw with `fallbackToPassword = true`  if user cancel the ios bimetric prompt

File: app/core/Authentication/Authentication.ts [hunk 3]
```diff
@@ -541,6 +522,31 @@ class AuthenticationService {
...
+          return AUTHENTICATION_TYPE.PASSWORD;
+        }
+      } catch (error) {
+        // Fallback to use password as authentication type
+        return AUTHENTICATION_TYPE.PASSWORD;
+      }
+    }
+
+    return authType;
+  };
```
[the remark this answers is not in the document]
Comment (Cal-L) [reply app/core/Authentication/Authentication.ts:549]: Resolved

File: app/core/Authentication/Authentication.ts
Comment (Cal-L) [reply app/core/Authentication/Authentication.ts:356]: Opted to use `authenticateAsync` from expo instead for iOS

**Review by ieow — APPROVED** [review]
lgtm
