### PR TITLE
fix: cp-7.53.0 swaps default slippage

### LINKED ISSUE #17881: [Bug]: Default slippage values affecting tx success
### Describe the bug

Currently, slippage for all swap/bridge transactions is set to 0.5%. This will result in transactions being dropped due to the small value.

### Expected behavior

Default slippage values should be the following for swaps/bridges:

Swap:

undefined slippage on every Solana token pair (rely on provider's dynamic slippage value)

0.5% default slippage on stablecoin pairs on EVM

2% default slippage on everything else on EVM

Bridge:

0.5% default slippage on all routes

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Go to Swaps screen
2. Open the cog icon
3. See that all swaps have 0.5% as default slippage

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.5.3

### Build type

None

### Device

iPhone 13 Pro

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by infiniteflower**
## **Description**

This PR fixes the default slippage for Swaps.

Swap:

- undefined default slippage on every Solana token pair (this is so we can use dynamic slippage from providers)
- 0.5% default slippage on stablecoin pairs on EVM
- 2% default slippage on everything else on EVM

Bridge:

- 0.5% default slippage on all routes

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: #17881

## **Manual testing steps**

1. Go to Swaps
2. Change tokens and notice slippage changing

### **After**

https://github.com/user-attachments/assets/c577f7b2-7491-4261-97dd-3c810de5411e

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Bridge/hooks/useInitialSlippage/index.ts [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+  const isSolanaSwap = useSelector(selectIsSolanaSwap);
+  const isBridge = useSelector(selectIsBridge);
+  const isEvmSwap = useSelector(selectIsEvmSwap);
+  const sourceToken = useSelector(selectSourceToken);
+  const destToken = useSelector(selectDestToken);
+
+  useEffect(() => {
+    // Solana Swaps
+    if (isSolanaSwap) {
+      dispatch(setSlippage('0.5'));
```
Comment (SteP-n-s) [inline app/components/UI/Bridge/hooks/useInitialSlippage/index.ts]: Should we add a constant here as well for consistency and not hardcode the value?

File: app/components/UI/Bridge/hooks/useInitialSlippage/index.ts [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+        );
+        return;
+      }
+      dispatch(setSlippage(AppConstants.SWAPS.DEFAULT_SLIPPAGE.toString()));
+      return;
+    }
+
+    // Bridge
+    if (isBridge) {
+      dispatch(setSlippage('0.5'));
```
Comment (SteP-n-s) [inline app/components/UI/Bridge/hooks/useInitialSlippage/index.ts]: Same here (or even use the `DEFAULT_SLIPPAGE_STABLECOINS` value).

**Review by SteP-n-s — DISMISSED** [review]

File: app/components/UI/Bridge/hooks/useInitialSlippage/index.ts (hunk 2 above)
Comment (infiniteflower) [reply app/components/UI/Bridge/hooks/useInitialSlippage/index.ts]: Done

File: app/components/UI/Bridge/hooks/useInitialSlippage/index.ts (hunk 1 above)
Comment (infiniteflower) [reply app/components/UI/Bridge/hooks/useInitialSlippage/index.ts]: Done

**Review by SteP-n-s — APPROVED** [review]

**Comment by infiniteflower** [comment]
Skipping E2E, flaky tests, the only one failing is `run_network_abstraction_swimlane_android_smoke`, NFT tests, which are unrelated to these changes
