### PR TITLE
fix: Change login in field.setValue to use optional operator

### LINKED ISSUE #12653: [Sentry] TypeError: Cannot read property 'setValue' of null
Sentry Issue: [METAMASK-MOBILE-30P0](https://metamask.sentry.io/issues/6027139969/?referrer=github_integration)

```
TypeError: Cannot read property 'setValue' of null
  at ?anon_0_ (app/components/Views/Login/index.js:422:21)
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by smilingkylan**
## **Description**

Login view attempts to reset the password input field value but sometimes the ref for the input field is `null`. Therefore, I have turned `fieldRef.setValue` to `fieldRef?.setValue`. Alternatively, since this occurs once successful navigation occurs and component is about to unmount, we may also be able to just remove the line.

## **Related issues**

Addresses this Sentry issue: https://metamask.sentry.io/share/issue/ef784f4e764a4a76bc505dcdaa52c0ec/
GitHub issue: #12653 

## **Manual testing steps**

1. You can manually set the ref to `null` in the code and login to the app. It should not trigger the catch clause right underneath it.

## **Screenshots/Recordings**

n/a but can producer if necessary

### **Before**

n/a

### **After**

https://github.com/user-attachments/assets/67579f9a-57c7-4209-85f8-78830683839f

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Cal-L — CHANGES_REQUESTED** [review]
While this prevents the crash, it doesn't solve the issue of the ref not being assigned correctly. Referencing this thread - https://consensys.slack.com/archives/C081B61CDS9/p1734459919055509?thread_ts=1734414724.387639&cid=C081B61CDS9, I suggested that we need to forward the ref to the TextInput so that the ref is propagated through. See implementation here - https://github.com/MetaMask/metamask-mobile/pull/12649/files#diff-b7bdacbc89185049ac31d9f4ede89235bf33402b7c5ea3977fc6328c11d51d06R22

File: app/components/Views/Login/index.js [hunk 1]
```diff
@@ -259,6 +259,7 @@ class Login extends PureComponent {
   });
 
   async componentDidMount() {
+    this.fieldRef.current?.focus()
```
Comment (smilingkylan) [inline app/components/Views/Login/index.js:262]: I believe this is a UX improvement since the input field is almost certainly what the user will be interacting with when arriving at the login screen

File: app/components/Views/Login/index.js [hunk 2]
```diff
@@ -419,7 +420,7 @@ class Login extends PureComponent {
         password: '',
         hasBiometricCredentials: false,
       });
-      field.setValue('');
+      field?.clear();
```
Comment (smilingkylan) [inline app/components/Views/Login/index.js:423]: `field.setValue(someValue)` was having no affect. The proper way, in this case, to set a value is `field.setNativeProps({ text: "some text value" })` (yes I tested it) or, in our case, to just use `clear()` since we are setting it to an empty string.

I learn something every day.

File: app/component-library/components/Form/TextField/foundation/Input/Input.tsx [hunk 3]
```diff
@@ -13,7 +13,7 @@ import styleSheet from './Input.styles';
 import { InputProps } from './Input.types';
 import { INPUT_TEST_ID } from './Input.constants';
 
-const Input: React.FC<InputProps> = ({
+const Input = React.forwardRef<HTMLInputElement, InputProps>(({
```
Comment (Cal-L) [inline app/component-library/components/Form/TextField/foundation/Input/Input.tsx:16]: Since this is mobile, it's not a web element type. Change this to type `TextInput`. You can reference it here https://github.com/MetaMask/metamask-mobile/pull/12649/files#diff-8df37aee24382aa4b3254dceb547f90b3e96bd7cbc150b97f61c01ebe5a45d16R16

File: app/component-library/components/Form/TextField/foundation/Input/Input.tsx [hunk 4]
```diff
@@ -67,8 +67,9 @@ const Input: React.FC<InputProps> = ({
       autoFocus={autoFocus}
       onBlur={onBlurHandler}
       onFocus={onFocusHandler}
+      ref={ref as React.RefObject<TextInput>}
```
Comment (Cal-L) [inline app/component-library/components/Form/TextField/foundation/Input/Input.tsx:70]: Remove type casting

**Review by Cal-L — COMMENTED** [review]
Left a comment

**Review by brianacnguyen — CHANGES_REQUESTED** [review]
Can you attach a video of current usage of the TextField/Input still being functional?

**Comment by smilingkylan** [comment]
> Can you attach a video of current usage of the TextField/Input still being functional?

Done

**Comment by Cal-L** [comment]
@smilingkylan Feel free to reach out once the E2E test is resolved

**Comment by smilingkylan** [comment]
Please see [this Slack thread](https://consensys.slack.com/archives/C06FXU326RL/p1737659562931419) for justification of removal of autoFocus for Login password input field

**Review by frankvonhoven — APPROVED** [review]

**Review by Cal-L — APPROVED** [review]
LGTM

**Review by brianacnguyen — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]
