### PR TITLE
fix: Fix add custom rpc detox test script

### LINKED ISSUE #8601: Fix Add Custom RPC Detox test script
Currently, the tabs Popular and Custom Network in the Add Network screen are creating issues for the detox tests. Detox is not capable to Match the element with the current implementation. Also, we have found that using the byLabel Matcher also do not work as well. This issue affects both ios and android.

### PR DESCRIPTION
**Pull request by SamuelSalas**
## **Description**

Currently, the tabs Popular and Custom Network in the Add Network screen are creating issues for the detox tests. Detox is not capable to Match the element with the current implementation. Also, we have found that using the byLabel Matcher also do not work as well. This issue affects both ios and android.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -74,7 +74,7 @@ const IGNORE_BOXLOGS_DEVELOPMENT = process.env.IGNORE_BOXLOGS_DEVELOPMENT;
 if (IGNORE_BOXLOGS_DEVELOPMENT === 'true') {
   LogBox.ignoreAllLogs();
 }
-
+LogBox.ignoreAllLogs();
```
Comment (cortisiko) [inline index.js:77]: remove this. Seems like you committed it by accident

**Review by cortisiko — CHANGES_REQUESTED** [review]
left one small comment. Link the builds in your PR description

**Review by cortisiko — APPROVED** [review]
LGTM
