### PR TITLE
fix: font rendering issues by updating font preloader to preload all custom font files

### LINKED ISSUE #15115: [Sentry] EXC_BAD_ACCESS: hash >
Sentry Issue: [METAMASK-MOBILE-3NQE](https://metamask.sentry.io/issues/6548857783/?referrer=github_integration)

```
EXC_BAD_ACCESS: hash >
Stack overflow in (null)
  ?, in -[__NSDictionaryM objectForKeyedSubscript:]
  File "EXFontLoaderProcessor.m", line 49, in -[EXFontLoaderProcessor updateFont:withFamily:size:weight:style:variant:scaleMultiplier:]
  File "EXReactFontManager.m", line 28, in +[RCTFont(EXReactFontManager) EXUpdateFont:withFamily:size:weight:style:variant:scaleMultiplier:]
  File "RCTTextAttributes.m", line 220, in -[RCTTextAttributes effectiveFont]
  File "RCTTextAttributes.m", line 150, in -[RCTTextAttributes effectiveTextAttributes]
...
(114 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by brianacnguyen**
## **Description**

This PR improves font rendering consistency across the entire app by enhancing the FontPreloader implementation to prevent font-related rendering issues.

**What is the reason for the change?**
The existing FontPreloader used a variant-based approach that maintained a manual list of TextVariant enums to preload. This approach was prone to:
- Missing newly added TextVariants, causing font loading race conditions
- Inconsistent font rendering with FOIT (Flash of Invisible Text) or FOUT (Flash of Unstyled Text)
- Maintenance overhead to keep variant lists synchronized with actual usage
- Potential layout shifts when fonts load asynchronously

**What is the improvement/solution?**
Refactored the FontPreloader to load all available font files directly instead of maintaining a variant-based list. The new approach:
- Preloads all 6 Geist font variations (Regular, Medium, Bold + Italic versions)
- Preloads all 4 MM font variations (MM Poly Regular, MM Sans Regular/Medium/Bold)
- Eliminates the need to maintain TextVariant lists that could become outdated
- Provides comprehensive font coverage that automatically supports any TextVariant
- Future-proofs the system against font rendering issues

## **Changelog**

CHANGELOG entry: Improved font rendering consistency by preloading all available font files

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15115 https://github.com/MetaMask/metamask-mobile/issues/19485 https://github.com/MetaMask/metamask-mobile/issues/20001

## **Manual testing steps**

```gherkin
Feature: Comprehensive font preloading

  Scenario: user views components with various text variants
    Given the user navigates through different app screens
    And components use different TextVariant types (DisplayLG, BodyMDBold, BodySMBold, etc.)
    
    When the user views any text content
    Then all text should render immediately with correct fonts
    And there should be no font flashing or layout shifts
    
  Scenario: user experiences consistent font rendering across platforms
    Given the FontPreloader has loaded all font files
    And the user is on web or native platform
    
    When the user interacts with any UI components containing text
    Then font rendering should be consistent and immediate
    And no fallback fonts should be visible during loading
```

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Refactors FontPreloader to preload all Geist/MM fonts across web/native, standardizes text input typography (adds fontFamily, sets lineHeight, removes fontWeight), and updates tests/snapshots accordingly.
> 
> - **Core**:
>   - **FontPreloader**: Refactor to preload all custom font families (Geist Regular/Medium/Bold + Italics; MM Poly/Sans Regular/Medium/Bold) via FontFace on web and timed warm-up on native; add `extractFontProperties`; improve logging and error handling; return consistent loading promise.
>   - **Tests**: Rewrite with platform/timeouts/DOM mocks; add coverage for concurrency, platform-specific delays, web API success/fallback paths, and error handling.
> - **UI/Typography**:
>   - **Inputs**: Standardize typography by adding `fontFamily: 'Geist Regular'` in `Views/EnterPasswordSimple`, `Views/RevealPrivateCredential`, `MultichainAccounts/PrivateKeyList`; enforce `lineHeight` and remove `fontWeight` from input styles.
>   - **Snapshots**: Update across components to reflect removed `fontWeight` and added `lineHeight`/`fontFamily`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 1652c65a2103f9c94a456288a14a1ecf4e33c2f0. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/core/FontPreloader/FontPreloader.ts [hunk 1]
```diff
@@ -74,38 +72,38 @@ class FontPreloader {
...
         document.fonts.load('500 16px "Geist Medium"'),
         document.fonts.load('700 16px "Geist Bold"'),
-      ])
+        document.fonts.load('italic 400 16px "Geist Regular Italic"'),
+        document.fonts.load('italic 500 16px "Geist Medium Italic"'),
+        document.fonts.load('italic 700 16px "Geist Bold Italic"'),
+        document.fonts.load('400 16px "MM Poly Regular"'),
+        document.fonts.load('400 16px "MM Sans Regular"'),
+        document.fonts.load('500 16px "MM Sans Medium"'),
+        document.fonts.load('700 16px "MM Sans Bold"'),
```
Comment (georgewrmarshall) [inline app/core/FontPreloader/FontPreloader.ts:130]: Should we store these strings in a const?

**Review by davibroc — DISMISSED** [review]
I tested the fix and it's looking good now

**Review by georgewrmarshall — DISMISSED** [review]
Nice work! Do we have a planned follow-up to make these changes more maintainable? Defining `fontFamily: 'Geist Regular'` for each input that isn't working doesn't seem very scalable. Is there a way to set this globally, or should we replace these inputs with design system versions instead? What are your thoughts?

**Review by georgewrmarshall — DISMISSED** [review]

**Review by davibroc — DISMISSED** [review]
LGTM

File: app/core/FontPreloader/__tests__/FontPreloader.test.ts [hunk 2]
```diff
@@ -1,12 +1,155 @@
 import FontPreloader from '../FontPreloader';
+import { Platform } from 'react-native';
```
Comment (georgewrmarshall) [inline app/core/FontPreloader/__tests__/FontPreloader.test.ts:2]: Improving testing coverage after SonarCloud test failures

### Before

Screenshot 2025-10-24 at 9 11 17 AM

Image

### After

Image

**Review by georgewrmarshall — APPROVED** [review]

**Review by gantunesr — APPROVED** [review]
Approved for Accounts CO
