### PR TITLE
fix: (cp-7.46.0) network switcher - use additional checks for non-evm networks

### LINKED ISSUE #15272: Error: Invalid character
Sentry Issue: [METAMASK-MOBILE-3R9J](https://metamask.sentry.io/issues/6596162341/?referrer=github_integration)

```
Error: Invalid character
  at ResultError (ses.cjs:7676:17)
  at isAdded (app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.tsx:60:13)
  at supportedNetworkList (app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.tsx:48:60)
  at _e.default (app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.tsx:46:68)
...
(23 additional frame(s) were not displayed)
```

Issue found on: 1827 build

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

I have not been able to replicate this [bug](https://github.com/MetaMask/metamask-mobile/issues/15272), but this is some additional checks to ensure we are correctly checking against EVM networks and ignore non-EVM networks.

We already added checks into main from https://github.com/MetaMask/metamask-mobile/pull/15184
^ However this targets `@metamask/multichain-network-controller@^0.4.0`, whereas the RC uses `0.3.0`

## **Related issues**

Fixes: #15272

## **Manual testing steps**

N/A, I still haven't figured out how to repro this.

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.tsx [hunk 1]
```diff
@@ -51,7 +51,8 @@ const CustomNetwork = ({
         ) => {
           if (
             isNonEvmChainId(networkConfiguration.chainId) ||
-            isNonEvmChainId(savedNetwork.chainId)
+            isNonEvmChainId(savedNetwork.chainId) ||
+            ('isEvm' in savedNetwork && savedNetwork.isEvm === false)
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.tsx:55]: Ensures that networks in the `MultichainNetworkController` filters out non-evm networks.

Comment (Prithpal-Sooriya) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.tsx:55]: However I'm unsure if this is the definitive fix for the sentry [bug](https://github.com/MetaMask/metamask-mobile/issues/15272)

Comment (Prithpal-Sooriya) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.tsx:55]: I'm about 80% confident that this is the issue.

If the `chainId` were undefined, we would have received:
> TypeError: undefined is not an object (evaluating 'value.toString')

If the `chainId` below was a normal number or a hex value, it would have correctly been parsed with `toHex`.

So chainId must be a string that we do not support, such as these CAIP-2 ChainIds

**Comment by Prithpal-Sooriya** [comment]
I think I'm in favour of closing this fix for this already merged fix:
https://github.com/MetaMask/metamask-mobile/pull/15184

**Review by NicolasMassart — CHANGES_REQUESTED** [review]
Can we have a unit test for CustomNetwork please?
I know there's no test file already, but adding one could be a good way to make sure we deal with all the cases.

**Comment by Prithpal-Sooriya** [comment]
Yep @NicolasMassart, attempting to add a test helped me uncover the [root issue which was fixed here](https://github.com/MetaMask/metamask-mobile/pull/15184).

This PR may be closed in favour of the root fix in main.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.tsx (hunk 1 above)
Comment (Prithpal-Sooriya) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.tsx:55]: However the state is weird.
The `MultichainNetworkController` only adds the testnet state in `@metamask/multichain-network-controller@0.4.0`, however the RC uses `0.3.0`. So still confused on how we got this weird state with testnets.

**Comment by Prithpal-Sooriya** [comment]
@NicolasMassart tests added.

This technically is already fixed in `main` through https://github.com/MetaMask/metamask-mobile/pull/15184.
This is just some additional checks for 7.46.0.

**Review by gambinish — DISMISSED** [review]

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.test.tsx [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+        chainId: '0x1',
+        nickname: 'Ethereum Mainnet',
+        rpcUrl: 'https://mainnet.infura.io/v3/your-api-key',
+        ticker: 'ETH',
+        rpcPrefs: {
+          blockExplorerUrl: 'https://etherscan.io',
+        },
+      },
+      showNetworkModal: mockShowNetworkModal,
+      shouldNetworkSwitchPopToWallet: false,
```
Comment (NicolasMassart) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.test.tsx:38]: S: have showAddedNetworks defined in mock with other props, for readability.
**Suggestion part 1/2**

```suggestion
      shouldNetworkSwitchPopToWallet: false,
      showAddedNetworks: true,
```

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.test.tsx [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+    };
+    return mockCustomNetworkProps;
+  };
+
+  it('filters out CAIP-2 networks', () => {
+    const props = getMockCustomNetworkProps();
+    const mockState = getMockState();
+    const { getByText, queryByText } = renderWithProvider(
+      <CustomNetwork {...props} showAddedNetworks />,
```
Comment (NicolasMassart) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.test.tsx:47]: S: have showAddedNetworks defined in mock with other props, for readability.
**Suggestion part 2/2**
```suggestion
      <CustomNetwork {...props} />,
```

Comment (Prithpal-Sooriya) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.test.tsx:47]: Using a different approach in the [above comment](https://github.com/MetaMask/metamask-mobile/pull/15283/files/8f9dadbcab7a4fe316c6c03e68babbb3eac314ec#r2088595338).

Using `<CustomNetwork {...props} />` by adding the `showAddedNetworks` to default props makes the test less readable and more confusing (it is hard to see why these set of props are important).

Instead we will specify the props used to trigger the test.
```ts
const props = getMockCustomNetworkProps({ showAddedNetworks: true })
const {} = render(<CustomNetwork {...props} />)
```

Comment (Prithpal-Sooriya) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.test.tsx:47]: Hmm I'll also update the test name, to indicate that showAddedNetworks are important to show the added networks in the component we are testing.

Comment (Prithpal-Sooriya) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.test.tsx]: Fixed in https://github.com/MetaMask/metamask-mobile/pull/15283/commits/3a84fb35a75f6d60978e5fd1651ddfdae77a2898

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.test.tsx (hunk 2 above)
Comment (Prithpal-Sooriya) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/CustomNetworkView/CustomNetwork.test.tsx:40]: Fixed in https://github.com/MetaMask/metamask-mobile/pull/15283/commits/3a84fb35a75f6d60978e5fd1651ddfdae77a2898

**Review by NicolasMassart — APPROVED** [review]
Looks good to me!

**Comment by NicolasMassart** [comment]
I added the `no-qa-needed` as [e2e tests passed initially](https://github.com/MetaMask/metamask-mobile/pull/15283#issuecomment-2873033354) but started failing after update with main, the e2e are the cause, not the code in this PR. The changes after the passing e2e are only unit tests.

**Review by NidhiKJha — APPROVED** [review]
