### PR TITLE
PPOM - Signature Metric events have the `flagged_as_malicious` and Blockaid info when using a different network than Mainnet

### LINKED ISSUE #8065: [Bug]: PPOM - Signature Metric events have the `flagged_as_malicious` and Blockaid info when using a different network than Mainnet
### Describe the bug

**Problem:** whenever I am on a different network than Mainnet (i.e. Sepolia) if I perform signatures from the test dapp I can see how the metrics information for that event displays PPOM information (i.e. flagged as malicious, reason, RPC counts, etc).

```
Analytics 'trackEventWithParameters' - {"category": "Signature Rejected"} {"account_type": "MetaMask", "chain_id": "11155111", "dapp_host_name": "metamask.github.io", "ppom_debug_traceCall_count": 1, "ppom_eth_call_count": 12, "ppom_eth_getBalance_count": 1, "ppom_eth_getBlockByNumber_count": 1, "request_platform": undefined, "request_source": "In-App-Browser", "security_alert_reason": "seaport_farming", "security_alert_response": "Malicious", "signature_type": "eth_signTypedData_v4", "ui_customizations": ["flagged_as_malicious"], "version": "V4"}
```

### Expected behavior

For not supported networks, we should see the same as we see in Extension:

```
    security_alert_reason: 'NotApplicable',
    security_alert_response: 'NotApplicable',
```
and no RPC counts

Screenshot from 2023-12-11 11-53-24

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/ac0acb8f-4b08-4a48-b546-746642b9e047

### Steps to reproduce

1. Enable Blockaid
2. Select Sepolia network
3. Go to test dapp
4. Trigger any signature
5. Reject/Accept the signature
6. See log metrics events, with Blockaid information (flagged as malicious,etc)

### Error messages or log output

_No response_

### Version

7.14.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by segun**
## **Description**
Whenever I am on a different network than Mainnet (i.e. Sepolia) if I perform signatures from the test dapp I can see how the metrics information for that event displays PPOM information (i.e. flagged as malicious, reason, RPC counts, etc).

Analytics 'trackEventWithParameters' - {"category": "Signature Rejected"} {"account_type": "MetaMask", "chain_id": "11155111", "dapp_host_name": "metamask.github.io", "ppom_debug_traceCall_count": 1, "ppom_eth_call_count": 12, "ppom_eth_getBalance_count": 1, "ppom_eth_getBlockByNumber_count": 1, "request_platform": undefined, "request_source": "In-App-Browser", "security_alert_reason": "seaport_farming", "security_alert_response": "Malicious", "signature_type": "eth_signTypedData_v4", "ui_customizations": ["flagged_as_malicious"], "version": "V4"}
Expected behavior

For not supported networks, we should see the same as we see in Extension:

    security_alert_reason: 'NotApplicable',
    security_alert_response: 'NotApplicable',
and no RPC counts

The direction taken in this solution is to create a supported networks list (with only mainnet for now) and check if the current chainId is in supported networks. 

I think this will make multichain support easier to add/implement when we are ready to go to multichain

## **Related issues**

Fixes: #8065 

## **Manual testing steps**

1. Launch MM
2. Make sure `yarn watch` is running
3. Open testdapp and switch to any network other than mainnet
4. Do a PPOM signature request from testdapp
5. Cancel it
6. Open Terminal running `yarn watch` and see that PPOM security alert metrics are sent
7. Checkout this branch
8. Repeat Steps 2-6, but noticed `NotApplicable` are now sent in metrics now.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/blockaid/index.ts [hunk 1]
```diff
@@ -33,6 +61,9 @@ export const getBlockaidMetricsParams = (
         additionalParams[metricKey] = providerRequestsCount[key];
       });
     }
+  } else {
+    additionalParams.security_alert_response = 'NotApplicable';
+    additionalParams.security_alert_reason = 'NotApplicable';
   }
```
Comment (jpuri) [inline app/util/blockaid/index.ts:67]: I think we can get rid of blockaid params altogether is network does not supports blockaid.

File: app/util/blockaid/index.ts [hunk 2]
```diff
@@ -2,10 +2,39 @@ import {
...
+
+export const isSupportedChainId = (chainId: string) => {
+  /**
+   * Quite a number of our test cases return undefined as chainId from state.
+   * In such cases, the tests don't really care about the chainId.
+   * So, this treats undefined chainId as mainnet for now.
+   * */
+  if (chainId === undefined) {
+    return true;
+  }
```
Comment (jpuri) [inline app/util/blockaid/index.ts:22]: This logic added for test cases does not seems good.

File: app/util/blockaid/index.ts [hunk 3]
```diff
@@ -2,10 +2,39 @@ import {
...
 
 // eslint-disable-next-line import/prefer-default-export
-export const isBlockaidFeatureEnabled = () =>
-  process.env.MM_BLOCKAID_UI_ENABLED === 'true';
+export const isBlockaidFeatureEnabled = () => {
+  const chainId = selectChainId(store.getState());
+  return (
+    process.env.MM_BLOCKAID_UI_ENABLED === 'true' && isSupportedChainId(chainId)
+  );
+};
```
Comment (jpuri) [inline app/util/blockaid/index.ts:37]: In future this condition will go away `process.env.MM_BLOCKAID_UI_ENABLED === 'true'`. We need to have clarity exactly where and how this check is used and we want to add this new condition to all those places.

File: app/util/blockaid/index.ts (hunk 2 above)
Comment (segun) [reply app/util/blockaid/index.ts:22]: The alternative is to edit all the test cases that are failing if we remove the condition. We can maybe do that in a separate PR.

File: app/util/blockaid/index.ts (hunk 3 above)
Comment (segun) [reply app/util/blockaid/index.ts:37]: We use the function `isBlockaidFeatureEnabled` everywhere we need to  do this check, so when we want to remove the condition in future, we only have to do it here.

File: app/util/blockaid/index.ts (hunk 2 above)
Comment (jpuri) [reply app/util/blockaid/index.ts:22]: I would prefer fixing test cases instead of this change, but I leave it to you if you prefer to do it in separate PR.

**Review by jpuri — APPROVED** [review]

File: app/util/blockaid/index.ts (hunk 2 above)
Comment (segun) [reply app/util/blockaid/index.ts:22]: It's a number of test cases and I don't want to end up with a huge PR :( I'll rather do it in another PR.

Comment (segun) [reply app/util/blockaid/index.ts:22]: I created [this issue](https://github.com/MetaMask/metamask-mobile/issues/8367)

**Review by jpuri — APPROVED** [review]

File: app/util/blockaid/index.ts [hunk 4]
```diff
@@ -2,10 +2,39 @@ import {
   ResultType,
   SecurityAlertResponse,
 } from '../../components/UI/BlockaidBanner/BlockaidBanner.types';
+import { getDecimalChainId } from '../networks';
+import { store } from '../../store';
+import { selectChainId } from '../../selectors/networkController';
+import { NETWORKS_CHAIN_ID } from '../../constants/network';
+
+export const SUPPORTED_CHAIN_IDS: string[] = [
```
Comment (blackdevelopa) [inline app/util/blockaid/index.ts:10]: Can we move this to `../util`

**Review by blackdevelopa — APPROVED** [review]

File: app/util/blockaid/index.test.ts [hunk 5]
```diff
@@ -4,14 +4,33 @@ import {
...
+  });
+
+  it('returns enpty object when chain id is not in supported chain ids list', () => {
+    jest.spyOn(NetworkControllerMock, 'selectChainId').mockReturnValue('10');
     const result = getBlockaidMetricsParams(undefined);
     expect(result).toStrictEqual({});
   });
 
-  it('should return additionalParams object when securityAlertResponse defined', () => {
+  it('should return additionalParams object when securityAlertResponse is defined', () => {
```
Comment (digiwand) [inline app/util/blockaid/index.test.ts:33]:
```suggestion
  it('returns additionalParams object when securityAlertResponse is defined', () => {
```

**Review by digiwand — APPROVED** [review]

File: app/util/blockaid/index.ts (hunk 4 above)
Comment (segun) [reply app/util/blockaid/index.ts:10]: Let's do it in your PR that adds multichain support.
