### PR TITLE
fix: cp-7.42.0 fix history transactions loading

### LINKED ISSUE #9727: [Bug]:  The 'Transaction details' screen closes on its own, sometimes not providing users with sufficient time to interact with it.
### Describe the bug

'Transaction details' screen closes by itself, sometimes it says open only for a second.

### Expected behavior

Users should have a comfortable timeframe to review and engage with their transaction details.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/104780023/39f69ce6-10fe-4c2b-883e-767e28f09449

### Steps to reproduce

1. Have a transaction in any status within the Activity tab
2. Click on the transaction
3. Notice that 'Transaction details' screen may close within 1-2 seconds making it impossible to interact with it

### Error messages or log output

_No response_

### Version

7.22.0(1325)

### Build type

None

### Device

Samsung S24+

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #13936: [Bug]: Activity list and token details are blank after clicking multiple times on the transaction details
### Describe the bug

When clicking multiple times on any transaction details from the activity list, the transaction list and the token details screen go blank. 

This happens until the app is closed and reopen again.

The issue is present on all versions available in TestFlight, until version v7.37.1

### Expected behavior

Activity list and token details not to be blank

### Screenshots/Recordings

V7.42.0:

[Loom Video](https://www.loom.com/share/4a9655ded1a545638df5408237ee066b?sid=fbee72d4-2189-4d7c-93d9-3d6ebe2a2388)

v7.37.1:

https://github.com/user-attachments/assets/9fdfa932-233e-4e10-9d86-21bf562b63a3

### Steps to reproduce

1. Have transactions on any network
2. Click on the Activity List
3. Click on any transaction 
4. Click multiple times inside the transaction details screen
5. Notice the activity list crashed and goes blank
6. Click on any token 
7. Notice the token details are also blank
8. Close the app and re-open it
9. Notice the activity list and token details are loading again

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.42.0

### Build type

None

### Device

iphone 15, Pixel 6 Pro

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

When clicking multiple times on any transaction details from the activity list, the transaction list and the token details screen go blank.

This happens until the app is closed and reopen again.

## **Related issues**

Fixes: #13936 #9727

## **Manual testing steps**

1. Have transactions on any network
2. Click on the Activity List
3. Click on any transaction
4. Click multiple times inside the transaction details screen
5. Notice the activity list crashed and goes blank
6. Click on any token
7. Notice the token details are also blank
8. Close the app and re-open it
9. Notice the activity list and token details are loading again

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/TransactionsView/index.js [hunk 1]
```diff
@@ -155,8 +153,14 @@ const TransactionsView = ({
     so the effect will not be noticeable if the user is in this screen.
     */
     InteractionManager.runAfterInteractions(() => {
-      const { networkId } = store.getState().inpageProvider;
-      filterTransactions(networkId);
+      const state = store.getState();
+      const networkId =
+        state?.engine?.backgroundState?.NetworkController
+          ?.selectedNetworkClientId;
```
[the remark this answers is not in the document]
Comment (Prithpal-Sooriya) [reply app/components/Views/TransactionsView/index.js:159]: Understandable since this is an old component that uses mapStateToProps instead of useSelector.

File: app/components/Views/confirmations/Approval/index.test.tsx
Comment (Prithpal-Sooriya) [inline app/components/Views/confirmations/Approval/index.test.tsx:1]: nit - did we need to include these test changes? It seems like formatting changes.

File: app/selectors/transactionController.test.ts [hunk 2]
```diff
@@ -1,10 +1,195 @@
...
+          },
+        },
+      } as unknown as RootState;
+      expect(
+        selectTransactionMetadataById(state, 'non-existent'),
+      ).toBeUndefined();
+    });
+  });
+
+  describe('selectSortedTransactions', () => {
```
Comment (Prithpal-Sooriya) [inline app/selectors/transactionController.test.ts:135]: nit - can we add a selector equality test?

**Review by Prithpal-Sooriya — APPROVED** [review]

File: app/components/Views/confirmations/Approval/index.test.tsx
Comment (salimtb) [reply app/components/Views/confirmations/Approval/index.test.tsx:1]: yes to fix the unit test , this was needed.
this PR address two problems , first one is the loading reported by the QA , and second one is , when you open the history it's keep rerendering , and this is why i created a deepEqual selector

**Review by MarioAslau — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Comment by Unik0rnMaggie** [comment]
The fix works for Android, using the build from [here](https://app.bitrise.io/build/6577bf35-bf4e-480d-894e-3d344356fdb0?tab=artifacts) 


https://github.com/user-attachments/assets/32bce948-f34a-4456-9572-076a6d4e8f74
