### PR TITLE
fix: fix send flow on token detail page

### LINKED ISSUE #13224: [Bug]: Cannot process send from token detail view
### Describe the bug

use cannot process send using the token detail view for any token

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/c127f90c-c1c4-41c8-a984-b13833bffaf2

### Steps to reproduce

1. Go to token Detail page
2. try to send any token ( BNB for instance )
3. you will get insufficient funds error 

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.38

### Build type

None

### Device

iphone 13

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Related issues**

Fixes: #13224 
 
## **Manual testing steps**

1. Go to token detail page
2. Process send

### **After**

https://github.com/user-attachments/assets/ff1b4c9f-3d00-439e-acc6-c43fa8bd7a5b

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/confirmations/SendFlow/Confirm/index.js [hunk 1]
```diff
@@ -743,7 +743,8 @@ class Confirm extends PureComponent {
 
     let transactionValue, transactionValueFiat;
     const valueBN = hexToBN(value);
-    const parsedTicker = getTicker(ticker);
+    const symbol = ticker ?? selectedAsset?.symbol;
```
Comment (Prithpal-Sooriya) [inline app/components/Views/confirmations/SendFlow/Confirm/index.js:746]: Comment - Could you explain this change? It'll be a good knowledge share here.

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by gambinish — APPROVED** [review]

**Review by sethkfman — APPROVED** [review]
LGTM

**Review by matthewwalsh0 — APPROVED** [review]
