### PR TITLE
fix: Design QA Bugs 4 cp-7.52.0

### LINKED ISSUE #17011: [Bug]: After creating the password, it navigated to Welcome screen
### Describe the bug

After creating the password, it navigated to Welcome screen

### Expected behavior

It should go to MetaMetric screen

### Screenshots/Recordings

https://github.com/user-attachments/assets/6cb4193f-222a-4f47-93e9-6ab90b72356f

### Steps to reproduce

1. Onboarding with social login
2. Creating password

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

7.50.0

### Build type

Beta

### Device

Honor Play

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #17012: [Bug]: Should show "Wallet already exists" screen if social account is linked
### Describe the bug

After creating new wallet with the GG account, tried to create new wallet with same GG account and it still went to Create password screen, should go to "Wallet already exists" screen

### Expected behavior

Should show "Wallet already exists" screen

### Screenshots/Recordings

https://github.com/user-attachments/assets/25992ca6-04b2-4083-97ad-33b5cc26b09a

### Steps to reproduce

1. Finish the onboarding flow
2. Reset the wallet
3. Create new wallet again with same GG account

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

7.50.0

### Build type

Beta

### Device

Honor Play

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #17013: [Bug]: Should not show the scrolling at "Wallet already exists" screen
### Describe the bug

Should not show the scrolling at "Wallet already exists" screen

### Expected behavior

Should not have the scroll bar

**suggestion**:
image

### Screenshots/Recordings

https://github.com/user-attachments/assets/ad708df3-102a-48b0-a945-7b821d15f74f

### Steps to reproduce

1. Create wallet with GG account which linked to wallet

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

7.50.0

### Build type

Beta

### Device

Honor Play

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by smgv**
## **Description**
- UI Design Bug Fixes
- Bug 1: https://www.notion.so/metamask-consensys/Copy-is-wrong-for-password-for-social-login-22df86d67d68809c9b43d7d89b0f6be2?source=copy_link
- Bug 2: https://www.notion.so/metamask-consensys/Apple-icon-should-be-white-in-dark-mode-233f86d67d68803b83bfe4ebb7cc62d7?source=copy_link
- Bug 3: https://www.notion.so/metamask-consensys/Copy-on-main-screen-is-wrong-for-SRP-233f86d67d68804c86c1dccf3da94202?source=copy_link
- Bug 4: https://www.notion.so/metamask-consensys/When-clicking-on-unlock-a-few-times-it-seems-to-be-glitching-upwards-after-a-few-times-233f86d67d6880f2afc3c304d2cae9a4?source=copy_link
- Bug 5: https://www.notion.so/metamask-consensys/Link-text-copy-is-wrong-on-rehydration-233f86d67d6880829efadab2b11a98df?source=copy_link
- Bug 6: https://www.notion.so/metamask-consensys/Can-we-shift-fox-closer-to-the-center-of-the-screen-233f86d67d68807fbc65d9f68f709e12?source=copy_link
- Bug 7: https://www.notion.so/metamask-consensys/Change-section-color-233f86d67d688029936efeeb582c12ce?v=211f86d67d68803c88d7000cfcf4f021&source=copy_link
- Bug 8: Account Status PaddingTop 
- Bug 9: https://www.notion.so/metamask-consensys/211f86d67d688014b7a6cc068367e4c5?v=211f86d67d68803c88d7000cfcf4f021&p=237f86d67d68804cbdede7df8a6f8486&pm=s
- Bug 10: ResetPassword UI based on Authconnection.

Revalidate below GitHub issues (@LeVinhGithub ):
- https://github.com/MetaMask/metamask-mobile/issues/17013
- https://github.com/MetaMask/metamask-mobile/issues/17012
- https://github.com/MetaMask/metamask-mobile/issues/17011

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

### **Before**

- Bug 1: https://www.notion.so/metamask-consensys/Copy-is-wrong-for-password-for-social-login-22df86d67d68809c9b43d7d89b0f6be2?source=copy_link
- Bug 2: https://www.notion.so/metamask-consensys/Apple-icon-should-be-white-in-dark-mode-233f86d67d68803b83bfe4ebb7cc62d7?source=copy_link
- Bug 3: https://www.notion.so/metamask-consensys/Copy-on-main-screen-is-wrong-for-SRP-233f86d67d68804c86c1dccf3da94202?source=copy_link
- Bug 4: https://www.notion.so/metamask-consensys/When-clicking-on-unlock-a-few-times-it-seems-to-be-glitching-upwards-after-a-few-times-233f86d67d6880f2afc3c304d2cae9a4?source=copy_link
- Bug 5: https://www.notion.so/metamask-consensys/Link-text-copy-is-wrong-on-rehydration-233f86d67d6880829efadab2b11a98df?source=copy_link
- Bug 6: https://www.notion.so/metamask-consensys/Can-we-shift-fox-closer-to-the-center-of-the-screen-233f86d67d68807fbc65d9f68f709e12?source=copy_link

### **After**

https://github.com/user-attachments/assets/3fd721e0-3c5d-4341-9146-564a69f7b965

https://github.com/user-attachments/assets/fd1fb309-26f0-4888-bffc-e70bb2ac0d00

https://github.com/user-attachments/assets/6e2faac6-2501-4acc-b515-d428f6c0a08e

Screenshot 2025-07-17 at 8 49 13 PM
Screenshot 2025-07-17 at 8 49 24 PM
Screenshot 2025-07-17 at 8 55 47 PM
Screenshot 2025-07-17 at 8 55 59 PM
Screenshot 2025-07-17 at 9 13 41 PM
Screenshot 2025-07-17 at 10 12 26 PM
Screenshot 2025-07-18 at 10 30 39 AM
Screenshot 2025-07-18 at 1 03 55 PM
Screenshot 2025-07-18 at 1 06 13 PM
Screenshot 2025-07-18 at 1 06 26 PM
Simulator Screenshot - iPhone 16 Pro - 2025-07-21 at 18 36 14
Simulator Screenshot - iPhone 16 Pro - 2025-07-21 at 18 43 32
Simulator Screenshot - iPhone 16 Pro - 2025-07-21 at 18 45 47
Simulator Screenshot - iPhone 16 Pro - 2025-07-21 at 19 04 56

Revalidate Issues:

Issuse 1 & 2:

Screenshot 2025-07-21 at 3 38 52 PM

https://github.com/user-attachments/assets/b19b81ef-8f12-4131-bc87-6638fde3f992

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by hieu-w — DISMISSED** [review]
lgtm

**Comment by LeVinhGithub** [comment]
With the issue in build for social login, I can only check Bug 4,6,7
They're passed now.
cc @smgv

File: app/core/OAuthService/OAuthLoginHandlers/constants.ts [hunk 1]
```diff
@@ -31,6 +31,8 @@ const buildTypeMapping = (buildType: string, isDev: boolean) => {
   const IS_QA = process.env.METAMASK_ENVIRONMENT === 'qa';
 
   switch (buildType) {
+    case 'QA':
```
Comment (chaitanyapotti) [inline app/core/OAuthService/OAuthLoginHandlers/constants.ts]: undo this pls

**Comment by LeVinhGithub** [comment]
lgtm

File: app/core/OAuthService/OAuthLoginHandlers/constants.ts (hunk 1 above)
Comment (smgv) [reply app/core/OAuthService/OAuthLoginHandlers/constants.ts]: PR updated

**Review by chaitanyapotti — APPROVED** [review]
