### PR TITLE
fix: blockaid banner should not break if feature is an object

### LINKED ISSUE #7819: [Bug]: PPOM - `Objects are not valid as React child` if PPOM returns a response with an object
### Describe the bug

**Problem:** if ppom passes an object on one of the features field, MetaMask breaks.

### Expected behavior

We cannot assume the types returned by ppom in the validation response, as it's a blackbox, so we should validate the response and types accordingly.

### Screenshots/Recordings

Screenshot from 2023-11-15 12-28-17

https://github.com/MetaMask/metamask-mobile/assets/54408225/631be145-34b0-4065-a5be-404b983f7c9a

### Steps to reproduce

1. Change the ppom response on the `ppom-utils.js` file

```
securityAlertResponse = {
        "result_type": "Malicious",
        "reason": "test",
        "features": [
          {"slkjd": "sjdfsa", "ksdf": "skhdjfska"},
          "blablabla",
          "blablabla",
        ]
    }
```
3. Go to test dapp
4. Trigger any tx
5. Click Details on the blockaid banner

### Error messages or log output

_No response_

### Version

main (with blockaid feature flag on)

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**
Blockaid banner should not throw error if feature is an object.

## **Related issues**

Fixes: #7819

## **Manual testing steps**
1. Change the ppom response on the ppom-utils.js file
securityAlertResponse = {
        "result_type": "Malicious",
        "reason": "test",
        "features": [
          {"slkjd": "sjdfsa", "ksdf": "skhdjfska"},
          "blablabla",
          "blablabla",
        ]
    }
2. Go to test dapp
3. Trigger any tx
4. Click Details on the blockaid banner

## **Screenshots/Recordings**
NA

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've clearly explained what problem this PR is solving and how it is solved.
- [X] I've linked related issues
- [X] I've included manual testing steps
- [X] I've included screenshots/recordings if applicable
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [X] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by jpuri** [comment]
Bitrise: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/1590f43c-fdd4-46e0-98ff-8e665bf11ef4

**Review by blackdevelopa — DISMISSED** [review]

File: app/components/UI/BlockaidBanner/BlockaidBanner.tsx [hunk 1]
```diff
@@ -166,7 +166,7 @@ const BlockaidBanner = (bannerProps: BlockaidBannerProps) => {
         <View style={styles.details}>
           {features?.map((feature, i) => (
             <Text key={`feature-${i}`} style={styles.detailsItem}>
-              • {feature}
+              • {JSON.stringify(feature)}
```
Comment (cryptotavares) [inline app/components/UI/BlockaidBanner/BlockaidBanner.tsx:169]: Why do we need to JSON.stringify when according to the types `features` is an array of strings?

Should we at least update the BlockaidBanner types?

Comment (jpuri) [reply app/components/UI/BlockaidBanner/BlockaidBanner.tsx:169]: Features as I know are still not supported with blockaid, thus I found extension is also not handling features being object.

It will be anyways good to fix this and also fix types. Let me do that.

**Review by blackdevelopa — APPROVED** [review]

**Review by cryptotavares — APPROVED** [review]
