### PR TITLE
fix: for from address balance shown for ERC20 transfers

### LINKED ISSUE #6218: [Bug] ERC20 Token Balance is pointing to the incorrect Account
**Describe the bug**
Whenever we are sending an ERC20 token from a Dapp, the `Balance` field we display is pointing to the Selected Account on the Wallet view, but not to the Selected Account which is performing the transaction.

**Screenshots**

https://user-images.githubusercontent.com/54408225/233124416-019420b1-a395-442e-9a69-0be59f3ad6fa.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the https://metamask.github.io/test-dapp/
2. Connect MM Account 2
3. Go to the Wallet, Select MM Account 1
4. Go back to the test dapp
5. Deploy an ERC20 Token Contract
6. Click Transfer
7. See how the Account 2 `Balance` amount is 0 (incorrect)
8. Go back to the Wallet
9. Switch to Account 2
10. Go back to test dapp
11. Click Transfer
12. See how the Account 2 `Balance` amount is 10 (correct)

**Expected behavior**
Balance displayed should indicate the balance from the Account which is displayed and performing the transaction.

**Smartphone (please complete the following information):**
 - Device: Pixel
 - OS: Android
 - App Version: `v6.3.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by jpuri**
Fixes: #6218 

If DAPP is connected to address different from selected address, ERC20 token balance is wrong.

QA Steps:
- Transfer ERC20 from DAPP, ensure that account connected to DAPP is different from selected account in metamask. The ERC20 token balance should be correct.
- Transfer ERC20 from DAPP, ensure that account connected to DAPP is different from selected account in metamask. Ensure that connected account does not have sufficient balance of ERC20 token. There should be a warning on the page that for insufficient funds.

### CODE REVIEW

File: app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx [hunk 1]
```diff
@@ -148,22 +150,40 @@ const AccountFromToInfoCard = (props: AccountFromToInfoCardProps) => {
...
+            );
+            fromAccBalance = `${renderFromTokenMinimalUnit(
+              fromAccBalance || '0',
+              decimals,
+            )} ${symbol}`;
+            setFromAccountBalance(fromAccBalance);
+          } catch (exp) {
+            console.error(`Error in trying to fetch token balance - ${exp}`);
+          }
+        })();
```
Comment (jpuri) [inline app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx:175]: `contractBalances` has balance for selected address only, thus if from address is not same as selected address we get balance from `AssetsContractController`.

File: app/util/dappTransactions/index.ts [hunk 2]
```diff
@@ -143,13 +144,13 @@ export const validateTokenAmount = async (
...
       contractBalanceForAddress = hexToBN(
         contractBalances[selectedAsset.address].toString(),
       );
     } else {
-      const { AssetsContractController }: any = Engine.context;
       try {
+        const { AssetsContractController }: any = Engine.context;
         contractBalanceForAddress =
           await AssetsContractController.getERC20BalanceOf(
             selectedAsset.address,
```
Comment (jpuri) [inline app/util/dappTransactions/index.ts:156]: Code above performs validation to show error message for insufficient funds. It should call `AssetsContractController` to get balance if selected address if not same as from address in the transaction.

File: app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx [hunk 3]
```diff
@@ -148,22 +150,40 @@ const AccountFromToInfoCard = (props: AccountFromToInfoCardProps) => {
...
+              address,
+              fromAddress,
+            );
+            fromAccBalance = `${renderFromTokenMinimalUnit(
+              fromAccBalance || '0',
+              decimals,
+            )} ${symbol}`;
+            setFromAccountBalance(fromAccBalance);
+          } catch (exp) {
+            console.error(`Error in trying to fetch token balance - ${exp}`);
```
Comment (blackdevelopa) [inline app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx:173]: For this, can we use Logger in utils file? Should work

**Review by blackdevelopa — DISMISSED** [review]

File: app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.test.tsx [hunk 4]
```diff
@@ -147,4 +166,59 @@ describe('AccountFromToInfoCard', () => {
...
+    };
+    let mockGetERC20BalanceOf: any;
+    beforeEach(() => {
+      mockGetERC20BalanceOf = jest.fn().mockReturnValue(0x0186a0);
+      Engine.context.AssetsContractController = {
+        getERC20BalanceOf: mockGetERC20BalanceOf,
+      };
+    });
+
+    it('should render balance from AssetsContractController.getERC20BalanceOf if selectedAddress is different from fromAddress', async () => {
```
Comment (digiwand) [inline app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.test.tsx:198]:
```suggestion
    it('should render balance from AssetsContractController.getERC20BalanceOf if selectedAddress is different from fromAddress', () => {
```

no need for async for these tests

File: app/util/dappTransactions/index.test.ts [hunk 5]
```diff
@@ -77,10 +83,44 @@ describe('Dapp Transactions utils :: validateTokenAmount', () => {
         TEST_GAS,
         TEST_FROM,
         TEST_SELECTED_ASSET,
+        TEST_SELECTED_ADDRESS,
         TEST_CONTRACT_BALANCES,
       ),
     ).toBeUndefined();
   });
+
+  it('should check value from contractBalances is selectedAddress is equal to from', async () => {
```
Comment (digiwand) [inline app/util/dappTransactions/index.test.ts:92]:
```suggestion
  it('should check value from contractBalances if selectedAddress is from address', async () => {
```
I'm not sure how this checks the value from `contractBalances` since we check the value is equal to undefined. Should we mock a value and check that it is checked here?

File: app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx (hunk 1 above)
Comment (jpuri) [reply app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx:175]: Done

File: app/util/dappTransactions/index.test.ts (hunk 5 above)
Comment (jpuri) [reply app/util/dappTransactions/index.test.ts]: @digiwand : if validate returns undefined that implies that there is no error in value selected

File: app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx (hunk 1 above)
Comment (digiwand) [reply app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx:180]: very helpful. thank you!

**Review by digiwand — DISMISSED** [review]

**Review by digiwand — DISMISSED** [review]

**Comment by seaona** [comment]
PR looks good from QA side :+1: I can see how balances are correctly matching the selected account in the Dapp.
This PR can be merged once we have the x2 dev approvals @jpuri 

image

**Review by digiwand — APPROVED** [review]

**Review by blackdevelopa — APPROVED** [review]
