### PR TITLE
fix: improve assets perfs + fix blurred balances and prices

### LINKED ISSUE #12679: [Bug]: Slower performance when selecting tokens on a network different from the one currently active
### Describe the bug

The token details page may require several seconds to load fully.

Possibly related:

https://github.com/MetaMask/metamask-mobile/issues/12711

https://github.com/MetaMask/metamask-mobile/issues/12678

https://github.com/MetaMask/metamask-mobile/issues/12546

https://github.com/MetaMask/metamask-mobile/issues/12680

https://github.com/MetaMask/metamask-mobile/issues/12753 - Android performance issue

### Expected behavior

https://github.com/user-attachments/assets/7a9a5eb1-6769-46c3-aa06-1d9b13e2ff22

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Switch to 'All networks' view
2. Select token on another network

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

v7.38.0(1514)

### Build type

None

### Device

iPhone 15

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #12724: [Bug]: Blurred balance
### Describe the bug

Blurred balance for tokens on OP Mainnet and Arbitrum One

### Expected behavior

See token balance

### Screenshots/Recordings

https://github.com/user-attachments/assets/1934c67f-5538-4c46-bb59-5d064884ef08

### Steps to reproduce

1. Go to OP Mainnet
2. Notice blurred balance of tokens

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.38.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

I obtained the build from [here](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/85ba5e0e8319c808/public-install-page/f569a89af0111bece1dff683e9a9d8fb) 

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Related issues**

Fixes:  #12724

## **Manual testing steps**

1. Build android project locally
2. Add your account or create new one
3. switch btw network ( the perfs should be good )
4. switch btw popular network and current network on the token list and check the perfs
5. the list of assets should be displayed quickly

### **After**

https://github.com/user-attachments/assets/cdd70d65-820b-40fc-ba7f-85a6dceb66c1

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Tokens/index.tsx [hunk 1]
```diff
@@ -144,48 +144,52 @@ const Tokens: React.FC<TokensI> = ({ tokens }) => {
...
+        stableSelectedAccountTokensChains,
       ).flat() as TokenI[];
-      /*
-        If hideZeroBalanceTokens is ON and user is on "all Networks" we respect the setting and filter native and ERC20 tokens when zero
-        If user is on "current Network" we want to show native tokens, even with zero balance
-      */
-      let tokensToDisplay = [];
+
+      // Use a Set to eliminate duplicates
+      const tokenSet = new Set<TokenI>(allTokens);
```
Comment (salimtb) [inline app/components/UI/Tokens/index.tsx:170]: we're using Set now

File: app/components/Views/NetworkSelector/NetworkSelector.tsx [hunk 2]
```diff
@@ -414,10 +414,7 @@ const NetworkSelector = () => {
       NetworkController.setActiveNetwork(clientId);
       closeRpcModal();
       AccountTrackerController.refresh();
-
-      setTimeout(async () => {
-        await updateIncomingTransactions([networkConfiguration.chainId]);
-      }, 1000);
```
Comment (salimtb) [inline app/components/Views/NetworkSelector/NetworkSelector.tsx:420]: await here is blocking the execution and decrease perfs

File: app/components/UI/Tokens/index.tsx [hunk 3]
```diff
@@ -497,4 +483,4 @@ const Tokens: React.FC<TokensI> = ({ tokens }) => {
   );
 };
 
-export default Tokens;
+export default React.memo(Tokens);
```
Comment (salimtb) [inline app/components/UI/Tokens/index.tsx:486]: use memorisation to have a better perf

File: app/components/UI/Tokens/index.tsx (hunk 1 above)
Comment (Prithpal-Sooriya) [reply app/components/UI/Tokens/index.tsx:170]: Nice win! I'm not sure we get any wins from Set indexes since we do `Array.from(tokenSet)`.

I'm not sure if it also deduplicates since it is an array of objects and not primitives.

Comment (salimtb) [reply app/components/UI/Tokens/index.tsx:170]: eem good point , let me make some changes to use Set indexes instead of converting to an array

File: app/components/UI/Tokens/index.tsx [hunk 4]
```diff
@@ -194,94 +198,76 @@ const Tokens: React.FC<TokensI> = ({ tokens }) => {
...
 
-      const assets = [...nativeTokens, ...nonNativeTokens];
+        // Skip testnet tokens if on mainnet
+        if (isTestNet(chainId) && !isTestNet(currentChainId)) {
+          continue;
+        }
 
-      // Calculate fiat balances for tokens
-      const tokenFiatBalances = assets.map((token) => {
+        assets.push(token);
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Tokens/index.tsx:211]: Really nice cleanup! I prefer the readability of `push`ing than the reduce approach!

File: app/components/Views/NetworkSelector/NetworkSelector.tsx (hunk 2 above)
Comment (Prithpal-Sooriya) [reply app/components/Views/NetworkSelector/NetworkSelector.tsx:420]: LOL

Comment (Prithpal-Sooriya) [reply app/components/Views/NetworkSelector/NetworkSelector.tsx:420]: Great point though, do we need to 'wait' for this promise from `updateIncomingTransactions` to finish? If not, then we can have a dangling promise.

Comment (matthewwalsh0) [reply app/components/Views/NetworkSelector/NetworkSelector.tsx:420]: This predates us but I can try and help.

To clarify, the `await` won't block execution or return here since it's within a `setTimeout` callback so it will queue this for execution after a second but continue the rest of the function and return in the meantime, so it's already a form of dangling promise.

So the suggested safe approach has no impact since the there is no code after the `await` within the `setTimeout` callback.

File: app/components/UI/Tokens/index.tsx (hunk 1 above)
Comment (salimtb) [reply app/components/UI/Tokens/index.tsx]: hey @Prithpal-Sooriya ,
i'm now using the Set and avoid using Array.from , let me know your thoughts/suggestions on this part

Comment (Prithpal-Sooriya) [reply app/components/UI/Tokens/index.tsx]: Cool! The main concern was the `Array.from` conversions (made the usage of the Set pointless). Satisfied with the impl.

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: app/util/networks/index.js [hunk 5]
```diff
@@ -497,5 +497,4 @@ export const isChainPermissionsFeatureEnabled =
 export const isPermissionsSettingsV1Enabled =
   process.env.MM_PERMISSIONS_SETTINGS_V1_ENABLED === 'true';
 
-export const isPortfolioViewEnabled = () =>
-  process.env.PORTFOLIO_VIEW === 'true';
+export const isPortfolioViewEnabled = () => true;
```
Comment (vinnyhoward) [inline app/util/networks/index.js:500]: Is this intentional?

Comment (salimtb) [reply app/util/networks/index.js]: no , just fixed

**Review by vinnyhoward — DISMISSED** [review]
LGTM!

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Comment by owencraston** [comment]
@salimtb do you have any data about how much of a perf improvement this is?

**Comment by salimtb** [comment]
> @salimtb do you have any data about how much of a perf improvement this is?

i can provide some of metrics regarding this

File: app/components/UI/AssetOverview/AssetOverview.tsx [hunk 6]
```diff
@@ -195,7 +196,11 @@ const AssetOverview: React.FC<AssetOverviewProps> = ({
             networkConfiguration.defaultRpcEndpointIndex
           ]?.networkClientId;
 
-        await NetworkController.setActiveNetwork(networkClientId as string);
+        const throttledSetActiveNetwork = throttle(async (id: string) => {
```
Comment (Prithpal-Sooriya) [inline app/components/UI/AssetOverview/AssetOverview.tsx:199]: Nice!

Discuss - do we want a throttle, or a debounce here?
- Throttle - every Xms, we will make the call to set active network. So when "spammed" we will attempt to switch the network.
- Debounce - we only select the active network once, when spam ends. So whatever the last value received from the "spam" invocations, we will execute.

https://css-tricks.com/debouncing-throttling-explained-examples/

File: app/components/UI/AssetOverview/AssetOverview.tsx [hunk 7]
```diff
@@ -226,13 +231,23 @@ const AssetOverview: React.FC<AssetOverviewProps> = ({
...
-              handleSwapNavigation();
-            }, 500);
+        // Create a throttled version of setActiveNetwork
+        const throttledSetActiveNetwork = throttle(
+          async (networkClientIdToUse: string) => {
+            try {
+              await NetworkController.setActiveNetwork(networkClientIdToUse);
+              setTimeout(() => {
+                handleSwapNavigation();
+              }, 500);
```
Comment (Prithpal-Sooriya) [inline app/components/UI/AssetOverview/AssetOverview.tsx:241]: Retaining the original setTimeout here. I'm not entirely sure why it is needed, but that's fine.

File: app/components/UI/NetworkModal/index.tsx [hunk 8]
```diff
@@ -266,7 +267,11 @@ const NetworkModals = (props: NetworkProps) => {
 
     if (networkClientId) {
       onUpdateNetworkFilter();
-      await NetworkController.setActiveNetwork(networkClientId);
+      const throttledSetActiveNetwork = throttle(async (id: string) => {
+        await NetworkController.setActiveNetwork(id);
+      }, 300);
+
+      throttledSetActiveNetwork(networkClientId as string);
```
Comment (Prithpal-Sooriya) [inline app/components/UI/NetworkModal/index.tsx:274]: Nit (we don't need to do this now) - is it possible to make this a reusable func?

**Review by chrisleewilcox — DISMISSED** [review]
After all changes please run E2E and ensure it passes.

File: app/util/networks/index.js (hunk 5 above)
Comment (Prithpal-Sooriya) [reply app/util/networks/index.js:500]: Was this added back?

File: ios/Podfile.lock [hunk 9]
```diff
@@ -791,6 +791,9 @@ PODS:
     - FirebaseCoreExtension
     - React-Core
     - RNFBApp
+  - RNFlashList (1.7.2):
+    - RCT-Folly (= 2021.07.22.00)
+    - React-Core
```
Comment (Prithpal-Sooriya) [inline ios/Podfile.lock:796]: Ok nice pod update!

Qs for mobile team:
1. How come there are no `.gradle` files updated for android? Is this done automatically?
2. Does this mean developers need to re-download the expo APK from runway once this is in if they want the latest native modules? Or is this automatically picked up on main if I run `yarn setup:expo`?

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by vinnyhoward — DISMISSED** [review]

**Review by vinnyhoward — DISMISSED** [review]

File: app/components/UI/Ramp/Views/NetworkSwitcher/NetworkSwitcher.tsx [hunk 10]
```diff
@@ -205,25 +206,37 @@ function NetworkSwitcher() {
...
+
+        // Check if the current network configuration exists in networkConfigurations
+        for (const savedNetwork of Object.values(networkConfigurations)) {
+          if (
+            toHex(savedNetwork.chainId) === toHex(networkConfiguration.chainId)
+          ) {
+            isAdded = true;
+            break; // Exit early if a match is found
+          }
+        }
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Ramp/Views/NetworkSwitcher/NetworkSwitcher.tsx:221]: Nit - 2 loops here, I think there are strategies we can use to minimise this.
BUT if the lists are small, ignore this.

1. Use the networkConfigurationsByChainId state on the networkController
```ts
const networkConfigsByChainId: Record<Hex, NetworkConfig> =
  useSelector(???) // NetworkController.state.networkConfigurationsByChainId

const supportedNetworkConfigurations = rampNetworksDetails.map((n) => ({
  ...n,
  isAdded: toHex(n.chainId) in networkConfigsByChainId
))
```

2. Convert inner into set
```
const savedChainIds = new Set(Object.values(networkConfigurations).map(n => n.chainId))

const supportedNetworkConfigurations = rampNetworksDetails.map((n) => ({
  ...n,
  isAdded: savedChainIds.has(n.chainId)
))
```

File: app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx [hunk 11]
```diff
@@ -112,24 +112,26 @@ export const PortfolioBalance = () => {
     type,
   );
 
-  let total;
-  if (isOriginalNativeTokenSymbol) {
-    if (isPortfolioViewEnabled()) {
-      total = totalFiatBalance ?? 0;
-    } else {
+  const total = useMemo(() => {
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx:115]: Nice! I prefer this over the let mutations!

File: app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx [hunk 12]
```diff
@@ -112,24 +112,26 @@ export const PortfolioBalance = () => {
...
+      return totalTokenFiat ?? 0;
+    }
+    return balance?.tokenFiat ?? 0;
+  }, [isOriginalNativeTokenSymbol, totalFiatBalance, totalTokenFiat, balance]);
 
-  const onOpenPortfolio = () => {
+  const fiatBalance = useMemo(
+    () => `${renderFiat(total, currentCurrency)}`,
+    [total, currentCurrency],
+  );
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx:133]: You do not need to `useMemo` if it returns a primitive (e.g. a basic string/number).

File: app/components/UI/Tokens/index.tsx [hunk 13]
```diff
@@ -56,7 +55,7 @@ import ButtonBase from '../../../component-library/components/Buttons/Button/fou
 import { selectNetworkName } from '../../../selectors/networkInfos';
 import ButtonIcon from '../../../component-library/components/Buttons/ButtonIcon';
 import { selectAccountTokensAcrossChains } from '../../../selectors/multichain';
-import { filterAssets } from './util/filterAssets';
+import { useDebouncedValue } from '../../hooks/useDebouncedValue';
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Tokens/index.tsx:58]: Nice hook! 🎉

File: app/components/UI/Tokens/index.tsx [hunk 14]
```diff
@@ -138,116 +137,140 @@ const Tokens: React.FC<TokensI> = ({ tokens }) => {
...
+          if (isUserOnCurrentNetwork) {
+            // Show tokens if balance is non-zero, native, or staked
+            if (!isZero(balance) || curToken.isNative || curToken.isStaked) {
+              tokensToDisplay.push(curToken);
+            }
+          }
+          // Show tokens if balance is non-zero or staked
+          if (!isZero(balance) || curToken.isStaked) {
+            tokensToDisplay.push(curToken);
+          }
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Tokens/index.tsx:191]: Can you doublecheck for me that we aren't able to push a token into this list twice?

File: app/components/UI/Tokens/index.tsx [hunk 15]
```diff
@@ -138,116 +137,140 @@ const Tokens: React.FC<TokensI> = ({ tokens }) => {
...
         }
       } else {
         tokensToDisplay = allTokens;
       }
 
       // Then apply network filters
-      const filteredAssets = filterAssets(tokensToDisplay, [
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Tokens/index.tsx:189]: I kinda like the original here, but if we measured performance differences then fair 👍🏾

File: app/components/Views/NetworkSelector/NetworkSelector.tsx [hunk 16]
```diff
@@ -285,11 +291,19 @@ const NetworkSelector = () => {
...
+
+          networkThrottled(networkClientId);
+        } catch (error) {
+          Logger.error(new Error(`Error in setActiveNetwork: ${error}`));
+        }
+        sheetRef.current?.dismissModal();
       }
 
-      setTokenNetworkFilter(chainId);
+      // setTokenNetworkFilter(chainId);
```
Comment (Prithpal-Sooriya) [inline app/components/Views/NetworkSelector/NetworkSelector.tsx:306]: Is this intentional?

File: app/selectors/tokensController.ts [hunk 17]
```diff
@@ -7,8 +7,11 @@ import { selectSelectedInternalAccountAddress } from './accountsController';
 import { isPortfolioViewEnabled, TESTNET_CHAIN_IDS } from '../util/networks';
 import {
   selectChainId,
+  selectIsAllNetworks,
+  selectIsPopularNetwork,
   selectNetworkConfigurations,
 } from './networkController';
+import { entries, flatMap } from 'lodash';
```
Comment (Prithpal-Sooriya) [inline app/selectors/tokensController.ts:14]: Do we need these 2 lodash functions?

We have this in core JS.
```
entries -> Object.entries
flatMap -> [...].flatMap
```

File: yarn.lock [hunk 18]
```diff
@@ -29633,9 +29633,9 @@ yocto-queue@^0.1.0:
   integrity sha512-rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==
 
 yocto-queue@^1.0.0:
-  version "1.0.0"
-  resolved "https://registry.yarnpkg.com/yocto-queue/-/yocto-queue-1.0.0.tgz#7f816433fb2cbc511ec8bf7d263c3b58a1a3c251"
-  integrity sha512-9bnSc/HEW2uRy67wc+T8UwauLuPJVn28jb+GtJY16iiKWyvmYJRXVT4UamsAEGQfPohgr2q4Tq0sQbQlxTfi1g==
+  version "1.1.1"
```
Comment (Prithpal-Sooriya) [inline yarn.lock:29636]: Is yarn.lock change intentional? I don't see any `package.json` changes?

File: app/components/UI/Tokens/index.tsx (hunk 15 above)
Comment (salimtb) [reply app/components/UI/Tokens/index.tsx:189]: yes i changed it mainly because of the perf, it's making things slow

**Review by Prithpal-Sooriya — DISMISSED** [review]
LGTM

**Review by vinnyhoward — DISMISSED** [review]

**Review by gambinish — DISMISSED** [review]

File: app/components/UI/Tokens/index.tsx [hunk 19]
```diff
@@ -153,114 +164,127 @@ const Tokens: React.FC<TokensI> = ({ tokens }) => {
...
-        ...token,
-        tokenFiatAmount: tokenFiatBalances[i],
-      }));
-      const tokensSorted = sortAssets(tokensWithBalances, tokenSortConfig);
       endTrace({
         name: TraceName.Tokens,
       });
-      return tokensSorted;
+
+      return sortAssets(tokensWithBalances, tokenSortConfig);
```
Comment (tommasini) [inline app/components/UI/Tokens/index.tsx:287]: Can we sort the tokens first and then end the trace? I think it's good for we to catch all the function complexity in the trace, wdyt?

Comment (salimtb) [reply app/components/UI/Tokens/index.tsx:287]: yes that's true , it's better to include the sort on the traces, will do it now

File: app/components/UI/Tokens/index.tsx [hunk 20]
```diff
@@ -153,114 +164,127 @@ const Tokens: React.FC<TokensI> = ({ tokens }) => {
...
+
+      for (let i = 0; i < assets.length; i++) {
+        const token = assets[i];
+        const tokenWithBalance = {
+          ...token,
+          tokenFiatAmount: tokenFiatBalances[i],
+        };
+
+        tokensWithBalances.push(tokenWithBalance);
+      }
```
Comment (tommasini) [inline app/components/UI/Tokens/index.tsx:281]: In order to remove the exhaustive depts ignore, we could move some of the responsabilities of this functions to other smaller functions wdyt? Does that make sense to you?

Comment (salimtb) [reply app/components/UI/Tokens/index.tsx:281]: that's a good idea , i'll get back to you once it's done

File: app/selectors/tokensController.ts [hunk 21]
```diff
@@ -44,6 +46,45 @@ export const selectTokensByChainIdAndAddress = createDeepEqualSelector(
   ) => tokensControllerState?.allTokens[chainId]?.[selectedAddress as Hex],
 );
 
+// Full selector implementation with selected address filtering
+export const selectTransformedTokens = createDeepEqualSelector(
```
Comment (tommasini) [inline app/selectors/tokensController.ts:50]: Why does this selector needs to be a deep equal?

**Comment by darkwing** [comment]
## Impact

## Root cause

### Related to change?

## Lessons learned

## Corrective actions

File: app/selectors/tokensController.ts (hunk 21 above)
Comment (salimtb) [reply app/selectors/tokensController.ts:50]: The selectTransformedTokens selector uses createDeepEqualSelector to ensure that it only recalculates its output when any of its dependencies (like tokensControllerState, selectedAddress, chainId, etc.) change in a meaningful way. This prevents unnecessary recomputations and re-renders in components, enhancing performance when dealing with complex state structures.

**Review by tommasini — DISMISSED** [review]
Awesome work!!!! LGTM!

**Review by tommasini — DISMISSED** [review]

**Review by tommasini — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
