### PR TITLE
fix: Added TempTouchableOpacity to conditionally simulate tap behavior for android cp-7.57.0

### LINKED ISSUE #21350: [Bug]: Android: Ramp Deposit, Buy, Withdraw closes when token selected is changed
### Describe the bug

Ramps deposit closed when changing the token selected

https://github.com/user-attachments/assets/3a19a3ea-2e36-4a06-8316-134f59181cc5

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

Follow the video steps

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.57.0 (2743)

### Build type

None

### Device

Redmi Note 13 Pro 5G

### Operating system

Android

### Additional context

_No response_

### Severity

sev2

### PR DESCRIPTION
**Pull request by brianacnguyen**
## **Description**

This PR addresses Android-specific touch handling issues where `TouchableOpacity` components within `ScrollView` sometimes fail to fire `onPress` events. The solution introduces a new `TempTouchableOpacity` component that implements a "tap emulator" approach to improve touch reliability on Android while maintaining ScrollView compatibility.

**Key improvements:**
1. **Android Touch Reliability**: Implements strict tap detection with velocity-based filtering to distinguish between taps and scroll gestures
2. **ScrollView Compatibility**: Uses a 50ms delay to allow ScrollView's pan gesture to take precedence when users are scrolling
3. **Accessibility Support**: Maintains normal touch behavior when screen readers are enabled
4. **Component Consolidation**: Replaces multiple custom touch handling implementations with a single, reusable solution

## **Changelog**

CHANGELOG entry: Fixed Android touch handling issues where buttons in ScrollViews sometimes either responded twice or failed to respond to taps

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/21350

## **Manual testing steps**

```gherkin
Feature: Android touch handling in ScrollViews

  Scenario: user taps a button within a ScrollView
    Given the app is running on Android
    And there is a ScrollView containing buttons or list items

    When user taps a button or list item
    Then the onPress event should fire reliably
    And scrolling should not trigger button presses

  Scenario: user scrolls within a ScrollView containing buttons
    Given the app is running on Android
    And there is a ScrollView containing buttons or list items

    When user scrolls the ScrollView
    Then button presses should not be triggered
    And scrolling should work smoothly
```

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Introduce `TempTouchableOpacity` with Android tap emulation and replace custom touch wrappers across components; add opt-in prop, update tests, and bump mobile build numbers.
> 
> - **Touch Handling (Android)**:
>   - Add `components-temp/TempTouchableOpacity` implementing strict tap emulation, ScrollView-friendly delay, and accessibility-aware behavior.
>   - Remove bespoke wrappers (e.g., `PressablePerpsComponent`) and migrate usages to `TempTouchableOpacity`.
> - **Component Updates**:
>   - Replace touch handling in `ButtonBase`, `ListItemSelect`, `ListItemMultiSelect`, Perps components (`PerpsTabView`, `PerpsCard`, `PerpsTutorialCard`), and multiple views to use `TempTouchableOpacity`.
>   - Add `shouldEnableAndroidPressIn` prop to `ButtonBase`, `ListItemSelect`, `ListItemMultiSelect`; propagate where needed (e.g., fiat/region/token selectors, networks filter buttons).
> - **Build/Config**:
>   - Bump Android `versionCode` and iOS `CURRENT_PROJECT_VERSION` to `2772`; update Bitrise `VERSION_NUMBER`/`FLASK_VERSION_NUMBER`.
> - **Tests**:
>   - Update snapshots to reflect new touch behavior (e.g., `onPress` mock, removed `onPressOut`), and revised structure in list/cell snapshots.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit b6d6c97ef4413fa07765c019f97f828d7ad67202. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by wachunei — DISMISSED** [review]

**Comment by sleepytanya** [comment]
Latest QA build - https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/d8ccef4c-e001-4720-8901-377be1f752df

Works as expected:
- switching tokens in `Deposit-Buy-Withdraw` 
- `Got it` button in` Perps`
- `Confirm / Cancel` in Solana and EVM flows 
- `Token details`
- `Add Popular network`
- Token list scroll in `Buy / Withdraw`
- Account name can be edited and successfully saved

   Two remaining issues decided to be unrelated here - [Slack thread:](https://consensys.slack.com/archives/C09GF03A411/p1760976059301069)
- `Wallet `details from `Account details` is unresponsive
- `Receive` button `'Unknown network address'` message


Switching tokens:


https://github.com/user-attachments/assets/be34f11f-c7fe-4c5e-a1c8-9030b163c8c2

`Got it` button in `Perps`:


https://github.com/user-attachments/assets/7647c131-4d43-4253-a82e-0aa80ebeabd7

`Confirm / Cancel` in `Send flow`, `Add Popular Network`, `Account Details`:


https://github.com/user-attachments/assets/2ef5834b-f471-4e4f-a23c-bb9358ce2054


Token list scroll, `Wallet` details and `Receive` button:




https://github.com/user-attachments/assets/66466f40-8b9e-4a57-a836-e61e78e5b4fc

**Review by abretonc7s — DISMISSED** [review]
Tested perps flow  working.

**Comment by Unik0rnMaggie** [comment]
Testing on the QA build from [here](https://app.bitrise.io/build/c97d4dda-dad0-4885-bb02-4aa20248aa20?tab=artifacts) on Android Pixel 6 Pro device:

- Clicking on a token from buy/withdraw is flaky - sometimes it works from the first try, sometimes it works from the third or fourth try
- Accounts list Details button is unresponsive
- Edit account name not possible: clicking on edit account brings up the keyboard, but account cannot be edited
- Account names did not preserve
- Clicking on Wallet details from Account details is unresponsive
- Unknown Network address when clicking on Receive button


https://github.com/user-attachments/assets/7236e331-377c-4cf2-8ffe-0f05f96604d6


https://github.com/user-attachments/assets/fc8336e6-ad70-4184-bb68-e1038e19adbc


https://github.com/user-attachments/assets/3a937e87-f0ca-4cba-aff4-676b4b56171c

**Comment by Unik0rnMaggie** [comment]
Testing on the QA build from [here](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/63512814-4dca-4c2a-ad32-d13e3533649a?tab=artifacts) same Pixel 6 Pro Android device:

- Clicking on a token from buy/withdraw is flaky - sometimes it works from the first try, sometimes it works from the third or fourth try
- Edit account name not possible: clicking on edit account brings up the keyboard, but account cannot be edited



https://github.com/user-attachments/assets/931107b1-dedc-4fd1-8bf4-94f6c810699e


https://github.com/user-attachments/assets/f29231cc-828d-4e26-a948-17c5ec7980a3

**Review by weitingsun — DISMISSED** [review]

**Review by gambinish — DISMISSED** [review]
Approving for Perps. I've tested the edit tpsl flow and geoblock flows.

However, I'd like to also test this on the 7.57 RC, since we've already refactored this UI for 7.58 on main.

@brianacnguyen could you please tag me on the cherry pick PR when Runway creates it? I just want to verify that this fix still works on the 7.57 RC for Perps flows.

**Comment by weitingsun** [comment]
build number changes in mobile platform code owner files. Can either revert or keep them in. Approved the PR

**Comment by sethkfman** [comment]
> build number changes in mobile platform code owner files. Can either revert or keep them in. Approved the PR

We can keep this change unless there is an additional set of changes required from feedback.

File: app/component-library/components-temp/TempTouchableOpacity/TempTouchableOpacity.tsx [hunk 1]
```diff
@@ -0,0 +1,185 @@
...
+
+      // Clear any existing timeout
+      if (timeoutRef.current) {
+        clearTimeout(timeoutRef.current);
+      }
+
+      // Set a delay to allow ScrollView to win if user is scrolling
+      timeoutRef.current = setTimeout(() => {
+        // This will be cancelled by onPressOut if it's a real tap
+      }, 50); // 50ms delay to let ScrollView pan gesture win (reduced for responsiveness)
```
Comment (georgewrmarshall) [inline app/component-library/components-temp/TempTouchableOpacity/TempTouchableOpacity.tsx:93]: non-blocking: could move `50`ms delay to a constant

File: android/app/build.gradle [hunk 2]
```diff
@@ -188,7 +188,7 @@ android {
         minSdkVersion rootProject.ext.minSdkVersion
         targetSdkVersion rootProject.ext.targetSdkVersion
         versionName "7.58.0"
-        versionCode 2296
+        versionCode 2772
```
Comment (georgewrmarshall) [inline android/app/build.gradle:191]: non-blocking: Is this necessary to trigger a new build or target a current one?

**Review by georgewrmarshall — DISMISSED** [review]
Great work consolidating the touch handling logic into a single reusable component! 👍

Approving to unblock ✅

Quick question: have we tested the behavior with TalkBack and VoiceOver? The component includes logic to detect screen readers and fall back to `TouchableOpacity`, but I didn’t see corresponding tests or manual QA validation.

Really appreciate the accessibility focus here but without confirming whether this issue actually impacts screen reader users, we may be introducing complexity to solve an unverified problem.

**Not blocking:** the core fix looks great, just something to consider for future iterations.

File: app/component-library/components-temp/TempTouchableOpacity/TempTouchableOpacity.tsx [hunk 3]
```diff
@@ -0,0 +1,185 @@
+/* eslint-disable react/prop-types */
```
Comment (georgewrmarshall) [inline app/component-library/components-temp/TempTouchableOpacity/TempTouchableOpacity.tsx:1]: non-blocking: This component may need some unit tests to pass SonarCloud tests

Comment (brianacnguyen) [reply app/component-library/components-temp/TempTouchableOpacity/TempTouchableOpacity.tsx:1]: this component is only rendered in non-test env though

File: android/app/build.gradle (hunk 2 above)
Comment (brianacnguyen) [reply android/app/build.gradle:191]: that was automated and was addressed by @sethkfman above

**Review by gantunesr — DISMISSED** [review]

**Review by wachunei — DISMISSED** [review]

**Review by wachunei — DISMISSED** [review]

**Review by weitingsun — DISMISSED** [review]

**Review by weitingsun — APPROVED** [review]

**Review by gambinish — APPROVED** [review]

**Review by georgewrmarshall — APPROVED** [review]

**Review by wachunei — APPROVED** [review]

File: app/component-library/components-temp/TempTouchableOpacity/TempTouchableOpacity.tsx (hunk 3 above)
Comment (georgewrmarshall) [reply app/component-library/components-temp/TempTouchableOpacity/TempTouchableOpacity.tsx:1]: Isn't `process.env.IS_TEST` specifically for e2e tests? I referring to unit tests. I don't think you'll be able to merge until you provide adequate test coverage. See the [Sonar Cloud here](https://sonarcloud.io/component_measures?metric=new_uncovered_lines&selected=metamask-mobile%3Aapp%2Fcomponent-library%2Fcomponents-temp%2FTempTouchableOpacity&pullRequest=21426&id=metamask-mobile) 


Screenshot 2025-10-21 at 12 36 00 PM

**Review by gantunesr — APPROVED** [review]
