### PR TITLE
feat: refactor and fix invalid RPC URL error on paste

### LINKED ISSUE #17161: [Bug]: When adding a custom network or an additional RPC, pasting the link results in Invalid RPC URL message
View issue in GitHub: https://github.com/MetaMask/metamask-mobile/issues/17161

View issue in GitHub: https://github.com/MetaMask/metamask-mobile/issues/17161

View issue in GitHub: https://github.com/MetaMask/metamask-mobile/issues/17161

View issue in GitHub: https://github.com/MetaMask/metamask-mobile/issues/17161

View issue in GitHub: https://github.com/MetaMask/metamask-mobile/issues/17161

**Describe the bug**

When adding a custom network or an additional RPC to an existing network, if the RPC URL is pasted, there is a message stating `Invalid RPC URL` and the RPC or the network cannot be added.

The workaround is to delete some characters and type them back and the message will disappear.

Unable to reproduce on iOS, only on Android

**Expected behavior**

No error message if RPC URL is pasted and is valid

**Screenshots/Recordings**

https://github.com/user-attachments/assets/693de16a-3648-461f-b1ec-ebd296fda7ab

https://github.com/user-attachments/assets/ec1f147a-ec7e-493c-8a47-8daffe8f70ce

**Steps to reproduce**

1. Add custom network or additional RPC to existing network
2. Paste RPC URL
3. Notice error Invalid RPC URL
4. Notice Add RPC URL button greyed out
5. Delete a character from the RPC URL and type it back
6. Notice error message disappeared and Add RPC URL button can be clicked

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

7.51.0

**Build type**

None

**Device**

Pixel 6 Pro

**Operating system**

Android

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

This commit fixes a bug on Android where pasting a valid RPC URL into the network settings would incorrectly trigger an "Invalid RPC URL" error.

The bug was caused by the validation logic being tied to the `onBlur` event, which was not firing correctly after a paste. The fix moves the validation to the `onChangeText` event, ensuring that it is triggered immediately after the text is pasted.

As part of this fix, the RPC URL input field and its validation logic have been refactored into a new, isolated component called `RpcUrlInput`. This improves the testability of the component and the overall code quality. A new test suite has been added for the `RpcUrlInput` component, and the old, now-obsolete tests have been removed. The new files have been created in TypeScript, and PropTypes have been replaced with TypeScript types.

The form has also been cleaned up to remove old feature flags which led to very complex conditional logic.

## **Changelog**

CHANGELOG entry: fix: invalid RPC URL error on paste

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/17161 https://consensyssoftware.atlassian.net/browse/ASSETS-1176

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **After**

https://www.loom.com/share/c415ef5d1d6b497ea9775ece3b041608

https://www.loom.com/share/78d8c8c6b10542389ddccdf748c2b0b8

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Fixes invalid RPC URL error on paste by validating onChange via new RpcUrlInput component and simplifies NetworkSettings by removing legacy UI flag paths.
> 
> - **Networks Settings UI**
>   - **New `RpcUrlInput` component**: Extracts RPC URL field with inline validation on `onChangeText`, warning display, and success callback.
>   - **Integration**: Uses `RpcUrlInput` in the Add RPC modal; updates state via `onValidationChange` and triggers `validateRpcAndChainId` on success.
>   - **Validation changes**: RPC URL validation no longer tied to `onBlur`; chain ID validation paths simplified; removed `isNetworkUiRedesignEnabled` conditionals across rendering and logic.
>   - **UI cleanup**: Consolidates buttons, warning banners, and dropdown usage for RPC and block explorer selectors.
> - **Tests**
>   - Adds unit tests for `RpcUrlInput` (valid paste, invalid/duplicate/existing cases).
>   - Updates `NetworkSettings` tests and snapshots; removes obsolete tests tied to the old validation flow and feature flag.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit af5e9bab98d5e58723507eb9139d85b9a84ba805. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/RpcUrlInput.tsx [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+
+  const [warningRpcUrl, setWarningRpcUrl] = useState<string | undefined>(
+    undefined,
+  );
+
+  const validateRpcUrl = useCallback(
+    async (rpcUrl: string) => {
+      const isNetworkExists = await checkIfNetworkExists(rpcUrl);
+      const isRpcExists = await checkIfRpcUrlExists(rpcUrl);
+      if (!isWebUri(rpcUrl)) {
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/RpcUrlInput.tsx:56]: lifted the existing conditional logic for the RPC url warnings into this component.
The logic is still pretty complex, but we can tackle this as part of another refactor

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/RpcUrlInput.tsx [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+  );
+
+  return (
+    <>
+      <TextInput {...inputProps} onChangeText={handleRpcUrlChange} />
+      {warningRpcUrl && (
+        <View testID={NetworksViewSelectorsIDs.RPC_WARNING_BANNER}>
+          <Text style={warningStyle}>{warningRpcUrl}</Text>
+        </View>
+      )}
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/RpcUrlInput.tsx:117]: This isolated component is soleley responsible for its own validation and error states.

Reduces complexity in the main network settings form component.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/__snapshots__/index.test.tsx.snap [hunk 3]
```diff
@@ -31,38 +31,7 @@ exports[`NetworkSettings should render correctly 1`] = `
 </ContextProvider>
 `;
 
-exports[`NetworkSettings should render the component correctly when isNetworkUiRedesignEnabled is false 1`] = `
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/__snapshots__/index.test.tsx.snap:34]: Removed 1 snapshot, keeping rest as it would be a large time to refactor.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 4]
```diff
@@ -71,7 +64,7 @@ import Icon, {
   IconName,
   IconSize,
 } from '../../../../../component-library/components/Icons/Icon';
-import { isNetworkUiRedesignEnabled } from '../../../../../util/networks/isNetworkUiRedesignEnabled';
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:74]: Removed this FF. It added a lot of complexity to this form component.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 5]
```diff
@@ -710,58 +691,6 @@ export class NetworkSettings extends PureComponent {
    * Validates rpc url, setting a warningRpcUrl if is invalid
    * It also changes validatedRpcURL to true, indicating that was validated
    */
-  validateRpcUrl = async (rpcUrl) => {
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:713]: This was lifted into the RpcUrlInput component.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 6]
```diff
@@ -1568,66 +1479,22 @@ export class NetworkSettings extends PureComponent {
     };
 
     const renderButtons = () => {
-      if (isNetworkUiRedesignEnabled()) {
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:1571]: Removing FF, there is only 1 button we render now.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 7]
```diff
@@ -1919,25 +1741,29 @@ export class NetworkSettings extends PureComponent {
...
+                  checkIfRpcUrlExists={this.checkIfRpcUrlExists}
+                  onValidationSuccess={this.validateRpcAndChainId}
+                  onValidationChange={this.onRpcUrlValidationChange}
+                  warningStyle={styles.warningText}
                 />
-                {warningRpcUrl && (
-                  <View testID={NetworksViewSelectorsIDs.RPC_WARNING_BANNER}>
-                    <Text style={styles.warningText}>{warningRpcUrl}</Text>
-                  </View>
-                )}
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:1940]: This set of components and logic is now replaced with the new isolated component.
Note - there may be some stale component state that was not cleaned up, but we can tackle this once this file is moved to TS.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.test.tsx [hunk 8]
```diff
@@ -744,89 +722,6 @@ describe('NetworkSettings', () => {
       expect(wrapper.state('showAddBlockExplorerForm').isVisible).toBe(false);
     });
 
-    it('should validate RPC URL and set a warning if the format is invalid', async () => {
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.test.tsx:747]: RPC url tests are now handled in isolation.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.test.tsx [hunk 9]
```diff
@@ -1829,24 +1723,6 @@ describe('NetworkSettings', () => {
       expect(instance.checkIfNetworkExists).not.toHaveBeenCalled();
     });
 
-    it('should check if network exists in edit mode', async () => {
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.test.tsx:1832]: this edit mode does not exist as the FF is always enabled now

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.test.tsx [hunk 10]
```diff
@@ -1951,33 +1827,12 @@ describe('NetworkSettings', () => {
...
       jest.spyOn(instance, 'setState');
-      (isNetworkUiRedesignEnabled as jest.Mock).mockImplementation(() => true);
     });
 
     afterEach(() => {
       jest.clearAllMocks(); // Clear all spies after each test
     });
 
-    it('should return custom network if rpcUrl exists in networkConfigurations and UI redesign is disabled', async () => {
-      (isNetworkUiRedesignEnabled as jest.Mock).mockImplementation(() => false);
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.test.tsx:1962]: This test points to code that does not exist as FF is always enabled.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 11]
```diff
@@ -1973,7 +1799,7 @@ export class NetworkSettings extends PureComponent {
             </View>
           </ReusableModal>
         ) : null}
-        {isNetworkUiRedesignEnabled() && showAddBlockExplorerForm.isVisible ? (
+        {showAddBlockExplorerForm.isVisible ? (
```
[the remark this answers is not in the document]
Comment (Prithpal-Sooriya) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:1802]: This was the original logic. I do agree that this is messy, but we'll need to spend some time to actually refactor this component to be easier to work with.

**Review by bergarces — APPROVED** [review]

**Review by PatrykLucka — APPROVED** [review]
