### PR TITLE
fix: ensure edit nonce input only accepts numbers

### LINKED ISSUE #6857: [Bug] Unhandled error `Cannot convert string to buffer` whenever inputing a non-integer nonce
**Describe the bug**
Whenever we Edit the nonce, it is possible to add any value (strings, numbers etc) and proceed with the transaction. This causes the error `Cannot convert string to buffer`

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/f8ff9045-09fd-48e8-a4e1-35ee9b3558ae

**To Reproduce**
_Steps to reproduce the behavior_
1. Enable Edit nonce from Advanced Settings
2. Initiate a transaction
3. Click Edit nonce
4. Input any value adding letters
5. Accept
6. Proceed with the transaction
7. See error

**Expected behavior**
Nonce input should be validated at the time user enters a value, preventing them to input non-permitted values and proceed with the transaction

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `7.4.0` dev build

On production, this also throws an error but it's a different one: `MetaMask Tx Signature: Unkown problem: '....'`

unknown-problem

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by vinistevam**
## **Description**

This PR ensures the input field for edit nonce only accepts numbers.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/6857

## **Manual testing steps**

1. Enable Edit nonce from Advanced Settings
2. Initiate a transaction
3. Click Edit nonce
4. Input any value adding letters
5. Accept
6. Proceed with the transaction

### **After**

[numericNonce.webm](https://github.com/MetaMask/metamask-mobile/assets/45455812/d0ec2b1b-cf55-4031-b78d-5a23450898be)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by OGPoyraz — DISMISSED** [review]

File: app/components/UI/CustomNonceModal/index.js [hunk 1]
```diff
@@ -166,7 +167,11 @@ const CustomModalNonce = ({ proposedNonce, nonceValue, close, save }) => {
                 // autoFocus
                 autoCapitalize="none"
                 autoCorrect={false}
-                onChangeText={onChangeText}
+                onChangeText={(text) => {
+                  if (regex.number.test(text)) {
```
Comment (matthewwalsh0) [inline app/components/UI/CustomNonceModal/index.js:171]: Should we use `isNumber` in `app/util/number` since it's the same logic?

File: app/components/UI/CustomNonceModal/index.js [hunk 2]
```diff
@@ -166,7 +167,11 @@ const CustomModalNonce = ({ proposedNonce, nonceValue, close, save }) => {
                 // autoFocus
```
Comment (matthewwalsh0) [inline app/components/UI/CustomNonceModal/index.js:167]: Given the `keyboardType`, I'm surprised that doesn't prevent text input. Is this fix just for emulator usage or external keyboards?

**Comment by sleepytanya** [comment]
Adding nonnumerical characters works fine - letters are ignored:

https://github.com/MetaMask/metamask-mobile/assets/104780023/8500bfbe-5874-4d57-be4f-b5ea4638a35f

Adding numbers AND letters leads to higher nonce stuck transaction (Etherscan unable to locate hash):

https://github.com/MetaMask/metamask-mobile/assets/104780023/ae30db03-e055-4225-9216-5e337b9694a9


Screenshot 2024-01-09 at 12 25 37 PM

Here I tried to edit nonce using only numbers while having stuck high nonce transaction. While the nonce is successfully edited the transaction gets higher nonce again:


Uploading high.mov…

**Comment by sleepytanya** [comment]
Editing nonce by manual input using numbers only (while having higher nonce stuck transactions) results in wrong high nonce:

https://github.com/MetaMask/metamask-mobile/assets/104780023/50142397-9245-4505-b4f6-2db6ffc88ac8

Editing nonce using "+-" buttons works normal:


https://github.com/MetaMask/metamask-mobile/assets/104780023/dccb1df2-75c3-4046-a217-83285f8be63b

File: app/components/UI/CustomNonceModal/index.js (hunk 2 above)
Comment (vinistevam) [reply app/components/UI/CustomNonceModal/index.js:167]: I was also surprised. It actually prevents the keyboard from showing up in the physical device but accepts copy&paste and any input from an external keyboard on Android (It can be different for ios) for the emulator and the physical device.

File: app/components/UI/CustomNonceModal/index.js (hunk 1 above)
Comment (vinistevam) [reply app/components/UI/CustomNonceModal/index.js]: 100%, I should have searched for it before using the regex.

**Comment by sleepytanya** [comment]
Same bug exist on `main` - manual editing using numbers only results in higher nonce stuck transaction.

**Comment by sleepytanya** [comment]
Probably it is not a bug since we use computer keyboard to input characters on local build while on real Android device keyboard does not appear. Need to confirm the keyboard is unavailable on other mobile devices as well. If we don't get keyboard on mobile devices current issue is not a bug.

**Review by matthewwalsh0 — APPROVED** [review]

**Comment by sleepytanya** [comment]
I'm not able to use any other symbols but numbers in the 'edit nonce'. I'm able to edit nonce numbers on Confirmation screen using = / - buttons and numbers (cut-n-paste). But the transaction submits with next nonce instead of custom one.


https://github.com/MetaMask/metamask-mobile/assets/104780023/143d2e0d-0910-45aa-bc02-337a6de30f83

**Comment by sleepytanya** [comment]
Editing nonce works as expected, low nonce value prompts the error message, high nonce transaction submits successfully.
Samsung s24 + physical device, [QA build](https://app.bitrise.io/build/866e9c25-197d-43c6-a8f9-1203673cf55e?tab=artifacts):


https://github.com/MetaMask/metamask-mobile/assets/104780023/547cd929-a00a-4433-9cdb-5c43236aaaf6
