### PR TITLE
fix: PPOM - Malicious transactions triggered from Deeplinks are not flagged

### LINKED ISSUE #7543: [Bug]: PPOM - Malicious transactions triggered from Deeplinks are not flagged
### Describe the bug

**Problem**: malicious transactions triggered from Deeplinks are not flagged by Blockaid

### Expected behavior

Malicious transactions triggered from deeplinks should also be flagged by Blockaid.

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/edbe2046-6046-4c26-a2ad-3037807d9b71

### Steps to reproduce

1. Generate a malicious link
2. Scan the QR code
3. See how no warning appears

To generate a malicious link. You can use:
- https://metamask.github.io/metamask-deeplinks/# and add the malicious recipeint 0x5FbDB2315678afecb367f032d93F642f64180aa3
-Or modify any links from here, to use the same data as the test dapp https://cortisiko.github.io/ I.e.

Links
- Send ETH: https://metamask.app.link/send/0x5FbDB2315678afecb367f032d93F642f64180aa3?value=3e13
- Malicious Approve: https://metamask.app.link/approve/0x4fabb145d64652a948d72533023f6e7a623c7c53@1/approve?address=0xe50a2dbc466d01a34c3e8b7e8e45fce4f7da39e6&uint256=3e18

### Error messages or log output

_No response_

### Version

Integrate PPOM branch  (behind feature flag) https://github.com/MetaMask/metamask-mobile/pull/7363
In main once the PR is merged
 
### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by segun**
## **Description**
When a malicious transaction is triggered from a dapplink, the blockaid banner alert is not shown. This is because the transaction is shown in the confirm screen after evaluation without calling PPOM.

The approach taken here is to add ppom validation to send flow. 

## **Related issues**

Fixes: #7543 

## **Manual testing steps**

1. Enable Blockaid in Experimental Settings
2. Goto https://metamask.github.io/metamask-deeplinks/# and generate a malicious Payment Request, set the recipient to this malicious address: 0x5FbDB2315678afecb367f032d93F642f64180aa3
3. Open MM Mobile and scan the QR code generated in 1 above
4. You should not see a Blockaid alert
5. Press Cancel the confirm screen
6. Perform a normal send from wallet, enter 0x5FbDB2315678afecb367f032d93F642f64180aa3 as the recipient
7. On confirm screen, you should not see a Blockaid alert
9. Checkout this branch, build and run on a physical device
10. Repeat Steps 2-7
11. This time Blockaid alert should be shown on the confirm screen in Step 4 and Step 7

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/44811/b4c7dc19-8b2b-4133-a09e-3a17a1b2ff6b

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/SendFlow/Confirm/index.js [hunk 1]
```diff
@@ -372,6 +403,36 @@ class Confirm extends PureComponent {
         POLLING_INTERVAL_ESTIMATED_L1_FEE,
       );
     }
+    // add transaction
+    const { TransactionController } = Engine.context;
+    const { result, transactionMeta } =
+      await TransactionController.addTransaction(this.props.transaction, {
```
Comment (blackdevelopa) [inline app/components/Views/SendFlow/Confirm/index.js:409]: Is the intention to add the transaction to on mount rather than on next?

Comment (segun) [reply app/components/Views/SendFlow/Confirm/index.js:409]: As explained on slack: We need the transaction added so that we can get an ID. The ID is needed for PPOM Alerts to show.

Comment (jpuri) [reply app/components/Views/SendFlow/Confirm/index.js:409]: We might need to check if transaction is appropriately updated if user rejects it.

Comment (segun) [reply app/components/Views/SendFlow/Confirm/index.js:409]: I had a call with @blackdevelopa earlier. There's code in transaction controller that does clean up when transaction is rejected.

Comment (jpuri) [reply app/components/Views/SendFlow/Confirm/index.js:409]: Just want to be sure we are updating transaction to rejected when `reject` button is clicked.

Comment (segun) [reply app/components/Views/SendFlow/Confirm/index.js:409]: I just checked again, and cleanup is done when the cance button is pressed.

**Review by blackdevelopa — DISMISSED** [review]

File: app/components/Views/SendFlow/Confirm/index.js (hunk 1 above)
Comment (segun) [reply app/components/Views/SendFlow/Confirm/index.js:409]: So in `app/components/UI/Navbar/index.js:getSendFlowTitle` we have this code
```
  const rightAction = () => {
    const providerType = route?.params?.providerType ?? '';
    trackEventWithParameters(MetaMetricsEvents.SEND_FLOW_CANCEL, {
      view: title.split('.')[1],
      network: providerType,
    });
    resetTransaction();
    navigation.dangerouslyGetParent()?.pop();
  };
```

`resetTransaction` is an action with a reducer, the reducer is defined thus

```
    case 'RESET_TRANSACTION':
      return {
        ...initialState,
      };
 ```
 
 I also did a couple of transactions and logged the state to see if the previous transactions linger in state, but the state is cleared everytime the transaction is cancelled.

**Review by jpuri — APPROVED** [review]

**Review by blackdevelopa — APPROVED** [review]
