### PR TITLE
fix: Base Network change toast and Network Settings

### LINKED ISSUE #16527: [Bug]: Base Mainnet displayed as Private Network in the network picker
### Describe the bug

Base Mainnet is displayed as `Private Network` in the network picker.

This issue was initially noticed in this [PR](https://github.com/MetaMask/metamask-mobile/pull/16349#issuecomment-2976651943), the fix for [this issue](https://github.com/MetaMask/metamask-mobile/issues/15664) 

### Expected behavior

Network name to be displayed as Base Mainnet

### Screenshots/Recordings

https://github.com/user-attachments/assets/86504d55-1b2c-456a-831a-c1d54bc60e5e

### Steps to reproduce

1. Switch to Base Mainnet
2. Switch to Current Network in the network picker
3. Notice network name

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.50.0

### Build type

None

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/16527 and some "Network Setting" UI issues

## **Manual testing steps**

Toast Test
1. Switch to Base
2. Does the toast for switching look correct?

Network Settings
1. Go to Settings > Networks
2. Does Base look correct
3. Try searching/filtering, does Base behave like other default networks?

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/ImageIcon/index.tsx [hunk 1]
```diff
@@ -1,9 +1,9 @@
-import { Image } from 'react-native';
+import { Image, type ImageSourcePropType } from 'react-native';
 import React from 'react';
 import images from 'images/image-icons';
 
 interface ImageIconPropTypes {
-  image: string;
+  image: string | ImageSourcePropType;
```
Comment (Prithpal-Sooriya) [inline app/components/UI/ImageIcon/index.tsx:6]: A string was too "magical", only certain strings that fully match an expected pattern would render.

Now we can optionally takes a string, or pass in an image.

File: app/components/Views/Settings/NetworksSettings/__snapshots__/index.test.tsx.snap [hunk 2]
```diff
@@ -651,7 +649,7 @@ exports[`NetworksSettings should render correctly 1`] = `
                                       }
                                     }
                                   >
-                                    Solana
+                                    Base Main Network
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/__snapshots__/index.test.tsx.snap:652]: Snapshot is expected, as we have added Base Main Network to the list of default networks.

File: app/components/Views/Settings/NetworksSettings/index.js [hunk 3]
```diff
@@ -263,62 +262,54 @@ class NetworksSettings extends PureComponent {
...
-                    style={styles.icon}
-                  />
-                )}
-              </View>
-            </TouchableOpacity>
-          )
-        }
+        {isMainnetNetwork(networkTypeOrRpcUrl) ? (
+          this.renderMainnetNetworks(networkTypeOrRpcUrl)
+        ) : (
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/index.js:267]: Cleaned this up to prevent duplication of main network logic.
Now we don't need seperate render methods for ethereum, linea, etc.

File: app/components/Views/Settings/NetworksSettings/index.js [hunk 4]
```diff
@@ -263,62 +262,54 @@ class NetworksSettings extends PureComponent {
...
+          </TouchableOpacity>
+        )}
       </View>
     );
   }
 
-  renderOtherNetworks() {
-    return this.getOtherNetworks().map((networkType, i) => {
+  renderTestNetworks() {
+    return getTestNetworks().map((networkType, i) => {
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/index.js:312]: Rename `renderOtherNetworks` as this did not match the the header copy "Test Networks".

File: app/components/Views/Settings/NetworksSettings/index.js [hunk 5]
```diff
@@ -359,15 +353,8 @@ class NetworksSettings extends PureComponent {
...
-    const excludedChainIds = [
-      CHAIN_IDS.MAINNET,
-      CHAIN_IDS.LINEA_MAINNET,
-      CHAIN_IDS.GOERLI,
-      CHAIN_IDS.LINEA_GOERLI,
-      CHAIN_IDS.SEPOLIA,
-      CHAIN_IDS.LINEA_SEPOLIA,
-    ];
+    // Define the chainIds to exclude (from our predefined networks list)
+    const excludedChainIds = getAllNetworks().map((n) => Networks[n].chainId);
```
Comment (Prithpal-Sooriya) [inline app/components/Views/Settings/NetworksSettings/index.js:357]: Rather than updating 2 places, we can use the existing Network config.

File: app/constants/urls.ts [hunk 6]
```diff
@@ -48,7 +48,7 @@ export const LINEA_SEPOLIA_BLOCK_EXPLORER = 'https://sepolia.lineascan.build';
 export const LINEA_MAINNET_BLOCK_EXPLORER = 'https://lineascan.build';
 export const MAINNET_BLOCK_EXPLORER = 'https://etherscan.io';
 export const SEPOLIA_BLOCK_EXPLORER = 'https://sepolia.etherscan.io';
-export const BASE_MAINNET_BLOCK_EXPLORER_URL = 'https://basescan.org';
+export const BASE_MAINNET_BLOCK_EXPLORER = 'https://basescan.org';
```
Comment (Prithpal-Sooriya) [inline app/constants/urls.ts:51]: Small rename, to that it matches the other block explorer variable names.

File: app/util/networks/index.js [hunk 7]
```diff
@@ -73,6 +76,19 @@ import {
...
+ *   shortName: string;
+ *   networkId: number;
+ *   chainId: import('@metamask/utils').Hex;
+ *   ticker: string;
+ *   color: string;
+ *   networkType: string;
+ *   imageSource: any;
+ *   blockExplorerUrl: string;
+ *   isTestNet?: boolean;
+ * }>}
```
Comment (Prithpal-Sooriya) [inline app/util/networks/index.js]: LOL I can't go back to JS, I need types.
Using JSDoc types to provide some types/defined interface.

Long term - we really should move this to TS.

File: app/util/networks/index.js [hunk 8]
```diff
@@ -100,6 +104,21 @@ export const NetworkList = {
     networkType: 'linea-mainnet',
     imageSource: lineaMainnetLogo,
     blockExplorerUrl: LINEA_MAINNET_BLOCK_EXPLORER,
+    isTestNet: false,
+  },
+  [BASE_MAINNET]: {
```
Comment (Prithpal-Sooriya) [inline app/util/networks/index.js:109]: I do not like how this file is in JS - it would be good to convert this in TS as a cleanup item.

**Review by salimtb — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
