### PR TITLE
fix: provide snap naming from client cp-7.47.0

### LINKED ISSUE #15399: [Bug]: Naming is inconsistent when running discoverAccounts
### Describe the bug

When discovering Solana accounts, account names are conflicting and thus, the Snap keyring will append a " N" extra-suffix.

Extension fix for this:

https://github.com/MetaMask/metamask-extension/pull/32122

### Expected behavior

_No response_

### Screenshots/Recordings

Image

Image

### Steps to reproduce

1. Import an SRP
  This should trigger the account discovery
2. All accounts should be created and named the proper way like Solana Account 1, ... 2, etc...
3. Try to create a new account from different flows
4. Notice that the nth index is appended to the end of the account name

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.47.0

### Build type

Beta

### Device

iPhone and Android

### Operating system

Android, iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This PR updates the addDiscoveredAccounts to use createAccount from the MultichainWalletSnapClient. It will provide the correct first party snap name. 

Changes:
1. `addDiscoveredAccounts` uses the `createAccount` from the MultichainWalletSnapClient

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15399
Resolves: https://consensyssoftware.atlassian.net/browse/MUL-209?atlOrigin=eyJpIjoiMjdlNTQxYTVmYjNkNDQ3ZmFlODFlMzllMTZkYTNkMDEiLCJwIjoiaiJ9

## **Manual testing steps**

1. Create a brand new wallet
2. Import a SRP
3. See that the Solana account names are correct and not. `Solana Account 1 2`

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/SnapKeyring/MultichainWalletSnapClient.ts [hunk 1]
```diff
@@ -209,31 +209,29 @@ export abstract class MultichainWalletSnapClient {
...
+              entropySource,
+            },
+            {
+              displayConfirmation: false,
+              displayAccountNameSuggestion: false,
+              setSelectedAccount: false,
+            },
+          );
+        }),
+      );
```
Comment (ccharly) [inline app/core/SnapKeyring/MultichainWalletSnapClient.ts:227]: I think we have to go sequentially here, otherwise we could compute the same name with `getMultichainAccountName` and that would still result in `<name> <suffix>` to resolve name conflicts, no?

But there's another problem to this, we are not really `await`ing the account creation to finalize (mainly to avoid a deadlock when the Snap derives its keys, which uses `withKeyring` under the hood)

IMO, we need more refactoring than that to fix this unfortunately 😅

Comment (montelaidev) [reply app/core/SnapKeyring/MultichainWalletSnapClient.ts]: From my testing it didn't, but lets change this to a simple for loop instead.

**Review by owencraston — APPROVED** [review]
Working as expected with multiple SRPs

Simulator Screenshot - iPhone 16 Pro - 2025-05-21 at 18 04 51
