### PR TITLE
fix: Remove hardware wallets cp-7.50.2 cp-7.51.0

### LINKED ISSUE #17061: [Bug] App crash when removing Ledger/QR accounts
Build: RC 7.51.0 - 2081
Ledger Stax

1. Install MM
2. Recover from SRP
3. Add hardware wallet
4. Import 2 Ledger/QR accounts
4. Verify Ledger/QR accounts are imported
5. Add hardware wallet
6. Forget Ledger device 

Expected: Ledger/QR accounts removed with no errors

Actual: View: Root
TypeError: undefined is not an object (evaluating 'e.metadata')

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNityQ2c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb3d73be9a0fc217e3f2f2cda763887bac7beed4/ErrorWhenRemovingLedgerAccounts.MP4)

### PR DESCRIPTION
**Pull request by owencraston**
## **Description**
This change fixes a a crash that would occur when removing a hardware wallet from the account list. The error would throw `Cannot read property 'metadata' of undefined`. This was because the reference to the old InternalAccount was still held on the view but it had been removed from the controllers. To fix this I simply added a optional chaining to the `getLabelTextByInternalAccount` functions's switch statement so that it wouldn't throw/crash if a falsely value was passed in. 

I confirmed that this issue is present in 7.51.0 (where it was initially reported) as well as 7.50.2 therefore I will be cherry picking it into both branches.

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/17061

## **Manual testing steps**

1. Create a wallet 
2. import a hardware wallet, either using Ledger or QR. Easiest is QR with airgap vault
3. connect the wallet via account list -> add account or hardware wallets -> QR
4. you should see a bunch of new accounts added to your wallet with the Pill label of `QR Hardware`
5. click the three dot menu
6. click on remove hardware account
7. click remove
8. the account should be removed from the list
9. the popup with the three dot menu items should close.
10. No error should be thrown.

### **Before**

https://github.com/user-attachments/assets/93c24b59-b83b-4aa4-9ef1-ae408ed93926

### **After**

https://github.com/user-attachments/assets/3714ff80-19e6-4753-9017-d901a8164953

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/address/index.ts [hunk 1]
```diff
@@ -351,7 +357,7 @@ export function getLabelTextByInternalAccount(internalAccount: InternalAccount)
     return null;
   };
 
-  switch (internalAccount.metadata.keyring.type) {
+  switch (internalAccount?.metadata?.keyring?.type) {
```
Comment (owencraston) [inline app/util/address/index.ts:360]: This is the only real change that I made in this file. The rest were auto formatting.

File: app/components/Views/AccountActions/AccountActions.tsx [hunk 2]
```diff
@@ -338,13 +338,15 @@ const AccountActions = () => {
         return;
       }
 
-      await removeHardwareAccount();
+      sheetRef.current?.onCloseBottomSheet(async () => {
```
Comment (owencraston) [inline app/components/Views/AccountActions/AccountActions.tsx:341]: This is not strictly necessary but I noticed that without this change, the popup for the account actions would not close. I imagine this could cause bugs since that popup menu has the deleted account in context. All other actions auto close.

File: app/util/address/index.ts (hunk 1 above)
Comment (owencraston) [reply app/util/address/index.ts:360]: This was the main fix for this change.

**Review by darkwing — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]
