### PR TITLE
fix: always show total for popular networks in connected accounts view 

### LINKED ISSUE #15639: [Bug]: Incorrect account balance in the Permissions in the dapp when on the network other than the globally selected one
### Describe the bug

1. Connect to a dapp
2. In the dapp select a network other than the globally selected one
3. Check the account balance in the Permissions menu

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/2776f115-aff8-4c8f-a9a1-5c4d82f7a8b4

### Steps to reproduce

1. See the description

### Error messages or log output

```shell

```

### Detection stage

On a feature branch

### Version

7.45.2

### Build type

None

### Device

Samsung S24 Ultra

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jiexi**
In this PR, the permissions menu total fiat balance always shows the total for the popular networks regardless of the currently selected network for the dapp, the globally selected network, and the token filter value

## **Related issues**

~Fixes: https://github.com/MetaMask/metamask-mobile/issues/15639~

## **Manual testing steps**

1. Connect to a dapp
2. In the dapp select a network other than the globally selected one
3. Check the account balance in the Permissions menu, it should render aggregated balance

### **Before**

https://github.com/user-attachments/assets/9c42c3b7-6fb5-461e-8e23-ff61e44ebe93

### **After**

https://github.com/user-attachments/assets/299da2da-e75e-4504-9da2-9f2786cebf5c

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by NidhiKJha** [comment]
I suppose this should show the aggregated balance, not the selected network balance

https://github.com/user-attachments/assets/1742b358-0064-452d-a1cb-1082355fcd95

**Comment by NidhiKJha** [comment]
More findings: I reloaded the app with flags on. 

https://github.com/user-attachments/assets/d39e263e-f503-44b2-b440-615bda8b95d7

File: app/components/hooks/useMultichainBalances/useMultichainBalancesForAllAccounts.ts [hunk 1]
```diff
@@ -34,46 +32,27 @@ import {
...
-
-    console.log({isTokenNetworkFilterEqualCurrentNetwork, isPopularNetwork})
-
     const { type } = useSelector(selectProviderConfig);
     const ticker = useSelector(selectEvmTicker);
 
     const formattedTokensWithBalancesPerChain = useGetFormattedTokensPerChain(
       accountsList,
-      !isTokenNetworkFilterEqualCurrentNetwork && isPopularNetwork,
+      true,
```
Comment (NidhiKJha) [inline app/components/hooks/useMultichainBalances/useMultichainBalancesForAllAccounts.ts:52]: Is it ok to pass a hardcoded boolean value here?

**Review by NidhiKJha — COMMENTED** [review]
Looks great! Just left one small nit

https://github.com/user-attachments/assets/093b256f-755a-4116-b883-7e7be2ca1262

File: app/components/hooks/useMultichainBalances/useMultichainBalancesForAllAccounts.ts (hunk 1 above)
Comment (ffmcgee725) [reply app/components/hooks/useMultichainBalances/useMultichainBalancesForAllAccounts.ts:52]: Honestly I would like to give you an informed answer on this, but I don't have enough context on the mobile UI side of things to do so. I do understand that the intent with this hook is to always return the aggregated balance for all available networks, and seeing as how it's only referenced in another hook, I thought it would make sense to simplify this and just pass `true`.

I could be doing something wrong though, so it would be good to have feedback from a more more UI/UX centric dev before proceeding with my suggestion 👍🏾

Comment (NidhiKJha) [reply app/components/hooks/useMultichainBalances/useMultichainBalancesForAllAccounts.ts:52]: Looked more into it, since this is referenced in another hook. I suppose for single network it should have a separate parameter. I believe your fix is fine for now although I am a bit concerned about performance. But I guess we can do it in a follow up PR

**Review by NidhiKJha — DISMISSED** [review]

File: app/components/hooks/useMultichainBalances/useMultichainBalancesForAllAccounts.ts [hunk 2]
```diff
@@ -46,16 +44,12 @@ const useMultichainBalancesForAllAccounts =
...
-    const isTokenNetworkFilterEqualCurrentNetwork = useSelector(
-      selectIsTokenNetworkFilterEqualCurrentNetwork,
-    );
-    const isPopularNetwork = useSelector(selectIsPopularNetwork);
     const { type } = useSelector(selectProviderConfig);
     const ticker = useSelector(selectEvmTicker);
 
     const formattedTokensWithBalancesPerChain = useGetFormattedTokensPerChain(
       accountsList,
-      !isTokenNetworkFilterEqualCurrentNetwork && isPopularNetwork,
```
Comment (sahar-fehri) [inline app/components/hooks/useMultichainBalances/useMultichainBalancesForAllAccounts.ts:58]: I think removing this and hardcoding it to `true` would make the main page always display the balance for allNetworks even when the user clicks on "current network"

https://github.com/user-attachments/assets/1e41aba1-940f-437f-a7b3-31e24aa5716c

File: android/app/build.gradle [hunk 3]
```diff
@@ -188,7 +188,7 @@ android {
         minSdkVersion rootProject.ext.minSdkVersion
         targetSdkVersion rootProject.ext.targetSdkVersion
         versionName "7.46.2"
-        versionCode 1891
+        versionCode 1952
```
Comment (tommasini) [inline android/app/build.gradle]: Can we revert versionCode changes?

File: bitrise.yml [hunk 4]
```diff
@@ -2309,13 +2309,13 @@ app:
       VERSION_NAME: 7.46.2
     - opts:
         is_expand: false
-      VERSION_NUMBER: 1891
+      VERSION_NUMBER: 1952
```
Comment (tommasini) [inline bitrise.yml]: Can we revert this unneeded change as well?

File: ios/MetaMask.xcodeproj/project.pbxproj [hunk 5]
```diff
@@ -1261,7 +1261,7 @@
 				CODE_SIGN_IDENTITY = "Apple Development";
 				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
 				CODE_SIGN_STYLE = Manual;
-				CURRENT_PROJECT_VERSION = 1891;
+				CURRENT_PROJECT_VERSION = 1952;
```
Comment (tommasini) [inline ios/MetaMask.xcodeproj/project.pbxproj]: And at this file as well pleaseee

**Comment by tommasini** [comment]
Let me know once the comments are addressed and will approve it!

File: app/components/hooks/useAccounts/useAccounts.types.ts [hunk 6]
```diff
@@ -81,6 +81,10 @@ export interface UseAccountsParams {
    * @default false
    */
   isLoading?: boolean;
+  /**
+   * Optional chain ID to filter balances for a specific chain. If not provided, uses the currently selected chain.
+   */
+  chainId?: string;
```
Comment (jiexi) [inline app/components/hooks/useAccounts/useAccounts.types.ts]: don't think this is needed either

**Review by NidhiKJha — APPROVED** [review]

**Comment by jiexi** [comment]
Skipping smoke tests as failing scenario seems to be coming from `main`

**Review by tommasini — APPROVED** [review]
