### PR TITLE
fix: fix smart contract address call with non valid network client id

### LINKED ISSUE #14674: Error: No custom network client was found with the ID "ef1b7d1c-fdf5-4532-9dcf-4786f1b39513".
Sentry Issue: [METAMASK-MOBILE-3N95](https://metamask.sentry.io/issues/6540997088/?referrer=github_integration)

```
Error: No custom network client was found with the ID "ef1b7d1c-fdf5-4532-9dcf-4786f1b39513".
  at ResultError (ses.cjs:7676:17)
  at _isSmartContractAddress (app/util/transactions/index.js:394:23)
  at isSmartContractAddress (app/util/transactions/index.js:373:45)
  at _getTransactionActionKey (app/util/transactions/index.js:467:15)
...
(20 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by salimtb**
## **Related issues**

Fixes: #14674 

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/transactions/index.js [hunk 1]
```diff
@@ -493,7 +493,7 @@ export async function getTransactionActionKey(transaction, chainId) {
   const toSmartContract =
     transaction.toSmartContract !== undefined
       ? transaction.toSmartContract
-      : await isSmartContractAddress(to, chainId, networkClientId);
```
Comment (salimtb) [inline app/util/transactions/index.js:496]: When a transaction is processed on a network that is later removed, the `networkClientId` remains in the transaction payload, which causes an error. Therefore, we should always retrieve the `networkClientId` based on the `chainId`, which is what we do when `networkClientId` is not passed

**Review by Prithpal-Sooriya — APPROVED** [review]
