### PR TITLE
fix: metrics event not fired when blockaid is disabled

### LINKED ISSUE #8064: [Bug]: PPOM - Disabling Blockaid from Settings does not fire a metrics event
### Describe the bug

**Problem:** whenever we are disabling Blockaid from Settings we don't see anymore the corresponding metrics event: `Analytics 'trackEventWithParameters' - {"category": "Settings Updated"} {"security_alerts_enabled": false}`
Notice we do see the event for Enabling the feature.

### Expected behavior

We should see a metrics event whenever we disable Blockaid from Settings

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/560e9cb9-1b92-449e-a57e-c27e28a8ca40

### Steps to reproduce

1. Go to Settings
2. Enable Blockaid -- see metrics event is fired
3. Disable Blockaid -- see no metrics event is fired now

### Error messages or log output

_No response_

### Version

7.14.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**
Metrics event not fired when blockaid is toggled off

## **Related issues**

Fixes: MetaMask/metamask-mobile#8064

## **Manual testing steps**

1. Go to settings page
2. Enable and then disable blockaid
3. Check that metrics event if fired

## **Screenshots/Recordings**
NA

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've clearly explained what problem this PR is solving and how it is solved.
- [X] I've linked related issues
- [X] I've included manual testing steps
- [X] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [X] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/Settings/ExperimentalSettings/BlockaidIndicator/BlockaidIndicator.tsx [hunk 1]
```diff
@@ -69,7 +69,7 @@ const BlockaidIndicator = ({ navigation }: Props) => {
       AnalyticsV2.trackEvent(
         MetaMetricsEvents.SETTINGS_EXPERIMENTAL_SECURITY_ALERTS_ENABLED,
         {
-          security_alerts_enabled: !securityAlertsEnabled,
+          security_alerts_enabled: true,
         },
```
Comment (digiwand) [inline app/components/Views/Settings/ExperimentalSettings/BlockaidIndicator/BlockaidIndicator.tsx:73]: it looks like this would not fire if the user happened to close the app while the initialization is processing. I'm thinking it may be better to call this when the initialization has started rather than when it finishes unless the enablement may fail during initialization.

Comment (jpuri) [reply app/components/Views/Settings/ExperimentalSettings/BlockaidIndicator/BlockaidIndicator.tsx:73]: This is actually place where user decides to start initialisation.

Comment (digiwand) [reply app/components/Views/Settings/ExperimentalSettings/BlockaidIndicator/BlockaidIndicator.tsx:73]: it is in the callback passed to `runAfterInteractions` which says it is scheduled to "run after all interactions have completed." are we sure this is the start of the initialization? cc: @jpuri

Comment (jpuri) [reply app/components/Views/Settings/ExperimentalSettings/BlockaidIndicator/BlockaidIndicator.tsx:73]: Yep good point, I would prefer to not change this as its existing code and anyways this code is changing in a following PR.

**Review by blackdevelopa — APPROVED** [review]
Looks good

**Review by segun — APPROVED** [review]
