### PR TITLE
fix: capture exception with Sentry instead throwing the error

### LINKED ISSUE #15453: Error: No metadata found for 'disabledRpcMethodPreferences'
Sentry Issue: [METAMASK-MOBILE-3R35](https://metamask.sentry.io/issues/6591918631/?referrer=github_integration)

```
Error: No metadata found for 'disabledRpcMethodPreferences'
  at ResultError (ses.cjs:7676:17)
  at persistTransform (app/store/persistConfig.ts:102:30)
...
(9 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**

Capture exception instead of throwing an error at the getPersistentState. This is a re implementation of what we have at the base controller.

This is the longer term solution: https://github.com/MetaMask/core/issues/5545

## **Related issues**

Fixes: #15453 

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/store/getPersistentState/getPersistentState.ts [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+      if (typeof propertyMetadata === 'function') {
+        derivedState[key] = propertyMetadata(stateProperty);
+      } else if (propertyMetadata) {
+        derivedState[key] = stateProperty;
+      }
+      return derivedState;
+    } catch (error) {
+      // Throw error after timeout so that it is captured as a console error
+      // (and by Sentry) without interrupting state-related operations
+      setTimeout(() => {
```
Comment (Gudahtt) [inline app/store/getPersistentState/getPersistentState.ts:57]: We don't need `setTimeout` here. We only used `setTimeout` as a way of reporting the error without interrupting the operation. But `captureException` accomplishes that on its own, without `setTimeout`

**Review by Gudahtt — COMMENTED** [review]
Looks good! Left one suggestion for simplifying it though

**Review by MarioAslau — APPROVED** [review]
Looks good!

**Comment by tommasini** [comment]
e2e that are failing are flaky ones failing on main as well https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/b54214fa-e494-48ab-b69b-fd258987981d
