### PR TITLE
[Design Quality] Updated navbar title to remove green dot

### LINKED ISSUE #12768: [Design quality]: Update the mobile header to the design system header - Navbar Title & Receive Flow
### Describe the bug

In mobile, the header we have is deprecated across many pages. Updating all headers to the version we have in our design system creates a consistent look and feel.

### Expected behavior

Headers for all pages use [the DS version](https://github.com/MetaMask/metamask-mobile/tree/main/app/component-library/components/HeaderBase), namely:
- Navbar Title
- Receive Flow

### Screenshots/Recordings

Screenshot 2024-10-18 at 12 56 18 AM

[Figma link](https://www.figma.com/design/bkJ9Ot0HGXiakMqZtQfs8G/Design-Quality?node-id=2362-458)

### Steps to reproduce

1. Open MetaMask
2. Click on Token details

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

11.16.15

### Build type

None

### Device

Samsung

### Operating system

Android

### Additional context

Ping @amandaye0h for context

### Severity

_No response_

### PR DESCRIPTION
**Pull request by brianacnguyen**
## **Description**
- This PR updates the navbar title to remove the green dot
- Also updated the navbar title in Receive flow

## **Related issues**

Fixes: #12768 

## **Manual testing steps**

1. Go to wallet
2. Click on asset
3. Observe change in header
4. Go to receive
5. Observe change in header

### **After**
https://github.com/user-attachments/assets/84d7e1c0-a9a9-4c26-9584-6d83cd1614bd
Screenshot_1734556451
Screenshot_1734557087

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/NavbarTitle/index.js [hunk 1]
```diff
@@ -163,26 +137,22 @@ class NavbarTitle extends PureComponent {
...
-          <Text numberOfLines={1} style={styles.title}>
+          <Text numberOfLines={1} variant={TextVariant.BodyMDBold}>
             {realTitle}
           </Text>
         ) : null}
         {typeof children === 'string' ? (
-          <Text variant={TextVariant.HeadingMD} style={styles.children}>
-            {strings(children)}
-          </Text>
+          <Text variant={TextVariant.BodyMDBold}>{strings(children)}</Text>
```
Comment (brianacnguyen) [inline app/components/UI/NavbarTitle/index.js:145]: Updating text variants based on updated design https://www.figma.com/design/bkJ9Ot0HGXiakMqZtQfs8G/Design-Quality?node-id=2362-458&t=xdB71TRas8cvpwxf-0

**Review by georgewrmarshall — DISMISSED** [review]

**Review by georgewrmarshall — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]

**Review by wachunei — APPROVED** [review]
Ramp Snapshot changes LGTM

**Review by nickewansmith — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Review by jclancy93 — APPROVED** [review]
