### PR TITLE
fix: SRP image cp-7.54.0

### LINKED ISSUE #18290: [Bug]: Should enhance the  image resolution of the SRP flow
### Describe the bug

When user uses phone which bigger screen, the image solution is not high enough and can see it's low

### Expected behavior

Should enhance the image resolution

Image

Figma:
https://www.figma.com/design/pViOUcmjwhEzFsdrwknpNc/Onboarding-redesign--Main-?node-id=6773-54546&m=dev 

### Screenshots/Recordings

Image

### Steps to reproduce

1. Create new wallet with SRP
2. Create password
3. Check the image resolution

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.53.0

### Build type

Beta

### Device

SS S24 Ultra, iPhone14promax

### Operating system

Android, iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by smgv**
## **Description**

1. When user uses phone which bigger screen, the image solution is not high enough and can see it's low - https://github.com/MetaMask/metamask-mobile/issues/18290

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes:

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

- https://github.com/MetaMask/metamask-mobile/issues/18290

## **Pre-merge author checklist**

Screenshot 2025-08-14 at 8 20 02 PM

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by LeVinhGithub** [comment]
lgtm

File: app/components/UI/OptinMetrics/index.js [hunk 1]
```diff
@@ -200,6 +200,13 @@ class OptinMetrics extends PureComponent {
       });
 
   componentDidMount() {
+    if (
+      !this.props.metrics.isEnabled() &&
```
Comment (ieow) [inline app/components/UI/OptinMetrics/index.js]: This is not the root cause of the bug
Check on No Thanks button.
I think we can clear DataCollectionForMarketing when no thanks is pressed.
However please check with original author if the checkbox persistence is intended
https://github.com/MetaMask/metamask-mobile/pull/9687

**Review by ieow — APPROVED** [review]
lgtm
