### PR TITLE
'Use Max' fixes

### LINKED ISSUE #1614: Send Max Balance issue
**Describe the bug**
When clicking send "Max", there is still a remaining amount of ETH left.

Example below.  The user had a balance of 0.03329 ETH but only 0.02876 will be deducted when you click max + tx gas fee.

**Screenshots**
image

### LINKED ISSUE #1700: Insufficient funds during 'use max' for transactions
**Describe the bug**
Insufficient funds error when pressing 'use max' during a transaction and fiat is selected as primary currency
**Screenshots**
Screen Shot 2020-07-16 at 2 38 11 PM

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to settings --> general --> select Fiat as primary currency
2. Open the menu and tap send
3 Press 'use max' button when prompted for amount
4. Press 'next', the error appears

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by EtDu**
**Description**

- Fixes sometimes seeing insufficient funds error when using max
- Fixes sometimes not wiping the entire balance when using max

**Checklist**

**Issue**
 
Resolves #1700 
Resolves #1614 

https://trello.com/c/jlCqEW9v/181-insufficient-funds-during-use-max-for-transactions
https://trello.com/c/kf9Po3o6/157-send-max-balance-doesnt-wipe-out-the-account-fully

### CODE REVIEW

**Review by ibrahimtaveras00 — APPROVED** [review]
Looks good, QA Passed 👍 

Tried with both native and fiat set as my primary currency and tried with both ETH and a few ERC20 tokens to be safe!

File: app/components/Views/SendFlow/Amount/index.js [hunk 1]
```diff
@@ -675,12 +695,13 @@ class Amount extends PureComponent {
...
 		}
-		this.onInputChange(input);
+		this.onInputChange(input, undefined, true);
 	};
 
-	onInputChange = (inputValue, selectedAsset) => {
+	onInputChange = (inputValue, selectedAsset, useMax) => {
 		const { contractExchangeRates, conversionRate, currentCurrency, ticker } = this.props;
 		const { internalPrimaryCurrencyIsCrypto } = this.state;
+		!useMax && this.setState({ maxFiatInput: undefined });
```
Comment (estebanmino) [inline app/components/Views/SendFlow/Amount/index.js:704]: does this need to be here or it can be put in https://github.com/MetaMask/metamask-mobile/pull/1710/files#diff-3fb35285a1d5260613283030e9e9a32cR756 just to not have two state updates on a method

**Review by estebanmino — APPROVED** [review]
LGTM just one small comment

File: app/components/Views/SendFlow/Amount/index.js (hunk 1 above)
Comment (EtDu) [reply app/components/Views/SendFlow/Amount/index.js]: moved!
