### PR TITLE
fix(perps): add fallback subscriptions for missing HyperLiquid API fields cp-7.60.4

### LINKED ISSUE #23721: "Could not connect to Perps" error with no recovery
Reopening the app after having it locked for something like 30 minutes, I can’t access perps anymore.

Need to close/reopen the app to recover

[^ScreenRecording_12-05-2025 10-53-35_1.MP4]

### PR DESCRIPTION
**Pull request by michalconsensys**
## **Description**

This PR fixes missing data issues in HyperLiquid WebSocket subscriptions by implementing fallback subscription mechanisms. The HyperLiquid API has changed its structure, and fields like `clearinghouseState` and `openOrders` that were previously available in `webData2` and `webData3` subscriptions are now missing or have been moved to separate subscription types.

## **Changelog**

CHANGELOG entry: Fixed missing position and order data in HyperLiquid perpetuals by implementing fallback subscription mechanisms for API changes

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/23721
Incident: https://consensys.slack.com/archives/C0A1HK3MZ6K

## **Manual testing steps**

```gherkin
Feature: HyperLiquid Perpetuals Data Subscription

  Scenario: user views positions when API fields are missing
    Given user has an active HyperLiquid perpetuals position
    And the HyperLiquid API is missing clearinghouseState in webData3 response

    When user opens the perpetuals screen
    Then positions should be displayed correctly using fallback subscription
    And position data should update in real-time

  Scenario: user views orders when API fields are missing
    Given user has open orders on HyperLiquid
    And the HyperLiquid API is missing openOrders in webData3 response

    When user opens the perpetuals screen
    Then orders should be displayed correctly using fallback subscription
    And order data should update in real-time

  Scenario: user views account state when API fields are missing
    Given user is connected to HyperLiquid
    And the HyperLiquid API is missing clearinghouseState in webData2 response

    When user views their account balance
    Then account state should be displayed correctly using fallback subscription
    And account data should update in real-time
```

### **Before**

Simulator Screenshot - iPhone 17 Pro - 2025-12-06 at 10 07 33

### **After**

Simulator Screenshot - iPhone 17 Pro - 2025-12-06 at 10 03 55

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Adds fallback `clearinghouseState` and `openOrders` subscriptions and centralized aggregation to handle missing HyperLiquid WebSocket fields, with robust error handling and cleanup.
> 
> - **HyperLiquid perps subscription service (`app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts`)**:
>   - **Fallback data sources**:
>     - Add per-DEX fallback subscriptions for `clearinghouseState` and `openOrders` when absent in `webData3`, with caches (`fallbackClearinghouseStateCache`, `fallbackOpenOrdersCache`).
>     - Auto-ensure fallbacks during `webData3` processing; use cached fallback data when available.
>   - **Aggregation & notification**:
>     - Introduce `aggregateAndNotifySubscribers()` to unify per-DEX caches into aggregated positions, orders, and account and notify only on change.
>   - **Resilience & logging**:
>     - Wrap `webData2`/`webData3` callbacks in try/catch with detailed `Logger.error` context.
>     - Guard against missing fields in `webData2`/`webData3` before access.
>   - **Lifecycle management**:
>     - Track/manage fallback subscriptions (`clearinghouseStateSubscriptions`, `openOrdersSubscriptions`).
>     - Cleanup fallbacks and caches in `cleanupSharedWebData3Subscription()` and `clearAll()`.
>   - **Misc**:
>     - Maintain OI caps extraction and notification; preserve per-DEX caches and HIP-3 handling.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 98a7365cb2ea8fabd17b0cdb2bdbe47e303c44a3. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts [hunk 1]
```diff
@@ -1036,6 +1116,204 @@ export class HyperLiquidSubscriptionService {
...
+            const positionsWithTPSL = positions;
+
+            // Update account state
+            const accountState: AccountState = adaptAccountStateFromSDK(
+              data.clearinghouseState,
+              undefined,
+            );
+
+            // Update caches
+            this.dexPositionsCache.set(cacheKey, positionsWithTPSL);
```
[the remark this answers is not in the document]
Comment (michalconsensys) [reply app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts:1186]: These fields are missing, so no data should come through

File: app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts [hunk 2]
```diff
@@ -774,77 +791,105 @@ export class HyperLiquidSubscriptionService {
...
+
+              // Check for removed fields before accessing
+              if (!data.clearinghouseState) {
+                Logger.error(
+                  new Error(
+                    '[HyperLiquid] CRITICAL: clearinghouseState missing from webData2',
+                  ),
+                  this.getErrorContext('webData2 missing clearinghouseState', {
+                    dataKeys: Object.keys(data),
+                    dataStructure: JSON.stringify(data, null, 2),
```
Comment (nickewansmith) [inline app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts]: Nit: Is it nec to log the entire object?

**Review by dylanbutler1 — DISMISSED** [review]

File: app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts [hunk 3]
```diff
@@ -868,152 +913,187 @@ export class HyperLiquidSubscriptionService {
...
+                        dexStateKeys: Object.keys(dexState),
+                      },
+                    ),
+                  );
+                  // Ensure fallback subscription exists
+                  this.ensureFallbackClearinghouseStateSubscription(
+                    userAddress,
+                    currentDexName,
+                  ).catch((error) => {
+                    Logger.error(
```
Comment (dylanbutler1) [inline app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts]: @sethkfman any way we can bypass this for a hotfix?

File: app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts (hunk 2 above)
Comment (michalconsensys) [reply app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts]: Not actually, removing it

File: app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts (hunk 3 above)
Comment (michalconsensys) [reply app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts]: I'm refactoring it to resolve the sonarcloud issue. Will also attach a label to skip sonarcloud

Comment (sethkfman) [reply app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts]: @dylanbutler1 @michalconsensys Yes, please bypass. I see the label added.

**Review by dylanbutler1 — DISMISSED** [review]

File: app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts [hunk 4]
```diff
@@ -774,77 +791,105 @@ export class HyperLiquidSubscriptionService {
...
           .webData2({ user: userAddress }, (data: WsWebData2Event) => {
-            // webData2 returns clearinghouseState for main DEX only
-            const currentDexName = ''; // Main DEX
+            try {
+              // webData2 returns clearinghouseState for main DEX only
+              const currentDexName = ''; // Main DEX
+
+              // Check for removed fields before accessing
+              if (!data.clearinghouseState) {
+                Logger.error(
```
Comment (nickewansmith) [inline app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts]: nit: not a blocker or anything, this error logs a lot though we will have a fallback, maybe we don't need it and can rely on an error for fallback failure.

**Review by dylanbutler1 — DISMISSED** [review]

File: app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts (hunk 4 above)
Comment (michalconsensys) [reply app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts]: I've removed the logs here completely

File: app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts [hunk 5]
```diff
@@ -868,152 +904,173 @@ export class HyperLiquidSubscriptionService {
...
+                  this.setupFallbackClearinghouseStateSubscription(
+                    userAddress,
+                    currentDexName,
+                  );
+                  // Try to use cached fallback data
+                  const fallbackState =
+                    this.fallbackClearinghouseStateCache.get(currentDexName);
+                  if (!fallbackState) {
+                    // No fallback data yet, skip this update
+                    return;
```
[the remark this answers is not in the document]
Comment (michalconsensys) [reply app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts:942]: This may probably need to be addressed later, but not as a part of the hotfix. We will need to refactor the HL service and drop the old fetching/websockets completely

File: app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts [hunk 6]
```diff
@@ -868,152 +904,173 @@ export class HyperLiquidSubscriptionService {
...
+                }
+
+                const currentDexName = dexIdentifier ?? ''; // null -> '' for Map keys
+
+                // HOTFIX: Handle missing fields by using fallback subscriptions
+                // Check if clearinghouseState is missing and ensure fallback subscription
+                if (!dexState.clearinghouseState) {
+                  Logger.error(
+                    new Error(
+                      '[HyperLiquid] CRITICAL: clearinghouseState missing from webData3.perpDexStates - using fallback subscription',
```
Comment (nickewansmith) [inline app/components/UI/Perps/services/HyperLiquidSubscriptionService.ts]: nit: We could remove this error in favor of errors if the fallback fails

**Review by nickewansmith — DISMISSED** [review]
approving to unblock, perps is working lgtm

**Review by nickewansmith — APPROVED** [review]
