### PR TITLE
fix: redirect to market details page after filling order cp-7.67.0

### LINKED ISSUE #26482: Redirection immédiate après exécution d'une commande perpétuelle
Lorsqu'un utilisateur exécute une transaction à partir de la page de détail du token en appuyant sur le bouton Long/Short, il est d'abord redirigé vers l'écran de détail du token, puis quelques secondes plus tard vers l'écran de détail perpétuel. Nous devrions rediriger l'utilisateur directement vers l'écran du marché perpétuel dès que la commande est soumise, c'est-à-dire lorsque l'écran de commande est fermé.

_Issue created in Slack from a_ [_message_|https://consensys.slack.com/archives/C05PK980JBC/p1771402837777269]_._

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

When a user selects a custom token to pay with on the PerpsOrderView (coming from Token Details), after tapping Long:
- User lands briefly on Token Details (wrong)
- Then gets redirected to Market Details
The expected behavior (which works when Perps balance is selected) is to go directly to Market Details.
## **Changelog**

CHANGELOG entry: Redirects user to Market details page instead of token details page after submitting a perps position when coming from token details page

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/26482

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

https://github.com/user-attachments/assets/1de2360a-cdd1-4750-a8e4-72f1a6f11a01

### **After**

https://github.com/user-attachments/assets/d19cafab-3ecd-465b-8540-c298dc3a0929

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I've included tests if applicable
- [ ] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Low Risk**
> Small, localized change to navigation behavior gated by a new `fromTokenDetails` param; primary risk is unintended back-stack/reset behavior in this specific flow.
> 
> **Overview**
> Fixes the Token Details → Perps one-click trade flow by threading a `fromTokenDetails` flag through `usePerpsActions` → `PerpsOrderRedirect` → confirmations.
> 
> When a deposit is confirmed in `PerpsOrderView` (custom pay token path), the navigation now **resets directly to `PerpsMarketDetails`** instead of `goBack()`, preventing the brief, incorrect return to Token Details; the new flag is added to the Perps navigation param types and passed through unchanged alongside the existing A/B test param.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit acea8889887355c59e7edb96b2b0b74f9377be35. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx [hunk 1]
```diff
@@ -864,8 +865,25 @@ const PerpsOrderViewContentBase: React.FC<PerpsOrderViewContentProps> = ({
           handlePlaceOrder(true);
         });
 
-        await onDepositConfirm();
-        navigation.goBack();
```
Comment (sahar-fehri) [inline app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx:868]: When a custom token needs depositing, the order flow hits this branch:
The navigation.goBack() was causing the tokendetails page to flash before it gets redirected to market details page

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by michalconsensys — DISMISSED** [review]

**Review by OGPoyraz — DISMISSED** [review]

File: app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx [hunk 2]
```diff
@@ -865,7 +866,24 @@ const PerpsOrderViewContentBase: React.FC<PerpsOrderViewContentProps> = ({
         });
 
         await onDepositConfirm();
-        navigation.goBack();
+        navigation.dispatch(
+          CommonActions.reset({
```
Comment (michalconsensys) [inline app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx]: Will this still allow the user to use hardware buttons to go back?

Comment (michalconsensys) [reply app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx]: When going back on android simulator, the user is returned to the main wallet screen instead of the list of the assets to trade with. This can be tested on android emulator using the hardware buttons

Image

Comment (sahar-fehri) [reply app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx]: Good catch
CommonActions.reset broke back navigation when a user entered from the perps tab (perps home → explore markets → market list → market details → order), pressing back would go to the wallet home screen instead of the market list,


I think safest approach would be:
Pass a fromTokenDetails flag through the navigation chain (usePerpsActions → PerpsOrderRedirect → confirmation → PerpsOrderView) and only changes the post-deposit navigation behavior when this flag is true:
* fromTokenDetails: true (token details entry) → CommonActions.reset to market details. The stack reset is acceptable here because the user crossed from outside the perps stack, so there's no meaningful perps back history to preserve.
* fromTokenDetails: false (perps tab entry) → navigation.goBack(), the original behavior. The perps navigation stack stays intact, so back works correctly.

Comment (sahar-fehri) [reply app/components/UI/Perps/Views/PerpsOrderView/PerpsOrderView.tsx]: [644ba68](https://github.com/MetaMask/metamask-mobile/pull/26533/commits/644ba68b2bd43e30df7c108d24bda459590d87d3)

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by michalconsensys — APPROVED** [review]
