### PR TITLE
fix(ramps): adds error message if user tries to sell zero balance token

### LINKED ISSUE #16404: [Bug]: Off ramps - No validation when using a taken with balance 0
### Describe the bug

Usually there's a validation message warning when user tries to submit a value higher than the balance, but if we utilice a token with balance 0, there's no validation.

### Expected behavior

We should get the same message as when using a token with a positive balance.

### Screenshots/Recordings

https://www.loom.com/share/7c4886dec7fc46ff9f9a0cd617b1a3a3?sid=2bb18116-9f31-4475-b1e8-d0f83108013a

### Steps to reproduce

1. Go to Sell section
2. Select a token with balance 0
3. Input a value higher than 0 in the Amount field

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.47.0

### Build type

None

### Device

iPhone 14

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by georgeweiler**
## **Description**

An error message is now displayed if the user tries to sell a token when they have zero balance.

Fixes https://github.com/MetaMask/metamask-mobile/issues/16404

zero-balance

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Ramp/Aggregator/Views/BuildQuote/BuildQuote.tsx [hunk 1]
```diff
@@ -316,9 +316,12 @@ const BuildQuote = () => {
   }, [amountBNMinimalUnit, isBuy, maxSellAmount]);
 
   const hasInsufficientBalance = useMemo(() => {
-    if (!balanceBN || !amountBNMinimalUnit) {
```
Comment (AxelGes) [inline app/components/UI/Ramp/Aggregator/Views/BuildQuote/BuildQuote.tsx:319]: Why aren’t we checking for `balanceBN` anymore? Was that check incorrect?

**Review by AxelGes — APPROVED** [review]
