### PR TITLE
fix: Prevent recipient input to show multiline for selected address

### LINKED ISSUE #22207: [Bug]: BTC address doesn't fit in recipient field
### Describe the bug

Image

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Start a BTC send
2. Pick a recipient
3. Notice the address input field

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

7.59.0

### Build type

None

### Device

iphone 11

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to fix recipient input to show multiline for selected address in send flow

## **Changelog**

CHANGELOG entry: Fix recipient to be shown multi-line in send flow

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/22207

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

Screenshot 2025-11-10 at 12 03 50

### **After**

Screenshot 2025-11-10 at 12 03 43

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Replaces direct TextField props with a custom Input element to force single-line recipient addresses and prevent multiline behavior.
> 
> - **Confirmations › RecipientInput (`app/components/Views/confirmations/components/recipient-input/recipient-input.tsx`)**
>   - Use `TextField` `inputElement` with `foundation/Input` to control behavior.
>     - Configure single-line input: `multiline={false}`, `numberOfLines={1}`, `scrollEnabled={false}`, `textAlignVertical="center"`, `textBreakStrategy="simple"`.
>     - Move input props (value, change handlers, autocorrect/spellcheck/autocomplete/capitalize, placeholder, autofocus, testID) onto `Input`.
>     - Apply `INPUT_STYLE_OVERRIDE` to remove height/lineHeight and pad adjustments; disable state styles; set `textVariant` via `TOKEN_TEXTFIELD_INPUT_TEXT_VARIANT`.
>   - Keep start/end accessories (To label, Clear/Paste buttons) unchanged.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit e06f20c956877dc83e7fb6508bcd9cd9dcf06837. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/confirmations/components/recipient-input/recipient-input.tsx [hunk 1]
```diff
@@ -94,22 +102,39 @@ export const RecipientInput = ({
...
         autoCapitalize="none"
         placeholder={strings('send.enter_address_to_send_to')}
+        autoFocus={false}
+        testID="recipient-address-input"
+        isStateStylesDisabled
+        style={INPUT_STYLE_OVERRIDE}
+      />
+    ),
+    [to, handleTextChange],
+  );
```
Comment (jpuri) [inline app/components/Views/confirmations/components/recipient-input/recipient-input.tsx]: I think we should avoid `useMemo` for jsx fragments like this, We should rather prefer to create a separate small component. Or put it ininline.

Comment (OGPoyraz) [reply app/components/Views/confirmations/components/recipient-input/recipient-input.tsx]: Thanks @jpuri, fair comment - I forgot to remove that while trying to understand issue - making this inline.

**Review by jpuri — APPROVED** [review]
