### PR TITLE
fix: cp-7.45.0 use correct default etherscan link on tx details

### LINKED ISSUE #14767: [Bug]: Clicking on View on etherscan does not display the transaction details anymore
### Describe the bug

When clicking on the `VIEW ON Etherscan` button from the transaction details, the user is redirected to [etherscan.io](https://etherscan.io/) and the transaction details are not displayed. 

It seems that this is due to the link: 

in v7.44.0 the link looks like this: 
https://etherscan.io/tx/0xc800f654a93a570eb252c335bc15e95a180dc5553cc6cbd77eefb129ce9b51ca  

in v7.45.0 the link looks like this: 
https://etherscan.com/tx/0xc800f654a93a570eb252c335bc15e95a180dc5553cc6cbd77eefb129ce9b51ca 

### Expected behavior

See the transaction details, not the main page on etherscan.io 

### Screenshots/Recordings

https://github.com/user-attachments/assets/5ce04302-1d98-4ff4-ba9c-12650c9c0e4f

https://github.com/user-attachments/assets/4e6d47a7-c3aa-4f8f-aca4-150bdb9fc4db

### Steps to reproduce

1. Send any transaction on Ethereum Mainnet
2. Go to Activity List
3. Click on the transaction
4. Click on VIEW ON Etherscan button
5. Notice the transaction details are not displayed 

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.45.0 

### Build type

None

### Device

iPhone 15, Pixel 6 Pro

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

This updates the default etherscan link to be `etherscan.io`

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/14767

## **Manual testing steps**

See repro steps in issue .

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/constants/urls.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ export const MM_ETHERSCAN_URL = 'https://etherscamdb.info/domain/meta-mask.com';
 export const LINEA_GOERLI_BLOCK_EXPLORER = 'https://goerli.lineascan.build';
 export const LINEA_SEPOLIA_BLOCK_EXPLORER = 'https://sepolia.lineascan.build';
 export const LINEA_MAINNET_BLOCK_EXPLORER = 'https://lineascan.build';
-export const MAINNET_BLOCK_EXPLORER = 'https://etherscan.com';
+export const MAINNET_BLOCK_EXPLORER = 'https://etherscan.io';
```
Comment (Prithpal-Sooriya) [inline app/constants/urls.ts:53]: etherscan.com seems to be the wrong link.
It redirects to etherscan.io, however the redirect does not contain the rest of tx url path.

Comment (darkwing) [reply app/constants/urls.ts:53]: Geez :/

File: app/components/UI/TransactionElement/TransactionDetails/index.test.tsx [hunk 2]
```diff
@@ -55,13 +56,6 @@ const initialState = {
       ...backgroundState,
       AccountsController: MOCK_ACCOUNTS_CONTROLLER_STATE,
     },
-    // NetworkController: {
```
Comment (darkwing) [inline app/components/UI/TransactionElement/TransactionDetails/index.test.tsx:58]: Should we restore this?

Comment (Prithpal-Sooriya) [reply app/components/UI/TransactionElement/TransactionDetails/index.test.tsx:58]: Not sure why this was commented out in the first place.
Tests all seem to pass without it.

File: app/constants/urls.ts (hunk 1 above)
Comment (Prithpal-Sooriya) [reply app/constants/urls.ts:53]: For visibility, we never really used these default block explorers for the TX details.

It was recently added to fix a scenario where a user did not set a block explorer.
https://github.com/MetaMask/metamask-mobile/pull/14498/files#diff-6a367b305e0025982838abfec4079d5d86d0c81b975bb74c43a44c40fa92dbe7R192-R200

**Review by sahar-fehri — APPROVED** [review]
