### PR TITLE
fix: cp-7.44.0 Add notification when redesigned transaction confirmation submitted and finalized

### LINKED ISSUE #14438: [Bug]: Staking transaction confirmation toast missing
### Describe the bug

Transaction confirmation toasts aren't appearing for pooled-staking transactions.
- Stake
- Unstake
- Claim

In previous builds, a green transaction confirmation toast would appear at the bottom of the screen.

### Expected behavior

A transaction confirmation toast should appear at the bottom of the screen.

### Screenshots/Recordings

_No response_

### Steps to reproduce

**Staking on Mainnet** 
1. Stake some ETH
2. Navigate away from the smart transactions bottom-sheet
3. When the transaction confirms there's no transaction confirmation toast.

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.44.0

### Build type

None

### Device

iPhone 11 (iOS v18.3.2)

### Operating system

iOS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

Adds an event handler to `TransactionController:transactionApproved` and when transaction approved it calls NotificationManager to handle notification.

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/4595

## **Manual testing steps**

No user flow changes

## **Screenshots/Recordings**

Fixes : https://github.com/MetaMask/metamask-mobile/issues/14438

### **After**

https://github.com/user-attachments/assets/c1692a6f-4b36-4388-8723-8a9db9546074

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/Engine/controllers/transaction-controller/transaction-controller-init.ts [hunk 1]
```diff
@@ -18,20 +18,21 @@ import {
...
 } from '../../types';
 import type { TransactionEventHandlerRequest } from './types';
+import {
+  handleTransactionApprovedEventForMetrics,
+  handleTransactionRejectedEventForMetrics,
+  handleTransactionSubmittedEventForMetrics,
+  handleTransactionAddedEventForMetrics,
+  handleTransactionFinalizedEventForMetrics,
+} from './event-handlers/metrics';
+import { handleShowNotification } from './event-handlers/notification';
```
Comment (OGPoyraz) [inline app/core/Engine/controllers/transaction-controller/transaction-controller-init.ts:35]: These are just small reorganisation under `event-handler` folder.

File: app/core/Engine/controllers/transaction-controller/transaction-controller-init.ts [hunk 2]
```diff
@@ -194,7 +195,14 @@ function addTransactionControllerListeners(
   initMessenger.subscribe(
     'TransactionController:transactionApproved',
     ({ transactionMeta }: { transactionMeta: TransactionMeta }) => {
-      handleTransactionApproved(
+      handleShowNotification(transactionMeta);
+    },
+  );
```
Comment (OGPoyraz) [inline app/core/Engine/controllers/transaction-controller/transaction-controller-init.ts:200]: New event handler added here

File: app/core/Engine/controllers/transaction-controller/event-handlers/notification.ts [hunk 3]
```diff
@@ -0,0 +1,16 @@
+import {
+  TransactionType,
+  type TransactionMeta,
+} from '@metamask/transaction-controller';
+import NotificationManager from '../../../../NotificationManager';
+import { REDESIGNED_TRANSACTION_TYPES } from '../../../../../components/Views/confirmations/hooks/useConfirmationRedesignEnabled';
+
+export function handleShowNotification(transactionMeta: TransactionMeta) {
+  if (
+    REDESIGNED_TRANSACTION_TYPES.includes(
```
Comment (OGPoyraz) [inline app/core/Engine/controllers/transaction-controller/event-handlers/notification.ts:10]: Existing confirmations already handling this in the page components hence only triggering this for redesigned.

**Review by vinistevam — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]
