### PR TITLE
fix: Improve address formatting for CAIP asset types

### LINKED ISSUE #16129: [Bug]: 'To' field should surface token address
### Describe the bug

'To' field should surface token address

Image

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

Open swaps and see what the to address is

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.48.99

### Build type

None

### Device

iPhone 14 Pro

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by bfullam**
## **Description**
Updated the formatAddress function to handle CAIP asset types by extracting and shortening the asset reference. Introduced a shortAddress helper for consistent address shortening.

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/16129

## **Manual testing steps**

1. Go to swaps on Solana
2. See destination token address does not include chain identifier

### **Before**
image

### **After**
Screenshot 2025-07-09 at 15 52 21

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Bridge/components/TokenInputArea/index.tsx [hunk 1]
```diff
@@ -80,8 +81,16 @@ export enum TokenInputAreaType {
...
+const shortAddress = (address?: string) => address ? `${address.slice(0, 6)}...${address.slice(-4)}` : undefined;
+
+const formatAddress = (address?: string) => {
+  if (isCaipAssetType(address)) {
+    const { assetReference } = parseCaipAssetType(address);
+    return shortAddress(assetReference);
+  }
+
+  return shortAddress(address);
+};
```
Comment (SteP-n-s) [inline app/components/UI/Bridge/components/TokenInputArea/index.tsx:93]: Should we extract these helper methods in a utility file in case we want to use them in other places in the app?

Comment (bfullam) [reply app/components/UI/Bridge/components/TokenInputArea/index.tsx:93]: Good call, just checked this out and we already have a util for rendering shortened addresses. Transitioned to using this util now 👌

**Review by SteP-n-s — APPROVED** [review]
