### PR TITLE
fix: back up logic to clear vault before reapplying

### LINKED ISSUE #9355: [Sentry] Error: Could not encrypt data with alias: VAULT_BACKUP
Sentry Issue: [METAMASK-MOBILE-2BYM](https://metamask.sentry.io/issues/5206822698/?referrer=github_integration)

```
Error: Could not encrypt data with alias: VAULT_BACKUP
  at backupVault (app/core/BackupVault/backupVault.ts:41:54)
  at <global> (app/core/BackupVault/backupVault.ts:37:34)
  at controllerMessenger.subscribe$argument_1 (app/core/Engine.ts:954:20)
...
(37 additional frame(s) were not displayed)
```

### LINKED ISSUE #9419: [Sentry] Error: The specified item already exists in the keychain.
Sentry Issue: [METAMASK-MOBILE-2BAS](https://metamask.sentry.io/issues/5153283155/?referrer=github_integration)

```
Error: The specified item already exists in the keychain.
  at r (ses.cjs:7575:17)
  at backupVault (app/core/BackupVault/backupVault.ts:41:32)
  at backupVault (app/core/BackupVault/backupVault.ts:67:2)
  at <global> (app/core/BackupVault/backupVault.ts:37:34)
  at controllerMessenger.subscribe$argument_1 (app/core/Engine.ts:895:9)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by sethkfman**
## **Description**

# Root Cause of the Issue

`backupVault` unconditionally calls `setInternetCredentials`, failing when `VAULT_BACKUP_KEY` already exists in the keychain due to repeated `KEYRING_STATE_CHANGE_EVENT` triggers.

### The Engine class is initialized, setting up the vault backup mechanism.
The `Engine` class constructor calls `this.handleVaultBackup()` to subscribe to keyring state changes, initiating the backup process.
(See app/core/Engine/Engine.ts)

### The Engine subscribes to the KEYRING_STATE_CHANGE_EVENT.
This subscription means that whenever the keyring's state changes, the associated callback function will be executed, potentially triggering a vault backup.
(See app/core/Engine/Engine.ts)

### The keyring state changes, and the new state contains a vault.
This event signifies that the keyring's vault data has been loaded or modified, prompting a backup. This could happen on unlock, account creation, or import.
(See app/core/Engine/Engine.ts)

### The handleVaultBackup function is triggered, calling backupVault.
The subscription callback in `handleVaultBackup` is executed, leading to the invocation of the `backupVault` function with the current keyring state.
(See app/core/Engine/Engine.ts)

### The backupVault function attempts to store the vault in the keychain without checking for existing credentials.
The `backupVault` function directly calls `setInternetCredentials` with `VAULT_BACKUP_KEY`, `VAULT_BACKUP_KEY`, and the vault data, without verifying if an entry with that key already exists. This is the most critical step leading to the error.
(See app/core/BackupVault/backupVault.ts)

### The setInternetCredentials function throws an error because the keychain item already exists.
Since a vault backup already exists in the keychain (from a previous keyring state change), `setInternetCredentials` throws an error, halting the backup process.
(See node_modules/react-native-keychain/index.js)

# Changes

### Back up temporary vault before re-applying primary vault
Since the primary vault needs to be reset before a new one is applied, we added a fail safe (in `backupVault` function) by first backing up a temporary version of the vault. In the event of failure when attempting to reset and/or re-apply the vault, the temporary one would still be available as the fallback. If the vault is successfully re-applied, then the temporary vault is reset immediately afterwards.

### Clear any existing vault backup before creating a new one to avoid keychain errors.
```typescript
await _resetVaultBackup();
```
This line calls the `_resetVaultBackup` function to delete any existing keychain entry associated with `VAULT_BACKUP_KEY` before attempting to create a new one. This prevents the "Keychain item already exists" error.
(See app/core/BackupVault/backupVault.ts)

### Implement error handling to prevent app crashes during vault backup.
```typescript
try {
  // ... backup logic ...
} catch (error) {
  Logger.error(error, 'Vault backup failed');
  return {
    success: false,
    error: error instanceof Error ? error.message : VAULT_BACKUP_FAILED
  };
}
```
This code adds a `try...catch` block around the vault backup logic. If any error occurs during the backup process, it will be caught, logged, and a failure response will be returned, preventing the app from crashing.
(See app/core/BackupVault/backupVault.ts)

### Debounce `backupVault` calls in KeyringController state change subscription
Since this event is triggered may be triggered multiple times in quick succession, we added a debounce mechanism to prevent multiple asynchronous calls for updating the vault

## **Related issues**

Fixes: #9419

## **Manual testing steps**

1. Start up the app
2. Run the app and see the lack of a vault back up error in logs. 
3. Remove the state object to trigger vault corruption
4. Confirm app can recover.

### **After**

iOS

https://github.com/user-attachments/assets/9e9a4ed5-a7bc-4b11-bc09-20371d635922

Android

## **Pre-merge author checklist**

https://github.com/user-attachments/assets/26415f84-1ed5-4cfe-9332-d926d82b924a

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by MarioAslau — DISMISSED** [review]

**Review by Cal-L — DISMISSED** [review]
Nice LGTM

**Review by gantunesr — COMMENTED** [review]
looks good! I'd just update/add the proper unit tests

File: app/core/BackupVault/backupVault.ts [hunk 1]
```diff
@@ -38,24 +45,34 @@ export async function backupVault(
...
-  // Backup vault
-  const backupResult = await setInternetCredentials(
-    VAULT_BACKUP_KEY,
-    VAULT_BACKUP_KEY,
-    keyringVault,
-    options,
-  );
+  try {
+    // Clear any existing vault backup first to prevent "item already exists" errors
+    await resetVaultBackup();
```
Comment (gantunesr) [inline app/core/BackupVault/backupVault.ts:50]: While talking to @ccharly, he pointed out that this solution would be more robust if we safe two copies of the vault. In the edge case that we execute `resetVaultBackup` and `setInternetCredentials` fails, there will be an extra copy that can still be retrieved

Comment (Cal-L) [reply app/core/BackupVault/backupVault.ts:49]: @gantunesr I'll reach out to you in Slack about this to see how we can implement this. As for this PR, we can keep it scoped to just addressing the original error for now.

Comment (Cal-L) [reply app/core/BackupVault/backupVault.ts]: Implemented a temporary secondary backup while reseting the primary for now based on our convo - https://consensys.slack.com/archives/C08PN631R0X/p1745884192737909

**Review by MarioAslau — APPROVED** [review]
