### PR TITLE
fix: cp-7.57.0 update destination chain balances after bridge transaction

### LINKED ISSUE #20727: [Bug]: Destination coin never appeared after a swap from Solana to Polygon
### Describe the bug

After performing a swap from Solana SOL to Polygon Aave (first time the account interact with this asset), the tx was completed, but the new token (Aave) never showed up in the assets list. Checking https://polygonscan.com/address/0x393a8d3f7710047324d369a7cb368c0570c335b8, the token appears 

### Expected behavior

New token should be displayed in the assets list

### Screenshots/Recordings

Image

### Steps to reproduce

Swap from Solana SOL to Aave on Polygon (the user did not have this token before)

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.57.0

### Build type

None

### Device

iphone

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by micaelae**
## **Description**

Changes
- patch bridge-status-controller so that it publishes the `destTransactionCompleted` event with the received token's CAIP  assetId when the bridge-api indicates that a bridge transaction has successfully completed

## **Changelog**

CHANGELOG entry: `fix: trigger token balance update on destination chain after a bridge transaction succeeds`

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/20727

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Emit a destination-transaction-completed event with CAIP asset from BridgeStatusController and have Engine refresh EVM token detection/balances upon receipt; update token refresh flow to use Solana selection and add a null-safe log topic check.
> 
> - **Bridge/Status**:
>   - Publish `BridgeStatusController:destinationTransactionCompleted` with received `CaipAssetType` when status is `COMPLETE` in `dist/bridge-status-controller.cjs`.
>   - Extend `dist/types.d.cts` with the new event type and payload.
> - **Engine**:
>   - Subscribe to `BridgeStatusController:destinationTransactionCompleted` and, for `eip155` chains, trigger `TokenDetectionController.detectTokens` and `TokenBalancesController.updateBalances` for the destination chain in `app/core/Engine/Engine.ts`.
> - **Tokens**:
>   - Refactor `refreshTokens` API to `isSolanaSelected` (non‑EVM path updates `MultichainBalancesController`; EVM path uses `performEvmRefresh`).
>   - Update `app/components/UI/Tokens/index.tsx` to derive `isSolanaSelected` and pass it to `refreshTokens`.
>   - Update tests in `util/refreshTokens.test.ts` to reflect new logic and expectations.
> - **Utils**:
>   - Add optional chaining to `topics[0]?.startsWith(...)` in `dist/utils/swap-received-amount.cjs` to avoid undefined access.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 3c913ccebbe9bd6eb6716cc8e795230c85e2516c. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by sleepytanya** [comment]
@micaelae 

Balances updated almost immediately, bridge Solana USDC -> Polygon USDC, Android, [QA build](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/55ebc564cf27c6ef):




https://github.com/user-attachments/assets/e9825e0d-6b63-4245-bf47-4914c9464705

File: app/components/UI/Tokens/util/refreshTokens.ts [hunk 1]
```diff
@@ -15,12 +15,12 @@ interface RefreshTokensProps {
 }
 
 export const refreshTokens = async ({
-  isEvmSelected,
+  isSolanaSelected,
   evmNetworkConfigurationsByChainId,
   nativeCurrencies,
   selectedAccountId,
 }: RefreshTokensProps) => {
-  if (!isEvmSelected) {
```
Comment (salimtb) [inline app/components/UI/Tokens/util/refreshTokens.ts:23]: this was wrong , this is an old behavior before BIP-44

**Review by salimtb — DISMISSED** [review]

**Review by tommasini — COMMENTED** [review]
We should also delete the patch file on the patches folder outside of the yarn folder

**Review by salimtb — DISMISSED** [review]

**Review by salimtb — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
