### PR TITLE
fix: cp-7.45.0 fix block explorer link for default networks on trx detail modal.

### LINKED ISSUE #14497: [Bug] View on Explorer button not being displayed for native networks
https://github.com/MetaMask/metamask-mobile/pull/13922

1. Install MM
2. Recover from SRP
3. Select Linea Sepolia network
4. Send a transaction 
5. Click on Transaction tab
6. Verify the 'Click on Explorer' button is displayed

Expected: Button to be displayed
Actual: Button not displayed 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXFWQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae455c1cec7aea9d4d7e630978b25a57589bbbc7/ClickOnExplorer-NotDisplayed.MP4)

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**
Block explorer link should be displayed for default networks

## **Related issues**

Fixes: #14497 

## **Manual testing steps**

1. Install MM
2. Recover from SRP
3. Select Linea Sepolia network
4. Send a transaction
5. Click on Transaction tab
6. Verify the 'Click on Explorer' button is displayed

### **After**

https://github.com/user-attachments/assets/80c5f382-1a57-44ff-bd64-f4a4f1d87d1d

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/TransactionElement/TransactionDetails/index.js [hunk 1]
```diff
@@ -166,6 +174,39 @@ class TransactionDetails extends PureComponent {
...
+    // Check for default block explorers based on chain ID
+    if (isMainNet(txChainId)) {
+      blockExplorer = MAINNET_BLOCK_EXPLORER;
+    } else if (isLineaMainnetChainId(txChainId)) {
+      blockExplorer = LINEA_MAINNET_BLOCK_EXPLORER;
+    } else if (txChainId === CHAIN_IDS.LINEA_SEPOLIA) {
+      blockExplorer = LINEA_SEPOLIA_BLOCK_EXPLORER;
+    } else if (txChainId === CHAIN_IDS.SEPOLIA) {
+      blockExplorer = SEPOLIA_BLOCK_EXPLORER;
+    }
```
Comment (stanleyyconsensys) [inline app/components/UI/TransactionElement/TransactionDetails/index.js:200]:
```suggestion
    // Due to `blockExplorerUrls` may be omit for new installed user,
    // hence, we re-assign the default block explorer from `blockExplorerUrls` 
    // TODO: It should be fixed in NetworkController
    if (blockExplorer === NO_RPC_BLOCK_EXPLORER  && hasProperty(BlockExplorerUrl, txChainId) {
       blockExplorer = BlockExplorerUrl[txChainId]
    }
```

URL can be found from `controler-utils`

File: app/components/UI/TransactionElement/TransactionDetails/index.js [hunk 2]
```diff
@@ -451,7 +489,6 @@ class TransactionDetails extends PureComponent {
             chainId={chainId}
           />
         </View>
-
         {updatedTransactionDetails.hash &&
           status !== 'cancelled' &&
           rpcBlockExplorer !== NO_RPC_BLOCK_EXPLORER && (
```
Comment (stanleyyconsensys) [inline app/components/UI/TransactionElement/TransactionDetails/index.js:494]:
```suggestion
          rpcBlockExplorer &&  
          rpcBlockExplorer !== NO_RPC_BLOCK_EXPLORER && (
```
i think the nested condition should placed here instead

**Review by stanleyyconsensys — COMMENTED** [review]
just few minor comments

File: app/components/UI/TransactionElement/TransactionDetails/__snapshots__/index.test.tsx.snap [hunk 3]
```diff
@@ -1569,6 +1569,55 @@ exports[`TransactionDetails should render correctly 1`] = `
...
+                            "marginBottom": 24,
+                            "marginTop": 12,
+                          }
+                        }
+                      >
+                        <Text
+                          style={
+                            [
+                              false,
+                              undefined,
```
Comment (Cal-L) [inline app/components/UI/TransactionElement/TransactionDetails/__snapshots__/index.test.tsx.snap:1585]: Where are all of these undefineds coming from?

**Review by Cal-L — APPROVED** [review]
Lgtm
