### PR TITLE
fix: forced light theme colors for buttons cp-7.54.0

### LINKED ISSUE #18115: [Bug]: Should use dark theme for login button and reset wallet text
### Describe the bug

User is at Get started step, will see button has light theme
when reset the wallet, the purple text display on iOS

### Expected behavior

Should use button with dark theme
Reset wallet text should be black

### Screenshots/Recordings

Image

Image

### Steps to reproduce

n/a

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.53.0

### Build type

Beta

### Device

All

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by smgv**
## **Description**
https://github.com/MetaMask/metamask-mobile/issues/18115
- Bug 1: https://www.notion.so/metamask-consensys/211f86d67d688014b7a6cc068367e4c5?v=211f86d67d68803c88d7000cfcf4f021&p=23ff86d67d6880eead78d7bd22270f4f&pm=s
- Bug 2: https://www.notion.so/metamask-consensys/211f86d67d688014b7a6cc068367e4c5?v=211f86d67d68803c88d7000cfcf4f021&p=23ff86d67d688022963ac7d1b6283b64&pm=s

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

### **Before**

- Bug 1: https://www.notion.so/metamask-consensys/211f86d67d688014b7a6cc068367e4c5?v=211f86d67d68803c88d7000cfcf4f021&p=23ff86d67d6880eead78d7bd22270f4f&pm=s
- Bug 2: https://www.notion.so/metamask-consensys/211f86d67d688014b7a6cc068367e4c5?v=211f86d67d68803c88d7000cfcf4f021&p=23ff86d67d688022963ac7d1b6283b64&pm=s

### **After**

Screenshot 2025-07-30 at 10 27 21 PM
Screenshot 2025-07-30 at 10 27 28 PM

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by LeVinhGithub** [comment]
lgtm

**Review by chaitanyapotti — DISMISSED** [review]

File: app/components/UI/SolanaNewFeatureContent/SolanaNewFeatureContent.tsx [hunk 1]
```diff
@@ -127,7 +128,14 @@ const SolanaNewFeatureContent = () => {
                 testID={
                   SolanaNewFeatureSheetSelectorsIDs.SOLANA_IMPORT_ACCOUNT_BUTTON
                 }
-                label={strings('solana_new_feature_content.import_your_wallet')}
+                label={
+                  <Text
+                    variant={TextVariant.BodyMDMedium}
+                    color={lightTheme.colors.primary.inverse}
```
Comment (georgewrmarshall) [inline app/components/UI/SolanaNewFeatureContent/SolanaNewFeatureContent.tsx]: I'm not sure we want to use the theme color token here it changes depending on light and dark theme (light: white, dark: black) we want the text to stay white regardless of theme I have a fix here: https://github.com/MetaMask/metamask-mobile/pull/18206

**Review by georgewrmarshall — COMMENTED** [review]
Hey @smgv, is this PR still valid? I have a PR open  for the solana page fix
https://github.com/MetaMask/metamask-mobile/pull/18206

File: app/components/UI/SolanaNewFeatureContent/SolanaNewFeatureContent.tsx (hunk 1 above)
Comment (smgv) [reply app/components/UI/SolanaNewFeatureContent/SolanaNewFeatureContent.tsx]: Yes, it's valid.

Comment (georgewrmarshall) [reply app/components/UI/SolanaNewFeatureContent/SolanaNewFeatureContent.tsx]: Ah you're just using `lightTheme` here my mistake! Yes, this would absolutely work.

**Review by ieow — APPROVED** [review]
lgtm

**Review by chaitanyapotti — APPROVED** [review]
