### PR TITLE
fix: update setSelectedAccount to set the account group

### LINKED ISSUE #20844: (mob)[Bug] When importing hw account, the latest account does not set to active
Build: v7.57.0 (2629)
Android

1. Add hardware wallet
2. Import 2x QR accounts
3. Verify the QR Account 2 is set to active

Expected: QR Account 2 is set to active
Actual: Existing account remains active

https://github.com/user-attachments/assets/1eaf8439-8649-4ef1-aa98-43c57c9d2435

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This PR updates `setSelectedAccount` to update the selected account group instead of only setting the selected internal account. 

## **Changelog**

CHANGELOG entry: Imported SRP and hardware wallets will now have their first account selected. 

## **Related issues**

Fixes: https://consensyssoftware.atlassian.net/browse/MUL-1218?atlOrigin=eyJpIjoiYjA4MjFiNDE4NjgzNDg5MTk1MzdhNzUyZWIwZDg5OGQiLCJwIjoiaiJ9

Fixes: https://github.com/MetaMask/metamask-mobile/issues/20844
 
## **Manual testing steps**

```gherkin
Feature: importing new srp

  Scenario: user imports a new srp
    Given has entered a valid srp in the import wallet screen.

    When user clicks import
    Then the srp is imported with its first account selected. 
```

### **After**

[mul-1218-after.webm](https://github.com/user-attachments/assets/b9cfb5e8-2e96-4f8e-9ab7-5120ee80b4b3)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Ensure the most recently unlocked hardware account is set as the selected address for QR and Ledger imports, with tests covering selection, errors, and navigation.
> 
> - **QR Hardware Connect (`app/components/Views/ConnectQRHardware`)**
>   - **Behavior**: After unlocking selected indices, capture the last added account and call `Engine.setSelectedAddress` with it.
>   - **Tests**: Add `ConnectQRHardware.test.tsx` covering multi/single account unlock, no-account case, error logging, and `navigation.pop(2)`.
> - **Ledger (`app/core/Ledger`)**
>   - **Behavior**: After `unlockLedgerWalletAccount`, call `Engine.setSelectedAddress` with the unlocked address.
>   - **Tests**: Update `Ledger.test.ts` to assert selected address is set after unlock and mock `setSelectedAddress`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 6684e3aefbc81a37a04a6ed035b0aa9c597e14c5. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/ConnectQRHardware/index.tsx [hunk 1]
```diff
@@ -195,12 +195,19 @@ const ConnectQRHardware = ({ navigation }: IConnectQRHardwareProps) => {
...
-            await keyring.addAccounts(1);
+            const [newAccount] = await keyring.addAccounts(1);
+            lastAccount = newAccount;
           }
+          return lastAccount;
         });
+
+        if (accountToSelect) {
+          Engine.setSelectedAddress(accountToSelect);
+        }
```
Comment (gantunesr) [inline app/components/Views/ConnectQRHardware/index.tsx:210]: Is this setting the correct account group? maybe we should update the docs for `setSelectedAccount` and `setSelectedAddress` in the Engine file

Comment (montelaidev) [reply app/components/Views/ConnectQRHardware/index.tsx:210]: This would trigger the account group selection too because the AccountTreeController listens to this event change

**Review by mathieuartu — APPROVED** [review]
