### PR TITLE
fix: Migrate Login view to use design system components (and fix blur error)

### LINKED ISSUE #10805: [Sentry] TypeError: null is not an object (evaluating 'this.inputRef.current.blur')
Sentry Issue: [METAMASK-MOBILE-2NQ9](https://metamask.sentry.io/issues/5714192897/?referrer=github_integration)

```
TypeError: null is not an object (evaluating 'this.inputRef.current.blur')
  at value (node_modules/rxjs/dist/cjs/internal/util/NotFoundError.js:11:4)
  at a (node_modules/react-redux/lib/utils/reactBatchedUpdates.native.js:11:44)
  at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:15)
  at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
  at u (node_modules/react-native/Libraries/Core/polyfillPromise.js:37:3)
...
(9 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by smilingkylan**
## **Description**

The purpose of this task is to fix an error that keeps occurring where a `TextField` ref is `null` when the `blur` method on it is executed. 

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/10805

## **Manual testing steps**

The best way to make sure this bug is fixed will be to check the error logs in Sentry.

## **Screenshots/Recordings**

n/a

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by brianacnguyen — DISMISSED** [review]

**Comment by brianacnguyen** [comment]
Can you provide a screenshot?

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
The keypad is now being displayed by default on the Login view.  This is causing a failure with spec `./e2e/specs/settings/delete-wallet.spec.js` trying to tap 'Reset Wallet' button link but it's now blocked by the keypad.

Can we adjust the changes on Login view to not show the keypad by default when navigating/loading Login view?  I have no clue what the exact change that is causing this.
[
Screenshot_1728340706
](url)

**Review by brianacnguyen — DISMISSED** [review]

File: app/component-library/components/Form/TextField/foundation/Input/Input.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ const Input: React.FC<InputProps> = ({
   isReadonly = false,
   onBlur,
   onFocus,
-  autoFocus = false,
+  autoFocus = true,
```
Comment (wachunei) [inline app/component-library/components/Form/TextField/foundation/Input/Input.tsx:24]: I have a concern with `true` being the default value: what is the behavior when there are more than 1 `Input` components with `autoFocus`?

Comment (kylanhurt) [reply app/component-library/components/Form/TextField/foundation/Input/Input.tsx:24]: That is a fair point. Thoughts, @brianacnguyen

Comment (kylanhurt) [reply app/component-library/components/Form/TextField/foundation/Input/Input.tsx:24]: @wachunei Now that I think of it, they were already autofocusing before so technically that shouldn't change any behavior

Comment (wachunei) [reply app/component-library/components/Form/TextField/foundation/Input/Input.tsx:24]: I'm seeing that in `TextField` the default is `false`, so the default `true` would only apply for `Input` components being directly used. https://github.com/MetaMask/metamask-mobile/blob/253449c5d066d772337af6d38b923a37b2f01c54/app/component-library/components/Form/TextField/TextField.tsx#L30

File: app/components/Views/Login/index.js [hunk 2]
```diff
@@ -564,41 +557,46 @@ class Login extends PureComponent {
...
+                  endAccessory={
                     <BiometryButton
                       onPress={this.tryBiometric}
                       hidden={shouldHideBiometricAccessoryButton}
                       biometryType={this.state.biometryType}
                     />
-                  )}
+                  }
                   keyboardAppearance={themeAppearance}
+                  autoFocus={false}
```
Comment (wachunei) [inline app/components/Views/Login/index.js:568]: This is not needed since the default is false already https://github.com/MetaMask/metamask-mobile/blob/253449c5d066d772337af6d38b923a37b2f01c54/app/component-library/components/Form/TextField/TextField.tsx#L30

File: app/component-library/components/Form/TextField/foundation/Input/Input.tsx (hunk 1 above)
Comment (wachunei) [reply app/component-library/components/Form/TextField/foundation/Input/Input.tsx:24]: > they were already autofocusing
oh right, the prop is set to true 😅

File: app/components/Views/Login/index.js (hunk 2 above)
Comment (kylanhurt) [reply app/components/Views/Login/index.js]: Removed!

**Comment by kylanhurt** [comment]
> Can you provide a screenshot?

Side by side comparison (before on left, after on right)
image

**Review by chrisleewilcox — APPROVED** [review]
LGTM

**Review by brianacnguyen — APPROVED** [review]
LGTM. Thank you for this!

**Review by Daniel-Cross — APPROVED** [review]

**Review by darkwing — APPROVED** [review]
Looks good!  Nice work!
