### PR TITLE
fix: cp-7.47.0 Replace commas when inputting numbers in `SnapUIInput`

### LINKED ISSUE #15682: [Bug]: Solana send flow iOS - typing amount results in Transaction simulation failed message, due to keyboard missing period symbol
### Describe the bug

When trying to send any SPL or SOL tokens:

- when typing `0,01` there is a transaction simulation failed warning and the continue button is greyed out

- when typing `0.01 `there is no issue.

Only present on iOS. Keyboard missing `.` symbol. error is caused by the `,` symbol

### Expected behavior

Similar to EVM accounts: be able to send when using keyboard symbol `,` in the amount field

### Screenshots/Recordings

https://github.com/user-attachments/assets/06c05628-d9f0-49ff-b581-5accaa822b80

### Steps to reproduce

1. Be on Solana network on iOS device
2. Click Send
3. Enter recipient 
4. Type any amount in the amount field (keyboard using `,` symbol)
5. Notice Transaction simulation failed message
6. Click on MAX button and edit the amount (now the amount has `.` symbol)
7. Notice no failed message 

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.47.0

### Build type

None

### Device

iphone 15

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by FrederikBolding**
## **Description**

Mimic the browser behavior of replacing commas with dots for increased Snaps platform compatibility between mobile and extension.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15682

## **Manual testing steps**

1. Go to the Solana send flow
2. Use the keyboard to input a comma
3. See that it is replaced by a dot

### CODE REVIEW

File: app/components/Snaps/SnapUIInput/SnapUIInput.tsx [hunk 1]
```diff
@@ -54,9 +56,20 @@ export const SnapUIInput = ({
     }
   }, [inputRef, name, focusedInput]);
 
+  const getInputValue = (text: string) => {
+    if (keyboardType === 'numeric') {
+      // Mimic browser behaviour where commas are replaced.
+      return text.replace(/,/g, ".");
```
Comment (Mrtenz) [inline app/components/Snaps/SnapUIInput/SnapUIInput.tsx:62]:
```suggestion
      return text.replaceAll(',', '.');
```

Comment (FrederikBolding) [reply app/components/Snaps/SnapUIInput/SnapUIInput.tsx:62]: Seemingly not allowed with the TS lib we use

**Review by Mrtenz — APPROVED** [review]

**Review by GuillaumeRx — COMMENTED** [review]
Working as intended ! LGTM

https://github.com/user-attachments/assets/bb7567ce-1a37-4429-ac0a-e15cd48e0b88

**Review by GuillaumeRx — APPROVED** [review]
