### PR TITLE
fix: private key scroll

### LINKED ISSUE #27192: [Bug]: Unable to scroll in Private key screen
### Describe the bug

On Android, scrolling on the Private Key screen is not possible unless using two finger scroll.

Unable to reproduce on Android.

### Expected behavior

Be able to scroll

### Screenshots/Recordings

https://github.com/user-attachments/assets/4484ae43-ce72-4973-9ef8-d4d56adf508a

### Steps to reproduce

1. Click Account
2. Click three dots menu
3. Click Private Keys
4. Enter password
5. Click continue
6. Scroll
7. Notice it's not possible
8. Scroll using two fingers gesture
9. Notice scrolling is possible

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

7.69.0

### Build number

3910

### Build type

None

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gantunesr**
## **Description**

Fix scroll in the "Private Key" list for Android devices

## **Changelog**

CHANGELOG entry: fix scroll in the "Private Key" list for Android devices

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/27192
Fixes: https://consensyssoftware.atlassian.net/browse/MUL-1552

## **Manual testing steps**

1. Use a device/emulator with small screen
2. Go to the private key list
3. Try to scroll without dismissing the bottom sheet

### **Before**

Check https://github.com/MetaMask/metamask-mobile/issues/27192

### **After**

https://github.com/user-attachments/assets/d1b9c4a7-1005-4b32-b19c-258b440dd54f

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I've included tests if applicable
- [ ] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Touches shared `BottomSheet`/`BottomSheetDialog` gesture handling by forwarding arbitrary `PanGestureHandler` props, which could subtly change swipe-to-dismiss behavior across consumers (especially on Android). Changes are localized but affect a common UI primitive.
> 
> **Overview**
> Fixes Android scrolling in the Private Key list bottom sheet by allowing callers to pass `PanGestureHandler` configuration down into `BottomSheetDialog` and wiring `PrivateKeyList` to use `simultaneousHandlers` with the list’s RNGH `ScrollView` ref so scroll gestures don’t trigger sheet dismissal.
> 
> Updates/extends tests to cover the new `panGestureHandlerProps` plumbing and adds broader `PrivateKeyList` behavior assertions (error reset, banner content, cancel navigation, SOL-only filtering, and Android-specific rendering).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit f72fa253ffb8a9bd5785629869118d826af46dcd. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.tsx [hunk 1]
```diff
@@ -239,6 +240,7 @@ const BottomSheetDialog = forwardRef<
         <PanGestureHandler
           enabled={isInteractable}
           onGestureEvent={gestureHandler}
+          simultaneousHandlers={simultaneousHandlers}
```
Comment (georgewrmarshall) [inline app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.tsx]: Could we change this to a prop object that allows access to the child `PanGestureHandler` component? That way engineers will have access to all available PanGestureHandler props instead of just `simultaneousHandlers`

```suggestion
         ...panGestureHandlerProps
```

File: app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.tsx [hunk 2]
```diff
@@ -59,6 +59,7 @@ const BottomSheetDialog = forwardRef<
       keyboardAvoidingViewEnabled = true,
       onClose,
       onOpen,
+      simultaneousHandlers,
```
Comment (georgewrmarshall) [inline app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.tsx]:
```suggestion
      panGestureHandlerProps,
```

File: app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.test.tsx [hunk 3]
```diff
@@ -110,4 +110,46 @@ describe('BottomSheetDialog', () => {
...
+  describe('simultaneousHandlers', () => {
+    it('accepts a single ref as simultaneousHandlers without error', () => {
+      const handler = React.createRef<unknown>();
+      const { getByText } = render(
+        <BottomSheetDialog simultaneousHandlers={handler}>
+          <Text>Test Child</Text>
+        </BottomSheetDialog>,
+      );
+      expect(getByText('Test Child')).toBeOnTheScreen();
+    });
```
Comment (georgewrmarshall) [inline app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.test.tsx]: If we change to the prop object can we simplify these tests to asserting that a test id exists?

```suggestion
    it('passes props to the PanGestureHandler via panGestureHandlerProps', () => {

      const { getByTestId } = render(
        <BottomSheetDialog panGestureHandlerProps={{testID: 'pan-gesture-handler'}}>
          <Text>Test Child</Text>
        </BottomSheetDialog>,
      );
      expect(getByTestId('pan-gesture-handler')).toBeOnTheScreen();
    });
```

File: app/component-library/components/BottomSheets/BottomSheet/BottomSheet.tsx [hunk 4]
```diff
@@ -42,6 +42,7 @@ const BottomSheet = forwardRef<BottomSheetRef, BottomSheetProps>(
       shouldNavigateBack = true,
       isFullscreen = false,
       keyboardAvoidingViewEnabled = true,
+      simultaneousHandlers,
```
Comment (georgewrmarshall) [inline app/component-library/components/BottomSheets/BottomSheet/BottomSheet.tsx]:
```suggestion
      panGestureHandlerProps,
```

File: app/component-library/components/BottomSheets/BottomSheet/BottomSheet.tsx [hunk 5]
```diff
@@ -157,6 +158,7 @@ const BottomSheet = forwardRef<BottomSheetRef, BottomSheetProps>(
           isFullscreen={isFullscreen}
           style={style}
           keyboardAvoidingViewEnabled={keyboardAvoidingViewEnabled}
+          simultaneousHandlers={simultaneousHandlers}
```
Comment (georgewrmarshall) [inline app/component-library/components/BottomSheets/BottomSheet/BottomSheet.tsx]:
```suggestion
          ...panGestureHandlerProps
```

File: app/components/Views/MultichainAccounts/PrivateKeyList/PrivateKeyList.tsx [hunk 6]
```diff
@@ -301,20 +357,30 @@ export const PrivateKeyList = () => {
...
-          style={styles.banner}
-          testID={PrivateKeyListIds.BANNER}
-        />
+    <GestureScrollRefContext.Provider value={flashListScrollGestureRef}>
+      <BottomSheet
+        style={styles.bottomSheetContent}
+        ref={sheetRef}
+        simultaneousHandlers={
+          Platform.OS === 'android' ? flashListScrollGestureRef : undefined
+        }
```
Comment (georgewrmarshall) [inline app/components/Views/MultichainAccounts/PrivateKeyList/PrivateKeyList.tsx]: Update to use prop object 

```suggestion
        panGestureHandlerProps={{
          simultaneousHandlers: Platform.OS === 'android' ? flashListScrollGestureRef : undefined
        }}
```

**Review by georgewrmarshall — COMMENTED** [review]
Hey @gantunesr, thanks for extending the functionality of the BottomSheetDialog. I was wondering if we can make this somewhat more future proofed to allow for all `PanGestureHandler` props via a prop object? Some of my code suggestions may be sudo-code and need formatting or testing.

@MetaMask/design-system-engineers we will need to do this to the MMDS version as well

File: app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.tsx (hunk 1 above)
Comment (gantunesr) [reply app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.tsx]: Done in https://github.com/MetaMask/metamask-mobile/pull/27891/commits/582346452cb05faf07952eeb8e58fc364e657964

File: app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.tsx (hunk 2 above)
Comment (gantunesr) [reply app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.tsx]: Done in https://github.com/MetaMask/metamask-mobile/pull/27891/commits/582346452cb05faf07952eeb8e58fc364e657964

File: app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.test.tsx (hunk 3 above)
Comment (gantunesr) [reply app/component-library/components/BottomSheets/BottomSheet/foundation/BottomSheetDialog/BottomSheetDialog.test.tsx]: Done in https://github.com/MetaMask/metamask-mobile/pull/27891/commits/582346452cb05faf07952eeb8e58fc364e657964

File: app/component-library/components/BottomSheets/BottomSheet/BottomSheet.tsx (hunk 4 above)
Comment (gantunesr) [reply app/component-library/components/BottomSheets/BottomSheet/BottomSheet.tsx]: Done in https://github.com/MetaMask/metamask-mobile/pull/27891/commits/582346452cb05faf07952eeb8e58fc364e657964

File: app/component-library/components/BottomSheets/BottomSheet/BottomSheet.tsx (hunk 5 above)
Comment (gantunesr) [reply app/component-library/components/BottomSheets/BottomSheet/BottomSheet.tsx]: Done in https://github.com/MetaMask/metamask-mobile/pull/27891/commits/582346452cb05faf07952eeb8e58fc364e657964

File: app/components/Views/MultichainAccounts/PrivateKeyList/PrivateKeyList.tsx (hunk 6 above)
Comment (gantunesr) [reply app/components/Views/MultichainAccounts/PrivateKeyList/PrivateKeyList.tsx]: Done in https://github.com/MetaMask/metamask-mobile/pull/27891/commits/582346452cb05faf07952eeb8e58fc364e657964

**Review by mathieuartu — APPROVED** [review]
Looks good, haven't tested

**Review by georgewrmarshall — APPROVED** [review]
LGTM! Approving on behalf of @MetaMask/design-system-engineers 

Created same PR in MMDS
- https://github.com/MetaMask/metamask-mobile/pull/27891
