### PR TITLE
Fix ENS name displayed on confirm send page

### LINKED ISSUE #6330: [Bug] ENS domain not displayed on the Confirmation screen
**Describe the bug**
Whenever we perform a Send to an ENS domain, we can see how when we land on the last Confirmation screen, only the recipient address is displayed but not the ENS domain.
 
**Screenshots**

[Screencast from 04-05-23 12:20:29.webm](https://user-images.githubusercontent.com/54408225/236177795-c4baa6eb-48af-4862-bc13-57a36a0872cf.webm)

**To Reproduce**
_Steps to reproduce the behavior_
1. Select Main network
2. Click Send
3. Add an ENS domain : `seaona.eth`
4. Click Next
5. Add amount
6. Proceed
7. See how only recipient address is displayed

**Expected behavior**
We should see the ENS domain as well as the address below, like we did before:

Screenshot from 2023-05-04 12-20-01

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS:  android
 - App Version: `6.6`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by jpuri**
Fixes: #6330

Show ENS name of to address in confirmation page.

QA Steps:
- start a send transaction on mainnet
- enter an ens address, go to next page
- enter amount, go to confirm page
- ***ENS name*** of to address should be visible

### CODE REVIEW

File: app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx [hunk 1]
```diff
@@ -66,11 +66,15 @@ const AccountFromToInfoCard = (props: AccountFromToInfoCardProps) => {
...
+      const fromEns = await doENSReverseLookup(fromAddress, network);
+      if (fromEns) {
+        setFromAccountName(fromEns);
+      } else {
+        const { name: fromName } = identities[fromAddress];
+        setFromAccountName(fromName);
+      }
     })();
-  }, [fromAddress, identities, transactionFromName]);
+  }, [fromAddress, identities, transactionFromName, network]);
```
Comment (digiwand) [inline app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx:77]: 👍

**Review by digiwand — DISMISSED** [review]

**Review by blackdevelopa — DISMISSED** [review]

**Comment by seaona** [comment]
I can see the ENS name on the confirmations page now. Looks good to be merged :100: @jpuri 

image

**Review by blackdevelopa — APPROVED** [review]
