### PR TITLE
fix: deprecate legacy swaps

### LINKED ISSUE #20813: [Bug]: Cannot read property 'address' of undefined
### Describe the bug

Sentry has started logging a new type of error with the latest release that we need to look into in case it has a greater impact:

https://metamask.sentry.io/issues/6920102055/?notification_uuid=d81ecee9-1b7b-4b0e-b739-84877fa797be&project=2299799&referrer=assigned_activity-email

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

Not persistent, Sentry logs provide more details

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.56.1

### Build type

None

### Device

iPhone 13

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by bfullam**
## **Description**
**Problem**
Attempting to open swaps while on an unsupported network (sepolia, etc.) was falling back to legacy swaps and causing the app to crash. Additionally, LD was failing to load on occasion, resulting in showing legacy bridge buttons/routes incorrectly.

**Solution**
Completely deprecated legacy swaps and now we always show unified swaps. If a network doesn't support swaps, clicking the home page swaps button will fallback to an ETH > mUSD swap on Ethereum mainnet.

## **Changelog**

CHANGELOG entry: Fixed bug that was causing swaps to crash on unsupported networks

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/20813, https://github.com/MetaMask/metamask-mobile/issues/19261

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

https://github.com/user-attachments/assets/234bca4a-943f-4581-8c2c-0771cd6bf3fd

### **After**

https://github.com/user-attachments/assets/d09c6303-30e4-41eb-8bc8-9f392c1ceb3b

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Removes legacy swaps and bridge button, simplifies navigation to always open the unified Bridge view for swaps, updates bridge selectors/utils, and cleans up related env flags, tests, and stories.
> 
> - **Trade/Navigation**:
>   - Replace legacy Swaps flow with unified Bridge navigation in `useSwapBridgeNavigation`; always open `Bridge/BridgeView` (Unified mode); remove legacy network switching and portfolio bridge fallbacks.
>   - Update consumers (`AssetOverview`, `Wallet`, `UrlAutocomplete`, Card `useOpenSwaps`) to call `goToSwaps` (no args) and navigate to Bridge.
> - **UI**:
>   - Remove `displayBridgeButton` and `goToBridge` from `AssetDetailsActions` and its usages/stories; drop Bridge button from asset actions.
>   - Adjust tests/snapshots to expect Bridge navigation and no Bridge button.
> - **State/Selectors**:
>   - Add `selectIsBridgeEnabledSourceFactory`; refactor selectors; remove `isUnifiedSwapsEnvVarEnabled` usage.
>   - Simplify `hasMinimumRequiredVersion` (drops env var param) and related tests.
> - **BridgeView**:
>   - Streamline confirm flow/button and quote handling (tests now use `bridge-confirm-button`).
> - **CI/Config**:
>   - Remove legacy `MM_UNIFIED_SWAPS_ENABLED`/`MM_BRIDGE_ENABLED` from workflows and `.js.env.example`.
> - **Tests**:
>   - Broad updates across unit/E2E mocks and snapshots to align with unified swaps behavior.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit d11a4cf29095c33a3cc46934fc73ad36a9ce1d8f. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by SteP-n-s — DISMISSED** [review]

**Review by christopherferreira9 — DISMISSED** [review]

**Review by bergarces — DISMISSED** [review]

**Review by Brunonascdev — DISMISSED** [review]

File: app/components/UI/Card/hooks/useOpenSwaps.ts [hunk 1]
```diff
@@ -70,7 +70,7 @@ export const useOpenSwaps = ({
       dispatch(setDestToken(destToken));
 
       const navigate = () => {
-        goToSwaps(sourceToken);
```
Comment (tommasini) [inline app/components/UI/Card/hooks/useOpenSwaps.ts:73]: This will not break a deeplink with source token for example?

**Review by tommasini — DISMISSED** [review]

**Review by tommasini — APPROVED** [review]

**Review by bergarces — APPROVED** [review]

**Review by christopherferreira9 — APPROVED** [review]

**Review by Brunonascdev — APPROVED** [review]

**Review by SteP-n-s — APPROVED** [review]
