### PR TITLE
Fix: bip 44 bugs

### LINKED ISSUE #19870: [Bug]: Scam token warning is shown for Ethereum
### Describe the bug

When testing the nightly experimental build (2450) under BIP44, Eth token is shown as a scam token on the home page. I believe this is because the current selected network is Solana which is confusing this logic. 

### Expected behavior

Eth, and other native assets should not be rendered as a scam token.

### Screenshots/Recordings

https://github.com/user-attachments/assets/dc90bde4-7e8c-4ad7-9201-072275fa5107

### Steps to reproduce

- download the nightly experimental build 2450
- import a wallet with eth
- go to the browser and navigate to jup.ag
- notice that the current network is solana
- navigate back to the home page
- notice the warning icon rendered beside eth
- click the warning icon
- notice the scam modal

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

7.57.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Pixel 6

### Operating system

Android

### Additional context

- experimental nightly build 2450

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

This PR addresses the following issues:
	•	Inconsistencies in the network manager
	•	Slow token list loading when switching to the token tab
	•	Infinite loading of DeFi positions
	•	Bugs when clicking between tabs

## **Changelog**

CHANGELOG entry: fix bip-44 bugs

## **Related issues**

Fixes: #19870 #19869  #19866 

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Nav/Main/index.js [hunk 1]
```diff
@@ -314,24 +314,6 @@ const Main = (props) => {
       ) {
         selectNetwork(chainId);
       }
-      toastRef?.current?.showToast({
```
Comment (Prithpal-Sooriya) [inline app/components/Nav/Main/index.js:317]: Should we remove the toast?

File: app/components/UI/Tokens/index.tsx [hunk 2]
```diff
@@ -54,19 +63,95 @@ const Tokens = memo(() => {
...
+      () =>
+        isMultichainAccountsState2Enabled
+          ? selectSortedAssetsBySelectedAccountGroup
+          : selectSortedTokenKeys,
+      [isMultichainAccountsState2Enabled],
+    ),
   );
 
+  // High-performance async rendering with progressive loading
+  useEffect(() => {
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Tokens/index.tsx:94]: This is interesting, let's discuss tomorrow

File: app/components/UI/shared/BaseControlBar/BaseControlBar.tsx [hunk 3]
```diff
@@ -107,6 +115,21 @@ const BaseControlBar: React.FC<BaseControlBarProps> = ({
 
   const currentNetworkName = getNetworkInfo(0)?.networkName;
 
+  useEffect(() => {
```
Comment (Prithpal-Sooriya) [inline app/components/UI/shared/BaseControlBar/BaseControlBar.tsx:118]: Might need an explanation on this effect

**Review by Prithpal-Sooriya — APPROVED** [review]
