### PR TITLE
Swaps: fix Use Max by adding `fromTokenMinimalUnitString`

### LINKED ISSUE #2206: Number utils
Some number utils are behaving incorrectly, generating loose if precision

- `fromTokenMinimalUnit` shouldn't convert the input to Number, instead we should treat numbers in string at least in these methods
- any other number utils should do it, we need a sanity check

### PR DESCRIPTION
**Pull request by wachunei**
**Description**

This PR adds a working function to parse minimal units into token format depending on the decimal places of the currency. This makes <kbd>Use Max</kbd> work as expected.

* **Previous wrong behavior**, present in Send Flow (notice balance on the left and value on the right don't match) 
image

* **Swaps behavior (values match)**
image

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2206

### CODE REVIEW

File: app/util/number.js [hunk 1]
```diff
@@ -57,6 +58,31 @@ export function fromTokenMinimalUnit(minimalInput, decimals) {
...
+ */
+export function fromTokenMinimalUnitString(minimalInput, decimals) {
+	if (typeof minimalInput !== 'string') {
+		throw new TypeError('minimalInput must be a string');
+	}
+
+	const tokenFormat = ethersUtils.formatUnits(minimalInput, decimals);
+	const isInteger = Boolean(INTEGER_REGEX.exec(tokenFormat));
+
+	// eslint-disable-next-line prefer-const
```
Comment (rickycodes) [inline app/util/number.js:78]: why the eslint-disable? can this not just be `const`?

**Review by rickycodes — APPROVED** [review]
LGTM

File: app/util/number.js (hunk 1 above)
Comment (wachunei) [reply app/util/number.js]: Good catch, I carried it over from a refactor 😅
