### PR TITLE
fix(bridge): fix: cp-7.47.3 prevent crash when viewing Solana asset details

### LINKED ISSUE #16734: [Bug]: App crashes when selecting asset detail info from swap token list for solana swaps
### Describe the bug

In the Solana swap flow, when a user taps the Asset Detail Info icon (ⓘ) from the Swap Token List, the app crashes immediately. This behavior is observed in both production and RC builds.

### Expected behavior

The app should navigate to the Asset Detail Page of the selected Solana token

### Screenshots/Recordings

https://github.com/user-attachments/assets/1c09a9cc-98a6-4998-bd94-7371419947b7

Image

### Steps to reproduce

	1.	Launch MetaMask Mobile (7.47.1 or 7.50.0 (2031))
	2.	Initiate a Solana Swap
	3.	Tap the token selector to bring up the token list
	4.	Tap the ⓘ (info icon) next to any token

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.47.1

### Build type

None

### Device

iPhone 16 Pro

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by amitabh94**
## **Description**

Fixes a crash that occurs when viewing asset details for Solana tokens in the Bridge flow. The issue was caused by `getTokenDetails` assuming all non-EVM asset addresses are already in CAIP format, when the Bridge API sometimes returns raw Solana addresses.

## **Related issues**

Fixes #16734
Fixes [SWAPS-2525](https://consensyssoftware.atlassian.net/browse/SWAPS-2525)

## **Manual testing steps**

1. Navigate to Bridge feature
2. Select Solana as source or destination chain
3. Select any Solana token from the token list
4. Tap on the asset detail info button
5. Verify the asset details screen loads without crashing
6. Verify contract address and other details display correctly

## **Screenshots/Recordings**

**Before:**

https://github.com/user-attachments/assets/cf41e9fa-ae3d-4336-aefe-40017e831364

**After:**

https://github.com/user-attachments/assets/ccacf57e-1971-42c4-a3d7-a3978e7c954b

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md)
- [x] I've clearly explained what problem this PR solves
- [x] I've linked the issue that this PR fixes
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I've added unit tests if applicable

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed)
- [ ] I confirm that this PR addresses the issue linked above
- [ ] I've checked that all unit tests pass

### **Root Cause**

The `getTokenDetails` function was calling `parseCaipAssetType` directly on `asset.address` for non-EVM assets, assuming it was already in CAIP format. However, the Bridge API sometimes returns raw Solana addresses instead of CAIP-formatted addresses, causing `parseCaipAssetType` to throw an error.

### **Fix Applied**

Implemented the same defensive approach used in `useTokenHistoricalPrices`:

```typescript
// Detect if address is already in CAIP format
const isCaipAssetType = asset.address.startsWith(`${asset.chainId}`);

// Convert to CAIP format if needed
const normalizedCaipAssetTypeAddress = isCaipAssetType
  ? asset.address
  : `${asset.chainId}/token:${asset.address}`;
```

### **Benefits**

- ✅ **Fixes crash**: Solana asset details now load without errors
- ✅ **Backward compatible**: Handles both raw and CAIP format addresses
- ✅ **Consistent pattern**: Uses same approach as `useTokenHistoricalPrices`
- ✅ **Zero breaking changes**: All existing functionality preserved
- ✅ **Future-proof**: Works with any non-EVM chain automatically

### **Testing**

- Added comprehensive unit tests covering both scenarios
- All 12 tests pass including new test cases
- Verified with existing Bridge test suite
- Manual testing confirms crash is resolved

[SWAPS-2525]: https://consensyssoftware.atlassian.net/browse/SWAPS-2525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: app/components/UI/AssetOverview/utils/getTokenDetails.ts [hunk 1]
```diff
@@ -10,8 +10,16 @@ export const getTokenDetails = (
   tokenMetadata: Record<string, string | number | string[]>,
 ): TokenDetails => {
   if (isNonEvmAsset) {
+    // Use the same approach as useTokenHistoricalPrices
+    const isCaipAssetType = asset.address.startsWith(`${asset.chainId}`);
+
+    // Ensure we have proper CAIP format address for parsing
+    const normalizedCaipAssetTypeAddress = isCaipAssetType
+      ? asset.address
+      : `${asset.chainId}/token:${asset.address}`;
```
Comment (Prithpal-Sooriya) [inline app/components/UI/AssetOverview/utils/getTokenDetails.ts:19]: Very nice. I feel like this should be a util (lets do this separately)

**Review by Prithpal-Sooriya — APPROVED** [review]

File: app/components/UI/AssetOverview/utils/getTokenDetails.ts [hunk 2]
```diff
@@ -10,8 +10,16 @@ export const getTokenDetails = (
   tokenMetadata: Record<string, string | number | string[]>,
 ): TokenDetails => {
   if (isNonEvmAsset) {
+    // Use the same approach as useTokenHistoricalPrices
```
Comment (Prithpal-Sooriya) [inline app/components/UI/AssetOverview/utils/getTokenDetails.ts:13]: Adding a comment for PR visibility. This is required as currently we can't really trust that our address provided is a CAIP address.

This will be resolved when:
1. We move our existing EVM addresses to CAIP.
2. The data we use from our APIs are CAIP.

File: app/components/UI/AssetOverview/utils/getTokenDetails.ts (hunk 1 above)
Comment (amitabh94) [reply app/components/UI/AssetOverview/utils/getTokenDetails.ts:19]: I agree!
