### PR TITLE
fix: you have to press the login button twice (#6633)

### LINKED ISSUE #6633: You have to press the login button twice.
**Describe the bug**
On the login page, if the cursor is in the password entry box the "LOG IN" button doesn't work.  You have to first get the cursor out of the password entry box before you can press the LOG IN button.

**To Reproduce**
_Steps to reproduce the behavior_
1. Open MetaMask Mobile on Android.
2. Enter a password.
3. Touch LOG IN button.
4. Notice that nothing visible happens other than the cursor stops flashing in the password entry box.
5. Touch LOG IN button again.
6. Notice that you now log in.

**Expected behavior**
Upon entering my password, I can touch the log in button once and log in.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 9
 - App Version: 6.6.0 (1114)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by tibi77**
**Description**

When a user wants to login into the wallet they need to press the login button twice. The issue comes from the way that the Scrollview component is behaving when input is active.

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**
Fix: #6633 

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

File: app/components/Views/Login/index.js [hunk 1]
```diff
@@ -521,8 +521,9 @@ class Login extends PureComponent {
       <ErrorBoundary navigation={this.props.navigation} view="Login">
         <SafeAreaView style={styles.mainWrapper}>
           <KeyboardAwareScrollView
-            style={styles.wrapper}
+            keyboardShouldPersistTaps="handled"
```
Comment (tibi77) [inline app/components/Views/Login/index.js:524]: maybe we want to manually dismiss the keyboard when we press the button... I d not really like that behaviour as if you did mistyped your password you have to retype inside the input field

**Review by tommasini — DISMISSED** [review]
Thanks for the contribution @tibi77! LGTM!

**Comment by hesterbruikman** [comment]
@tibi77 Added a `Needs QA` label, please stay tuned for QA feedback. I think it'll be good to do a quick check on physical device (Android + iOS)

File: app/components/Views/Login/index.js (hunk 1 above)
Comment (leotm) [reply app/components/Views/Login/index.js:527]: for the best of both worlds, we could call `Keyboard.dismiss` on/after successful login
(before navigation with no need for additional listeners) https://github.com/MetaMask/metamask-mobile/pull/6663/commits/df40da44338b22d005b35842e0aa4c5a51a6cf93

https://github.com/MetaMask/metamask-mobile/assets/1881059/bcb51dd7-9fab-426d-b588-8171ff1bef59

what do you think?

Comment (leotm) [reply app/components/Views/Login/index.js:527]: cc @tommasini feel free to revert the change if not
as there's the possibility it could be considered janky

**Review by leotm — DISMISSED** [review]
(see: https://github.com/MetaMask/metamask-mobile/pull/6663#pullrequestreview-1491724380)

edit: added `Fix: ` prefix in description to auto-close your linked issue @tibi77 thx again

File: app/components/Views/Login/index.js (hunk 1 above)
Comment (tommasini) [reply app/components/Views/Login/index.js:527]: This change looks good to me, thanks for bringing this up @leotm

**Review by tommasini — DISMISSED** [review]
LGTM with the latest [commit](https://github.com/MetaMask/metamask-mobile/commit/df40da44338b22d005b35842e0aa4c5a51a6cf93)

**Comment by tibi77** [comment]
So I can merge it @leotm ? 
My first contribution to this repo, not sure how it goes :D

**Comment by tibi77** [comment]
@leotm could you approve the workflow so we can merge this

**Comment by cortisiko** [comment]
@tibi77 can you test this PR and provide recording details of what was tested?

**Comment by hesterbruikman** [comment]
@tibi77 bumping @cortisiko's [comment](https://github.com/MetaMask/metamask-mobile/pull/6663#issuecomment-1714380327), would love to see this included, but we'd need a recording of testing before this can be merged

**Comment by tibi77** [comment]
@hesterbruikman just saw this
recording now

**Comment by tibi77** [comment]
https://github.com/MetaMask/metamask-mobile/assets/8665054/6bd603f9-0d9d-4ad7-8aed-83962ac71707

The issue was that the button for login/unlock had to be pressed twice, now, with this change you need to press the button only once
The reason that this bug happened was that the keyboard aware scroll swallows the click event and the button does not get that event, so, to fix it, we remove the event handling from the keyboard and we closed the Keyboard manually.

**Comment by tommasini** [comment]
Hey @tibi77, could you solve the conflicts? Our team is on the way to review/test this implementation! Thanks for the contribution!

File: app/components/Views/Login/index.js [hunk 2]
```diff
@@ -3,6 +3,8 @@ import PropTypes from 'prop-types';
 import {
   Alert,
   ActivityIndicator,
+  Keyboard,
+  Text,
```
Comment (tibi77) [inline app/components/Views/Login/index.js:7]: this needs to be removed
```suggestion
```

**Comment by tibi77** [comment]
@tommasini @leotm solved the conflicts, and requested the review again

**Review by tommasini — APPROVED** [review]
LGTM!

**Comment by hesterbruikman** [comment]
You're ready to merge @tibi77 ! Thanks so much for your contribution and patience! Looking forward to see this improvement in the app

**Comment by leotm** [comment]
@sethkfman can you see why GH's still expecting/waiting on the status of the final SonarCloud check?
even tho [summary](https://github.com/MetaMask/metamask-mobile/actions/runs/7034852836) shows a pass and the job's marked [complete](https://github.com/MetaMask/metamask-mobile/actions/runs/7034852836/job/19144987213?pr=6663) after we skip it (same after re-runs)

Screenshot 2023-11-29 at 3 56 23 pm

remembering from recent [sonar](https://github.com/MetaMask/metamask-mobile/pulls?q=sonar) PRs we skipped it for ext contributors in https://github.com/MetaMask/metamask-mobile/pull/7086
but still got [couple](https://github.com/MetaMask/metamask-mobile/pulls?q=is%3Apr+is%3Aopen+label%3Aexternal-contributor) more PRs hanging about on this step

tried manually merging via command line but ofc our branch protection doesn't allow

**Comment by tibi77** [comment]
@leotm I still see sonar not passing... what would be the next steps to solve this?

**Comment by hesterbruikman** [comment]
cc @frankvonhoven

**Comment by tibi77** [comment]
it seems that we have just Bitrise failing, but it looks like it fails from the get go

**Comment by sethkfman** [comment]
This PR looks good we are merging into a temp branch were E2E testing can be run for final validation.
