### PR TITLE
fix: google login fallback in android if no google account available on device.

### LINKED ISSUE #22766: [Bug]: App should fallback to the device’s default browser for Google account login when no existing Google account session is detected.
### Describe the bug

When attempting to log in with a Google account, the app does not correctly fallback to the device’s default browser if no existing Google account session is available on the device.

The app does not fallback to the browser and instead remains stuck on the in-app Google login flow (or fails to proceed), preventing the user from logging in.

### Expected behavior

If no Google session exists on the device, the app should automatically fallback to the device’s default browser to complete the Google OAuth login.

### Screenshots/Recordings

https://github.com/user-attachments/assets/0c46a449-1202-425a-8951-599445b19f4d

### Steps to reproduce

1. Install and open the app on a device that does not have any Google accounts logged in.
2. Navigate to the Login screen.
3. Select “Continue with Google”.
4. Observe the login flow.

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.60.0

### Build type

Beta

### Device

All device

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by grvgoel81**
## **Description**
* fix: google login fallback in android if no google account available on device.
* Jira: https://consensyssoftware.atlassian.net/browse/SL-351
* Github Issue: https://github.com/MetaMask/metamask-mobile/issues/22766

## **Changelog**

CHANGELOG entry: fix: google login fallback in android if no google account available on device.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/22766

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

https://github.com/user-attachments/assets/c3d4f0fb-187d-4daf-839a-6dd80e539fe9

### **After**

https://github.com/user-attachments/assets/9b7bb0bf-8251-4808-8e02-c56ec191a518

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Adds a browser-based Google login fallback on Android when ACM has no credentials, refactors Google handlers with a shared base, and updates onboarding to use the fallback path.
> 
> - **OAuth Handlers**:
>   - **Android Google Fallback**: Introduces `AndroidGoogleFallbackLoginHandler` (browser/PKCE flow) and `AndroidGoogleRedirectUri` (universal link) in `constants`.
>   - **Shared Google Logic**: Adds `BaseGoogleLoginHandler` used by `IosGoogleLoginHandler` and Android fallback; updates error messages and token request shaping.
>   - **Factory**: `createLoginHandler(os, provider, fallback?)` supports Android Google fallback; uses universal redirect for fallback.
>   - **Types**: `OAuthService.handleSeedlessAuthenticate` now uses `SeedlessAuthConnection`.
> - **Onboarding Flow**:
>   - On Android Google errors `GoogleLoginNoCredential`/`GoogleLoginNoMatchingCredential`, attempts browser fallback instead of showing error sheet; maintains loading state and success navigation (e.g., `ChoosePassword`).
> - **Tests**:
>   - Adds unit tests for Android Google fallback handler and factory fallback behavior.
>   - Updates onboarding tests to verify fallback attempts, silent handling on failure, and success navigation.
>   - Minor test message tweaks and selector test type import adjustments.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit a463787a0a32e03da0bcf2c96fb052adc1e6919f. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/core/OAuthService/OAuthLoginHandlers/shared/GoogleLoginHandler.ts [hunk 1]
```diff
@@ -0,0 +1,141 @@
+import {
```
Comment (ieow) [inline app/core/OAuthService/OAuthLoginHandlers/shared/GoogleLoginHandler.ts:1]: do not abstract the code
keep it separate for iosGoogle and android google fallback

File: app/core/OAuthService/OAuthLoginHandlers/constants.ts [hunk 2]
```diff
@@ -96,6 +102,11 @@ export const AuthConnectionConfig: Record<
       groupedAuthConnectionId:
         CURRENT_OAUTH_CONFIG.GOOGLE_GROUPED_AUTH_CONNECTION_ID,
     },
+    [AuthConnection.GoogleFallback]: {
```
Comment (ieow) [inline app/core/OAuthService/OAuthLoginHandlers/constants.ts]: Ios do not have GoogleFallback

File: app/core/OAuthService/OAuthInterface.ts [hunk 3]
```diff
@@ -14,6 +14,7 @@ export interface HandleOAuthLoginResult {
 
 export enum AuthConnection {
   Google = 'google',
+  GoogleFallback = 'google-fallback',
```
Comment (ieow) [inline app/core/OAuthService/OAuthInterface.ts]: do not create new google-fallback AuthConnection
this is used by ui to display logo
there are not google-fallback logo

File: app/selectors/seedlessOnboardingController.test.ts [hunk 4]
```diff
@@ -69,7 +72,7 @@ describe('Seedless Onboarding Controller Selectors', () => {
     it('returns authConnection when it exists', () => {
       const mockAuthConnection = AuthConnection.Google;
       const mockState = createMockState({
-        authConnection: mockAuthConnection,
+        authConnection: mockAuthConnection as SeedlessAuthConnection,
```
Comment (ieow) [inline app/selectors/seedlessOnboardingController.test.ts]: do not cast `as`

File: app/core/OAuthService/OAuthLoginHandlers/shared/GoogleLoginHandler.ts (hunk 1 above)
Comment (grvgoel81) [reply app/core/OAuthService/OAuthLoginHandlers/shared/GoogleLoginHandler.ts:1]: Sonar is complaining about code duplicacy that's why

File: app/core/OAuthService/OAuthLoginHandlers/index.ts [hunk 5]
```diff
@@ -62,11 +66,18 @@ export function createLoginHandler(
...
+                clientId: AndroidGoogleWebGID,
+                redirectUri: AndroidGoogleRedirectUri,
+                authServerUrl: AuthServerUrl,
+                web3AuthNetwork,
+              })
+            : new AndroidGoogleLoginHandler({
+                clientId: AndroidGoogleWebGID,
+                authServerUrl: AuthServerUrl,
+                web3AuthNetwork,
+              });
```
Comment (ieow) [inline app/core/OAuthService/OAuthLoginHandlers/index.ts:80]: remove googlefallback case

File: app/core/OAuthService/OAuthLoginHandlers/index.ts [hunk 6]
```diff
@@ -62,11 +66,18 @@ export function createLoginHandler(
...
-          });
+          return fallback
+            ? new AndroidGoogleFallbackLoginHandler({
+                clientId: AndroidGoogleWebGID,
+                redirectUri: AndroidGoogleRedirectUri,
+                authServerUrl: AuthServerUrl,
+                web3AuthNetwork,
+              })
+            : new AndroidGoogleLoginHandler({
+                clientId: AndroidGoogleWebGID,
```
Comment (ieow) [inline app/core/OAuthService/OAuthLoginHandlers/index.ts:77]: redirectUri is not needed for AndroidGoogleLoginHandler

File: app/core/OAuthService/OAuthService.ts [hunk 7]
```diff
@@ -139,7 +142,7 @@ export class OAuthService {
       const result =
         await Engine.context.SeedlessOnboardingController.authenticate({
           idTokens: [data.id_token],
-          authConnection,
+          authConnection: authConnection as SeedlessAuthConnection,
```
Comment (ieow) [inline app/core/OAuthService/OAuthService.ts]: cast is not needed

File: app/components/Views/Onboarding/index.tsx [hunk 8]
```diff
@@ -625,24 +651,25 @@ const Onboarding = () => {
...
         const loginHandler = createLoginHandler(Platform.OS, provider);
-        const result = await OAuthLoginService.handleOAuthLogin(
-          loginHandler,
-          !createWallet,
-        ).catch((error: Error) => {
+        try {
+          const result = await OAuthLoginService.handleOAuthLogin(
+            loginHandler,
+            !createWallet,
+          );
```
Comment (ieow) [inline app/components/Views/Onboarding/index.tsx:668]: should catch and handle the fallback here instead in the handleLoginError

File: app/selectors/seedlessOnboardingController.test.ts [hunk 9]
```diff
@@ -67,7 +69,7 @@ describe('Seedless Onboarding Controller Selectors', () => {
 
   describe('selectSeedlessOnboardingAuthConnection', () => {
     it('returns authConnection when it exists', () => {
-      const mockAuthConnection = AuthConnection.Google;
+      const mockAuthConnection = SeedlessAuthConnection.Google;
```
Comment (ieow) [inline app/selectors/seedlessOnboardingController.test.ts:72]: why this changes needed?

Comment (grvgoel81) [reply app/selectors/seedlessOnboardingController.test.ts:72]: SeedlessAuthConnection.Google because the selectSeedlessOnboardingAuthConnection selector returns the value from SeedlessOnboardingController state, which uses the SeedlessAuthConnection type from @metamask/seedless-onboarding-controller. Using the correct type improves type safety.

File: app/components/Views/Onboarding/index.tsx (hunk 8 above)
Comment (grvgoel81) [reply app/components/Views/Onboarding/index.tsx:668]: fallback is handled in handleLoginError because it's where we can detect the specific error type (GoogleLoginNoCredential/GoogleLoginNoMatchingCredential) that triggers the fallback. If we handle it in the catch block of onPressContinueWithSocialLogin, we'd need to duplicate the error type checking logic there.

File: app/core/OAuthService/OAuthLoginHandlers/index.ts (hunk 5 above)
Comment (grvgoel81) [reply app/core/OAuthService/OAuthLoginHandlers/index.ts:80]: that has been removed.

File: app/core/OAuthService/OAuthLoginHandlers/index.ts (hunk 6 above)
Comment (grvgoel81) [reply app/core/OAuthService/OAuthLoginHandlers/index.ts:77]: there is no redirectUri; only clientId, authServerUrl and web3AuthNetwork is there.

File: app/components/Views/Onboarding/index.tsx [hunk 10]
```diff
@@ -511,18 +515,34 @@ const Onboarding = () => {
...
+          // For Android Google, try browser fallback instead of showing error
+          if (Platform.OS === 'android' && socialConnectionType === 'google') {
+            try {
+              setLoading();
+              const fallbackHandler = createLoginHandler(
+                Platform.OS,
+                AuthConnection.Google,
+                true, // Use browser fallback
+              );
+              const result = await OAuthLoginService.handleOAuthLogin(
```
Comment (ieow) [inline app/components/Views/Onboarding/index.tsx:527]: you need to handle error throw from this function
like user cancel and etc

File: app/core/OAuthService/OAuthLoginHandlers/constants.ts [hunk 11]
```diff
@@ -56,10 +56,11 @@ export const AUTH_SERVER_MARKETING_OPT_IN_PATH =
 export const IosGID = process.env.IOS_GOOGLE_CLIENT_ID;
 export const IosGoogleRedirectUri = process.env.IOS_GOOGLE_REDIRECT_URI;
 export const AndroidGoogleWebGID = process.env.ANDROID_GOOGLE_SERVER_CLIENT_ID;
+export const AndroidGoogleClientId = process.env.ANDROID_GOOGLE_CLIENT_ID;
```
Comment (ieow) [inline app/core/OAuthService/OAuthLoginHandlers/constants.ts]: this is not used.
remove it

File: app/components/Views/Onboarding/index.tsx (hunk 10 above)
Comment (grvgoel81) [reply app/components/Views/Onboarding/index.tsx:527]: resolved.

**Review by ieow — APPROVED** [review]
lgtm
