### PR TITLE
fix: MMASSETS-626-new-rpc-no-confirmation

### LINKED ISSUE #12850: [Bug]: `wallet_addEthereumChain` adds new default RPC URL without confirmation
### Describe the bug

Following extension, when `wallet_addEthereumChain` is called for an existing chain, before the active chain switches the user is presented with a confirmation screen warning that a different RPC url is going to be added. 
Without this confirmation screen we might be bumping into a phishing potential (see https://github.com/MetaMask/metamask-extension/issues/16712) .

### Expected behavior

The user is presented with a confirmation screen warning the user that a new RPC url for the chain he's trying to add is going to be added to the RPC list and this will turn into the default active RPC.

### Screenshots/Recordings

https://github.com/user-attachments/assets/bb4fd623-b147-402a-bfe3-b6c8d1f560f9

### Steps to reproduce

1. Add Polygon in MetaMask and switch back to Mainnet
2. Open this [dapp](https://metamask.github.io/metamask-sdk/release-107.0.0/packages/examples/react-demo/build/index.html) on the inapp browser
3. Tap request accounts and connect while having Mainnet as the active chain
4. Tap AddEthereumChain
5. Go to the list of chains in the wallet and verify the list of RPC urls under the Polygon

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.38.0

### Build type

None

### Device

iPhone 11

### Operating system

iOS, Android

### Additional context

Call being made under the AddEthereumChain button:
```javascript
{
  method: 'wallet_addEthereumChain',
  params: [{
    chainId: '0x89',
    chainName: 'Polygon',
    blockExplorerUrls: ['https://polygonscan.com'],  // notice that this RPC url is different than the one preloaded in MetaMask
    nativeCurrency: { symbol: 'POL', decimals: 18 },
    rpcUrls: ['https://polygon-rpc.com/'],
  }]
}
```

### Severity

_No response_

### PR DESCRIPTION
**Pull request by bergarces**
## **Description**

When a dapp sends a `wallet_addEthereumChain` request for an existing network with a different RPC, there should be a confirmation dialog. It currently updates the network without asking for any sort of permission from the user.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12850

## **Manual testing steps**

1. Add Polygon in MetaMask and switch back to Mainnet
2. Open this [dapp](https://metamask.github.io/metamask-sdk/release-107.0.0/packages/examples/react-demo/build/index.html) on the inapp browser
3. If required, tap request accounts and connect while having Mainnet as the active chain
4. Tap Add Polygon Chain
5. A confirmation should show allowing the user to review the update (this was not happening before)
6. Go to the list of chains in the wallet and verify the list of RPC urls under the Polygon

### **Before**

Check bug report

### **After**

https://github.com/user-attachments/assets/c5b9c94b-646f-448c-98b0-d4bc3e381929

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Approvals/AddChainApproval/AddChainApproval.tsx [hunk 1]
```diff
@@ -15,13 +15,17 @@ const AddChainApproval = () => {
 
   if (approvalRequest?.type !== ApprovalTypes.ADD_ETHEREUM_CHAIN) return null;
 
+  const { isNetworkRpcUpdate, ...customNetworkInformation } =
+    approvalRequest.requestData;
```
Comment (bergarces) [inline app/components/Approvals/AddChainApproval/AddChainApproval.tsx:19]: New property passed alongside `requestData` to determine if we should be showing Add or Update text in the modal.

File: app/components/UI/NetworkVerificationInfo/NetworkVerificationInfo.test.tsx [hunk 2]
```diff
@@ -42,6 +43,48 @@ describe('NetworkVerificationInfo', () => {
...
+      ),
+    ).toBeDefined();
+    expect(
+      getByText(
+        strings('networks.update_network', {
+          network_name: networkWithCustomRpcUrl.chainName,
+        }),
+      ),
+    ).toBeDefined();
+  });
```
Comment (bergarces) [inline app/components/UI/NetworkVerificationInfo/NetworkVerificationInfo.test.tsx:86]: Verifies the snapshot as well as text that specifically should appear when updating the network instead of adding a new one.

File: app/core/RPCMethods/wallet_addEthereumChain.js [hunk 3]
```diff
@@ -46,7 +46,6 @@ const wallet_addEthereumChain = async ({
   endApprovalFlow,
 }) => {
   const {
-    CurrencyRateController,
```
Comment (bergarces) [inline app/core/RPCMethods/wallet_addEthereumChain.js:49]: This controller is not being used at all here or in the function that is called to perform the switch, so can be removed.

File: app/core/RPCMethods/wallet_addEthereumChain.js
Comment (bergarces) [inline app/core/RPCMethods/wallet_addEthereumChain.js:1]: The summary of the changes to this file is:
- If the network already exists and the network already has an rpc url that matches the one passed alongside `wallet_addEthereumChain`, we just switch network.
- Otherwise, we initiate an approval flow.
  * If the network exists, the approval flow triggers an update network modal.
  * If the network does not exist, the approval flow triggers a new network modal.

File: app/components/Approvals/AddChainApproval/AddChainApproval.test.tsx [hunk 4]
```diff
@@ -27,6 +27,7 @@ describe('AddChainApproval', () => {
   it('renders', () => {
     mockApprovalRequest({
       type: ApprovalTypes.ADD_ETHEREUM_CHAIN,
+      requestData: {},
```
Comment (bergarces) [inline app/components/Approvals/AddChainApproval/AddChainApproval.test.tsx:30]: `requestData` is always defined according to the type of `ApprovalRequest`.

**Review by gambinish — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]

**Comment by adonesky1** [comment]
I'm a bit confused in the video you've linked in the description. There appear to be two modals that pop up, the first one suggests you're adding the network for the first time, and then the second one suggests your updating the default rpcUrl for an existing network configuration. It seems like it should just be the second modal that shows?

**Comment by bergarces** [comment]
> I'm a bit confused in the video you've linked in the description. There appear to be two modals that pop up, the first one suggests you're adding the network for the first time, and then the second one suggests your updating the default rpcUrl for an existing network configuration. It seems like it should just be the second modal that shows?

I managed to paste the wrong video. I've updated it with one showing the "Update XXX" modal asking for confirmation.

The first time the modal shows, it's adding the network from the extension list of networks. The second one, shows how a dapp requesting to update the existing network with a new rpc requests permissions. Before this change, no permission was being asked to update the network with a new rpc.

**Comment by adonesky1** [comment]
Ok nice! Yes the new video looks correct to me!

**Review by Cal-L — APPROVED** [review]
LGTM

File: app/core/RPCMethods/wallet_addEthereumChain.js [hunk 5]
```diff
@@ -73,20 +97,23 @@ const wallet_addEthereumChain = async ({
...
 
-    // A network for this chain id already exists.
-    // Update it with any new information.
-    const clonedNetwork = { ...networkConfiguration };
+  const existingNetworkConfiguration = Object.values(
+    networkConfigurations,
+  ).find((networkConfiguration) => networkConfiguration.chainId === chainId);
 
-    // Use the addOrUpdateIndex utility for rpcEndpoints
+  const existingNetworkConfigurationHasRpcEndpint =
```
Comment (adonesky1) [inline app/core/RPCMethods/wallet_addEthereumChain.js:105]: nit
```suggestion
  const existingNetworkConfigurationHasRpcEndpoint =
```

File: app/core/RPCMethods/wallet_addEthereumChain.js [hunk 6]
```diff
@@ -73,20 +97,23 @@ const wallet_addEthereumChain = async ({
...
+    existingNetworkConfiguration?.rpcEndpoints.some(
+      (endpoint) => endpoint.url === firstValidRPCUrl,
+    );
+
+  // If the network already exists and the RPC URL is the same, perform a network switch only
+  if (
+    existingNetworkConfiguration &&
+    existingNetworkConfigurationHasRpcEndpint
```
Comment (adonesky1) [inline app/core/RPCMethods/wallet_addEthereumChain.js:113]:
```suggestion
    existingNetworkConfigurationHasRpcEndpoint
```

**Review by adonesky1 — APPROVED** [review]
Didn't manually test, but code looks pretty good. Probably could be cleaned up/refactored a bit but won't block on that!

File: app/core/RPCMethods/wallet_addEthereumChain.js (hunk 5 above)
Comment (bergarces) [reply app/core/RPCMethods/wallet_addEthereumChain.js:105]: Will resolve in subsequent PR to avoid having the bugfix not merged whilst waiting for approvals.
