### PR TITLE
fix: [Trending] use preferred search engine

### LINKED ISSUE #24400: [Bug]: Changing default search engine from google to duckduckgo in settings is not respected in the browser
**Describe the bug**

Title: Changing default search engine from google to duckduckgo in settings is not respected in the browser
Type: Bug
Build: 7.62 (3402)
Description: If i were to change my search engine from google to duckduckgo, i am still seeing google as my search option

**Expected behavior**

After updating the default search engine in the settings, the search option should update in the app

**Screenshots/Recordings**

https://github.com/user-attachments/assets/0c6d0be1-ea10-4a53-9cc1-5b5cd3b119e5

**Steps to reproduce**

see recording

**Error messages or log output**

```shell

```

**Where was this bug found?**

Internal release testing

**Version**

7.62.0

**Build number**

3402

**Build type**

None

**Device**

Not specified

**Operating system**

Android

### PR DESCRIPTION
**Pull request by juanmigdr**
## **Description**
Changing default search engine from google to duckduckgo in settings is not respected in the browser when searching on the Trending View

## **Changelog**

CHANGELOG entry: use preferred search engine on trending

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/24400 & https://consensyssoftware.atlassian.net/browse/ASSETS-2263

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Ensures the Trending view respects the user-selected search engine.
> 
> - SitesSearchFooter now reads `searchEngine` via `useSelector(selectSearchEngine)` and builds `searchUrl`/label dynamically (Google or DuckDuckGo)
> - Pressing the search link navigates with the computed `searchUrl`; URL detection behavior unchanged
> - Tests updated to mock `react-redux` and add DuckDuckGo coverage, including query encoding and text assertions
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit e6d867f41402fe706596f8067a21a6e2ae6886b0. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by sahar-fehri — APPROVED** [review]

File: app/components/UI/Sites/components/SitesSearchFooter/SitesSearchFooter.tsx [hunk 1]
```diff
@@ -53,6 +56,14 @@ const SitesSearchFooter: React.FC<SitesSearchFooterProps> = ({
 
   const isUrl = looksLikeUrl(searchQuery.toLowerCase());
 
+  const searchUrl =
+    searchEngine === 'DuckDuckGo'
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Sites/components/SitesSearchFooter/SitesSearchFooter.tsx:60]: How many search engines do we support? Is there more than DuckDuckGo and Google?

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by salimtb — APPROVED** [review]

File: app/components/UI/Sites/components/SitesSearchFooter/SitesSearchFooter.tsx (hunk 1 above)
Comment (juanmigdr) [reply app/components/UI/Sites/components/SitesSearchFooter/SitesSearchFooter.tsx:60]: Nope thats all of them. I was thinking the same in case we supported more it should be more modular but it seems like we only support those 2

Comment (Prithpal-Sooriya) [reply app/components/UI/Sites/components/SitesSearchFooter/SitesSearchFooter.tsx:60]: noice
