### PR TITLE
fix: No selected account or hd keyrings when device is locked during create account flow cp-7.47.0

### LINKED ISSUE #15982: [Bug]: Error: No selected account or hd keyrings when device is locked during create account flow
### Describe the bug

If the device is locked during the _Create a new account flow_, then there is an error and the app crashes when the device is unlocked again.

This happens for both:

- create Ethereum Account (but multiple SRPs need the be imported)
- create Solana account (only 1 SRP needs to be imported)

### Expected behavior

No error

### Screenshots/Recordings

https://github.com/user-attachments/assets/8517fbd2-34c6-487e-afaf-e0035d87d182

https://github.com/user-attachments/assets/04f66bec-579d-474b-b2cd-c08b0fa17cf8

Image

### Steps to reproduce

1. Click Add account
2. click Create Ethereum account (but only if you have multiple SRPs imported) or click Create Solana Account
3. Lock the device or wait for the device to auto-lock on the Create account screen
4. Unlock device
5. Notice error 

### Error messages or log output

```shell
View: Root
Error: No selected account or hd keyrings
```

### Detection stage

During release testing

### Version

7.47.0

### Build type

None

### Device

iPhone 15 Pixel 6 Pro

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by montelaidev**
## **Description**

This PR removes the usage of `getHdKeyringOfSelectedAccountOrPrimaryKeyring`. It would throw if the selectedAccount is undefined or if there aren't any hd keyrings. This causes an error when the wallet is locked during the add account screen. The state of the keyrings are cleared when the wallet is locked thus causing the error. 

The accounts controller now provides the entropySource for hd accounts and this is now used instead. 

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15982#event-17933966386

## **Manual testing steps**

1. Create a new wallet
2. Import a srp
3. Go to wallet view and add account
4. Click Add account
5. click Create Ethereum account (but only if you have multiple SRPs imported) or click Create Solana Account
6. Lock the device or wait for the device to auto-lock on the Create account screen
7. Unlock device
8. See that no error is thrown. 

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Unik0rnMaggie** [comment]
The fix works for both iOS and Android.



https://github.com/user-attachments/assets/44daf1de-b0cf-402b-aa67-02ddd814d846

File: app/components/Views/AddNewAccount/AddNewAccount.tsx [hunk 1]
```diff
@@ -55,14 +57,19 @@ const AddNewAccount = ({ route }: AddNewAccountProps) => {
...
-  const [keyringId, setKeyringId] = useState<string>(
-    keyringOfSelectedAccount.metadata.id,
-  );
   const hdKeyrings = useSelector(selectHDKeyrings);
+  const [primaryKeyringId] = hdKeyrings;
+  const initialKeyringIdToUse = useMemo(() => {
+    // The accounts controller now adds the entropySource to to hd accounts since 29.0.1
+    // if it is not a hd account, we use the primary keyring id
+    return (
+      (selectedInternalAccount!.options.entropySource as string) ??
```
Comment (owencraston) [inline app/components/Views/AddNewAccount/AddNewAccount.tsx]: this is concerning. if we can't avoid doing a null check perhaps we should throw and error and log it in sentry that we can track it.

Comment (montelaidev) [reply app/components/Views/AddNewAccount/AddNewAccount.tsx]: The null check can be removed.

**Review by owencraston — APPROVED** [review]
