### PR TITLE
fix: fix displayed warning for network

### LINKED ISSUE #20757: [Bug]: Incorrect asset name warnings for test networks
View issue in GitHub: https://github.com/MetaMask/metamask-mobile/issues/20757

**Describe the bug**

The default asset names for ETH on the following networks is:

- MegaETH: MegaETH
- Linea Sepolia: LineaETH
- Sepolia: SepoliaETH

However, the network edit view shows a warning and claims that the suggested ticker symbol should be ETH. It should not be ETH.

Also note in some cases there is a warning shown for network name as well. This should not be happening either.

**Expected behavior**

No warning is shown, nothing is suggested. The provided names are correct.

**Screenshots/Recordings**

Image
Image
Image

**Steps to reproduce**

1. Open the settings page
2. Open network settings
3. View settings for built-in testnets: MegaETH, Sepolia, Linea Sepolia

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

7.57.0 (2631)

**Build type**

Other (please specify exactly where you obtained this build in "Additional Context" section)

**Device**

iPhone 16

**Operating system**

iOS

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

This PR fixes the display of symbol warning for SepoliaETH.
This was happening because the code was prioritizing the value we get from https://chainid.network/chains.json which has `"symbol": "ETH"`, for the Sepolia network.

## **Changelog**

CHANGELOG entry: Fixed a bug that was causing the user to see ETH as a suggested correct symbol for SepoliaETH.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/20757

### **Before**

https://github.com/user-attachments/assets/9096c15f-68fa-499f-ba81-c57d37fd3218

### **After**

https://github.com/user-attachments/assets/f023bd9e-8e4d-40bd-a6e7-91e6a658354f

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Symbol validation now prefers `nativeCurrency` from `networkConfigurations` and revalidates on ticker updates; adds tests for Sepolia and fallback behavior.
> 
> - **Networks Settings (`app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js`)**:
>   - Update `validateSymbol` to prioritize `networkConfigurations[chainId]?.nativeCurrency` over Safe Chains list/network list when suggesting the symbol.
>   - Change `onTickerChange` to use `setState` callback, calling `getCurrentState` and `validateSymbol` immediately after ticker updates.
> - **Tests (`index.test.tsx`)**:
>   - Add tests ensuring no warning for Sepolia when symbol comes from `networkConfigurations` and fallback to `chainToMatch` when config is absent.
>   - Maintain existing validations for whitelisted symbols and general symbol/chain ID checks.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit ab709f2edc6817ba02c076092cdd1e8a779fcdae. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 1]
```diff
@@ -1477,9 +1482,11 @@ export class NetworkSettings extends PureComponent {
     this.getCurrentState();
   };
 
-  onTickerChange = async (ticker) => {
-    await this.setState({ ticker, validatedSymbol: false });
-    this.getCurrentState();
+  onTickerChange = (ticker) => {
+    this.setState({ ticker, validatedSymbol: false }, () => {
+      this.getCurrentState();
+      this.validateSymbol();
```
Comment (sahar-fehri) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:1488]: Added a call to `validateSymbol()` so that we validate the symbol everytime the user changes the ticker input.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 2]
```diff
@@ -1477,9 +1482,11 @@ export class NetworkSettings extends PureComponent {
     this.getCurrentState();
   };
 
-  onTickerChange = async (ticker) => {
-    await this.setState({ ticker, validatedSymbol: false });
```
Comment (sahar-fehri) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:1481]: `setState` asynchronous.
Even though we used `await`, React’s `setState` doesn’t resolve like an async function, the code continues running before the state is updated. As a result, when added a call to `this.validateSymbol()` runs immediately after, it still sees the previous ticker value one step behind.

**Review by juanmigdr — APPROVED** [review]
LGTM 🚀

**Review by vinnyhoward — APPROVED** [review]
LGTM!
