### PR TITLE
fix: cp-7.51.0 Fix loading state of transfer info page

### LINKED ISSUE #17095: [Bug]: When confirming a Send transaction, the value initially appears as 'Undefined' before updating to display the correct amount.
### Describe the bug

When confirming a Send transaction, the value initially appears as 'Undefined' before updating to display the correct amount.

### Expected behavior

Correct value is displayed on Confirmation screen.

### Screenshots/Recordings

Image

https://github.com/user-attachments/assets/b04fbeb3-a342-4dc5-82b6-1ac51b0f7f08

### Steps to reproduce

1. Start Send transaction

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.51.0 (2081)

### Build type

None

### Device

Samsung S24+

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

While loading momentarily undefined is visible in token hero component.

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/17095

## **Manual testing steps**

1. Create a send in app
2. Check confirmation page loading

## **Screenshots/Recordings**

Uploading Screen Recording 2025-07-15 at 5.42.03 PM.mov…

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by cryptotavares — COMMENTED** [review]
What's the reason for all the changes besides the ones on the hero component? 🤔

**Comment by jpuri** [comment]
Hey @cryptotavares : main reason for the issue was actually this [line](https://github.com/MetaMask/metamask-mobile/pull/17212/files#diff-06dd0bb0e0db0ab6831c6514dcd63d3dfcd34c1376b2684d96f0ccbab30cf253L18), `isNFT` was  initially `true` but there was no NFT data and thus undefined was rendered.

Other fixes are just sort of improvements / formatting.

**Review by cryptotavares — DISMISSED** [review]

File: app/components/Views/confirmations/components/rows/transactions/hero-row/hero-row.tsx [hunk 1]
```diff
@@ -6,12 +6,22 @@ import { useIsNft } from '../../../../hooks/nft/useIsNft';
...
 
   return (
-    <View testID={ConfirmationRowComponentIDs.TOKEN_HERO}>
-      {isNft ? <HeroNft /> : <HeroToken amountWei={amountWei} />}
+    <View
+      style={styles.wrapper}
+      testID={ConfirmationRowComponentIDs.TOKEN_HERO}
+    >
+      {!isPending && isNft === true && <HeroNft />}
+      {!isPending && isNft === false && <HeroToken amountWei={amountWei} />}
```
Comment (cryptotavares) [inline app/components/Views/confirmations/components/rows/transactions/hero-row/hero-row.tsx:24]: [nit]: I don't think you need to validate `isPending` here, as you have already added that into the `isNft` computation. So there is no way that `isPending` is truthy and `isNft` is `true` or `false`.

**Review by cryptotavares — APPROVED** [review]

File: app/components/Views/confirmations/components/rows/transactions/hero-row/hero-row.tsx (hunk 1 above)
Comment (jpuri) [reply app/components/Views/confirmations/components/rows/transactions/hero-row/hero-row.tsx:24]: I agree, its bit redundant here
