### PR TITLE
fix: cp-7.60.0 staked eth balances show first account staked balance across accounts

### LINKED ISSUE #23259: [Bug]: Staked Eth balance for first account is shown for multiple accounts with Staked Eth
### Describe the bug

The Staked Ethereum balance can be incorrect when a user has multiple accounts. This can cause user confusion as the amounts differ between the token list and the token asset detail pages.

### Expected behavior

The Staked Ethereum balance should be correct across multiple accounts with Staked Ethereum

### Screenshots/Recordings

https://github.com/user-attachments/assets/c41b4a98-42a9-44c8-94a0-cb9b987ec8ac

### Steps to reproduce

1. Use 2 accounts
2. Stake Eth in both accounts
3. The first account Staked Eth will show in the second account
4. The asset list will show the actual account Staked Eth

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.60.0

### Build number

3142

### Build type

Beta

### Device

Iphone 14 Pro Max

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #23260: [Bug]: Pooled-Staking APR and Earnings History not appearing on asset details screen
### Describe the bug

The APR is missing in the Ethereum asset detail page on supported chains

The Earnings History is empty in the Ethereum asset detail page on supported chains

### Expected behavior

The APR should be available in the Ethereum asset detail page on supported chains

The Earnings History should be available in the Ethereum asset detail page on supported chains

### Screenshots/Recordings

Image

Image

### Steps to reproduce

1. Go to the Ethereum asset page with 0 Staked Ethereum

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.60.0

### Build number

3142

### Build type

Beta

### Device

Iphone 14 pro max

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by nickewansmith**
## **Description**

1. What is the reason for the change?
There is a bug where we are not able to see the correct staked ethereum balance when there are multiple accounts with staked ethereum. There is also a bug where we are not able to see the APR and Earn History for a user with 0 staked ethereum balance.

2. What is the improvement/solution?
- Ensure that the native asset is not set isStaked true, as the Staked Ethereum asset is the one which should be set isStaked true. 
- Add accountId to filtering of token data in assets list selector to ensure we have correct balances across multiple accounts for staked ethereum. 
- Allow zero value staked ethereum in the allTokens selector, but limit to supported staking chains to lessen amount of tokens returned.

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://consensyssoftware.atlassian.net/browse/MUSD-114
Fixes: https://consensyssoftware.atlassian.net/browse/MUSD-112
Fixes: https://github.com/MetaMask/metamask-mobile/issues/23259
Fixes: https://github.com/MetaMask/metamask-mobile/issues/23260
## **Manual testing steps**

```gherkin
Feature: fix staked eth balances across multiple accounts and apr / earn history for zero balance staked eth
  Scenario: user has multiple accounts with ETH
    Given user stakes ETH on all accounts

    When user views the token list
    Then the Staked Ethereum balance should be correct in each account
    Then the Staked Ethereum asset detail page should show the correct amount for the account
    Then the Ethereum asset detail page should show the correct Staked Ethereum amount
    
 Scenario: user has multiple accounts with ETH, 1 with 0 Staked ETH
    Given user has 0 Staked Eth on an account

    When user views the token list
    Then the Staked Ethereum balance should not show in token list
    Then the Ethereum asset detail page should show no Staked Ethereum at all
    Then the Ethereum asset detail page should show APR and Earn History even when 0 Staked ETH
```

### **Before**

https://github.com/user-attachments/assets/b08a1c20-6e57-45cf-b238-53d3b5008b6a

### **After**

https://github.com/user-attachments/assets/488c8b0e-57a8-4228-8e6f-0b43c00ee952

Simulator Screenshot - iPhone 17 Pro - 2025-11-25 at 10 15 28
Simulator Screenshot - iPhone 17 Pro - 2025-11-25 at 10 15 31

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Ensure native assets are never marked staked, include a distinct Staked Ethereum entry, and adjust zero-balance filtering to retain native/staked tokens on the current network; update tests accordingly.
> 
> - **Selectors**:
>   - Set `isStaked: false` for native balances in `selectedAccountNativeTokenCachedBalanceByChainId*`.
>   - Update `selectNativeTokensAcrossChains` to always add a separate "Staked Ethereum" token alongside the native asset using cached staked balance data.
>   - Modify zero-balance behavior in `selectEvmTokensWithZeroBalanceFilter` to keep native and staked tokens on the current network when hiding zero balances.
>   - Cleanup: remove unused `toHex` import.
> - **Tests**:
>   - Adjust expectations for `isStaked` on native balances and zero-balance filtering results.
>   - Assert presence of "Staked Ethereum" in filtered lists and updated token counts.
>   - Maintain memoization and network filtering coverage.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit ce727563c1a373e97752e510539561ceaa4d5ef3. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/selectors/multichain/evm.ts [hunk 1]
```diff
@@ -192,10 +190,8 @@ export const selectNativeTokensAcrossChainsForAddress = createSelector(
 
       if (
         nativeTokenInfoByChainId &&
-        nativeTokenInfoByChainId.isStaked &&
-        nativeTokenInfoByChainId.stakedBalance !== '0x00' &&
-        nativeTokenInfoByChainId.stakedBalance !== toHex(0) &&
-        nativeTokenInfoByChainId.stakedBalance !== '0'
+        !nativeTokenInfoByChainId.isStaked &&
+        isSupportedPooledStakingChain(getDecimalChainId(nativeChainId as Hex))
```
Comment (Matt561) [inline app/selectors/multichain/evm.ts]: Do we have other supported staked assets that rely on the previous generic check against `nativeTokenInfoByChainId.stakedBalance`? If yes, we wouldn't want to limit this to purely pooled-staking.

Comment (nickewansmith) [reply app/selectors/multichain/evm.ts]: Are you thinking of Tron? It is non-evm. I am being purposefully restrictive here, in hopes that it will not decrease performance unnecessarily, as the code removed here seems to be aiming to slim down the amount of assets that could be returned.

Comment (nickewansmith) [reply app/selectors/multichain/evm.ts]: Removed this restriction after convo with assets team.

Comment (nickewansmith) [reply app/selectors/multichain/evm.ts]: They are ok with showing all zero balances

File: app/selectors/multichain/evm.ts [hunk 2]
```diff
@@ -190,13 +186,7 @@ export const selectNativeTokensAcrossChainsForAddress = createSelector(
...
       tokensByChain[nativeChainId].push(tokenByChain);
 
-      if (
-        nativeTokenInfoByChainId &&
-        nativeTokenInfoByChainId.isStaked &&
-        nativeTokenInfoByChainId.stakedBalance !== '0x00' &&
-        nativeTokenInfoByChainId.stakedBalance !== toHex(0) &&
-        nativeTokenInfoByChainId.stakedBalance !== '0'
-      ) {
+      if (nativeTokenInfoByChainId && !nativeTokenInfoByChainId.isStaked) {
```
[the remark this answers is not in the document]
Comment (nickewansmith) [reply app/selectors/multichain/evm.ts:189]: This is ok

**Review by Matt561 — APPROVED** [review]
