### PR TITLE
fix: issue in blockaid spinner for batched confirmations

### LINKED ISSUE #10514: [Bug]: During the Blockaid validation process, the spinner that typically indicates activity is not displayed
### Describe the bug

During the Blockaid validation process, the spinner that typically indicates activity is not displayed.
The spinner is visible for some time on Android devices.

Related PR: https://github.com/MetaMask/metamask-mobile/pull/10266

### Expected behavior

A spinner is displayed to indicate that validation is currently in progress.

### Screenshots/Recordings

iPhone 15:

https://github.com/user-attachments/assets/9716b52c-11e0-465c-968e-d0306c5e9f66

Samsung S24+:

https://github.com/user-attachments/assets/5c3a635b-ae9e-499f-bddb-8b604adb6c03

### Steps to reproduce

1. Go to https://metamask.github.io/test-dapp/
2. Submit batch of 10 malicious transactions (validation takes longer)

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

7.28.0

### Build type

None

### Device

Samsung S24+, iPhone 15

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Bloackaid spinner is not shown correctly when confirmation requests are batched.

Previously we only kept result of blockaid validation for only current transaction in redux state, this PR makes change to keep validation result of all recent transaction in state.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/10514

## **Manual testing steps**

1. Go to test dapp
2. Submit batched malicious request
3. Blockaid alert banner should appear correctly

## **Screenshots/Recordings**
https://github.com/user-attachments/assets/645bcd71-6fb8-45fa-a254-407a15195e0b

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sleepytanya** [comment]
Bitrise build https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/ce7aed75-1bea-4174-809c-3d7fbe24c12e?tab=artifacts
 @jpuri @bschorchit Looks great to me! Spinner is visible all the time while waiting for the warning.

Android:


https://github.com/user-attachments/assets/68b3a552-28b5-46cf-8146-07c19dc63733


iOS:


https://github.com/user-attachments/assets/d304467a-2b39-4423-92ad-48559f536ac3

File: app/reducers/transaction/index.js [hunk 1]
```diff
@@ -132,9 +133,9 @@ const transactionReducer = (state = initialState, action) => {
       const { transactionId, securityAlertResponse } = action;
       return {
         ...state,
-        currentTransactionSecurityAlertResponse: {
-          id: transactionId,
-          response: securityAlertResponse,
+        transactionSecurityAlertResponses: {
```
Comment (matthewwalsh0) [inline app/reducers/transaction/index.js:136]: Minor, since this is already in the transaction reducer, could we call this `securityAlertResponses` or even `securityAlertResponsesById` to be explicit?

File: app/components/Views/confirmations/components/TransactionReview/index.js [hunk 2]
```diff
@@ -359,12 +359,14 @@ class TransactionReview extends PureComponent {
 
   onContactUsClicked = () => {
     const { transaction, metrics } = this.props;
+    const { id, transactionSecurityAlertResponses } = transaction;
+    const securityAlertResponse = transactionSecurityAlertResponses?.[id];
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/components/TransactionReview/index.js:363]: Minor, but since we extract the specific security alert response in a few places, and are just using the `id` from the reducer, could we just make a selector such as `selectCurrentTransactionSecurityAlertResponse` to encapsulate the process and rely less on the properties being passed around?

**Review by matthewwalsh0 — DISMISSED** [review]

File: app/components/Views/confirmations/components/TransactionBlockaidBanner/TransactionBlockaidBanner.tsx [hunk 3]
```diff
@@ -8,25 +8,25 @@ const TransactionBlockaidBanner = (
 ) => {
   const { transactionId, ...rest } = bannerProps;
 
-  const securityAlertResponse = useSelector(
+  const transactionSecurityAlertResponses = useSelector(
     // TODO: Replace "any" with type
     // eslint-disable-next-line @typescript-eslint/no-explicit-any
-    (state: any) => state.transaction.currentTransactionSecurityAlertResponse,
+    (state: any) => state.transaction.transactionSecurityAlertResponses,
```
Comment (tommasini) [inline app/components/Views/confirmations/components/TransactionBlockaidBanner/TransactionBlockaidBanner.tsx:14]: Can we replace the any by `RootState`?

Comment (jpuri) [reply app/components/Views/confirmations/components/TransactionBlockaidBanner/TransactionBlockaidBanner.tsx:14]: Done 👍

File: app/reducers/transaction/index.js (hunk 1 above)
Comment (jpuri) [reply app/reducers/transaction/index.js:136]: Done 👍

File: app/components/Views/confirmations/components/TransactionReview/index.js (hunk 2 above)
Comment (jpuri) [reply app/components/Views/confirmations/components/TransactionReview/index.js:363]: Done 👍

**Review by brianacnguyen — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]
