### PR TITLE
fix: removed protect wallet for social login

### LINKED ISSUE #17586: [Bug]: Should not show "Protect wallet" reminder for social login flow
### Describe the bug

When user finish the onboarding with social login, at the home screen it shows the reminder for "Protect wallet"

### Expected behavior

Should not show because social login flow no need to do the backup

### Screenshots/Recordings

Image

### Steps to reproduce

1. Create new wallet with social account
2. Finish the onboarding steps
3. Check the homepage

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.0.0

### Build type

Beta

### Device

Honor Play

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by smgv**
## **Description**

Should not show "Protect wallet" reminder for social login flow - https://github.com/MetaMask/metamask-mobile/issues/17586

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes:

## **Manual testing steps**

1. Create new wallet with social account
2. Finish the onboarding steps
3. Check the homepage

### **Before**

https://github.com/MetaMask/metamask-mobile/issues/17586

### **After**

https://github.com/user-attachments/assets/b2fba9bf-7c46-49ca-a81a-49ab7d722314

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/BackupAlert/BackupAlert.tsx [hunk 1]
```diff
@@ -48,20 +50,22 @@ const BackupAlert = ({ navigation, onDismiss }: BackupAlertI) => {
...
-    // TODO: Replace "any" with type
-    // eslint-disable-next-line @typescript-eslint/no-explicit-any
-    (state: any) => state.user,
+    (state: RootState) => state.user,
   );
 
-  // TODO: Replace "any" with type
-  // eslint-disable-next-line @typescript-eslint/no-explicit-any
-  const onboardingWizardStep = useSelector((state: any) => state.wizard.step);
+  const onboardingWizardStep = useSelector(
```
Comment (ieow) [inline app/components/UI/BackupAlert/BackupAlert.tsx]: lets remove this onboarding wizard.
onboarding wizard flow is already removed

Comment (smgv) [reply app/components/UI/BackupAlert/BackupAlert.tsx]: PR updated. @ieow Please review

**Review by chaitanyapotti — DISMISSED** [review]

**Comment by LeVinhGithub** [comment]
lgtm but if any big change, pls let me validate again. thanks

**Review by LeVinhGithub — APPROVED** [review]
lgtm

**Review by chaitanyapotti — APPROVED** [review]

**Comment by hieu-w** [comment]
E2E pass for all other test except bug in main branch discussed here : https://consensys.slack.com/archives/C02U025CVU4/p1753717643905639
Failing on Import all tokens detected should import all tokens detected automatically
