### PR TITLE
fix: legacy gas fee edit modal

### LINKED ISSUE #5760: [Bug] Gas Fee modal for Legacy tx is displaying the EIP1559 fee modal
**Describe the bug**
Gas Fee modal for Legacy tx is displaying the EIP1159 fee modal

**Screenshots**

https://user-images.githubusercontent.com/54408225/218763488-000a2c00-a600-41c0-9b8b-b29a3e094eb8.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the test-dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Send Legacy Transaction
4. Click Fees
5. Click Edit Fees
6. See the gas modal for EIP1159 tx

**Expected behavior**
_A clear and concise description of what you expected to happen_
On legacy transactions we don't have priority fees. We should display the Gas limit and the Gas price. Take Extension as a reference:

image

**Smartphone (please complete the following information):**
Device: Samsung SM-A217F
OS: Android 11.0
App Version: v5.14.0 (1055)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by blackdevelopa**
**Description**
Currently, all legacy transactions on the mobile client uses the 1559 edit gas fee modal when editing gas prices. This PR replaces the legacy transaction edit gas fee modal with its own modal achieving parity with the extension.

[Figma](https://www.figma.com/file/aHdSNvg9ahXZMtThzz3bUo/Bugs?type=design&node-id=1%3A13803&mode=design&t=tobOzS87YOReqDgm-1)

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

- [x] Send native token: http://recordit.co/XdjZiopiOT
- [x] Send erc20 token: http://recordit.co/PYOTXtuggC
- [x] Token approve: http://recordit.co/iWwovKbRK8
- [x] Send legacy transaction: http://recordit.co/45CkaqNYte

**Issue**

fixes #5760 

Bitrise build: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/6af15cc0-3753-4daf-bc8d-f1fc6809bd2e

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx [hunk 1]
```diff
@@ -0,0 +1,420 @@
...
+  );
+
+  const gasEstimateType = useSelector(
+    (state: any) =>
+      state.engine.backgroundState.GasFeeController.gasEstimateType,
+  );
+
+  const chainId = useSelector((state: any) => selectChainId(state));
+
+  let gasTransaction = useMemo(() => ({}), []);
```
Comment (jpuri) [inline app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx:87]: Above looks weird.

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx [hunk 2]
```diff
@@ -0,0 +1,420 @@
...
+        ...analyticsParams,
+        chain_id: chainId,
+        function_type: view,
+        gas_mode: 'Basic',
+        speed_set: undefined,
+      };
+    } catch (err) {
+      return {};
+    }
+  }, [analyticsParams, chainId, view]);
```
Comment (jpuri) [inline app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx:107]: `useCallback` above looks redundant.

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx [hunk 3]
```diff
@@ -0,0 +1,420 @@
...
+                </Text>
+                <Icon
+                  name={'ios-arrow-back'}
+                  size={24}
+                  color={colors.background.default}
+                />
+              </View>
+            </View>
+            {renderWarning}
+            {renderError}
```
Comment (jpuri) [inline app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx:364]: Variable names `renderWarning`, `renderError` are not intuitive.

File: app/components/UI/EditGasFeeLegacyUpdate/types.ts [hunk 4]
```diff
@@ -81,4 +42,12 @@ export interface EditGasFeeLegacyUpdateProps {
...
   selectedGasObject: any;
+  hasDappSuggestedGas?: boolean;
+}
+
+export interface EditLegacyGasTransaction {
+  suggestedGasLimit: string;
+  suggestedGasPrice: string;
+  transactionFee: string;
+  transactionFeeFiat: string;
 }
```
Comment (jpuri) [inline app/components/UI/EditGasFeeLegacyUpdate/types.ts:53]: 👍

File: app/components/UI/CustomGasModal/CustomGasModal.tsx [hunk 5]
```diff
@@ -156,12 +156,6 @@ const CustomGasModal = ({
       >
         {legacy ? (
           <EditGasFeeLegacy
-            selected={selectedGas}
-            gasEstimateType={gasEstimateType}
-            gasOptions={gasFeeEstimate}
-            onChange={onChangeGas}
-            primaryCurrency={primaryCurrency}
-            chainId={chainId}
```
Comment (digiwand) [inline app/components/UI/CustomGasModal/CustomGasModal.tsx:164]: it looks like the test coverage has dropped for a couple of files. This one by -4.09%. Can we double check the changes are being tested here? 

`...pp/components/UI/CustomGasModal/CustomGasModal.tsx | 83.67% <100.00%> (-4.09%)`

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx [hunk 6]
```diff
@@ -0,0 +1,420 @@
...
+      return {
+        ...analyticsParams,
+        chain_id: chainId,
+        function_type: view,
+        gas_mode: 'Basic',
+        speed_set: undefined,
+      };
+    } catch (err) {
+      return {};
+    }
```
Comment (digiwand) [inline app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx:106]: I think we can remove the `try/catch` since I don't think 
```
      return {
        ...analyticsParams,
        chain_id: chainId,
        function_type: view,
        gas_mode: 'Basic',
        speed_set: undefined,
      };
```
could throw an error

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx (hunk 2 above)
Comment (digiwand) [reply app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx:107]: +1 maybe we can add the value directly to `const save` since it appears to only be used there

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx [hunk 7]
```diff
@@ -0,0 +1,420 @@
...
+              }
+            />
+          </View>
+        </TouchableWithoutFeedback>
+      </ScrollView>
+    </View>
+  );
+};
+
+export default EditGasFeeLegacy;
```
Comment (digiwand) [inline app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx:420]: [suggestion] It's a bit inconvenient comparing the differences between the old code and new code with the file path change. I extracted the current new change and the former code to compare it here:

https://www.textcompare.org/javascript/?id=64ef8bc071788cfc1dab7a3a
(^ diff expires 1 year from now)

I'd suggest holding off on file path changes unless it's clear to compare e.g. 1 or two commits to compare diff, or git recognizes it as a file path change instead of a new file

**Review by digiwand — COMMENTED** [review]
looking like a good fix. I wonder if we should plan to add more test coverage

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx (hunk 6 above)
Comment (blackdevelopa) [reply app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx]: Thanks. Updated [here](https://github.com/MetaMask/metamask-mobile/pull/7035/commits/18d2ad728fb4e5280ad2fc4db549328abfac3a91)

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx (hunk 3 above)
Comment (blackdevelopa) [reply app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx]: Thanks. Updated [here](https://github.com/MetaMask/metamask-mobile/pull/7035/commits/18d2ad728fb4e5280ad2fc4db549328abfac3a91)

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx [hunk 8]
```diff
@@ -0,0 +1,420 @@
...
+        <StyledButton
+          type={'confirm'}
+          onPress={save}
+          disabled={Boolean(error) || isAnimating}
+        >
+          {strings('edit_gas_fee_eip1559.save')}
+        </StyledButton>
+      </View>
+    </View>
+  );
```
[the remark this answers is not in the document]
Comment (blackdevelopa) [reply app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx]: Thanks. Updated [here](https://github.com/MetaMask/metamask-mobile/pull/7035/commits/18d2ad728fb4e5280ad2fc4db549328abfac3a91)

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx (hunk 2 above)
Comment (blackdevelopa) [reply app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx]: This makes sense. Updated [here](https://github.com/MetaMask/metamask-mobile/pull/7035/commits/18d2ad728fb4e5280ad2fc4db549328abfac3a91)

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx (hunk 7 above)
Comment (blackdevelopa) [reply app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx]: Okay. Done [here](https://github.com/MetaMask/metamask-mobile/pull/7035/commits/e3e9dd9eb35f68e4fc332b95f0c3368cb848f144)

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx (hunk 1 above)
Comment (blackdevelopa) [reply app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx]: Updated [here](https://github.com/MetaMask/metamask-mobile/pull/7035/commits/3815361adc1a820c0c36fe669bc8c9b2ac8ab1c5)

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx (hunk 7 above)
Comment (digiwand) [reply app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.tsx]: tyvm! 🙏🏼

**Review by digiwand — DISMISSED** [review]
code LGTM! I'd suggest having this QA'd as I'm not seeing the labels for this yet

**Comment by blackdevelopa** [comment]
> code LGTM! I'd suggest having this QA'd as I'm not seeing the labels for this yet

Yes we will. I intend to move it to QA after getting dev approval.

**Comment by seaona** [comment]
## Send ERC20 Token from Dapp displays legacy fees
Whenever I am on an EIP1559 network, if I trigger the Send ERC20 token function I can see how the gas displayed is Legacy instead of EIP1559.

https://github.com/MetaMask/metamask-mobile/assets/54408225/1f535931-64b2-4eae-b6be-12b837cca204

**Repro**:
1. Select Sepolia opr Goerli network
2. Go to the test dapp
3. Connect Wallet
4. Click Deploy ERC20
5. Click Transfer ERC20
6. Check gas displays legacy modal

**Review by jpuri — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

**Comment by seaona** [comment]
QA after changes

## Send ERC20 Token from Dapp displays legacy fees
I am still able to reproduce this issue

## Cancel Legacy tx causes MM break
Whenever we initiate a legacy transaction from inside the wallet and cancel it, MetaMask breaks with the error `Cannot read property 'substr' of undefined`

Screenshot from 2023-09-06 10-35-26

**Repro**
1. Add Bnb Testnet
2. Click Send
3. Add any amount and recipient
4. Cancel the tx
5. See error

https://github.com/MetaMask/metamask-mobile/assets/54408225/f66cb710-d1e0-4895-baa7-5296cec069a0

**Comment by seaona** [comment]
[Update] Issue # 2 has been confirmed to be a pre-existing issue, so I've opened a separate ticket [here](https://github.com/MetaMask/metamask-mobile/issues/7149)

File: app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.test.tsx [hunk 9]
```diff
@@ -0,0 +1,98 @@
...
+    expect(wrapper).toMatchSnapshot();
+  });
+
+  it('should match snapshot', async () => {
+    const initialState = mockInitialState();
+    const container = renderWithProvider(
+      <EditGasFeeLegacyUpdate {...editGasFeeLegacyForFeeMarket} />,
+      { state: initialState },
+    );
+    expect(container).toMatchSnapshot();
```
Comment (digiwand) [inline app/components/UI/EditGasFeeLegacyUpdate/EditGasFeeLegacyUpdate.test.tsx:76]: what benefit do we have testing both `should render correctly` and `should match snapshot` when they both test `toMatchSnapshot`? can we combine them or update the test names to be more specific?

File: app/components/UI/EditGasFeeLegacyUpdate/index.tsx [hunk 10]
```diff
@@ -56,92 +50,82 @@ const EditGasFeeLegacy = ({
...
-    AnalyticsV2.trackEvent(
-      MetaMetricsEvents.GAS_FEE_CHANGED,
-      getAnalyticsParams(),
-    );
+    AnalyticsV2.trackEvent(MetaMetricsEvents.GAS_FEE_CHANGED, {
+      ...analyticsParams,
+      chain_id: chainId,
+      function_type: view,
+      gas_mode: 'Basic',
+      speed_set: undefined,
```
Comment (digiwand) [inline app/components/UI/EditGasFeeLegacyUpdate/index.tsx:99]: Q: why `undefined` vs. `null`? why pass the value if it is null or undefined? 
ref: https://stackoverflow.com/a/48197438

File: app/components/UI/EditGasFeeLegacyUpdate/index.tsx [hunk 11]
```diff
@@ -56,92 +50,82 @@ const EditGasFeeLegacy = ({
...
-  const [gasObject, updateLegacyGasObject] = useState<{
+  const [showEditUI, setShowEditUI] = useState<boolean>(!hasDappSuggestedGas);
+  const [gasObjectLegacy, updateGasObjectLegacy] = useState<{
     legacyGasLimit: string;
     suggestedGasPrice: string;
+    suggestedMaxFeePerGas?: string;
   }>({
     legacyGasLimit: selectedGasObject.legacyGasLimit,
     suggestedGasPrice: selectedGasObject.suggestedGasPrice,
+    suggestedMaxFeePerGas: selectedGasObject?.suggestedMaxFeePerGas,
```
Comment (digiwand) [inline app/components/UI/EditGasFeeLegacyUpdate/index.tsx:66]: I'm not fully understanding why we're adding `suggestedMaxFeePerGas` to `gasObjectLegacy` since max fee per gas was added for EIP-1559. Could you help me understand more please?

File: app/components/UI/EditGasFeeLegacyUpdate/index.tsx [hunk 12]
```diff
@@ -154,72 +138,32 @@ const EditGasFeeLegacy = ({
...
   );
 
   const changedGasLimit = useCallback(
     (value: string) => {
-      const newGas = { ...gasTransaction, suggestedGasLimit: value };
-      changeGas(newGas, null);
-    },
-    [changeGas, gasTransaction],
-  );
+      let newGas: { suggestedGasLimit: typeof value } | undefined;
```
Comment (digiwand) [inline app/components/UI/EditGasFeeLegacyUpdate/index.tsx:154]: [nit] I think we can remove `undefined` since newGas is being set directly after. Another option is to use a ternary here 

```
      const newGas: { suggestedGasLimit: typeof value } =
        typeof gasTransaction === 'object'
          ? { ...gasTransaction, suggestedGasLimit: value }
          : { suggestedGasLimit: value };
```

File: app/components/UI/EditGasFeeLegacyUpdate/index.tsx (hunk 11 above)
Comment (blackdevelopa) [reply app/components/UI/EditGasFeeLegacyUpdate/index.tsx:66]: Yep. This is useful when transacting in 1559 supported networks. The suggestedMaxFeePerGas is passed as the fallback for suggestedGasPrice if absent. [Here](https://github.com/MetaMask/metamask-mobile/pull/7035/files#diff-a3b5a793c5bbd1f3342532b6cd9498370b0e12186267611b4f9ab46d71f22c0cR219)

Comment (digiwand) [reply app/components/UI/EditGasFeeLegacyUpdate/index.tsx:66]: Thank you 🙏🏼

File: app/components/UI/EditGasFeeLegacyUpdate/index.tsx (hunk 12 above)
Comment (blackdevelopa) [reply app/components/UI/EditGasFeeLegacyUpdate/index.tsx]: Updated. https://github.com/MetaMask/metamask-mobile/pull/7035/commits/f7eb1665f2a678ff759f2963072302aca45f4fff

File: app/components/UI/EditGasFeeLegacyUpdate/index.tsx (hunk 10 above)
Comment (blackdevelopa) [reply app/components/UI/EditGasFeeLegacyUpdate/index.tsx]: Removed. https://github.com/MetaMask/metamask-mobile/pull/7035/commits/0f6aee6ce4c45f2b1891317e2d738c8ed958890b

**Comment by jpuri** [comment]
@blackdevelopa : seems ur patch needs update since I merged another patch: https://github.com/MetaMask/metamask-mobile/pull/7068/files#diff-a97d2fcf5065a3fdab653bf7896a9f64998e85513c5051844ca53863ca3dbf70

**Comment by blackdevelopa** [comment]
> @blackdevelopa : seems ur patch needs update since I merged another patch: https://github.com/MetaMask/metamask-mobile/pull/7068/files#diff-a97d2fcf5065a3fdab653bf7896a9f64998e85513c5051844ca53863ca3dbf70

Thank you @jpuri. Updated [here](https://github.com/MetaMask/metamask-mobile/pull/7035/commits/0f92d7d49669571bec6c8ce548e4ba24e0f829ec)

**Review by digiwand — DISMISSED** [review]

**Comment by seaona** [comment]
## Legacy gas missmatch
Whenever I trigger a legacy transaction from a dapp, I can see how the Estimated gas fees does not match the gas details (if I open the Edit gas). Furthermore if I change the suggested gas, I can see how the value is not changed and tx is submitted with the suggested gas value instead of the one I set.

https://github.com/MetaMask/metamask-mobile/assets/54408225/1638b615-4130-4ddb-9b8c-d48b40c24184

https://github.com/MetaMask/metamask-mobile/assets/54408225/1988b1df-ce81-4071-b4e7-c73f22f79d82

**Repro:**
1. Select a testnet (i.e. Goerli)
2. Go to testdapp
3. Click Send Legacy tx
4. Click Edit gas fees
5. Change its value and save
6. See how value is not updated on the confirmation screen
7. Send tx
8. Check Etherscan
9. See how gas was not saved



## Send ERC721 after Approve fails with out of gas
Whenever we try to send an ERC721 token **after** approving it, we can see how in MetaMask the transaction is successful, but if we go to Etherscan, we can see how tx failed with `Out of gas` error.
If I try again to send the ERC721 then it works.

https://github.com/MetaMask/metamask-mobile/assets/54408225/01f88a69-f439-4179-91e2-840cea592105

**Repro:**
1. Deploy an ERC721 contract (on Sepolia/Goerli)
11. Mint a couple of tokens
12. Approve a token
13. Transfer a token
14. Check tx details
15. Tx seem Confirmed
16. Check Etherscan
17. Tx has failed with `Out of gas`

File: patches/@metamask+transaction-controller+4.0.1.patch [hunk 13]
```diff
@@ -369,7 +369,7 @@ index 0000000..decccda
...umbers = this.#getLastFetchedBlockNumbers();\n    const previousValue = lastFetchedBlockNumbers[lastFetchedKey];\n\n    if (previousValue === lastFetchedBlockNumber) {\n      return;\n    }\n\n    lastFetchedBlockNumbers[lastFetchedKey] = lastFetchedBlockNumber;\n\n    this.hub.emit('updatedLastFetchedBlockNumbers', {\n      lastFetchedBlockNumbers,\n      blockNumber: lastFetchedBlockNumber,\n    });\n  }\n\n  #getBlockNumberKey(): string {\n    return `${this.#getCurrentChainId()}#${this.#getCurrentAccount().toLowerCase()}`;\n  }\n\n  #canStart(): boolean {\n    const isEnabled = this.#isEnabled();\n    const currentChainId = this.#getCurrentChainId();\n    const currentNetworkId = this.#getCurrentNetworkId();\n\n    const isSupportedNetwork = this.#remoteTransactionSource.isSupportedNetwork(\n      currentChainId,\n      currentNetworkId,\n    );\n\n    return isEnabled && isSupportedNetwork;\n  }\n\n  #getCurrentChainId(): string {\n    const chainIdDecimalString = this.#getNetworkState().providerConfig.chainId;\n    return `0x${parseInt(chainIdDecimalString, 10).toString(16)}`;\n  }\n\n  #getCurrentNetworkId(): string {\n    return this.#getNetworkState().network;\n  }\n}\n"]}
```
Comment (jpuri) [inline patches/@metamask+transaction-controller+4.0.1.patch:369]: Reason for few additional visible changes in the patch is that previous patch was creating by manual changes in node_modules but this has been created using `yarn build` in core repo branch `refactor/transaction-controller-patch-mobile `.

**Review by jpuri — DISMISSED** [review]
Changes look good, it will be nice to throughly QA these as they effect gas selection on confirmation pages.

File: patches/@metamask+transaction-controller+4.0.1.patch (hunk 13 above)
Comment (blackdevelopa) [reply patches/@metamask+transaction-controller+4.0.1.patch]: Thank you @jpuri , I think this looks cleaner [here](https://github.com/MetaMask/metamask-mobile/pull/7035/commits/8d42ccad1c9b7c309ac7f9bfa0d0aa5761564f33)

**Review by jpuri — APPROVED** [review]
LGTM

**Review by digiwand — APPROVED** [review]
re: https://github.com/MetaMask/metamask-mobile/pull/7035#issuecomment-1717118939

as proposed in ^ this comment, it seems others have agreed this PR is okay to merge based on a conversation @blackdevelopa showed me. It has been discussed by others that the issues mentioned above can be addressed in follow-up PRs

File: patches/@metamask+transaction-controller+4.0.1.patch [hunk 14]
```diff
@@ -1,16 +1,3 @@
-diff --git a/node_modules/@metamask/transaction-controller/dist/.patch.txt b/node_modules/@metamask/transaction-controller/dist/.patch.txt
-new file mode 100644
-index 0000000..550de56
---- /dev/null
-+++ b/node_modules/@metamask/transaction-controller/dist/.patch.txt
-@@ -0,0 +1,7 @@
-+PATCH GENERATED FROM MetaMask/core branch: refactor/transaction-controller-patch-mobile
-+This patch backports various transaction controller features from the main branch of MetaMask/core
-+Steps to update patch:
```
Comment (Gudahtt) [inline patches/@metamask+transaction-controller+4.0.1.patch:9]: It looks like this patch was not updated correctly. Please follow these instructions next time to ensure this patch comment is preserved

File: patches/@metamask+transaction-controller+4.0.1.patch [hunk 15]
```diff
@@ -2852,7 +2839,15 @@ index dc4300f..893ca7e 100644
  const ethereumjs_util_1 = require("ethereumjs-util");
  const controller_utils_1 = require("@metamask/controller-utils");
  exports.ESTIMATE_GAS_ERROR = 'eth_estimateGas rpc method error';
-@@ -121,50 +112,6 @@ const isEIP1559Transaction = (transaction) => {
+@@ -24,6 +15,7 @@ const NORMALIZERS = {
+     maxFeePerGas: (maxFeePerGas) => (0, ethereumjs_util_1.addHexPrefix)(maxFeePerGas),
+     maxPriorityFeePerGas: (maxPriorityFeePerGas) => (0, ethereumjs_util_1.addHexPrefix)(maxPriorityFeePerGas),
+     estimatedBaseFee: (maxPriorityFeePerGas) => (0, ethereumjs_util_1.addHexPrefix)(maxPriorityFeePerGas),
++    type: (type) => type === '0x0' ? '0x0' : undefined,
```
[the remark this answers is not in the document]
Comment (jpuri) [reply patches/@metamask+transaction-controller+4.0.1.patch:2846]: Currently `type` is always undefined, we are adding code to preserve it for legacy transactions.
