### PR TITLE
fix: Account List Performance Issues

### LINKED ISSUE #14863: [Bug]: performance degradation on account list rendering and account rename
### Describe the bug

performance degradation on account list rendering

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Open account list and create +30 accounts of any kind
2. Close and open account list
3. Notice degraded performance
4. Try to rename an account
5. Notice degraded performance

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.45.0

### Build type

None

### Device

Any

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

Android and iOS

### Severity

_No response_

### PR DESCRIPTION
**Pull request by owencraston**
## **Description**
This PR addresses serious performance issues when opening the account list on mobile. This issue is especially problematic when the user has lots of accounts.

### Result
Based on my measurements, `the account list took almost 12 (11.96) seconds to open on main vs only 3 seconds with my current fix`. The number of re renders on the AccountSelector component went from `34` to `5`. 

This means...
- `Time to render was reduced by ~74%`
_((11.96 - 3.11)/11.96) * 100 = 73.9966555184%_

- `Re renders were reduced by ~ 85%`
_((34-5)/34)*100 = 85.2941176471_

#### QA Info
- Device: Google Pixel 6
- 18 accounts. One Solana account with balances. 
- Debug mode

## How
There are several components to this change. 

1. The most important change was [this commit](https://github.com/MetaMask/metamask-mobile/pull/14817/commits/ad560294472e98af38c55194bacc0ecf7d553a21). This change makes it so that we only upset the ENS state in the `useAccounts` hook if we have changes. 
2. Then I broke up the useMultichainBalances hook  into two different hooks. Before we calculated the balance for all accounts AND the selected account in one hook. Now there are two hooks, `useSelectedAccountMultichainBalances` and `useMultichainBalancesForAllAccounts`. This is a small improvement but it makes it so that for screens where we only need to calculate the selected accounts balance, we do not do any extra computation for the other accounts. 
3. Better memoization of the AccountSelector component. 

## **Related issues**

Progresses: https://github.com/MetaMask/metamask-mobile/issues/14623
Fixes: https://github.com/MetaMask/metamask-mobile/issues/14863

## **Manual testing steps**

1. If you want to test with a Solana account, make sure you edit the METAMASK_BUILD_TYPE to be `beta` in the `.js.env`
4. `yarn setup && yarn watch:clean`
5. Create / Import a wallet, preferably with funds
6. create many accounts, the more the better. These can be eth accounts or Solana accounts. I tested with 18 accounts
7. open the account list by clicking the selected account at the top of the screen. 
8. You should notice an improvement in how long it takes for this screen to render. The subseuent times you open the account list should be even faster. 
9. Verify that all the info in the account list is valid...
    - All account should be present 
    - Account names should be correct
    - Account balances should be correct
    - Account actions (view on etherscan etc) should still work 

### **Before**

https://github.com/user-attachments/assets/dbcdd9f4-ed2a-4775-b2cb-f91ef71fbc23

Profiler:
Screenshot 2025-04-24 at 12 02 02 PM

### **After**

https://github.com/user-attachments/assets/08d8139a-d7a0-4749-8d03-dd88391a75d6

Profiler:
Screenshot 2025-04-24 at 11 52 14 AM

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

image

### CODE REVIEW

**Comment by sleepytanya** [comment]
Android Production build  https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/4b99da426f1fb748

https://github.com/user-attachments/assets/e6fa6c66-9045-4d72-9c50-5f060d3692dd

iOS and Android QA builds https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/c672cc63-a263-4ff5-becc-f4ba88172e5a?tab=artifacts

iOS:

https://github.com/user-attachments/assets/841b203a-00e8-4636-81be-946df5956aaa



Android:


https://github.com/user-attachments/assets/027f5c6b-0c1d-406b-914e-cb109cff4468


@owencraston @gantunesr Lightning fast Accounts list!

File: app/components/hooks/useMultichainBalances/utils.ts [hunk 1]
```diff
@@ -0,0 +1,170 @@
...
+} from '@metamask/assets-controllers';
+///: END:ONLY_INCLUDE_IF
+import { formatWithThreshold } from '../../../util/assets';
+import I18n from '../../../../locales/i18n';
+import Engine from '../../../core/Engine';
+import { SupportedCaipChainId } from '@metamask/multichain-network-controller';
+import { TotalFiatBalancesCrossChains } from '../useGetTotalFiatBalanceCrossChains';
+import { isPortfolioViewEnabled, isTestNet } from '../../../util/networks';
+
+// Production balance calculartion (EVM)
```
Comment (gambinish) [inline app/components/hooks/useMultichainBalances/utils.ts:22]: Small typo, nbd

File: app/components/hooks/useMultichainBalances/utils.ts [hunk 2]
```diff
@@ -0,0 +1,170 @@
...
+    account,
+    isOriginalNativeEvmTokenSymbol,
+    totalFiatBalancesCrossEvmChain,
+    currentCurrency,
+  );
+  return {
+    displayBalance: evmAccountBalance.displayBalance,
+    totalFiatBalance: evmAccountBalance.totalFiatBalance,
+    totalNativeTokenBalance:
+      evmAccountBalance.totalNativeTokenBalance?.toString() || '0',
```
Comment (gambinish) [inline app/components/hooks/useMultichainBalances/utils.ts:167]: I wonder if this should have an `undefined` fallback, rather than zero. Won't this break our spinner while fetching balances?

**Review by gambinish — DISMISSED** [review]

File: app/components/hooks/useMultichainBalances/utils.ts (hunk 2 above)
Comment (owencraston) [reply app/components/hooks/useMultichainBalances/utils.ts:167]: This is a good suggestion, since this is somewhat of an urgent issue I will would prefer to keep it the same as main in order to not introduce potential issues.

**Review by vinnyhoward — DISMISSED** [review]
Huge win here, nice work!

**Comment by sleepytanya** [comment]
ENS account works as expected, iPhone 15, QA build:


https://github.com/user-attachments/assets/dab1207e-1bc4-4619-9186-74a4f931faab

**Review by gambinish — DISMISSED** [review]

**Review by sleepytanya — DISMISSED** [review]

**Review by sleepytanya — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]

**Review by gambinish — APPROVED** [review]

**Comment by owencraston** [comment]
Some of the unit tests are failing on CI due to timeout issues. I tested these locally with no issues so I suspect it has to do with the recent issues of CI.
