### PR TITLE
fix: SnapUILink alignment and colour inheritance issue

### LINKED ISSUE #3245: Alignment is off on SnapUILink icons
Image

Alignment might also be off inside the row?

### PR DESCRIPTION
**Pull request by Daniel-Cross**
## **Description**

Changes made to the mapping component `link.ts` and the rendering component `SnapUILink.tsx` to handle alignment issues and colour inheritance.

## **Related issues**

Fixes: https://github.com/orgs/MetaMask/projects/149/views/1?pane=issue&itemId=102849361&issue=MetaMask%7Csnaps%7C3245

## **Manual testing steps**

1. Use mono-repo to create a small component including `Link`
2. Go to `localhost:8001` on mobile device and connect
3. Press send message button to see how components are rendered

### **After**

Simulator Screenshot - iPhone 16 Pro - 2025-04-07 at 16 11 04

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Snaps/SnapUILink/SnapUILink.tsx [hunk 1]
```diff
@@ -27,38 +41,22 @@ const onPress = (href: string) => {
...
-
-  return (
-    <ButtonLink
-      testID="snaps-ui-link"
-      // @ts-expect-error This prop is not part of the type but it works.
-      color={TextColor.Info}
-      onPress={() => onPress(href)}
-      label={label}
+export const SnapUILink: React.FC<SnapUILinkProps> = ({ href, children }) => (
+  <TouchableOpacity
```
Comment (FrederikBolding) [inline app/components/Snaps/SnapUILink/SnapUILink.tsx:45]: The problem with this solution is that inline links don't align well like this:

File: app/components/Snaps/SnapUIRenderer/components/link.ts [hunk 2]
```diff
@@ -7,13 +7,39 @@ import { UIComponentFactory } from './types';
...
+      return {
+        ...child,
+        props: {
+          ...child.props,
+          color: 'primary',
+        },
+      };
+    }
+
+    return child;
```
[the remark this answers is not in the document]
Comment (Daniel-Cross) [reply app/components/Snaps/SnapUIRenderer/components/link.ts:32]: We have to map over the `Icon` component if it is present in the link, and then add the text colour prop if no other colour prop is applied to the `Icon`. 

For example, if we remove the mapping above which checks for more complex logic and just render the children with `textColor` passed in, we get the following:
Simulator Screenshot - iPhone 16 Pro - 2025-04-09 at 15 41 35
Which is no colour inheritance on the `Icon`, the prop on `Icon` is also different from the props on `Text`. 

If we log the child also, we can see that the `textColor` doesn't get passed in:
```
 LOG  ["THIS IS A LINK", {"key": null, "props": {"name": "arrow-right"}, "type": "Icon"}]
 ```
This can be replicated with:
```
 <Link href="https://www.google.com">
      THIS IS A LINK
      <Icon name="arrow-right" />
 </Link>
```
This is only for custom Icon's added to the `SnapUILink` though, if we can expect this not to happen then we can remove this logic.

File: app/components/Snaps/SnapUILink/SnapUILink.tsx (hunk 1 above)
Comment (Daniel-Cross) [reply app/components/Snaps/SnapUILink/SnapUILink.tsx]: I've pushed a change that fixes the alignment issue when this is rendered within a `Text` component, however this will now be out of alignment when rendered outside of a text component, so we will have to do 2 separate types of `SnapUILink` within this component if we want to handle both cases.

File: app/components/Snaps/SnapUILink/SnapUILink.tsx [hunk 3]
```diff
@@ -27,38 +35,18 @@ const onPress = (href: string) => {
...
+    style={styles.container}
+    onPress={() => onPress(href)}
+    accessibilityRole="link"
+    accessibilityHint={`Opens ${href} in your browser`}
+  >
+    {children}
+    <View style={styles.spacer} />
+    <Icon name={IconName.Export} color={IconColor.Primary} size={IconSize.Sm} />
+  </Text>
+);
```
[the remark this answers is not in the document]
Comment (Daniel-Cross) [reply app/components/Snaps/SnapUILink/SnapUILink.tsx:51]: resolved this by reducing the width to the width of the content

File: app/components/Snaps/SnapUILink/SnapUILink.tsx (hunk 1 above)
Comment (Daniel-Cross) [reply app/components/Snaps/SnapUILink/SnapUILink.tsx]: To my eyes, this looks slightly out of alignment:
Simulator Screenshot - iPhone 16 Pro - 2025-04-15 at 13 53 36

It's because the text is wrapped in text x 2 and the icon is wrapped in text once.

Comment (Daniel-Cross) [reply app/components/Snaps/SnapUILink/SnapUILink.tsx]:
```
  <Box>
       <Link href="https://www.google.com">
                THIS IS A LINK
                <Icon name="arrow-right" color="muted" />
        </Link>
</Box>
```

File: app/components/Snaps/SnapUILink/SnapUILink.tsx [hunk 4]
```diff
@@ -27,38 +36,18 @@ const onPress = (href: string) => {
...
-      />
-    </>
-  );
+export const SnapUILink: React.FC<SnapUILinkProps> = ({ href, children }) => (
+  <Text
+    testID="snaps-ui-link"
+    style={styles.container}
+    onPress={() => onPress(href)}
+    accessibilityRole="link"
+    accessibilityHint={`Opens ${href} in your browser`}
```
[the remark this answers is not in the document]
Comment (Daniel-Cross) [reply app/components/Snaps/SnapUILink/SnapUILink.tsx:45]: Got it, I'll add

File: app/components/Snaps/SnapUILink/SnapUILink.tsx (hunk 1 above)
Comment (Daniel-Cross) [reply app/components/Snaps/SnapUILink/SnapUILink.tsx]: I agree and I'll make a ticket. The fix is to check for Icon components and then not wrap them in text, which involves mapping a new case for this event.

File: app/components/Snaps/SnapUILink/SnapUILink.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (Daniel-Cross) [reply app/components/Snaps/SnapUILink/SnapUILink.tsx:45]: Do I need to add the translations also?

**Review by david0xd — APPROVED** [review]
