### PR TITLE
fix(perps): set confirmation header and safe area by navigation source cp-7.64.0

### LINKED ISSUE #25469: [Bug]: Perps add funds keyboard has incorrect padding
## Describe the bug

The padding is off on the "add funds" keyboard screen for perps. The percentage buttons (10%, 25%, 50%, Max) and the numeric keypad extend to the edge of the screen without proper horizontal padding, while the similar "Add Prediction funds" screen has correct padding.

Additionally, the confirm screen in perps also has layout issues according to reports.

## Expected behavior

The add funds keyboard in perps should have consistent horizontal padding matching the "Add Prediction funds" screen, where buttons have proper margins from the screen edges.

## Screenshots/Recordings

Image

Image

https://github.com/user-attachments/assets/baffd2f7-12f2-44ba-be06-3616c3901958

## Steps to reproduce

1. Open MetaMask Mobile app
2. Navigate to perps feature
3. Go to "add funds" screen
4. Observe that the percentage buttons and numeric keypad have no horizontal padding (extend to screen edges)
5. Compare with "Add Prediction funds" screen which has proper padding

## Error messages or log output

N/A - This is a UI/layout issue

## Where was this bug found?

Internal release testing

## Version

7.64.0

## Build number

3586

## Build type

N/A

## Device

Not specified in report

## Operating system

- Android (confirmed from screenshots)
- iOS (potentially affected, needs verification)

## Additional context

- Reported in #mm-trade-team-mobile-perps Slack channel
- Barbara noted: "Funny that both should be the same exact screen and code" - suggesting the two screens may share code but have different styling behavior
- The confirm screen in perps reportedly also has layout issues

## Severity

- **User Impact**: Visual/UI issue affecting the perps add funds flow
- **Visibility**: Visible to all users accessing perps feature
- **Priority**: Medium - functional but visually inconsistent with other screens

### PR DESCRIPTION
**Pull request by michalconsensys**
## **Description**

Set confirmation header by navigation source

## **Changelog**

CHANGELOG entry: Fixed Perps confirmation screen so the header is hidden when opening from the one-click order flow and shows a minimal header when opening from other flows.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/25469

## **Manual testing steps**

```gherkin
Feature: Perps confirmation screen header

  Scenario: user opens confirmation via one-click order (navigateToOrder)
    Given user is on a Perps market and taps place order (one-click flow)

    When deposit is confirmed and confirmation screen opens

    Then the confirmation screen has no header (header: () => null)

  Scenario: user opens confirmation from another flow
    Given user reaches RedesignedConfirmations from a path other than navigateToOrder

    When the confirmation screen is shown

    Then the screen shows a minimal header (header visible, no left button, empty title)
```

### **Before**
Simulator Screenshot - iPhone 17 Pro - 2026-02-03 at 19 47 49

### **After**
Simulator Screenshot - iPhone 17 Pro - 2026-02-03 at 19 46 49

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Low Risk**
> Low risk UI/navigation behavior change scoped to Perps confirmations; main risk is unintended header/safe-area state if route params are missing or mis-set.
> 
> **Overview**
> Updates Perps navigation so `RedesignedConfirmations` can render *with or without* a Perps header based on a new `showPerpsHeader` route param.
> 
> The one-click deposit-and-trade flow (`navigateToOrder`) now explicitly navigates to confirmations with `showPerpsHeader: false`, while other entry points default to showing a minimal header; `Confirm`’s `disableSafeArea` is also tied to this flag. Adds `CONFIRMATION_HEADER_CONFIG`, updates Perps stack screen options accordingly, and adjusts the related hook test and navigation types.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 71b114b07f597486b82a45787444090d36030e25. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/Perps/hooks/usePerpsNavigation.ts [hunk 1]
```diff
@@ -145,7 +145,7 @@ export const usePerpsNavigation = (): PerpsNavigationHandlers => {
         .then(() => {
           navigation.navigate(
             Routes.FULL_SCREEN_CONFIRMATIONS.REDESIGNED_CONFIRMATIONS,
-            params,
+            { ...params, showPerpsHeader: false },
```
Comment (abretonc7s) [inline app/components/UI/Perps/hooks/usePerpsNavigation.ts]: should the false match DEFAULT_SHOW_PERPS_HEADER ?

File: app/components/UI/Perps/routes/index.tsx [hunk 2]
```diff
@@ -46,12 +48,35 @@ const styles = StyleSheet.create({
   },
 });
 
-const PerpsConfirmScreen = (props: React.ComponentProps<typeof Confirm>) => {
+const DEFAULT_SHOW_PERPS_HEADER = true;
```
Comment (abretonc7s) [inline app/components/UI/Perps/routes/index.tsx]: maybe a perps config value not in the file

**Review by abretonc7s — DISMISSED** [review]

**Review by abretonc7s — APPROVED** [review]

File: app/components/UI/Perps/routes/index.tsx (hunk 2 above)
Comment (michalconsensys) [reply app/components/UI/Perps/routes/index.tsx]: Resolved in https://github.com/MetaMask/metamask-mobile/pull/25601/commits/71b114b07f597486b82a45787444090d36030e25

File: app/components/UI/Perps/hooks/usePerpsNavigation.ts (hunk 1 above)
Comment (michalconsensys) [reply app/components/UI/Perps/hooks/usePerpsNavigation.ts]: Resolved in https://github.com/MetaMask/metamask-mobile/pull/25601/commits/71b114b07f597486b82a45787444090d36030e25
