### PR TITLE
fix: double press interaction on android cp-7.54.0

### LINKED ISSUE #18147: [Bug]: Button not firing onPress consistently on Android
### Describe the bug

On Android, when navigating to a scrollable asset or network list, the buttons sometimes do not fire onPress. This is a known bug from https://github.com/facebook/react-native/issues/34999 

### Expected behavior

onPress should be fired regardless of platforms

### Screenshots/Recordings

https://github.com/user-attachments/assets/05098185-7074-4a94-9ba1-33b989d9cef5

### Steps to reproduce

Please see recording

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

v7.51 + 

### Build type

None

### Device

All Android devices

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #18704: [Bug]: OnPress is called twice in ButtonBase
### Describe the bug

OnPress is called twice in the recent ButtonBase component update.
https://github.com/MetaMask/metamask-mobile/pull/18104#discussion_r2296998360

The issue is causing some weird behavior during seedless onboarding flow and change password flow in 7.53.0.
The changes is reverted in 7.53.0 but the issue is still exist in 7.54.0 and 7.55.0
https://github.com/MetaMask/metamask-mobile/issues/18614
https://github.com/MetaMask/metamask-mobile/issues/18616
https://github.com/MetaMask/metamask-mobile/issues/18615

https://github.com/MetaMask/metamask-mobile/issues/18460

### Expected behavior

OnPress should be only called once

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/pull/18104#discussion_r2296998360

### Steps to reproduce

1. Build android with IS_TEST='false'
2.Login with SeedlessOnboarding flow
3.Change Password

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.54.0, 7.55.0

### Build type

None

### Device

POCO F6

### Operating system

Android

### Additional context

_No response_

### Severity

- This will break some function that would fail if called twice such as seedless onboarding

### PR DESCRIPTION
**Pull request by brianacnguyen**
## **Description**
- This PR removes the double onPress interaction on Android (Tap + onPress both being triggered)

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/18704

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by ieow** [comment]
This pr is also solution for 
https://github.com/MetaMask/metamask-mobile/issues/18616
https://github.com/MetaMask/metamask-mobile/issues/18614

**Review by georgewrmarshall — COMMENTED** [review]
Hey @brianacnguyen, This implementation appears functional but the approach seems overly complex. I'm seeing both gesture handler workarounds and timestamp based debouncing being used together. Won't this coordination logic add overhead to every button press? It seems like we're layering a workaround on top of another workaround. If this is our path forward, do we have a ticket to upgrade to the version of react native that includes the fix and a ticket to refactor this once we've upgraded? I'd recommend getting a @MetaMask/mobile-platform engineer to review this, as they likely have more context on the Android touch event issues and can assess whether this complexity is necessary.

https://github.com/user-attachments/assets/738fbd4e-3407-4c4a-9b22-336c33c33ed4

**Comment by brianacnguyen** [comment]
> Hey @brianacnguyen, This implementation appears functional but the approach seems overly complex. I'm seeing both gesture handler workarounds and timestamp based debouncing being used together. Won't this coordination logic add overhead to every button press? It seems like we're layering a workaround on top of another workaround. If this is our path forward, do we have a ticket to upgrade to the version of react native that includes the fix and a ticket to refactor this once we've upgraded? I'd recommend getting a @MetaMask/mobile-platform engineer to review this, as they likely have more context on the Android touch event issues and can assess whether this complexity is necessary.
> 
>  testing720.mov

yes it is overly complex because it's trying to solve a system bug while trying to keep accessibility up. It is not ideal but it is contained to android only and it is what we have to do for the time being until the fix is merged and hotfixed on react-native's side. @wachunei can you help address his concern?

**Comment by ieow** [comment]
Hi @brianacnguyen ,
Since this solutions are complex and seems need more efforts to clean it up.
Is it possible we forgo the accessibilty for now by removing one of the onPress in order to meet 7.54.0 deadline as this is a blocker for a number of issues.
You can then work for a proper solution for this.

**Comment by brianacnguyen** [comment]
> Hi @brianacnguyen , Since this solutions are complex and seems need more efforts to clean it up. Is it possible we forgo the accessibilty for now by removing one of the onPress in order to meet 7.54.0 deadline as this is a blocker for a number of issues. You can then work for a proper solution for this.

I'll wait for @wachunei to answer this. If he approves, I'll create a separate PR to just remove the onPress

File: app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx [hunk 1]
```diff
@@ -110,15 +131,19 @@ const ButtonBase = ({
...
-      ? onPress
-      : isDisabled
-      ? undefined
-      : onPress;
+  // Option 3C: Universal coordination system
+  // All platforms use coordination logic to prevent double firing from any source
+  const conditionalOnPress = isDisabled
+    ? undefined
+    : (_pressEvent?: GestureResponderEvent) => {
+        const now = Date.now();
```
Comment (tommasini) [inline app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx:143]: Wondering instead of date, we could use a mutex logic here, since we want to prevent double tap, if I'm thinking correctly mutex logic would prevent that, instead of relying on timings

Comment (tommasini) [reply app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx:143]: Nevermind that would be for async operations

File: app/component-library/components/List/ListItemSelect/ListItemSelect.tsx [hunk 2]
```diff
@@ -25,10 +25,21 @@ const TouchableOpacity = ({
...
+  // Simple pass-through to main component coordination
+  // Main component handles ALL coordination logic
+
+  // Gesture detection for ScrollView compatibility on Android
+  // Sets timestamp FIRST, then calls parent function
   const tap = Gesture.Tap()
     .runOnJS(true)
+    .shouldCancelWhenOutside(false)
+    .maxDeltaX(20) // Allow some movement while tapping
+    .maxDeltaY(20)
```
Comment (tommasini) [inline app/component-library/components/List/ListItemSelect/ListItemSelect.tsx:42]: Would this be the solution for the press on scroll view right?

Comment (brianacnguyen) [reply app/component-library/components/List/ListItemSelect/ListItemSelect.tsx:42]: yes

**Review by georgewrmarshall — APPROVED** [review]
Nice work tackling this! Approving the design system changes to unblock release. I’ll defer to @MetaMask/mobile-platform engineers on the React Native and iOS/Android details of this fix. There also seem to be some Cursor/Copilot comments that could be addressed
