### PR TITLE
fix: fix approve flow on swap

### LINKED ISSUE #10834: [Bug]: Approve button disabled for Approvals of ERC20 tokens
### Describe the bug

This issue was already opened here: https://github.com/MetaMask/metamask-mobile/issues/6654
It has since been closed, however it is clearly still an issue 

Behaviour: 
- Approvals are impossible to complete with the Metamask mobile application due to the Approval button being disabled.  
- The same wallet being used via the metamask browser extension is able to complete the Approval just fine.

### Expected behavior

I should be able to approve the transaction, however the approve button is disabled 🙅

### Screenshots/Recordings

Recording:
https://github.com/user-attachments/assets/7d2cb0f7-b346-4111-a59c-8572d6047b04

### Steps to reproduce

- connect to UniSwap (i did so using WalletConnect, may or may not be relevant)
- initiate a transaction [that requires Approval](https://support.uniswap.org/hc/en-us/articles/8120520483085-What-is-an-approval-transaction) (first time you're interacting with a token, you can revoke previous approvals via something like revoke.cash) 
- receive the eth_sendTransaction request to perform the approval 

### Error messages or log output

```shell
Approve button is disabled
```

### Detection stage

In production (default)

### Version

7.28.1

### Build type

None

### Device

Pixel 6, OS 15

### Operating system

Android

### Additional context

As this is expected behaviour the first time you're interacting with a token via the uniswap protocol, it means this will affect ALL users and completely block them from being able to use this sort of service. 

In my opinion, this is **High** in terms of severity.

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR to fix the approve flow when users swap tokens.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/10834

## **Manual testing steps**

1. Switch to base network
2. Swap WETH against any other token, exp USDC
3. See approval screen; it should have the buttons enabled and you should be able to see token icon and spending cap

### **Before**

https://github.com/user-attachments/assets/d8be6306-be74-4c6c-8463-567f35ee891e

### **After**

https://github.com/user-attachments/assets/8382cc83-e4e7-42ce-b913-fcac7e906d4b

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/confirmations/components/ApproveTransactionReview/index.js [hunk 1]
```diff
@@ -384,7 +384,10 @@ class ApproveTransactionReview extends PureComponent {
       decodeApproveData(data);
     const encodedDecimalAmount = hexToBN(encodedHexAmount).toString();
 
-    const contract = tokenList[safeToChecksumAddress(to)];
+    // The tokenList addresses we get from state are not checksum addresses
+    // also, the tokenList we get does not contain the tokenStandard, so even if the token exists in tokenList we will
+    // need to fetch it using getTokenDetails
+    const contract = tokenList[to];
```
Comment (sahar-fehri) [inline app/components/Views/confirmations/components/ApproveTransactionReview/index.js:390]: The reason why this error was triggered with WETH initially is because the address of Weth is `0x4200000000000000000000000000000000000006` and its the same address when you apply `safeToChecksumAddress`;
For any other token; exp DAI; the contract would be `undefined` even though it exists in `tokenList` and the code would go into if(!contract) and fetch details.

Comment (sahar-fehri) [reply app/components/Views/confirmations/components/ApproveTransactionReview/index.js:390]: Maybe we can do sth like this too
`const contract = tokenList[to] || tokenList[safeToChecksumAddress (to)]`
Still not sure what was the case of adding safeToChecksumAddress in the first place

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by andreahaku — DISMISSED** [review]
LGTM

File: app/components/Views/confirmations/components/ApproveTransactionReview/index.js (hunk 1 above)
Comment (tommasini) [reply app/components/Views/confirmations/components/ApproveTransactionReview/index.js:390]: This maybe was something that was missed when migrating the token list endpoint, what is not making super sense to me because I believe the change was only to no target the coin gecko endpoint directly. Can we check with the api team if there was any change around this?
I will approve it!

**Review by tommasini — DISMISSED** [review]

**Review by andreahaku — DISMISSED** [review]
LGTM

**Review by NicolasMassart — CHANGES_REQUESTED** [review]
Tests are missing

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by davibroc — DISMISSED** [review]
I tested it and it works now

File: app/components/Views/confirmations/components/ApproveTransactionReview/index.test.tsx [hunk 2]
```diff
@@ -74,4 +94,60 @@ describe('ApproveTransactionModal', () => {
     );
     expect(toJSON()).toMatchSnapshot();
   });
+
+  it('render matches snapshot when tokenList is defined', () => {
```
Comment (NicolasMassart) [inline app/components/Views/confirmations/components/ApproveTransactionReview/index.test.tsx:98]:
```suggestion
  it('"Approve" button enabled when tokenList is defined', () => {
```

Comment (NicolasMassart) [inline app/components/Views/confirmations/components/ApproveTransactionReview/index.test.tsx:98]: S: Add another similar test but to check approve is disabled when no tokens in list. and call it `"Approve" button is disabled when no tokenList`

Comment (sahar-fehri) [reply app/components/Views/confirmations/components/ApproveTransactionReview/index.test.tsx]: updated the tests 🙏

**Review by NicolasMassart — COMMENTED** [review]
Only one comment on the second test, make sure you are not adding useless actions or missing testing them

File: app/components/Views/confirmations/components/ApproveTransactionReview/index.test.tsx [hunk 3]
```diff
@@ -148,6 +150,71 @@ describe('ApproveTransactionModal', () => {
...
+        <ApproveTransactionModal
+        onConfirm={mockOnConfirm}
+        />
+      ),
+      { name: 'Approve' },
+      { state },
+    );
+
+    expect(mockGetTokenDetails).toHaveBeenCalled();
+    fireEvent.press(getByTestId('Confirm'));
```
[the remark this answers is not in the document]
Comment (sahar-fehri) [reply app/components/Views/confirmations/components/ApproveTransactionReview/index.test.tsx]: Oh i ve already removed it in here [3cb2d4d](https://github.com/MetaMask/metamask-mobile/pull/11532/commits/3cb2d4daa9dfcb5e3d5e8e23d69d1cdcece19a1a) before checking your comment ^^"

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.
Thanks for all the changes you made and you patience!
