### PR TITLE
fix: cp-7.51.1 "send" deeplink regression

### LINKED ISSUE #17402: [Bug]: Send flow deeplinks not initiating confirmations
### Describe the bug

After `7.47.0` send flow deeplinks not working anymore, deeplinks are triggering another modal. Please see recordings below

### Expected behavior

Send flow deeplinks should work as before.

### Screenshots/Recordings

`7.47.0` => works as expected

https://github.com/user-attachments/assets/2c9ea7e4-4e52-458f-a6fe-153df4071ca1

`7.50.0` => not working anymore, triggering another modal

https://github.com/user-attachments/assets/ba8a160f-1c77-49d1-8e4b-c17abe18f514

### Steps to reproduce

1. Open "https://metamask.github.io/metamask-deeplinks/" in Safari
2. Select "Payment Request", then select "Eth payment"
3. Type any address and amount
4. Click link - this should open a transaction confirmation.

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.50.0

### Build type

None

### Device

iPhone 13 Mini

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by weitingsun**
## **Description**
Payment request link generated by deeplink generator is not working. Example links:
old domain: https://metamask.app.link/send/0x16867bc2567367406dbc8ee4fcba425b88ec349c%20?value=1e12
new domain: https://link.metamask.io/send/0x16867bc2567367406dbc8ee4fcba425b88ec349c%20?value=1e12

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: #17402 

## **Manual testing steps**

1. Pull down this PR locally
2. Go to deeplink generator and generate a payment request link or use the links provided in the description
3. Deeplink into the app
4. Should see expected deeplink modal and the app should redirect to send flow 

### **Before**

Android Before
iOS before

### **After**
Android after
iOS after

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/DeeplinkManager/ParseManager/handleUniversalLink.ts [hunk 1]
```diff
@@ -163,6 +164,43 @@ async function handleUniversalLink({
...
     instance._handleBrowserUrl(urlObj.href, browserCallBack);
+  } else if (action === SUPPORTED_ACTIONS.SEND) {
+    let deeplinkUrl = urlObj.href;
+
+    switch (urlObj.hostname) {
+      case MM_UNIVERSAL_LINK_HOST:
+        // Handle both /send and /send/ patterns
+        deeplinkUrl = urlObj.href.replace(
+          new RegExp(
+            `^${PROTOCOLS.HTTPS}://${MM_UNIVERSAL_LINK_HOST}/${action}/?`,
```
Comment (Cal-L) [inline app/core/DeeplinkManager/ParseManager/handleUniversalLink.ts]: Remove switch case and use `urlObj.hostname` in the replace instead

File: app/core/DeeplinkManager/ParseManager/handleUniversalLink.ts [hunk 2]
```diff
@@ -163,6 +164,43 @@ async function handleUniversalLink({
...
+          ),
+          PREFIXES[ACTIONS.SEND],
+        );
+        break;
+      default:
+        // No transformation needed for unsupported hosts
+        break;
+    }
+    // loops back to open the link with the right protocol
+    instance.parse(deeplinkUrl, { browserCallBack, origin: urlObj.origin });
```
Comment (Cal-L) [inline app/core/DeeplinkManager/ParseManager/handleUniversalLink.ts]: Remove `browserCallback`

Comment (Cal-L) [reply app/core/DeeplinkManager/ParseManager/handleUniversalLink.ts]: `origin` was an old input that was mislabeled. The more accurate term is `source` since it refers to the source from where the deeplink is coming from. Let's add a `source` input to `handleUniversalLink` function and pass it through here.

**Review by Cal-L — DISMISSED** [review]
LGTM!

**Review by Cal-L — APPROVED** [review]
LGTM
