### PR TITLE
fix: add retries on solana discovery fail cp-7.47.0

### LINKED ISSUE #15965: [Bug]: Import SRP flow - Only Account 1 is restored, closing the app and reopening causes onboarding screen to appear again
### Describe the bug

This issue is present only on Android, two latest RC v7.47.0 (1914) and v7.47.0 (1911) 

It is not present in v7.47.0 (1904) and previous versions.

When importing an SRP with multiple accounts:

1. The password screen shows up after creating new password
2. Only Account 1 is restored
3. Closing the app and re-opening causes the onboarding screen to appear again and SRP needs to be imported once more

After this, everything works as expected, but now the import SRP flow needs to be done twice.

### Expected behavior

- No password screen to show up after importing SRP and creating a new password
- All accounts to be restored
- No onboarding screen to appear after closing and re-opening the app

### Screenshots/Recordings

https://www.loom.com/share/712bd49005ce473f8edb75a16ffe2ad2?sid=3e08a19b-c7c3-4a26-9356-642b7cc39fcf

### Steps to reproduce

1. Import SRP with multiple accounts with funds
2. Type the new password
3. Notice password screen appears
4. Notice only Account 1 is restored
5. Close the app and reopen it
6. Notice onboarding screen appears again
7. Import SRP again
8. Notice password screen does not appear anymore
9. Notice all accounts are restored

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.47.0 

### Build type

None

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by PatrykLucka**
## **Description**

Solana account discovery failure was breaking the entire wallet creation/restoration flow, causing users to get locked out and restart onboarding.

**Key Changes:**
1. Non-blocking Discovery: Solana account discovery now runs asynchronously and can't break wallet creation
2. Automatic Retries: Built-in exponential backoff retry (3 attempts, up to 10s delay)
3. Persistent Retry: If all immediate retries fail, it stores a flag and retries on next app unlock
4. Clean Success: Removes retry flags when discovery succeeds

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15965
Jira ticket: https://consensyssoftware.atlassian.net/browse/MUL-251

## **Manual testing steps**
1. Import SRP with multiple accounts with funds
2. Type the new password
3. Password screen should not appear
4. If only 1 accounts has been created, after few seconds other accounts should be restored as well

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/Authentication/Authentication.ts [hunk 1]
```diff
@@ -92,20 +92,61 @@ class AuthenticationService {
...
-      WalletClientType.Solana,
-      {
-        setSelectedAccount: false,
-      },
-    );
-    await client.addDiscoveredAccounts(primaryHdKeyringId);
+    this.attemptSolanaAccountDiscovery().catch((error) => {
+      console.warn('Solana account discovery failed during wallet creation:', error);
+      // Store flag to retry on next unlock
+      StorageWrapper.setItem('SOLANA_DISCOVERY_PENDING', 'true');
```
Comment (gantunesr) [inline app/core/Authentication/Authentication.ts]: Why do you need to keep this in storage? Can't we set a property in the class instead?

File: app/core/Authentication/Authentication.ts [hunk 2]
```diff
@@ -92,20 +92,61 @@ class AuthenticationService {
...
     ///: END:ONLY_INCLUDE_IF
+    
     password = this.wipeSensitiveData();
     parsedSeed = this.wipeSensitiveData();
   };
 
+  ///: BEGIN:ONLY_INCLUDE_IF(solana)
+  private attemptSolanaAccountDiscovery = async (retryCount = 0): Promise<void> => {
+    const maxRetries = 3;
+    const retryDelay = Math.min(1000 * Math.pow(2, retryCount), 10000); // Exponential backoff, max 10s
```
Comment (owencraston) [inline app/core/Authentication/Authentication.ts]: It would be nice to create a util for the exponential backup logic. That way we can reuse it and test it better.

File: app/core/Authentication/Authentication.ts (hunk 1 above)
Comment (owencraston) [inline app/core/Authentication/Authentication.ts]: this should be added as a constant in app/constants/storage.ts

File: app/core/Authentication/Authentication.ts [hunk 3]
```diff
@@ -92,20 +92,61 @@ class AuthenticationService {
...
+      } else {
+        console.error('Solana account discovery failed after all retries');
+        // Keep the pending flag so we can retry on next unlock
+      }
+    }
+  };
+
+  private retrySolanaDiscoveryIfPending = async (): Promise<void> => {
+    try {
+      const isPending = await StorageWrapper.getItem('SOLANA_DISCOVERY_PENDING');
```
Comment (gantunesr) [inline app/core/Authentication/Authentication.ts]: ok, I see that the uncovered code is related to the access to storage in some parts of the code, if we're keeping this then we should add the proper test to cover the edge cases

File: app/core/Authentication/Authentication.ts [hunk 4]
```diff
@@ -92,20 +92,61 @@ class AuthenticationService {
...
+      await StorageWrapper.removeItem('SOLANA_DISCOVERY_PENDING');
+    } catch (error) {
+      console.warn(`Solana account discovery attempt ${retryCount + 1} failed:`, error);
+      
+      if (retryCount < maxRetries) {
+        setTimeout(() => {
+          this.attemptSolanaAccountDiscovery(retryCount + 1);
+        }, retryDelay);
+      } else {
+        console.error('Solana account discovery failed after all retries');
```
Comment (owencraston) [inline app/core/Authentication/Authentication.ts]: should we log the error here?

File: app/core/Authentication/Authentication.ts (hunk 1 above)
Comment (PatrykLucka) [reply app/core/Authentication/Authentication.ts]: We want to persist it across the app lifecycle events. This is mainly for trying again with next application unlocking/opening. Closing the app can destroy the class state.

**Review by owencraston — APPROVED** [review]
Tested and the bug seems to be resolved. I am not sure if I tested the exponential retry since it appeared to work the first time but overall the code and tests look good to me.

https://github.com/user-attachments/assets/7aec8b72-fc98-491f-b586-9291d7fa62e3
