### PR TITLE
Transaction components

### LINKED ISSUE #1473: iOS Crash after editing gas price that dapp suggested
DeFiDad reported

Using hegic.co

It seems to suggest a gas price to metamask.
When the user then opens advanced gas controls and tries to edit the gas price, MetaMask crashes.

### LINKED ISSUE #1497: Create transaction fee summary component
The task is to create a component for the transaction fee summary card we currently use in the app and that is used in the new [confirmation designs](https://www.figma.com/file/dzapXt5s0pKBxb9lZkIoDM/%231352---Confirm-transactions?node-id=916%3A156):

Screenshot from 2020-04-20 14-33-44

Create the unconnected component and snapshot tests. Use it in `metamask-mobile/app/components/Views/SendFlow/Confirm/index.js`

### LINKED ISSUE #1499: Create transaction data modal
The task is to create the new data modal being used across the latest confirmation designs:

Screenshot from 2020-04-20 15-24-49

For now, this can be implemented to replace the data section of the Approve screens:

Screenshot from 2020-04-20 15-32-29

(Code for that screen: `metamask-mobile/app/components/Views/ApproveView/Approve/index.js`)

Designs: https://www.figma.com/file/dzapXt5s0pKBxb9lZkIoDM/%231352---Confirm-transactions?node-id=916%3A101

### LINKED ISSUE #1500: Redesign transaction fee edit modal
Current transaction fee modal looks like:

Screenshot from 2020-04-20 15-59-25
-
Screenshot from 2020-04-20 15-59-59

This task is to redesign this to:

Screenshot from 2020-04-20 15-34-10

Designs: https://www.figma.com/file/dzapXt5s0pKBxb9lZkIoDM/%231352---Confirm-transactions?node-id=916%3A192

You should be able to use `metamask-mobile/app/components/UI/CustomGas/index.js`

For this task, replace the modal on the approve screen with the redesigned modal

----

Also, make sure to add an error box to the advanced screen if either gas limit is too low or the user has insufficient balance:

Screenshot from 2020-04-20 16-33-13

### PR DESCRIPTION
**Pull request by EtDu**
**Description**

Create components for transactions created from dApps redesign. #1501 

**Checklist**

- [x] Create `TransactionReviewFeeCard` component
- [x] `TransactionReviewFeeCard` create snapshot test
- [x] `Confirm`: Use `TransactionReviewFeeCard`
- [x] `CustomGas`: implement custom gas modal redesign
- [x] `Confirm` & `Approve`: use new `CustomGas`
- [x] Add in fix for #1473
- [x] Fix gas error not updating properly

**Issue**

Resolves #1497
Resolves #1500 
Resolves #1473

### CODE REVIEW

**Comment by EtDu** [comment]
Screen Shot 2020-04-27 at 11 59 56 AM
primaryCurrency = FIAT

Screen Shot 2020-04-27 at 11 59 25 AM
primaryCurrency = ETH

@cjeria is this what you had in mind?

**Comment by EtDu** [comment]
Screen Shot 2020-04-29 at 1 52 53 PM

Basic network fee selection

File: app/components/Views/SendFlow/CustomGas/index.js [hunk 1]
```diff
@@ -97,38 +155,62 @@ const styles = StyleSheet.create({
...
-		marginRight: 8
-	}
+	footerContainer: {
+		flexDirection: 'row',
+		alignItems: 'flex-end'
+	},
+	buttonNext: {
+		flex: 1
+	},
+	radio: {}
```
Comment (estebanmino) [inline app/components/Views/SendFlow/CustomGas/index.js:213]: I think you can remove this

File: app/components/Views/SendFlow/CustomGas/index.js [hunk 2]
```diff
@@ -398,57 +492,101 @@ class CustomGas extends PureComponent {
...
+				</View>
+			</View>
+		);
+	};
+
+	renderGasError = () => {
+		const { warningGasLimit, warningGasPrice } = this.state;
+		const { gasError } = this.props;
+		let gasErrorMessage;
+		if ((warningGasLimit && warningGasPrice) || warningGasPrice) {
```
Comment (estebanmino) [inline app/components/Views/SendFlow/CustomGas/index.js:534]: isn't this equivalent to `if (warningGasPrice)` ?

File: app/components/Views/SendFlow/CustomGas/index.js [hunk 3]
```diff
@@ -398,57 +492,101 @@ class CustomGas extends PureComponent {
...
+			gasErrorMessage = warningGasPrice;
+		} else if (warningGasLimit) {
+			gasErrorMessage = warningGasLimit;
+		}
+		return (
+			<View style={styles.warningWrapper}>
+				<View style={[styles.warningTextWrapper, !gasError ? styles.invisible : null]}>
```
Comment (estebanmino) [inline app/components/Views/SendFlow/CustomGas/index.js:541]: what about not returning any component if there's no error? I don't know if this is using space on the view even though is rendering nothing

**Review by estebanmino — COMMENTED** [review]
added small comments, looks good!

File: app/components/Views/SendFlow/CustomGas/index.js (hunk 1 above)
Comment (EtDu) [reply app/components/Views/SendFlow/CustomGas/index.js:213]: missed that, I wonder if the linter could pick up on empty styles

File: app/components/Views/SendFlow/CustomGas/index.js (hunk 2 above)
Comment (EtDu) [reply app/components/Views/SendFlow/CustomGas/index.js:534]: Yes, double logic at its finest

File: app/components/Views/SendFlow/CustomGas/index.js (hunk 3 above)
Comment (EtDu) [reply app/components/Views/SendFlow/CustomGas/index.js:541]: It is using space on the view on purpose, that's why I hide and show it with `opacity: 0`. If it doesn't initially take space, then when the error appears it will push everything else upward- which doesn't look good. 

Let me know however if this is the desired effect

File: app/components/Views/SendFlow/Confirm/index.js [hunk 4]
```diff
@@ -517,29 +503,30 @@ class Confirm extends PureComponent {
...
-				modalVisible={customGasModalVisible}
-				confirmText={strings('transaction.set_gas')}
-				cancelText={strings('transaction.cancel_gas')}
-				onCancelPress={this.toggleCustomGasModal}
-				onRequestClose={this.toggleCustomGasModal}
-				onConfirmPress={this.handleSetGasFee}
-				confirmDisabled={!!gasError}
-				cancelButtonMode={'neutral'}
-				confirmButtonMode={'confirm'}
+			<Modal
```
Comment (estebanmino) [inline app/components/Views/SendFlow/Confirm/index.js:506]: I wonder why you didn't use `ActionModal` here, you can disable the cancel button if you want and add a style prop there to put it on the bottom of the screen. In terms of reusability of components, now if we change the color of these models, we'll have to change this one separately from the others.
Same comment for https://github.com/MetaMask/metamask-mobile/pull/1512/files#diff-1d09ed350c73498ec258583166d70e87R461

Comment (estebanmino) [reply app/components/Views/SendFlow/Confirm/index.js:506]: I mean is working and already approved, but I think we can reuse things here

Comment (EtDu) [reply app/components/Views/SendFlow/Confirm/index.js]: Cool, resolved

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Overall this looks and feels pretty solid across both OS's and multiple screen sizes! 

Only noticed two issues:

**Issue 1:**

When I edit network fee and go to advanced, I'm still able to tap save when I do not have anything entered in the gas limit input field

seen here = https://recordit.co/3sK3vd9Jt5

Screen Shot 2020-06-04 at 10 16 37 PM

When I tap send, I then get the error

Screen Shot 2020-06-04 at 10 18 00 PM

**Issue 2:** 

Continuing from issue one, when I get into this state and click Edit again and attempt to change to either slow/average/fast and tap save, the advanced section doesn't update thus I still have a network fee of $0.00.  Is the value supposed to update after saving gas speed? 

Seen here = https://recordit.co/c2F2d2tvA4

I'm sure the fix for one will ultimately fix issue 2 as they're related.

**Review by ibrahimtaveras00 — APPROVED** [review]
Fix looks good on both OS's, QA Passed 👍

**Review by estebanmino — APPROVED** [review]
🚀
