### PR TITLE
fix: only remove SES from exception if exception exists

### LINKED ISSUE #9221: TypeError: undefined is not an object (evaluating 'e.exception.values[0].stacktrace.frames')
Sentry Issue: [METAMASK-MOBILE-2AJ8](https://metamask.sentry.io/issues/5086040304/?referrer=github_integration)

```
TypeError: undefined is not an object (evaluating 'e.exception.values[0].stacktrace.frames')
  at removeSES (app/util/sentry/utils.js:94:55)
  at rewriteReport (app/util/sentry/utils.js:104:5)
  at init (app/util/sentry/utils.js:229:31)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by leotm**
## **Description**

Follow-up to
- https://github.com/MetaMask/metamask-mobile/pull/8584

There's been a recent spike in errors throwing at

https://github.com/MetaMask/metamask-mobile/blob/11ce2f3678039a73b20d5cc6e07782c5604ae24f/app/util/sentry/utils.js#L94-L95

This change ensures the error exists, before removing SES from the stack trace frame

In a similar manner to how we've been doing it in

https://github.com/MetaMask/metamask-mobile/blob/11ce2f3678039a73b20d5cc6e07782c5604ae24f/app/util/sentry/utils.js#L44-L51

This doesn't impact users and will help assess the underlying error causing the spike

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/9221

## **Manual testing steps**

Same as: https://github.com/MetaMask/metamask-mobile/pull/8584

## **Screenshots/Recordings**

Screenshot 2024-06-06 at 4 27 36 PM

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/sentry/utils.js [hunk 1]
```diff
@@ -92,11 +92,13 @@ function removeDeviceName(report) {
  * @param {*} report - the error event
  */
 function removeSES(report) {
-  const stacktraceFrames = report.exception.values[0].stacktrace.frames;
-  const filteredFrames = stacktraceFrames.filter(
-    (frame) => frame.filename !== 'app:///ses.cjs',
-  );
-  report.exception.values[0].stacktrace.frames = filteredFrames;
+  if (report.exception && report.exception.values) {
+    const stacktraceFrames = report.exception.values[0].stacktrace.frames;
```
Comment (NicolasMassart) [inline app/util/sentry/utils.js:96]: C: would it be useful to also make sure that stacktrace and frames are populated? or use optional on them and fallback?

**Review by tommasini — APPROVED** [review]
Awesome!
