### PR TITLE
fix: cp-7.47.0 add loader if account balance is not defined 

### LINKED ISSUE #15396: [Bug]: Solana balances are undefined for some time on the account menu list
### Describe the bug

Balances load after 2-4s, but in the meantime, they are showing up as undefined.

### Expected behavior

While the balance loads we should show a loading indicator

### Screenshots/Recordings

Image

### Steps to reproduce

1. import a wallet with a SOL balance on Android (android is slower so its easier to notice)
2. view Solana account
3. open the accounts list on the wallet view
4. notice the balance is rendered as undefined for a few seconds

### Error messages or log output

```shell

```

### Detection stage

In public beta

### Version

7.47.0

### Build type

Beta

### Device

Android

### Operating system

Android, iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

This PR adds a loading indicator while the balance is being fetched, instead of showing `undefined`.

## **Related issues**

Fixes: #15396 

## **Manual testing steps**

1. Go Account list
2. check the balance

**in order to reproduce , you can test on android and create a slow device emulator, then add a new Solana account**

### **Before**

Screenshot 2025-06-03 at 10 52 41

### **After**

Screenshot 2025-06-03 at 10 52 34

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Prithpal-Sooriya — APPROVED** [review]

File: app/components/hooks/useMultichainBalances/useMultichainBalancesForAllAccounts.ts [hunk 1]
```diff
@@ -112,6 +112,9 @@ const useMultichainBalancesForAllAccounts =
           ),
           isPortfolioVieEnabled: isPortfolioEnabled,
           aggregatedBalance: getAggregatedBalance(account),
+          // if the totalNativeTokenBalance is undefined, it means that the account is loading
+          isLoadingAccount:
+            accountBalanceData.totalNativeTokenBalance === undefined,
```
Comment (Prithpal-Sooriya) [inline app/components/hooks/useMultichainBalances/useMultichainBalancesForAllAccounts.ts:117]: Nice fix!

Debating if we could have added a check inside the component for this, but I think the hook is a good place in case of reuse.

Comment (salimtb) [reply app/components/hooks/useMultichainBalances/useMultichainBalancesForAllAccounts.ts:117]: same, I thought of the reuse case and that's why I put it here

**Review by OGPoyraz — APPROVED** [review]
