### PR TITLE
fix: cp-7.41.0 fix main aggregated account balance

### LINKED ISSUE #13478: [Bug]: When in the "Popular Networks" view, the overall displayed balance does not align with the aggregate value of the assets listed
### Describe the bug

When in the "Popular Networks" view, the overall displayed balance does not align with the aggregate value of the assets listed. Only for the mainnet the correct balance is shown.

### Expected behavior

The total balance accurately reflects the sum of assets within this view 

### Screenshots/Recordings

Image

https://github.com/user-attachments/assets/719ec157-dbe0-43b9-81b5-f3dd1eefe232

### Steps to reproduce

1. Switch to `Popular networks` view
2. Compare balance for the account value and the value of all tokens

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.40.0(1551)

### Build type

None

### Device

iPhone 15

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

fixes main aggregated balance
## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/13478

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sleepytanya** [comment]
@sahar-fehri 

Builds: https://app.bitrise.io/build/5e1c8dc2-334d-486f-be04-3152b8c1f142?tab=artifacts
Balance looks good for all networks except Linea:



https://github.com/user-attachments/assets/ad02cdcb-f423-4582-abb0-0a26c0574788

File: app/selectors/tokensController.ts [hunk 1]
```diff
@@ -92,6 +93,8 @@ export const getChainIdsToPoll = createDeepEqualSelector(
     return Object.keys(networkConfigurations).filter(
       (chainId) =>
         chainId === currentChainId ||
+        chainId === ChainId.mainnet ||
+        chainId === ChainId['linea-mainnet'] ||
         popularNetworksChainIds.includes(chainId as Hex),
```
Comment (sahar-fehri) [inline app/selectors/tokensController.ts:98]: The main balance works when the user is on mainnet but it was missing some balances when the user in on another network with popularNetworks selected.
Popular network list does not include mainnet and linea mainnet which resulted is main balances not including mainnet and linea balances when the user is on a popular network.

**Comment by sleepytanya** [comment]
@sahar-fehri 
Fixed in the latest commit:


https://github.com/user-attachments/assets/9859d8a8-9054-4b46-9eaf-0e52411b299c

**Review by salimtb — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
