### PR TITLE
fix: fix asset options sheet

### LINKED ISSUE #12660: [Bug]: App error when navigating to token details page
### Describe the bug

When the user navigates to token details page, app crashes.

### Expected behavior

Navigate successfully to token details

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Click on any asset
2. Click on options top right
3. See error

### Error messages or log output

```shell
Cannot read property of undefined
```

### Detection stage

On main branch

### Version

7.38

### Build type

None

### Device

Android pixel pro 5

### Operating system

Android

### Additional context

https://github.com/user-attachments/assets/62f1c76a-6ded-4469-932b-d1bbe2bddccc

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR to fix options displayed in Asset Options bottom sheet.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12660#issuecomment-2576418131

## **Manual testing steps**

1. Click on a native token on any network
2. Click on asset options button on top right
3. Notice that you should not see "Token Details" option

### **After**

https://github.com/user-attachments/assets/db23c1df-4e2b-46cb-a0f4-ea976005d4ea

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/Asset/index.js [hunk 1]
```diff
@@ -208,7 +208,7 @@ class Asset extends PureComponent {
       networkConfigurations,
     } = this.props;
     const colors = this.context.colors || mockTheme.colors;
-    const isNativeToken = route.params.isETH;
+    const isNativeToken = route.params.isNative ?? route.params.isETH;
```
Comment (sahar-fehri) [inline app/components/Views/Asset/index.js:211]: Before PV the isETH value used to be `true` for all native tokens. After PV, `isETH` is now true for ethereum but false with other natives BNB for example, which introduced this bug.
With PV we also introduced the `isNative` param which should indicate whether a token is native or not.
The code now checks if isNative exists else fallsback to isETH

**Review by salimtb — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]
