### PR TITLE
fix: cp-7.47.0 Pass optional disabled prop into token details list item

### LINKED ISSUE #15345: [Bug]: Clicking on account balance on detailed asset page crashes app
### Describe the bug

While on the detailed asset page for Virtual Protocol a SPL token, the user clicks on the number of tokens and value and the app changes to an error page.

`View: Root
TypeError: undefined is not an object (evaluating 'Z.symbol')`

This user's wallet is also showing an incorrect (does not match the blockchain) balance for this particular asset. That was reported in (GH issue)[https://github.com/MetaMask/metamask-mobile/issues/15344]

### Expected behavior

All should work

### Screenshots/Recordings

**Asset Details Page**
Image

**Error Page**

Image

### Steps to reproduce

1. Go to the detailed asset page
2. Click on the account balance for the asset
3. Get the Crashed app

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.47.0

### Build type

Beta

### Device

iOS

### Operating system

iOS

### Additional context

_No response_

### Severity

Sev1

### PR DESCRIPTION
**Pull request by gambinish**
## **Description**

The token list item should not always be pressable on the token detail page. This was a fragment from the initial implementation of the Asset Details page.

The balance list item isn't intended to always be interactive, and should only be pressable when the token being pressed is a non native EVM asset (erc20) from the detail page. User reported getting navigated to an error screen when pressing this on certain Solana SPL tokens.

This adds the option to disable this button, making the list item read only and non-interactive. This fixes the bug reported, but also the UX papercut of having a pressable element that doesn't do anything.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15345

## **Manual testing steps**

1. Go to detail page for any token
2. Balance TokenListItem should not be pressable

### **Before**

https://github.com/user-attachments/assets/819d842a-251d-4163-beb7-70596b02220f

### **After**

https://github.com/user-attachments/assets/17385a1c-4ac9-47b2-9a48-e0d6d7a51a8d

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/AssetOverview/Balance/Balance.tsx [hunk 1]
```diff
@@ -108,23 +108,36 @@ const Balance = ({ asset, mainBalance, secondaryBalance }: BalanceProps) => {
     );
   }, [asset, styles.ethLogo]);
 
+  const isDisabled = useMemo(
+    () =>
+      asset.isETH ||
+      asset.isNative ||
```
Comment (sahar-fehri) [inline app/components/UI/AssetOverview/Balance/Balance.tsx:114]: Nit: are asset.isNative and asset.isETH redundant?
Wonder if we can we just use asset.isNative?

**Review by sahar-fehri — DISMISSED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]
