### PR TITLE
fix: fix edit network and delete network with tokenNetworkFilter

### LINKED ISSUE #13133: [Bug]: When editing a popular network name, the token list does not update
### Describe the bug

After editing a popular network name, MetaMask switched to that network, but the token list is not updated, still showing the tokens from the previously selected network. 

### Expected behavior

Token list to update

### Screenshots/Recordings

https://github.com/user-attachments/assets/77a62a7b-e372-4d49-a0c1-94953a8edb1c

### Steps to reproduce

1. Edit any popular network name, besides the currently enabled one
2. Notice the token list does not update

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.39.0

### Build type

None

### Device

Pixel 6 Pro, iPhone 15

### Operating system

Android, iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR to fix issue when a user edits a network or deletes a network. The token network filter is not correctly set.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/13133 and https://github.com/MetaMask/metamask-mobile/issues/13134

## **Manual testing steps**

1. Go to this page...
2.
3.

### **After**

Edit issue: 

https://github.com/user-attachments/assets/76608d48-70bb-4825-bfef-7af65ce9cfe6

Delete issue:

https://github.com/user-attachments/assets/bda85701-b178-4653-b1ec-6f84511a8841

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Unik0rnMaggie** [comment]
The fix works:


https://github.com/user-attachments/assets/ffeb642d-7335-4550-9ec0-bc60ffc719ec


https://github.com/user-attachments/assets/f1a9ec82-3d39-4334-9b7c-cae011438871

File: app/components/Views/NetworkSelector/RpcSelectionModal/RpcSelectionModal.tsx [hunk 1]
```diff
@@ -49,13 +51,51 @@ interface RpcSelectionModalProps {
...
   styles,
 }) => {
   const isAllNetwork = useSelector(selectIsAllNetworks);
 
+  const { navigate } = useNavigation();
+
+  const onRpcSelect = useCallback(
+    async (clientId: string, chainId: `0x${string}`) => {
+      const { NetworkController } = Engine.context;
+      const existingNetwork = networkConfigurations[chainId];
```
Comment (sahar-fehri) [inline app/components/Views/NetworkSelector/RpcSelectionModal/RpcSelectionModal.tsx:65]: In the original code there used to be a check here
`` `       if (!existingNetwork) {
        Logger.error(
          new Error(`No existing network found for chainId: ${chainId}`),
        );
        return;
      }`` ` 

I do not think it is necessary since the `ListItemSelect` component is rendered when looping on :

`` `   const rpcEndpoints =
    networkConfigurations[chainId as `0x${string}`]?.rpcEndpoints || [];`` ` 

If `networkConfigurations[chainId]` does not exist the rpcEndpoints would be an empty array

**Review by vinnyhoward — APPROVED** [review]

**Review by darkwing — APPROVED** [review]

File: app/components/Views/NetworkSelector/NetworkSelector.tsx [hunk 2]
```diff
@@ -888,6 +847,25 @@ const NetworkSelector = () => {
...
+          PreferencesController.setTokenNetworkFilter({
+            [chainId]: true,
+          });
+        } else {
+          // Remove the chainId from the tokenNetworkFilter
+          const { [chainId]: _, ...newTokenNetworkFilter } = tokenNetworkFilter;
+          PreferencesController.setTokenNetworkFilter({
+            // TODO fix type of preferences controller level
+            // setTokenNetworkFilter in preferences controller accepts Record<string, boolean> while tokenNetworkFilter is Record<string, string>
+            // eslint-disable-next-line @typescript-eslint/no-explicit-any
```
Comment (gambinish) [inline app/components/Views/NetworkSelector/NetworkSelector.tsx:863]: This must have been an oversight during development while we were hustling. No need to make this change here, but `Record<string, boolean>` makes most sense to me.

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 3]
```diff
@@ -934,6 +955,21 @@ export class NetworkSettings extends PureComponent {
...
+        PreferencesController.setTokenNetworkFilter({
+          [chainId]: true,
+        });
+      } else {
+        PreferencesController.setTokenNetworkFilter({
+          ...tokenNetworkFilter,
+          [chainId]: true,
+        });
+      }
+    }
```
Comment (gambinish) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:971]: Can't wait until we can remove this feature flag

**Review by gambinish — APPROVED** [review]

File: app/components/Views/NetworkSelector/RpcSelectionModal/RpcSelectionModal.tsx [hunk 4]
```diff
@@ -49,13 +51,51 @@ interface RpcSelectionModalProps {
...
   rpcMenuSheetRef,
   networkConfigurations,
   styles,
 }) => {
   const isAllNetwork = useSelector(selectIsAllNetworks);
 
+  const { navigate } = useNavigation();
+
+  const onRpcSelect = useCallback(
+    async (clientId: string, chainId: `0x${string}`) => {
```
Comment (tommasini) [inline app/components/Views/NetworkSelector/RpcSelectionModal/RpcSelectionModal.tsx:63]: Can we use Hex from metamask/utils?
```suggestion
    async (clientId: string, chainId: Hex) => {
```

File: app/components/Views/NetworkSelector/NetworkSelector.tsx (hunk 2 above)
Comment (tommasini) [inline app/components/Views/NetworkSelector/NetworkSelector.tsx:863]: Instead of any just a nit pick we can use the ts-expect-error and explain why it is failing and avoid casting

Comment (sahar-fehri) [reply app/components/Views/NetworkSelector/NetworkSelector.tsx:863]: I dnt think the using the `@ts-expect-error` directive workks with the `any` type errors. It would still consider the directive as unused.

**Review by tommasini — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
