### PR TITLE
[2847] Bug in token balance

### LINKED ISSUE #2847: WatchAsset method: "Add suggested token" prompt doesn't show correct balance
As an example, if your wallet did have non-zero token balance on this token, it'll still show zero.

### PR DESCRIPTION
**Pull request by gantunesr**
Bug related to a case sensitive match between the keys (address) associated with the token balance.

`0x514910771bf9ca656af840dff83e8264ecf123nm != 0x514910771BF9Ca656af840dff83E8264EcF123NM`

Fix: Case insensitive key match.

### CODE REVIEW

**Review by andrepimenta — APPROVED** [review]
LGTM! 👍

**Comment by cortisiko** [comment]
**Issue 1**

If I were to remove a token from my wallet then re-add it, the token value shows as “0”
see on [android](http://recordit.co/MsRZBiIpKa)
see on [iOS](http://recordit.co/F5MnQIruhu)

to reproduce:

- delete a saved token from your wallet (i deleted chainlink by long pressing the token then tapping delete)
- from the browser, go to coingecko.com
- search for chainlink
- scroll down a little and then tap on “more information”
- tap on the fox logo.
- notice a modal appears with the coin name. notice the coin value is incorrect.

**Review by cortisiko — CHANGES_REQUESTED** [review]
sending this guy back. found an issue

**Review by cortisiko — APPROVED** [review]
🎉 🎉 🎉 🎉

**Review by sethkfman — APPROVED** [review]
Updates LGTM

File: app/components/hooks/useTokenBalance.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
+import { useState, useEffect, Dispatch, SetStateAction } from 'react';
+import Engine from '../../core/Engine';
+import { BN } from '@metamask/controllers';
+
+/**
+ * Hook to handle the balance of ERC20 tokens
+ * @param {String} tokenAddress Token contract address
+ * @param {String} userAddress Public address which holds the token
+ * @returns {Handlers} Handlers `[balance, loading, error]`
```
Comment (Cal-L) [inline app/components/hooks/useTokenBalance.tsx:9]: Since this is TypeScript, we could remove the types from the TSDocs. 
Ref: https://github.com/microsoft/tsdoc/tree/master/tsdoc

For returns, I wasn't really sure what `Handlers` meant in this context. We could do something like:
`@returns Array that consists of [balance, loading, error]` to be more explicit.

**Review by Cal-L — CHANGES_REQUESTED** [review]
@gantunesr  Left some comments.

File: app/components/UI/WatchAssetRequest/index.js [hunk 2]
```diff
@@ -130,92 +117,115 @@ class WatchAssetRequest extends PureComponent {
...
-		);
-	}
-}
+				</View>
+			</ActionView>
+		</View>
+	);
+};
+
+WatchAssetRequest.propTypes = {
```
[the remark this answers is not in the document]
Comment (gantunesr) [reply app/components/UI/WatchAssetRequest/index.js:188]: @Cal-L I'll open another PR for the next release to convert this component to TS, for the moment I would merged as it is.

File: app/components/UI/WatchAssetRequest/index.js [hunk 3]
```diff
@@ -130,92 +117,115 @@ class WatchAssetRequest extends PureComponent {
...
-							<Text style={styles.signText}>{strings('watch_asset_request.message')}</Text>
-						</View>
+	const { asset } = suggestedAssetMeta;
 
-						<View style={styles.tokenInformation}>
-							<View style={styles.tokenInfo}>
-								<View style={styles.infoTitleWrapper}>
-									<Text style={styles.infoTitle}>{strings('watch_asset_request.token')}</Text>
-								</View>
+	const address = Object.keys(contractBalances).find(key => toLowerCaseEquals(key, asset.address));
```
[the remark this answers is not in the document]
Comment (gantunesr) [reply app/components/UI/WatchAssetRequest/index.js]: Agreed, I was thinking to pass the balance value of `contractBalances` to the hook and only fetch the new balance if the value was `undefined` but in a second thought, maybe is better to remove `contractBalances` as a dependence.

File: app/components/hooks/useTokenBalance.tsx (hunk 1 above)
Comment (gantunesr) [reply app/components/hooks/useTokenBalance.tsx]: Fixed, thanks for the reference

File: app/components/UI/WatchAssetRequest/index.js [hunk 4]
```diff
@@ -130,92 +109,107 @@ class WatchAssetRequest extends PureComponent {
...
+	const { asset } = suggestedAssetMeta;
+	let [balance] = useTokenBalance(asset.address, selectedAddress);
 
-						<View style={styles.tokenInformation}>
-							<View style={styles.tokenInfo}>
-								<View style={styles.infoTitleWrapper}>
-									<Text style={styles.infoTitle}>{strings('watch_asset_request.token')}</Text>
-								</View>
+	try {
+		balance = renderFromTokenMinimalUnit(balance, asset.decimals);
```
Comment (Cal-L) [inline app/components/UI/WatchAssetRequest/index.js:123]: Let's move this try catch logic into the `renderFromTokenMinimalUnit` function and have it return a fallback balance of 0.

cc: @gantunesr

**Review by Cal-L — CHANGES_REQUESTED** [review]
cc: @gantunesr

**Review by Cal-L — APPROVED** [review]
@gantunesr LGTM
