### PR TITLE
fix: asset overview tx list scroll on click

### LINKED ISSUE #22863: [Bug]: Activity - Clicking on a transaction to see the details from the Asset page, automatically closes the modal, not being able to check the details
**Describe the bug**

Clicking on a transaction to see the details from the Asset page, automatically closes the modal, not being able to check the details

**Screenshots/Recordings**

https://github.com/user-attachments/assets/1a69dd97-a4bf-42ee-9096-f3269121f515

**Steps to reproduce**

1. Click on an Asset which you have previously transacted
2. See the Assets page
3. Scroll down to activity
4. Click on any transaction
5. See the modal is auto closed and you are automatically scrolled to the top of the page

**Error messages or log output**

```shell

```

**Detection stage**

During release testing

**Version**

7.60.0

**Build type**

None

**Device**

Pixel 6

**Operating system**

Android

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

Add `skipScrollOnClick` prop to prevent automatic scrolling when expanding transaction details in the Asset view.

The automatic scrolling when a user clicked on a transaction to expand its details in the Asset view was disorienting. This change introduces a prop to conditionally disable this scroll behavior specifically for the Asset screen, improving user experience.

Fixes https://github.com/MetaMask/metamask-mobile/issues/22863
Fixes https://consensyssoftware.atlassian.net/browse/ASSETS-2061
Fixes https://consensyssoftware.atlassian.net/browse/ASSETS-1966
Fixes https://consensyssoftware.atlassian.net/browse/ASSETS-2109

## **Changelog**

CHANGELOG entry: fix: remove scroll on click when clicking a tx in the asset details modal

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/22863

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **After**

https://www.loom.com/share/cf4e25f1729a4b63a5b8fb64e872c886

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots. 

---
<a href="https://cursor.com/background-agent?bcId=bc-3d2ecce2-010b-4b08-854b-9e619a914564"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/open-in-cursor-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/open-in-cursor-light.svg">Open in Cursor</picture></a>&nbsp;<a href="https://cursor.com/agents?id=bc-3d2ecce2-010b-4b08-854b-9e619a914564"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/open-in-web-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/open-in-web-light.svg">Open in Web</picture></a>

---

> [!NOTE]
> Adds an optional `skipScrollOnClick` prop to `Transactions` and uses it in the Asset screen to stop auto-scrolling when expanding a transaction.
> 
> - **UI**:
>   - **Transactions (`app/components/UI/Transactions/index.js`)**:
>     - Add optional `skipScrollOnClick` prop (PropTypes + docs).
>     - Gate `scrollToIndex` on expand with `!skipScrollOnClick` to disable auto-scroll when set.
>   - **Asset View (`app/components/Views/Asset/index.js`)**:
>     - Pass `skipScrollOnClick` to embedded `Transactions` to prevent auto-scroll when expanding tx details in the Asset screen.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit eb28abd233821b5738747cba8ca8b4f98cc5ef07. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/Transactions/index.js [hunk 1]
```diff
@@ -191,6 +191,8 @@ class Transactions extends PureComponent {
      * Whether multichain accounts state 2 is enabled
      */
     isMultichainAccountsState2Enabled: PropTypes.bool,
+
+    skipScrollOnClick: PropTypes.bool,
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Transactions/index.js:198]: @cursor, can you add a little comment about this proptype?

File: app/components/UI/Transactions/index.js [hunk 2]
```diff
@@ -191,6 +191,12 @@ class Transactions extends PureComponent {
      * Whether multichain accounts state 2 is enabled
      */
     isMultichainAccountsState2Enabled: PropTypes.bool,
+    /**
+     * Whether to skip automatic scrolling when a transaction is clicked/expanded.
+     * Useful in views like Asset where the header is already visible and scrolling
+     * would be disorienting to the user.
+     */
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Transactions/index.js:197]: @cursor 
```suggestion
    /**
     * (optional) Skip automatic scrolling when a transaction is clicked/expanded.
     * Useful in views like Asset Details scrolling inside modals will cause issues (such as closing the stacked tx modal)
     */
```

**Comment by Prithpal-Sooriya** [comment]
Skipping sonar cloud since this adds like 2/3 lines of code. It is super minimal and only for 1 area of the app

**Review by sahar-fehri — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]
