### PR TITLE
fix: broken WhatsNew

### LINKED ISSUE #8553: [Bug]: What's New not displayed on Android after upgrade (no fresh install) & Multiple issues with upcoming migrations `7.16` and `7.17`
### Describe the bug

**Problem:** 
- the What's New message is not displayed on Android after an upgrade. It is displayed on iOS and also with Android fresh installs
- The What's New message is not displayed in Android nor in iOS for migrations from `7.15` to `7.16` . It is for fresh installs
- The What's New message won't be displayed in Android nor in iOS for migrations from `7.16` to `7.17` . It seems it will for fresh installs

### Expected behavior

The What's New should be displayed

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/7f43a057-792e-44a6-a618-78860ca335d7

### Steps to reproduce

1. Install 7.15 on Android 
2. Upgrade to 7.16
3. See no What's New is displayed

After checking a previous version, this seems to be also the case from 7.14 to 7.15 for Android 
cc @hesterbruikman I think this explains what you experienced a couple of days ago

### Error messages or log output

_No response_

### Version

7.15.0 7.16

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by blackdevelopa**
## **Description**

The WhatsNew modal isn't displayed when updating from the v7.15.0 to v7.16.0. We had previously defined the `minAppVersion` to `v7.15.0`. See [comment](https://github.com/MetaMask/metamask-mobile/pull/8453#discussion_r1470139639)

## **Related issues**

Fixes: #8553 

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/WhatsNewModal/whatsNewList.ts [hunk 1]
```diff
@@ -7,8 +7,8 @@ import { WhatsNew } from './types';
 export const whatsNew: WhatsNew = {
   // All users that have <6.4.0 and are updating to >=6.4.0 should see
   onlyUpdates: false, // false: Users who updated the app and new installs will see this. true: only users who update will see it
-  maxLastAppVersion: '7.15.0', // Only users who had a previous version <7.15.0 version will see this
-  minAppVersion: '7.15.0', // Only users who updated to a version >= 7.15.0 will see this
+  maxLastAppVersion: '7.19', // Only users who had a previous version <7.19.0 version will see this
+  minAppVersion: '7.14.0', // Only users who updated to a version >= 7.14.0 will see this
```
Comment (digiwand) [inline app/components/UI/WhatsNewModal/whatsNewList.ts:11]: [non-blocker] I think the comments here can be improved. I find the minAppVersion comment to also be misleading since it's not dependent on being an updated version

```suggestion
  maxLastAppVersion: '7.19', // When updating, only users who had a previous version < '7.19' version may see the modal
  minAppVersion: '7.14.0', // Only users whose current version is >= 7.14.0 may see the modal
```

---

for more details about `maxLastAppVersion` and `minAppVersion` please see [related comment in other PR](https://github.com/MetaMask/metamask-mobile/pull/8453#discussion_r1470139639)

File: app/components/UI/WhatsNewModal/whatsNewList.ts [hunk 2]
```diff
@@ -7,8 +7,8 @@ import { WhatsNew } from './types';
 export const whatsNew: WhatsNew = {
   // All users that have <6.4.0 and are updating to >=6.4.0 should see
   onlyUpdates: false, // false: Users who updated the app and new installs will see this. true: only users who update will see it
-  maxLastAppVersion: '7.15.0', // Only users who had a previous version <7.15.0 version will see this
-  minAppVersion: '7.15.0', // Only users who updated to a version >= 7.15.0 will see this
+  maxLastAppVersion: '7.20', // When updating, only users who had a previous version < '7.20' may see the modal
+  minAppVersion: '7.14.0', // Only users whose current version is >= 7.14.0 may see the modal
```
Comment (seaona) [inline app/components/UI/WhatsNewModal/whatsNewList.ts:11]: not sure how the logic works but just to clarify that we don't have Blockaid in 7.14

Comment (digiwand) [reply app/components/UI/WhatsNewModal/whatsNewList.ts:11]: great callout @seaona. I think we'll want to update this version to the version with the latest copy changes of the WhatsNew modal

Comment (digiwand) [inline app/components/UI/WhatsNewModal/whatsNewList.ts:11]:
```suggestion
  minAppVersion: '7.14.0', // Only users whose current version is >= 7.14.0 may see the modal. This should match the version with the latest copy changes of the modal.
```

Comment (digiwand) [reply app/components/UI/WhatsNewModal/whatsNewList.ts:11]:
```suggestion
  minAppVersion: '7.14.0', // Only users whose current version is >= 7.14.0 may see the modal. This should match the version with the latest copy changes in the modal.
```

**Review by jpuri — DISMISSED** [review]

**Review by digiwand — APPROVED** [review]

**Review by jpuri — APPROVED** [review]
