### PR TITLE
fix: cp-7.55.0 fix grant permission via connected site popover

### LINKED ISSUE #19309: [Bug]: Switching networks from dapps--> Manage Permissions switches network in the Network Manager.
### Describe the bug

Switching networks from a dapp --> Manage Permissions switches network in the Network Manager.

### Expected behavior

Switching dapp network should not affect network manager or global network

### Screenshots/Recordings

https://github.com/user-attachments/assets/21dc2f77-d778-484c-b389-6b10006e525e

### Steps to reproduce

1. Connect to any dapp
2. Click on icon in the upper right side
3. Click on Manage Permissions
4. Click on dapp symbol
5. Switch networks
6. Go to Home
7. Refresh
8. Notice network has changed

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.55.0

### Build type

None

### Device

iPhone15, Pixel 6 Pro

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by NidhiKJha**
## **Description**

This PR ensures Switching dapp network should not affect network manager or global network

## **Changelog**

CHANGELOG entry: added grant permission via connected site popover

## **Related issues**

Fixes: [https://github.com/MetaMask/metamask-mobile/issues/19309](https://github.com/MetaMask/metamask-mobile/issues/19309)

## **Manual testing steps**

```gherkin
Feature: Network Switching with Dapp Connection

  Scenario: Network switch should not affect dapp connection
    Given the user is connected to a dapp
    When the user clicks on the icon in the upper right side
    And clicks on "Manage Permissions"
    And clicks on the dapp symbol
    And switches networks
    And goes to Home
    And refreshes the page
    Then the network should not have changed
    And the dapp connection should remain intact
```

## **Screenshots/Recordings**

`~`

### **Before**

`~`

### **After**

https://github.com/user-attachments/assets/c8c48cb0-75d9-4f2f-999c-c1e417e2ffbd

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by salimtb — DISMISSED** [review]
lgtm

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by n3ps — APPROVED** [review]

File: app/selectors/selectedNetworkController.ts [hunk 1]
```diff
@@ -32,6 +32,16 @@ export const selectNetworkClientIdsByDomains = createSelector(
     selectedNetworkControllerState?.domains,
 );
 
+export const selectActiveDappNetwork = createSelector(
+  selectSelectedNetworkControllerState,
+  (selectedNetworkControllerState: SelectedNetworkControllerState) =>
+    (
+      selectedNetworkControllerState as SelectedNetworkControllerState & {
```
Comment (tommasini) [inline app/selectors/selectedNetworkController.ts:39]: If the type is wrong, should we modify the type instead of casting ?

File: app/selectors/selectedNetworkController.ts [hunk 2]
```diff
@@ -252,8 +270,9 @@ export const makeSelectRpcUrl = () =>
       }
       if (!hostname || !isPerDappSelectedNetworkEnabled())
         return providerRpcUrl;
+
       const relevantNetworkClientId =
-        domainNetworkClientId || globalNetworkClientId;
+        activeDappNetwork || domainNetworkClientId || globalNetworkClientId;
```
[the remark this answers is not in the document]
Comment (tommasini) [reply app/selectors/selectedNetworkController.ts:275]: @NidhiKJha Do we reviewed this scenario identified by cursor?

File: app/core/Engine/Engine.ts [hunk 3]
```diff
@@ -961,7 +964,14 @@ export class Engine {
           'PermissionController:stateChange',
         ],
       }),
-      state: initialState.SelectedNetworkController || { domains: {} },
+      state:
+        initialState.SelectedNetworkController ||
```
Comment (tommasini) [inline app/core/Engine/Engine.ts:968]: Is there any reason why this is needed? I think we should be pointing to change the default state at the controller and not override here

File: app/components/Views/NetworkSelector/useSwitchNetworks.ts [hunk 4]
```diff
@@ -141,6 +141,15 @@ export function useSwitchNetworks({
...
         );
+        (
+          SelectedNetworkController as typeof SelectedNetworkController & {
+            update: (
+              fn: (state: { activeDappNetwork: string | null }) => void,
+            ) => void;
+          }
+        ).update((state: { activeDappNetwork: string | null }) => {
+          state.activeDappNetwork = networkConfigurationId;
+        });
```
[the remark this answers is not in the document]
Comment (tommasini) [reply app/components/Views/NetworkSelector/useSwitchNetworks.ts:152]: @NidhiKJha I agree that we shouldn't typing everywhere the SelectedNetworkController but fix the typescript issue! Is there anything particular that doens't let us do it?

File: app/core/Engine/Engine.ts (hunk 3 above)
Comment (NidhiKJha) [reply app/core/Engine/Engine.ts:968]: Considering we want to have the activeDappNetwork for this fix and we want to ship this release blocker asap without waiting for controller package updates, I think it's fine. We can always refactor to move this into the controller's default state in a follow up PR. wdyt?

File: app/components/Views/NetworkSelector/useSwitchNetworks.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (NidhiKJha) [reply app/components/Views/NetworkSelector/useSwitchNetworks.ts:152]: The type casting is necessary because we're extending an external controller that doesn't natively support activeDappNetwork. What specific TypeScript solution did you have in mind?

File: app/core/Engine/Engine.ts (hunk 3 above)
Comment (tommasini) [reply app/core/Engine/Engine.ts:968]: Yeah I think it's okay to follow up with the change

Although I question if a patch would be better in this case then changing multiple places of the codebase

Will approve and will let you decide, this is okay for me as temporary

**Review by tommasini — APPROVED** [review]
