### PR TITLE
fix: cp-7.59.0 fix crash when hiding token on token details in android

### LINKED ISSUE #22325: TypeError: Cannot read property 'symbol' of undefined
Sentry Issue: [METAMASK-MOBILE-2H4B](https://metamask.sentry.io/issues/5652194274/?referrer=github_integration)

```
TypeError: Cannot read property 'symbol' of undefined
  at AssetDetails (/app/components/Views/AssetDetails/index.tsx:190:17)
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

PR to fix undefined error when trying to hide a token from Asset details page.

## **Changelog**

CHANGELOG entry: Fixed a bug that was causing app crash when trying to hide a token from asset details page.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/22325

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

https://github.com/user-attachments/assets/c2eafdbd-2399-4294-b37b-7f04e8e5e00c

### **After**

https://github.com/user-attachments/assets/a6c9e115-9399-47ab-ae2b-3511db97cbff

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Refactors AssetDetails to a container/presentational pattern that resolves the token via normalized address matching and passes it in, returning null if missing.
> 
> - **Asset Details refactor**:
>   - Introduce `AssetDetailsContainer` that:
>     - Selects tokens by `chainId`/account, finds the token using `areAddressesEqual(address)`.
>     - Returns `null` if the token is not found.
>     - Passes the resolved `token` to `AssetDetails`.
>   - Update `AssetDetails` to accept a `token` prop and remove internal token selection logic.
> - **Address handling**: Use `areAddressesEqual` for robust token address comparison.
> - **Export**: Default export switched to `AssetDetailsContainer`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 4af9f02e175799c979a8e4e18a4b661a8a9fd374. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/AssetDetails/index.tsx [hunk 1]
```diff
@@ -398,4 +388,31 @@ const AssetDetails = (props: Props) => {
...
+  const portfolioToken = useMemo(
+    () => tokensByChain.find((rawToken) => rawToken.address === address),
+    [tokensByChain, address],
+  );
+
+  const token: TokenType | undefined = portfolioToken;
+
+  if (!token) {
+    return null;
+  }
```
Comment (Prithpal-Sooriya) [inline app/components/Views/AssetDetails/index.tsx:417]: if no token, we early return null.

Comment (Prithpal-Sooriya) [reply app/components/Views/AssetDetails/index.tsx:417]: We can add some extra logic if we need to handle any navigations.

**Review by sahar-fehri — DISMISSED** [review]

**Review by sahar-fehri — APPROVED** [review]

**Review by Prithpal-Sooriya — COMMENTED** [review]
LGTM

**Review by juanmigdr — APPROVED** [review]
