### PR TITLE
fix: Warning when rejecting an approval request with id XYZ not found

### LINKED ISSUE #6860: [Bug] Warning when Rejecting an Approve tx `Approval request with id XYZ not found`
**Describe the bug**
Whenever we Reject an Approve transaction, we can see the following warning `Approval request with id XYZ not found`

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/334b9c66-594f-4448-b927-eb9992ea6d94

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to test dapp
2. Deploy an ERC20 token
3. Click Approve
4. Reject the approval
5. See warning

**Expected behavior**
Warning should be handled

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `main` QA build `a8d0613cc3d12ebea2f095bf29d68fe9d113f809`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by vinistevam**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add the appropiate QA label when dev review is completed
    - `needs-qa`: PR requires manual QA.
    - `No QA/E2E only`: PR does not require any manual QA effort. Prior to merging, ensure that you have successful end-to-end test runs in Bitrise. 
    - `Spot check on release build`: PR does not require feature QA but needs non-automated verification. In the description section, provide test scenarios. Add screenshots, and or recordings of what was tested.
5. Add `QA Passed` label when QA has signed off (Only required if the PR was labeled with `needs-qa`)
6. Add your team's label, i.e. label starting with `team-` (or `external-contributor` label if your not a MetaMask employee)

**Description**

Whenever you deploy an ERC 20, create an approval request, move the app to the background and get it back active again.
Basically, the issue is that `handleAppStateChange` and `componentWillUnmount` are calling reject approval twice without checking if the approval exists.

Changes:
- Includes a check if an approval request exists before trying to reject.

**Screenshots/Recordings**

[bug-warning-approval-id-not-found.webm](https://github.com/MetaMask/metamask-mobile/assets/45455812/7caca741-8e12-4ea3-ae2a-ddeb8fe0e89b)

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**To Reproduce**
Steps to reproduce the behaviour

- Go to test dapp
- Deploy an ERC20 token
- Click Approve
- Go in the background and get the app back "active"
- See warning

The expected behaviour is the transaction being rejected but no warning or error is shown.

**E2E**
https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8c4f9cff-ec1b-43ed-8c6f-776cfb46d06f

**Issue**

fixes https://github.com/MetaMask/metamask-mobile/issues/6860

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

File: app/components/Views/ApproveView/Approve/index.js [hunk 1]
```diff
@@ -304,30 +304,30 @@ class Approve extends PureComponent {
...
   };
 
   handleAppStateChange = (appState) => {
     if (appState !== 'active') {
+      const { ApprovalController } = Engine.context;
       const { transaction } = this.props;
-      transaction &&
-        transaction.id &&
-        Engine.context.ApprovalController.reject(
+      if (transaction?.id && ApprovalController.has({ id: transaction.id })) {
```
Comment (matthewwalsh0) [inline app/components/Views/ApproveView/Approve/index.js:325]: Rather than duplicating this check here and in the `Approval` component, would it be cleaner to move this logic to the `Engine.rejectPendingApproval` method via an options object and an argument like `ignoreMissing`?

At the same time, we could make the `reason` argument optional and default to `ethErrors.provider.userRejectedRequest` so we don't have to specify it everytime.

Finally, it catches all errors and logs currently so we could add an option for that too such as `logErrors`.

File: app/core/Engine.ts [hunk 2]
```diff
@@ -893,13 +894,29 @@ class Engine {
     Engine.instance = null;
   }
 
-  rejectPendingApproval(id: string, reason: Error) {
+  rejectPendingApproval(
+    id: string,
+    reason: Error = ethErrors.provider.userRejectedRequest(),
+    { ignoreMissing, logErrors } = {
```
Comment (matthewwalsh0) [inline app/core/Engine.ts:900]: We haven't formally defined a type here, only a fallback value, would it be clearer to define the type (with optional properties for both) but have the fallback just be an empty object.

Then we can instead default each property inline, so we'd change the `logErrors` condition to `logErrors !== false` as currently if you provided it as `undefined`, it would not log errors but we want it to so it matches the previous behaviour.

File: app/core/Engine.ts [hunk 3]
```diff
@@ -1029,6 +1046,16 @@ export default {
...
-  rejectPendingApproval: (id: string, reason: Error) =>
-    instance?.rejectPendingApproval(id, reason),
+  rejectPendingApproval: (
+    id: string,
+    reason: Error,
+    {
+      ignoreMissing,
+      logErrors,
+    }: {
+      ignoreMissing: boolean;
```
Comment (matthewwalsh0) [inline app/core/Engine.ts:1056]: Both optional properties here also plus a default value (empty object) for the options so it's not required?

File: app/core/Engine.ts (hunk 2 above)
Comment (vinistevam) [reply app/core/Engine.ts]: Thanks for the suggestion, I've defined the type with both properties optional and modified the fallback to use an empty object as default.

**Review by matthewwalsh0 — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Comment by sleepytanya** [comment]
The 'Approve token' transaction is rejected after moving to background, no error/wa
rning is shown. 
iOS build:

https://github.com/MetaMask/metamask-mobile/assets/104780023/f98bee68-c9cf-435b-9e85-2c8134347c5e

Android build:


https://github.com/MetaMask/metamask-mobile/assets/104780023/8879b194-37e6-4365-9a68-7cc5cff63316
