### PR TITLE
fix: fix balance after swap

### LINKED ISSUE #13187: [Bug]: Balances Not Updating on Mobile After Swaps
### Describe the bug

On the MetaMask Mobile app, token balances are not updating immediately after completing a swap. This issue occurs across multiple networks, including Linea and BSC, and persists even after refreshing the asset list manually.

Although the swap completes successfully (confirmed on the blockchain explorer), the balance in the asset list remains unchanged. Users can even attempt a second swap of the same token, which subsequently fails due to insufficient balance—highlighting a discrepancy between the UI and the actual blockchain state.

Balances update immediately on the MetaMask extension, even for swaps initiated on mobile, but there appears to be a significant delay or failure in updating ERC-20 token balances on the mobile app. Balances eventually update, but they take roughly 3 minutes to update in the UI.

This suggests that the problems is not at the controller/backend level, but potentially some sort of polling loop on the client.

First reported on version 7.33.2, still present on 7.39

https://github.com/user-attachments/assets/370f6f56-6f8a-4a95-9ef5-5e94399793f3

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

	1.	On MetaMask Mobile (iOS, version 7.38.0 or earlier), perform a token swap of erc20 token.
	2.	Verify the swap’s success on the blockchain explorer.
	3.	Check the token balance in the asset list—it remains unchanged.
	4.	Pull down to refresh the asset list—balance still does not update.
	5.	Attempt a second swap of the same token, which could fail due to insufficient balance.

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.38

### Build type

None

### Device

iPhone

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Related issues**

Fixes: #13187

## **Manual testing steps**

1. Process swap
2. check the token balances

### **After**

https://github.com/user-attachments/assets/c1dc8164-aef6-466e-8df7-e1def33d6a95

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/NotificationManager.js [hunk 1]
```diff
@@ -234,14 +234,16 @@ class NotificationManager {
         // Detect assets and tokens for ERC20 txs
         // Detect assets for ERC721 txs
         // right after a transaction was confirmed
-        const pollPromises = [AccountTrackerController.refresh()];
+        const pollPromises = [
+          AccountTrackerController.refresh(),
+          TokenBalancesController.updateBalancesByChainId({
+            chainId: transactionMeta.chainId,
+          }),
+        ];
```
Comment (Prithpal-Sooriya) [inline app/core/NotificationManager.js:242]: This is the main fix yeah? So now we will always attempt a token balances update?

**Review by Prithpal-Sooriya — APPROVED** [review]

File: app/core/NotificationManager.js (hunk 1 above)
Comment (salimtb) [reply app/core/NotificationManager.js:242]: yes for every confirmed transaction , we will update the tokens balances

**Review by gambinish — APPROVED** [review]

**Review by sethkfman — APPROVED** [review]
LGTM
