### PR TITLE
On-Ramp: Refactor and Wyre countries

### LINKED ISSUE #2484: On-ramp with Wyre need to be update
**Describe the bug**
On the on-ramp flow, we have some information that is inaccurate and needs to be updated.
We need to update information in 3 different "buckets":
1) Countries supported
2) Max limit
3) Excluded U.S. states 

*1) Countries Supported*
Currently, we show that Apple Pay is available to U.S. only.
Wyre with its Apple Pay option supports more countries and here is the list of all countries supported by Wyre/Apple Pay: Australia, Austria, Belarus, Belgium, Brazil, Canada, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hong Kong, Iceland, Ireland, Italy, Japan, Latvia, Lithuania, Luxembourg, New Zealand, Norway, Poland, Portugal, Singapore, Slovakia, Slovenia, Spain, Sweden, Switzerland, The Netherlands.

*2) Max limit*
Currently, we show an inaccurate limit for US onl=y of $450. 
The correct amounts are:
Domestic (US): Weekly: $500 ; Monthly: $2,000; Yearly: $5,000
International: Weekly: $1,000; Monthly: $4,000; Yearly: $7,500

*Excluded U.S. States*
Currently, we show that the following states are excluded: CT, HI, NC, NH, NY, VA and VT. 
Wyre supports all states except NY and TX for cards. 

**Screenshots**
IMG_E19659BD5F5B-1

IMG_1BC19B6AA86D-1

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the app homescreen
2. Click on "Buy"
5. when clicking the "i" also see error

**Expected behavior**
Already covered in the description above. 

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.4.2
 - App Version - v2.01(605)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by wachunei**

### CODE REVIEW

File: app/reducers/fiatOrders/index.js [hunk 1]
```diff
@@ -61,28 +77,49 @@ export const getProviderName = provider => {
 	}
 };
 
-export const getOrders = (orders, selectedAddress, network) =>
-	orders.filter(order => order.account === selectedAddress && order.network === network);
+const ordersSelector = state => state.fiatOrders.orders || [];
+const selectedAddressSelector = state => state.engine.backgroundState.PreferencesController.selectedAddress;
+const networkSelector = state => state.engine.backgroundState.NetworkController.network;
```
Comment (estebanmino) [inline app/reducers/fiatOrders/index.js:82]: can we have this dependant on chainId instead of network?

File: app/components/UI/FiatOrders/index.js [hunk 2]
```diff
@@ -78,7 +78,7 @@ function FiatOrders({ pendingOrders, dispatch }) {
 			await Promise.all(
 				pendingOrders.map(async order => {
 					const updatedOrder = await processOrder(order);
-					dispatch({ type: 'FIAT_UPDATE_ORDER', payload: updatedOrder });
+					dispatch(updateFiatOrder(updatedOrder));
```
Comment (estebanmino) [inline app/components/UI/FiatOrders/index.js:81]: hm there's any reason to dispatch from the component rather than doing mapDispatchToProps? just to maintain the same structure

File: app/components/UI/FiatOrders/components/PaymentMethod/index.js [hunk 3]
```diff
@@ -14,11 +15,13 @@ const style = StyleSheet.create({
 		borderColor: colors.blue,
 		paddingVertical: 15,
 		paddingHorizontal: 20,
-		marginHorizontal: 25,
+		marginHorizontal: Device.isIphone5() ? 15 : 25,
```
Comment (estebanmino) [inline app/components/UI/FiatOrders/components/PaymentMethod/index.js:18]: is this for only iPhone5 or all smaller devices? i believe there's a isSmallDevice method too

File: app/components/UI/FiatOrders/components/CountrySelectorModal.js [hunk 4]
```diff
@@ -0,0 +1,190 @@
...
+		...fontStyles.normal,
+		flex: 1
+	},
+	modalTitle: {
+		marginTop: Device.isIphone5() ? 10 : 15,
+		marginBottom: Device.isIphone5() ? 5 : 5,
+		marginHorizontal: 36
+	},
+	resultsView: {
+		height: Device.isSmallDevice() ? 130 : 250,
```
Comment (estebanmino) [inline app/components/UI/FiatOrders/components/CountrySelectorModal.js:58]: ah you're using it (I commented this below, I'm reviewing from bottom to top)

File: app/components/UI/FiatOrders/PaymentMethodSelector/transak.js [hunk 5]
```diff
@@ -26,123 +31,128 @@ const style = StyleSheet.create({
...
-											<Text primary>Turkey 🇹🇷</Text>
-											<Text primary>United Kingdom 🇬🇧</Text>
-											<Text primary>Vietnam 🇻🇳</Text>
-											<Text primary>USA 🇺🇸</Text>
-										</View>
-									</ScrollView>
+						<Text modal bold>
+							{strings('fiat_on_ramp.supported_countries_title')}
+						</Text>
+						<View style={styles.countryList}>
```
Comment (estebanmino) [inline app/components/UI/FiatOrders/PaymentMethodSelector/transak.js:76]: is this the same list than https://github.com/MetaMask/metamask-mobile/pull/2617/files?file-filters%5B%5D=.js&file-filters%5B%5D=.snap#diff-c4abe94ba2fc59ac406bb0e39c608aca28757ae56470d8ea275dead83345ffe5R94 ?
Maybe it would make sense to have another component?

File: app/components/Base/Text.js [hunk 6]
```diff
@@ -45,7 +45,7 @@ const style = StyleSheet.create({
 	modal: {
 		color: colors.fontPrimary,
 		fontSize: 16,
-		lineHeight: 30
+		lineHeight: 16 * 1.4
```
Comment (estebanmino) [inline app/components/Base/Text.js:48]: 22.4?

File: app/components/UI/FiatOrders/PaymentMethodSelector/transak.js (hunk 5 above)
Comment (wachunei) [reply app/components/UI/FiatOrders/PaymentMethodSelector/transak.js:76]: No, is not the same

File: app/components/UI/FiatOrders/components/PaymentMethod/index.js (hunk 3 above)
Comment (wachunei) [reply app/components/UI/FiatOrders/components/PaymentMethod/index.js:18]: Yeah, this is more related to the width and the `isSmallDevice` to the height

File: app/reducers/fiatOrders/index.js (hunk 1 above)
Comment (wachunei) [reply app/reducers/fiatOrders/index.js]: Fixed 👌

File: app/components/UI/FiatOrders/index.js (hunk 2 above)
Comment (wachunei) [reply app/components/UI/FiatOrders/index.js]: Moved it to `mapDispatchToProps` 👌

File: app/components/Base/Text.js (hunk 6 above)
Comment (wachunei) [reply app/components/Base/Text.js]: 👌

**Comment by estebanmino** [comment]
@wachunei @ibrahimtaveras00 just pushed a build to testflight to QA this PR. we need to revert this https://github.com/MetaMask/metamask-mobile/pull/2617/commits/4a60af557de04771ec3ae569dd90c659b01f69d5 before merging

**Comment by mobularay** [comment]
Currently in limited user testing stage: 

- Andre (Portugal): passed successfully in Portugal
- Omna (Canada): currently working through some issues with Pedro
- Gabriel (Canada): still need to test. ETA eod June 1st. 
- Peter (UK): to be added to Testflight's internal testing group?
- Chantal (Singapore): to be added to Testflight's internal testing group?


If the above testings go well, then once Ibrahim is back this Thursday, he can do minimal feature testing and then move quickly into regression testing stage.

**Comment by mobularay** [comment]
Update on user testing progress:

* Andre: pass
* Peter: pass
* Omna: stuck
* Gabriel: stuck
* Chantal: ???

**Comment by wachunei** [comment]
Just to clarify: Omna and Gabriel are stuck because of Apple Pay restriction, this restriction is also present before the support of multiple countries.

**Comment by mobularay** [comment]
- stuck error by Omna and Gabriel is not "terrible"
- It’ll just prevent them from using Apple Pay
- Transak will still work, or is available at least
- this error doesn't hit Wyre; stays at card level
- need to give heads-up to Customer Success

Removing Omna and Gabriel's stuck issue as blocker; will check with Chantal

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
I added my QA results in slack with @wachunei and @jakehaugen, but posting here as well:
- Double check if $10K is accurate for yearly
- Not seeing Lithuania as a supported country 
- US and NON-US limits questions 
- Did we want to change the notification to match figma?
- In addition, do we want to change the quick buttons to match max of $400 US and $800 non-US?

**Comment by mobularay** [comment]
Other than encountering a minor(?) UI issue, Chantal seems to have successfully completed the purchase - @wachunei to confirm!

**Comment by mobularay** [comment]
Latest update: https://consensys.slack.com/archives/G018FR294E9/p1622818729047100

TBD on go/no-go status to be included into v2.5 release

**Comment by wachunei** [comment]
> * Double check if $10K is accurate for yearly
> * Not seeing Lithuania as a supported country
> * US and NON-US limits questions
> * Did we want to change the notification to match figma?
> * In addition, do we want to change the quick buttons to match max of $400 US and $800 non-US?

All of these are fixed 🆗

**Review by ibrahimtaveras00 — APPROVED** [review]
I will have to check Issue 4 during regression testing as I can't do the full flow on debug mode and will need testflight instead.

Everything else looks good, QA Passed 👍🏽
