### PR TITLE
Don't render swap router address in recents

### LINKED ISSUE #2822: don't show swaps contract address in recent "Recents"
**Describe the bug**

Right now when a user performs a swap the swaps contract address gets added to "Recents". this has resulted in quite a few of our users sending funds to the swaps contract address in error. The hypothetical flow is this:

a) user sends funds to their best friend Esteban
b) user then performs a swap
c) user wants to send funds to their best friend again and assumes the first address on recents is their best friend when in fact it's the swaps contract address. they select that address and send
d) user is angry because their funds went to the wrong address.

**Expected behaviour**

We should have a list of addresses (perhaps malicious ones could also be included?) that never get added to "Recents"

### LINKED ISSUE #2833: Sync Mobile with Extension no exists menu item
** Please describe the error **
I am trying to sync a wallet with Metamask extension using a QR code

** Screenshots **

** Steps **
1. I click on the extension in the Chrome browser
2. Go to Settings> Advanced> Synchronization with a mobile device
3. I enter the password for the Metamask wallet
4. A QR code is displayed
5. I open the application
6. From the home screen, click the "QR Icon"
7. Scanning the QR code of the Metamask extension
8. The application on the device reports:
8.1 "Error! It looks like you are trying to sync a wallet with the Metamask extension, to do this open" Settings> Advanced> Synchronize with Metamask extension ""
8.2 I go to "Settings> Advanced", but there is no such item in the settings.
** Expected Behavior **
Expect wallets and network settings to sync between extension and device.

** Smartphone (include the following information): **
  - Device: Sony Xperia XA2 +
  - OS: Android 9
  - Extension version (Google Chrome) [9.6.1]
  - Application version (Android) [2.40] Google Play

-------------------------------------------------- -------------------------------------------------- ------------
- How to sync with a mobile device?

### PR DESCRIPTION
**Pull request by rickycodes**
**Description**

This makes it so we don't render the MetaMask Swaps contract router address in Recents. Perhaps we should also consider not rendering token contract addresses as well? but at least we do show warnings for those on send:

image

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2822

### CODE REVIEW

File: app/components/Views/SendFlow/AddressList/index.js [hunk 1]
```diff
@@ -13,6 +13,9 @@ import {
 	TRANSFER_FROM_FUNCTION_SIGNATURE
 } from '../../../../util/transactions';
 
+// MetaMask: Swap Router
+const MM_SWAP_ROUTER = '0x881D40237659C251811CEC9c364ef91dC08D300C';
```
Comment (wachunei) [inline app/components/Views/SendFlow/AddressList/index.js:17]: Use
```js
import { swapsUtils } from '@metamask/swaps-controller';

// ...

swapsUtils.getSwapsContractAddress(props.chainId);
```
to get the Swaps Contract Address

**Review by wachunei — APPROVED** [review]
