### PR TITLE
fix: add missing isPortfolioUrl import and update portfolio url name

### LINKED ISSUE #9242: [Bug]: app closes when tapping portfolio button on wallet view
### Describe the bug

Tapping the portfolio button on wallet view closes the app for both iOS and Android.

Comms: https://consensys.slack.com/archives/C02U025CVU4/p1713171912524269

### Expected behavior

After tapping the portfolio button on wallet view the app should navigate to the browser and open a browser tab to portfolio webapp.

### Screenshots/Recordings

See convo here: https://consensys.slack.com/archives/C02U025CVU4/p1713171912524269

### Steps to reproduce

GIVEN I am on wallet view
WHEN I tap portfolio
THEN app navigates to browser view
AND browser tab is open to portfolio app
AND browser tab will connect wallet a current session is still active
BUT browser tab will not connect wallet if there is no active session with portfolio

### Error messages or log output

_No response_

### Version

7.21.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

Sev1

### PR DESCRIPTION
**Pull request by ameliejyc**
## **Description**

Fixes https://github.com/MetaMask/metamask-mobile/issues/9242 and https://github.com/MetaMask/metamask-mobile/issues/9244

More specifically, fixes these 2 issues:

- URL not called properly for Stake button since constant name changes (broken Portfolio Stake link)
- `isPortfolioUrl` is not imported in app/components/UI/Tokens/index.tsx (broken Portfolio home link)

**NOTE**: These [breaking issues](https://github.com/MetaMask/metamask-mobile/pull/8674) should have been caught by the typechecker which is [currently disabled for the components folder](https://github.com/MetaMask/metamask-mobile/blob/ef475b788f9be7f0d2b66ea749045772ed899ba0/tsconfig.lint.json#L11). I'd strongly advise that this is re-implemented as these issues could have been easily been caught at the commit or CI level.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/9242 and https://github.com/MetaMask/metamask-mobile/issues/9244

## **Manual testing steps**

- Go to Token Listing
- Verify that the new staking icon shows up on ETH on mainnet
- Verify that onPress, the MM browser opens up the Portfolio stake page with the correct query params (https://portfolio.metamask.io/stake?metamaskEntry=mobile)
- Verify that if a browser tab is already open on the stake page, the MM browser picks this tab rather than opening a new one
- Verify that the Token Listing Portfolio button opens up the portfolio page (https://portfolio.metamask.io?metamaskEntry=mobile) and does not crash the app

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/22345430/05d258d8-e962-4297-9e2d-b6f7a47f688f

### **After**

https://github.com/MetaMask/metamask-mobile/assets/22345430/8b7cdca4-1028-45e3-8da8-074d80e70755

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Tokens/index.tsx [hunk 1]
```diff
@@ -220,7 +221,7 @@ const Tokens: React.FC<TokensI> = ({ tokens }) => {
 
   const renderStakeButton = (asset: TokenI) => {
     const onStakeButtonPress = () => {
-      const STAKE_URL = `${AppConstants.PORTFOLIO_URL}/stake`;
+      const STAKE_URL = `${AppConstants.PORTFOLIO.URL}/stake`;
```
Comment (sethkfman) [inline app/components/UI/Tokens/index.tsx:224]: Could these URLS but added to the AppConstants similar to [here](https://github.com/MetaMask/metamask-mobile/blob/547ca9dcb1e3364b94c513a5f0821e0200ac38d9/app/core/AppConstants.ts#L25)

File: app/components/UI/Tokens/index.test.tsx [hunk 2]
```diff
@@ -240,7 +240,7 @@ describe('Tokens', () => {
     fireEvent.press(getByTestId(STAKE_BUTTON));
     expect(mockNavigate).toHaveBeenCalledWith(Routes.BROWSER.HOME, {
       params: {
-        newTabUrl: `${AppConstants.PORTFOLIO_URL}/stake?metamaskEntry=mobile`,
+        newTabUrl: `${AppConstants.PORTFOLIO.URL}/stake?metamaskEntry=mobile`,
```
Comment (sethkfman) [inline app/components/UI/Tokens/index.test.tsx:243]: Could these URLS but added to the AppConstants similar to [here](https://github.com/MetaMask/metamask-mobile/blob/547ca9dcb1e3364b94c513a5f0821e0200ac38d9/app/core/AppConstants.ts#L25)

File: app/components/UI/Tokens/index.tsx [hunk 3]
```diff
@@ -220,16 +221,15 @@ const Tokens: React.FC<TokensI> = ({ tokens }) => {
...
-        tab.url.includes(STAKE_URL),
+        tab.url.includes(AppConstants.STAKE.URL),
       );
       let existingTabId;
       let newTabUrl;
       if (existingStakeTab) {
         existingTabId = existingStakeTab.id;
       } else {
-        newTabUrl = `${STAKE_URL}?metamaskEntry=mobile`;
+        newTabUrl = `${AppConstants.STAKE.URL}?metamaskEntry=mobile`;
```
Comment (NicolasMassart) [inline app/components/UI/Tokens/index.tsx:232]: Q: Could this param `?metamaskEntry=mobile` be in the constant directly? Then on `tab.url.includes(AppConstants.STAKE.URL`  you can transform as an URL and only check the domain and path excluding params.

Comment (ameliejyc) [reply app/components/UI/Tokens/index.tsx:232]: It's doable. It would differ to how we treat the Portfolio and Bridges URLs though so if I did it for Stake, I think it would make sense to consider updating the two places the Portfolio URL is used, as well as the Bridge Portfolio URL.

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.
image

**Review by sethkfman — APPROVED** [review]
LGTM
