### PR TITLE
fix: cp-7.55.0 initialize network enablement controller

### LINKED ISSUE #19201: [Bug]: Missing chain id for Bitcoin when in Flask build
### Describe the bug

When you run the Flask build the app crashes due to the `bip122:000000000019d6689c085ae165831e93` not being present within the network enablement controller state

### Expected behavior

To not crash and the network enablement controller has btc mainet within its state 

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Build the app in Flask
2. Login
3. You should see it crash

### Error messages or log output

```shell
Missing chain id
```

### Detection stage

On main branch

### Version

7.55.0

### Build type

None

### Device

Both

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by vinnyhoward**
## **Description**

Initialize network enablement controller to get correct namespaces based off of multichain network controller configurations

**Problem:** When running the Flask build we get a `Missing chain id` error. This is because the network enablement controller state for `bip22` is an empty object and is missing the `bip122:000000000019d6689c085ae165831e93` caip chain id.

**Solution:** Initialize the network enablement controller based off of the multichain network controller config. There is a separate PR [here](https://github.com/MetaMask/core/pull/6455) for core that enabled that. For now we will just use a patch

**Update** Controller has been released and patch is no longer needed

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/19201

## **Manual testing steps**

```gherkin
Feature: Network Enablement Controller

  Scenario: user logs in
    Given they are on Flask build and has a bitcoin address
    Then user switches to bitcoin
    Then nothing happens and app doesn't crash
```

## **Screenshots/Recordings**

`~`

### **Before**

image

### **After**

simulator_screenshot_25C53C66-6164-40F9-A881-C2F262FE9AFE

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

-  [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/Engine/Engine.ts [hunk 1]
```diff
@@ -1280,6 +1280,7 @@ export class Engine {
 
     const networkEnablementController =
       controllersByName.NetworkEnablementController;
+    networkEnablementController.init();
```
Comment (vinnyhoward) [inline app/core/Engine/Engine.ts]: This initializes the state based on what has been enabled in the multichain network config. See [here](https://github.com/MetaMask/core/pull/6455/files#diff-4cb506e1745c5abc7cd82056fc02b425aed5d30cbf11f1298c1c658c52795fa4R278)

**Review by salimtb — DISMISSED** [review]

File: patches/@metamask+network-enablement-controller+0.4.0.patch [hunk 2]
```diff
@@ -0,0 +1,247 @@
+diff --git a/node_modules/@metamask/network-enablement-controller/dist/NetworkEnablementController.cjs b/node_modules/@metamask/network-enablement-controller/dist/NetworkEnablementController.cjs
+index 9ddb3ce..f86c612 100644
+--- a/node_modules/@metamask/network-enablement-controller/dist/NetworkEnablementController.cjs
++++ b/node_modules/@metamask/network-enablement-controller/dist/NetworkEnablementController.cjs
+@@ -29,6 +29,9 @@ const getDefaultNetworkEnablementControllerState = () => ({
+         [utils_1.KnownCaipNamespace.Solana]: {
+             [types_1.SolScope.Mainnet]: true,
+         },
++        [utils_1.KnownCaipNamespace.Bip122]: {
```
Comment (Prithpal-Sooriya) [inline patches/@metamask+network-enablement-controller+0.4.0.patch]: This is temporary until https://github.com/MetaMask/core/pull/6455 is released

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: app/util/logs/__snapshots__/index.test.ts.snap [hunk 3]
```diff
@@ -962,6 +965,9 @@ exports[`logs :: generateStateLogs generates a valid json export 1`] = `
       },
       "NetworkEnablementController": {
         "enabledNetworkMap": {
+          "bip122": {
+            "bip122:000000000019d6689c085ae165831e93": true,
+          },
```
Comment (aganglada) [inline app/util/logs/__snapshots__/index.test.ts.snap]: We also need to enable Bitcoin testnets

**Review by aganglada — CHANGES_REQUESTED** [review]
Need to enable Bitcoin testnets and cherry pick this into the current RC

File: app/util/logs/__snapshots__/index.test.ts.snap (hunk 3 above)
Comment (vinnyhoward) [reply app/util/logs/__snapshots__/index.test.ts.snap]: Done!

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: app/util/logs/__snapshots__/index.test.ts.snap [hunk 4]
```diff
@@ -962,6 +966,10 @@ exports[`logs :: generateStateLogs generates a valid json export 1`] = `
       },
       "NetworkEnablementController": {
         "enabledNetworkMap": {
+          "bip122": {
+            "bip122:000000000019d6689c085ae165831e93": true,
+            "bip122:000000000933ea01ad0ee984209779ba": true,
+          },
```
Comment (aganglada) [inline app/util/logs/__snapshots__/index.test.ts.snap]: there are several bitcoin testnets, let me check with product which ones we want to enable

Comment (vinnyhoward) [reply app/util/logs/__snapshots__/index.test.ts.snap]: Looking at our multichain selectors it looks like we support these ones:
```bash
  {
    caipChainId: 'bip122:000000000019d6689c085ae165831e93',
    chainId: 'bip122:000000000019d6689c085ae165831e93',
    decimals: 8,
    imageSource: 21,
    isEvm: false,
    isTestnet: false,
    name: 'Bitcoin',
    nativeCurrency: 'bip122:000000000019d6689c085ae165831e93/slip44:0',
    ticker: 'BTC',
  },
  {
    caipChainId: 'bip122:000000000933ea01ad0ee984209779ba',
    chainId: 'bip122:000000000933ea01ad0ee984209779ba',
    decimals: 8,
    imageSource: 22,
    isEvm: false,
    isTestnet: true,
    name: 'Bitcoin Testnet',
    nativeCurrency: 'bip122:000000000933ea01ad0ee984209779ba/slip44:0',
    ticker: 'tBTC',
  },
  {
    caipChainId: 'bip122:00000008819873e925422c1ff0f99f7c',
    chainId: 'bip122:00000008819873e925422c1ff0f99f7c',
    decimals: 8,
    imageSource: 23,
    isEvm: false,
    isTestnet: true,
    name: 'Bitcoin Mutinynet',
    nativeCurrency: 'bip122:00000008819873e925422c1ff0f99f7c/slip44:0',
    ticker: 'sBTC',
  },
  ```

File: app/components/UI/Tokens/TokenListControlBar/TokenListControlBar.tsx [hunk 5]
```diff
@@ -36,7 +44,7 @@ export const TokenListControlBar = ({
     <BaseControlBar
       networkFilterTestId={WalletViewSelectorsIDs.TOKEN_NETWORK_FILTER}
       additionalButtons={additionalButtons}
-      useEvmSelectionLogic
+      useEvmSelectionLogic={!!isSolanaSelected}
```
[the remark this answers is not in the document]
Comment (vinnyhoward) [reply app/components/UI/Tokens/TokenListControlBar/TokenListControlBar.tsx]: This is intentional. We want to let people filter on EVM and Bitcoin but not Solana since we don't support testnet/custom networks yet

File: app/selectors/multichain/multichain.ts [hunk 6]
```diff
@@ -266,8 +270,19 @@ export const selectMultichainTokenListForAccountId = createDeepEqualSelector(
...
+
+    const filteredTokens = tokens.filter((token) => {
+      if (token.chainId.includes(KnownCaipNamespace.Solana)) {
+        return solanaEnabledNetworks[token.chainId];
+      }
+      return bip122EnabledNetworks[token.chainId];
+    });
 
-    return tokens;
+    return filteredTokens;
```
[the remark this answers is not in the document]
Comment (vinnyhoward) [reply app/selectors/multichain/multichain.ts]: EVM tokens are not selected from here. It is only non-evm, we also have guard clause in the same selector not selecting EVM
```typescript
  if (isEvmNetworkSelected) {
    return undefined;
  }
```

File: app/components/UI/Tokens/TokenListControlBar/TokenListControlBar.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (aganglada) [reply app/components/UI/Tokens/TokenListControlBar/TokenListControlBar.tsx]: We will support solana testnets shortly, so it will be nice if they can be filtered

File: app/selectors/multichain/multichain.ts [hunk 7]
```diff
@@ -266,8 +270,19 @@ export const selectMultichainTokenListForAccountId = createDeepEqualSelector(
...
+      enabledNetworksByNamespace[KnownCaipNamespace.Solana];
+    const bip122EnabledNetworks =
+      enabledNetworksByNamespace[KnownCaipNamespace.Bip122];
+
+    const filteredTokens = tokens.filter((token) => {
+      if (token.chainId.includes(KnownCaipNamespace.Solana)) {
+        return solanaEnabledNetworks[token.chainId];
+      }
+      return bip122EnabledNetworks[token.chainId];
+    });
```
Comment (aganglada) [inline app/selectors/multichain/multichain.ts]: we need to try to generalise this code as we will have more and more non-evm networks, we don't want to have this logc spread thought the app.

**Review by aganglada — COMMENTED** [review]
We need to try to make the logic network agnostic and work with the configurations, otherwise we are going to have harcoded network values spread across the app.

File: app/selectors/multichain/multichain.ts (hunk 7 above)
Comment (vinnyhoward) [reply app/selectors/multichain/multichain.ts]: Agreed

**Review by aganglada — DISMISSED** [review]

**Review by tommasini — DISMISSED** [review]

**Review by aganglada — DISMISSED** [review]

File: app/core/Engine/Engine.ts [hunk 8]
```diff
@@ -1266,6 +1266,10 @@ export class Engine {
     const multichainAccountService = controllersByName.MultichainAccountService;
     ///: END:ONLY_INCLUDE_IF
 
+    const networkEnablementController =
+      controllersByName.NetworkEnablementController;
+    networkEnablementController.init();
```
Comment (tommasini) [inline app/core/Engine/Engine.ts:1281]: Sorry It's most likely due to the nature of the network enablement controller, but why couldn't be called [here](https://github.com/MetaMask/metamask-mobile/blob/890cace1899f3c56f210ba5899dbbcd6c056d7cf/app/core/Engine/Engine.ts#L1169)?

Comment (vinnyhoward) [reply app/core/Engine/Engine.ts:1281]: The `networkEnablementController.init()` call needs to happen after `initModularizedControllers` because:

1.  The NetworkEnablementController's `init()` method synchronizes its state with the `MultichainNetworkController`, which must be fully instantiated first.

2. The `init()` method performs post-construction setup that requires the controller to be completely built with its messenger and state.

**Review by tommasini — DISMISSED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
