### PR TITLE
fix: cp-7.47.0 persist completedOnboarding state value

### LINKED ISSUE #15631: [Bug]: Backup and Sync is not updating on lock/unlock
### Describe the bug

After updating to 7.47.0 (with the redesign), the accounts are not syncing(updating) after a lock/unlock when updated happen on a different client. 

### Expected behavior

When the User Storage has been updated by a different client. The current client should get the latest changes after a lock/unlock of the wallet. 

### Screenshots/Recordings

_No response_

### Steps to reproduce

        Given I have the same SRP set up on two MetaMask clients
        And "Backup and Sync" is enabled on both clients
        And the "Accounts" toggle is enabled on the "Manage what you sync" section
        And I have the following accounts on the first client:
            | Account Name | Type |
            | Account 1    | EVM  |
            | Account 2    | EVM  |
        When I add a new EVM account on the first client
        And I navigate to the second client
        And I lock and unlock the second client
        Then I should see the new account in the account list
        And the account names should match between clients

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.47.0

### Build type

None

### Device

iPhone 14, Pixel 8 

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

Android and iOS

### Severity

_No response_

### PR DESCRIPTION
**Pull request by mathieuartu**
## **Description**

This PR un-blacklists the `onboarding` reducer from `persistConfig`.
Instead, it adds granular control over which `onboarding` keys we want to persist.
Since it was blacklisted before, and in order to keep the previous logic, `onboarding.events` is still not persisted.

This PR also deprecates migration 71, and moves the original migration logic to `onPersistComplete`, as it is needed to correctly populate `completedOnboarding` for upgrading users that don't have `state.onboarding` yet.

As a reference, but not introduced by this PR:
- For new users, `completedOnboarding` is set to `true` after a proper onboarding.
- For all users, `completedOnboarding` is set to `false` after deleting the wallet.

This needs to be cherry-picked in `release/7.47.0` as it is a **release blocker**.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15631

## **Manual testing steps**

1. No manual testing steps

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/store/persistConfig.ts [hunk 1]
```diff
@@ -122,12 +122,26 @@ const persistUserTransform = createTransform(
...
 );
 
+const persistOnboardingTransform = createTransform(
+  (inboundState: RootState['onboarding']) => {
+    const { events, ...state } = inboundState;
+    // Reconstruct data to persist
+    return state;
+  },
+  null,
+  { whitelist: ['onboarding'] },
```
Comment (Prithpal-Sooriya) [inline app/store/persistConfig.ts:132]: Very nice transform! Yep this is extensible if we need more control over the onboarding slice.

**Review by Prithpal-Sooriya — DISMISSED** [review]

File: app/store/persistConfig.ts (hunk 1 above)
Comment (Prithpal-Sooriya) [reply app/store/persistConfig.ts:132]: Is profile-sync a feature of 7.47.0? 

If no (it was released earlier), do we need to add back this onboarding state?

Comment (mathieuartu) [reply app/store/persistConfig.ts:132]: Re-added migration 71 disguised as 81 in consequence @Prithpal-Sooriya 🫡 🖖

File: app/store/migrations/081.ts [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+  }
+
+  try {
+    const KeyringController = state.engine.backgroundState.KeyringController;
+
+    if (
+      KeyringController &&
+      hasProperty(KeyringController, 'vault') &&
+      hasProperty(state, 'onboarding') &&
+      isObject(state.onboarding)
```
[the remark this answers is not in the document]
Comment (mathieuartu) [reply app/store/migrations/081.ts:23]: Oh you're actually right, might as well delete those two conditions. Will pick this up tomorrow morning!

**Review by Prithpal-Sooriya — APPROVED** [review]

File: app/store/index.ts [hunk 3]
```diff
@@ -64,12 +65,22 @@ const createStoreAndPersistor = async () => {
...
     // This sets the basic functionality value from the persisted state when the app is restarted
     store.dispatch(
-      toggleBasicFunctionality(
-        store.getState().settings.basicFunctionalityEnabled,
-      ),
+      toggleBasicFunctionality(currentState.settings.basicFunctionalityEnabled),
     );
+
+    // This sets the completedOnboarding value based on the KeyringController state
+    // This cannot be done in a migration because `state.onboarding` was previously blacklisted in `persistConfig`
```
Comment (tommasini) [inline app/store/index.ts:77]: Hmm, we will be running this unnecessarily multiple times if its not a migration, am I wrong?

 Also, it was blacklisted, but that shouldnt block us from creating it during the migration, right?

**Review by tommasini — APPROVED** [review]
