### PR TITLE
WalletConnect + Deeplink + RPC Methods Refactors

### LINKED ISSUE #2522: Issues signing messages with WalletConnect
**Describe the bug**

Using `eth_sign` with WalletConnect never resolves on bad input.

**To Reproduce**

1. Using `connector.signMessage([account, "not a hash"])` to sign an `eth_sign` message, promise never resolves
   - Note that the popup **does appear in the app** for signing the message
   - Selecting "Cancel" instead of "Sign" in the mobile app causes the promise to correctly revert with `MetaMask Message Signature: User denied message signature.`

<details><summary>Sample code:</summary>

```js
import WalletConnectProvider from "@walletconnect/web3-provider";

async function testSigningMethods() {
  const provider = new WalletConnectProvider({
    infuraId: process.env.INFURA_PROJECT_ID,
  });
  const [account] = await provider.enable();

  try {
    const signature = await Promise.race([
      provider.wc.signMessage([account, "Hello MetaMask!"]),
      delay(10000),
    ]);

    if (signature) {
      console.log(`SUCCESS: ${signature}`);
    } else {
      console.log(`TIMEOUT`);
    }
  } catch ({ message }) {
    console.log(`FAILURE: ${message}`);
  }
}
```

</details>

**Expected behavior**

- When handling a WalletConnect `eth_sign` request, the hash of `\x19Ethereum Signed Message:\n${message.length}${message}` should be computed and signed (like `personal_sign`). This would be inline with how [WalletConnect expects `eth_sign` requests to be handled](https://docs.walletconnect.org/json-rpc-api-methods/ethereum#eth_sign).
- Alternatively, if the behaviour of `eth_sign` doesn't want to be changed (although I don't think the legacy argument applies to the MetaMask mobile app with WalletConnect) the promise should reject when signing a message with bad input.

**Smartphone (please complete the following information):**
 - OS: Android 10
 - App Version: 2.0.1

### LINKED ISSUE #3376: method: 'wallet_watchAsset' is not launched in mobile version
My code include the next code to add my token. 
https://docs.metamask.io/guide/registering-your-token.html#code-free-example

Works correctly in navigator plugins but not in the mobile version.

### LINKED ISSUE #3415: Walletconnect support unreliable
**Describe the bug**
Using the walletconnect kotlin sample app, connecting may work the first time, then disconnect and try to connect again and metamask simply won't prompt anything. This happens also with another own implementation, I'm having a nightmare testing my dapp with metamask, sooooooooooooooooo unreliable. I must uninstall it each time I need to test the connection to the wallet otherwise the prompt will simply not appear. Also starting transactions will only work the first time right after linking my app to metamask, then I close metamask and try to send a transaction again no prompt at all.
Also the sessions seams to get dirty, after working a few hours you have many sessions with the same app in the list of sessions inside metamask, and despite you uninstalled the other app there are still sessions being listed which you can "close".

**To Reproduce**
_Steps to reproduce the behavior_
Try the sample from walletconnect https://github.com/mobilekosmos/kotlin-walletconnect-lib/tree/master/sample/app
- Connect and disconnect few times, and try to send a transaction a few times, you will se that metamask most of the time won't react.

**Smartphone (please complete the following information):**
 - Device: Galaxy S9
 - OS: Android 10
 - App Version: 3.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### LINKED ISSUE #3524: Transaction response is not getting passed back to Dapp
### **Description**

Hello, sorry if this is the wrong place to post this. I am just puzzled and looking for some more info!

Currently we interact with a contract using ethers, the user authenticates with an injected metamask provider, and everything is dandy. What my problem is now is I am authenticating users on mobile with Wallet Connect, and transactions are _succeeding_, but I do not get any response to update my UI.

Here is an example (names have been replaced but this contract WORKS and is functioning completely fine on desktop)

```javascript
const tx = await signedDemoContract.customContractMethod(PARAM);

console.log("TX", tx);

const txReceipt = await tx.wait();

console.log("TX RES", txReceipt);
```

What happens on mobile is when we hit the contract interaction, the user is redirected to their mobile wallet (I have tested with mobile metamask) and they are given the option to approve or reject the transaction. After approving, I wait on metamask and they give me a notification that the transaction succeeds. I can verify this by checking etherscan.

When I go back to my dapp, the first `console.log('TX')` does not even log. We don't even get to the waiting portion because the first transaction response does not return. So is this an issue in the way I am setting up the contract with ethers, or maybe a metamask/wallet connect problem? Sorry there are a lot of moving parts.

Super bizarre, but it's like Metamask is not even returning the transaction response. Any help is appreciated!!

### **Technical Details**

- Connecting using Wallet Connect
- Also using web3 React
- Redirects to Metamask just fine
- Transactions SUCCEEDS but does not return status to Dapp

### LINKED ISSUE #3581: [SDK] Implement global RPC methods middleware
ETA: 2 weeks

Check the following implementations:
- Browser
- Wallet connect
- Engine
- Deeplinks (?)

Refactor in a way that all the RPC methods are used in one place.

Implement tests for all rpc methods.

### LINKED ISSUE #3583: [SDK] Refactor Deeplinks
ETA: 2 weeks

- Look at issues
- Start DeeplinkManager from scratch

DeepLink & WalletConnect Tasks and bugs (filter by deeplink)

- https://github.com/MetaMask/metamask-mobile/issues/1695
- https://github.com/MetaMask/metamask-mobile/issues/3580
- https://github.com/MetaMask/metamask-mobile/issues/3534
- https://github.com/MetaMask/metamask-mobile/issues/3552
- https://github.com/MetaMask/metamask-mobile/issues/3525
- https://github.com/MetaMask/metamask-mobile/issues/3521
- https://github.com/MetaMask/metamask-mobile/issues/3399
- https://github.com/MetaMask/metamask-mobile/issues/3395
- https://github.com/MetaMask/metamask-mobile/issues/3326
- https://github.com/MetaMask/metamask-mobile/issues/3216

Commits/PR:
- https://github.com/MetaMask/metamask-mobile/pull/3570
- https://github.com/MetaMask/metamask-mobile/pull/3566
- https://github.com/MetaMask/metamask-mobile/pull/3560
- https://github.com/MetaMask/metamask-mobile/pull/3220
- https://github.com/MetaMask/metamask-mobile/pull/3120
- https://github.com/MetaMask/metamask-mobile/pull/3627

### PR DESCRIPTION
**Pull request by andrepimenta**
**Description**

Refactors:
- RPC Methods
- WalletConnect
- Deeplinks

We need to test:
- All browser interactions because of the change on RPC Methods
- WalletConnect (check WC issues)
- Deeplinks  (check Deeplinks issues)

---

This PR includes the following work:
https://github.com/MetaMask/metamask-mobile/pull/3637
https://github.com/MetaMask/metamask-mobile/pull/3570
https://github.com/MetaMask/metamask-mobile/pull/3627

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #3583
Resolves #3376
Resolves #3581
Resolves #2522 
Resolves #3415 
Resolves #3524

### CODE REVIEW

File: app/core/BackgroundBridge.js [hunk 1]
```diff
@@ -103,13 +151,19 @@ export class BackgroundBridge extends EventEmitter {
 	}
 
 	onUnlock() {
+		// TODO UNSUBSCRIBE EVENT INSTEAD
```
Comment (sethkfman) [inline app/core/BackgroundBridge.js:154]: Is this for a future work or something you want to do for this PR?

File: app/core/DeeplinkManager.js [hunk 2]
```diff
@@ -103,92 +117,77 @@ class DeeplinkManager {
...
-			case 'wc':
-				handled();
-				if (!WalletConnect.isValidUri(url)) return;
-				// eslint-disable-next-line no-case-declarations
-				const redirect = params && params.redirect;
-				// eslint-disable-next-line no-case-declarations
-				const autosign = params && params.autosign;
-				WalletConnect.newSession(url, redirect, autosign);
+			case PROTOCOLS.WC:
+				handled(); //TODO: check if we have to handle it here or handle after the next isValidUri check
```
Comment (sethkfman) [inline app/core/DeeplinkManager.js:152]: Remove TODO if this is the correct location of `handled`

File: app/core/WalletConnect.js [hunk 3]
```diff
@@ -106,177 +135,62 @@ class WalletConnect {
...
-								data,
-								from,
-								meta: {
-									title: meta && meta.name,
-									url: meta && meta.url,
-									icon: meta && meta.icons && meta.icons[0],
-								},
-								origin: WALLET_CONNECT_ORIGIN,
+
+					// Engine eth_sendTransaction not working - can't send correct origin
```
Comment (sethkfman) [inline app/core/WalletConnect.js:150]: Remove comment if no longer valid

File: ios/MetaMask/AppDelegate.m [hunk 4]
```diff
@@ -33,8 +33,11 @@ - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(
     foxCode = @"debug";
   }
   
-  [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
-  
+  // Uncomment this line to use the test key instead of the live one.
+  // [RNBranch useTestInstance];
```
Comment (sethkfman) [inline ios/MetaMask/AppDelegate.m:37]: Could we just a debug boolean instead of uncommenting?

**Review by sethkfman — COMMENTED** [review]
A few minor comments.

File: android/app/src/main/AndroidManifest.xml [hunk 5]
```diff
@@ -51,10 +51,14 @@
 				<action android:name="android.intent.action.VIEW" />
 				<category android:name="android.intent.category.DEFAULT" />
 				<category android:name="android.intent.category.BROWSABLE" />
-				<data android:scheme="https" android:host="metamask.app.link" />
-				<data android:scheme="https" android:host="metamask-alternate.app.link" />
-				<data android:scheme="https" android:host="metamask.test-app.link" />
-				<data android:scheme="https" android:host="metamask-alternate.test-app.link" />
+				<data android:scheme="https" />
```
[the remark this answers is not in the document]
Comment (andreahaku) [reply android/app/src/main/AndroidManifest.xml:54]: yes this is how the Android 12 compatibility issues are solved. We need to separate 'scheme' and 'host' tags. And so it needs to be repeated for each 'host'.

File: ios/MetaMask/AppDelegate.m (hunk 4 above)
Comment (andreahaku) [reply ios/MetaMask/AppDelegate.m:37]: I'm not an iOS developer and don't know how to get if it's debug. Also it's not said that we want to use test in debug as well. So I prefer to keep the comment and eventually uncomment while developing.

File: app/core/DeeplinkManager.js (hunk 2 above)
Comment (andreahaku) [reply app/core/DeeplinkManager.js]: fixed :) thanks

File: app/core/BackgroundBridge.js (hunk 1 above)
Comment (andrepimenta) [reply app/core/BackgroundBridge.js:154]: This is a bit out of scope, it would need controllers work on the keyring part. I will leave the todo there for future reference.

File: app/core/WalletConnect.js (hunk 3 above)
Comment (andrepimenta) [reply app/core/WalletConnect.js]: Comment fixed

**Review by andreahaku — APPROVED** [review]

**Review by cortisiko — APPROVED** [review]
🌮 🌮 🌮 🌮 🌮
