### PR TITLE
fix: PPOM - Malicious transactions triggered from Deeplinks are not flagged

### LINKED ISSUE #7543: [Bug]: PPOM - Malicious transactions triggered from Deeplinks are not flagged
### Describe the bug

**Problem**: malicious transactions triggered from Deeplinks are not flagged by Blockaid

### Expected behavior

Malicious transactions triggered from deeplinks should also be flagged by Blockaid.

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/edbe2046-6046-4c26-a2ad-3037807d9b71

### Steps to reproduce

1. Generate a malicious link
2. Scan the QR code
3. See how no warning appears

To generate a malicious link. You can use:
- https://metamask.github.io/metamask-deeplinks/# and add the malicious recipeint 0x5FbDB2315678afecb367f032d93F642f64180aa3
-Or modify any links from here, to use the same data as the test dapp https://cortisiko.github.io/ I.e.

Links
- Send ETH: https://metamask.app.link/send/0x5FbDB2315678afecb367f032d93F642f64180aa3?value=3e13
- Malicious Approve: https://metamask.app.link/approve/0x4fabb145d64652a948d72533023f6e7a623c7c53@1/approve?address=0xe50a2dbc466d01a34c3e8b7e8e45fce4f7da39e6&uint256=3e18

### Error messages or log output

_No response_

### Version

Integrate PPOM branch  (behind feature flag) https://github.com/MetaMask/metamask-mobile/pull/7363
In main once the PR is merged
 
### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by segun**
## **Description**

When a malicious transaction is triggered from a dapplink, the blockaid banner alert is not shown. This is because the transaction is shown in the confirm screen after evaluation without calling PPOM.

The fix is to call PPOM before showing the transaction in the confirm screen.

## **Related issues**

Fixes: #7543 

## **Manual testing steps**

1. Goto https://metamask.github.io/metamask-deeplinks/# and generate a malicious Payment Request, set the recipient to this malicious address: 0x5FbDB2315678afecb367f032d93F642f64180aa3
2. Open MM Mobile and scan the QR code generated in 1 above
3. Enable Blockaid in Experimental Settings
4. You should not see a Blockaid alert
5. Checkout this branch, build and run on a physical device
6. Scan the QR code generated in 1 above
7. You should see a Blockaid alert.

### **Before**

Screenshot 2023-11-07 at 11 06 22

### **After**

Screenshot 2023-11-07 at 11 05 10

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/Send/index.js [hunk 1]
```diff
@@ -409,6 +411,24 @@ class Send extends PureComponent {
...
+      jsonrpc: '2.0',
+      method: 'eth_sendTransaction',
+      params: [
+        {
+          from: selectedAddress,
+          to: newTxMeta.transactionTo,
+          value: newTxMeta.value,
+        },
+      ],
+    };
```
Comment (digiwand) [inline app/components/Views/Send/index.js:426]: I think we can add these two in the if block as well and use const for securityAlertResponse

**Review by jpuri — APPROVED** [review]

**Review by blackdevelopa — APPROVED** [review]

**Comment by jpuri** [comment]
@segun : looking at the latest code, I see an issue in this fix. Blockaid validations are not done for all send requests and since code is also called from `componentDidUpdate` it is happening repeatedly.
