### PR TITLE
fix: display chainId as decimal

### LINKED ISSUE #15127: [Bug]: Networks -  chain ids have been changed to their corresponding hex values
### Describe the bug

  chain ids have been changed to their corresponding hex values

### Expected behavior

_No response_

### Screenshots/Recordings

Image

### Steps to reproduce

1. Open network details
2. See chain id

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.45.0

### Build type

None

### Device

Pixel 6

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR to fix displaying chainId as decimal.

## **Related issues**

Fixes: Partially fixes https://github.com/MetaMask/metamask-mobile/issues/15127 , recommended to open a new ticket for  deep linking UX.

## **Manual testing steps**

1. Click on network selector
2. Choose any network and click edit
3. You should see the chainId in the placeholder in decimal format.

### **After**

Screenshot 2025-05-05 at 19 45 33

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by vinnyhoward — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by chrisleewilcox — DISMISSED** [review]
LGTM

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 1]
```diff
@@ -2077,7 +2077,7 @@ export class NetworkSettings extends PureComponent {
               style={inputChainIdStyle}
               autoCapitalize={'none'}
               autoCorrect={false}
-              value={chainId}
+              value={this.getDecimalChainId(chainId)}
```
Comment (tommasini) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js]: Can we use getDecimalChainId from utils instead? https://github.com/MetaMask/metamask-mobile/blob/44296de37beb65f3182068b643989571a022cbc0/app/util/networks/index.js#L214

We could remove this code as this seems to be using a util function created in the class component

Comment (sahar-fehri) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js]: Updated here [c98169b](https://github.com/MetaMask/metamask-mobile/pull/15140/commits/c98169bb317413111aa47a804121565c9aefa755) 🙏

[the remark this answers is not in the document]
Comment (sahar-fehri) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js]: Hi @digiwand ! this seems like a different issue than the one the PR is trying to fix.
The issue reported is related to clicking on Edit button and seeing decimal chainId displayed instead of hex.
(which aligns with extension experience)
Agree with what you mentioned that the behavior seen in your shared video should change, also to align with extension and allow entering both hex and decimal; but still show decimal when clicking on "edit" button.

I think this should be fixed separately, wdyt?

Side note; in your video you had to go to Settings => Networks to see that component. that should be removed since it has been also removed in extension.

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by tommasini — DISMISSED** [review]

**Review by chrisleewilcox — DISMISSED** [review]

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js [hunk 2]
```diff
@@ -2061,7 +2061,7 @@ export class NetworkSettings extends PureComponent {
               style={inputChainIdStyle}
               autoCapitalize={'none'}
               autoCorrect={false}
-              value={getDecimalChainId(chainId)}
+              value={addMode ? chainId : getDecimalChainId(chainId)}
```
Comment (sahar-fehri) [inline app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js:2064]: when user is adding a new network; addMode=true we keep the current behavior that supports adding both hex and decimal. When the user is only viewing the network; addMode= false; hence we display decimal value always

File: app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (digiwand) [reply app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js]: hey @sahar-fehri, 

I saw the update to preserve the '0x' input support https://github.com/MetaMask/metamask-mobile/pull/15140/commits/55450fcaae4373cf92eb505797045e0b2e645e08. I didn't get to test it again, but the code looks good to me

**Review by digiwand — APPROVED** [review]

**Review by salimtb — APPROVED** [review]

**Review by tommasini — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by erdimaden — APPROVED** [review]

**Review by vinnyhoward — APPROVED** [review]

**Review by NidhiKJha — APPROVED** [review]
