### PR TITLE
fix: Fix `disabled` send button on sending `erc721` and `erc20`

### LINKED ISSUE #12317: [Bug]: When attempting to send an ERC-721 token, users encounter an issue where the "Next" button is disabled, preventing the transaction from proceeding. Furthermore, this issue persists into subsequent attempts to send ERC-20 tokens, with the "Next" button remaining disabled on the Confirmation screen
### Describe the bug

When attempting to send an ERC-721 token, users encounter an issue where the "Next" button is disabled, preventing the transaction from proceeding. Furthermore, this issue persists into subsequent attempts to send ERC-20 tokens, with the "Next" button remaining disabled on the Confirmation screen and 'Fiat conversions are not available at this moment' message shown.
Additionally on the assets picker while on NFT tab only ERC 20 tokens displayed.

Seems like it first appeared in 7.43.0, also present in 7.36.0

Related:  https://github.com/MetaMask/metamask-mobile/issues/12972

### Expected behavior

-

### Screenshots/Recordings

Sending ERC 721 works as expected in 7.33.2:

https://github.com/user-attachments/assets/3078beb4-d6c8-4711-8224-5e9ed9975ff2

Bug in 7.34.0:

https://github.com/user-attachments/assets/8d550c25-894a-4a51-b083-0cd0c9b75f46

Bug in 7.36.0:

https://github.com/user-attachments/assets/25988b20-d4af-4cbf-904e-0533cf5bcc4c

### Steps to reproduce

1. Have an account with ERC 721 tokens
2. Switch to NFTs tab
3. Start Send transaction for the ERC 721 token
4. Observe that 'Next' button is disabled
5. Switch to the Tokens tab
6. Start Send transaction for any token
7. Observe 'Fiat conversions are not available at this moment' message and disabled 'Next' button

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

7.34.0 (1462)

### Build type

None

### Device

iPhone 15

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to fix issue where users having issue on sending `ERC721` tokens. 

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12317

## **Manual testing steps**

See original issue

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/confirmations/SendFlow/Amount/index.js [hunk 1]
```diff
@@ -1188,21 +1188,24 @@ class Amount extends PureComponent {
   processCollectibles = () => {
     const { collectibleContracts } = this.props;
     const collectibles = [];
-    this.props.collectibles
```
Comment (OGPoyraz) [inline app/components/Views/confirmations/SendFlow/Amount/index.js:1191]: Mutating props using .sort here doesn't throw an error but silently crashes the function.

This prevents componentDidMount from being invoked and disrupts almost the entire flow.

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by matthewwalsh0 — DISMISSED** [review]

File: app/components/Views/confirmations/SendFlow/Amount/index.js (hunk 1 above)
Comment (matthewwalsh0) [reply app/components/Views/confirmations/SendFlow/Amount/index.js:1191]: Could this have been verified originally and now with a unit test?

Comment (OGPoyraz) [reply app/components/Views/confirmations/SendFlow/Amount/index.js:1191]: I was thinking about this but rather than specifically testing this mutation issue, I will add the broken test NFT state as default. 

On unit tests, account was not having any NFTs hence this problematic `.sort` was not invoked because of empty `collectibles`.

**Comment by Unik0rnMaggie** [comment]
Tested the fix for Android:

- On Ethereum Mainnet there is an error when trying to send ERC721 token and after that, native token.

Despite the error, the Tx is successful, for both the NFT and the ETH token.

- On Linea and Base, the MM app closes after sending the NFT. But the Tx is still successful:


https://github.com/user-attachments/assets/ac6f268a-a101-4f2c-b924-ddbddddaef16


https://github.com/user-attachments/assets/2e6e7354-d64b-4696-9076-ffb10d2f0741


Is seems to be the same behavior as in v7.39.0, described [here](https://github.com/MetaMask/metamask-mobile/issues/12317#issuecomment-2598593991)

File: app/components/Views/confirmations/hooks/useConfirmationRedesignEnabled.ts [hunk 2]
```diff
@@ -16,7 +16,9 @@ export const useConfirmationRedesignEnabled = () => {
     type: approvalRequestType,
     requestData: { from: fromAddress },
   } = approvalRequest ?? {
-    requestData: {},
+    requestData: {
+      from: '',
```
Comment (OGPoyraz) [inline app/components/Views/confirmations/hooks/useConfirmationRedesignEnabled.ts:20]: This is a hacky fix for given task. 

In my opinion if there is no `approvalRequest` then it shouldn't even come at this point. `Confirm` component is trying to render - we should prevent that to happen. Then we will not need this optional nullish coalescing operator on `approvalRequest`

File: app/core/NotificationManager.js [hunk 3]
```diff
@@ -250,9 +250,6 @@ class NotificationManager {
             );
             break;
           }
-          case 'ERC721':
-            pollPromises.push(NftDetectionController.start());
```
Comment (OGPoyraz) [inline app/core/NotificationManager.js:254]: This is breaking app if you we are transaction asset type is `ERC721`. There is no `start` function in `NftDetectionController` so crashing app.

**Comment by Unik0rnMaggie** [comment]
Tested the fix on iOS, using the build from [here](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/28671a099f72ab5b) and it's a similar behavior to Android:


https://github.com/user-attachments/assets/785d3061-0029-49df-b54e-562198511042

**Comment by sleepytanya** [comment]
@OGPoyraz @Unik0rnMaggie Can it the same issue as exactly same error message is documented here? https://github.com/MetaMask/metamask-mobile/issues/13046

**Comment by sleepytanya** [comment]
Android Bitrise build https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/3f96e64202856b47


Tested on Base, Polygon, Linea Sepolia and Sepolia with STX ON and OFF - sending NFT and native+non-native tokens after works as expected:


https://github.com/user-attachments/assets/b90c2aff-b0cf-437c-86fa-bd5ac1705047



https://github.com/user-attachments/assets/bfd3b293-abde-4aae-a762-66f82bed1df0




https://github.com/user-attachments/assets/792d0c8f-1484-48e3-8b18-4638db3f3dee

**Comment by sleepytanya** [comment]
iOS QA build https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/496fefc308d590d0

Sending NFT and consecutive native / non-native tokens transactions works as expected:


https://github.com/user-attachments/assets/52ae30d7-4f2f-4ffd-ac68-b290667417b4

File: app/components/Views/confirmations/hooks/useConfirmationRedesignEnabled.ts (hunk 2 above)
Comment (jpuri) [reply app/components/Views/confirmations/hooks/useConfirmationRedesignEnabled.ts:20]: @OGPoyraz : confirmation components do not render if there is no `approvalRequest`. But it's hard to return before the line above as we can not return before all hooks are executed.

**Review by jpuri — DISMISSED** [review]
Looks good 👍

File: app/components/Views/confirmations/hooks/useConfirmationRedesignEnabled.ts (hunk 2 above)
Comment (OGPoyraz) [reply app/components/Views/confirmations/hooks/useConfirmationRedesignEnabled.ts:20]: We can make it work something similar to this in `Confirm` component.

```
import useApprovalRequest from '../hooks/useApprovalRequest';

const RedesignedConfirmation = () => {
  const { isRedesignedEnabled } = useConfirmationRedesignEnabled();
  const { styles } = useStyles(styleSheet, {});

  if (!isRedesignedEnabled) {
    return null;
  }

  return (
    <BottomModal canCloseOnBackdropClick={false}>
      <View style={styles.container}>
        <View>
          <Title />
          {/* TODO: component SignatureBlockaidBanner to be removed once we implement alert system in mobile */}
          <SignatureBlockaidBanner />
          <AccountNetworkInfo />
          <Info />
        </View>
        <Footer />
      </View>
    </BottomModal>
  );
};

const Confirm = () => {
  const { approvalRequest } = useApprovalRequest();

  if (!approvalRequest) {
    return null;
  }

  return <RedesignedConfirmation />;
};

export default Confirm;
```

Comment (jpuri) [reply app/components/Views/confirmations/hooks/useConfirmationRedesignEnabled.ts:20]: Please note that `useConfirmationRedesignEnabled` is the first hook in re-designed flow and the only hook which will execute even if there is no request, it's kind of entry point.

We can achieve early return in `useMemo` hook if we use whole of `approvalRequest` as dependency, but I am trying to avoid that.

Comment (OGPoyraz) [reply app/components/Views/confirmations/hooks/useConfirmationRedesignEnabled.ts:20]: Maybe I am missing the obvious, what is the point of calling `useConfirmationRedesignEnabled` if there is no `approvalRequest`? 

If we allow to do that, we need to satisfy all types with bunch of optional chains which is error prone, exactly the reason that we faced the issue below.

image

**Comment by Unik0rnMaggie** [comment]
Hi @OGPoyraz and @sleepytanya !


Tested with above builds that Tanya shared and it seems that for Ethereum Mainnet, when STX is ON, the error is still showing:


**View: Root
TypeError: null is not an object (evaluating 'p.requestData.from')**



https://github.com/user-attachments/assets/b2bb6465-3593-4e71-a63c-19750cd16eae


https://github.com/user-attachments/assets/45265e46-04a4-4142-9139-91f52db9c0ee


When Smart Transactions is OFF, it works as expected:


https://github.com/user-attachments/assets/2c22b12f-f096-4661-936b-4b895070f8fc

File: app/util/smart-transactions/smart-publish-hook.ts [hunk 4]
```diff
@@ -372,6 +372,9 @@ class SmartTransactionHook {
         isSwapApproveTx: this.#isSwapApproveTx,
         isSwapTransaction: this.#isSwapTransaction,
       },
+      requestData: {
```
Comment (OGPoyraz) [inline app/util/smart-transactions/smart-publish-hook.ts:375]: Assuming this is fine to add this, otherwise it will fail.
Screenshot 2025-01-22 at 08 28 46

**Review by jpuri — DISMISSED** [review]

**Review by vinistevam — DISMISSED** [review]

**Comment by Unik0rnMaggie** [comment]
Retested using the latest QA build from [here](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/b84f787a-8eb2-4197-9ae9-1441249e26cb?tab=artifacts) and sending NFT and native token works as expected, with both STX ON and OFF:

STX ON:

https://github.com/user-attachments/assets/6d9e8a9c-d6fa-40a6-bd02-8686e8c03af0

https://github.com/user-attachments/assets/aa9ce195-c2da-4e97-809a-65402fa87cd3


STX OFF:

https://github.com/user-attachments/assets/47f9b2d9-df66-4c32-b8e4-4b972bc5fa1f

File: app/components/Views/confirmations/hooks/useConfirmationRedesignEnabled.ts [hunk 5]
```diff
@@ -12,12 +12,8 @@ export const useConfirmationRedesignEnabled = () => {
   const { isSigningQRObject, isSyncingQRHardware } = useQRHardwareAwareness();
   const { confirmation_redesign } = useSelector(selectRemoteFeatureFlags);
 
-  const {
-    type: approvalRequestType,
-    requestData: { from: fromAddress },
-  } = approvalRequest ?? {
```
Comment (OGPoyraz) [inline app/components/Views/confirmations/hooks/useConfirmationRedesignEnabled.ts:18]: Destructing object here is not working as expected. Because even if `approvalRequest` is defined - `requestData` could be null. That's being an issue with those approvals without `requestData`

**Review by vinistevam — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Comment by OGPoyraz** [comment]
`SmokeConfirmations: Advanced Gas Fees and Priority Tests should edit priority gas settings and send ETH`
is failing on the e2e tests but I believe this PR has nothing to do with those flows. You can also find passing e2e flows above, hence I am assuming those tests are flaking.
