### PR TITLE
fix: add logic to compute the correct non-EVM network image source using `getNetworkImageSource`

### LINKED ISSUE #22787: [Bug]: Networks - Incorrect Network (Solana) is displayed on dapp browsing when I have Bitcoin/ or Tron selected in my wallet
### Describe the bug

Incorrect Network (Solana) is displayed on dapp browsing when I have Bitcoin/ or Tron selected in my wallet

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/e2d114cb-2a99-497b-9417-ee7877e98fc7

### Steps to reproduce

1. Select Bitcoin or Tron network in your wallet
2. Click on browser
3. See network icon displays Solana

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.60.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ffmcgee725**
## **Description**

Incorrect Network (Solana) is displayed on dapp browsing when I have Bitcoin/ or Tron selected in my wallet, because current logic either renders EVM selected network, or defaults to Solana when something other than EVM is selected.

This PR proposes a fix to handle non EVM networks accordingly.

## **Changelog**

CHANGELOG entry: Add logic to compute the correct non-EVM network image source using `getNetworkImageSource`

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/22787

## **Manual testing steps**

```gherkin
Feature: Non EVM Image for AccountRightButton Component

  Scenario: user selects non evm network
    Given he does so in In App Browser

    When user selects non evm network via In App Browser AccountRightButton
    Then the correct network image should be displayed
```

### **Before**

https://github.com/user-attachments/assets/e2d114cb-2a99-497b-9417-ee7877e98fc7

### **After**

https://github.com/user-attachments/assets/5ca5dc99-e94a-41e3-a48c-371762a7320c

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Computes the proper non-EVM network image using getNetworkImageSource and replaces the hardcoded Solana fallback in AccountRightButton.
> 
> - **UI**:
>   - **AccountRightButton (`app/components/UI/AccountRightButton/index.tsx`)**:
>     - Compute non-EVM network image via `useMemo` and `getNetworkImageSource` using `selectedNonEvmNetworkChainId`.
>     - Replace hardcoded Solana fallback with computed `imageSource`; EVM logic unchanged.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 2851891dd74c2ca35f59db0ebea87e8cf1738833. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/AccountRightButton/index.tsx [hunk 1]
```diff
@@ -156,6 +164,12 @@ const AccountRightButton = ({
 
   const { networkName, networkImageSource } = useNetworkInfo(hostname);
 
+  const nonEvmNetworkImageSource = useMemo(() => {
```
Comment (wenfix) [inline app/components/UI/AccountRightButton/index.tsx:167]: [nit]: could this logic be moved into `useNetworkInfo`?

**Review by wenfix — DISMISSED** [review]

File: app/components/UI/AccountRightButton/index.tsx (hunk 1 above)
Comment (ffmcgee725) [reply app/components/UI/AccountRightButton/index.tsx:167]: https://github.com/MetaMask/metamask-mobile/pull/23089/commits/a89c500f5b9274ac810b0c186190297f8f1a24dd

**Review by wenfix — DISMISSED** [review]

**Review by wenfix — DISMISSED** [review]

**Review by wenfix — APPROVED** [review]
