### PR TITLE
fix(bridge): resolve duplicate tokens in destination selector with CAIP normalization

### LINKED ISSUE #16195: [Bug]: Solana - Swap - Repeated asset in the token list with imported token
### Describe the bug

Whenever I start a Swap in Solana, when I click on the asset and I see the asset list, I see a repeated token (USDC) if I already have that token in my wallet.
I'm unsure if this is because there's a miss-match between the detect token list and the swap list (see USDC and USD Coin) or if it happens to all tokens

### Expected behavior

No repeated tokens in the token list

### Screenshots/Recordings

Image

https://github.com/user-attachments/assets/186f054b-a06f-46dd-a457-3b87a80b2e56

### Steps to reproduce

1. Select Solana network
2. Get some USDC and import it into your wallet
3. Start a Swap from SOL
4. Click destination token
5. See 2 entries for USDC

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.47 (1953)

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by amitabh94**
## **Description**

This PR addresses the issue of repeated assets appearing in the Bridge destination token selector by implementing CAIP asset type normalization for the bridge tokens.

### **Root Cause:**

The duplicate token issue was caused by inconsistent address formats between Solana tokens returned by the Bridge API (raw format) and default destination tokens (CAIP format). This inconsistency prevented proper deduplication in the token selector.

## **Related issues**

Fixes: [SWAPS-1834](https://consensyssoftware.atlassian.net/browse/SWAPS-1834)
Fixes : #16195 

## **Manual testing steps**

1. Navigate to the Bridge feature in MetaMask Mobile
2. Select Solana as source or destination chain
3. Open the token selection dropdown
4. Verify that no duplicate tokens appear in the destination selector
5. Verify the default token is correctly highlighted
6. Test with EVM chains to confirm no regression
7. Verify that historical prices display correctly for Solana tokens
8. Test asset overview pages to ensure proper token details display

### **Before**

https://github.com/user-attachments/assets/1090db75-1206-49cb-a3bf-8247045ed001

### **After**

https://github.com/user-attachments/assets/0a319cde-f553-4c9a-ae16-2b89a62ce627

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

[SWAPS-1834]: https://consensyssoftware.atlassian.net/browse/SWAPS-1834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by amitabh94** [comment]
bugbot run

File: app/components/UI/Bridge/utils/index.ts [hunk 1]
```diff
@@ -58,3 +60,23 @@ export const wipeBridgeStatus = (address: string, chainId: Hex | CaipChainId) =>
...
+ */
+export function normalizeToCaipAssetType(
+  address: string,
+  chainId: Hex | CaipChainId,
+): string {
+  if (isSolanaChainId(chainId)) {
+    if (isCaipAssetType(address)) {
+      return address;
+    }
+    return `${chainId}/token:${address}`;
```
Comment (micaelae) [inline app/components/UI/Bridge/utils/index.ts]: Do you plan to use this for SOL? Is it worth adding a condition here to return `slip44:501` if it's the "native" address? On extension possible native addresses include zeroAddress, empty string or null

Comment (amitabh94) [reply app/components/UI/Bridge/utils/index.ts]: I have simplified the util function to just be a normalizing function and other functions can check fo r evm/non-evm before normalizing. This is because normalizing was happening at different places so just refactoring to bring it into a util function . We may want to think of adding slip44 for different chains as an enhancement going forward as we introduce more chains.

**Review by micaelae — APPROVED** [review]

**Review by SteP-n-s — APPROVED** [review]
