### PR TITLE
fix: fix non regression tests

### LINKED ISSUE #11892: [Bug]: Unable to add alternate RPC URL manually on iPhone
### Describe the bug

The 'Add RPC URL' modal unexpectedly closes when a user attempts to paste or manually enter the URL.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/4a48a240-c0aa-4216-a4f0-e84688e02101

### Steps to reproduce

1. Go to networks list
2. Edit one of the networks
3. Try to add new RPC URL manually

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

7.34.0 (1462)

### Build type

None

### Device

iPhone 15

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**
This PR addresses multiple areas to improve the stability and maintainability of the project:

1. Fix Non-Regression Tests
2. Code Cleanup
3. Increased Code Quality

## **Related issues**

Fixes: #11892 #11893 

## **Manual testing steps**

1. Run non regression test on this branch

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: e2e/pages/Settings/NetworksView.js [hunk 1]
```diff
@@ -149,6 +139,10 @@ class NetworkView {
   }
 
   async tapAddRpcButton() {
+    /* android is failing to tap on this element
```
Comment (cortisiko) [inline e2e/pages/Settings/NetworksView.js:142]: Feel free to remove this comment

**Review by cortisiko — COMMENTED** [review]
small feedback to remove comment

**Review by cortisiko — DISMISSED** [review]
✅ ✅

**Comment by salimtb** [comment]
non regression test: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/d2a66d74-5960-4642-a292-aca9b42586ec

File: app/components/Views/NetworkSelector/RpcSelectionModal/RpcSelectionModal.tsx [hunk 2]
```diff
@@ -0,0 +1,144 @@
...
+          {rpcEndpoints.map(
+            (
+              {
+                url,
+                networkClientId,
+              }: { url: string; networkClientId: string },
+              index: number,
+            ) => (
+              <ListItemSelect
+                key={index}
```
Comment (andreahaku) [inline app/components/Views/NetworkSelector/RpcSelectionModal/RpcSelectionModal.tsx:106]: probably it would be better to use `networkClientId` instead of `index` as a key

File: app/components/Views/NetworkSelector/RpcSelectionModal/RpcSelectionModal.tsx [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+const RpcSelectionModal: FC<RpcSelectionModalProps> = ({
+  showMultiRpcSelectModal,
+  closeRpcModal,
+  onRpcSelect,
+  rpcMenuSheetRef,
+  networkConfigurations,
+  styles,
+}) => {
+  const renderRpcSelection = useCallback(() => {
+    let imageSource;
```
Comment (andreahaku) [inline app/components/Views/NetworkSelector/RpcSelectionModal/RpcSelectionModal.tsx:49]: I'd create an helper function and memoize it for the `imageSource` like:
```
const imageSource = useMemo(() => {
  switch (showMultiRpcSelectModal.chainId) {
    case CHAIN_IDS.MAINNET:
      return images.ETHEREUM;
    case CHAIN_IDS.LINEA_MAINNET:
      return images['LINEA-MAINNET'];
    default:
      return getNetworkImageSource({
        chainId: showMultiRpcSelectModal?.chainId?.toString(),
      });
  }
}, [showMultiRpcSelectModal.chainId]);
```

**Review by andreahaku — COMMENTED** [review]
a couple of comments on `RpcSelectionModal` component

**Review by andreahaku — DISMISSED** [review]
LGTM

File: app/store/migrations/055.ts [hunk 4]
```diff
@@ -381,23 +377,6 @@ export default function migrate(state: unknown) {
       );
   }
 
-  // Migrate the user's drag + drop preference order for the network menu
```
Comment (tommasini) [inline app/store/migrations/055.ts:384]: Hmm is there a reason why we do not need this migration anymore? This is being shipped to some users, and some user will have this code applied in 7.34.0 that is already in testing, does this mean this work needs to be cherry picked?

File: app/components/Views/NetworkSelector/RpcSelectionModal/RpcSelectionModal.tsx [hunk 5]
```diff
@@ -0,0 +1,133 @@
...
+  showMultiRpcSelectModal: {
+    isVisible: boolean;
+    chainId: string;
+    networkName: string;
+  };
+  closeRpcModal: () => void;
+  onRpcSelect: (networkClientId: string, chainId: `0x${string}`) => void;
+  rpcMenuSheetRef: React.RefObject<BottomSheetRef>;
+  networkConfigurations: Record<string, NetworkConfiguration>;
+  // TODO: Replace "any" with type
```
Comment (tommasini) [inline app/components/Views/NetworkSelector/RpcSelectionModal/RpcSelectionModal.tsx:35]: Can this todo be addressed?

**Review by tommasini — DISMISSED** [review]

File: app/store/migrations/055.ts (hunk 4 above)
Comment (salimtb) [reply app/store/migrations/055.ts]: fixed

**Review by cortisiko — APPROVED** [review]

**Review by andreahaku — APPROVED** [review]
LGTM
