### PR TITLE
Make selected option comes first in picker component on Android

### LINKED ISSUE #3611: Users have problem exiting the pop up when they are choosing currency in settings on Android
**Describe the bug**
Users have problem exiting the pop up when they are choosing currency in settings on Android

**Screenshots**
Screen Shot 2022-01-20 at 17 11 43

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Settings > General > Currency

**Expected behavior**
Users should be able to exit 

**Smartphone (please complete the following information):**
 - OS: Android

### PR DESCRIPTION
**Pull request by Fatxx**
**Description**

The selected option is now the first option in Picker select component, this will make less annoying for the users to close the popup if they don't have to change the value on Android.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #3611

### CODE REVIEW

File: app/components/UI/SelectComponent/index.js [hunk 1]
```diff
@@ -161,9 +161,32 @@ export default class SelectComponent extends PureComponent {
...
 				prompt={this.props.label}
 			>
-				{this.props.options.map((option) => (
-					<PickerItem value={option.value} label={option.label} key={option.key} />
-				))}
+				{this.props.options
+					/**
+					 * Select value always comes first
+					 */
+					.sort((a, b) => {
```
Comment (andreahaku) [inline app/components/UI/SelectComponent/index.js:168]: if you want to be more concise you can do:
`.sort((a, b) =>
	a.value === this.props.selectedValue
		? -1
		: b.value === this.props.selectedValue
		? 0
		: a.value > b.value
		? 1
		: a.value < b.value
		? -1
		: 0
);`

**Comment by chrisleewilcox** [comment]
LGTM

**Review by chrisleewilcox — APPROVED** [review]

**Review by chrisleewilcox — APPROVED** [review]
