### PR TITLE
fix: cp-7.55.0: earn lending deposit confirmation button disabled state

### LINKED ISSUE #19352: [Bug]: Confirm button allows to be clicked several times when submitting Lending Deposit, duplicate tx is created with extremely high tx fee
### Describe the bug

 Confirm button allows to be clicked several times when submitting Lending Deposit, duplicate tx is created with extremely high tx fee.
 Present in 7.54.1 (2362) and 7.55.0 (2363).
 Not present in 7.53.1 (prod).

### Expected behavior

Confirm button is disabled after click.

### Screenshots/Recordings

https://github.com/user-attachments/assets/9276d1c2-65e1-4ba4-ad78-dbb30aafe9a9

Image

### Steps to reproduce

1. Submit Lending Deposit
2. Click Confirm again (when it becomes available after clicking 1st time)

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.55.0

### Build type

None

### Device

Samsung S24 +

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by ameliejyc**
## **Description**

It looks like a [recent bug fix](https://github.com/MetaMask/metamask-mobile/pull/18887) introduced another where the Lending Deposit Confirm button is re-enabled after press, allowing time for a user to press it again before the transaction view loads.

## **Changelog**

CHANGELOG entry: Fixes issue where Confirm button can be clicked several times when submitting Lending Deposit

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/19352

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **Before**

See here: https://github.com/MetaMask/metamask-mobile/pull/18887

### **After**

https://github.com/user-attachments/assets/e43acc15-8e50-4305-b09b-1785e2351f56

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Earn/Views/EarnLendingDepositConfirmationView/index.tsx [hunk 1]
```diff
@@ -758,15 +755,14 @@ const EarnLendingDepositConfirmationView = () => {
       const txType = txResult?.transactionMeta?.type;
 
       if (!transactionId || !txType) {
-        setIsConfirmButtonDisabled(false);
+        unsetDepositLoadingState();
```
Comment (Matt561) [inline app/components/UI/Earn/Views/EarnLendingDepositConfirmationView/index.tsx]: `unsetDepositLoadingState` sets the `setIsDepositLoading` to false but what if the error happens in the `ALLOWANCE_RESET` or `ALLOWANCE_INCREASE` steps? Do the unset methods in the transaction event listeners suffice?

Comment (ameliejyc) [reply app/components/UI/Earn/Views/EarnLendingDepositConfirmationView/index.tsx]: They should do, and I've refactored them a tiny bit to make them a) consistently use try/catch and b) use the helper `unset` functions for each type of transaction. So now those steps plus `DEPOSIT` definitely handle their own edge cases with correct loading state and Confirm button state. 

Meanwhile I've now adjusted the `handleConfirm` function so that it is agnostic of the loading states given the transaction methods handle them individually. Now the early return and catch only set the Confirm button state. And we should note the `handleConfirm` function early return and catch is unlikely to be invoked, it's quite defensive.

File: app/components/UI/Earn/Views/EarnLendingDepositConfirmationView/index.tsx [hunk 2]
```diff
@@ -682,16 +692,15 @@ const EarnLendingDepositConfirmationView = () => {
...
 
       if (!depositTransaction) {
+        unsetDepositLoadingState();
         return;
       }
 
       return depositTransaction;
-    } catch (error: Error | unknown) {
+    } catch (error) {
+      unsetDepositLoadingState();
```
[the remark this answers is not in the document]
Comment (ameliejyc) [reply app/components/UI/Earn/Views/EarnLendingDepositConfirmationView/index.tsx:701]: This is actually the bug I'm fixing - if the deposit loading states are cleared after the transaction submission then the user can click the confirm button again.

**Review by Matt561 — APPROVED** [review]
