### PR TITLE
fix: totals in MUSD conversion using max button

### LINKED ISSUE #25972: [Bug]: Total doesn't add up for MAX USD conversion
### Describe the bug

- Amount entered is less than full balance. I have ~0.12 USDC in the example but the amount changes from $0.11 to ~0.04 USDC after fetching Relay quote.
- Feel totals don't add up correctly. input amount of $0.04 USDC + $0.06 network fee != $0.17 total. This total does add up if we're converting the $0.11 balance that was briefly displayed before fetching the quote (0.11 + 0.6 = 0.17)

[Slack thread](https://consensys.slack.com/archives/C0A134JNHRV/p1770659743156009)

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Start a conversion to MUSD
2. Click Max

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

7.65.0

### Build number

3690

### Build type

None

### Device

-

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## **Description**

Ensure totals are correct for MUSD conversions using `Max` button.

- Bump `@metamask/transaction-pay-controller` and handle breaking changes.
- Add MUSD, USDC, and USDT on Mainnet and Linea to stablecoin support in `useTokenFiatRates`.

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: #25972 

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Upgrades `@metamask/transaction-pay-controller` with API changes and alters how Max-state is persisted, which could impact confirmation totals and transaction config behavior across networks.
> 
> **Overview**
> Fixes USD totals for *stablecoin* payments by treating a broader set of stablecoins as having a fixed `1` USD rate in `useTokenFiatRates` (adds MUSD/USDC/USDT on Mainnet & Linea, plus Polygon USDC.e; replaces per-feature constants with a chain/address allowlist).
> 
> Updates `useTransactionCustomAmount` to reflect breaking changes from bumping `@metamask/transaction-pay-controller` to `^14.0.0`, switching from `setIsMaxAmount` to `setTransactionConfig` for toggling `isMaxAmount`, and adjusts related unit tests/messenger action delegation accordingly.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 9d2309c9cfc937bbf118586d367ce6a328538857. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/confirmations/hooks/transactions/useTransactionCustomAmount.ts [hunk 1]
```diff
@@ -92,7 +92,9 @@ export function useTransactionCustomAmount({
     (value: boolean) => {
       const { TransactionPayController } = Engine.context;
 
-      TransactionPayController.setIsMaxAmount(transactionId, value);
+      TransactionPayController.setTransactionConfig(transactionId, (config) => {
+        config.isMaxAmount = value;
+      });
```
Comment (Matt561) [inline app/components/Views/confirmations/hooks/transactions/useTransactionCustomAmount.ts:97]: Non-blocking question: @matthewwalsh0 Is this the recommended way of setting max amount going forward? Asking because we call `TransactionPayController.setIsMaxAmount(transactionId, value);` in our separate quick convert feature. Quick convert isn't part of this release. Just asking so it gets updated if it needs it.

Comment (matthewwalsh0) [reply app/components/Views/confirmations/hooks/transactions/useTransactionCustomAmount.ts:97]: Exactly, we've added additional flags so simpler and more flexible to have a single action for all config.

Comment (Matt561) [reply app/components/Views/confirmations/hooks/transactions/useTransactionCustomAmount.ts:97]: Sounds good!

**Review by nickewansmith — DISMISSED** [review]

**Review by OGPoyraz — DISMISSED** [review]

**Review by sleepytanya — DISMISSED** [review]

**Review by vinistevam — DISMISSED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
