### PR TITLE
fix: Transaction Details view shows inaccurate balance on Mobile

### LINKED ISSUE #7787: [Bug]: Transaction Details view shows inaccurate balance
### Describe the bug

A user has a discrepancy in the USDT token balance on his transaction details page and the main view in the MM app. 

After a swap, the user received a value according to Etherscan, but MM transaction details view shows a different value.

device info: Android
app version: 7.8.0

A similar issue was reported for PEPE. In this case it was confirmed that the main view was showing the correct balance.

### Expected behavior

Main view and token details view show the same and accurate balance for tokens

### Screenshots/Recordings

_No response_

### Steps to reproduce

TBD

### Error messages or log output

_No response_

### Version

7.8.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

NA

### Operating system

Android

### Additional context

[Slack thread](https://consensys.slack.com/archives/C8RSKCNCD/p1698417235602149)

### Severity

Medium severity; unclear how many users are affected (if this is token specific)
Accurate value still displayed on main view

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**
users have discrepancy in the USDT token balance on his tx insight page in the MM app, they are seeing 33.22 USDT but it should be 5.43 USDT ( see the pictures below ) 

**the problem is due to the fact that we use a hexadecimal value to create a big number object, whereas the function balanceToFiat expects a decimal value. to calculate the conversion fiat**

## **Related issues**

Fixes: #7787 

## **Manual testing steps**

1. Go to the main page of the app and click on your USDT token.
2. scroll down and click on "Received USDT"
3. check the amount section

### **Before**

https://drive.google.com/file/d/1766q37UBdndVqk0cNG8eVCBf-mCsCm2j/view?usp=sharing

### **After**

https://drive.google.com/file/d/1l_sC7CK67WbjQmtLpbFUqiqj4iie2Fqv/view?usp=sharing

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/TransactionElement/utils.js [hunk 1]
```diff
@@ -281,7 +281,8 @@ function decodeIncomingTransfer(args) {
     selectedAddress,
   } = args;
 
-  const amount = toBN(value);
+  const decimalAmount = parseInt(value, 16).toString();
+  const amount = toBN(decimalAmount);
```
Comment (salimtb) [inline app/components/UI/TransactionElement/utils.js:285]: the problem is due to the fact that we use a hexadecimal value to create a big number object, whereas it expects a decimal value.

**Comment by tommasini** [comment]
Is there an issue already created on github that we can link  for this bug?

**Comment by salimtb** [comment]
> Is there an issue already created on github that we can link for this bug?

hey @tommasini ,
you can find here the [github](https://github.com/MetaMask/metamask-mobile/issues/7787) issue link

**Comment by tommasini** [comment]
Thanks @salimtb , could we have some recordings with this working on some other networks? Like polygon, avalanche and bsc?

**Comment by salimtb** [comment]
> Thanks @salimtb and thanks for looking into this! Could we have some recordings with this working on some other networks? Like polygon, avalanche and bsc?

i just added another screenshot on polygon on Polygon network

**Review by tommasini — DISMISSED** [review]
LGTM!
Wondering if it would be cool to switch the conversion by this parseInt(value, 16).toString() by this [function](https://github.com/MetaMask/core/blob/235777c3feaf33a10ca8c01762e1c4d24adc478e/packages/controller-utils/src/util.ts#L456) it should work the same way! But with more safety I would say

File: app/components/UI/TransactionElement/utils.js [hunk 2]
```diff
@@ -281,7 +281,8 @@ function decodeIncomingTransfer(args) {
     selectedAddress,
   } = args;
 
-  const amount = toBN(value);
+  const decimalAmount = parseInt(value, 16).toString();
```
Comment (tommasini) [inline app/components/UI/TransactionElement/utils.js:284]: Do you think it would be cool to use this -https://github.com/MetaMask/core/blob/235777c3feaf33a10ca8c01762e1c4d24adc478e/packages/controller-utils/src/util.ts#L456

Comment (salimtb) [reply app/components/UI/TransactionElement/utils.js]: nice catch , i just updated this line :)

File: app/components/UI/TransactionElement/utils.js (hunk 1 above)
Comment (digiwand) [reply app/components/UI/TransactionElement/utils.js:286]: I thought BN accepts hexadecimals as a string with a caveat 
> String values in hexadecimal literal form, e.g. '0xff' or '0xFF' (but not '0xfF'), are valid

ref: https://mikemcl.github.io/bignumber.js/

Comment (salimtb) [reply app/components/UI/TransactionElement/utils.js:286]: hey @digiwand ,
sorry for the lack of precision, we use the bigNumber from the `ethereumjs-util` package.

Comment (digiwand) [reply app/components/UI/TransactionElement/utils.js:286]: oh thanks for the explanation! I was confused since we utilize both packages in our repo. I see it imported now in the [controller-util](https://github.com/MetaMask/core/blob/235777c3feaf33a10ca8c01762e1c4d24adc478e/packages/controller-utils/src/util.ts#L456)

Comment (digiwand) [reply app/components/UI/TransactionElement/utils.js:286]: I'm unable to locate where this version doesn't support hex strings during construction

Comment (salimtb) [reply app/components/UI/TransactionElement/utils.js:286]: the `BN` object is always returning an hex value if you give an hex value as input, even if you specify the base ( 10 for example ) ,  i made this conclusion from some tests that i made.
let me try to find it in the doc.

Comment (salimtb) [reply app/components/UI/TransactionElement/utils.js:286]: in the step after , to get the conversion to $ we're using `balanceToFiat` function , this one should take a `decimal` , but we was sending a hex because the `amount` that we got from `BN` was in `hex`

**Review by tommasini — APPROVED** [review]
lGTM
