### PR TITLE
fix: Tweak send max calculation to use max possible actual gas fees

### LINKED ISSUE #17865: [Bug]: Send max on Base and Sepolia leads to an infinite spinner
### Describe the bug

Send max on Sepolia leads to you to an infinite spinner after you approve the confirmation. Disabling smart transactions doesn't affect this issue. 

Update: the same is also happening on Base

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/39fa6023-e893-4d3a-9eff-6c631069cec3

### Steps to reproduce

1. Start a send max on Sepolia
2. Notice the infinite spinner

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.53.0

### Build type

None

### Device

iphone 11

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

The way we calculated the value to send all native asset funds of the wallet, subtracted the estimated gas fees to the balance. However, this may not always be sufficient given the gas fee market fluctuations. The estimated fee is not guaranteed to be enough for the transaction to be confirmed.

Where the estimated fee is calculated from the minimumFeePerGas * the gas limit (and the minimumFeePerGas is the minimum value between the maxFeePerGas and the sum of the estimatedBaseFee and maxPriorityFeePerGas), the max fee is calculated from the maxFeePerGas * the gas limit directly. This means that the maxFee is greater or equal than the estimated fee.

This PR implements the calculation of the max fee so we can use it to calculate the total to transfer, lowering the likelihood of failing transactions.

Something must have changed on the gas API last week, because this is a recent regression only now reported, and the client code hasn't changed. In fact, I tested that this regression is now happening on old client code, at least as old as [#15074](https://github.com/MetaMask/metamask-mobile/pull/15074).

[#17865](https://github.com/MetaMask/metamask-mobile/issues/17865) should not happen anymore with this fix, but a try catch was wrapped around `Engine.acceptPendingApproval` in any case, to prevent instances of a transaction failure error bubbling up to the navigation code again.

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: [#17865](https://github.com/MetaMask/metamask-mobile/issues/17865) and [#17836](https://github.com/MetaMask/metamask-mobile/issues/17836)

## **Manual testing steps**

```gherkin
Feature: my feature name
  Scenario: user [verb for user action]
    Given [describe expected initial app state] 
    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/confirmations/hooks/useApprovalRequest.ts [hunk 1]
```diff
@@ -29,12 +30,15 @@ const useApprovalRequest = () => {
...
-        opts,
-      );
+      try {
+        await Engine.acceptPendingApproval(
+          approvalRequest.id,
+          { ...approvalRequest.requestData, ...(value || {}) },
+          opts,
+        );
+      } catch (error: Error | unknown) {
+        captureException(error as Error);
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/hooks/useApprovalRequest.ts]: Should this instead be the responsibility of the caller, such as `Footer` as it then has the opportunity to present or render errors in a standard way?

File: app/components/Views/confirmations/hooks/gas/useFeeCalculations.ts [hunk 2]
```diff
@@ -98,10 +99,29 @@ export const useFeeCalculations = (transactionMeta: TransactionMeta) => {
     ],
   );
 
+  // Max fee
+  const maxFee = useMemo(() => multiplyHexes(
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/hooks/gas/useFeeCalculations.ts]: Minor, this logic is great, but there is a lot in this single hook.

Not needed now but I added a `useTransactionMaxGasCost` and I wondered if we'd benefit from additional more granular hooks in future such as `useEstimatedGasCost`.

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: app/components/Views/confirmations/hooks/gas/useFeeCalculations.ts [hunk 3]
```diff
@@ -98,10 +99,33 @@ export const useFeeCalculations = (transactionMeta: TransactionMeta) => {
...
   );
 
+  // Max fee
+  const maxFee = useMemo(
+    () =>
+      multiplyHexes(
+        supportsEIP1559
+          ? (decimalToHex(maxFeePerGas) as Hex)
+          : (txParamsGasPrice as Hex),
+        gasLimitNoBuffer as Hex,
```
Comment (OGPoyraz) [inline app/components/Views/confirmations/hooks/gas/useFeeCalculations.ts]: I think we should use `txParams.gas` instead of `gasLimitNoBuffer` here. 

The reason that we use `gasLimitNoBuffer` in the calculations is showing the minimal values in UI. But in reality `txParams.gas` value could be spend. This will cause more dust to be left over but it will be more reliable then.

File: app/components/Views/confirmations/hooks/gas/useFeeCalculations.ts [hunk 4]
```diff
@@ -98,10 +127,38 @@ export const useFeeCalculations = (transactionMeta: TransactionMeta) => {
     ],
   );
 
+  // Max fee
+  const maxFee = useMemo(
+    () =>
+      multiplyHexes(
+        supportsEIP1559
+          ? (decimalToHex(maxFeePerGas) as Hex)
```
Comment (OGPoyraz) [inline app/components/Views/confirmations/hooks/gas/useFeeCalculations.ts:135]: Minor - we can use directly `transactionMeta.txParams.maxFeePerGas` instead of converting decimal `maxFeePerGas`

**Review by OGPoyraz — DISMISSED** [review]

**Review by matthewwalsh0 — DISMISSED** [review]

**Review by OGPoyraz — APPROVED** [review]
