### PR TITLE
fix: fix sentry noice related to undefined currentCurrency property when the app start

### LINKED ISSUE #14504: Error: Migration: Invalid CurrencyController state type 'undefined'
Sentry Issue: [METAMASK-MOBILE-3K07](https://metamask.sentry.io/issues/6469359219/?referrer=github_integration)

```
Error: Migration: Invalid CurrencyController state type 'undefined'
  at ResultError (ses.cjs:7676:17)
  at e.default (app/store/migrations/069.ts:31:11)
  at _ref3 (app/store/migrations/index.ts:173:37)
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by salimtb**
## **Related issues**

Fixes: #14504 

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/store/migrations/069.ts [hunk 1]
```diff
@@ -23,16 +23,15 @@ export default function migrate(state: unknown) {
   const currencyController =
     state.engine.backgroundState.CurrencyRateController;
 
-  if (
-    !isObject(currencyController) ||
-    !hasProperty(currencyController, 'currentCurrency')
```
Comment (salimtb) [inline app/store/migrations/069.ts:28]: At app startup, the `currentCurrency` property is sometimes not yet defined, which has been triggering a Sentry error. To reduce noise, we’ve added a silent return in that case. In parallel, we’ll investigate why this property is occasionally missing during initialization.

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by Cal-L — APPROVED** [review]
LGTM
