### PR TITLE
MediaPlayer component

### LINKED ISSUE #2596: Collectible support for audio and video
Research and implement the best option to reproduce audio and video, to put it on the collectible view

image

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

New `MediaPlayer` component to reproduce mp4 files.

The package on this PR is tracking an address with collectibles with mp4 as assets

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #2596

### CODE REVIEW

File: app/components/UI/CollectibleMedia/index.js [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+		height: 260,
+		width: 260
+	}
+});
+
+/**
+ * View that renders an ERC-721 Token image
+ */
+export default function CollectibleMedia({ collectible, small, big }) {
+	const [sourceUri, serSourceUri] = useState(null);
```
Comment (andrepimenta) [inline app/components/UI/CollectibleMedia/index.js:26]: This may be typo? `serSourceUri` instead of `setSourceUri`

File: app/components/UI/CollectibleMedia/index.js [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+				fadeIn
+				resizeMode={'contain'}
+				source={{ uri: sourceUri }}
+				style={[small && styles.smallImage, big && styles.bigImage]}
+				onError={fallback}
+			/>
+		);
+	} else {
+		child = <Identicon address={collectible.address + collectible.tokenId} />;
+	}
```
Comment (andrepimenta) [inline app/components/UI/CollectibleMedia/index.js:56]: This could be inside a function like renderChild() could make it cleaner wdyt?

File: app/components/UI/CollectibleMedia/index.js [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+	return <View style={[styles.container, { backgroundColor: `#${collectible.backgroundColor}` }]}>{child}</View>;
```
Comment (andrepimenta) [inline app/components/UI/CollectibleMedia/index.js:57]: I think we try not to have inline styles but maybe in this case it's fine? You can also make the style a function and pass `collectible.backgroundColor`

File: app/components/UI/CollectibleMedia/index.js [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+}
+
+CollectibleMedia.propTypes = {
+	/**
+	 * Collectible object (in this case ERC721 token)
+	 */
+	collectible: PropTypes.object,
+	small: PropTypes.bool,
+	big: PropTypes.bool
```
Comment (andrepimenta) [inline app/components/UI/CollectibleMedia/index.js:66]: Missing descriptions for small and big props if you want to add them

File: app/components/UI/CollectibleMedia/index.js [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+		child = (
+			<RemoteImage
+				fadeIn
+				resizeMode={'contain'}
+				source={{ uri: sourceUri }}
+				style={[small && styles.smallImage, big && styles.bigImage]}
+				onError={fallback}
+			/>
+		);
+	} else {
```
Comment (andrepimenta) [inline app/components/UI/CollectibleMedia/index.js:54]: What are the types we are going to support? Can the sourceUri exist but it's not an image for example?

File: app/components/Views/MediaPlayer/index.js [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+				<AndroidMediaPlayer source={{ uri }} />
+			) : (
+				<Video style={style} source={{ uri }} controls />
+			)}
+		</View>
+	);
+}
+
+MediaPlayer.propTypes = {
+	uri: PropTypes.string,
```
Comment (andrepimenta) [inline app/components/Views/MediaPlayer/index.js:21]: Missing propTypes descriptions here if you want to add them

File: app/components/Views/MediaPlayer/index.js [hunk 7]
```diff
@@ -0,0 +1,30 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+import { View } from 'react-native';
+import AndroidMediaPlayer from './AndroidMediaPlayer';
+import Video from 'react-native-video';
+import Device from '../../../util/Device';
+
+function MediaPlayer({ uri, style }) {
+	return (
+		<View style={[style]}>
```
Comment (andrepimenta) [inline app/components/Views/MediaPlayer/index.js:10]: Should this be an array or maybe just `style={style}`?

**Review by andrepimenta — CHANGES_REQUESTED** [review]

**Review by andrepimenta — APPROVED** [review]
LGTM! 👍
