### PR TITLE
fix: update selectedGasFeeToken when payment token is selected for gasless flow cp-7.62.1

### LINKED ISSUE #25185: [Bug]: Predict and Perps deposits incorrectly failing with "Gas fee token not found and insufficient native balance"
### Describe the bug

On v7.62 prod, Predict and Perps deposits incorrectly failing with "Gas fee token not found and insufficient native balance". 

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

You can replicate this if you had just enough gas for the quote but not for the original Predict batch transaction and no existing Polygon USDCe balance.

### Error messages or log output

```shell

```

### Where was this bug found?

Live version (from official store)

### Version

7.62.0

### Build number

3527

### Build type

None

### Device

iphone 15

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by pedronfigueiredo**
## **Description**

Fixes a regression from bcf7c34 ([see PR](https://github.com/MetaMask/metamask-mobile/pull/24290)) where passing `gasFeeToken` at transaction creation time caused premature balance validation, failing deposits with "Gas fee token not found and insufficient native balance".

Instead of setting `gasFeeToken` at transaction creation, we now update `selectedGasFeeToken` on the transaction metadata when the user selects a payment token in the MetaMask Pay UI. This allows the 7702 gasless flow to process the transaction correctly without triggering early validation.

Changes:
- Remove `gasFeeToken` from Perps/Predict transaction creation
- Update `useTransactionPayToken` to set `selectedGasFeeToken` on the transaction metadata when a payment token is selected
- Update tests to reflect the new approach

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/25185

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I've included tests if applicable
- [ ] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Fixes gasless deposit flow by deferring gas fee token selection to the confirmation UI instead of at transaction creation.
> 
> - Removes `gasFeeToken` from Perps and Predict deposit submission paths (`PerpsController`, `PredictController`, Polymarket provider), and types/tests updated accordingly
> - Updates `useTransactionPayToken` to set `selectedGasFeeToken` (and `isGasFeeTokenIgnoredIfBalance`) for `predictDeposit` when the chosen pay token matches the required token; resets when it doesn’t; triggers gas estimate refresh
> - Adds unit tests validating `selectedGasFeeToken` update/reset logic and adjusts existing deposit tests to new behavior
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit f0ad3ed448d7d29064cfecc707ca0b9b457928c7. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/Predict/controllers/PredictController.ts [hunk 1]
```diff
@@ -2233,8 +2229,6 @@ export class PredictController extends BaseController<
         disableHook: true,
         disableSequential: true,
         requireApproval: true,
-        // Temporarily breaking abstraction, can instead be abstracted via provider.
-        gasFeeToken: MATIC_CONTRACTS.collateral as Hex,
```
Comment (matthewwalsh0) [inline app/components/UI/Predict/controllers/PredictController.ts:2237]: We need to keep these two in this file as these are for Predict claim and withdraw which already had functioning support and don't use quotes.

File: app/components/Views/confirmations/hooks/pay/useTransactionPayToken.ts [hunk 2]
```diff
@@ -43,13 +52,38 @@ export function useTransactionPayToken(): {
...
-        EngineService.flushState();
       } catch (e) {
         console.error('Error updating payment token', e);
       }
+
+      // perps deposits only use relay, so doesn't need gasFeeToken update
+      const isPredictDepositTransaction =
+        transactionMeta?.type === TransactionType.predictDeposit;
+      const isPayTokenRequiredToken =
+        payToken?.chainId === primaryRequiredToken?.chainId &&
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/hooks/pay/useTransactionPayToken.ts]: We haven't re-rendered at this point so should we be checking `newPayToken`?

File: app/components/Views/confirmations/hooks/pay/useTransactionPayToken.ts [hunk 3]
```diff
@@ -43,13 +52,38 @@ export function useTransactionPayToken(): {
...
+          primaryRequiredToken?.address.toLowerCase();
+
+      if (isPredictDepositTransaction && isPayTokenRequiredToken) {
+        const updatedTx = {
+          ...transactionMeta,
+          selectedGasFeeToken: newPayToken.address,
+          isGasFeeTokenIgnoredIfBalance: false,
+        };
+
+        updateTransaction(updatedTx, transactionMeta.id);
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/hooks/pay/useTransactionPayToken.ts:79]: Unrelated, but we need a ticket to expose a callback based version of this function to make state updates safer and easier.

File: app/components/Views/confirmations/hooks/pay/useTransactionPayToken.ts [hunk 4]
```diff
@@ -43,13 +52,38 @@ export function useTransactionPayToken(): {
...
+      }
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/hooks/pay/useTransactionPayToken.ts:80]: We need to reset these two values if it's changed back to a different token?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

**Review by michalconsensys — DISMISSED** [review]

File: app/components/Views/confirmations/hooks/pay/useTransactionPayToken.ts [hunk 5]
```diff
@@ -43,13 +52,41 @@ export function useTransactionPayToken(): {
...
+          newPayToken.address.toLowerCase() ===
+            primaryRequiredToken?.address.toLowerCase();
+
+        const updatedTx = {
+          ...transactionMeta,
+          selectedGasFeeToken: isNewPayTokenRequiredToken
+            ? newPayToken.address
+            : undefined,
+          isGasFeeTokenIgnoredIfBalance: isNewPayTokenRequiredToken
+            ? false
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/hooks/pay/useTransactionPayToken.ts]: This should be `true` so we only use gas station if the user has insufficient balance.

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: app/components/Views/confirmations/hooks/pay/useTransactionPayToken.ts (hunk 5 above)
Comment (pedronfigueiredo) [reply app/components/Views/confirmations/hooks/pay/useTransactionPayToken.ts]: Adressed in f0ad3ed448

**Review by matthewwalsh0 — APPROVED** [review]

**Review by michalconsensys — APPROVED** [review]

**Review by caieu — APPROVED** [review]
LGTM
