### PR TITLE
Bugfix/deeplink, request modals and wallet connect

### LINKED ISSUE #1798: Connect prompt not shown after unlock
Reproduction steps:
- on iOS
- Let metamask lock
- navigate to a site that uses walletConnect for logon, like mooniswap.exchange
- click connect wallet, walletconnect, metamask
- MetaMask opens, requires faceID

Expected:
- connect prompt is shown

Result:
- At first just wallet screen is shown, I had to switch apps to another and back to metamask before it showed the connect screen.

### LINKED ISSUE #1804: Links are lost when unlocking
**Describe the bug**
When metamask is the default browser on Android, and the metamask app is currently in a locked state, clicking a link in an external app for example an email app, results in the user being prompted to unlock metamask, but after unlocking, the original link that the user clicked is gone.

**To Reproduce**

1. Set MM to default browser 
2. Click a link in your email 
3. Be prompted to unlock 
4. See the link you followed is lost

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 10, Oxygen OS 10.5.13
 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

This PR includes

1. refactor of the `Entry` and  `Main` components to hooks. The problem with these component was the state handling, it was messy so we were having problems with all the modals on  `Main`.

2. WalletConnect version update and added a way to handle wallet connect requests when the app is locked.

3. Deeplinks are being erased if the app is closed, to not get the request when the app is opened again without context.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves https://github.com/MetaMask/metamask-mobile/issues/1798
Resolves https://github.com/MetaMask/metamask-mobile/issues/1804

### CODE REVIEW

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Android doesn't progress pass splash screen 
iOS I'm unable to get any deeplinks to work 

built with METAMASK_ENVIRONMENT='production' yarn build:ios:release and detox build -c android.emu.release && detox test -c android.emu.release

File: app/core/WalletConnect.js [hunk 1]
```diff
@@ -28,6 +29,15 @@ const waitForInitialization = async () => {
 	}
 };
 
+const waitForKeychainUnlocked = async () => {
+	let i = 0;
+	const { KeyringController } = Engine.context;
+	while (!KeyringController.isUnlocked()) {
```
Comment (rickycodes) [inline app/core/WalletConnect.js:35]: does the `KeyringController` not have an unlock event we can listen for? checking every second for a whole minute seems _not_ ideal :thinking:

i see on the extension `KeyringController` extends `EventEmitter` which seems like a better pattern.

File: app/components/Nav/Main/index.js [hunk 2]
```diff
@@ -122,526 +74,389 @@ const styles = StyleSheet.create({
...
+			} else {
+				const {
+					transaction: { value, gas, gasPrice, data }
+				} = transactionMeta;
+				const { AssetsContractController } = Engine.context;
+				transactionMeta.transaction.gas = hexToBN(gas);
+				transactionMeta.transaction.gasPrice = hexToBN(gasPrice);
+
+				if (
+					(value === '0x0' || !value) &&
```
Comment (rickycodes) [inline app/components/Nav/Main/index.js:218]: rather than doing all the magic directly in an if condition what if instead we outline what the constraints are separately? I think that will make things a bit easier to understand.

something like:

```js
const valueIsEmpty = value === '0x0' || !value;
const dataIsNotEmpty = data && data !== '0x';
...

if (valueIsEmpty && dataIsNotEmpty && ...)
```

File: app/components/Nav/Main/index.js [hunk 3]
```diff
@@ -122,526 +74,389 @@ const styles = StyleSheet.create({
...
+		async transactionMeta => {
+			if (transactionMeta.origin === TransactionTypes.MMM) return;
+
+			const to = safeToChecksumAddress(transactionMeta.transaction.to);
+			const networkId = Networks[props.providerType].networkId;
+
+			if (
+				props.paymentChannelsEnabled &&
+				AppConstants.CONNEXT.SUPPORTED_NETWORKS.includes(props.providerType) &&
+				transactionMeta.transaction.data &&
```
Comment (rickycodes) [inline app/components/Nav/Main/index.js:204]: does `transactionMeta` always have a `transaction` key? what happens if it doesn't? you could use optional chaining here to be safe

File: app/components/Nav/Main/index.js [hunk 4]
```diff
@@ -122,526 +74,389 @@ const styles = StyleSheet.create({
...
+			}
+		},
+		[backgroundMode, pollForIncomingTransactions]
+	);
 
-				this.removeConnectionStatusListener = NetInfo.addEventListener(this.connectionChangeHandler);
-			}, 1000);
-		});
+	const initForceReload = () => {
+		// Force unmount the webview to avoid caching problems
```
Comment (rickycodes) [inline app/components/Nav/Main/index.js:307]: Why do we have to do this?

**Review by rickycodes — CHANGES_REQUESTED** [review]
left a few comments/question. admittedly, I need to brush up on react hooks... most of where we used them previously i was able to understand, but there's a lot of changes here. I may need to take another look at this tomorrow with a fresh set of eyes.

File: app/components/Nav/Main/index.js (hunk 2 above)
Comment (estebanmino) [reply app/components/Nav/Main/index.js:218]: this is payment channel stuff which we're deprecating, I think we shouldn't spend time on this (in fact I was deleting it https://github.com/MetaMask/metamask-mobile/pull/1877/commits/acd5d434635f62397f0500efded0e22d4c8a02dc)

File: app/components/Nav/Main/index.js (hunk 3 above)
Comment (estebanmino) [reply app/components/Nav/Main/index.js:204]: payment channel stuff

File: app/components/Nav/Main/index.js (hunk 4 above)
Comment (estebanmino) [reply app/components/Nav/Main/index.js:307]: is to mount `MainNavigator` on language change

File: app/core/WalletConnect.js (hunk 1 above)
Comment (estebanmino) [reply app/core/WalletConnect.js:35]: we don't have that on `controllers` KeyringController

**Comment by ibrahimtaveras00** [comment]
After retesting, here are the following issues:

**Issue 1:**

Android still isn't moving past the splash screen

**Issue 2:** 

I'm unable to open deeplinks/Wallet Connect when the app is either in the background and locked, or completely in a killed state

also too, as a side not, I'm in a broken state when I attempt to do this, seen here = http://recordit.co/Flpx8M1fyG 
the app stays with a white loading screen on browser, and none of my account information is displayed

Screen Shot 2020-10-08 at 8 08 37 PM

Screen Shot 2020-10-08 at 8 08 51 PM

This currently works on iOS build 525 seen here = http://recordit.co/67bKuGHqLF

 **Issue 3:**

When you are going via Wallet connect (in this scenario I had uniswap.exchange open on Safari and came to MM via wallet connect), it shows the wrong title URL on the approve modal.  Furthermore, when I kill the app and relaunch, I'm no longer able to see the ERC-20 token I want to swap to; seen here = https://recordit.co/zPi5Z8hxOo

Screen Shot 2020-10-08 at 8 19 44 PM

You can also follow [this thread](https://consensys.slack.com/archives/GBW7S9FSN/p1601335976059900) for more information

**Review by andrepimenta — APPROVED** [review]
LGTM! 👍

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Real iOS device used on testflight build 1.0.5 (532) = iPhone X OS 13.7
Android apk = Pixel 2

**Issue 1:**  Fixed 

**Issue 2:**
The broken state part is fixed, however, I'm still unable to open any deep link on iOS when the app is in background/locked/or killed state.

On android it only works if the app is completely killed.

Killed state = https://recordit.co/y6Tld4TStU
Locked state = https://recordit.co/037QPM1Hq8
app in background and not locked =https://recordit.co/wKcCQSAHkM

**Issue 3:** 

I couldn't retest this as it still doesn't work on iOS (as above) nor on android; seen here = http://recordit.co/8uCB8rmVwI

New issues...

**Issue 4:** 

This happens when I sync with extension or when I search tokens on wallet > add tokens

Screen Shot 2020-10-16 at 4 25 35 PM

**Issue 5:** 

Now android is asking for my fingerprint twice when just launching the app normally

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
**Issue 2:** 
Still an issue according to the following:

on iOS:
- can't open deeplink in locked state
- can't open deeplink in killed state 

on android:
- can't open deeplink in locked state

**Issue 3**
Fixed, however, when I relaunch app, iOS doesn't show me the modal which is correct, but on Android, I still see the modal in a broken state

**Issue 4** = fixed

**Issue 5** = fixed on both OS's

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Issue 2 and Issue 3 still exist

**For issue 2**

Both OS's pass for background state 👍 

However the following scenarios are still failing.

- killed state on iOS 

URL example = https://recordit.co/1WSPanYeib
to reproduce this, kill app and open this deeplink = https://metamask.app.link/dapp/uniswap.eth

WC example = https://recordit.co/q2UtgNXrlt
to reproduce this kill app, and try to connect to wallet connect while in safari https://example.walletconnect.org/ 

Approve example = http://recordit.co/7kCSQqMkfB
I created this deeplink by going to https://brunobar79.github.io/eip681-link-generator/# with the following ethereum:0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@4/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=1

Payment request example = http://recordit.co/o29lXfczlb
To reproduce this kill app and click on this deeplink = https://metamask.app.link/send/0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6@4?value=1e15

- Locked state on both OS's are failing 

URL example seen here = https://recordit.co/7R0E753mkM
to reproduce this go to settings > security & privacy and change your Auto-lock to immediately and then go to chrome/safari web browser or click on this link https://metamask.app.link/dapp/uniswap.eth

Wallet connect example = seen here = http://recordit.co/yJvRicB2bu
to reproduce this go to settings > security & privacy and change your Auto-lock to immediately and then go to chrome/safari web browser and go to wallet connect and attempt to connect while MM is locked

Approve seen here = http://recordit.co/4nVly5RGq3
Attempt to open the deeplink while MM app is locked
I created this deeplink by going to https://brunobar79.github.io/eip681-link-generator/# with the following ethereum:0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@4/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=1

Payment request example seen here = http://recordit.co/1jeSYnwcFx
to reproduce this go to settings > security & privacy and change your Auto-lock to immediately and then go to chrome/safari web browser to create a deeplink or just click on this link = https://metamask.app.link/send/0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6@4?value=1e15

**For Issue 3**
This works on iOS now, however, still fails on Android; seen here = http://recordit.co/ynZBE9znLK

I created this deeplink by going to https://brunobar79.github.io/eip681-link-generator/# with the following ethereum:0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@4/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=1
Now open this deeplink in MM browser, and once the approve modal is displayed kill the app and relaunch

**Issue 6:**

Not sure if this was newly introduced here, or exists on develop or not but when I QA'd https://github.com/MetaMask/metamask-mobile/pull/1847 when I had the MM wallet open and tapped on the QR code scanner and scanned the following QR code the approve modal would pop up, however, now it doesn't and just takes me to Send flow

image

seen here = http://recordit.co/SLsQrYvaK5

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
All issues have been resolved on Android 

With iOS, the only outstanding issue is that in a killed, or locked state deeplinks will not work on a device that has biometrics enabled (FaceID or TouchID)

similar to https://github.com/MetaMask/metamask-mobile/issues/1798

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Only 1 scenario fails on both OS's:

When you have the app in a locked state and you're not on the wallet view
 
ios = http://recordit.co/8sEuCj1qyp
Android = https://recordit.co/LnIdgLJavd

This nonetheless works if you have a device without biometrics and use your password to log in

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Wallet connect is now fixed on both OS's 👍 

However, there are now 2 places of failure on both OS's

1) Payment request isn’t working when app is in a locked state (set to immediately)

Seen here = http://recordit.co/uyQfcwuGXF

As you can see it opens to the correct view then immediately closes the view

2) Scanning a public address is not working as it should
Ever since https://github.com/MetaMask/metamask-mobile/pull/1859 when a user scans a public address QR code, they should be sent to the send to view

Seen here = http://recordit.co/JmRNIYrhl8

**Review by ibrahimtaveras00 — APPROVED** [review]
fixes look good on both OS's, QA Passed 👍
