### PR TITLE
fix: cp-7.43.0 QR hardware signature requests not showing result after signing

### LINKED ISSUE #14052: [Bug]:  For the QR-based hardware wallets the QR code necessary for the Signature transaction is not being displayed (Keystone)
### Describe the bug

There appears to be an issue with signatures on mobile devices when using QR-based hardware wallets, as the QR code necessary for the transaction is not being displayed. It appears that all types of signatures are experiencing issues, both platforms affected.
_Keystone wallet_

### Expected behavior

Reliable signatures functionality with QR-based hardware wallets

### Screenshots/Recordings

Android:

https://github.com/user-attachments/assets/b7ab2f5e-ab0d-4905-9202-a16b36aa370c

iOS:

https://github.com/user-attachments/assets/dc8b002b-c7ab-4926-bed5-0c60212cba96

### Steps to reproduce

1. Connect QR based hardwallet
2. Trigger any type of Signature

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.43.0 (1624)

### Build type

None

### Device

Samsung S24 Ultra, iPhone 15

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Fix - QR hardware signature requests not showing result after signing

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/14052

## **Manual testing steps**

1. Switch to QR hardware account
2. Go to testdapp and submit a signature
3. It should work ac expected

## **Screenshots/Recordings**
TODO

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by jpuri** [comment]
The change has been texted by @sleepytanya https://github.com/MetaMask/metamask-mobile/issues/14052#issuecomment-2736733655

File: app/components/Views/confirmations/hooks/useConfirmActions.ts [hunk 1]
```diff
@@ -59,7 +59,7 @@ export const useConfirmActions = () => {
       return;
     }
     await onRequestConfirm({
-      waitForResult: false,
+      waitForResult: true,
```
Comment (OGPoyraz) [inline app/components/Views/confirmations/hooks/useConfirmActions.ts:62]: Can we set this to `true` only for signatures? Obviously this will not work for transactions.

https://github.com/user-attachments/assets/669e360e-f7a5-4e23-944f-54c916ff976b

**Review by OGPoyraz — CHANGES_REQUESTED** [review]

File: app/components/Views/confirmations/hooks/useConfirmActions.ts (hunk 1 above)
Comment (jpuri) [reply app/components/Views/confirmations/hooks/useConfirmActions.ts:62]: I would prefer to use `true` for all confirmations and also this is how it worked in old designs.

Is there any reason to use `false` for non-hardware signatures.

Comment (OGPoyraz) [reply app/components/Views/confirmations/hooks/useConfirmActions.ts:62]: Apologies @jpuri my comment above is a bit misleading.
I think the issue above is happening because of enabled smart transactions. I will confirm this and let you know.

Comment (OGPoyraz) [reply app/components/Views/confirmations/hooks/useConfirmActions.ts:62]: Ok seems like it's happening because of enabled smart transactions. 

Can we set it to `false` if approval is `transaction` and it should use smart transactions?
Similar logic added here: https://github.com/MetaMask/metamask-mobile/blob/main/app/components/Views/confirmations/SendFlow/Confirm/index.js#L1045

Comment (jpuri) [reply app/components/Views/confirmations/hooks/useConfirmActions.ts:62]: Sounds good let me make this change

Comment (OGPoyraz) [reply app/components/Views/confirmations/hooks/useConfirmActions.ts:62]: Thanks for fixing this @jpuri and sorry for inconvenience, we will early informed once e2e tests are enabled on staking transaction.

**Review by OGPoyraz — APPROVED** [review]
