### PR TITLE
fix: Cannot read property 'requiredScopes' of undefined cp-7.56.0

### LINKED ISSUE #19553: TypeError: Cannot read property 'requiredScopes' of undefined
Sentry Issue: [METAMASK-MOBILE-40FC](https://metamask.sentry.io/issues/6783821428/?referrer=github_integration)

```
TypeError: Cannot read property 'requiredScopes' of undefined
  at None (app:///index.android.bundle)
  at None (app:///index.android.bundle)
  at None (app:///index.android.bundle)
  at None (app:///index.android.bundle)
  at None (app:///index.android.bundle)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by wenfix**
## **Description**
This PR fixes a bug that was causing a `Caip25CaveatValue` to be unexpectedly undefined after revoking permissions.
It occured when:
1. Dapp calls `wallet_revokePermissions` .
2. `PermissionController` removes the CAIP-25 permission; if no permissions remain, it prunes the `subject` entry.
3. `PermissionController` fires a `stateChange` event.
4. Our subscriptions to that event use the `getAuthorizedScopes(this.origin)` selector; after pruning, it returns `undefined` for the `origin`.
5. Our event handler `handleCaipSessionScopeChanges(currentValue, previousValue`) gets `currentValue = undefined`.
6. `getChangedAuthorization(currentValue, previousValue)` returns `undefined` as-is.
7. We pass that `undefined` to `getSessionScopes(...)`, which immediately reads `authorization.requiredScopes`, resulting in the current error.

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/19553

## **Manual testing steps**
1. Add this log on method `handleCaipSessionScopeChanges` of `BackgroundBridge.js`

```diff
 handleCaipSessionScopeChanges = async (currentValue, previousValue) => {
    const origin = this.channelIdOrOrigin;
    const changedAuthorization = getChangedAuthorization(
      currentValue,
      previousValue,
    );

+   console.log({ changedAuthorization });

    const removedAuthorization = getRemovedAuthorization(
      currentValue,
      previousValue,
    );

```
2. Connect to a dapp
3. Revoke dapp permissions
4. `changedAuthorization` should be an empty `Caip25CaveatValue`
5. Before this change, `changedAuthorization` would be undefined (which causes getSessionScopes to throw) 

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/selectors/permissions/index.js [hunk 1]
```diff
@@ -34,7 +34,10 @@ export const getAuthorizedScopes = (origin) =>
     const subject = subjects[origin];
 
     if (!subject) {
-      return undefined;
```
Comment (adonesky1) [inline app/selectors/permissions/index.js:37]: the jsdoc above still reads:
```
 * Get the authorized CAIP-25 scopes for the subject.
 * The returned value is an immutable value from the PermissionController state,
 * or undefined if no authorization exists.
```

So lets change that too

**Review by adonesky1 — DISMISSED** [review]
LGTM other than one small req for doc changes. Great digging + find!

**Comment by wenfix** [comment]
> LGTM other than one small req for doc changes. Great digging + find!

here: 7a3f332d1a9f2d8eb3affa53c7e5f3a5fd8a653b

also added a `sessionProperties` property to fully match the `Caip25CaveatValue` type.

@adonesky1

File: app/selectors/permissions/index.js (hunk 1 above)
Comment (wenfix) [reply app/selectors/permissions/index.js:37]: d7b4fe943d78f6a04dac2c3095b9fc8f929d2c92

Comment (wenfix) [reply app/selectors/permissions/index.js:37]: Actually Cursor pointed out that the return of the function can still be undefined at the end. I've added extra defenses by also returning an empty `Caip25CaveatValue` in that case.

9883f62d80115b81dcb9f0326130832978391449

**Review by adonesky1 — APPROVED** [review]
LGTM!
