### PR TITLE
fix: activity reloads every minute

### LINKED ISSUE #14446: [Bug]: Activity list reloads every minute
### Describe the bug

When interacting with the activity list I noticed if you wait a minute on the same page it reloads (shows a spinner). 

### Expected behavior

We should not show the spinner on every update but rather, update the list if there is an update.

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Create a Solana Account
2. Go to the activity page
3. Wait for a minute
4. You should see the page reloading

### Error messages or log output

```shell

```

### Detection stage

In beta

### Version

7.43.0

### Build type

Flask

### Device

Iphone 16 Pro

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by aganglada**
## **Description**

Activity was reloading every minute, closing the details modal as the loading appeared in the screen.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/14446

## **Manual testing steps**

1. Go to activity
2. Wait until a minute change on the top of the device
3. Activity should not reload
4.

### **Before**

https://github.com/user-attachments/assets/272cb2fa-3b84-4b37-947f-bea52764cbf5

### **After**

https://github.com/user-attachments/assets/c3e604da-9d36-4a88-9051-ffb727453215

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by zone-live — DISMISSED** [review]

**Review by javiergarciavera — DISMISSED** [review]

File: app/components/Views/MultichainTransactionsView/MultichainTransactionsView.tsx [hunk 1]
```diff
@@ -30,31 +30,30 @@ const MultichainTransactionsView = () => {
...
-    setLoading(true);
+  const transactions = useMemo(() => {
+    if (
+      solanaAccountTransactions &&
+      'transactions' in solanaAccountTransactions
+    ) {
+      return solanaAccountTransactions.transactions;
+    }
+    return [];
+  }, [solanaAccountTransactions]);
```
Comment (Daniel-Cross) [inline app/components/Views/MultichainTransactionsView/MultichainTransactionsView.tsx:45]: Question around this `useMemo`. Is it not simpler to do the following?

```suggestion
const transactions = useMemo(() => 
  solanaAccountTransactions?.transactions || [], 
  [solanaAccountTransactions]
);
```

File: app/components/Views/MultichainTransactionsView/MultichainTransactionsView.tsx [hunk 2]
```diff
@@ -30,31 +30,30 @@ const MultichainTransactionsView = () => {
...
-        setTransactions(solanaAccountTransactions.transactions);
-      } else {
-        setTransactions([]);
-      }
       setLoading(false);
     }, 500);
 
     return () => clearTimeout(timer);
-  }, [solanaAccountTransactions]);
+  }, [loading, solanaAccountTransactions]);
```
Comment (Daniel-Cross) [inline app/components/Views/MultichainTransactionsView/MultichainTransactionsView.tsx:56]: I know this isn't your code for the most part but is a `setTimeout` really a good practice? Is there a reason we're waiting half a second to change state? Also, the use of `loading` in the dependancy array means this will re-render unnecessarily multiple times.  Do we really need the `loading` state?

**Review by javiergarciavera — DISMISSED** [review]

**Review by zone-live — DISMISSED** [review]

**Review by Daniel-Cross — DISMISSED** [review]
Looks good!

**Review by javiergarciavera — DISMISSED** [review]

**Review by zone-live — DISMISSED** [review]

**Review by Daniel-Cross — DISMISSED** [review]

**Review by zone-live — APPROVED** [review]

**Review by javiergarciavera — APPROVED** [review]

**Review by Daniel-Cross — APPROVED** [review]
