### PR TITLE
fix: regeneration of metametrics id when it is an empty string cp-7.58.0

### LINKED ISSUE #22133: Error: Hex ID must start with 0x prefix
Sentry Issue: [METAMASK-MOBILE-3VB7](https://metamask.sentry.io/issues/6696615102/?referrer=github_integration)

```
Error: Hex ID must start with 0x prefix
  at isSamplingMetaMetricsUser (app/core/Engine/controllers/network-controller/utils.ts:139:45)
  at shouldCreateRpcServiceEvents (app/core/Engine/controllers/network-controller/utils.ts:118:30)
  at trackRpcEndpointEvent (app/core/Engine/controllers/network-controller/messenger-action-handlers.ts:141:34)
  at onRpcEndpointDegraded (app/core/Engine/controllers/network-controller/messenger-action-handlers.ts:95:24)
  at ?anon_0_ (app/core/Engine/Engine.ts:458:30)
...
(8 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**

**What is the reason for the change?**

Users with corrupted `metaMetricsId` values (such as `""`, `"null"`, or other invalid strings) were experiencing empty remote feature flags, preventing them from receiving A/B test variants, gradual rollouts, and platform-specific configurations.

**Root Cause:**
The `#getMetaMetricsId` method in `MetaMetrics.ts` only checked for falsy values (`!metametricsId`), which failed to catch corrupted strings like `""` (2-character string containing two double-quotes). This corrupted ID would then be passed to `RemoteFeatureFlagController`, where `generateDeterministicRandomNumber("")` would throw an error during user segmentation processing, preventing feature flags from being cached.

**What is the improvement/solution?**

Added a simple length validation check (`metametricsId.length < 32`) to detect and regenerate corrupted IDs. Valid IDs are at least 32 characters (UUIDv4 = 36 chars, Hex = 66 chars), so this single check catches all known corruptions:
- `""` (length 2)
- `"null"` (length 4)  
- `"undefined"` (length 9)
- Any other short corrupted strings

The fix applies the same validation to both legacy Mixpanel IDs and new MetaMetrics IDs, ensuring consistency and preventing crashes in `RemoteFeatureFlagController`.

## **Changelog**

CHANGELOG entry: Fixed a bug where corrupted analytics IDs prevented users from receiving remote feature flags

## **Related issues**

Fixes: #[ISSUE_NUMBER]

## **Manual testing steps**

```gherkin
Feature: MetaMetrics ID corruption recovery

  Scenario: user with corrupted metaMetricsId gets feature flags
    Given the user has a corrupted metaMetricsId stored (e.g., '""')
    When the app initializes MetaMetrics
    Then a new valid UUID is generated and stored
    And remote feature flags are successfully fetched and cached
    And the corruption is logged for monitoring

  Scenario: user with valid metaMetricsId continues normally
    Given the user has a valid metaMetricsId (length >= 32)
    When the app initializes MetaMetrics
    Then the existing ID is preserved
    And remote feature flags work correctly

  Scenario: legacy Mixpanel ID validation
    Given the user has a legacy Mixpanel ID
    When the ID length is >= 32
    Then the legacy ID is migrated to MetaMetrics storage
    When the ID length is < 32
    Then a new UUID is generated instead
```

### **Unit Test Coverage**

Run the following to verify all corrupted ID scenarios are handled:

```bash
yarn jest app/core/Analytics/MetaMetrics.test.ts -t "corrupted ID validation"
```

Tests cover:
- ✅ JSON-stringified empty string (`""`)
- ✅ Too short IDs (`"abc"`)
- ✅ String literals (`"null"`, `"undefined"`)
- ✅ Invalid UUID formats
- ✅ Valid UUID acceptance
- ✅ Valid hex format acceptance
- ✅ Corrupted legacy Mixpanel ID rejection

## **Screenshots/Recordings**
This record goest over a branch switch from main to this branch with the metametrics hardcoded to a string inside of a string
https://github.com/user-attachments/assets/9fc5bb8f-d61c-461d-8b6a-6315de36c6b8

### **Before**

User state with corrupted ID:
```json
{
  "metaMetricsId": "\"\"",
  "RemoteFeatureFlagController": {
    "remoteFeatureFlags": {},
    "cacheTimestamp": 0
  }
}
```

Console logs would show silent failures in feature flag processing, with users missing out on:
- A/B test variants
- Gradual feature rollouts
- Platform-specific configurations

### **After**

With the fix applied:
```
MetaMetrics: Corrupted metaMetricsId detected and regenerated. Invalid value: ""
```

User state after fix:
```json
{
  "metaMetricsId": "12345678-1234-4567-89ab-123456789012",
  "RemoteFeatureFlagController": {
    "remoteFeatureFlags": {
      "backendWebSocketConnection": { "value": true },
      "perpsPerpTradingGeoBlockedCountriesV2": { "blockedRegions": [...] }
    },
    "cacheTimestamp": 1699564800000
  }
}
```

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

### **Files Changed**
- `app/core/Analytics/MetaMetrics.ts`: Added length validation to `#getMetaMetricsId` method
- `app/core/Analytics/MetaMetrics.test.ts`: Added comprehensive test suite for corrupted ID scenarios

### **Performance Impact**
- Negligible: Single length check is O(1) operation
- No additional API calls or storage operations

### **Backward Compatibility**
- ✅ Fully backward compatible
- ✅ Automatically heals users with existing corrupted IDs
- ✅ No migration required
- ✅ No user action needed

### **Monitoring**
The fix includes logging when corrupted IDs are detected:
```typescript
Logger.log(
  `MetaMetrics: Corrupted metaMetricsId detected and regenerated. Invalid value: ${metametricsId}`,
);
```

This allows us to:
- Track how many users are affected
- Identify potential sources of corruption
- Monitor if the issue persists or is resolved

### **Security Considerations**
- No security implications
- Corrupted ID values are logged (for debugging), but they contain no PII
- New generated UUIDs follow existing security practices

---

> [!NOTE]
> Adds strict ID validation (UUIDv4 or legacy hex) for MetaMetrics, regenerating corrupted IDs and migrating valid Mixpanel hex IDs.
> 
> - **Analytics (`app/core/Analytics/MetaMetrics.ts`)**:
>   - Validate stored `metaMetricsId` using `uuid.validate`; regenerate with `uuidv4()` and log when invalid or corrupted.
>   - Accept legacy Mixpanel ID only if it’s a valid hex address (`isHexAddress(legacyId.toLowerCase())`); migrate to `METAMETRICS_ID`.
>   - Import `validate` (uuid) and `isHexAddress` for the above checks.
> - **Tests (`app/core/Analytics/MetaMetrics.test.ts`)**:
>   - Add cases covering valid hex Mixpanel IDs (including uppercase), rejection of non-hex Mixpanel IDs, and multiple corruption scenarios (`""`, short strings, `"null"`, `"undefined"`, invalid UUID), plus acceptance of valid UUIDv4.
>   - Use `uuid.validate` and `isHexAddress` assertions; update expectations for storage interactions.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0bddd52f20633e6cca3ffcea76552e190c21bed3. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/core/Analytics/MetaMetrics.ts [hunk 1]
```diff
@@ -298,7 +298,7 @@ class MetaMetrics implements IMetaMetrics {
     // this same ID should be retrieved from preferences and reused.
     // look for a legacy ID from MixPanel integration and use it
     const legacyId = await StorageWrapper.getItem(MIXPANEL_METAMETRICS_ID);
-    if (legacyId) {
+    if (legacyId && legacyId.length >= 32) {
```
Comment (tommasini) [inline app/core/Analytics/MetaMetrics.ts]: Double check if mixpanel legacy id was on a UUID v4 format

Comment (NicolasMassart) [reply app/core/Analytics/MetaMetrics.ts]: I'm not sure why you test it's >= 32. The legacy format was ETH like address which is 42 characters.
Legacy can not be uuid, it's only readonly.

File: app/core/Analytics/MetaMetrics.ts [hunk 2]
```diff
@@ -307,7 +307,17 @@ class MetaMetrics implements IMetaMetrics {
     // look for a new Metametics ID and use it or generate a new one
     const metametricsId: string | undefined =
       await StorageWrapper.getItem(METAMETRICS_ID);
-    if (!metametricsId) {
+
+    // Validate the stored ID - regenerate if corrupted or too short
+    // Valid IDs are at least 32 chars (UUIDv4=36, Hex=66)
+    // This catches '""', 'null', 'undefined', and other corruptions
+    if (!metametricsId || metametricsId.length < 32) {
```
Comment (NicolasMassart) [inline app/core/Analytics/MetaMetrics.ts]: S: If you need to validate that id is a valid UUID, use the uuid `validate` function.

File: app/core/Analytics/MetaMetrics.test.ts [hunk 3]
```diff
@@ -731,6 +731,129 @@ describe('MetaMetrics', () => {
...
+        );
+        const metaMetrics = TestMetaMetrics.getInstance();
+
+        await metaMetrics.configure();
+
+        const metricsId = await metaMetrics.getMetaMetricsId();
+        expect(metricsId).not.toEqual('not-a-valid-uuid-format');
+        expect(metricsId).toMatch(
+          /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
+        );
```
Comment (NicolasMassart) [inline app/core/Analytics/MetaMetrics.test.ts]: S: use `uuid.validate()` instead of reinventing the wheel

**Review by NicolasMassart — CHANGES_REQUESTED** [review]

File: app/core/Analytics/MetaMetrics.ts [hunk 4]
```diff
@@ -307,7 +307,17 @@ class MetaMetrics implements IMetaMetrics {
...
+      if (metametricsId) {
+        // Log corruption for monitoring
+        Logger.log(
+          `MetaMetrics: Corrupted metaMetricsId detected and regenerated. Invalid value: ${metametricsId}`,
```
Comment (NicolasMassart) [inline app/core/Analytics/MetaMetrics.ts:317]: Q: do we have any idea of what leads to corruption?

Comment (tommasini) [reply app/core/Analytics/MetaMetrics.ts:317]: No :(

File: app/core/Analytics/MetaMetrics.test.ts [hunk 5]
```diff
@@ -791,7 +792,7 @@ describe('MetaMetrics', () => {
 
         const metricsId = await metaMetrics.getMetaMetricsId();
         expect(metricsId).not.toEqual('undefined');
-        expect(metricsId.length).toBeGreaterThan(10);
+        expect(metricsId?.length).toBeGreaterThan(10);
```
Comment (NicolasMassart) [inline app/core/Analytics/MetaMetrics.test.ts]: why testing > 10 instead of actually testing the uuid format?

File: app/core/Analytics/MetaMetrics.ts [hunk 6]
```diff
@@ -298,7 +298,7 @@ class MetaMetrics implements IMetaMetrics {
     // this same ID should be retrieved from preferences and reused.
     // look for a legacy ID from MixPanel integration and use it
     const legacyId = await StorageWrapper.getItem(MIXPANEL_METAMETRICS_ID);
-    if (legacyId && legacyId.length >= 32) {
+    if (legacyId) {
```
Comment (NicolasMassart) [inline app/core/Analytics/MetaMetrics.ts]: Q: you are not testing for a corrupted legacy id anymore? See 
cursor[bot] comment bellow

Comment (tommasini) [reply app/core/Analytics/MetaMetrics.ts]: Yeah not sure now, how to test for legacy corrupted ones, you mentioned they are hexadecimal addresses hmm
Wondering how should we validate it tbh

File: app/core/Analytics/MetaMetrics.test.ts (hunk 5 above)
Comment (tommasini) [reply app/core/Analytics/MetaMetrics.test.ts]: Ah, forgot to update those tests clearly with the new logic!

**Review by NicolasMassart — APPROVED** [review]
Looks good to me. I would love us to understand and get rid of the corruption, but until then, this fix is fine.
Note that I will take that into account for #21763
