### PR TITLE
fix: cp-7.47.0 fix watchAsset

### LINKED ISSUE #12501: [Bug]: Failing to add a token from the dapp
### Describe the bug

Calling `wallet_watchAsset` is not adding a token to the token list when called from dapps.
Call being made:
```
provider.request({
      method: 'wallet_watchAsset',
      params: {
        type: 'ERC20',
        options: {
          address: erc20Address,
          symbol: tokenSymbol,
          decimals: decimalUnitsInput.value,
          image: 'https://metamask.github.io/test-dapp/metamask-fox.svg',
        },
      },
    });
```

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/6be26f48-0094-4419-8404-cb06254235f7

### Steps to reproduce

1. Go to the MetaMask test dapp on the inapp browser
2. Connect to the dapp
3. Deploy an ERC20 token
4. Tap Add Tokens to Wallet
5. Approve -> Your token is not added to MetaMask

### Error messages or log output

_No response_

### Detection stage

During release testing

### Version

7.37.0

### Build type

None

### Device

iPhone 11

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR to fix adding token to state through watchAsset

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15819
Fixes: https://github.com/MetaMask/metamask-mobile/issues/12501

## **Manual testing steps**

1. Go to linea scan or use any other network
2. Choose a token that you do not already own
3. Click "Add token to Metamask"
4. Go back to home page you should see your token correctly

### **After**

https://github.com/user-attachments/assets/c3c408fa-0716-4ce9-b85c-09d024a14c14

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/RPCMethods/wallet_watchAsset.ts [hunk 1]
```diff
@@ -107,7 +102,8 @@ export const wallet_watchAsset = async ({
       image,
     },
     type,
-    interactingAddress: safeToChecksumAddress(interactingAddress),
+    interactingAddress,
```
Comment (sahar-fehri) [inline app/core/RPCMethods/wallet_watchAsset.ts:105]: Hey @owencraston 👋 ; accountAddresses in `allTokens` state are not checksumAddresses.
I have removed the safeToChecksumAddress because when a user adds a new token through watchAsset; it was not being displayed in the asset list and it was creating a new entry in state with a new accountAddress that is checksum address instead of adding the token to the already exisiting user tokens

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Comment by Unik0rnMaggie** [comment]
- The fix works for watchAsset
- The scroll issue on Android is still present (workaround: two-finger scroll)


https://github.com/user-attachments/assets/8c6aa947-60da-4b90-8039-abc8a4b8c17d


https://github.com/user-attachments/assets/50ecaec4-0674-4492-ac04-7fde5cf9cd42

**Review by owencraston — DISMISSED** [review]

**Comment by Unik0rnMaggie** [comment]
- QA passed for watchAsset
- [new issue](https://github.com/MetaMask/metamask-mobile/issues/15900) created for scroll bug on Android, to be fixed separately

**Review by ffmcgee725 — DISMISSED** [review]

**Review by jiexi — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]
