### PR TITLE
fix: Network Configurations state is undefined

### LINKED ISSUE #9269: [Sentry] Error: Migration 23: Invalid network configuration state: 'undefined'
Sentry Issue: [METAMASK-MOBILE-2BW4](https://metamask.sentry.io/issues/5199480198/?referrer=github_integration)

```
Error: Migration 23: Invalid network configuration state: 'undefined'
  at r (ses.cjs:7575:17)
  at migrate (app/store/migrations/023.js:43:11)
  at asyncMigration (app/store/migrations/index.ts:100:16)
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**

Remove frequentRpcList length validation, or if networkConfigurations is undefined default back to an empty object

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/9269

## **Manual testing steps**
Nothing to add
1. Go to this page...
2.
3.

### **Before**
Nothing to add

### **After**
Nothing to add

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/store/migrations/020.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ export default function migrate(state) {
     );
     delete preferencesControllerState.frequentRpcList;
 
-    networkControllerState.networkConfigurations = networkConfigurations;
+    networkControllerState.networkConfigurations = networkConfigurations ?? {};
```
Comment (Cal-L) [inline app/store/migrations/020.js:38]: Update the migration test to account for this

**Review by Cal-L — APPROVED** [review]
LGTM
