### PR TITLE
fix: cp-7.51.0 import token navigation

### LINKED ISSUE #17201: [Bug]: Import token flow broken on iOS
### Describe the bug

When importing a token on iOS:

- The Import button is unresponsive
- Clicking Cancel works and the token is displayed in the token list
- The toast message `You've imported a token` does not disappear when restarting the app, switching networks or tabs
- Restarting the app a second time makes the toast message disappear

Unable to reproduce on Android.

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/660aeb7d-664f-4cf9-a11b-07a4acbdd10e

### Steps to reproduce

1. Import token on any network on iOS device

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.51.0

### Build type

None

### Device

iPhone 15

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

There was an issue on IOS after new re-architecture, where importing a token never navigated to the home screen. We have moved the navigation directly inside the modal rather than being invoked through a useParam callback.

## **Changelog**

CHANGELOG entry: Fixed IOS bug where import tokens never navigated back to home screen

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/17201

## **Manual testing steps**

See issue above and fix video below
1. Try to import a token
2. Click confirm
3. EXPECTED - to be navigated to the home screen and 1 toast is shown.

### **After**

https://www.loom.com/share/cd4e6fa339c041edb9b4b727d81a8f83?sid=54c7d141-2147-4c79-a8d9-21e7d8403c30

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/AddCustomToken/index.js [hunk 1]
```diff
@@ -257,28 +257,21 @@ class AddCustomToken extends PureComponent {
...
+      warningSymbol: '',
+      warningDecimals: '',
+    });
+
+    NotificationManager.showSimpleNotification({
+      status: `import_success`,
+      duration: 5000,
+      title: strings('wallet.token_toast.token_imported_title'),
+      description: strings('wallet.token_toast.token_imported_desc_1'),
+    });
```
Comment (Prithpal-Sooriya) [inline app/components/UI/AddCustomToken/index.js:274]: 1. Removed the logic from the setState callback.
2. Removed navigation - this was "flakey" on IOS, so moved to the actual confirm button instead of passing through.
3. Removed `InteractionManager` as this doesn't manage navigation.

**Review by salimtb — APPROVED** [review]

File: app/components/UI/ConfirmAddAsset/ConfirmAddAsset.tsx [hunk 2]
```diff
@@ -219,8 +219,9 @@ const ConfirmAddAsset = () => {
               size: ButtonSize.Lg,
             },
             {
-              onPress: () => {
-                addTokenList();
+              onPress: async () => {
+                await addTokenList();
+                goToWalletPage();
```
Comment (Prithpal-Sooriya) [inline app/components/UI/ConfirmAddAsset/ConfirmAddAsset.tsx:224]: 1. We await the addTokenList function passed in.
2. This component is responsible for navigation (it already is responsible for other navigations).
