### PR TITLE
Stops the unintended 'User Rejected...' error caused by buggy submitt…

### LINKED ISSUE #1420: When sending a transaction, "Transaction error" alert pops up but transaction still goes through
Screen Shot 2020-03-11 at 4 21 19 PM

This issue has been happening inconsistently since last year, but has been happening more frequently lately, and when it does happen, it produces a poor user experience.  Unfortunately I have not found a way to consistently reproduce this issue, nonetheless it does happen during the send flow process (send a token from one address to another).  Out of 5 transactions it may happen once or more.

example flow seen here = https://recordit.co/0kmeXBC7zk

Even though I got the transaction error, you can see that transaction still went through 

image

**Another user reported something similar:** 
_While sending some ETH via metamask mobile iOS testflight, my first transaction to another wallet presented “the user/receiver declined/rejected the transaction”
i retried the transaction, which succeeded. What i then found was that both transactions had succeeded even though the first presented an error. this could be a critical bug if it happens on the main net seeing that a user may think their initial transaction failed, only to find that they’ve sent the same amount of eth twice._

I can send that users state logs to whomever picks this one up.

### PR DESCRIPTION
**Pull request by danjm**
Fixes #1420

----

1. Create a new wallet
2. Switch to the ropsten network
3. Go to the metamask faucet and get 1 eth for your Account 1
4. Create a new account, Account 2, so that your wallet has two accounts
5. Go to the metamask faucet and get 1 eth for your Account 2
6. Once the transaction is confirmed, go to your Transaction History
7. Now open the wallet sidebar and click "Send"
8. Send a transaction (this will be a transaction sent from account 2).
9. Wait for the transaction to confirm.
10. Switch to Account 1
11. go to your Transaction History
12. Now open the wallet sidebar and click "Send"
13. When you attempt to send this transaction, you will see the "User rejected this transaction" error, but when you cancel you will see that the transaction was submitted.

From this state, you can continuously recreate the error by doing the following:
14. Wait for the last transaction to confirm
15. Switch to Account 2
16. Repeat steps 7-13

----

Explanation of why this is happening from the perspective of the code.

1. When the "Transaction History" is open, the `TransactionView` component mounts
2. On every update of the `TransactionView` component, its `normalizeTransactions` method is called
3. When in the send flow after having been on the transaction history page, the `TransactionView` component stays mounted. So when in this flow and confirming a transaction by clicking "Send", the `normalizeTransactions` method of `TransactionView` will be called.
4. `normalizeTransactions` compares the nonces of all `submitted` transactions to all `confirmed` transactions, if any of the submitted tx nonces are the same as the confirmedTx nonces, `TransactionController.cancelTransaction` is called on that submitted transaction.
5. **Important:** the `confirmed` transactions here includes all confirmed transactions from all accounts. _If_ the just submitted transaction has a nonce equal to the nonce of an already confirmed transaction _from another account_ then the `cancelTransaction` method mentioned in 4 will be called.
6. `cancelTransaction` causes an error to be emitted that causes the modal "User rejected..." message to be shown
7. However, step 5 and 6 happens _after_ the `TransactionController.approveTransaction` method has been called and sent the transaction to the blockchain. Which is why the transaction still goes through

### CODE REVIEW

File: app/components/Views/Asset/index.js [hunk 1]
```diff
@@ -179,9 +179,12 @@ class Asset extends PureComponent {
 			submittedTxs.sort((a, b) => (a.time > b.time ? -1 : b.time > a.time ? 1 : 0));
 			confirmedTxs.sort((a, b) => (a.time > b.time ? -1 : b.time > a.time ? 1 : 0));
 
+			const currentAccountConfirmedTxs = confirmedTxs.filter(
+				tx => tx.transaction.from === this.props.selectedAddress.toLowerCase()
+			);
 			const submittedNonces = [];
 			submittedTxs = submittedTxs.filter(transaction => {
-				const alreadyConfirmed = confirmedTxs.find(
+				const alreadyConfirmed = currentAccountConfirmedTxs.find(
```
Comment (andrepimenta) [inline app/components/Views/Asset/index.js:187]: Here couldn't we do:
`tx => tx.transaction.nonce === transaction.transaction.nonce && tx.transaction.from === this.props.selectedAddress.toLowerCase()`?

In this way we can remove the previous filter and we would do only 1 cycle. This would be noticeable in terms of performance if `confirmedTxs` possible gets large.

What do you think?

**Review by andrepimenta — APPROVED** [review]
I left a small comment about the filter, to see what you think.

But apart from that, all the logic and solution looks great! 👍

**Review by ibrahimtaveras00 — APPROVED** [review]
Fix looks good, QA Passed 👍

File: app/components/Views/Asset/index.js (hunk 1 above)
Comment (danjm) [reply app/components/Views/Asset/index.js]: I have addressed this in the latest commit
