### PR TITLE
fix: 7862 invalid address error

### LINKED ISSUE #7862: [Bug]: Inputting any manual char into `Recipient` field breaks the wallet with `Invalid address` (implications: ENS is broken now)
### Describe the bug

**Problem:** whenever I try to enter a ENS domain, the wallet breaks at the first char with the error `Invalid address`

### Expected behavior

The wallet should not break.
ENS should be supported.

### Screenshots/Recordings

Screenshot from 2023-11-17 10-51-06

https://github.com/MetaMask/metamask-mobile/assets/54408225/bc9041ce-aaca-4c71-a6ac-393530f32ee7

### Steps to reproduce

1. Start Send flow
2. Add any char for recipient
3. Wallet breaks

### Error messages or log output

_No response_

### Version

7.11.0 (1200)- not present in 7.10.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by dawnseeker8**
## **Description**

This PR was created to fix the issue [#7862], following code change has been done:
1. Change the `getKeyringByAddress()` method to return undefined when address is not valid hex address (e.g. ENS domain name)
2. Fix the existing unit tests to reflect above changes in `address/index.test.ts` file
3. add extra unit tests to make sure function will return undefined when address is not valid hex address (e.g. ENS domain)

## **Related issues**

Fixes: [#7862]

## **Manual testing steps**

Please refer to following videos for detail how to test.

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/7315988/2c61515b-df26-460f-b2da-93fe6902e004

### **After**

https://github.com/MetaMask/metamask-mobile/assets/7315988/f8cf64bb-e323-452f-99be-0c3ffc99592f

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/address/index.js [hunk 1]
```diff
@@ -171,11 +171,11 @@ export function isQRHardwareAccount(address) {
  * get address's kerying
  *
  * @param {String} address - String corresponding to an address
- * @returns {Keyring} - Returns address's account keyriong
+ * @returns {Keyring | undefined} - Returns address's account keyriong if keyring found, otherwise return undefined
```
Comment (gantunesr) [inline app/util/address/index.js:174]: Nit
```suggestion
 * @returns {Keyring | undefined} - Returns the keyring of the provided address if keyring found, otherwise returns undefined
```

**Review by gantunesr — DISMISSED** [review]

**Review by cryptotavares — COMMENTED** [review]
@dawnseeker8 can you please also add a unit test to the `AddressInput` component where the `toSelectedAddress` is not a valid hex address?
[AddressTo Component](https://github.com/MetaMask/metamask-mobile/blob/main/app/components/UI/AddressInputs/index.js#L244)
[Existing unit tests](https://github.com/MetaMask/metamask-mobile/blob/main/app/components/UI/AddressInputs/index.test.jsx#L83) - as you can see there are only tests with valid hex addresses.

**Comment by seaona** [comment]
The PR looks good from QA cc @dawnseeker8 . I see the issue fixed. I can enter any char, and both hex and ENS address seem to work as expected


https://github.com/MetaMask/metamask-mobile/assets/54408225/48313c4b-e72c-44ca-8f03-fae2c8161a14

**Review by sethkfman — APPROVED** [review]
LGTM
