### PR TITLE
fix: Use max in send flow

### LINKED ISSUE #13215: [Bug]: not able to send "Use Max" assets, always getting JSON-RPC error
### Describe the bug

Not able to send "Use Max" assets.  Always getting JSON-RPC error after trying to send.

### Expected behavior

I should be able to send "Use Max" assets.

### Screenshots/Recordings

https://github.com/user-attachments/assets/78b5737e-9300-4f82-ae85-1e4b7e36d582

### Steps to reproduce

GIVEN I am sending assets from my imported QR HW account
WHEN I send "Use Max" assets
THEN send transaction is successful (FAILED: getting JSON-RPC error)
AND assets value sent is asset balance minus fees (FAILED: getting JSON-RPC error)

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.39.0

### Build type

None

### Device

iOS

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR revives https://github.com/MetaMask/metamask-mobile/pull/13304

Fix support for the Use Max option in the send flow.

- Ensure the maxValueMode prop is populated from the Redux state.
- Update once transaction state is added to controller.

Also revert previous fix for the sake of minimum code.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/13215

## **Manual testing steps**

Use max in send flow should work properly

### **After**

Without waiting for gas update 

https://github.com/user-attachments/assets/58cf9757-7add-423e-8f37-210eb2ecada0

With waiting gas update 

https://github.com/user-attachments/assets/4db02957-9150-4313-93c5-a0753857f18c

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/confirmations/legacy/SendFlow/Amount/index.js [hunk 1]
```diff
@@ -1534,16 +1523,10 @@ class Amount extends PureComponent {
...
                     onPress={this.useMax}
                   >
-                    <Text
-                      style={
-                        isEstimateedTotalGasValid
-                          ? styles.maxText
-                          : styles.maxTextDisabled
-                      }
-                    >
+                    <Text style={styles.maxText}>
```
Comment (digiwand) [inline app/components/Views/confirmations/legacy/SendFlow/Amount/index.js:1529]: Q: why did we remove the disabled style in the file?

**Comment by digiwand** [comment]
looks like we need to add additional tests to pass coverage

File: app/components/Views/confirmations/legacy/SendFlow/Amount/index.js (hunk 1 above)
Comment (OGPoyraz) [reply app/components/Views/confirmations/legacy/SendFlow/Amount/index.js:1529]: It reverts the previous fix PR as it doesn't solve the fix. (This is mentioned in the previous PR description https://github.com/MetaMask/metamask-mobile/pull/13304)

Comment (OGPoyraz) [reply app/components/Views/confirmations/legacy/SendFlow/Amount/index.js:1529]: More accurately - https://github.com/MetaMask/metamask-mobile/pull/13279

**Comment by OGPoyraz** [comment]
> looks like we need to add additional tests to pass coverage

@digiwand I think it's fair to say skip unit tests for legacy components like `Send` since the testability of these components are terribly bad. It's not worth the effort since we are already on a track for redesigns. I will just add `skip-sonar-cloud` to pass that check but first need a validation from @sleepytanya

**Comment by sleepytanya** [comment]
@OGPoyraz 
QA builds: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/20246c5e-624f-422e-b15c-c1cdb880a167

Sending Max native token (and other ERC 20) looks beautiful! Whne there are not enough ETH to pay for gas the correct message is shown:



https://github.com/user-attachments/assets/b46f2a8d-d8d4-40b0-a3c3-274635e10fac

**Review by sleepytanya — DISMISSED** [review]

**Review by pedronfigueiredo — DISMISSED** [review]

**Review by jpuri — DISMISSED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

File: app/components/Views/confirmations/legacy/SendFlow/Confirm/utils.test.ts [hunk 2]
```diff
@@ -1,45 +1,108 @@
...
 describe('updateTransactionToMaxValue', () => {
-  it('should update the transaction value correctly', async () => {
+  let mockSetTransactionValue: jest.Mock;
+
+  beforeEach(() => {
+    mockSetTransactionValue = jest.fn();
+    (updateEditableParams as jest.Mock).mockClear();
+  });
+
+  it('should update EIP1559 transaction value correctly', async () => {
```
Comment (NicolasMassart) [inline app/components/Views/confirmations/legacy/SendFlow/Confirm/utils.test.ts:19]:
```suggestion
  it('updates EIP1559 transaction value', async () => {
```

File: app/components/Views/confirmations/legacy/SendFlow/Confirm/utils.test.ts [hunk 3]
```diff
@@ -1,45 +1,108 @@
...
+      .toString(16);
+    const expectedHexValue = `0x${expectedValue}`;
+
+    expect(mockSetTransactionValue).toHaveBeenCalledWith(expectedHexValue);
+    expect(updateEditableParams).toHaveBeenCalledWith(transactionId, {
+      value: expectedHexValue,
+    });
+  });
+
+  it('should update legacy transaction value correctly', async () => {
```
Comment (NicolasMassart) [inline app/components/Views/confirmations/legacy/SendFlow/Confirm/utils.test.ts:44]:
```suggestion
  it('updates legacy transaction value', async () => {
```

File: app/components/Views/confirmations/legacy/SendFlow/Confirm/utils.test.ts [hunk 4]
```diff
@@ -1,45 +1,108 @@
...
+      .toString(16);
+    const expectedHexValue = `0x${expectedValue}`;
+
+    expect(mockSetTransactionValue).toHaveBeenCalledWith(expectedHexValue);
+    expect(updateEditableParams).toHaveBeenCalledWith(transactionId, {
+      value: expectedHexValue,
+    });
+  });
+
+  it('should handle negative balance case', async () => {
```
Comment (NicolasMassart) [inline app/components/Views/confirmations/legacy/SendFlow/Confirm/utils.test.ts:69]:
```suggestion
  it('does not update value if it makes account have negative balance', async () => {
```

File: app/components/Views/confirmations/legacy/SendFlow/Confirm/utils.test.ts [hunk 5]
```diff
@@ -1,45 +1,108 @@
...
-
-    // Check if setTransactionValue was called with the correct value
-    expect(setTransactionValue).toHaveBeenCalledWith(
-      expectedMaxTransactionValueHex,
-    );
+    expect(mockSetTransactionValue).not.toHaveBeenCalled();
+    expect(updateEditableParams).not.toHaveBeenCalled();
+  });
+
+  it('should handle missing transactionId', async () => {
```
Comment (NicolasMassart) [inline app/components/Views/confirmations/legacy/SendFlow/Confirm/utils.test.ts:87]:
```suggestion
  it('does not update value when missing transactionId', async () => {
```
