### PR TITLE
fix: cp-7.55.0 deep link transfer request cause app to crash

### LINKED ISSUE #19372: [Bug]: ERC20 and ETH Payment deep link app crash - Cannot read property 'maxValueMode' of undefined
### Describe the bug

The app crashes when opening an ERC20 payment request deep link, on both iOS and Android (7.55.0 - **2370**), for both cold start and warm start, with the following error:

View: Root
TypeError: Cannot read property 'maxValueMode' of undefined

### Expected behavior

No crash

### Screenshots/Recordings

https://github.com/user-attachments/assets/fac2787b-abd1-4714-b670-12e622af03bc

Image

### Steps to reproduce

1. go to https://metamask.github.io/metamask-deeplinks/# on the device browser
2. Generate ERC20 token transfer
3. Click the link
4. Notice error 

### Error messages or log output

```shell
View: Root
TypeError: Cannot read property 'maxValueMode' of undefined
```

### Detection stage

During release testing

### Version

7.55.0

### Build type

None

### Device

iPhone 15, Pixel 6 Pro

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Fix for the issue that app crashes when trying to send transfer from deeplink.

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/19372

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Screenshots/Recordings**
TODO

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/confirmations/hooks/useMaxValueMode.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import { useSelector } from 'react-redux';
+
+import { selectTransactionState } from '../../../../reducers/transaction';
+import { useParams } from '../../../../util/navigation/navUtils';
+
+export function useMaxValueMode() {
```
Comment (Matt561) [inline app/components/Views/confirmations/hooks/useMaxValueMode.ts:6]: A comment above this hook to explain what "max value mode" is and why we use it would be helpful.

**Review by Matt561 — APPROVED** [review]
Approving on behalf of Earn 👍

**Review by OGPoyraz — APPROVED** [review]
