### PR TITLE
fix: Fix fallback of gas market estimates on send flow

### LINKED ISSUE #20877: [Sentry] TypeError: Cannot read property 'suggestedMaxFeePerGas' of undefined
Sentry Issue: [METAMASK-MOBILE-4H61](https://metamask.sentry.io/issues/6921751722/?referrer=github_integration)

```
TypeError: Cannot read property 'suggestedMaxFeePerGas' of undefined
  at getEstimatedTotalGas (/app/components/Views/confirmations/components/send/asset/asset.tsx:99:9)
  at getPercentageValueFn (/app/components/Views/confirmations/components/send/asset/asset.tsx:129:12)
  at anonymous (/app/components/Views/confirmations/components/send/asset/asset.tsx:122:24)
  at anonymous (/app/components/Views/confirmations/components/send/asset/asset.tsx:14:99)
  at onPress (/app/components/Views/confirmations/components/network-filter/network-filter.tsx:15:69)
...
(8 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to fix rarely happening issue on estimating gas on send flow. 

The issue happens because of the undefined market values - basically the PR is fixing it to '0' to prevent crash.

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/20877

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Adds a null-safe fallback for `suggestedMaxFeePerGas` in `getEstimatedTotalGas` to prevent crashes when gas market data is undefined.
> 
> - **Send flow**
>   - `app/components/Views/confirmations/hooks/send/usePercentageAmount.ts`:
>     - `getEstimatedTotalGas`: use optional chaining and default `medium.suggestedMaxFeePerGas` to `0` when absent to ensure safe gas total calculation.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0b70da281352b6fff73e398d75e863c6a7acf8ab. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/confirmations/hooks/send/usePercentageAmount.ts [hunk 1]
```diff
@@ -28,9 +28,8 @@ export const getEstimatedTotalGas = (
   if (!gasFeeEstimates) {
     return new BN(0);
   }
-  const {
-    medium: { suggestedMaxFeePerGas },
-  } = gasFeeEstimates;
+  const suggestedMaxFeePerGas =
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/hooks/send/usePercentageAmount.ts:31]: Do we only support EIP-1559 chains via the gas fee API in the send flow?

What if basic functionality is disabled?

**Review by matthewwalsh0 — APPROVED** [review]

File: app/components/Views/confirmations/hooks/send/usePercentageAmount.ts (hunk 1 above)
Comment (OGPoyraz) [reply app/components/Views/confirmations/hooks/send/usePercentageAmount.ts:31]: Good call, I will merge this as it's fixing an exception. But we should definitely handle that case, I will do that in a separate PR
