### PR TITLE
Sig request design fixed

### LINKED ISSUE #1488: Complete New Signature Request Screen Designs
This task is to follow up on the work done in https://github.com/MetaMask/metamask-mobile/issues/1484 and complete the signature request screen redesign.

Pictured here:

Screenshot from 2020-04-13 22-33-29

As a first step, you should make a reusable component for the "account info card":

Screenshot from 2020-04-13 22-40-33

It is likely not important to componentize the "message card" at this time:

Screenshot from 2020-04-13 22-42-31

But you should be able to see the full message when that card is clicked (The second of the two screens here: https://www.figma.com/file/dzapXt5s0pKBxb9lZkIoDM/%231352---Confirm-transactions?node-id=916%3A125).

Most of the work will be doable in `mobile/app/components/UI/SignatureRequest/index.js` or imported child components.

### PR DESCRIPTION
**Pull request by EtDu**
**Description**

Implement new signature request screen designs

**Checklist**

- [x] Create `AccountInfoCard` component
- [x] SignatureRequest: use AccountInfoCard
- [x] SignatureRequest: remove scrollview
- [x] ActionView: remove scrollview if rendered by message, typed or personal sign components (isSigning = true)
- [x] TypedSign (V1, V3, V4): Ensure message content fits within the box (no overflow)
- [x] MessageSign: Ensure message content fits within the box (no overflow)
- [x] PersonalSign: Ensure message content fits within the box (no overflow)
- [x] Ensure arrow icon only renders if content is clipped
- [x] SignatureRequest: tap on children (message box) to expand and reveal the full message
- [x] SignatureRequest: tap on the top left arrow to go back (collapsing full message)
- [x] MessageSign: add new warning message 

**Issue**

Resolves #1488

### CODE REVIEW

**Comment by EtDu** [comment]
Screen Shot 2020-04-16 at 11 12 34 PM

@cjeria What do you think? This is with typed data signing.

**Comment by cjeria** [comment]
@EtDu Does the style of the data change per the data type (string vs type data)? For instance, if the message is a string (like the cryptokitties example below), does the style of the message font change?

If so, I'm inclined to suggest styling `type data` messages like code blocks and strings like the example below.



Also, note that the arrow symbol ">" (indicating the message can be expanded) is only intended for very long messages that don't fit inside the container.

**Comment by EtDu** [comment]
Screen Shot 2020-04-17 at 9 48 03 PM

CryptoKitties example with a regular message

**Comment by EtDu** [comment]
Screen Shot 2020-04-20 at 8 45 51 PM
eth_sign message sign

File: app/components/UI/StyledButton/styledButtonStyles.js [hunk 1]
```diff
@@ -45,12 +45,12 @@ const styles = StyleSheet.create({
 		color: colors.blue
 	},
 	normal: {
-		backgroundColor: colors.white,
+		backgroundColor: colors.blue,
```
Comment (danjm) [inline app/components/UI/StyledButton/styledButtonStyles.js:48]: The changes in this file will affect 'normal' type buttons across the app. Was this requested by design?

File: app/components/UI/ActionView/index.js [hunk 2]
```diff
@@ -43,28 +41,33 @@ export default function ActionView({
...
 }) {
 	return (
 		<View style={baseStyles.flexGrow}>
-			<KeyboardAwareScrollView
-				style={baseStyles.flexGrow}
-				resetScrollToCoords={{ x: 0, y: 0 }}
-				keyboardShouldPersistTaps={keyboardShouldPersistTaps}
-			>
-				<TouchableWithoutFeedback
+			{isSigning ? (
```
Comment (danjm) [inline app/components/UI/ActionView/index.js:49]: Nit: a variable name that is more general than `isSigning` would more accurately reflect the general purpose use of `ActionView`.

`noScroll` would be an option

File: app/components/UI/ActionView/index.js [hunk 3]
```diff
@@ -161,5 +165,9 @@ ActionView.propTypes = {
 	/**
 	 * Determines if the keyboard should stay visible after a tap
 	 */
-	keyboardShouldPersistTaps: PropTypes.string
+	keyboardShouldPersistTaps: PropTypes.string,
+	/**
```
Comment (danjm) [inline app/components/UI/ActionView/index.js:169]: See above comment on suggested variable name change. The comment here could then be more generalized as well.

File: app/components/UI/MessageSign/index.js [hunk 4]
```diff
@@ -1,44 +1,42 @@
...
+		...fontStyles.regular,
+		fontSize: 14
 	}
 });
 
 /**
- * PureComponent that supports eth_sign
+ * Component that supports eth_sign
  */
-export default class MessageSign extends PureComponent {
```
Comment (danjm) [inline app/components/UI/MessageSign/index.js:41]: Why the change from `PureComponent` to `React.Component`?

**Review by danjm — CHANGES_REQUESTED** [review]
Nice work. Left some minor comments and questions.

**Comment by danjm** [comment]
I'll do final review once unit tests are passing and we get design approval. I'll also do a QA pass as Ibrahim is mostly out this week.

File: app/components/UI/StyledButton/styledButtonStyles.js (hunk 1 above)
Comment (EtDu) [reply app/components/UI/StyledButton/styledButtonStyles.js:48]: Hmm I made the assumption. Perhaps I shouldn't have.

File: app/components/UI/ActionView/index.js (hunk 3 above)
Comment (EtDu) [reply app/components/UI/ActionView/index.js:169]: This one was there already

File: app/components/UI/MessageSign/index.js (hunk 4 above)
Comment (EtDu) [reply app/components/UI/MessageSign/index.js:41]: Now the signing components have state

Comment (danjm) [reply app/components/UI/MessageSign/index.js:41]: oh, right

File: app/components/UI/AccountInfoCard/index.js [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+					<View style={styles.accountNameAndAddress}>
+						<Text numberOfLines={1} style={styles.accountName}>
+							{accountLabel}
+						</Text>
+						<Text numberOfLines={1} style={styles.accountAddress}>
+							({address})
+						</Text>
+					</View>
+					<Text numberOfLines={1} style={styles.balanceText}>
+						{strings('signature_request.balance_title')} ${dollarBalance} ({balance} {strings('unit.eth')})
```
Comment (estebanmino) [inline app/components/UI/AccountInfoCard/index.js:95]: my guess is that here we're not using the proper format for fiat balance, we have a method to handle that called `weiToFiat`

File: app/components/UI/ActionView/index.js [hunk 6]
```diff
@@ -43,28 +41,33 @@ export default function ActionView({
 	showConfirmButton,
 	confirmed,
 	confirmDisabled,
-	keyboardShouldPersistTaps = 'never'
+	keyboardShouldPersistTaps = 'never',
```
Comment (estebanmino) [inline app/components/UI/ActionView/index.js:44]: what's the purpose of this? I remember being debugging some problems for `ActionView`s that are using this in order to work

File: app/components/UI/MessageSign/index.js (hunk 4 above)
Comment (estebanmino) [reply app/components/UI/MessageSign/index.js:41]: you can have `PureComponents` with state (in fact all of our components with state are PureComponents), this is a performance improvement we did while ago, could you change it back?

File: app/components/UI/PersonalSign/index.js [hunk 7]
```diff
@@ -1,52 +1,48 @@
...
+		fontSize: 14
 	}
 });
 
 /**
- * PureComponent that supports personal_sign
+ * Component that supports personal_sign
  */
-export default class PersonalSign extends PureComponent {
+export default class PersonalSign extends React.Component {
```
Comment (estebanmino) [inline app/components/UI/PersonalSign/index.js:45]: same about `PureComponent`

File: app/components/UI/PersonalSign/index.js [hunk 8]
```diff
@@ -96,35 +97,76 @@ export default class PersonalSign extends PureComponent {
...
+						{this.renderMessageText()}
 					</View>
 				</SignatureRequest>
 			</View>
 		);
+		return rootView;
+	};
+
+	render() {
+		return this.renderRootView();
```
Comment (estebanmino) [inline app/components/UI/PersonalSign/index.js:170]: why don't just add that method content on `render`

File: app/components/UI/SignatureRequest/index.js [hunk 9]
```diff
@@ -177,42 +180,34 @@ class SignatureRequest extends PureComponent {
 		</TouchableOpacity>
 	);
 
+	renderActionViewChildren = () => {
+		const { children, currentPageInformation, shouldRenderArrow, toggleExpandedMessage } = this.props;
+		const url = currentPageInformation.url;
+		const title = getHost(url);
+		const arrowIcon = shouldRenderArrow ? this.renderArrowIcon() : null;
```
Comment (estebanmino) [inline app/components/UI/SignatureRequest/index.js:187]: am I missing the definition of `renderArrowIcon` ?

File: app/components/UI/SignatureRequest/index.js [hunk 10]
```diff
@@ -229,20 +224,17 @@ class SignatureRequest extends PureComponent {
 					confirmText={strings('signature_request.sign')}
 					onCancelPress={this.onCancel}
 					onConfirmPress={this.onConfirm}
+					confirmButtonMode="sign"
+					noScroll
```
Comment (estebanmino) [inline app/components/UI/SignatureRequest/index.js:228]: seems like this is removing the ability to scroll? we have to keep in mind that there are smaller devices that needs this to see the whole view

File: app/components/UI/TypedSign/index.js [hunk 11]
```diff
@@ -1,56 +1,55 @@
...
 		fontWeight: 'bold'
 	}
 });
 
 /**
- * PureComponent that supports eth_signTypedData and eth_signTypedData_v3
+ * Component that supports eth_signTypedData and eth_signTypedData_v3
  */
-export default class TypedSign extends PureComponent {
+export default class TypedSign extends React.Component {
```
Comment (estebanmino) [inline app/components/UI/TypedSign/index.js:52]: same about `PureComponent`

File: app/components/UI/ActionView/index.js [hunk 12]
```diff
@@ -43,28 +41,33 @@ export default function ActionView({
...
+	noScroll
```
Comment (estebanmino) [inline app/components/UI/ActionView/index.js:45]: what's the purpose to block the abiolity to scroll? we have to support smaller devices that without this could not be able to display all the information we may need to

**Review by estebanmino — CHANGES_REQUESTED** [review]
left some comments. @danjm I'd wait for @ibrahimtaveras00 to do QA he can build the app on both IOS and Android devices

**Comment by estebanmino** [comment]
I'm also worried about the task `SignatureRequest: remove scrollview` I believe we need that for smaller devices but @ibrahimtaveras00 can take a look that

File: app/components/UI/ActionView/index.js (hunk 6 above)
Comment (EtDu) [reply app/components/UI/ActionView/index.js:44]: I don't know why this is showing up in the diff, this wasn't my work so I'm not sure

File: app/components/UI/MessageSign/index.js (hunk 4 above)
Comment (EtDu) [reply app/components/UI/MessageSign/index.js:41]: You're right, misunderstanding on my part, I'll change it back

File: app/components/UI/AccountInfoCard/index.js (hunk 5 above)
Comment (EtDu) [reply app/components/UI/AccountInfoCard/index.js:95]: Noted!

File: app/components/UI/PersonalSign/index.js (hunk 8 above)
Comment (EtDu) [reply app/components/UI/PersonalSign/index.js:170]: Okay, makes sense

File: app/components/UI/SignatureRequest/index.js (hunk 9 above)
Comment (EtDu) [reply app/components/UI/SignatureRequest/index.js:187]: It is directly below `renderActionViewChildren`

**Comment by EtDu** [comment]
> I'm also worried about the task `SignatureRequest: remove scrollview` I believe we need that for smaller devices but @ibrahimtaveras00 can take a look that

@estebanmino  The reasoning for this was because of the new design. Instead of scrolling on the signature request screen, the user would tap the message to expand it, where they can scroll there if necessary

File: app/components/UI/ActionView/index.js (hunk 12 above)
Comment (EtDu) [reply app/components/UI/ActionView/index.js:45]: below comment

File: app/components/UI/TypedSign/index.js (hunk 11 above)
Comment (EtDu) [reply app/components/UI/TypedSign/index.js:52]: resolved

File: app/components/UI/SignatureRequest/index.js (hunk 10 above)
Comment (EtDu) [reply app/components/UI/SignatureRequest/index.js:228]: below comment

**Comment by EtDu** [comment]
Screen Shot 2020-04-24 at 11 35 35 AM
@cjeria

**Comment by EtDu** [comment]
Screen Shot 2020-04-27 at 12 46 30 PM

with `AccountInfoCard` ontop

**Review by estebanmino — APPROVED** [review]
LGTM!

**Comment by ibrahimtaveras00** [comment]
There are quite a few screen sizes that don't play well with the new design: 

image

**Comment by EtDu** [comment]
@ibrahimtaveras00 Thank you for the feedback, I'll get it fixed

**Comment by EtDu** [comment]
@ibrahimtaveras00 Fixed all of the above! Also, Android native back button takes you back to "Sign this message"

File: app/components/UI/AccountInfoCard/index.js [hunk 13]
```diff
@@ -0,0 +1,119 @@
...
+							{accountLabel}
+						</Text>
+						<Text numberOfLines={1} style={styles.accountAddress}>
+							({address})
+						</Text>
+					</View>
+					{operation === 'signing' ? null : (
+						<Text numberOfLines={1} style={styles.balanceText}>
+							{strings('signature_request.balance_title')} {dollarBalance} ({balance}{' '}
+							{strings('unit.eth')})
```
Comment (estebanmino) [inline app/components/UI/AccountInfoCard/index.js:102]: users can change the ticker of networks so can we use https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/UI/AccountSelect/index.js#L179 ?

File: app/components/UI/PersonalSign/index.js [hunk 14]
```diff
@@ -4,47 +4,26 @@ import { StyleSheet, View, Text } from 'react-native';
...
-		fontSize: 18,
-		marginVertical: 12,
-		marginHorizontal: 20,
-		color: colors.fontPrimary,
-		...fontStyles.bold
+	textLeft: {
+		textAlign: 'left'
+	},
+	messageWrapper: {
+		marginBottom: 5
```
Comment (estebanmino) [inline app/components/UI/PersonalSign/index.js:21]: I'm almost sure 5 is not a number we use for margins and borders, are we sure about it?

File: app/components/UI/SignatureRequest/index.js [hunk 15]
```diff
@@ -167,60 +191,68 @@ class SignatureRequest extends PureComponent {
...
+			<Ionicons name={'ios-arrow-forward'} size={20} style={styles.arrowIcon} />
+		</View>
+	);
+
+	render() {
+		const { showWarning, currentPageInformation, type } = this.props;
+		let expandedHeight;
+		if (Device.getDeviceHeight() < 736) {
+			expandedHeight = styles.expandedHeight2;
+		} else if (type === 'ethSign' && Device.getDeviceHeight() >= 736) {
```
Comment (estebanmino) [inline app/components/UI/SignatureRequest/index.js:243]: where is 736 coming from? we have an util file that can help you with this https://github.com/MetaMask/metamask-mobile/blob/develop/app/util/Device.js

File: app/components/UI/StyledButton/styledButtonStyles.js [hunk 16]
```diff
@@ -60,10 +60,10 @@ const styles = StyleSheet.create({
 	cancel: {
 		backgroundColor: colors.white,
 		borderWidth: 1,
-		borderColor: colors.grey400
+		borderColor: colors.blue
 	},
 	cancelText: {
-		color: colors.grey400
+		color: colors.blue
```
Comment (estebanmino) [inline app/components/UI/StyledButton/styledButtonStyles.js:66]: this is changing all the cancel buttons we have in the app... is that the purpose of this?

File: app/components/Nav/Main/index.js [hunk 17]
```diff
@@ -928,7 +940,7 @@ class Main extends PureComponent {
 				animationInTiming={600}
 				animationOutTiming={600}
 				onBackdropPress={this.onSignAction}
-				onBackButtonPress={this.onSignAction}
+				onBackButtonPress={showExpandedMessage ? this.toggleExpandedMessage : this.onSignAction}
```
Comment (estebanmino) [inline app/components/Nav/Main/index.js:943]: this feels strange to me, having a state variable from /Main to change stuff inside a component. Did you try to use https://reactnative.dev/docs/backhandler to handle the back button on these modals?

**Review by estebanmino — CHANGES_REQUESTED** [review]

**Comment by ibrahimtaveras00** [comment]
Issues 1 and 2 have been fixed!

**Issue 3:**

However, I'm noticing that we no longer show the balance in the accountInfoCard how it appears in the design mockups; is that intentional?  I wasn't sure if we should only show it for sign message v2, but currently it's not showing for any sign type.  

Screen Shot 2020-05-06 at 12 34 06 AM

Screen Shot 2020-05-06 at 12 52 27 AM


**Issue 4:**

For some reason, I'm unable to bring up the sign modal for sign typed data v4 on the bottom of this page https://danfinlay.github.io/js-eth-personal-sign-examples/ 

seen here = https://recordit.co/AyTlC6gYdL

Screen Shot 2020-05-06 at 12 48 08 AM

File: app/components/Nav/Main/index.js (hunk 17 above)
Comment (EtDu) [reply app/components/Nav/Main/index.js:943]: Yes, but when a Modal is open `BackHandler` doesn't publish any events. Modal has the `onRequestClose` prop for this very purpose. Since we're using a wrapped version of the native `Modal`, it's `onBackButtonPress`.  Since the Modal is at the top of the view hierarchy for signing operations, I wasn't sure how else to implement this.

File: app/components/UI/AccountInfoCard/index.js (hunk 13 above)
Comment (EtDu) [reply app/components/UI/AccountInfoCard/index.js]: done

File: app/components/UI/PersonalSign/index.js (hunk 14 above)
Comment (EtDu) [reply app/components/UI/PersonalSign/index.js]: changed to 4

File: app/components/UI/SignatureRequest/index.js (hunk 15 above)
Comment (EtDu) [reply app/components/UI/SignatureRequest/index.js]: 736 is the height of iPhone 8+/7+. Added new helper to `Device`

File: app/components/UI/StyledButton/styledButtonStyles.js (hunk 16 above)
Comment (EtDu) [reply app/components/UI/StyledButton/styledButtonStyles.js:74]: Not sure, so just made a new button type for signing components

**Comment by EtDu** [comment]
@ibrahimtaveras00 Issue #3 is intentional as of recently, but only for the signing components. Issue #4 doesn't appear to be related to this PR (also present on `develop`). I've opened #1551 to address it. 

To anyone: In the case I'm missing something and this is intentional, please close the issue

**Review by ibrahimtaveras00 — APPROVED** [review]
Fixes look good on both OS's, QA passed 👍

File: app/components/UI/StyledButton/styledButtonStyles.js (hunk 16 above)
Comment (estebanmino) [reply app/components/UI/StyledButton/styledButtonStyles.js:74]: we need to change it, can you create a new style? This is changing all the cancel button styles

Comment (estebanmino) [reply app/components/UI/StyledButton/styledButtonStyles.js:74]: you can use `info` style https://github.com/MetaMask/metamask-mobile/pull/1493/files/c4b8407d87ddb76adb061c24d4a1cc4ac0ac2b54#diff-ff2e6a58d18583289e9404b4a668ecc5R149 for that button and make `cancelText` with color `grey400` again

Comment (estebanmino) [reply app/components/UI/StyledButton/styledButtonStyles.js:74]: @EtDu I talked with @cjeria about this, we're going with grey400 as the color for cancel buttons so we need to update it

Comment (estebanmino) [reply app/components/UI/StyledButton/styledButtonStyles.js:74]: this is the button style we should use https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/UI/StyledButton/styledButtonStyles.js#L121

Comment (EtDu) [reply app/components/UI/StyledButton/styledButtonStyles.js:74]: I already created a new style `signingCancel` is that ok?

**Comment by EtDu** [comment]
Okay I've rebased and switched the compare branch to `develop`. Anything else before merge?

**Review by estebanmino — APPROVED** [review]

**Review by danjm — APPROVED** [review]
LGTM
