### PR TITLE
fix: poll only popular network

### LINKED ISSUE #29055: [Bug]: Infinite Load after upgrade to `12.9.0`
### Describe the bug

I just updated to the latest version `12.9.0` and it keeps loading forever when I log in. Before you ask, yes I cleared the cache, yes I restarted the browser, yes I checked that it's the correct MetaMask version. Previously I had no such issue.

Image

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Upgrade to latest MetaMask version and try log in

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.9.0

### Build type

None

### Browser

Microsoft Edge

### Operating system

Windows

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**
To reduce the impact of showing assets across all networks, which can be unbounded, this PR scopes the portfolio view to the 9 popular networks built into metamask.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/29055

## **Manual testing steps**

1. On popular networks:
  - The token filter should allow switching between popular networks and current network
  - The filter should work as described
  - RPC requests in the background should only hit the popular networks

2. On other networks
  - The token filter should become disabled and scoped to the current network
  - RPC requests in the background should only hit the current network

### **After**

https://github.com/user-attachments/assets/a65afd42-b67e-401e-b33c-b46fad3dd812

https://github.com/user-attachments/assets/e2179b4c-c3da-43d1-86d3-50fc066f0899

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by tommasini** [comment]
Can we have a recording of what changed?

File: app/components/UI/Tokens/index.tsx [hunk 1]
```diff
@@ -141,6 +143,22 @@ const Tokens: React.FC<TokensI> = ({ tokens }) => {
...
+      currentChainId === CHAIN_IDS.MAINNET ||
+      currentChainId === CHAIN_IDS.LINEA_MAINNET,
+  );
+
+  useEffect(() => {
+    const { PreferencesController } = Engine.context;
+    if (!isPopularNetwork) {
+      PreferencesController.setTokenNetworkFilter({
+        [currentChainId]: true,
+      });
```
Comment (bergeron) [inline app/components/UI/Tokens/index.tsx:158]: One thing that seems undesirable about this.

If you're on a popular network with the filter on 'popular'.  Then switch to a non popular network (which scopes your filter to 'current'), then switch back to a popular network, it does not restore your filter to 'popular'.

By writing to the setting here, we lose the memory of which filter we would restore when coming back to a popular network.  That might be fine for now if it simplifies getting this fix in.


https://github.com/user-attachments/assets/6b307f79-03e0-4e39-8759-2ecf77690344

File: app/selectors/networkController.ts [hunk 2]
```diff
@@ -168,12 +171,16 @@ export const selectIsEIP1559Network = createSelector(
...
-  (tokenNetworkFilter) => {
+  (networkConfigurations, tokenNetworkFilter) => {
     if (Object.keys(tokenNetworkFilter).length === 1) {
       return false;
     }
-    return true;
+    const allNetworks = enableAllNetworksFilter(networkConfigurations);
+    return (
+      Object.keys(tokenNetworkFilter).length === Object.keys(allNetworks).length
+    );
```
Comment (bergeron) [inline app/selectors/networkController.ts:183]: Can you explain why this change is needed?

File: app/components/hooks/AssetPolling/useAccountTrackerPolling.ts [hunk 3]
```diff
@@ -1,37 +1,61 @@
...
+  }));
 
-  const chainIdsToPoll = isPortfolioViewEnabled()
-    ? networkClientIds ?? networkClientIdsConfig
-    : [
-        {
-          networkClientId: selectedNetworkClientId,
-        },
-      ];
+  const chainIdsToPoll =
```
Comment (bergeron) [inline app/components/hooks/AssetPolling/useAccountTrackerPolling.ts:51]: All of these polling hooks should only hit the current chain if the token filter is set to 'current network', but it doesn't look like that currently the case?

File: app/selectors/networkController.ts [hunk 4]
```diff
@@ -187,3 +194,25 @@ export const selectNativeCurrencyByChainId = createSelector(
   (networkConfigurations, chainId) =>
     networkConfigurations?.[chainId]?.nativeCurrency,
 );
+
+export const selectChainIdsToPoll = createSelector(
```
Comment (bergeron) [inline app/selectors/networkController.ts:198]: Similar comment where we only want to poll the current chain if the filter is set to 'current network'

File: app/components/hooks/AssetPolling/useTokenBalancesPolling.ts [hunk 5]
```diff
@@ -3,22 +3,22 @@ import usePolling from '../usePolling';
...
+  selectChainIdsToPoll,
 } from '../../../selectors/networkController';
 import { Hex } from '@metamask/utils';
 import { isPortfolioViewEnabled } from '../../../util/networks';
 import { selectAllTokenBalances } from '../../../selectors/tokenBalancesController';
 
 const useTokenBalancesPolling = ({ chainIds }: { chainIds?: Hex[] } = {}) => {
   // Selectors to determine polling input
-  const networkConfigurations = useSelector(selectNetworkConfigurations);
+  const networkConfigurations = useSelector(selectChainIdsToPoll);
```
Comment (bergeron) [inline app/components/hooks/AssetPolling/useTokenBalancesPolling.ts:14]: Don't think `networkConfigurations` is an accurate variable name anymore, isn't this an array of chain ids now?

Here and in other files

File: app/components/hooks/AssetPolling/useCurrencyRatePolling.ts [hunk 6]
```diff
@@ -1,26 +1,51 @@
...
+  const currentChainId = useSelector(selectChainId);
+
+  const isPopular = PopularList.some(
+    (popular) =>
+      popular.chainId === currentChainId ||
+      currentChainId === CHAIN_IDS.MAINNET ||
+      currentChainId === CHAIN_IDS.LINEA_MAINNET,
+  );
+
+  const chainIdsToPoll: NetworkConfiguration[] = Object.values(
```
Comment (bergeron) [inline app/components/hooks/AssetPolling/useCurrencyRatePolling.ts:29]: Any reason some hooks use `selectChainIdsToPoll` and others have their own logic?

File: app/components/UI/Tokens/TokensBottomSheet/TokenFilterBottomSheet.test.tsx [hunk 7]
```diff
@@ -114,14 +114,14 @@ describe('TokenFilterBottomSheet', () => {
...
-    expect(queryByText('All Networks')).toBeTruthy();
+    expect(queryByText('Popular networks')).toBeTruthy();
     expect(queryByText('Current Network')).toBeTruthy();
   });
 
   it('sets filter to All Networks and closes bottom sheet when first option is pressed', async () => {
     const { queryByText } = render(<TokenFilterBottomSheet />);
 
-    fireEvent.press(queryByText('All Networks'));
+    fireEvent.press(queryByText('Popular networks'));
```
Comment (gambinish) [inline app/components/UI/Tokens/TokensBottomSheet/TokenFilterBottomSheet.test.tsx:124]: Nit: I wonder if we should use a `testID` instead here. Also on line 114 we should probably change "All Networks" in the test statement to "Popular Networks"

File: app/components/UI/Tokens/index.tsx (hunk 1 above)
Comment (salimtb) [reply app/components/UI/Tokens/index.tsx]: fixed [1b9230d](https://github.com/MetaMask/metamask-mobile/pull/12658/commits/1b9230d235493704a9640d17238cd8c15cd78055)

File: app/selectors/networkController.ts (hunk 2 above)
Comment (salimtb) [reply app/selectors/networkController.ts:181]: they are no needed , i changed a bit the logic now

File: app/components/hooks/AssetPolling/useTokenBalancesPolling.ts (hunk 5 above)
Comment (salimtb) [reply app/components/hooks/AssetPolling/useTokenBalancesPolling.ts]: fixed [1b9230d](https://github.com/MetaMask/metamask-mobile/pull/12658/commits/1b9230d235493704a9640d17238cd8c15cd78055)

File: app/components/hooks/AssetPolling/useCurrencyRatePolling.ts (hunk 6 above)
Comment (salimtb) [reply app/components/hooks/AssetPolling/useCurrencyRatePolling.ts]: logic changed , i also add some comments to explain
check fixed [1b9230d](https://github.com/MetaMask/metamask-mobile/pull/12658/commits/1b9230d235493704a9640d17238cd8c15cd78055)

File: app/components/UI/Tokens/TokensBottomSheet/TokenFilterBottomSheet.test.tsx (hunk 7 above)
Comment (salimtb) [reply app/components/UI/Tokens/TokensBottomSheet/TokenFilterBottomSheet.test.tsx:124]: good idea , i'll try to do it separately

File: app/components/hooks/AssetPolling/useTokenDetectionPolling.ts [hunk 8]
```diff
@@ -3,21 +3,55 @@ import usePolling from '../usePolling';
...
 
 const useTokenDetectionPolling = ({ chainIds }: { chainIds?: Hex[] } = {}) => {
   const networkConfigurations = useSelector(selectNetworkConfigurations);
   const currentChainId = useSelector(selectChainId);
   const selectedAccount = useSelector(selectSelectedInternalAccount);
   const useTokenDetection = useSelector(selectUseTokenDetection);
+  const isAllNetworksSelected = useSelector(selectIsAllNetworks);
 
+  // determine if the current chain is popular
+  const isPopular = PopularList.some(
```
Comment (vinnyhoward) [inline app/components/hooks/AssetPolling/useTokenDetectionPolling.ts:25]: I'm seeing this used a lot. Would probably be best as a helper function in network util? I don't think its a blocker though

Comment (gambinish) [reply app/components/hooks/AssetPolling/useTokenDetectionPolling.ts:25]: ☝️ this might help get past the sonar cloud quality gate as well

Comment (salimtb) [reply app/components/hooks/AssetPolling/useTokenDetectionPolling.ts:25]: yes on it , coming with a refacto now

File: app/components/hooks/AssetPolling/useTokenBalancesPolling.ts [hunk 9]
```diff
@@ -3,22 +3,53 @@ import usePolling from '../usePolling';
...
+  ).reduce((acc: NetworkConfiguration[], network) => {
+    if (
+      isPopular ||
+      network.chainId === CHAIN_IDS.MAINNET ||
+      network.chainId === CHAIN_IDS.LINEA_MAINNET
+    ) {
+      acc.push(network);
+    }
+    return acc;
+  }, []);
```
Comment (bergeron) [inline app/components/hooks/AssetPolling/useTokenBalancesPolling.ts:44]: Looks duplicated across the polling hooks, which sonar cloud doesn't like.  Do you think this could be shared in a hook?

Comment (salimtb) [reply app/components/hooks/AssetPolling/useTokenBalancesPolling.ts:44]: yes on it now , will push a refacto on a second commit il a few moment

Comment (salimtb) [reply app/components/hooks/AssetPolling/useTokenBalancesPolling.ts]: fixed [3687f77](https://github.com/MetaMask/metamask-mobile/pull/12658/commits/3687f77e742cabda50c3338dab2b8f8299c5d0af)

**Review by vinnyhoward — DISMISSED** [review]

**Review by vinnyhoward — DISMISSED** [review]

File: app/components/hooks/AssetPolling/utils.ts [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+      popular.chainId === currentChainId ||
+      currentChainId === CHAIN_IDS.MAINNET ||
+      currentChainId === CHAIN_IDS.LINEA_MAINNET,
+  );
+
+  // filter out networks that are not popular, mainnet or linea mainnet
+  return Object.values(networkConfigurations).reduce(
+    (acc: NetworkConfiguration[], network) => {
+      if (
+        isPopular ||
```
Comment (bergeron) [inline app/components/hooks/AssetPolling/utils.ts:23]: While testing, I noticed it was polling sepolia 0xaa36a7 and other testnets when it should not.

I think this doesn't work because it's using `isPopular` based on the current chain, which is just making this reduce true for every chain in the network configurations

Comment (salimtb) [reply app/components/hooks/AssetPolling/utils.ts:23]: what was you configuration when you noticed this ? were you on currentNetwork or popularNetwork ? what was the selected network ?

Comment (salimtb) [reply app/components/hooks/AssetPolling/utils.ts]: i implemented a potential solution based on your comment here:
[68a2adc](https://github.com/MetaMask/metamask-mobile/pull/12658/commits/68a2adc87b013681e436b95e516a0ed0e5b8f0f6)
let me know your thoughts

File: app/components/hooks/AssetPolling/utils.ts [hunk 11]
```diff
@@ -0,0 +1,27 @@
...
+
+  // filter out networks that are not popular, mainnet or linea mainnet
+  return Object.values(networkConfigurations).reduce(
+    (acc: NetworkConfiguration[], network) => {
+      if (
+        // check if the network is popular
+        popularNetworksChainIds.includes(network.chainId) ||
+        network.chainId === CHAIN_IDS.MAINNET ||
+        network.chainId === CHAIN_IDS.LINEA_MAINNET ||
+        isAllNetworksSelected
```
Comment (bergeron) [inline app/components/hooks/AssetPolling/utils.ts:19]: I don't think it makes sense to have `isAllNetworksSelected` here.  Wouldn't this include every network, even ones that aren't popular?

Comment (bergeron) [reply app/components/hooks/AssetPolling/utils.ts:19]: A cleaner approach might be:

- have this hook check `isAllNetworksSelected`
- if true, we return the popular networks
- if false, we return the current network

Then, each of the polling hooks does not need to check `isAllNetworksSelected` since that logic is just handled here.

We would return an array of network configurations, so each polling hook has the data is needs.  (some need chain, others need network client, others need native currency).

Comment (salimtb) [reply app/components/hooks/AssetPolling/utils.ts]: I've just pushed a refacto and here's my approach (which is also based on what you suggested):
**Selector for Popular Networks**
- i've created a selector to determine if the current network is considered popular.
- This selector will also ensure memorization in the network menu, meaning if network is not popular , the filter menu will be always on current network

**Selector to Filter Configurations for Popular Networks**

- Another selector filters out network configurations, keeping only those for popular networks.
- This excludes configurations related to test networks, such as testNet, ensuring the focus is on production-worthy networks.

**Combining Selectors and AllNetworkFilter**
- These selectors, combined with the existing allNetworkFilter, are used to define the polling rules
- Together, they dynamically adapt the application's behavior based on whether the network is popular or not.

**Comment by bergeron** [comment]
One bug I notice.

- Start on a popular network
- With the filter set to 'current network'
- Switch to a non-popular network
- Switch back to the popular network

It keeps showing tokens from the non-popular network.



https://github.com/user-attachments/assets/af85e733-4476-4588-96b2-caedf4a99208

**Comment by salimtb** [comment]
> 3adb9de

@bergeron fixed [3adb9de](https://github.com/MetaMask/metamask-mobile/pull/12658/commits/3adb9de42a0da6b7de516d072f4ebc3bf8eeaba4)

**Comment by salimtb** [comment]
> One bug I notice.
> 
> * Start on a popular network
> * With the filter set to 'current network'
> * Switch to a non-popular network
> * Switch back to the popular network
> 
> It keeps showing tokens from the non-popular network.
> 
>  Screen.Recording.2024-12-13.at.9.54.43.AM.mov

@bergeron fixed [3adb9de](https://github.com/MetaMask/metamask-mobile/pull/12658/commits/3adb9de42a0da6b7de516d072f4ebc3bf8eeaba4)

**Comment by bergeron** [comment]
Now when switching networks while the filter is on 'current network', the tokens do not update to the new network.

https://github.com/user-attachments/assets/d583eaa1-931d-464a-8dfe-5d95cad570c8

**Comment by salimtb** [comment]
> https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/497f2346-4e3b-42f9-8b6a-7a51036bd038

@bergeron bug fixed + flaky e2e test addressed , i should have a green build now

**Comment by salimtb** [comment]
> Now when switching networks while the filter is on 'current network', the tokens do not update to the new network.
> 
>  Screen.Recording.2024-12-13.at.12.11.36.PM.mov

@bergeron bug fixed + flaky e2e test addressed , i should have a green build now

**Review by Cal-L — APPROVED** [review]
LGTM

**Review by vinnyhoward — APPROVED** [review]

**Review by bergeron — APPROVED** [review]
