### PR TITLE
fix: fallback to symbol

### LINKED ISSUE #24377: [Bug]: Trending List - Token name is not showing
**Describe the bug**

Bug
Category: Trending [x] list
Build number: v7.62.0 (3402)
Device/OS: iPhone 13 Max Pro
Description: Some token names are not showing up on the trending list but their name is there on the token details page

**Expected behavior**

All tokens in the list should have their name displayed in the list

**Screenshots/Recordings**

https://github.com/user-attachments/assets/cb679fd4-13da-4867-9a03-f65c135e0e44

**Steps to reproduce**

see recording

**Error messages or log output**

```shell

```

**Where was this bug found?**

Internal release testing

**Version**

7.62.0

**Build number**

3402

**Build type**

Beta

**Device**

Iphone 13

**Operating system**

iOS

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**
Fallback to symbol if name is null

## **Changelog**

CHANGELOG entry: fallback to symbol if name is null on trending page

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/24377

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Improves robustness of Trending token row rendering, price change formatting, and navigation, with comprehensive test coverage.
> 
> - UI: `TrendingTokenRowItem` now falls back to `token.symbol` when `token.name` is null/undefined
> - Price change: extracted `getPriceChangePrefix` to standardize sign handling and neutral 0%
> - Navigation: `getAssetNavigationParams` returns null for invalid CAIP, uses native address for EVM, and passes full `assetId` as `address` for non‑EVM chains
> - Tests: add extensive cases for name/symbol fallback, price/percentage formatting (positive/negative/zero/missing), time options (`h24`, `h6`, `h1`, `m5`), zero‑price dash, network badge sources (default/testnet/popular/unpopular/non‑EVM/undefined), and navigation/modal flows
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit d4e4e08e5d383b561266dbb7762813b8cc63358d. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/Trending/components/TrendingTokenRowItem/TrendingTokenRowItem.tsx [hunk 1]
```diff
@@ -296,7 +296,7 @@ const TrendingTokenRowItem = ({
               numberOfLines={1}
               ellipsizeMode="tail"
             >
-              {token.name}
+              {token.name || token.symbol}
```
Comment (salimtb) [inline app/components/UI/Trending/components/TrendingTokenRowItem/TrendingTokenRowItem.tsx]: Small safety improvement: if `token` or `token.name` is undefined, this can behave unexpectedly.  
Suggest using optional chaining with nullish coalescing instead:

```jsx
{token?.name ?? token?.symbol}
```

**Review by salimtb — DISMISSED** [review]

**Review by Prithpal-Sooriya — DISMISSED** [review]

**Review by salimtb — DISMISSED** [review]

**Review by salimtb — APPROVED** [review]
