### PR TITLE
fix: Updated ButtonBase and ListItems to have gesture detection on Android cp-7.53.0

### LINKED ISSUE #18147: [Bug]: Button not firing onPress consistently on Android
### Describe the bug

On Android, when navigating to a scrollable asset or network list, the buttons sometimes do not fire onPress. This is a known bug from https://github.com/facebook/react-native/issues/34999 

### Expected behavior

onPress should be fired regardless of platforms

### Screenshots/Recordings

https://github.com/user-attachments/assets/05098185-7074-4a94-9ba1-33b989d9cef5

### Steps to reproduce

Please see recording

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

v7.51 + 

### Build type

None

### Device

All Android devices

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by brianacnguyen**
## **Description**
This PR updated the `ButtonBase`, `ListItemSelect`, and `ListItemMultiSelect` to include Gesture Detector, resolving a current bug in `react-native`'s `TouchableOpacity` component occasionally not triggering `onPress` on Android

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/18147

## **Manual testing steps**

```gherkin
Feature: my feature name
  Scenario: user [verb for user action]
    Given [describe expected initial app state] 
    When user [verb for user action]
    Then [describe expected outcome]
```

### **After**
Everything still functional 
https://github.com/user-attachments/assets/f4e9f41e-34f7-4bf8-a090-860bee411050
https://github.com/user-attachments/assets/f2791eb2-9520-4ce7-ad3e-6d0933d59c35

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/component-library/components/List/ListItemSelect/ListItemSelect.tsx [hunk 1]
```diff
@@ -26,11 +86,31 @@ const ListItemSelect: React.FC<ListItemSelectProps> = ({
 }) => {
   const { styles } = useStyles(styleSheet, { style, isDisabled });
 
+  // Disable gesture wrapper in test environments to prevent test interference
+  const isE2ETest =
```
Comment (vinnyhoward) [inline app/component-library/components/List/ListItemSelect/ListItemSelect.tsx:90]: nit: I see this in 3 other places. We could possibly refactor this into a helper function?

File: app/component-library/components/List/ListItemSelect/ListItemSelect.tsx [hunk 2]
```diff
@@ -12,6 +18,60 @@ import ListItem from '../../List/ListItem/ListItem';
 import styleSheet from './ListItemSelect.styles';
 import { ListItemSelectProps } from './ListItemSelect.types';
 import { DEFAULT_SELECTITEM_GAP } from './ListItemSelect.constants';
+import { Gesture, GestureDetector } from 'react-native-gesture-handler';
+
+const TouchableOpacity = ({
```
Comment (vinnyhoward) [inline app/component-library/components/List/ListItemSelect/ListItemSelect.tsx:23]: I'm possibly not looking hard enough but is there a difference with the new `TouchableOpacity` in the other 2-3 files? Should this be its own component?

**Review by vinnyhoward — APPROVED** [review]
Approving and aware that this is temporary so there isn't need for optimization at the moment after speaking with Brian

File: app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx [hunk 3]
```diff
@@ -19,6 +24,61 @@ import {
...
+            /* no-op for synthetic event */
+          },
+          preventDefault: () => {
+            /* no-op for synthetic event */
+          },
+          stopPropagation: () => {
+            /* no-op for synthetic event */
+          },
+        } as GestureResponderEvent;
+        onPress(syntheticEvent);
```
Comment (ieow) [inline app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx:60]: would this onPress being called twice?
as onPress on the RNTouchableOpacity will be called as well?

https://github.com/MetaMask/metamask-mobile/pull/18104/files#diff-d8ff46ee74cd57f89c7ac7deb9144c994a7f9db5145060058638387669a72b5aR72
