### PR TITLE
fix: cp-7.46.0 Improve `TokenList` performance with `FlashList` and improved data flow

### LINKED ISSUE #14856: [Bug]: Toggling Popular/Current Networks in Asset list lags the wallet substantially
### Describe the bug

Toggling Popular/Current Networks in Asset list lags the wallet substantially on iOS.  

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Open wallet
2. Toggle Poppular Networks / Current Network and vice versa. 
3. Observe: Wallet becomes laggy, sometimes the wallet does not register any taps, sometimes it takes a few seconds for the selection options to appear.

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.45.0

### Build type

None

### Device

iPhone X

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gambinish**
## **Description**

Expands on https://github.com/MetaMask/metamask-mobile/pull/14942 by extending `FlashList` usage and improving the data flow between our token list components for better performance.

**Improvements**
1. FlashList Optimization
- Implements `estimatedItemSize`, `estimatedListSize`, `removeClippedSubviews`, and `recomputeViewableItems`.
- Memoizes renderItem via useCallback (renderTokenListItem).
2. Data Flow Refactor — goal was to reduce the amount of data passed to `FlashList` to improve rendering performance at scale.
- Keeps responsibility of sorting and filtering logic to the `Tokens` component, consolidated to single `useMemo` hook.
- Instead of passing the full sorted/filtered asset list down as props, `Tokens` now passes a minimal list of `{ address, chainId }` to `TokenList`, where FlashList lives.
- `TokenListItem` then selects itself from Redux using the provided address/chainId pair
- Introduces two new memoized selectors that select a single token from Redux for both EVM and multichain
3. Code Cleanup
- Removes unnecessary logic such as useTokenBalancesController, which was no longer needed.
- Moves `ScamWarningModal` to parent, rather than being rendered with each `TokenListItem`, causing potential re-renders

TODO:

- Refactor TokenListFooter to select asset data from Redux instead of relying on the full asset array prop.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/14856#issuecomment-2840509507

## **Manual testing steps**

1. Add account with many assets, both on EVM and Solana
2. Aggressively scroll. There may be some empty whitespace on extremely large lists, but it shouldn't feel like a deal breaker
3. Popular Networks | Current Network filter should be responsive and not freeze the app

## **Screenshots/Recordings**

https://github.com/user-attachments/assets/27ce06b1-b85d-410e-b274-15d92ea92a5b

https://github.com/user-attachments/assets/de1fe4ea-934a-441a-b1c1-f821ed59cbad

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Tokens/TokenList/index.tsx [hunk 1]
```diff
@@ -16,56 +20,99 @@ import { useNavigation } from '@react-navigation/native';
...
+      data={tokenKeys}
+      estimatedItemSize={itemHeight}
+      estimatedListSize={{ height: estimatedListHeight, width: deviceWidth }}
+      removeClippedSubviews
+      // uncomment for debugging whitespace purposes
+      // onBlankArea={(e: BlankAreaEvent) => {
+      //   if (e.blankArea > 0.1) {
+      //     console.warn(`Large blank area detected: ${e.blankArea}`);
+      //   }
+      // }}
```
Comment (sahar-fehri) [inline app/components/UI/Tokens/TokenList/index.tsx:103]: Nit: should we remove the comments?

File: app/components/UI/Tokens/TokenList/index.tsx [hunk 2]
```diff
@@ -16,56 +20,99 @@ import { useNavigation } from '@react-navigation/native';
...
-          setShowScamWarningModal={setShowScamWarningModal}
-          privacyMode={privacyMode}
-          showPercentageChange={showPercentageChange}
-        />
-      )}
-      keyExtractor={(_, index) => index.toString()}
+      data={tokenKeys}
+      estimatedItemSize={itemHeight}
+      estimatedListSize={{ height: estimatedListHeight, width: deviceWidth }}
+      removeClippedSubviews
```
Comment (sahar-fehri) [inline app/components/UI/Tokens/TokenList/index.tsx:97]: Nice! what does this one do?

File: app/components/UI/Tokens/TokenList/index.tsx [hunk 3]
```diff
@@ -16,56 +20,99 @@ import { useNavigation } from '@react-navigation/native';
...
+        waitForInteraction: true,
+        itemVisiblePercentThreshold: 50,
+        minimumViewTime: 1000,
+      }}
+      renderItem={renderTokenListItem}
+      keyExtractor={(item) => `${item.address}-${item.chainId}`}
       ListFooterComponent={
         <TokenListFooter
-          tokens={tokens}
+          // TODO: This previously accepted all tokens as a prop
```
Comment (sahar-fehri) [inline app/components/UI/Tokens/TokenList/index.tsx:113]: Is this todo still valid

File: app/components/UI/Tokens/TokenList/index.tsx [hunk 4]
```diff
@@ -16,56 +20,99 @@ import { useNavigation } from '@react-navigation/native';
...
+          // Instead, select tokens in the footer component via redux selector
+          tokens={[]}
```
Comment (sahar-fehri) [inline app/components/UI/Tokens/TokenList/index.tsx:115]: Sorry dnt understand why we are explicitly passing an empty tokens array here?
If tokens are being selected in the footer component, should we remove the prop all together?

File: app/components/UI/Tokens/TokenList/TokenListItem/index.tsx [hunk 5]
```diff
@@ -95,15 +103,36 @@ export const TokenListItem = React.memo(
...
+    const chainId = asset?.chainId as Hex;
     const primaryCurrency = useSelector(
       (state: RootState) => state.settings.primaryCurrency,
     );
     const currentCurrency = useSelector(selectCurrentCurrency);
     const networkConfigurations = useSelector(selectNetworkConfigurations);
     const showFiatOnTestnets = useSelector(selectShowFiatInTestnets);
 
-    // multi chain
+    // // multi chain
```
Comment (Prithpal-Sooriya) [inline app/components/UI/Tokens/TokenList/TokenListItem/index.tsx:135]: double comments :D

File: app/components/UI/Tokens/TokenList/index.tsx (hunk 3 above)
Comment (gambinish) [reply app/components/UI/Tokens/TokenList/index.tsx:113]: Yep! This is something that we'll need to do before merging.

File: app/components/UI/Tokens/TokenList/TokenListItem/index.tsx [hunk 6]
```diff
@@ -95,15 +103,36 @@ export const TokenListItem = React.memo(
...
+    const selectedAccount = useSelector(selectSelectedInternalAccount);
+    const nonEvmAsset = useSelector((state: RootState) =>
+      selectNonEvmAssetById(state, {
+        accountId: selectedAccount?.id,
+        assetId: assetKey.address,
+      }),
+    );
+    ///: END:ONLY_INCLUDE_IF
+
+    let asset = isEvmNetworkSelected ? evmAsset : nonEvmAsset;
```
[the remark this answers is not in the document]
Comment (gambinish) [reply app/components/UI/Tokens/TokenList/TokenListItem/index.tsx:125]: Hmm, I don't think so but I will double check a main build to be sure.

File: app/components/UI/Tokens/TokenList/TokenListItem/index.tsx (hunk 5 above)
Comment (gambinish) [reply app/components/UI/Tokens/TokenList/TokenListItem/index.tsx]: https://github.com/MetaMask/metamask-mobile/pull/14988/commits/8b712d0a7a7bc8dc2b0154b442cbb4e397762e9e

File: app/components/UI/Tokens/TokenList/index.tsx (hunk 1 above)
Comment (gambinish) [reply app/components/UI/Tokens/TokenList/index.tsx]: https://github.com/MetaMask/metamask-mobile/pull/14988/commits/e21237ec26428fc2e4b809e857725c28266f658d

File: app/components/UI/Tokens/TokenList/TokenListItem/index.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (gambinish) [reply app/components/UI/Tokens/TokenList/TokenListItem/index.tsx:125]: Turns out I did need to codefence more things: https://github.com/MetaMask/metamask-mobile/pull/14988/commits/849b7bb87273dffaf24903f86750d2c42373fa62

Here is a recording of a main build with these codefences added:

https://github.com/user-attachments/assets/260096a0-69ed-484b-a3da-e1248d81d914

File: app/components/UI/Tokens/TokenList/TokenListFooter/__snapshots__/index.test.tsx.snap [hunk 7]
```diff
@@ -26,7 +26,7 @@ exports[`TokenListFooter renders correctly 1`] = `
         }
       }
     >
-      ETH is needed to continue
```
Comment (gambinish) [inline app/components/UI/Tokens/TokenList/TokenListFooter/__snapshots__/index.test.tsx.snap:29]: This unit test was wrong, and wasn't accurately reflecting state. Imo this is a bug, but unrelated to FlashList implementation, and should be fixed separately.

Comment (gambinish) [reply app/components/UI/Tokens/TokenList/TokenListFooter/__snapshots__/index.test.tsx.snap:29]: Ticker for tracking: https://consensyssoftware.atlassian.net/browse/MMASSETS-766

File: app/components/UI/Tokens/TokenList/index.tsx (hunk 4 above)
Comment (gambinish) [reply app/components/UI/Tokens/TokenList/index.tsx]: https://github.com/MetaMask/metamask-mobile/pull/14988/commits/2098f7961f0a833c40fb7bc7634f9f1b9dc999c9

File: app/components/UI/Tokens/TokenList/index.tsx (hunk 3 above)
Comment (gambinish) [reply app/components/UI/Tokens/TokenList/index.tsx]: https://github.com/MetaMask/metamask-mobile/pull/14988/commits/2098f7961f0a833c40fb7bc7634f9f1b9dc999c9

**Review by Prithpal-Sooriya — APPROVED** [review]

**Comment by sleepytanya** [comment]
QA builds:

https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/469ee3dd-62cf-47ad-a4e1-623e242ec17a


iOS looks great, iPhone 15:



https://github.com/user-attachments/assets/e5f4364f-ecf4-44cf-8a76-63bac6dd39c0


Android is doing good too, Samsung S24 Ultra:




https://github.com/user-attachments/assets/45df210a-b72b-429b-b5dd-47eece6195ea
