### PR TITLE
fix: migration to fix TokenController string decimals

### LINKED ISSUE #24360: [Bug]: Wallet balance not updating for EstateX token
### Describe the bug

The main wallet balance does not update and account for the EstateX token on Base blockchain (0x6a72d3A87f97a0fEE2c2ee4233BdAEBc32813D7a).

If your wallet balance shows $10, and you send $10 of EstateX token to your wallet (manual import is required), your balance will not update. The EstateX token pricing is showing correctly, but the main wallet balance does not account for this token value.

### Expected behavior

The value of EstateX token should be accounted for in the main token balance.

### Screenshots/Recordings

Image

### Steps to reproduce

1. On mobile app, have any amount of EstateX token in your wallet.
2. Add up token balances for your tokens
3. EstateX fiat token value is not accounted for

EstateX token contract: 0x6a72d3A87f97a0fEE2c2ee4233BdAEBc32813D7a

### Error messages or log output

```shell

```

### Where was this bug found?

Live version (from official store)

### Version

7.61.5

### Build number

3341

### Build type

None

### Device

Samsung Note 20 Ultra

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

EDIT: the main fix was recently done in this: https://github.com/MetaMask/metamask-mobile/pull/26108

This PR adds a migration to ensure old entries are normalised and use the expected typed shape.

## **Changelog**

CHANGELOG entry: fix: migration to fix TokenController string decimals

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/24360 https://consensyssoftware.atlassian.net/browse/ASSETS-2241

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

### **After**

https://www.loom.com/share/8e4070c5143645b98cf1f65740ff73c8

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Touches the persisted migration pipeline and mutates stored token metadata across all users, so mistakes could affect token balance display/calculations. Logic is scoped to `decimals` type normalization with guarded state checks and tests, limiting blast radius.
> 
> **Overview**
> Fixes persisted token data where `TokensController` tokens could have `decimals` stored as strings, which can break downstream calculations.
> 
> Adds migration `122` to walk `TokensController.allTokens` and `TokensController.allDetectedTokens`, converting string `decimals` to numbers (falling back to `0` when parsing fails), and wires the migration into the main `migrationList`. Includes a comprehensive unit test suite covering no-op cases and successful normalization across chains/accounts.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 3dc5c4c0f23d29f6089bc2fd3d156bb0b070078c. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/UI/AddCustomToken/index.js [hunk 1]
```diff
@@ -211,7 +211,7 @@ class AddCustomToken extends PureComponent {
     await TokensController.addToken({
       address,
       symbol,
-      decimals,
+      decimals: Number(decimals),
```
Comment (Prithpal-Sooriya) [inline app/components/UI/AddCustomToken/index.js]: Debugging this made me crazy 🤪

**Review by juanmigdr — DISMISSED** [review]
Nice one!!

**Review by sahar-fehri — DISMISSED** [review]

File: app/components/UI/AddCustomToken/index.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (Prithpal-Sooriya) [reply app/components/UI/AddCustomToken/index.js]: Hmm good callout...

Realistically we have UI form validation before it reaches here, but doesn't hurt to add some better validation checks.

[the remark this answers is not in the document]
Comment (Prithpal-Sooriya) [reply app/components/UI/AddCustomToken/index.js]: Fixed in https://github.com/MetaMask/metamask-mobile/pull/26338/commits/109f102c7d290f3f0c905b2b8c23edc3ad29e860

**Review by juanmigdr — DISMISSED** [review]

File: app/store/migrations/121.ts [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+ */
+const migration = (state: unknown): unknown => {
+  if (!ensureValidState(state, migrationVersion)) {
+    return state;
+  }
+
+  const tokensControllerState =
+    state?.engine?.backgroundState?.TokensController;
+  if (!isObject(tokensControllerState)) {
+    return state;
```
Comment (tommasini) [inline app/store/migrations/121.ts:28]: Should we capture the exception if the tokens controller state is not an object?

Comment (Prithpal-Sooriya) [reply app/store/migrations/121.ts:28]: Great calllout. Will capture errors around this.
Also will test some other edge cases

File: app/components/Views/AddAsset/components/AddCustomToken/AddCustomToken.tsx
Comment (Prithpal-Sooriya) [inline app/components/Views/AddAsset/components/AddCustomToken/AddCustomToken.tsx:1]: @cursor READ AND FOLLOW THESE MEMORY FILES:
- https://raw.githubusercontent.com/Prithpal-Sooriya/Cloud-Agent-Memory/refs/heads/main/Memory.md

Please can you undo all changes on this file? I realised that since this is now a TS file, we have the correct logic now.

The changes on this file are not needed anymore so revert the changes on this file app/components/Views/AddAsset/components/AddCustomToken/AddCustomToken.tsx (I should not see any diff changes on this file when compared to main now right?)

File: app/store/migrations/122.ts [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+
+  // Normalize allDetectedTokens decimals
+  if (
+    hasProperty(tokensControllerState, 'allDetectedTokens') &&
+    isObject(tokensControllerState.allDetectedTokens)
+  ) {
+    normalizeTokensDecimalsInMap(
+      tokensControllerState.allDetectedTokens as TokensMap,
+    );
+  }
```
Comment (Prithpal-Sooriya) [inline app/store/migrations/122.ts:87]: @cursor READ AND FOLLOW THESE MEMORY FILES:
- https://raw.githubusercontent.com/Prithpal-Sooriya/Cloud-Agent-Memory/refs/heads/main/Memory.md

From discussion here: https://github.com/MetaMask/metamask-mobile/pull/26338#discussion_r2833821043

1. Can we add the captureException similar to other migrations.

```
if (!hasProperty(...) | !isObject(...)) {
  captureException(...)
  return state;
}
```

2. Update tests to include capturing exception, hopefully we can keep tests nice and clean still.

3. Add test case to check null? (since null is an object right, wanna make sure things are fine)

**Review by sahar-fehri — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
