### PR TITLE
fix: Add PPOM validation for deeplink requests

### LINKED ISSUE #17358: [Sentry] Error: Cannot add another deeplink transaction
Sentry Issue: [METAMASK-MOBILE-3XHT](https://metamask.sentry.io/issues/6741635359/?referrer=github_integration)

```
Error: Cannot add another deeplink transaction
  at ResultError (ses-hermes.cjs:9515:17)
  at _addTransactionForDeeplink (app/components/Views/confirmations/utils/deeplink.ts:71:22)
  at e.addTransactionForDeeplink (app/components/Views/confirmations/utils/deeplink.ts:60:48)
  at _handleEthereumUrl (app/core/DeeplinkManager/Handlers/handleEthereumUrl.ts:52:13)
  at _e.default (app/core/DeeplinkManager/Handlers/handleEthereumUrl.ts:17:33)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by OGPoyraz**
## **Description**

This PR aims to add PPOM validation requests for deeplinks.

## **Changelog**

CHANGELOG entry: null

## **Related issues**

Fixes: https://github.com/MetaMask/mobile-planning/issues/2370
Fixes: https://github.com/MetaMask/metamask-mobile/issues/17358

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> Integrates PPOM validation into deeplink transfer/approve flows, generating a securityAlertId and passing it to addTransaction, with refactors and tests.
> 
> - **Deeplink handling (`app/components/Views/confirmations/utils/deeplink.ts`)**:
>   - Add `validateWithPPOM` to build a PPOM request (with uuid-based `securityAlertId`) and call `ppomUtil.validateRequest`.
>   - Pass returned `securityAlertResponse` to `addTransaction` for both native and ERC20 transfers.
>   - Refactor tx construction to derive `txParams` and `transactionType`; downgrade duplicate-request log from error to log.
> - **Approve flow (`app/core/DeeplinkManager/TransactionManager/approveTransaction.ts`)**:
>   - Compute `chainId`/`networkClientId`, call `validateWithPPOM`, and include `securityAlertResponse` in `addTransaction`.
> - **Tests**:
>   - Extend deeplink and approve tests to mock PPOM and UUID, assert PPOM validation payload, `securityAlertResponse`, and `networkClientId` wiring.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit daa4941b6922ba20b26396fd0c3e12f947bd030c. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/components/Views/confirmations/utils/deeplink.ts [hunk 1]
```diff
@@ -68,7 +72,7 @@ export async function addTransactionForDeeplink({
 
   // Temporary solution for preventing back to back deeplink requests
   if (isAddingDeeplinkTransaction) {
-    Logger.error(new Error('Cannot add another deeplink transaction'));
```
Comment (OGPoyraz) [inline app/components/Views/confirmations/utils/deeplink.ts:71]: This is causing false positives in the Sentry logs - hence we are decreasing it to log instead of error.

See comment here: https://github.com/MetaMask/metamask-mobile/issues/17358#issuecomment-3515739757

**Review by vinistevam — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
