### PR TITLE
fix: updated asset hooks to fetch enabled networks only when feature flag on

### LINKED ISSUE #18183: [Bug]: [Remove GNS] Adding a network from a dapp does not update the token list
### Describe the bug

After adding a token from a dapp, the network appears as enabled in the Portfolio Network Manager, but the token list displays the tokens of the previously enabled networks, until it is refreshed manually

### Expected behavior

Token list to update, after adding a network from a dapp

### Screenshots/Recordings

https://github.com/user-attachments/assets/719a4aaa-d3bc-4784-8397-0eaaf2721f5e

### Steps to reproduce

1. Connect to chainlist
2. Add any network
3. Go back to wallet view
4. Notice Token list does not display the tokens of the newly added network
5. Refresh to Token list
6. Notice it now displays the updated tokens

### Error messages or log output

```shell

```

### Detection stage

On a feature branch

### Version

7.54.0

### Build type

None

### Device

iPhone 15, Pixel 6 Pro

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by vinnyhoward**
## **Description**

Asset polling related hooks have been updated to fetch only enabled networks behind the `isRemoveGlobalNetworkSelectorEnabled` feature flag. This also fixes the issue where if you add a custom network via dapp the asset does not load

## **Changelog**

CHANGELOG entry:null

## **Related issues**

Fixes: [18183](https://github.com/MetaMask/metamask-mobile/issues/18183) [18236](https://github.com/MetaMask/metamask-mobile/issues/18236)

## **Manual testing steps**

```gherkin
Feature: my feature name

  Scenario: user [verb for user action]
    Given [describe expected initial app state]

    When user [verb for user action]
    Then [describe expected outcome]
```

## **Screenshots/Recordings**

`~`

### **Before**

`~`

### **After**

`~`

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/hooks/AssetPolling/useCurrencyRatePolling.ts [hunk 1]
```diff
@@ -25,19 +29,47 @@ const useCurrencyRatePolling = ({ chainIds }: { chainIds?: Hex[] } = {}) => {
...
-        }))
-      : [
+  if (isPortfolioViewEnabled()) {
+    if (isRemoveGlobalNetworkSelectorEnabled()) {
+      // When global network selector is removed, use enabled EVM networks
+      networkConfigurationsToPoll = (enabledEvmNetworks || [])
+        .filter((network) => networkConfigurations[network]?.nativeCurrency)
+        .map((network) => ({
+          nativeCurrency: networkConfigurations[network].nativeCurrency,
+        }));
```
Comment (Prithpal-Sooriya) [inline app/components/hooks/AssetPolling/useCurrencyRatePolling.ts]: Very similar network configuration logic for all of these hooks.
I wonder if we can lift this to reduce duplication.

```ts
// This handles the if checks for each of the network paths.
function getPollingNetworks(): NetworkConfiguration[] {}
```

Comment (Prithpal-Sooriya) [reply app/components/hooks/AssetPolling/useCurrencyRatePolling.ts]: Okay I've got a refactor that would be nice to include in this PR.

Comment (Prithpal-Sooriya) [reply app/components/hooks/AssetPolling/useCurrencyRatePolling.ts]: Potential clean up commit we can add.
https://github.com/MetaMask/metamask-mobile/pull/18309/commits/8b2c1ba70304444a4fcf5350f9d0e2e001b0defa

File: app/components/hooks/AssetPolling/useAccountTrackerPolling.ts [hunk 2]
```diff
@@ -1,58 +1,28 @@
...
-    : [];
-
-  let providedNetworkClientIds;
+  const pollingNetworks = usePollingNetworks();
+  const pollingNetworkClientIds = pollingNetworks
+    .map((c) => c?.rpcEndpoints?.[c?.defaultRpcEndpointIndex]?.networkClientId)
+    .filter((networkClientId) => Boolean(networkClientId));
+  const pollingInput =
+    pollingNetworkClientIds.length > 0
+      ? [{ networkClientIds: pollingNetworkClientIds }]
```
Comment (Prithpal-Sooriya) [inline app/components/hooks/AssetPolling/useAccountTrackerPolling.ts:15]: **Perf**
Before: We created multiple inputs each with a single networkClientId.
After: We now only have 1 input with multiple networkClientIds

File: app/components/hooks/AssetPolling/useCurrencyRatePolling.ts [hunk 3]
```diff
@@ -1,74 +1,49 @@
...
-  const networkConfigurationsToPoll =
-    isAllNetworksSelected && isPopularNetwork && isPortfolioViewEnabled()
-      ? Object.values(networkConfigurationsPopularNetworks).map((network) => ({
-          nativeCurrency: network.nativeCurrency,
-        }))
-      : [
+  const pollingNetworks = usePollingNetworks();
+  const pollingInput =
+    pollingNetworks.length > 0
+      ? [
```
Comment (Prithpal-Sooriya) [inline app/components/hooks/AssetPolling/useCurrencyRatePolling.ts:18]: **Perf**
Before: We created multiple inputs each with a single native currency.
After: We now only have 1 input with multiple network currencies

File: app/components/hooks/AssetPolling/useTokenBalancesPolling.ts [hunk 4]
```diff
@@ -1,47 +1,20 @@
...
-  // Selectors to determine polling input
-  const networkConfigurationsPopularNetworks = useSelector(
-    selectAllPopularNetworkConfigurations,
-  );
-  const currentChainId = useSelector(selectEvmChainId);
-  const isAllNetworksSelected = useSelector(selectIsAllNetworks);
-  const isPopularNetwork = useSelector(selectIsPopularNetwork);
-  const isEvmSelected = useSelector(selectIsEvmNetworkSelected);
+  const pollingNetworks = usePollingNetworks();
+  const pollingInput = pollingNetworks.map((c) => ({ chainId: c.chainId }));
```
Comment (Prithpal-Sooriya) [inline app/components/hooks/AssetPolling/useTokenBalancesPolling.ts:8]: Future - we should optmise this polling, instead of multiple inputs can this be squashed into 1 input?

File: app/components/hooks/AssetPolling/useTokenDetectionPolling.ts [hunk 5]
```diff
@@ -1,68 +1,47 @@
...
   }
 
-  const input = providedChainIdsAndAddress ?? chainIdsToPoll;
+  const { TokenDetectionController } = Engine.context;
+
+  const input = useTokenDetection
+    ? (overridePollingInput ?? pollingInput).filter(
+        (i) => i.chainIds && i.address,
+      )
+    : [];
```
Comment (Prithpal-Sooriya) [inline app/components/hooks/AssetPolling/useTokenDetectionPolling.ts:44]: Perf/optimisation.

We do not poll if we are missing a chainIds or address.
I'm open to reverting this but it should be acceptable

File: app/components/hooks/AssetPolling/useTokenListPolling.ts [hunk 6]
```diff
@@ -1,46 +1,20 @@
...
-  // Selectors to determine polling input
-  const networkConfigurationsPopularNetworks = useSelector(
-    selectAllPopularNetworkConfigurations,
-  );
-  const currentChainId = useSelector(selectEvmChainId);
-  const isAllNetworksSelected = useSelector(selectIsAllNetworks);
-  const isPopularNetwork = useSelector(selectIsPopularNetwork);
-  const isEvmSelected = useSelector(selectIsEvmNetworkSelected);
+  const pollingNetworks = usePollingNetworks();
+  const pollingInput = pollingNetworks.map((c) => ({ chainId: c.chainId }));
```
Comment (Prithpal-Sooriya) [inline app/components/hooks/AssetPolling/useTokenListPolling.ts:8]: Future - should we optimise this polling input? Instead of many polling inputs, should we group this into 1 input?

File: app/selectors/networkEnablementController/index.ts [hunk 7]
```diff
@@ -18,6 +18,6 @@ export const selectEVMEnabledNetworks = createDeepEqualSelector(
     enabledNetworksByNamespace: NetworkEnablementControllerState['enabledNetworkMap'],
   ) =>
     Object.keys(enabledNetworksByNamespace?.eip155 ?? {}).filter(
-      (chainId) => enabledNetworksByNamespace?.eip155?.[chainId as CaipChainId],
-    ),
+      (chainId) => enabledNetworksByNamespace?.eip155?.[chainId as Hex],
+    ) as Hex[],
```
Comment (Prithpal-Sooriya) [inline app/selectors/networkEnablementController/index.ts:22]: Meh a type change, we can keep it.

**Review by salimtb — APPROVED** [review]
