### PR TITLE
fix(deposit): fixes android region select bug

### LINKED ISSUE #17269: [Bug]: Android only - cannot select region on deposit page
### Describe the bug

Cannot select region on deposit page on Android

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/b6576c56-29d6-4daf-b3ff-61f1acaaf1dc

### Steps to reproduce

1. Go to deposit page
2. Open select region modal
3. Try to select different countries

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.51.0

### Build type

None

### Device

Android - Galaxy S 24 Ultra

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by georgeweiler**
## **Description**

Fixes https://github.com/MetaMask/metamask-mobile/issues/17269

IMG_0027

## **Changelog**

CHANGELOG entry:

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/Ramp/Deposit/Views/Modals/RegionSelectorModal/RegionSelectorModal.tsx [hunk 1]
```diff
@@ -93,45 +92,64 @@ function RegionSelectorModal() {
...
-      </ListItemSelect>
-    ),
-    [handleOnRegionPressCallback, selectedRegion, styles.region, styles.emoji],
+        </TouchableWithoutFeedback>
+      );
+    },
+    [
+      handleOnRegionPressCallback,
+      selectedRegion,
+      styles.region,
```
Comment (AxelGes) [inline app/components/UI/Ramp/Deposit/Views/Modals/RegionSelectorModal/RegionSelectorModal.tsx]: do we need this here?

**Review by AxelGes — DISMISSED** [review]

**Review by AxelGes — APPROVED** [review]
