### PR TITLE
fix: Blockaid wallet connect errors.

### LINKED ISSUE #8066: [Bug]: PPOM - `Request failed` for SendERC20, ApproveERC20 and ApproveERC721 transactions using Wallet Connect
### Describe the bug

**Problem:** whenever I am using Wallet Connect I can see how the PPOM module fails to return a response for the case of:
- Malicious SendERC20
- Malicious ApproveERC20
- Malicious ApproveERC721

Using the same account and transactions without wallet connect, results into flagging the transactions as malicious, but when using wallet connect I see the ` LOG  [MetaMask DEBUG]: Error validating JSON RPC using PPOM: Error: simulation: error: execution reverted` on the logs and the fallback UI warning.

### Expected behavior

These tx should alse be flagged as malicious when using Wallet Connect.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/364c4dfd-595b-4849-8e9e-3dff6733db53

### Steps to reproduce

1. Go to https://seaona.github.io/test-dapp/
2. Click Connect Wallet Connect
3. Scan the QR from your mobile wallet
4. Click again  Wallet Connect in the test dapp --- this is necessary for the dapp to detect the mobile account
5. Trigger any malicious: SendERC20, ApproveERC20 or ApproveERC721 tx
6. See error in the console `LOG  [MetaMask DEBUG]: Error validating JSON RPC using PPOM: Error: simulation: error: execution reverted`

### Error messages or log output

_No response_

### Version

7.14.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by segun**
## **Description**
When using Wallet Connect you can see how the PPOM module fails to return correctly for the below requests.

Malicious SendERC20
Malicious ApproveERC20
Malicious ApproveERC721
Malicious ApprovalForAll

**Expected behavior**
These tx should alse be flagged as malicious when using Wallet Connect.

**Fix**
The fix is here is just looking at the working requests and the failing request to see what's missing and adding the missing parameters to the failing requests appropriately.

## **Related issues**

Fixes: #8066 

## **Manual testing steps**

1. Go to https://seaona.github.io/test-dapp/
2. Click Connect Wallet Connect
3. Scan the QR from your mobile wallet
4. Click again Wallet Connect in the test dapp --- this is necessary for the dapp to detect the mobile account
5. Trigger any malicious: SendERC20, ApproveERC20 or ApproveERC721 
6. See error in the console LOG  [MetaMask DEBUG]: Error validating JSON RPC using PPOM: Error: simulation: error: execution reverted
7. And you see Benign Banner shown
8. Checkout this PR
9. Build and run on actual device
10. Do step 2-5
11. See no errors in console and Malicious Banner shown

### **Before**

[](https://github.com/MetaMask/metamask-mobile/assets/54408225/364c4dfd-595b-4849-8e9e-3dff6733db53)

### **After**

https://github.com/MetaMask/metamask-mobile/assets/44811/980890e8-2daf-48a2-83a8-e8813e936eb7

https://github.com/MetaMask/metamask-mobile/assets/44811/c42af17a-5119-4344-b987-ca78390efe51

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/core/WalletConnect/WalletConnectV2.ts [hunk 1]
```diff
@@ -296,13 +296,16 @@ class WalletConnect2Session {
 
         const id = trx.transactionMeta.id;
         const reqObject = {
+          id: requestEvent.id,
```
Comment (digiwand) [inline app/core/WalletConnect/WalletConnectV2.ts:299]: to confirm, looks like this might be fixing another issue. I think it would be handy to add a note for this in the PR ticket

File: app/core/WalletConnect/WalletConnectV2.ts [hunk 2]
```diff
@@ -296,13 +296,16 @@ class WalletConnect2Session {
...
-          method: 'eth_sendTransaction',
+          method,
+          origin,
           params: [
             {
               from: methodParams[0].from,
               to: methodParams[0].to,
-              value: methodParams[0].value,
+              value: methodParams[0]?.value,
+              data: methodParams[0]?.data,
```
Comment (digiwand) [inline app/core/WalletConnect/WalletConnectV2.ts:308]: this appears to be the fix. if you happen to have more details as to how this fixes the issue, please share them in the description 🙏🏼

**Review by jpuri — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
