### PR TITLE
fix: include blockaid parameters in metrics of send flow

### LINKED ISSUE #8824: [Bug]: PPOM - No blockaid data is included in Metrics events for transactions triggered from inside the wallet
### Describe the bug

**Problem:** there is no Blockaid information on metric events for transactions triggered from inside the wallet

### Expected behavior

We should have the same metrics as we have for transactions triggered from a dapp, for the following events:
- Tx added
- Tx rejected
- Tx acceptdd

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/12153f52-baeb-4344-b6f6-0c00c2a1d1fc

### Steps to reproduce

1. Enable Blockiad
2. Enable metrics
3. Send a malicious tx from inside the wallet
4. See no blockaid info is included in the metrics event

### Error messages or log output

_No response_

### Version

7.17.0

### Build type

None

### Device

Pixel 6 

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**
Include blockaid data in metrics on send from inside the app.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/8824

## **Manual testing steps**

1. Submit a transaction to a malicious address, ensure that error is reported by blockaid
2. Check that the send metrics events include blockaid results

## **Screenshots/Recordings**
NA

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/confirmations/SendFlow/Confirm/index.js [hunk 1]
```diff
@@ -443,6 +438,15 @@ class Confirm extends PureComponent {
 
       ppomUtil.validateRequest(reqObject, id);
     }
+
+    // For analytics
+    this.props.metrics.trackEvent(MetaMetricsEvents.SEND_TRANSACTION_STARTED, {
```
Comment (matthewwalsh0) [inline app/components/Views/confirmations/SendFlow/Confirm/index.js:443]: Are we intentionally moving this after the `addTransaction` so some state is updated first?

My only concern is the metric will be delayed as `addTransaction` won't resolve until multiple requests are completed like updating the gas properties, plus we won't get this metric if the validation fails for example or any error occurs when adding the transaction.

Comment (jpuri) [reply app/components/Views/confirmations/SendFlow/Confirm/index.js:443]: Transaction id is required to get blockaid metrics params, thus I moved it after addTransaction. But I agree this will delay adding `addTransaction` metrics.

A possible solution could be a exclude blockaid parameters from `addTransaction` metrics. Also, I noticed that blockaid request status is mostly `loading...` when this metrics is captured.

Comment (bschorchit) [reply app/components/Views/confirmations/SendFlow/Confirm/index.js:443]: is `addTransaction` the same of what I see as Transaction Added on Mixpanel?

Comment (bschorchit) [reply app/components/Views/confirmations/SendFlow/Confirm/index.js:443]: is `addTransaction` the Send Transaction Started or Dapp Transaction Started that I see on Mixpanel? I think we're already skipping it for dapp proposed requests too and only adding to Dapp Transaction Completed event

Comment (jpuri) [reply app/components/Views/confirmations/SendFlow/Confirm/index.js:443]: This one is for send, in case we are skipping it for DAPP transactions I think its ok we skip it for sends also

Comment (bschorchit) [reply app/components/Views/confirmations/SendFlow/Confirm/index.js]: Sounds good to me

**Review by OGPoyraz — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]

**Review by digiwand — APPROVED** [review]
