### PR TITLE
fix: Perps chart viewport breaking when revisiting a candle interval

### LINKED ISSUE #29232: [Bug]: Chart is flickering, sometimes displaying only 10 candles
### Describe the bug

The chart is flickering between only 10 candles and sometimes expected behavior.
It seems to happen every time we select >2h candle period

### Expected behavior

Display the right number of candles, no flickering

### Screenshots/Recordings

https://github.com/user-attachments/assets/f8a78541-8f93-4ecc-823b-898619ebadb7

### Steps to reproduce

1. Go to perps
2. Open a market, ex: BTC
3. Observe the chart

### Error messages or log output

```shell

```

### Where was this bug found?

Internal release testing

### Version

7.74

### Build number

4609

### Build type

None

### Device

iphone 11

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by gambinish**
## **Description**

Fixes a bug where the Perps trading chart's viewport would break, flicker, or "jump between views" when navigating back to a previously visited candle interval (e.g. 4h → 8h → 4h). The first visit to an interval worked correctly, but revisits would render the wrong zoom, drop candles older than the visible range, and reset continuously on every live tick.

**Root causes**
There were two independent bugs compounding each other:

1. Cache was overwritten on revisit, shrinking the dataset
In CandleStreamChannel, the first visit to an interval fetches OneWeek of candles (~42 for 4h). On revisit, we intentionally do a lighter OneDay refetch (~6 candles) to conserve rate limit budget. However, the subscription callback was doing a full cache.set(cacheKey, incoming) — replacing the cached 42 candles with only 6.

When that shrunken dataset propagated to the WebView, TradingView's stored visible range pointed outside the new data, causing the viewport to collapse and candles older than the visible window to disappear.

2. Every live tick triggered a full chart reset
In TradingViewChart, every new candleData prop (including live ticks) sent SET_CANDLESTICK_DATA to the WebView, which called candlestickSeries.setData(fullDataset). setData is a destructive operation that resets the chart's internal state. On revisit this collided with the shrunken-cache propagation, producing the flicker and zoom reset the user experienced.

**Changes**

CandleStreamChannel.ts — merge instead of replace
- Added a static mergeCandleData helper that merges incoming candles into the cached dataset by timestamp (incoming wins on overlapping times, older cached candles are preserved), capped at 1000 candles to prevent unbounded growth.
- Updated the subscribeToCandles callback in connectNow to merge instead of replace, so a lighter refetch on revisit no longer drops history.

TradingViewChart.tsx — route live ticks to an incremental path
- Added a lastSentSignatureRef that tracks { symbol, interval, firstTime, count, lastTime } of the last dataset sent to the WebView.
- `SET_CANDLESTICK_DATA` (full reload) for initial load, symbol/interval change, history prepend, count decrease, or multi-bar jump.
- `UPDATE_LAST_CANDLE` (incremental, 1–2 candles) for live ticks and single-bar appends on the same symbol/interval/firstTime.
- `CHART_READY` clears the signature so a WebView remount always forces a full reload.
- `CLEAR_DATA` clears the signature so the next send is a full reload (empty chart can't be incrementally updated).

TradingViewChartTemplate.tsx — handle incremental updates
- Added a new UPDATE_LAST_CANDLE message handler that calls candlestickSeries.update(candle) for each candle in the payload, keeps window.allCandleData in sync, mirrors the update on the volume series, and refreshes Y-axis decimal precision without touching the visible range or zoom.

## **Changelog**

CHANGELOG entry: fixes bug related to chart re-rendering and flickering

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/29232 https://consensyssoftware.atlassian.net/browse/TAT-2973

## **Manual testing steps**

```gherkin
Feature: Perps chart interval revisit
  Scenario: User revisits a previously loaded candle interval
    Given the user has loaded the Perps chart on the 4h interval
    And the user has switched to the 8h interval
    When the user switches back to the 4h interval
    Then the chart renders with its full candle history preserved
    And the viewport stays zoomed to the same visible range as before
    And no skeleton loader or flicker is shown
  Scenario: User receives a live tick on a revisited interval
    Given the user is viewing the Perps chart on a revisited interval
    And the chart is fully rendered with live data
    When a live candle tick arrives
    Then only the last candle is updated in place
    And the chart's visible range and zoom remain unchanged
    And no full chart reload occurs
  Scenario: User returns after a new candle has closed
    Given the user has loaded the Perps chart on the 4h interval
    And the user has been away long enough for at least one new 4h bar to close
    When the user switches back to the 4h interval
    Then the chart reloads with the merged history and the new bars
    And the chart re-zooms cleanly to the latest candles
    And no older candles are dropped from view
  Scenario: User switches to a different symbol
    Given the user is viewing the Perps chart for BTC
    When the user navigates to the chart for ETH
    Then the chart performs a full reload with the new symbol's data
    And the previous symbol's candles are not shown
```

### **Before**

https://github.com/user-attachments/assets/9d56fd25-ad48-404e-a921-7a9eeb85763f

### **After**

https://github.com/user-attachments/assets/86f0bdcc-ab85-4f2f-877d-d4c187534222

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I've included tests if applicable
- [x] I've documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I've applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

#### Performance checks (if applicable)

- [ ] I've tested on Android
  - Ideally on a mid-range device; emulator is acceptable
- [ ] I've tested with a power user scenario
  - Use these [power-user SRPs](https://consensyssoftware.atlassian.net/wiki/spaces/TL1/pages/edit-v2/401401446401?draftShareId=9d77e1e1-4bdc-4be1-9ebb-ccd916988d93) to import wallets with many accounts and tokens
- [ ] I've instrumented key operations with Sentry traces for production performance metrics
  - See [`trace()`](/app/util/trace.ts) for usage and [`addToken`](/app/components/Views/AddAsset/components/AddCustomToken/AddCustomToken.tsx#L274) for an example

For performance guidelines and tooling, see the [Performance Guide](https://consensyssoftware.atlassian.net/wiki/spaces/TL1/pages/400085549067/Performance+Guide+for+Engineers).

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

---

> [!NOTE]
> **Medium Risk**
> Touches candle caching/merging and the WebView messaging path used to render the Perps chart; mistakes could cause stale/incorrect candles, memory growth, or regress zoom/viewport behavior across symbols/intervals.
> 
> **Overview**
> Fixes Perps chart flicker/viewport jumps when revisiting candle intervals by **preserving candle history in cache** and **avoiding full chart resets on every tick**.
> 
> `CandleStreamChannel` now merges incoming candle updates into the existing cached dataset (timestamp-based, incoming wins) and caps cached history at `1000` candles, notifying subscribers with the merged result instead of replacing the cache.
> 
> `TradingViewChart` introduces signature-based routing to send either a full `SET_CANDLESTICK_DATA` reload (initial load, symbol/interval/history changes, WebView remount, or cleared data) or an incremental `UPDATE_LAST_CANDLE` message (live ticks / single-bar append, sending only the last 1–2 candles). The WebView template adds an `UPDATE_LAST_CANDLE` handler that applies `series.update()` and keeps internal candle/volume state in sync.
> 
> Adds focused regression tests for both the incremental update routing (`TradingViewChart.incremental.test.tsx`) and the candle cache merge invariants (`CandleStreamChannel.test.ts`).
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 91eaa5d4005bf3b1d3f534201811a734d3f2fa13. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: app/components/UI/Perps/providers/channels/CandleStreamChannel.ts [hunk 1]
```diff
@@ -126,8 +126,62 @@ export class CandleStreamChannel extends StreamChannel<CandleData> {
...
+   * for in-progress bars and final values for closed bars). Older cached
+   * candles outside the incoming range are preserved so a light refetch
+   * (e.g. OneDay on revisit) does not shrink the dataset that previously
+   * contained a longer history (e.g. OneWeek).
+   *
+   * Without this merge, `cache.set(cacheKey, incoming)` on revisit drops every
+   * candle older than the refetch window — the "candles before the visible
+   * range disappear" bug when switching between intervals.
+   */
+  private static mergeCandleData(
```
Comment (geositta) [inline app/components/UI/Perps/providers/channels/CandleStreamChannel.ts:147]: Please add a describe('mergeCandleData', …) block before merging; since this part appears to be the more regression prone part of the change.   

Incoming candles win on overlapping timestamps

Older cached candles outside the incoming range are preserved (the One  Week-> One Day revisit case the PR is fixing).     
                      
Result is sorted ascending by time.

Cap at MAX_CACHED_CANDLES keeps the newest window.
                    
Symbol/interval mismatch falls back to incoming (defensive branch).

**Review by geositta — COMMENTED** [review]
I tested, looks good, could we add some unit tests for CandleStreamChannel.mergeCandleData ?

File: app/components/UI/Perps/providers/channels/CandleStreamChannel.ts (hunk 1 above)
Comment (gambinish) [reply app/components/UI/Perps/providers/channels/CandleStreamChannel.ts:147]: https://github.com/MetaMask/metamask-mobile/pull/29344/commits/c4eabc027525f20f96058a12284428719b3dd762

**Review by geositta — APPROVED** [review]
