### PR TITLE
Fix: deeplink intrinsic gas issue

### LINKED ISSUE #4853: Deeplinks/QR transfer scans no longer estimate the needed gas limit: "intrinsic gas too low"
**Describe the bug**
Previously, when opening an ERC20 transfer deeplink the gas limit would be estimated, allowing users to "just click" send.  Now, when a user opens an ERC20 transfer, the gas limit is set to the default of 21000, which is far too low.  Thus, when clicking send, they get an "intrinsic gas too low" error, as metamask knows the tx would fail so does not send it (Thanks there :D ).  What should be happening is the gas is set to something like 75k depending on the complexity of a contract's transfer function.

I'm pretty familiar with the EIP-681 standard, so I took a stab at using the query params "gasLimit" and "gas" in the deeplink to at least fix this for my users temporarily.  Luckily for me, "gas" is accepted in the deeplink and QR scanning formats (though gasLimit is not, and per the 681 standard, should be).  But with this solution, users have to pay more gas than they need to up front since I had to set it to a high default.

The desired UX is that gas estimation is always done if gas or gasLimit is not specified in the link.  This currently works when you click send on a token, so the functionality exists already within the app.

**Screenshots**
image

**To Reproduce**
_Steps to reproduce the behavior_
1. Create a deeplink for an ERC20 transfer https://metamask.github.io/metamask-deeplinks/#
2. Open it using a mobile device
3. Try to send the transaction without editing gas parameters
4. See it fail

**Expected behavior**
1. Open a deeplink for an ERC20 transfer
2. MetaMask looks up the token contract and estimates gas needed
3. User clicks send, it works as the gas was estimated correctly

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro,
 - OS: 15.6
 - App Version v5.5.0 (939)

Same behavior reproduced on some of my colleagues phones as well, will update with their info if needed.

PS:

I work at https://flexa.network/ , we're a digital assets payments firm.  We'd love to establish closer relationships with wallet organizations like MetaMask.  You can reach me at paul@flexa.co !  We're building a way for wallet developers to embed a top notch payment experience within their app that's usable at tens of thousands of stores, as well as some of the biggest crypto conferences like Consensus.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by segun**
**Description**

**Describe the bug**
Previously, when opening an ERC20 transfer deeplink the gas limit would be estimated, allowing users to "just click" send.  Now, when a user opens an ERC20 transfer, the gas limit is set to the default of 21000, which is far too low.  Thus, when clicking send, they get an "intrinsic gas too low" error, as metamask knows the tx would fail so does not send it (Thanks there :D ).  What should be happening is the gas is set to something like 75k depending on the complexity of a contract's transfer function.

I'm pretty familiar with the EIP-681 standard, so I took a stab at using the query params "gasLimit" and "gas" in the deeplink to at least fix this for my users temporarily.  Luckily for me, "gas" is accepted in the deeplink and QR scanning formats (though gasLimit is not, and per the 681 standard, should be).  But with this solution, users have to pay more gas than they need to up front since I had to set it to a high default.

The desired UX is that gas estimation is always done if gas or gasLimit is not specified in the link.  This currently works when you click send on a token, so the functionality exists already within the app.

**Screenshots**
Before

image

After

image

**Issue**
Fixes #4853
Progresses/Fixes

- #6505 
- #6490 

**NOTE**
The issue is basically that the gas fees are not being calculated properly. This solution makes sure the gas fees are properly calculated. 

When the suggested gas fee is 21000, the transaction will fail with intrinsic gas too low. But when the gas is properly calculated, it's usually above 21000.

But even after this solution, on the confirm screen there's usually a brief moment (during my testing like 1 to 3 seconds) where the Send button is active while the gas fee is 21000. 

I'm not sure how to fix this short of hardcoding suggestedGas * 2 when suggestedGas <= 21000.

**To Reproduce**
_Steps to reproduce the behavior_
1. Create a deeplink for an ERC20 transfer https://metamask.github.io/metamask-deeplinks/#
2. Open it using a mobile device
3. Try to send the transaction without editing gas parameters
4. See it fail

**Checklist**

* [x ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

File: app/components/UI/TransactionReview/TransactionReviewEIP1559Update/index.tsx [hunk 1]
```diff
@@ -84,7 +84,11 @@ const TransactionReviewEIP1559Update = ({
       updateTransactionState(gasTransaction);
     }
     // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, [gasEstimationReady, updateTransactionState]);
+  }, [
+    gasEstimationReady,
+    updateTransactionState,
+    gasTransaction.suggestedGasLimit,
```
Comment (blackdevelopa) [inline app/components/UI/TransactionReview/TransactionReviewEIP1559Update/index.tsx:90]: We should be able to destructure `suggestedGasLimit` out of gasTransaction after line 79.

**Review by blackdevelopa — APPROVED** [review]

**Review by digiwand — APPROVED** [review]

**Comment by seaona** [comment]
@segun great job! I can see the 2 issues fixed. The 2 issues can be closed now


https://github.com/MetaMask/metamask-mobile/assets/54408225/77b8d6e6-7955-4145-8535-f0ac03b2c05b
