### PR TITLE
fix: ensure inpage provider retries any pending requests sent before BackgroundBridge fully initialized

### LINKED ISSUE #15664: [Bug]: Can't switch accounts from Uniswap, transaction submitted with incorrect account, while notification and account icon suggest the tx is being submitted on the correct account
### Describe the bug

1. Select account 1 in the wallet
2. Connect to account 1 with Uniswap
3. Give permissions to account 2 from Uniswap
4. Switch to account 2 from Uniswap
5. Observe the notification, account icon and the homescreen being switched to the account 2
6. Create a transaction from the dapp
7. Observe that notification displayed previously selected account
8. Tx submitted on account 1

### Expected behavior

Transaction submitted on the selected account

### Screenshots/Recordings

https://github.com/user-attachments/assets/f0d292c3-bd00-43e2-b57b-2dab76e7002f

### Steps to reproduce

1. See the description

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.47.0 (1864)

### Build type

None

### Device

Samsung S24 Ultra

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by jiexi**
## **Description**

Fixes a race condition in Android builds that made it highly likely for the inpage provider to end up in an "uninitialized" state when loading a BrowserTab for the first time after fresh app start. This was a result of the provider's [metamask_getProviderState](https://github.com/MetaMask/providers/blob/5b3055f06290ca6b865e1af339c8e14b5ed032b4/src/StreamProvider.ts#L114-L116) request used to initialize the provider state never resolving if the request was sent before BackgroundBridge had fully initialized its own EIP-1193 JSON-RPC engine pipeline. The provider would end up in a semi-functional state where subsequent requests could continue to be made, but `chainChanged` and `accountsChanged` events would [not get emitted to the dapp](https://github.com/MetaMask/providers/blob/main/src/BaseProvider.ts#L461-L463) despite the wallet sending and the inpage provider receiving both `metamask_chainChanged` and `metamask_accountsChanged` events.

This does not seem to affect iOS although the bug should also exist there.

The solution was to copy the retry triggering logic that already exists in [Extension](https://github.com/MetaMask/metamask-extension/blob/6e4bcfd1ed61bc4c80fc5b5eaffe114370dee914/app/scripts/streams/provider-stream.ts#L336-L357).

It is questionable, both in Extension and Mobile, whether this needs to be triggered by `metamask_chainChanged` or if the background can send `METAMASK_EXTENSION_CONNECT_CAN_RETRY` directly after JSON-RPC pipelines are initialized. I've decided to simply mimic Extension for sake of parity and consistency for future maintainers.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15664

## **Manual testing steps**

Unsure, but you may need many many accounts

1. Restart the **Android** app (i.e. swipe it away and launch it again)
2. Open the in app browser
3. Go to any webpage
4. In your desktop chrome, visit `chrome://inspect/#devices`
5. Open the debugger for the webview you opened in the mobile app browser
6. In console, enter `window.ethereum._state`
7. `initialized` property should be `true`

Optionally, try the repro steps in the linked bug ticket which should no longer show the incorrect first account in the confirmation after you have switched the selected account from your first account to the second account.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Unik0rnMaggie** [comment]
Hi Team,

Using the QA builds from [here](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/b8631806-2b9f-4d33-88a0-2f06646414cb) the fix works for both iOS and Android:


https://github.com/user-attachments/assets/16fdfa2c-3e18-4f74-b5bf-08e0e6866d19


https://github.com/user-attachments/assets/c6e9ab34-d7fc-4fae-a25e-ec032490e372


Issues not related to the bug, but observed while testing this PR:

- Base network shows as Private Network in the network picker if Current network is selected
- Swap estimation error in the confirmation request
- Unable to add `space` when trying to import SRP and typing it (for both iOS and Android)


https://github.com/user-attachments/assets/3f4dc0d4-2c83-4a23-a06b-60e499a8c8f6

**Review by Cal-L — COMMENTED** [review]
Do you think  this can be a bug with remote connections as well? (WC and SDK).

**Comment by jiexi** [comment]
> Do you think this can be a bug with remote connections as well? (WC and SDK).

Based on the code i see for SDK, it seems this bug may also exist with SDK, but i'm not entirely sure. In the case that SDK is being used by a dapp in the in-app browser, the fix in this PR would also cover the SDK (after we loosen the remoteConn guard).

**Comment by sleepytanya** [comment]
I can't replicate the bug in QA and Release build:

release Android build https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/2ae5c97335fd122e


https://github.com/user-attachments/assets/3d8aa25c-b002-4c35-9066-c4f20243c9a7



https://github.com/user-attachments/assets/07c71621-63bb-4d4c-852c-829eee5d8f40

File: scripts/inpage-bridge/src/provider.js [hunk 1]
```diff
@@ -10,6 +10,8 @@ const CONTENT_SCRIPT = 'metamask-contentscript';
 const PROVIDER = 'metamask-provider';
 const MULTICHAIN_PROVIDER = 'metamask-multichain-provider';
 
+let METAMASK_CONNECT_SENT;
```
Comment (adonesky1) [inline scripts/inpage-bridge/src/provider.js]: could we add a comment explaining what this variable is? I also generally reserve the UPPERCASE_FORMAT for hardcoded constants?

File: scripts/inpage-bridge/src/provider.js [hunk 2]
```diff
@@ -113,6 +116,37 @@ function logStreamDisconnectWarning(remoteLabel, err) {
...
+    !METAMASK_CONNECT_SENT &&
+    msg.data.method === 'metamask_chainChanged'
+  ) {
+    METAMASK_CONNECT_SENT = true;
+    window.postMessage(
+      {
+        target: INPAGE, // the post-message-stream "target"
+        data: {
+          // this object gets passed to object-multiplex
+          name: PROVIDER, // the object-multiplex channel name
```
Comment (adonesky1) [inline scripts/inpage-bridge/src/provider.js]: nit
```suggestion
        target: INPAGE,
        data: {
          name: PROVIDER,
```

**Review by adonesky1 — COMMENTED** [review]
few small reqs

File: scripts/inpage-bridge/src/provider.js (hunk 2 above)
Comment (jiexi) [reply scripts/inpage-bridge/src/provider.js]: resolved here https://github.com/MetaMask/metamask-mobile/pull/16349/commits/a65d0c3fb2cf2c8897609efddb131226b054eb72

File: scripts/inpage-bridge/src/provider.js (hunk 1 above)
Comment (jiexi) [reply scripts/inpage-bridge/src/provider.js]: good point. copied these over from extension. resolved here https://github.com/MetaMask/metamask-mobile/pull/16349/commits/a65d0c3fb2cf2c8897609efddb131226b054eb72

**Review by adonesky1 — DISMISSED** [review]
LGTM!

File: .detoxrc.js [hunk 3]
```diff
@@ -37,6 +37,17 @@ module.exports = {
...
+        rootDir: "./artifacts",
+        plugins: {
+          screenshot: {
+            shouldTakeAutomaticSnapshots: true,
+          },
+          video: {
+            enabled: true,  // Enable video recording
+          },
+        },
+      }
```
Comment (jiexi) [inline .detoxrc.js]: this needs to be removed before merge

**Review by abretonc7s — DISMISSED** [review]

File: app/core/BackgroundBridge/BackgroundBridge.js [hunk 4]
```diff
@@ -240,6 +240,12 @@ export class BackgroundBridge extends EventEmitter {
     }
 
     this.on('update', () => this.onStateUpdate());
+    // Ensures the inpage provider receives a message indiciating background liveliness
+    // so that messages sent before BackgroundBridge's EIP-1193 JSON-RPC pipeline was
+    // fully initialized can be retried
+    if (!this.isRemoteConn && !this.isWalletConnect) {
```
Comment (jiexi) [inline app/core/BackgroundBridge/BackgroundBridge.js:246]:
```suggestion
    if (!this.isWalletConnect) {
```

**Review by Gudahtt — APPROVED** [review]
LGTM!
