### PR TITLE
fix: cp-7.51.0 add missing base notification properties

### LINKED ISSUE #17274: [Bug]: Open notification crashes the app
### Describe the bug

send ETH from a standard account to a smart account, then I switch to the smart account and click on the relevant notification it still crashes the app.

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Send eth from a smart account to eth account
2. Switch to smart account
3. Press notification
4. should open notification (not crash)

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.51.0

### Build type

None

### Device

Iphone

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## **Description**

During our migration to a centralised source, we missed the base network in our configs.
I'll create a followup PR to add these missing config fields.

## **Changelog**

CHANGELOG entry: add missing base network properties

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/17274

## **Manual testing steps**

1. Enable notifications
2. Create a base ETH sent/received notification (send the native token between accounts)
3. Check notifications after refreshing.

### **After**

https://www.loom.com/share/c58196388cb04e008f57ed988f038988?sid=4ad95fb3-af6c-4b76-a1d9-c3fe1e98220f

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/notifications/methods/common.ts [hunk 1]
```diff
@@ -346,7 +346,7 @@ export const sortNotifications = (
 };
 
 type KnownChainIds =
-  (typeof NOTIFICATION_CHAINS_ID)[keyof typeof NOTIFICATION_CHAINS_ID];
+  (typeof NOTIFICATION_CHAINS_ID)[keyof typeof NOTIFICATION_CHAINS_ID] | '8453';
```
Comment (Prithpal-Sooriya) [inline app/util/notifications/methods/common.ts]: I will update the core centralised configuration to include these missing properties.
In the future these will be provided by the notification API (so we fully avoid hardcoded configs!)

**Review by oilnam — APPROVED** [review]

File: app/util/notifications/methods/common.ts [hunk 2]
```diff
@@ -346,7 +346,8 @@ export const sortNotifications = (
 };
 
 type KnownChainIds =
-  (typeof NOTIFICATION_CHAINS_ID)[keyof typeof NOTIFICATION_CHAINS_ID];
+  | (typeof NOTIFICATION_CHAINS_ID)[keyof typeof NOTIFICATION_CHAINS_ID]
+  | '8453';
```
Comment (Prithpal-Sooriya) [inline app/util/notifications/methods/common.ts:350]: Fixed in https://github.com/MetaMask/core/pull/6124
Long term we want to get away with hardcoded configs and have our server return this information.

**Comment by Prithpal-Sooriya** [comment]
Failing smoke tests are known and not related to this PR
https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8607cc9e-92e5-45bb-a486-e1ca082121a9

Thread: https://consensys.slack.com/archives/C02U025CVU4/p1752691049283359
