### PR TITLE
Unify Custom Gas Components

### LINKED ISSUE #1834: Gas too low error not showing up on wallet transactions
**Describe the bug**
"Gas price extremely low" error message in custom gas controls is not showing up properly in regular wallet transactions. Does show up in dApp transactions.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### LINKED ISSUE #1885: Padding off on gas modal
**Describe the bug**
There is too much padding on the custom gas modal in the Approve view

**Screenshots**
Screen Shot 2020-10-09 at 6 02 39 PM

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by EtDu**
**Description**

This refactor aims to combine the `CustomGas` components inside `UI` & `SendFlow` to enable better code maintenance and error resolution surrounding gas errors.

**Checklist**

- [x] Remove redundant `TransactionEdit` component
- [x] Create a middle component to handle screen transitions/animations
- [x] Use same `CustomGas` components for Approve & SendFlow/Confirm

https://trello.com/c/TyjdNnRN/228-unify-customgas-components-for-dapp-wallet-txs

fixes #1834
fixes #1885

### CODE REVIEW

**Comment by EtDu** [comment]
@ibrahimtaveras00 QA notes:
- Test the Approve and dApp transaction modals
- Test the wallet send flow

General review notes:
- One diff contains all the animation/transition logic. This can be ignored, as it was simply moved from one location to another.
- Animations for custom gas now work for Approve, dApp transactions and wallet send flow. There are some animations that still need to be implemented at some point for Approve.

File: app/components/UI/AnimatedTransactionModal/index.js [hunk 1]
```diff
@@ -0,0 +1,268 @@
...
+		children: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.node), PropTypes.node]).isRequired
+	};
+
+	state = {
+		originComponent: React.Children.toArray(this.props.children).length > 1 ? 'dapp' : 'wallet',
+		modalValue:
+			React.Children.toArray(this.props.children).length > 1 ? new Animated.Value(1) : new Animated.Value(0),
+		reviewToEditValue: new Animated.Value(0),
+		reviewToDataValue: new Animated.Value(0),
+		editToAdvancedValue: new Animated.Value(0),
```
Comment (estebanmino) [inline app/components/UI/AnimatedTransactionModal/index.js:54]: any specific reason these are on state? I think this could be done under a component variable, there's no need to update this on state

Comment (estebanmino) [reply app/components/UI/AnimatedTransactionModal/index.js:54]: `reviewToEditValue`,`reviewToDataValue` and `editToAdvancedValue`

File: app/components/UI/AnimatedTransactionModal/index.js [hunk 2]
```diff
@@ -0,0 +1,268 @@
...
+						generateTransform: this.generateTransform,
+						animate: this.animate,
+						saveTransactionReviewDataHeight: this.saveTransactionReviewDataHeight,
+						onModeChange: this.onModeChange
+					})}
+				</Animated.View>
+
+				{ready && (
+					<Animated.View style={[styles.transactionEdit, this.generateTransform('reviewToEdit', [width, 0])]}>
+						{React.cloneElement(components[1], {
```
Comment (estebanmino) [inline app/components/UI/AnimatedTransactionModal/index.js:208]: I see you checked for components length to define some properties, us this always defined?

File: app/components/UI/CustomGas/index.js [hunk 3]
```diff
@@ -317,6 +316,39 @@ class CustomGas extends PureComponent {
...
+	};
+
+	//Validate locally instead of in TransactionEditor, otherwise cannot change back to review mode if insufficient funds
+	hasSufficientFunds = (gas, gasPrice) => {
+		const {
+			transaction: { from, value }
+		} = this.props;
+		const checksummedFrom = safeToChecksumAddress(from) || '';
+		const fromAccount = this.props.accounts[checksummedFrom];
+		if (hexToBN(fromAccount.balance).lt(gas.mul(gasPrice).add(toBN(value))))
```
Comment (estebanmino) [inline app/components/UI/CustomGas/index.js:347]: I think if checksummedFrom is '' this is going to crash

File: app/components/UI/AnimatedTransactionModal/index.js [hunk 4]
```diff
@@ -0,0 +1,268 @@
...
+	},
+	transactionReview: {
+		paddingTop: 24
+	}
+});
+
+/**
+ * PureComponent that handles most of the animation/transition logic
+ */
+class AnimatedTransactionModal extends PureComponent {
```
Comment (estebanmino) [inline app/components/UI/AnimatedTransactionModal/index.js:28]: I'm a bit confused about this component's utility. This only handles animations right?

File: app/components/UI/AnimatedTransactionModal/index.js [hunk 5]
```diff
@@ -0,0 +1,268 @@
...
+
+		return (
+			<Animated.View
+				style={[styles.root, this.generateTransform('modal', [70, 0]), { height: customGasHeight + 70 }]}
+			>
+				{ready && (
+					<Animated.View
+						style={[styles.transactionEdit, this.generateTransform('reviewToEdit', [0, -width])]}
+					>
+						{React.cloneElement(customGasComponent, {
```
Comment (estebanmino) [inline app/components/UI/AnimatedTransactionModal/index.js:240]: I think there's an opportunity to deduplicate code from https://github.com/MetaMask/metamask-mobile/pull/1860/files#diff-35ecbe8bc085d0b73e845cb41c95ce841926077dd9a17254b10d1e54e419c2d0R208

File: app/components/UI/AnimatedTransactionModal/index.js (hunk 1 above)
Comment (EtDu) [reply app/components/UI/AnimatedTransactionModal/index.js:54]: Cool, updated

File: app/components/UI/AnimatedTransactionModal/index.js (hunk 2 above)
Comment (EtDu) [reply app/components/UI/AnimatedTransactionModal/index.js:208]: That's a good point, if you don't pass down children it will be undefined. I've added some optional chaining to fix this

File: app/components/UI/CustomGas/index.js (hunk 3 above)
Comment (EtDu) [reply app/components/UI/CustomGas/index.js:347]: I don't know why that's there, removed

File: app/components/UI/AnimatedTransactionModal/index.js (hunk 4 above)
Comment (EtDu) [reply app/components/UI/AnimatedTransactionModal/index.js:28]: Yeah, the idea is to contain all the animation logic in this component to keep it clean and aintainable, instead of having it scattered throughout other components

File: app/components/UI/AnimatedTransactionModal/index.js (hunk 5 above)
Comment (EtDu) [reply app/components/UI/AnimatedTransactionModal/index.js]: Good point, done

**Review by estebanmino — APPROVED** [review]

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
**Issue 1:**

In send flow, when I change from slow/average/fast and return to the modal it always defaults to average (this works in dapp gas modal) seen here = https://recordit.co/cP8kdpTdYx

**Issue 2:**

On android, I cannot save when editing advanced gas on neither send flow, nor dapp flow; seen here = https://recordit.co/qmCV4qqjCa

**Comment by EtDu** [comment]
Issue 1 is fixed.
For issue 2, I couldn't figure out why the button is disabled.

**Review by ibrahimtaveras00 — APPROVED** [review]
QA Passed 👍
