### PR TITLE
fix: Add dark mode to storybook

### LINKED ISSUE #8683: [Bug]: Storybook does not render dark mode
### Describe the bug

Switching to dark/light mode in the Storybook changes the Storybook UI elements but does not change the story canvas and its components. There's no Add-on on the UI to switch the component theme to dark/light mode either.

### Expected behavior

When switching to dark mode, the story canvas and the components being presented change to dark mode.

### Screenshots/Recordings

storybook

### Steps to reproduce

1. Go to storybook (follow instruction at `storybook/DOCUMENTATION_GUIDELINES.md`)
2. Switch device to dark/light mode
3. Canvas won't change

### Error messages or log output

_No response_

### Version

7.17

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

iPhone Simulator

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by brianacnguyen**
## **Description**
This PR adds dark mode OS toggle on storybook

## **Related issues**

Fixes: #8683 

## **Manual testing steps**

1. Go to storybook
2. View any component
3. Toggle appearance on emulator

### **After**

https://github.com/MetaMask/metamask-mobile/assets/14355083/615f5a60-81da-45a7-95f4-b90a741166d3

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/component-library/providers/ThemeProvider.tsx [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+          backgroundColor: theme.colors.background.alternative,
+        }}
+      >
+        {children}
+      </View>
+    </ThemeContext.Provider>
+  );
+};
+
+export default ThemeProvider;
```
Comment (georgewrmarshall) [inline app/component-library/providers/ThemeProvider.tsx:26]: Are there plans to use this else where in the application or is specifically for storybook if so should it live in the `.storybook/` folder?

**Review by georgewrmarshall — COMMENTED** [review]
Looks good! Left one question regarding where the ThemeProvider lives

File: app/component-library/providers/ThemeProvider.tsx (hunk 1 above)
Comment (brianacnguyen) [reply app/component-library/providers/ThemeProvider.tsx:26]: for now it's only used for storybook, but it can potentially be used for test files or other cases as well so I'm putting this here instead. my plan in the future is to try to update the unit tests to test themed styles as well

Comment (georgewrmarshall) [reply app/component-library/providers/ThemeProvider.tsx:26]: OK, I can approve. Can we consolidate how the ThemeProvider currently works? Is there any duplication here?

**Review by georgewrmarshall — DISMISSED** [review]

**Review by wachunei — APPROVED** [review]

**Review by georgewrmarshall — APPROVED** [review]
