### PR TITLE
fix: Flickering permit and decoding simulation values

### LINKED ISSUE #12993: [non-Prod][Bug]: Permit Simulation lag displaying value with decimals
### Describe the bug

Incorrect value shows before value with decimal applied in the Redesign Permit Simulation

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/dc7c5015-811c-4f53-a10b-eb698644c247

### Steps to reproduce

1. Turn on simulation + redesign
2. Go to https://develop.d3bkcslj57l47p.amplifyapp.com/
3. Click Permit button

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.39

### Build type

None

### Device

iPhone 16 Pro

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by digiwand**
## **Description**

Permit Simulation displays value without decimals applied before displaying value with decimals applied.

This PR fixes the issue but introducing an isPending state to display a loader while the token details are being fetched 

Created a new UI to support the loading behavior called AnimatedPulse. This was approved by @SayaGT to be used here. 
Created a follow-up issue to move AnimatedPulse to components-temp later https://github.com/MetaMask/metamask-mobile/issues/13117

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12993

## **Manual testing steps**

1. Request a redesign Permit signature
2. Observe loader and value

### **Before**

https://github.com/user-attachments/assets/dc7c5015-811c-4f53-a10b-eb698644c247

### **After**

https://github.com/user-attachments/assets/e0870c75-b9d6-47c0-96fc-615b23cd62f8

#### Not being used, but if we used react-native Loader component. Instead of this, we are utilizing AnimatedPulse above
https://github.com/user-attachments/assets/fff5d869-19ce-465b-9414-cbb35331763a

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by pedronfigueiredo — DISMISSED** [review]

File: app/components/Views/confirmations/components/Confirm/Info/TypedSignV3V4/Simulation/components/ValueDisplay/ValueDisplay.tsx [hunk 1]
```diff
@@ -139,28 +143,39 @@ const SimulationValueDisplay: React.FC<
...
-                  })}
-                {tokenId && `#${tokenId}`}
-              </Text>
-            </ButtonPill>
+            {
+              isPendingTokenDetails ?
+              (
+                <View style={styles.loaderContainer} testID="simulation-value-display-loader">
+                  <Loader size={'small'} />
+                </View>
```
Comment (jpuri) [inline app/components/Views/confirmations/components/Confirm/Info/TypedSignV3V4/Simulation/components/ValueDisplay/ValueDisplay.tsx:151]: It might be useful to confirm with @SayaGT if this is the loader we should be using for mobile re-designs.

File: app/components/Views/confirmations/hooks/useGetTokenStandardAndDetails.ts [hunk 2]
```diff
@@ -9,31 +9,39 @@ import {
...
-      })) as TokenDetailsERC20;
+      }) as TokenDetailsERC20;
+      isPendingRef.current = false;
+
+      return result;
     }, [tokenAddress]);
 
   if (!details) {
-    return { decimalsNumber: undefined };
+    return { details: { decimalsNumber: undefined }, isPending: isPendingRef.current };
```
Comment (jpuri) [inline app/components/Views/confirmations/hooks/useGetTokenStandardAndDetails.ts:44]: Looks like here change is value of `isPending` should cause a re-render, any reason to prefer `useRef` here ?

Comment (digiwand) [reply app/components/Views/confirmations/hooks/useGetTokenStandardAndDetails.ts:44]: this was the reason I used useRef since I thought useRef avoids rerenders

File: app/components/Views/confirmations/components/Confirm/Info/TypedSignV3V4/Simulation/components/ValueDisplay/ValueDisplay.tsx (hunk 1 above)
Comment (digiwand) [reply app/components/Views/confirmations/components/Confirm/Info/TypedSignV3V4/Simulation/components/ValueDisplay/ValueDisplay.tsx:151]: absolutely, ty @jpuri for the reminder 🙏🏼

**Review by pedronfigueiredo — APPROVED** [review]

**Review by jpuri — APPROVED** [review]

**Comment by jpuri** [comment]
@digiwand : code changes look good, one feedback we should try to high unit test coverage in new code that we are adding for confirmations.
