### PR TITLE
fix: cp-7.55.0 UI flickering and ENS name resolution in contact form

### LINKED ISSUE #19117: [Bug]: ENS name not resolved while adding contacts
### Describe the bug

ENS name resolution seems to not be working while adding contacts

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/f085ced6-e5dd-4b3b-9fe7-6b714521967e

### Steps to reproduce

1. Go to Settings > contacts
2. Add a new contact with an ens name like vitalik.eth

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.55.0

### Build type

None

### Device

iPhone 15

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by mathieuartu**
## **Description**

This PR fixes UI flickering in the contact form address input when users type or erase text quickly. It debounces address validation and immediately clears stale ENS state. It also fixes the text color in the network selector.

## **Changelog**

CHANGELOG entry: Fixed UI flickering in the contact form address input

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/19117

## **Manual testing steps**

```gherkin
Feature: Add contact form

  Scenario: user types an ENS address
    Given any previous address present in the form

    When user types an ENS address
    Then no flickering happens, and the address resolution succeeds
```

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/Views/Settings/Contacts/ContactForm/index.js [hunk 1]
```diff
@@ -298,8 +309,21 @@ class ContactForm extends PureComponent {
...
 
   onChangeAddress = (address) => {
-    this.validateAddressOrENSFromInput(address);
-    this.setState({ address });
+    this.setState({
+      address,
+      toEnsName: null,
+      toEnsAddress: null,
+      addressError: null,
+      addressReady: false,
```
Comment (fabiobozzo) [inline app/components/Views/Settings/Contacts/ContactForm/index.js:317]: Long story short, they kept the previous state?

File: app/components/Views/Settings/Contacts/ContactForm/index.js [hunk 2]
```diff
@@ -298,8 +309,21 @@ class ContactForm extends PureComponent {
...
+    });
+
+    if (this.validationTimeoutId) {
+      clearTimeout(this.validationTimeoutId);
+    }
+
+    this.validationTimeoutId = setTimeout(() => {
+      this.validateAddressOrENSFromInput(address);
+    }, 300);
```
Comment (fabiobozzo) [inline app/components/Views/Settings/Contacts/ContactForm/index.js:326]: And here you're debouncing it, right? 🙌 
Nit: is there a constant for that timeout instead of hardcoded?

**Review by fabiobozzo — APPROVED** [review]
LGTM

File: app/components/Views/Settings/Contacts/ContactForm/index.js (hunk 1 above)
Comment (mathieuartu) [reply app/components/Views/Settings/Contacts/ContactForm/index.js:317]: Yes, there were race conditions when both typing and erasing, and when the ENS method resolved, it rolled back those values

File: app/components/Views/Settings/Contacts/ContactForm/index.js (hunk 2 above)
Comment (mathieuartu) [reply app/components/Views/Settings/Contacts/ContactForm/index.js:326]: This didn't seem to warrant a constant to me as what we do here is fairly understandable when reading 😄

**Review by n3ps — APPROVED** [review]
