### PR TITLE
fix: cp-7.47.0 fix error when navigating to asset details from bridge/swap

### LINKED ISSUE #15407: [Bug]: App crashes when selecting token details tooltip in dest token selector
### Describe the bug

While using the Bridge feature, tapping on the info/tooltip icon next to a destination token in the selector causes the app to crash.

The crash is due to an unhandled reference to multichainAssetRates.rate in the Price.tsx file. 

### Expected behavior

_No response_

### Screenshots/Recordings

https://github.com/user-attachments/assets/87651f7a-d9e6-450e-bfd9-4ca930dfe96d

### Steps to reproduce

Go to the Bridge screen.

Open the destination token selector.

Tap the info (ℹ️) tooltip icon next to any token.

Observe that the app crashes immediately.

### Error messages or log output

```shell

```

### Detection stage

On main branch

### Version

7.47.0

### Build type

Flask

### Device

iPhone 16 Pro

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### LINKED ISSUE #15582: [Bug]: Tried to swap USDC for JLP: I searched JLP token with the contract address, click on the JLP token tooltip in the swap destination token selector, and the app crash
### Describe the bug

Tried to swap USDC for JLP: I searched JLP token with the contract address, click on the JLP token tooltip in the swap destination token selector, and the app crash

Without clicking on the tooltip, I can initiative a swap, but the JLP token address displayed below the destination token logo has a different format than other solana tokens: it doesn't start with "solana..."

### Expected behavior

_No response_

### Screenshots/Recordings

Image

Image

### Steps to reproduce

1. Navigate to swaps and try to swap USDC for JLP, 
2. Observe that when trying to swap USDC for JLP: I searched JLP token with the contract address, click on the JLP token tooltip in the swap destination token selector, and the app crash

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.47 (1871)

### Build type

None

### Device

Mobile

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

PR fixes couple identified issues when the user attempts to swap/bridge and clicks on the "i" icon to view asset details page.

Related core PR: https://github.com/MetaMask/core/pull/5833

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/15407
Fixes: https://github.com/MetaMask/metamask-mobile/issues/15582

## **Manual testing steps**

Swap scenario

1. Select solana
2. Click on the button in the buttom middle of the screen
3. Click on Swap
4. Click on the pre-filled "to" asset
5. Click on the "i" icon that appears in front of any other token
6. You should be redirected to the asset details page successfully

Bridge scenario starting on EVM network

1. Select Ethereum EVM network
2. Click on the button in the buttom middle of the screen
3. Click on Bridge
4. Click on bridge to
5. Choose solana
6. Click on the "i" icon that appears in front of any other token
7. You should be redirected to the asset details page successfully

Bridge scenario starting on solana network

1. Select Solana
2. Click on the button in the buttom middle of the screen
3. Click on Bridge
4. Click on bridge to
5. Choose Ethereum
6. Click on the "i" icon that appears in front of any other token
7. You should be redirected to the asset details page successfully

### **After**

Swap scenario:

https://github.com/user-attachments/assets/c8ba4527-12c2-431e-acb9-f4e898932734

Bridge scenario:

https://github.com/user-attachments/assets/2a6d5951-55cd-4c37-bf76-8ca1aa46c483

https://github.com/user-attachments/assets/7cdab024-6b89-46e9-b26c-c145bc8c1501

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/components/UI/AssetOverview/Price/Price.tsx [hunk 1]
```diff
@@ -83,7 +83,7 @@ const Price = ({
 
   const price: number = isEvmNetworkSelected
     ? distributedPriceData[activeChartIndex]?.[1] || currentPrice
-    : Number(multichainAssetRates.rate);
+    : Number(multichainAssetRates?.rate);
```
Comment (gambinish) [inline app/components/UI/AssetOverview/Price/Price.tsx:86]: Could this potentially resolve as `NaN`?

File: app/components/UI/AssetOverview/AssetOverview.tsx [hunk 2]
```diff
@@ -91,11 +92,15 @@ const AssetOverview: React.FC<AssetOverviewProps> = ({
   swapsIsLive,
   networkName,
 }: AssetOverviewProps) => {
+  // For non evm assets, the resultChainId is equal to the asset.chainId; while for evm assets; the resultChainId === "eip155:1" !== asset.chainId
+  const resultChainId = formatChainIdToCaip(asset.chainId as Hex);
+  const isNonEvmAsset = resultChainId === asset.chainId ;
```
Comment (sahar-fehri) [inline app/components/UI/AssetOverview/AssetOverview.tsx:97]: Couple components were fetching data from EVM vs Non EVM selectors based on isEvmSelected
Which would work correctly if you are initially on an EVM or non EVM network initially, and then click on one of the assets from the main tokenList.

While in the bridge flow; you can initially be on a NonEVM network; then choose to bridge to an EVM network and naviagate to token details page for an EVM asset. Which meant that relying on "isEvmSelected" is no longer accurate to fetch correct data from correct selectors; hence; changed this to rely on whether the asset that is being clicked on is EVM or non EVM

File: app/components/UI/AssetOverview/Price/Price.tsx (hunk 1 above)
Comment (sahar-fehri) [reply app/components/UI/AssetOverview/Price/Price.tsx:91]: It can, in which case this code https://github.com/MetaMask/metamask-mobile/blob/70a22749f7060657d47c78a36b2dfe555148b57e/app/components/UI/AssetOverview/Price/Price.tsx#L117 handles the case

File: app/components/hooks/useTokenHistoricalPrices.ts [hunk 3]
```diff
@@ -62,32 +63,48 @@ const useTokenHistoricalPrices = ({
...
+  const isNonEvmAsset = resultChainId === asset.chainId;
   const [prices, setPrices] = useState<TokenPrice[]>(placeholderPrices);
   const [isLoading, setIsLoading] = useState(true);
   const [error, setError] = useState<Error>();
+  const lastSelectedNonEvmAccount = useSelector(
+    selectLastSelectedSolanaAccount,
+  );
+
+  // TODO; the asset.address received here is not a CaipAssetType asset when its coming from bridge flow; this is happening because of useTopTokens hook retuning the address for non evm as not a CaipAssetType asset;
+  // TODO; we need to fix this;
```
Comment (sahar-fehri) [inline app/components/hooks/useTokenHistoricalPrices.ts:77]: The item that is being sent in the bridge flow here https://github.com/MetaMask/metamask-mobile/blob/1d8946b7eb2a0a6dc51274a82036c6574463dac7/app/components/UI/Bridge/components/BridgeDestTokenSelector/index.tsx#L51 does not always have the address as CaipAssetType; which was resulting in couple issues when we try to fetch historical prices;
Swaps flow is also affected by this

cc @MetaMask/swaps-engineers

File: app/components/hooks/useTokenHistoricalPrices.ts [hunk 4]
```diff
@@ -62,32 +63,48 @@ const useTokenHistoricalPrices = ({
...
   ///: END:ONLY_INCLUDE_IF
-  const isEvmSelected = useSelector(selectIsEvmNetworkSelected);
+  const resultChainId = formatChainIdToCaip(asset.chainId as Hex);
+  const isNonEvmAsset = resultChainId === asset.chainId;
   const [prices, setPrices] = useState<TokenPrice[]>(placeholderPrices);
   const [isLoading, setIsLoading] = useState(true);
   const [error, setError] = useState<Error>();
+  const lastSelectedNonEvmAccount = useSelector(
+    selectLastSelectedSolanaAccount,
+  );
```
Comment (sahar-fehri) [inline app/components/hooks/useTokenHistoricalPrices.ts:73]: The bridge UI will show token balances for the last selected EVM account or last selected non EVM account.

To be able to call `fetchHistoricalPricesForAsset` the controller tries to call accountsController and get getSelectedMultichainAccount; which will be undefined if the user is initially on an EVM network.
To get around that; we are making a modification to the controller function to accept an optional account as arg, which will be `lastSelectedNonEvmAccount` in the case of a bridge.

There is a case where lastSelectedNonEvmAccount can be undefined, but this will be fixes by swaps team to prompt the user to create a solana account if they are on a bridge UI and they haven't already created one.

**Review by gambinish — APPROVED** [review]

**Review by bfullam — APPROVED** [review]

**Review by Prithpal-Sooriya — APPROVED** [review]

File: app/components/UI/AssetOverview/Price/Price.tsx [hunk 5]
```diff
@@ -51,11 +51,16 @@ const Price = ({
   ///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
   multichainAssetsRates,
   ///: END:ONLY_INCLUDE_IF
-  isEvmNetworkSelected,
+  isEvmAssetSelected,
 }: PriceProps) => {
   ///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
+  const assetAddress = asset.address;
+  const isCaipAssetType = assetAddress.startsWith(`${asset.chainId}`);
```
Comment (tommasini) [inline app/components/UI/AssetOverview/Price/Price.tsx:58]: What do you mean by `isCaipAssetType`?

File: app/components/hooks/useTokenHistoricalPrices.ts [hunk 6]
```diff
@@ -62,32 +63,48 @@ const useTokenHistoricalPrices = ({
...
+
+  // TODO; the asset.address received here is not a CaipAssetType asset when its coming from bridge flow; this is happening because of useTopTokens hook retuning the address for non evm as not a CaipAssetType asset;
+  // TODO; we need to fix this;
```
Comment (tommasini) [inline app/components/hooks/useTokenHistoricalPrices.ts:76]: Is there any issue to address this in the future?

File: app/components/hooks/useTokenHistoricalPrices.ts [hunk 7]
```diff
@@ -62,32 +63,48 @@ const useTokenHistoricalPrices = ({
...
     const fetchPrices = async () => {
       setIsLoading(true);
       try {
-        if (!isEvmSelected) {
+        if (isNonEvmAsset) {
           const caip19Address = asset.address as CaipAssetId;
+          const isCaipAssetType = caip19Address.startsWith(`${asset.chainId}`);
+
+          // TODO; this is a temporary fix to ensure the address is a CaipAssetType asset;
+          const normalizedCaipAssetTypeAddress = isCaipAssetType
```
Comment (tommasini) [inline app/components/hooks/useTokenHistoricalPrices.ts:87]: I get really confused by the `isCaipAssetType`, Do we want to check `isCaipAssetTypeFormat`?

File: patches/@metamask+assets-controllers+62.0.0.patch [hunk 8]
```diff
@@ -1,3 +1,43 @@
...
++++ b/node_modules/@metamask/assets-controllers/dist/MultichainAssetsRatesController/MultichainAssetsRatesController.cjs
+@@ -136,9 +136,10 @@ class MultichainAssetsRatesController extends (0, polling_controller_1.StaticInt
+      * Fetches historical prices for the current account
+      *
+      * @param asset - The asset to fetch historical prices for.
++     * @param account - optional account to fetch historical prices for
+      * @returns The historical prices.
+      */
+-    async fetchHistoricalPricesForAsset(asset) {
++    async fetchHistoricalPricesForAsset(asset, account) {
```
Comment (tommasini) [inline patches/@metamask+assets-controllers+62.0.0.patch:13]: Is there an issue on core or a PR to address this changes? We really should be working to remove the patches

File: app/components/UI/AssetOverview/Price/Price.tsx (hunk 5 above)
Comment (sahar-fehri) [reply app/components/UI/AssetOverview/Price/Price.tsx:58]: This is checking if the item address we got is of type:` CaipAssetType = `${string}:${string}/${string}:${string}``
Noticed that when a user is coming from a bridge/swap flow this is not always the case which was messing with the price chart.
This is not an issue when the user is coming from the main asset list.
As far as i have looked, this is related to useTopTokens hook; i thought it would be a bigger change to fix that; hence the TODO here https://github.com/MetaMask/metamask-mobile/pull/15409#discussion_r2103042103 
Definitely something that would love @MetaMask/swaps-engineers  to help look into as soon as possible;

File: app/components/hooks/useTokenHistoricalPrices.ts (hunk 6 above)
Comment (sahar-fehri) [reply app/components/hooks/useTokenHistoricalPrices.ts:76]: Yes; related to my other comment; i think we need to look more into the useTopTokens and the item type it is sending to the AssetOverview component.
I think we can get this release blocker in first and take more time to properly align the hook with the component later

File: app/components/hooks/useTokenHistoricalPrices.ts (hunk 7 above)
Comment (sahar-fehri) [reply app/components/hooks/useTokenHistoricalPrices.ts:87]: Yes; same happening here https://github.com/MetaMask/metamask-mobile/pull/15409#discussion_r2103203680

File: patches/@metamask+assets-controllers+62.0.0.patch (hunk 8 above)
Comment (sahar-fehri) [reply patches/@metamask+assets-controllers+62.0.0.patch:13]: Yes, the core PR is linked in description https://github.com/MetaMask/core/pull/5833 and been already merged;
Patched just because its a release blocker but we will be upgrading assets very soon to remove this 🙏

**Review by tommasini — APPROVED** [review]
