### PR TITLE
[FIX] Fixes renderFromGwei related crashes

### LINKED ISSUE #3537: Transaction crash caused by undefined or decimal values
**Describe the bug**
Crash that occurs when a value is undefined or a decimal number is passed to the method `renderFromWei`

**Screenshots**
drawing

**To Reproduce**
_Steps to reproduce the behavior_
1. Send a transaction to another account
2. Tap on the notification when the transaction arrives in the devices where the funds were sent
3. A crash should occur

**Expected behavior**
The app should avoid processing undefined and decimal values with web3 methods

### PR DESCRIPTION
**Pull request by andreahaku**
**Description**

Fixes some crashes related to transaction notification info display and others related to calculating/displaying gas fees. The main issue was that calculated gwei where not always integers/string format but could be undefined/decimal crashing the numberToBN method.

**Checklist**

* [X] There is a related GitHub issue
* [X] Tests are included if applicable
* [X] Any added code is fully documented

**Issue**

Resolves #3537

### CODE REVIEW

File: app/components/UI/Notification/TransactionNotification/index.js [hunk 1]
```diff
@@ -209,7 +209,8 @@ function TransactionNotification(props) {
 			const existingGasPrice = new BigNumber(tx?.transaction?.gasPrice || '0x0');
 			const gasFee = existingGasPrice
 				.times(transactionAction === ACTION_CANCEL ? CANCEL_RATE : SPEED_UP_RATE)
-				.toString();
+				.toString()
+				.split('.')[0]; // strips decimals if any, coming from the 'times' operation
 			setGasFee(gasFee);
```
Comment (rickycodes) [inline app/components/UI/Notification/TransactionNotification/index.js:214]: instead of using `.split` we could use `.substring`:

```suggestion
			const gasFeeValue = gasFee.toSrting();
			const [ from, to ] = [ gasFeeValue.indexOf('.'), 0 ];
			const gasFeeSubString = gasFeeValue.substring(from, to);
			setGasFee(gasFeeSubString);
```

the result is the same without having to split the string (an operation that can be costly depending on the situation). I also just find this a bit easier to grok, but maybe that's just me? this could also be a function that's added and tested in the `number/index.js` util (similar to what you do with the creation of `safeNumberToBN`).

File: app/util/number/index.js [hunk 2]
```diff
@@ -447,11 +450,22 @@ export function fiatNumberToWei(fiat, conversionRate) {
...
 }
 
+/**
+ * Wraps 'numberToBN' method to avoid potential undefined and decimal values
+ *
+ * @param {number|string} value -  number
+ * @returns {Object} - The converted value as BN instance
+ */
+export function safeNumberToBN(value) {
+	const safeValue = value?.toString().split('.')[0] || '0';
```
Comment (rickycodes) [inline app/util/number/index.js:465]: same as above

**Review by rickycodes — APPROVED** [review]
LGTM! thanks for working through the suggestions :)

**Review by gantunesr — APPROVED** [review]
🚀 🚀 🚀 🚀

**Comment by gantunesr** [comment]
@andreahaku can you provide steps to reproduce the bug for QA? Please

**Comment by andreahaku** [comment]
> @andreahaku can you provide steps to reproduce the bug for QA? Please

This can be replicated by doing and ETH transaction from one account to another (same wallet or different wallet) and by tapping on any of the popup notification messages confirming the transaction on both the sending and/or receiving wallets/accounts.

**Review by cortisiko — APPROVED** [review]
🌮 🌮 🌮 🌮
