### PR TITLE
fix: Receive page shows 0x prefix for Solana account

### LINKED ISSUE #14771: [Bug]: When I click "Receive" on a Solana account it has the prefix "0x"
### Describe the bug

On mobile - if on a Solana account and I click on "Receive" it opens the Receive dialogue with the QR code however the the address has a prefix with 0x

Image

### Expected behavior

show address without the 0x prefix

### Screenshots/Recordings

Image

### Steps to reproduce

1. Select a Solana account
2. Click on the center bottom button
3. Select Receive

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.45.0

### Build type

None

### Device

Android

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by owencraston**
## **Description**
This PR fixes a bug where the receive page would add a `0x` prefix to Solana addresses. This is invalid for Solana accounts. To fix this I simply swapped out a call from `toChecksumHexAddress` to `toFormattedAddress` which checks if the account is an EVM account before checksumming the address. This function is already widely used in the app, this section was just missed when we made this change. 

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/14771

## **Manual testing steps**

1. Ensure you are building beta by editing the value of `METAMASK_BUILD_TYPE` to be `beta` in your `.js.env` file
2. yarn setup && yarn watch:clean
3. this needs to be tested with a Physical device in order to use the camera permissions. 
4. Build the app on a physical device with expo (see readme for details)
5. create a wallet
6. click on the selected account and then click on add new account or hardware wallet
7. click on solana
8. create a solana account
9. then at the top of the home page, click on the scanner icon

Screenshot_20250424-164821

10. Allow camera permissions
11. then click on the receive tab
12. a QR code should be rendered, along with your full address and the account name which will likely be a shortened version of your address `WITHOUT A 0x PREFIX`

### **Before**

<image src="https://github.com/user-attachments/assets/3f38db9d-8338-4dbd-8d81-fb055ec336db" width="250" height="500">

#### Receive page with Sol account

<image src="https://github.com/user-attachments/assets/73863805-2014-43bf-98d3-683a14373121" width="250" height="500">

#### Address copy is working 

<image src="https://github.com/user-attachments/assets/b2ee2cf3-8a14-45aa-9f0e-3822ea7ae000" width="250" height="500">

#### ETH accounts are still working as expected

<image src="https://github.com/user-attachments/assets/defba664-8552-49a9-85d2-2e565ba97688" width="250" height="500">

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

File: app/util/address/index.ts [hunk 1]
```diff
@@ -136,7 +136,7 @@ export function renderAccountName(
   internalAccounts: InternalAccount[],
 ) {
   const chainId = selectChainId(store.getState());
-  address = toChecksumHexAddress(address);
+  address = toFormattedAddress(address);
```
Comment (owencraston) [inline app/util/address/index.ts:139]: This is all that was needed for the fix.

**Review by vinnyhoward — APPROVED** [review]
LGTM
